### ISSUE TITLE
How to add bounce in my application

### ISSUE THREAD

**Issue by bpareek9694** [postalhq/postal#1000]
Hello Community,

I install postal on my server. it's working fine.

How to add bounce in my application without using Webhooks,

Is there any other way/code to communicate the postal bounce message to my panel?

Please Help me with the same.

**Comment by willpower232** [comment]
Does this answer your question? https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces

**Comment by bpareek9694** [comment]
Thanks for your reply

I've followed your given docs and trying to route the address for the bounce in address point and Http endpoints, have a look in below screenshot
https://prnt.sc/r3yvo5
But still, I am facing the same issue, I also send emails for fetching the bounce, have a look in below screenshot
https://prnt.sc/r3ze23

and does not receive any bounced mail in my bounce email id.

Is there any other way for fetching bounce using Address Endpoint.

**Comment by approached** [comment]
Has your message in the header a **return-path**?

**Comment by willpower232** [comment]
The messages have soft failed, can you show us what the problem is that Postal has recorded?
