### ISSUE TITLE
Unable to grant admin access.

### ISSUE THREAD

**Issue by nuchanardy** [postalhq/postal#1001]
Hi Community,

I have a problem with changing permissions to admin. When I change to the admin role and click the save button.  But it not complete and the user is not updated.

Additional Details:

- Confirmed that I'm already a Postal admin

- The issue occurs in both Firefox and Chrome.

**Comment by willpower232** [comment]
You could use your browsers developer tools to see if there was an error in the network response.

If theres a server error, there should be some mention in the log files.

**Comment by nuchanardy** [comment]
The error received from the network response is 404 not found, as in the picture below. And on the server, there's not show an error.

<img width="1440" alt="Screen Shot 2020-02-18 at 9 17 41 AM" src="https://user-images.githubusercontent.com/27017732/74698484-8c102e80-5230-11ea-826c-bd0a93c6172b.png">

**Comment by willpower232** [comment]
I'm afraid I can't reproduce this, has the user accepted their invite?

**Comment by nuchanardy** [comment]
Yes, this problem occurs after the user has accepted it. But before that we were able to change the permission.

**Comment by willpower232** [comment]
Ah there it is, I've made a PR with what appears to be a resolution.

Can you confirm what your ruby version is currently?

**Comment by nuchanardy** [comment]
Sure, I use ruby `2.3.8` version.

**Comment by willpower232** [comment]
Interesting, presumably its more OpenSSL related then I guess. Can you try the change from #1002?
