### ISSUE TITLE
Mails Not Sending - Expected response code 250

### ISSUE THREAD

**Issue by suebum** [postalhq/postal#1003]
I am getting below error while sending mails.

Expected response code 250 but got code "", with message "" Log data: >> MAIL FROM:<reply@xxxxx.com> << !! Expected response code 250 but got code "", with message "" (code: 0)

Till yesterday everything was fine. today i changed number of mails sent per minute.
Earlier - 3 mails per minute
now - 6 mails per minute

but mails are not being sent. I am getting that error again & again.

**Comment by willpower232** [comment]
Where are you getting that error message? Can you share a screenshot?
