### ISSUE TITLE
Fast Server not renewing SSL

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#1005]
**Problem:**
SSL are not being renewed.

**Problem that I saw in the log file /opt/postal/log/lets_encrypt.log:**
```bash
^[[33m[worker.5:8812]^[[0m [2020-02-23T14:15:01.713] INFO -- : Attempting verification of xxx.yyy.zzz.com
^[[33m[worker.5:8812]^[[0m [2020-02-23T14:15:14.341] INFO -- : Status was not valid (was: invalid)
```
(there are other subdomains with same problem)

**All services are running:**
```bash
postal@:~$ postal status
Procodile Version   1.0.25
Application Root    /opt/postal/app
Supervisor PID      8786
Started             2020-01-10 02:14:55 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      10/01/2020   pid:8793     respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.2           Running      16:36        pid:24079    respawns:0      port:-        tag:-

|| worker
|| Quantity            5
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.6         Running      16:36        pid:24050    respawns:0      port:-        tag:-
|| => worker.7         Running      16:36        pid:24052    respawns:0      port:-        tag:-
|| => worker.8         Running      16:36        pid:24055    respawns:0      port:-        tag:-
|| => worker.9         Running      16:36        pid:24057    respawns:0      port:-        tag:-
|| => worker.10        Running      16:36        pid:24061    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      16:36        pid:24083    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      16:36        pid:24067    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Running      16:36        pid:24082    respawns:0      port:-        tag:-
```

**What I already tried?**
1. postal restart: not worked
2. postal console
TrackCertificate.where(certificate: nil).map(&:get)
RenewTrackCertificatesJob.perform
(for both the answer is "[]"; no logs are created on /opt/postal/log/lets_encrypt.log)
3. Try to use "check dns" link on web interface: the answer is "your CNAME for xxx.yyy.zzz.com looks good"
4. Try to disabled and then enable ssl feature on that domain (any log was wrote in /opt/postal/log/lets_encrypt.log) using web interface: not worked
5. Tried to registrate again the postal postal letsencrypt (not worked)
```bash
[23781] [2020-02-26T16:33:41.144] INFO -- : Successfully registered private key with address xxx@yyy.zzz
```

**My environment:**
```bash
root@:~# dpkg -l | egrep -i ruby
ii  libruby2.3:amd64                      2.3.8-4bbox1~xenial1                            amd64        Libraries necessary to run Ruby 2.3
ii  ruby2.3                               2.3.8-4bbox1~xenial1                            amd64        Interpreter of object-oriented scripting language Ruby
ii  ruby2.3-dev:amd64                     2.3.8-4bbox1~xenial1                            amd64        Header files for compiling extension modules for the Ruby 2.3
ii  rubygems-integration                  1.10                                            all          integration of Debian Ruby packages with Rubygems
root@:~# 

root@:~# cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

```

**This bug seems related with:**
- #892 
- #999 
- https://github.com/postalhq/postal/issues/529#issuecomment-373363441

**Comment by willpower232** [comment]
Your environment suggests that everything should be fine from that perspective.

Is your Postal up to date? I presume you were able to generate the certificate previously so this is just a renewal?

When the certificate fails to renew, it is bumped a whole day in the database so running the renew task repeatedly won't pick it up.

Status invalid means that Lets Encrypt was not able to get to your click tracking URL for some reason or another. If you visit it, do you see the word `Hello`?

**Comment by franciscopaniskaseker** [comment]
After I created the issue I saw I can not get Hello message due timedout. Then I tried to check 80 fastserver port and bam, closed.

Now I can see the Hello message. This explain why Lets Encrypt can not issue and log get invalid state. Only 443 inbound is allowed.

Is there a good procedure to force autorenew? In the logs I did not see the Lets Encrypt temporary banned the server, so I can try. I tried simply disable/enable o interface, but it did not do anything. Also using postal console I can not perform the SSL renew.

The Postal is not updated due other reason, but I will recommend that to the owner.

Also, you can close this issue. 

Thank you.

**Comment by willpower232** [comment]
Glad you got it figured out.

> When the certificate fails to renew, it is bumped a whole day in the database so running the renew task repeatedly won't pick it up.

This happens in the database so either wait until the same time tomorrow or edit the database record for the certificate and re run the command.

**Comment by franciscopaniskaseker** [comment]
> Glad you got it figured out.
> 
> > When the certificate fails to renew, it is bumped a whole day in the database so running the renew task repeatedly won't pick it up.
> 
> This happens in the database so either wait until the same time tomorrow or edit the database record for the certificate and re run the command.

I thought there is another way to do. But ok, thank you.
