### ISSUE TITLE
When add users to organizations, it seems fail, but work

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#1007]
**Problem:**
When I try to add an user to some organization, when I click in add, the process never finish.

**What errors I get?**
From puma.log:
```bash
x.y.z.w - - [28/Feb/2020:13:19:15 +0000] "POST /500 HTTP/1.0" 500 46 0.8201
```

From browser inspect:
```bash
application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:3 POST https://x.y.z.w/org/organizationanme/users 500 (Internal Server Error)
send @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:3
ajax @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:3
ajax @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:4
handleRemote @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:4
(anonymous) @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:4
dispatch @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:2
g.handle @ application-602ea59ead8408bdd66cbed4dc0d71c02bb8df0fe63aa700ac397a69ff29c17a.js:2
```

My environment:
```bash
root@:~# dpkg -l | egrep -i ruby
ii  libruby2.3:amd64                      2.3.8-4bbox1~xenial1                            amd64        Libraries necessary to run Ruby 2.3
ii  ruby2.3                               2.3.8-4bbox1~xenial1                            amd64        Interpreter of object-oriented scripting language Ruby
ii  ruby2.3-dev:amd64                     2.3.8-4bbox1~xenial1                            amd64        Header files for compiling extension modules for the Ruby 2.3
ii  rubygems-integration                  1.10                                            all          integration of Debian Ruby packages with Rubygems
root@:~# 

root@:~# cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

root@:~# 
```

Postal was upgraded with --safe parameter today.

And if I try again, I receive from ajax:
```bash
POST https://x.y.z.w/org/organizationanme/users 422 (Unprocessable Entity)
Email address is already assigned or has an pending invite
```

and from puma.log:
```bash
x.y.z.w - - [28/Feb/2020:13:28:09 +0000] "GET /org/organizationanme/users/new HTTP/1.0" 200 - 0.3650
x.y.z.w - - [28/Feb/2020:13:28:14 +0000] "POST /org/organizationanme/users HTTP/1.0" 422 - 0.0787
```

**note:**
z.y.z.w is generic name. does not mean they are the same in different logs, but they are when come from same log.

I did not receive any welcome email, but I think it is normal ( https://github.com/postalhq/postal/issues/537#issuecomment-375872095 )

**Issues related:**
not found

**Comment by franciscopaniskaseker** [comment]
Listing the organizations users I can see the new user e-mail is there and it is pending, so actually the first step worked, but due ajax 500 error it seems not worked.

**Comment by willpower232** [comment]
IIRC this can happen when Postal is unable to send the email. Have you configured the `smtp:` section in your Postal config?

**Comment by franciscopaniskaseker** [comment]
> IIRC this can happen when Postal is unable to send the email. Have you configured the `smtp:` section in your Postal config?

No. Then I configured the credentials and also not worked. Then I changed hostname from 127.0.0.1 to our official smtp hostname and it worked as expected.

So it is only a miss configuration.

Can I suggest some exception treatment that warn the user about the type of error? Because normal users will not get any message and will think the add process is frozen.

Thank you!

**Comment by willpower232** [comment]
Thanks for letting us know, glad you figured it out.

Yes there should be better handling of errors in the UI.

**Comment by apartamenti** [comment]
<img width="1163" alt="Screenshot 2020-04-17 at 17 19 54" src="https://user-images.githubusercontent.com/10740151/79579010-adc25080-80cf-11ea-8f4a-8f40747e82c0.png">
Getting Internal Server Error 500 when trying to add new user. I tried to change hostname 127.0.0.1 to my domain but still getting this error.

**Comment by willpower232** [comment]
> 
> 
> IIRC this can happen when Postal is unable to send the email. Have you configured the `smtp:` section in your Postal config?

**Comment by apartamenti** [comment]
Sure I configured even I am using successfully with api and smtp. The only error when I am adding a new user!

**Comment by willpower232** [comment]
You misunderstand me, the smtp section in the config file allows Postal to send email 

https://github.com/postalhq/postal/blob/0f30a53ebbc0f12eddd61f1397b955276bcd214f/config/postal.defaults.yml#L104-L110

If you don't fill this in, Postal won't be able to send an email to the new user generating the exception that occurs.

If you don't believe this to be the case, you can review the log files to see what else might be the problem.

**Comment by apartamenti** [comment]
Here is my smtp config
smtp:
  host: mydomain.com
  port: 2525
  username:                  
  password:                         
  from_name: Postal
  from_address: postal@mydomain.com

**Comment by apartamenti** [comment]
I am using username and password for SMTP from **Credentials section**. Am I missing something ?
Here is my log : 
EHLO localhost.localdomain
[smtp.1:9948] [2020-04-19T13:44:02.435] DEBUG -- : [RUCVLJ] => 250-My capabilities are
[smtp.1:9948] [2020-04-19T13:44:02.435] DEBUG -- : [RUCVLJ] => 250-STARTTLS
[smtp.1:9948] [2020-04-19T13:44:02.435] DEBUG -- : [RUCVLJ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:9948] [2020-04-19T13:44:02.476] DEBUG -- : [RUCVLJ] <= STARTTLS
[smtp.1:9948] [2020-04-19T13:44:02.476] DEBUG -- : [RUCVLJ] => 220 Ready to start TLS
[smtp.1:9948] [2020-04-19T13:44:02.480] DEBUG -- : [RUCVLJ] <= EHLO localhost.localdomain
[smtp.1:9948] [2020-04-19T13:44:02.491] DEBUG -- : [RUCVLJ] => 250-My capabilities are
[smtp.1:9948] [2020-04-19T13:44:02.491] DEBUG -- : [RUCVLJ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:9948] [2020-04-19T13:44:02.528] DEBUG -- : [RUCVLJ] <= MAIL FROM:<postal@mydomain.com>
[smtp.1:9948] [2020-04-19T13:44:02.528] DEBUG -- : [RUCVLJ] => 250 OK
[smtp.1:9948] [2020-04-19T13:44:02.529] DEBUG -- : [RUCVLJ] <= RCPT TO:<email@email.com>
[smtp.1:9948] [2020-04-19T13:44:02.715] DEBUG -- : [RUCVLJ] => 530 Authentication required
[smtp.1:9948] [2020-04-19T13:44:02.715] DEBUG -- : [RUCVLJ] <= QUIT
[smtp.1:9948] [2020-04-19T13:44:02.715] DEBUG -- : [RUCVLJ] => 221 Closing Connection
[smtp.1:9948] [2020-04-19T13:44:02.715] DEBUG -- : [RUCVLJ]    Connection closed

**Comment by apartamenti** [comment]
Ohhh...I finally fixed! username and pass info were in /opt/posta/config/postal.yml not in app/config/postal.defaults.yml :)

**Comment by willpower232** [comment]
Ordinarily your config should be in `/opt/postal/config/postal.yml` but if your setup requires the defaults then fair enough but be careful when updating Postal as it might undo your changes.
