### ISSUE TITLE
Classify '550 - Connection frequency limited' as softfail?

### ISSUE THREAD

**Issue by CalZzz** [postalhq/postal#1010]
We run a daily cron job that sends out a few thousand emails in minutes. A significant portion of the messages go to a domain with strict minute level connection frequency limit. So most of those emails will see a '550 - Connection frequency limited' warning and get classified as hardfail.

MailGun handles this situation more gracefully by treating the message as a softfail. They keep retrying. And most of such messages gets successfully delivered in an hour (after a few re-attempts).

With postal, we will have to click the 'redeliver' button for every failed message.

So we wonder if we can classify such warning as softfail and let postal retry for a dozen times.

**Comment by willpower232** [comment]
Can you send a screenshot of this error in the Postal UI?

**Comment by CalZzz** [comment]
![postal-550-hardfail](https://user-images.githubusercontent.com/20503978/75671715-36209980-5cba-11ea-8764-aeafa3872e6e.png)

As shown in the screenshot above, when this email was submitted by our daily cron job on March 02, 2020 15:57, it was rejected by QQ.com mail server as we have exhausted the minute level connection frequency allocated to our sending IP.

We just manually triggered re-delivery and QQ.com accepted it.

**Comment by willpower232** [comment]
Unfortunately it seems that the use of code 550 implies a permanent failure according to the standards and Postal catches the resulting exception here https://github.com/postalhq/postal/blob/634d3af59d392e84bdcd2b843b427f3a79d3ff4c/lib/postal/smtp_sender.rb#L171

Unless you modify this file locally for yourself (and restart Postal to apply the changes), I don't think there is another way around it but that could mean potentially retrying other messages which fail permanently as well, i.e. if the email address does not exist.

Ultimately its down to how you use Postal, if you use it for more than just the cron job then changing it might cause other problems.

**Comment by CalZzz** [comment]
Alas~

It would be very nice, if we have finer control with hardfail / softfail classification by matching fail reasons with regex.

**Comment by willpower232** [comment]
I think there has been some similar sentiment in other issues where the fail handling has not quite lined up to peoples expectations.

I can not find the specific code for rate limit SMTP error but in HTTP at least, it is a 4xx code rather than a 5xx code so it is also possible that this is a bad implementation of rate limiting from the receiving mail server.

**Comment by CalZzz** [comment]
You are absolutely right. Tencent (the company behind QQ.com) either accidentally misused the 550 error code, or did so deliberately to require senders to spread the incoming mails over time.

Either way, we will try modify the production code to accommodate Tencent's flavor of "rate limit reached, try again later."

Thanks dude. Awesome support!
