### ISSUE TITLE
Activation time and expire time

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#1012]
We are testing invite system and we are seeing a very short expire time.

We not found on postal.yml or in GUI this configuration. Is something hardcoded?

**Comment by franciscopaniskaseker** [comment]
Seems to be 7 days. Is that right?
https://github.com/postalhq/postal/blob/a66b94b228204fa9f389191825b4e0e7fdff754a/app/models/user_invite.rb#L26

**Comment by willpower232** [comment]
that looks to be it, does it correspond to the "very short expire time" you were seeing?

**Comment by franciscopaniskaseker** [comment]
> that looks to be it, does it correspond to the "very short expire time" you were seeing?

yes!
