### ISSUE TITLE
Not showing in browser

### ISSUE THREAD

**Issue by WizardKid** [postalhq/postal#1015]
I've followed all the steps and not found page on browser

**Comment by willpower232** [comment]
Have you tried running `postal status` in your terminal to see if its running properly?

**Comment by WizardKid** [comment]
Yes i did 
![Screenshot from 2020-03-06 12-42-33](https://user-images.githubusercontent.com/13104065/76084554-08806c80-5fa8-11ea-8ca8-01dfdcd944ac.png)
![Screenshot from 2020-03-06 12-42-22](https://user-images.githubusercontent.com/13104065/76084558-0a4a3000-5fa8-11ea-810e-af5e144aacad.png)

**Comment by WizardKid** [comment]
Now i am getting this in the browser
![Screenshot from 2020-03-06 12-44-02](https://user-images.githubusercontent.com/13104065/76084633-35cd1a80-5fa8-11ea-9311-624b234fd37a.png)

**Comment by WizardKid** [comment]
I got it started with the basic installation

**Comment by willpower232** [comment]
Have you applied the nginx config file and/or restarted nginx yet?

**Comment by WizardKid** [comment]
I have used basic installation and it is ok now..
