### ISSUE TITLE
Install failure - mariaDB error

### ISSUE THREAD

**Issue by taewookim** [postalhq/postal#1016]
Ubuntu 16.04 LTS on Google Cloud (shared instance with 600'ish MB ram)

I'm getting this error via install script:

dpkg: error processing package mariadb-server-10.1 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mariadb-server:
 mariadb-server depends on mariadb-server-10.1 (= 10.1.44+maria-1~xenial); however:
  Package mariadb-server-10.1 is not configured yet.

dpkg: error processing package mariadb-server (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 mariadb-server-10.1
 mariadb-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by taewookim** [comment]
Just tested the script on DigitalOcean's VPS instance.. no problems.

**Comment by taewookim** [comment]
Not sure if this is kosher, but skipping (i.e. commenting out) add-apt-repository from coreix.net seems to do the trick

`add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirrors.coreix.net/mariadb/repo/10.1/ubuntu xenial main'`

**Comment by taewookim** [comment]
PSA: Don't use VPS from Google cloud or AWS. They block port 25.

**Comment by willpower232** [comment]
Glad you figured it out, it may be that Googles apt setup is a little different from most or you're having memory issues but IIRC no one has reported this.

Regarding choice of cloud providers, AWS does let you use port 25 if you request it so whoever you choose, its worth reading their documentation fully first.
