### ISSUE TITLE
Email speed Limit & WarmUP

### ISSUE THREAD

**Issue by devallareddyb** [postalhq/postal#1017]
Hi if i keep any hourly sending limit on IP's i found that i need to again manually trigger messages every time to send . Eg: If i keep hourly speed is 60 Emails and if i submit 500 emails , First 60 emails delivering then again i need to send remaining mails manually. Is there any option where i can send emails automatically which are in q.?

Using IP Pool can i rotate ip's? Eg: If i have 10 IP's can i mention each ip sending limit is 100 emails per hour / per ip?

**Comment by willpower232** [comment]
The hourly limit is to prevent abuse so if you are the only user and know you are exceeding it, you should remove the limit.

Unfortunately there is not an easy way to get all the held email sent apart from clicking through the UI.

I don't believe that there is a limit per IP functionality.
