### ISSUE TITLE
Issue when mail stuck in queue possibly solved

### ISSUE THREAD

**Issue by joejordanbrown** [postalhq/postal#1021]
I can see many past GitHub issues relating to emails getting stuck in the queue but never getting resolved because there wasn't enough information provided.

I've debugged this issue today with our cluster, and I think I know how it happens. 

There seems to be an issue that mail can get stuck in a queue with no attempt because of one of the postal services have crashed for unknown reasons. The bug seems to be related to the table `queued_messages` column `ip_address_id` and possibly associated with the pool of IPs being deleted or changed.

I noticed the column `ip_address_id` had an ID number, I checked and these ID's no longer existed.

`use postal; select * from queued_messages;`

| id | server_id | message_id | domain             | locked_by | locked_at | retry_after | created_at                 | updated_at                 | ip_address_id | attempts | route_id | manual | batch_key                   |
|----|-----------|------------|--------------------|-----------|-----------|-------------|----------------------------|----------------------------|---------------|----------|----------|--------|-----------------------------|
| 75 |         1 |         63 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:14:55.705248 | 2020-01-09 22:14:55.705248 |             7 |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 94 |         1 |         82 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:50:11.026246 | 2020-01-09 22:50:11.026246 |             7 |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 95 |         1 |         83 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:50:56.221384 | 2020-01-09 22:50:56.221384 |             8 |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 96 |         1 |         84 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:51:44.348692 | 2020-01-09 22:51:44.348692 |             7 |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 97 |         1 |         85 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:52:13.214409 | 2020-01-09 22:52:13.214409 |             7 |        0 |     NULL |   NULL | outgoing-gmail.com          |

I fixed this by updating the ip_address_id to `NULL`, the queue then sent all the messages. Which shows it was related to the `ip_address_id` having an incorrect ID.

`use postal; update queued_messages set ip_address_id = NULL;`

| id | server_id | message_id | domain             | locked_by | locked_at | retry_after | created_at                 | updated_at                 | ip_address_id | attempts | route_id | manual | batch_key                   |
|----|-----------|------------|--------------------|-----------|-----------|-------------|----------------------------|----------------------------|---------------|----------|----------|--------|-----------------------------|
| 75 |         1 |         63 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:14:55.705248 | 2020-01-09 22:14:55.705248 |          NULL |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 94 |         1 |         82 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:50:11.026246 | 2020-01-09 22:50:11.026246 |          NULL |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 95 |         1 |         83 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:50:56.221384 | 2020-01-09 22:50:56.221384 |          NULL |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 96 |         1 |         84 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:51:44.348692 | 2020-01-09 22:51:44.348692 |          NULL |        0 |     NULL |   NULL | outgoing-gmail.com          |
| 97 |         1 |         85 | gmail.com          | NULL      | NULL      | NULL        | 2020-01-09 22:52:13.214409 | 2020-01-09 22:52:13.214409 |          NULL |        0 |     NULL |   NULL | outgoing-gmail.com          |

------

Also, the following command is useful to fix locked_by, locked_at or retry_after issues at the same time.

`use postal; update queued_messages set locked_by = NULL, locked_at = NULL, retry_after = NULL, ip_address_id = NULL;`

**Comment by rbustos** [comment]
This fix works like a charm!

Thanks @magicdrums 

@willpower232 : this is something that should go on next release.

**Comment by magicdrums** [comment]
please hold on, tomorrow new update the code

**Comment by Igcorreia** [comment]
All my emails are stuck :/ none suggestion work. Don't know what to do.

**Comment by magicdrums** [comment]
> All my emails are stuck :/ none suggestion work. Don't know what to do.

yo, testing Solution code?

**Comment by Igcorreia** [comment]
Yup, tried every single thing in the issues no luck:

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      12:46        pid:27118    respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      12:46        pid:27120    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      12:46        pid:27122    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      12:46        pid:27125    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      12:46        pid:27129    respawns:0      port:-        tag:-


![image](https://user-images.githubusercontent.com/1076409/102617162-a22c9b00-4130-11eb-920c-27edbf4f7c9a.png)

Pending:

![image](https://user-images.githubusercontent.com/1076409/102617208-b83a5b80-4130-11eb-91e9-fe4f5266f20b.png)

**Comment by Igcorreia** [comment]
Tried everything:
postal restart, boot restart, certificate renewal, log checking, notice that this happens after we change a webhook, the webhook failed 3 times, if I am not mistaken, and now nothing works.

**Comment by Igcorreia** [comment]
My case was disk space.
