### ISSUE TITLE
500 error internal-server-error 

### ISSUE THREAD

**Issue by ZaraBUy** [postalhq/postal#1023]
thanks for this good utils.

here,i got an exception in my java program. need for help.
When I call postal api "/api/v1/send/message", then return `status:500，content:{"status":"internal-server-error"}`

This exception happens 1 out of 100 times.

I check in rails.log:
`ESC[34m[web.1:25693]ESC[0m [2020-03-12T10:18:49.223] INFO -- : Started POST "/api/v1/send/message" for 35.175.15.248 at 2020-03-12 10:18:49 +0000
ESC[34m[web.1:25693]ESC[0m [2020-03-12T10:18:50.233] INFO -- : Mysql2::Error
ESC[34m[web.1:25693]ESC[0m [2020-03-12T10:18:50.233] INFO -- : MySQL server has gone away
ESC[34m[web.1:25693]ESC[0m [2020-03-12T10:18:50.233] INFO -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'`

`postal status`:
Procodile Version   1.0.26
Application Root    /opt/postal/app
Supervisor PID      25687
Started             2020-03-12 10:15:14 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      10:15        pid:25693    respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.1           Running      10:15        pid:25695    respawns:0      port:-        tag:-

|| worker
|| Quantity            2
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      10:15        pid:25697    respawns:0      port:-        tag:-
|| => worker.2         Running      10:15        pid:25699    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      10:15        pid:25703    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      10:15        pid:25706    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      10:15        pid:25709    respawns:0      port:-        tag:-

**Comment by ZaraBUy** [comment]
@willpower232

**Comment by ZaraBUy** [comment]
DB Server version: 10.1.44-MariaDB-1~xenial

**Comment by willpower232** [comment]
> MySQL server has gone away

Do you have enough memory to keep Postal and MySQL running at the same time?
