### ISSUE TITLE
Mysql2::Error: This connection is in use by

### ISSUE THREAD

**Issue by ZaraBUy** [postalhq/postal#1024]
![image](https://user-images.githubusercontent.com/31838874/76582848-71209980-6512-11ea-93b7-f12c5649f017.png)

It happens sometime when i use postal  to send email.

`postal.yml`:
web_server:
  bind_address: 127.0.0.1
  port: 5000
  max_threads: 10

workers:
  quantity: 2
  threads: 4

main_db:
  host: 127.0.0.1
  port: 3306
  username: postal
  password:
  database: postal
  pool_size: 16

Who can tell me how to deal with !?

**Comment by willpower232** [comment]
similarly to #1023 it sounds like you don't have enough system resources to run both MySQL and Postal or your MySQL has been tuned down somewhat
