### ISSUE TITLE
Postal worker issue

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#1026]
Hi

I have added into postal.yml

 workers:
  quantity: 4
  threads: 4
and then restarted server as well postal but when i check the postal status... status show's worker quantity is 1 only... why?

Can you please help me with this matter

**Comment by willpower232** [comment]
you'll have to check the log files, also do you have enough memory available?

**Comment by sahilsunesara** [comment]
yes... i have 8GB RAM

**Comment by willpower232** [comment]
have you looked in the log files? have you checked `htop` or something to see how much available memory you have?

**Comment by sahilsunesara** [comment]
htop information

https://paste.pics/e06c8fe9be9c01a1cb45e41ebb9b9c33

Please check

**Comment by willpower232** [comment]
>have you looked in the log files?
