### ISSUE TITLE
non random Dkim 

### ISSUE THREAD

**Issue by masihfathi** [postalhq/postal#1027]
In postal DKIM Record name create randomly. How do I create a fixed name?

**Comment by willpower232** [comment]
see #926 and #616

**Comment by masihfathi** [comment]
Thanks. I see them. but i mea:
as example for domain: example.com, postal create a name record with mix of 2 string, one of them static and next of randomly genrate, something like below:
` postal-BWBLWo._domainkey 
`But i need something like this:
`postal-static._domainkey`

**Comment by willpower232** [comment]
As discussed in those issues, its easier to change in the database after it has been created.
