### ISSUE TITLE
Email Stuck

### ISSUE THREAD

**Issue by lokival** [postalhq/postal#1028]
Marketing team tried to send out an email blast, 

Server ran out of disk space & RAM.

We rebooted the server, upgraded the RAM and moved the postal database over to a NAS to resume operations.

Now all email sent to postal is in state pending, but nothing is delivered.

Is there a way to force all queued messages to attempt delivery?

**Comment by willpower232** [comment]
Do you mean new messages go to pending or the messages that were trying to be sent before the crash?

If it was before the crash, you would have to go in the database and check the queued_messages and clear the locked_by, locked_at, and retry_after fields or something along those lines.

**Comment by lokival** [comment]
clearing the locked messages by following the steps described in -

Issue when mail stuck in queue possibly solved #1021
