### ISSUE TITLE
Error with MariaDB 10.2.12.

### ISSUE THREAD

**Issue by bpallin** [postalhq/postal#1029]
Hi,
We were working with Postal and MariaDB 10.2.16 in a development environment and everything was ok. When we have tried changing it to a production environment we haven't been able because the database doesn't work (MariaDB 10.2.12 version).

Does anybody know if there is any problem between Postal and MariaDB 10.2.12 or any way to solve it?
Thanks in advance!!

**Comment by willpower232** [comment]
When you say the database doesn't work, what does that mean?

**Comment by bpallin** [comment]
Willpower232 sorry for the delay in aswering you but I was reproducing the error again in order to have more information.

The problem appears when we try to create the mail server. When we click "build server" button the system doesn't do anything.

![Postal](https://user-images.githubusercontent.com/62292007/77162503-65058080-6aac-11ea-97c1-c14a3202c421.PNG)

This is the **log**:

12:41:54 web.1              | => [web.1:5483] [2020-03-20T12:41:54.044] INFO -- : Started POST "/org/devluispa/servers" for 127.0.0.1 at 2020-03-20 12:41:54 +0100
12:41:54 web.1              | => [web.1:5483] [2020-03-20T12:41:54.046] INFO -- : Processing by ServersController#create as JSON
12:41:54 web.1              | => [web.1:5483] [2020-03-20T12:41:54.047] INFO -- :   Parameters: {"utf8"=>"✓", "server"=>{"name"=>"app.org.es", "permalink"=>"app", "mode"=>"Live"}, "commit"=>"Build server", "org_permalink"=>"devluispa"}
12:41:59 web.1              | => [web.1:5483] [2020-03-20T12:41:59.103] INFO -- : Completed 500 Internal Server Error in 5055ms (ActiveRecord: 20.5ms)
12:41:59 web.1              | => [web.1:5483] [2020-03-20T12:41:59.106] FATAL -- :
12:41:59 web.1              | => [web.1:5483] [2020-03-20T12:41:59.106] FATAL -- : Mysql2::Error (No puedo eliminar base de datos 'postal-server-1'; la base de datos no existe):
12:41:59 web.1              | => [web.1:5483] [2020-03-20T12:41:59.107] FATAL -- :
12:41:59 web.1              | => [web.1:5483] [2020-03-20T12:41:59.107] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'
12:41:59 web.1              | => lib/postal/message_db/database.rb:311:in `block in query'
12:41:59 web.1              | => lib/postal/message_db/mysql.rb:20:in `client'
12:41:59 web.1              | => lib/postal/message_db/database.rb:342:in `with_mysql'
12:41:59 web.1              | => lib/postal/message_db/database.rb:310:in `query'
12:41:59 web.1              | => lib/postal/message_db/provisioner.rb:46:in `drop'
12:41:59 web.1              | => lib/postal/message_db/provisioner.rb:13:in `provision'
12:41:59 web.1              | => app/models/server.rb:86:in `block in <class:Server>'
12:41:59 web.1              | => app/controllers/servers_controller.rb:36:in `create'

And this is the error that the browser returns:

![browser_error](https://user-images.githubusercontent.com/62292007/77162786-04c30e80-6aad-11ea-9dcf-6a1b14aac55e.png)

I would appreciate if you could helps us.
Thanks in advance!!

**Comment by willpower232** [comment]
It sounds like the Postal database user might not have enough permissions to create databases and the code wasn't able to detect the problem.

Are you able to confirm if you've created permissions for the Postal database user for `postal-%`?

**Comment by bpallin** [comment]
Yes, we thought the same but we have checked thoroughly all the permisions and apparently everything is correct.
We have installed Postal in several servers and everything was ok, but in the production server doesn't work.

The permissions for the Postal user are these:

![Postal_user](https://user-images.githubusercontent.com/62292007/77311653-d0e02700-6d00-11ea-831e-fab4c294682b.PNG)

**Comment by willpower232** [comment]
Interesting, that certainly looks correct.

Can you tell us what is different about your production database server? Does it have replication on or some other specific customisation to make it the production one?

**Comment by bpallin** [comment]
Yes, it looks like it is, but it doesn't work.
We have a production server just for all our databases and we make a daily backup. That's all. 
All the applications are working against that database server and everything is fine apart from Postal.
We have done several tests on different servers and they worked, but when we try to do it on that database server Postal is not able to create the mail server.

Thanks a lot willpower232 for your help!

**Comment by willpower232** [comment]
Presumably nothing else tries to create databases on the fly like Postal.

One course of action could be to use Postals login details in HeidiSQL yourself and try creating a `postal-0` database to see what happens. Hopefully the query output at the bottom should tell you what is wrong.

**Comment by bpallin** [comment]
Willpower32, according to your question about if we have replication the answer is yes. We use log_bin and log_bin_index parameters to create the transaction files. These files will be picked up by the replica database server to ensure the high availability.

**Comment by willpower232** [comment]
Ah well I guess that means there could be a tiny delay in the database being created and the database actually existing on all the replicas? I'm not sure if there is a better way of coping than a sleep of some variety in the code.
