### ISSUE TITLE
Wiki Api pages not found

### ISSUE THREAD

**Issue by alanvallejodev** [postalhq/postal#1030]
Hi, 

I want to know how to send a message using the API but when I click "Sending a message" or "Sending an RFC 2822 message" in the documentation (https://github.com/postalhq/postal/wiki/Using-the-API) I get a 404 error "page not found". Where can I read the documentation to format a message and send it to the API? 

Also, if I want to read the Full API documentation, I also get a 404.

Thanks for you time.

**Comment by willpower232** [comment]
The link in your message works for me so it might be github having a bad moment. Do you still have this problem?

**Comment by alanvallejodev** [comment]
Maybe I didn't explain myself clearly enough. The links that are inside that page are those that are not working, see below:

Full API documentation - https://atech.github.io/postal-api
Sending a message - https://atech.github.io/postal-api/controllers/send/message
Sending an RFC 2822 message - https://atech.github.io/postal-api/controllers/send/raw

**Comment by willpower232** [comment]
Ah it seems the github organisation and more has changed behind the scenes (https://twitter.com/atechmedia/status/1240239030752686081)

You can get to the pages from https://krystal.github.io/postal-api/

**Comment by alanvallejodev** [comment]
Thank you very much!
I apreciate your swift response!
Have a good day!

**Comment by willpower232** [comment]
I'm holding out hope that someone will be able to update the wiki so will leave this open for now.

**Comment by sairam** [comment]
@willpower232 , looks like only contributors can edit the wiki. not everyone can.

**Comment by willpower232** [comment]
correct, that is why this issue is still open

**Comment by willpower232** [comment]
As observed in #1409 the link is now https://postalhq.github.io/postal-api/
