### ISSUE TITLE
Postal.local uesage

### ISSUE THREAD

**Issue by Danissss** [postalhq/postal#1031]
Hi, may I ask what `Postal.local` (in `update_process_concurrency.rb`)is used for?
```ruby
File.open(Postal.app_root.join('Procfile.local'), 'w') { |f| f.write(hash + "\n")}
```

I can also start the postal with `rails s`, so it's quite confusing.

**Comment by Danissss** [comment]
I probably should take look at `procodile` ;)

**Comment by willpower232** [comment]
You should use the documented processes to start Postal using `postal start` or systemd.

If you want to run individual parts of Postal separately on different servers (or in kubernetes), the processes listed in Procfile are a good place to start.

**Comment by Danissss** [comment]
Any drawbacks for not using Procfile? 
I used to use puma.

**Comment by willpower232** [comment]
Only that you would have to manage starting each of the processes yourself, depending on which parts of Postal you wanted to use.

The processes don't overlap that much but they almost all require access to the database and queue servers I believe.
