### ISSUE TITLE
Can only send mail when started by postal run

### ISSUE THREAD

**Issue by lokival** [postalhq/postal#1032]
New problem with my favourite bulk mailer, for some reason can only send email when I login as the postal user and use -

postal run

to start it up.

If I use postal start, all attempts to connect to the SMTP port by clients are rejected.

Would be glad of any ideas on how to figure out what's causing this

**Comment by lokival** [comment]
Since I wasn't getting anything in the logs, decided to move the original log folder to logs.old and create a new one to clear the clutter

As soon as I did this, started right up.

Maybe corrupt log file?

**Comment by willpower232** [comment]
Its possible that the permissions weren't quite right when it was being installed or run for the first time.

The only other thing I would have suggested is making sure ruby has permission to use the system ports as documented in the wiki: https://github.com/postalhq/postal/wiki/Installation#preparing-your-operating-system
