### ISSUE TITLE
SSl & TLS are not working ? How I enabled TLS on postal?

### ISSUE THREAD

**Issue by Infoworlds** [postalhq/postal#1033]
Hello,

I have installed postal and generated SSL certificate on postal.
But at some application, it will accept the certificate and when I am trying on smtper or Amazon SES  it will not accept the certificate.

Please help me out of this.

Thanks in advance

**Comment by willpower232** [comment]
When you say you have generated a certificate, do you mean a self-signed one? It sounds like that might be your problem as most services wouldn't trust a self signed certificate automatically.

If you use Lets Encrypt to make a certificate for nginx, you should be able to reuse that certificate within Postal and that should then be accepted by your other services.

Its also possible that you are encountering #999 and are having a problem because of a newer OpenSSL / ruby version. Which versions are you using currently?

**Comment by Infoworlds** [comment]
Hello @willpower232 

Thank for your reply.

I am using the below steps for generating a self-signed certificate in postal. I have also done some changes in postal.yml and nginx sites default file.

#certbot certonly --webroot --webroot-path /opt/postal/app/public --domains postal.example.com

#chown -R postal:postal /etc/letsencrypt/live/postal.example.com
#chown -R postal:postal /etc/letsencrypt/archive
#chown -R postal:postal /etc/letsencrypt

And my current ruby version is:-
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux-gnu]

Is there any changes in postal to generate a self-signed certificate. May I also know that this certificate will generate for both SSL and as well as TLS.

Thanks in advance

**Comment by willpower232** [comment]
Sounds like you're doing everything right so far but you will also need to put the letsencrypt certificate path in your Postal config file under `smtp_server`:

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.example.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.example.com/privkey.pem
```

**Comment by Infoworlds** [comment]
Hello @willpower232 

I have already done this change into postal.yml and nginx default file. My configuration is below:

#vim /opt/postal/config/postal.yml

smtp_server:

host: Hostname or ip
port: 587
 tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.example.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.example.com/privkey.pem
tls_ciphers:
ssl_version: TLSv1_2
proxy_protocol: false
log_connect: true
strip_received_headers: false
max_message_size: 14 


#vim /etc/nginx/sites-available/default

server {
    listen [::]:80;
    listen serverIP:80;
    server_name postal.example.com;
    return 301 https://$host$request_uri;
}

server {
    listen [::]:443 ssl;
    listen server IP:443 ssl;
    root /opt/postal/app/public;
    server_name postal.example.com; 
    ssl_certificate     /etc/letsencrypt/live/postal.example.com/fullchain.pem ; 
    ssl_certificate_key  /etc/letsencrypt/live/postal.example.com/privkey.pem; 

After doing all the process I am still facing the same issue. what I can do to resolve this issue.

Thanks in advance

**Comment by willpower232** [comment]
Did you also restart Postal after changing the configuration?

**Comment by Infoworlds** [comment]
yes I restart postal and reboot the server after all the changes

**Comment by Infoworlds** [comment]
Hello @willpower232 

After running a command (openssl s_client -connect postal.example.com:587 -tls1 -crlf -debug)I got the below error:-

**140109185652376:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:**
**secure renegotiation is not supported in letsencrypt**

Is there is the issue between connectivity . because when I see the logs of letsencrypt it shows the status=valid but when I try to connect postal in any application like amazon or outlook its doesn't accept the certificate and shows invalid certificate.

please help me out of this.

Thanks in advance

**Comment by willpower232** [comment]
Postal doesn't use port 587 by default, are you running something else besides Postal on that server or have you changed the port?

**Comment by oviliz** [comment]
@Infoworlds , I don't know if related nor if NGINX is happy with that (maybe is just a copy/paste error), you do have an extra space before the `;`:
`ssl_certificate /etc/letsencrypt/live/postal.example.com/fullchain.pem ;`

**Comment by Infoworlds** [comment]
Hello @willpower232  

Sorry for the late reply.

Now, TLS is working in outlook. but not in amazon ses and it doesn't accept my certificate
may I know the reason that what is the reason?

Thanks

**Comment by willpower232** [comment]
It could be worth finding out which port(s) Amazon is trying to use, it may be getting an unwanted response from something else and confusing the situation.

**Comment by Igcorreia** [comment]
To anyone reading this after it was closed. I need to restart postal after any Certificate is renewed.
