### ISSUE TITLE
Shared hosting

### ISSUE THREAD

**Issue by AndersonOuverney** [postalhq/postal#1035]
Hello
We are starting testing with the postal to relay on our servers.
Currently we have several hosting servers for shared websites, our idea is to use the postal as a central relay.

Can I use the postal transparently? without having to configure all the hosting server domains in the postal?

**Comment by willpower232** [comment]
Unfortunately for your use case, Postal requires explicit setup currently.

I'm not sure if you would be able to script setting up all the domains you'd want to use because you would also need to manually configure the DNS records for the domains to allow you to send email from them.

**Comment by AndersonOuverney** [comment]
Hello good afternoon.
We have made great progress in integrating our cPanel with Postal.
Right now we are working with custom scripts to integrate all domains, this will be possible, we have no more doubts here.

Our question now is as follows, we carry out the personalization of the postcard, in some items, one of these items is to stamp in the field from the origin of the sender, this is working for us at this moment.

My question at this point is.
Imagine that I have a domain set up and they are sending emails to 10 accounts created on the server. One of these accounts that are created on the server sends an email to an email account that does not exist, I would like to return the error to the sender, how can I do this?

**Comment by willpower232** [comment]
Does this page from the wiki help you? https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces

Alternatively, you may want to look at setting up webhooks which would cover the message being bounced and other events.

**Comment by AndersonOuverney** [comment]
Will thanks for your return, I appreciate your help.

Looking at your answer I need to ask some additional questions to be sure about possible problems.

Remembering that we are using a test hosting server, transparently integrated with the postal, all messages sent via webmail or any email client, such as outlook for example, are sent via relay by postal.

Currently we customize the postal code so as not to change the returnpath, this means that the return path address will always be the same as the sender's address, we did it so that the messages are delivered as if the sender was sending, currently this is working well and without problems.

The problem here is the following, when we send a wrong email (user or domain does not exist for example), I need to make 100% of the errors return to the sender, that way I will be able to show the error to the sender.

Thanks.

**Comment by willpower232** [comment]
If Postal is unable to send an email, the built in way to get that information is via webhooks so that your application receives a message that something went wrong.

Your integration of Postal is quite different to its intended use so I'm not sure how to suggest how you would do this.

**Comment by AndersonOuverney** [comment]
I would like to make sure I understand your answer.

Currently if there is a hardfail I cannot forward the message to the sender? is there anything i can do to perform this action?

**Comment by willpower232** [comment]
As per https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces, you can use a route to send a bounce to a specific route but I'm not sure if this will help you if you had multiple senders per domain.

**Comment by AndersonOuverney** [comment]
We were able to solve the problem by customizing the code.  
The solution was, instead of returning the error to return_path, we are returning the errors to the sender, from.

**Comment by willpower232** [comment]
Jolly good, feel free to close this issue if you don't have any more questions right now.

**Comment by Trouble123** [comment]
@AndersonOuverney are you able to share how you setup postal as a relay?
Thanks

**Comment by AndersonOuverney** [comment]
Hello.
We are making dozens of changes to the tool to allow use as a relay for cpanel.
We are currently working hard on a cpanel plugin.

We are currently testing the postcard with several cpanel servers.
We have a delivery rate of over 99% at this time.

It is not easy to say the changes made, we believe that we are only at the beginning of the project.

Our intention is to have a beta version in May/2020

**Comment by Trouble123** [comment]
Thanks, we were wanting to use it internally, ie setup our normal email server we use to point to Postal as a smart host (email relay), so we can use Postal's email tracking and delivery stats. 

Is the same concept as you?

**Comment by AndersonOuverney** [comment]
Exactly.
Our concept is for normal emails ...
That email sent via webmail, or any imap/pop3 client. (Desktop or mobile)
Any email account in the domain, as long as previously configured.
We are currently having a lot of success.

In theory, this initiative can be implemented with any final platform.

**Comment by Trouble123** [comment]
Hi, so your users will have a mailbox setup in Postal? Or they are on server X, which then is using Postal as its next hop (smart host), and then from Postal it will go to its final destination?

Are all emails going from server X to postal, as this is where we are seeing the issue. As Postal needs the domain setup to be able to accept emails, you cant setup every domain in postal - and that wouldnt really help in any case.

**Comment by AndersonOuverney** [comment]
Hello.
It works as follows.
On server1 we have the e-mail accounts created, it is on this server that e-mails are stored, passwords and users, etc .....

This server1 relays the postal completely automatically, I don't need to have email accounts on the postal, here is the postal that does all the work to deliver the message to the final recipient, the ips and hosts are from the postal.

The postal receives this message and transmits it to its final recipient.

There is a group on slack that we are discussing some similar issues, you are welcome to join us.
https://app.slack.com/client/T01167HJ95J/C0118NX6P7H

**Comment by AndersonOuverney** [comment]
I was already forgetting to say.
We created an api for the postal, with this api it is possible to add domains via curl.

I believe that the next version of the postal will be available

**Comment by Trouble123** [comment]
Thanks, how do i get an invite into that slack group?
With the API, can i ask what its required for? Is that because in your use case you have many different source email domains on server 1? And so your only allowing emails into postal based on the email domain that sends the emails to Postal?

**Comment by AndersonOuverney** [comment]
Hello good day.
That's right.
We use the api to keep the list of domains created on a cPanel server with the postal up to date.

If you used one or a few domains, it would not be necessary to integrate with API, since you can configure your domain only once. You just need to install the psotal and configure it to send emails correctly.

To access the slack just register and click on the link.

**Comment by Trouble123** [comment]
Whats the slack workspace called, as that link just takes me to a signup page - and without knowing the workspace - i cant go any further.

**Comment by AndersonOuverney** [comment]
For you to join a discussion group you need to have a slack account, it's free and quick to do.

**Comment by Trouble123** [comment]
Hi, i have a slack account - rarely use it, but i do have one. When i click the above link, it takes me a to a screen "Sign in to your workspace", and "Enter your workspace’s Slack URL.". I have googled how to join a workspace - and every link tells me that i need to be invited
