### ISSUE TITLE
Confusing DNS setup hint:

### ISSUE THREAD

**Issue by Danissss** [postalhq/postal#1037]
Hi, 

At the "DNS Setup for ..." page, there is the hint/instruction to setup the SPF record, and I found it is quite confusing.

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
SPF Record

Warning No SPF record exists for this domain

You need to add a TXT record at the apex/root of your domain (@) with the following content. If you already send mail from another service, you may just need to add include:spf.mail.sample.ca to your existing record.

```
v=spf1 a mx include:spf.mail.sample.ca ~all
```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

I think "... with the following content." should include an actually example rather than just `v=spf1 a mx include:spf.mail.sample.ca ~all`

Probably should add the following content from this [wiki](https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration)

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
SPF Record

Warning No SPF record exists for this domain

You need to add a TXT record at the apex/root of your domain (@) with the following content.
```
spf.mail.sample.ca.     IN    TXT   "v=spf1 ip4:192.168.0.0/28 ip6:2a00:1234:abcd:1::/64 ~all"
```
 If you already send mail from another service, you may just need to add include:spf.mail.sample.ca to your existing record.

```
v=spf1 a mx include:spf.mail.sample.ca ~all
```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Otherwise, I totally misunderstood the concept of SPF record... (please correct me if I am wrong)

**Comment by Danissss** [comment]
Also, the "DNS Setup for ..." page is not consistent with the [wiki](https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration). 

The last updated is 2018. Should that doc update?

**Comment by willpower232** [comment]
> I think "... with the following content." should include an actually example rather than just v=spf1 a mx include:spf.mail.sample.ca ~all

`v=spf1 a mx include:spf.mail.sample.ca ~all` is an example for the entire contents of an SPF record.

The `... IN TXT ...` example would be for something like setting up a DNS server zone file directly (or understanding the output of the `dig` command).

The wiki page refers to setting up the base DNS records for the Postal server itself, the DNS setup page within Postal is about applying those base DNS records to your own domains.

Hope this makes sense. There is regular confusion about setting up the DNS records so it could probably be better explained that Postal is essentially set up to be a white-label solution for you to offer clients but I think everyone just uses it for their own products.

**Comment by Danissss** [comment]
Hi, thanks for help. I am new to setting up the mail server, and hope that you can help me to understand more about postal.

About [wiki](https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration):
If I have
```
mail.sample.ca    IN     A     175.139.46.252
sample.ca         IN     MX    10 mail.sample.ca  
```
My `postal.yml` should be something like this (right?):
```
dns:
  mx_records:
    - mail.sample.ca
  smtp_server_hostname: mail.sample.ca  

  ... (more configuration)
```

About SPF, DKIM, return path and route domain, if I have following configuration:
```
dns:
  ... (more configuration)

  spf_include: spf.mail.sample.ca
  return_path: rp.mail.sample.ca
  route_domain: routes.mail.sample.ca
```

I should create following DNS:
```
# SPF
spf.mail.sample.ca     IN    TXT   "v=spf1 ip4:175.139.46.252 ~all"

# return path
rp.mail.sample.ca      IN    A     175.139.46.252
rp.mail.sample.ca      IN    MX    10 mail.sample.ca 
rp.mail.sample.ca      IN    TXT   "v=spf1 a mx include:spf.mail.sample.ca ~all"

# DKIM
postal._domainkey.rp.mail.sample.ca      IN    TXT   "v=DKIM1; t=s; h=sha256; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzipajyThkwNmZs0cBjghowttXe1FhxplkBljpk90tzCfkFWJ+QHsUCNGmsFXhRALBol8cC4YHks5R9cjvGsphEM8C4jV2Nef5TxofAXuOpV5tbI0H3pBQY1cmP6I82VDAchsmfADCW/3XIFCPpYvnRFVlDnEQcuk4Ghl9LarhCZQqP8x7b38sPV6fcTrWL0HnNxEGAxRDiNWzGD1nEkp/m1o4STC7H8NvDbuZGkopmciDEE8cDxTbHGv7KRd72W5JewEx43nbtFUOEiv6D/otwT1xN2XF3JkOBtD3VcH+KB/zB6wwxJptNamw5kunskUoWwZwN488CpxxRF5tKPhCwIDAQAB;"


routes.mail.sample.ca  IN    MX    10 mx.mail.sample.ca  # is mx.mail.sample.ca created when I set up MX record with sample.ca   IN     MX    10 mail.sample.ca  ?
```



About the postal organization and mail server (i.e. `Build a new mail server`):
If I created the organization named `personal` and a new mail server `admin`, I can create the domain at organization (`Domains`), as well as at the mail server `admin`. What is the difference between these two domains?

What credentials are used for?
After create my first credential on postal, I got following content:
```
SMTP Server Address       mail.sample.ca
Port                      25 or 2525
Username                  personal-2/admin
Password                  dy4U7SztwobcknbIECFsbG5k
Authentication Methods    PLAIN, LOGIN or CRAM-MD5
```

What routes are used for?
There are three options 1. HTTP endpoint; 2. SMTP endpoint; 3. an address endpoint.
Assume I create an address endpoint `green@google.com`, and I add my first routes,
```
NAME          admin  @ mail.sample.ca
ENDPOINT      green@google.com
```
So whoever sends the email to admin@mail.sample.ca, my gmail green@google.com will receive the email, right?

If I want to receive the email at my own SMTP server, I just need to set up the SMTP endpoints with
```
NAME       admin
HOSTNAME   mail.sample.ca
PORT       2525
SSL MODE   TLS
```
and then I just make the routes point to the created SMTP endpoints.


To answer my question about organization domain and server domain, I guess they are just two options that people can choose one of them to work with?

Thank you again for your help!

**Comment by willpower232** [comment]
> What is the difference between these two domains?

Domains created at the organization level can be used by all the mail servers within that organization so you could add `sample.ca` to the organization domains list and then have a mail server for each application so you can separate the messages and see which is busiest etc.

> What credentials are used for?

Credentials are used to send email through Postal, i.e. your website has a contact form and wants to send it via an email then it can use the credential to send an email of the contact form contents

> What routes are used for?
> So whoever sends the email to admin@mail.sample.ca, my gmail green@google.com will receive the email, right?

Correct. Routes decide where email goes if the DNS says deliver it to your Postal server.

**Comment by ilovepancakes95** [comment]
> 
> Domains created at the organization level can be used by all the mail servers within that organization so you could add `sample.ca` to the organization domains list and then have a mail server for each application so you can separate the messages and see which is busiest etc.
> 

This finally makes sense to me, so organizations are meant to be for a single domain essentially but you can have multiple "servers"? Although what I don't get is, if I make a separate organization for a separate domain, why does DNS config page in that organization reference the domains in main postal.yml file? How can I define different domain values for each organization in postal.yml?

Or are different organizations meant to be used in a way I am not understanding and to setup postal for another domain entirely I need to spin up a completely separate install?

**Comment by willpower232** [comment]
@ilovepancakes95 Postal is essentially a white label solution so if you were a software developer, you could have an organization for each of your clients and a different server for each software you made for them.

The domains listed in postal.yml would refer to the server you're running, i.e. postal.mysoftwaredevcompany.com so you shouldn't need to have different configuration for each client/organization.

Hope this makes sense, if you're still having troubles, feel free to open a new issue.

**Comment by ilovepancakes95** [comment]
@willpower232 Ahh okay, so postal is only meant to have one email domain per entire instance/server install of it, and organizations are just another way to segregate metrics and credentials essentially for if you run it for multiple apps or client?

**Comment by willpower232** [comment]
sort of, one Postal server can send emails for any domain appropriately configured for it, this configuration means that those domains should all link back to the same domain which is the one you have in postal.yml

**Comment by ilovepancakes95** [comment]
OK, I assume you mean as a relay, as in another mail server somewhere else sends message out to postal, which then sends the message out using it's own domain for email setup.

**Comment by willpower232** [comment]
Postals main purpose is to enable software to send email without that software needing to deal with the specifics of sending and receiving email. It is kind of a relay in that a message needs to be passed to Postal for it to send out, but if you are needing something specifically relating to email flow, Postal probably isn't exactly what you're looking for.

**Comment by ilovepancakes95** [comment]
I was more curious than anything to make sure I understanding how it all works and the relationship between organizations and mail servers in postal and domains it is used with. My use case is as an outgoing email relay for a system that has a dynamic IP. While it sounds like this isn't exactly what it is made for, it definitely seems to work nicely so far. Thanks for the clarifications.
