### ISSUE TITLE
Relay HELO differs from its IP's reverse DNS

### ISSUE THREAD

**Issue by hannyramzy** [postalhq/postal#1038]
Thanks for this Postal. It work great so far for me. In Spam Checks, I got this anyway, but clueless how to resolve it.

![01](https://user-images.githubusercontent.com/10192653/77878306-99d2be00-728a-11ea-9efe-9a8026a7c648.png)

I have made some test at mail-tester.com, and got this result anyway:

![02 fw](https://user-images.githubusercontent.com/10192653/77878759-a6a3e180-728b-11ea-84cf-df8ce2ba95e2.png)

**Comment by AndersonOuverney** [comment]
Hello.
DNS propagation can sometimes take longer than expected, make sure that there is no query cache on the postal server.

Any doubt just say.

**Comment by hannyramzy** [comment]
Its been few days already, I think the DNS propagation already resolved.

**Comment by willpower232** [comment]
Your first screenshot looks like the spam checking within Postal so is that referring to a message you're trying to send via Postal or a message that Postal has received?

I would suspect that the problem lies in how the message is being created.

**Comment by hannyramzy** [comment]
I'm sending the message via Postal SMTP through WordPress. Here the function from WordPress I used:

![06](https://user-images.githubusercontent.com/10192653/78014559-af271580-737a-11ea-9a35-fe513078e370.png)

Anyway I'm pooling the IPs, about 16 all of them. All the rDNS & A record is setup successfully.

**Comment by willpower232** [comment]
I see, you should try downloading the email message from Postals UI to see what the headers are in the message. I'm guessing you'll see something in there that refers to your server directly because of a header automatically created by phpmailer.

**Comment by hannyramzy** [comment]
This is what my header look like

![55](https://user-images.githubusercontent.com/10192653/78042026-11e0d700-73a4-11ea-8944-58b6f1b84e28.jpg)

Anyway before this, I've made some change to file /etc/hostname & /etc/hosts. Is it has something to do with it?

**Comment by willpower232** [comment]
If your server hostname is not a complete DNS name like whatever.example.com, that might be it?

**Comment by georgetasioulis** [comment]
Maybe you can try disabling IPv6 on your server.

**Comment by hannyramzy** [comment]
> Maybe you can try disabling IPv6 on your server.

Doesn't seems working. I have confirm the IPv6 has been disable through `ip a`.
