### ISSUE TITLE
Seconds in activities

### ISSUE THREAD

**Issue by AndersonOuverney** [postalhq/postal#1039]
Hello good afternoon.
When it comes to sending emails any delay is bad, so I would like to request the following:

On the e-amils submission screen, activities menu,
Today is:
Month day, year hour

I would like to request seconds, being:
Month day, year hour second

Thanks.

**Comment by willpower232** [comment]
Can you share a screenshot of where you would like the output changing?

**Comment by AndersonOuverney** [comment]
I prepared a print for you, where the red highlight is.
https://prnt.sc/rq3qxz

**Comment by willpower232** [comment]
This information only relates to a single email and, for us at least, is almost always only a couple of entries. If seconds are important to you, you should be able to update the view file to include the extra information.

In [app/views/messages/activity.html.haml](https://github.com/postalhq/postal/blob/master/app/views/messages/activity.html.haml) you can see there are a few uses of `to_s(:long)` which is where the time gets displayed and you can replace `:long` with a different format if you wish.

Here is some of the documentation with the default options: https://api.rubyonrails.org/v5.1/classes/DateTime.html#method-i-to_formatted_s

Please note that you may need to restart Postal to apply the changes you make.

**Comment by AndersonOuverney** [comment]
This worked exactly the way I was expecting.
We changed the default to: rfc822

Thank you very much for your important support.
