### ISSUE TITLE
Link tracking using html encoding when it should not

### ISSUE THREAD

**Issue by nhadsall** [postalhq/postal#1040]
Tracking converts example.com/lost-password/?key=123&id=456
example.com/lost-password/?key=123&amp;id=456

Notice the &amp; should not be there. Even if the & should be encoded, it should be Percent Encoding like %26. However, in this case it should not be encoded at all. It should remain &.

I'm not sure how tracking could work for anyone with this bug. Perhaps we have a special use case or something, but it is breaking WP password resets. That's about 30% of the internet market. I really want to love postal, but between this and scrambled eggs that come from missing a text version of an email, I just don't think it's a viable option for WP site owners (all my clients).

I'd be happy to put either time or a little money to get behind this project. Is there anything that can be done?

**Comment by willpower232** [comment]
I think there are a things open in this area see #907 and #296 but problems like this need resolving.

I'm not sure your example saved properly as I can't see where the difference is precisely.

**Comment by nhadsall** [comment]
Haha, yeah github tried to fix it for me. https://github.com/postalhq/postal/issues/907 is the same issue. Been open since Nov :(

**Comment by willpower232** [comment]
Ah okay, is wordpress sending the email to postal encoded or not?

**Comment by AndersonOuverney** [comment]
Hello.
Just so I know, are you using smtp or api?

**Comment by shaheryar2014** [comment]
I have the same issue in woocommerce reset page link the link must go to

http://vacsolution.com/my-account/lost-password/?key=5v7He35O5lGK9qL2265o&login=shaheryar.ali%40vacsolution.com&id=45

but go to that link instead

http://vacsolution.com/my-account/lost-password/?key=JWWWhh81y6TlQSazMbRL&amp;login=shaheryar.ali%40vacsolution.com&amp;id=45

after tracking is enabled

I also try to Disable tracking on a per e-mail basis by using this tag on mail header
X-AMP: skip
but no luck. Anyone please help me in this matter.
