### ISSUE TITLE
Unable to send mails

### ISSUE THREAD

**Issue by raiyansarker** [postalhq/postal#1043]
I installed postal and did all the necessary steps. This is my domain: knowforsharing.website. When I send mails using the smtp, it tells me the email is send. I come back to postal admin area and see it is pending. But after a while, it tells me soft bounce instead of pending. I am using AWS ec2 instance and ubuntu 18.04 LTS as my server. I checked 25 port which is open. Please anyone help me. Or you can check whether the 25 port is open or not. Please help me as soon as possible.
![Screenshot from 2020-04-04 12-55-02](https://user-images.githubusercontent.com/38852396/78420725-8e5d0980-7673-11ea-8c7c-a1e9ddd4abc0.png)

**Comment by PeterXQChen** [comment]
If you click into it, whats the reason they give for soft failing?

**Comment by raiyansarker** [comment]
No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com
![Screenshot from 2020-04-06 14-34-14](https://user-images.githubusercontent.com/38852396/78539066-cac76b80-7813-11ea-8277-b8d77a37644e.png)

**Comment by willpower232** [comment]
You will need to use AWS support to request permission to send emails I believe.

**Comment by raiyansarker** [comment]
I told them and they removed the limit. But now I am having both hard fail and soft fail and it is telling me no smtp servers are found!
![Screenshot from 2020-04-07 19-27-49](https://user-images.githubusercontent.com/38852396/78674748-ead75780-7905-11ea-8cdb-40373b43f231.png)

**Comment by PeterXQChen** [comment]
That seems to be a different email address. Are you able to try again with another gmail email address?

**Comment by navinp** [comment]
Your domain knowforsharing.website is blacklisted 
Probably that’s the reason for the bounce
