### ISSUE TITLE
How can I create sender/receiver email address?

### ISSUE THREAD

**Issue by Unumus** [postalhq/postal#1048]
How can I setup sender/receiver email address, and password to it?
To I be able to login from the client standart format, like SMTP server name, email address and password.

**Comment by PeterXQChen** [comment]
You're probably looking for something like mailcow or mail in a box rather than Postal.

**Comment by Unumus** [comment]
@PeterXQChen No, I need Postal. Just though that there is an option to open mailbox in Postal. However I created a separate server for these needs, and setup routes.
