### ISSUE TITLE
Click & open tracking not working 

### ISSUE THREAD

**Issue by hijjawi09** [postalhq/postal#1052]
Click & open tracking not working for me.

I've enabled the Fast server according to the documentation. configured the DNS for click subdomain, modify nginx accordingly(to listen only on IPv4), amended postal.yml with the 2nd IP details, enabled Fast server and finally configured a tracking domain. (Postal management IP is an IPv4, Fast server IP is an IPv6 one). after the configuration, I did a stop then start for postal.

![image](https://user-images.githubusercontent.com/3598114/79467393-68861c00-8006-11ea-9f9b-174f67357509.png)

![image](https://user-images.githubusercontent.com/3598114/79467518-82276380-8006-11ea-847e-31c78a6688fe.png)

![image](https://user-images.githubusercontent.com/3598114/79467177-2eb51580-8006-11ea-8ca4-d55ae148ed34.png)

**Comment by willpower232** [comment]
when you say its not working, could you clarify which part isn't working?

**Comment by hijjawi09** [comment]
When I send an email, URL is not being replaced. (I tried sending emails from management UI and from the API)

**Comment by hijjawi09** [comment]
One more thing, I didn’t figure how Postal track the email opening. I read something about inserting a pixel image in the email body, but didn’t know how to track and find related results.

**Comment by willpower232** [comment]
Check the tracking domains page, make sure that the domain has two ticks and then you can also edit the domain to see that both things are being tracked.

The tracking domain needs to be in the same organization as the credential you're sending from.

**Comment by hijjawi09** [comment]
let's say I'm using example.com domain, I'm using (click.example.com) as tracking domain with disabled SSL (CNAME is configured correctly according to postal DNS check) and I'm sending from email address (test@example.com) but still not working.

**Comment by willpower232** [comment]
Tracking is only activated if there is a tracking domain with valid DNS in the same organization as the domain you are using. If it isn't happening, then either the DNS isn't valid or you're using a different organizations credential.

**Comment by hijjawi09** [comment]
I figured out that I was using an organisation level defined domain (with the same name of my mail server domain), accordingly I changed the tracking domain to the mail server one. 
Tracing is working now where I can see if an email is opened (if the pixel image downloaded) and URLs are being converted but cannot reach my click domain (click.mydomain.com) even CNAME is configured accordingly, and I have no firewall. how can I check if fast server if listening properly? 

when I curl (click.mydomain.com) at the server, I got (Hello) response, but cannot curl that link from outside.

hint: I changed the (/etc/gai.conf) to make IPv4 as preferred (before doing this, postal wasn't able to send emails), uncomment this line (precedence ::ffff:0:0/96  100)

**Comment by hijjawi09** [comment]
Update:  

I've changed the IPv6 (the fast server IP) to a floating IP (on DigitalOcean) and my tracking domain is responding with (Hello) now. click & open tracking is working perfectly from management UI, URL converting not work when send an email using API with (html_body) parameter. it's only working when use (plain_body) parameter.

**Comment by hijjawi09** [comment]
Final update:

It's working fine now on both management UI and API, I found an issue with my HTML body.

**Comment by Rahul-Singla** [comment]
Hi,

I am also trying to configure IPv6 for tracking. If possible, please tell how you configure nginx ?
