### ISSUE TITLE
STARTTLS not supported and the user requires enforcement

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#1053]
I am using Gmail to send and receive emails, and using the SMTP credentials from my Postal setup.

Everything was working fine, until I started getting this error:

> STARTTLS not supported and the user requires enforcement., code: 500

At first I thought it was nothing, then the 3rd email bounced back... 3 emails send to 3 different companies, all returned this error.

I went into my Gmail SMTP settings (Gmail > Settings > Accounts & Imports > Edit info per email), then you get a popup window where you have to fill in your SMTP info.

Well, my SMTP is not connecting anymore, and I keep getting the same error listed above.

My SMTP was working fine with TLS, port 25 in Gmail, not anymore.

Using the **unsecure** option with port 25, is however working and delivering my emails.

**Comment by navinp** [comment]
Okay, some good news (and still some bad news):

Bad news: TLS with port 25 is not working anymore in Gmail (Did Gmaiil change their policy?)

Good news: you can use unsecure in Gmail when configuring your email, instead of TLS and SSL. Postal will stil **encrypt** your emails and deliver it to your recipients. They won't see an ugly "This email is not encrypted" label in Gmail (yeey for Postal, 1-0)

**Comment by willpower232** [comment]
Firstly I will say this wasn't what Postal was designed for so its possible this will never be free of problems.

Did you give an SSL certificate to the `smtp_server` config in your postal.yml?

**Comment by navinp** [comment]
It may not have been designed for this purpose but have been using it for this, for a while now and it saved me some money.

I just route emails to my Gmail and send emails from my Gmail using my company email address. 

I will check smtp_server and let you know ASAP.
