### ISSUE TITLE
How To Enable Open AND Click Tracking with additional IP

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#1055]
Hello Everyone,

I set up a Postal server using the quick install method and it's working well.

and I configure the open and click tracking using this link https://github.com/postalhq/postal/wiki/Click-&-Open-Tracking

but the open and click tracking don't work.

Thes step I have to do:-
1 step:-  Setup Let's Encrypt
2 step:- Enable the fast server

fast_server:
  enabled: true
  bind_address: 92.168.10.12

DNS
 track_domain: track.cloud.example.com

and I have pointed this IP 92.168.10.12 on this track.cloud.example.com

this 92.168.10.12 is an additional IP on the same server

3 step:-  /etc/nginx/sites-enabled/default
server {
    listen [::]:80;
    listen 92.168.10.12:80;
    server_name cloud.example.com;
    return 301 https://92.168.10.12;
}

server {
    listen [::]:443 ssl;
    listen 92.168.10.12:80;
    root /opt/postal/app/public;
    server_name cloud.example.com;
    ssl_certificate      /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/cloud.example.com/privkey.pem;

when I have done all these processes:-
Then I have postal stop and postal start
now the postal status is:- 
root@cloud:~# postal status
Procodile Version   1.0.25
Application Root    /opt/postal/app
Supervisor PID      27020
Started             2020-04-20 04:07:52 -0400

 * fast.1 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      04:07        pid:27026    respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.1           Failed       04:08        pid:27440    respawns:5      port:-        tag:-

and postal portal is not open

Please help me on this

**Comment by reshadman** [comment]
You need to bind the nginx config you are mentioning to the web management IP defined in your dns only so remove the `listen [::]:80;` and `listen [::]:443` parts of the config file. Then stop the nginx server and run `postal restart` then start the nginx server.

**Comment by willpower232** [comment]
As above, you have only shown one IP address to be on the server, you need one to be mentioned in nginx and the other to be the fast server.

**Comment by zeba121** [comment]
Hello @willpower232  and @reshadman,

@reshadman  I have done this all step according to your guideline I have to remove the listen [::]:80; and listen [::]:443 part of the Nginx default config file. then I have stopped the Nginx services and run postal restart then start the Nginx service.

server {
    listen 84.39.142.188:80;
    server_name cloud.example.com;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 84.39.142.188:443 ssl;
    root /opt/postal/app/public;
    server_name cloud.example.com;
    ssl_certificate      /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/cloud.example.com/privkey.pem;

@willpower232 this my postal server ifconfig status:- 

ens3      Link encap:Ethernet  HWaddr XX:00:0eX:00:X0:X0
          inet addr:51.62.34.28  Bcast:51.62.34.28  Mask:255.255.255.255
          inet6 addr: fXX:00:0eX:00:X0:X0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2688854 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1883508 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:242056726 (242.0 MB)  TX bytes:270373919 (270.3 MB)

ens3:1    Link encap:Ethernet  HWaddr XX:00:0eX:00:X0:X0
          inet addr:84.39.142.188  Bcast:54.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

ens3:2    Link encap:Ethernet  HWaddr XX:00:0eX:00:X0:X0
          inet addr:84.39.142.189  Bcast:54.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1



and the fast server IP is another VPS Server static IP 
can I use additional IP of the same server or another VPS Server static IP

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 122.27.81.72

If I have to do the wrong process so, please guide me in the right way.

Thank you both for replying to me.

**Comment by willpower232** [comment]
As you can see from the information you have shared, IP address 122.27.81.72 is not listed in your ipconfig.

I'd also note that 122.27.81.72 and 51.62.34.28 are wildly different from your other IP addresses so may not actually be directly available to you.

**Comment by zeba121** [comment]
Hello @willpower232 

This is my main IP or static IP 51.62.34.28 postal server is installed on this IP
These IPs are an additional IPs 84.39.142.188,  84.39.142.189 from the main server.



This is another server static IP 122.27.81.72.


and my question is which IP I can use for fast server and which IP I can use for the Nginx default config file.



please check again my configuration I am again sharing my configuration:-

postal.yml

web:
  # The host that the management interface will be available on
  host: cloud.example.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 54.39.153.120

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
 mx_records:
    - mx.cloud.example.com
  smtp_server_hostname: cloud.example.com
  spf_include: spf.cloud.example.com
  return_path: rp.cloud.example.com
  route_domain: routes.cloud.example.com
  track_domain: track.cloud.example.com
  dkim_identifier: cloud

workers:
  quantity: 4
  threads: 4

smtp_server:
  host: 167.114.112.240
  port: 587
  tls_enabled: true
  tls_certificate_path:  etsencrypt/live/cloud.example.com/fullchain.pem  # Defaults to config/smtp.cert
  tls_private_key_path: etsencrypt/live/cloud.example.com/privkey.pem  # Defaults to config/smtp.key
  tls_ciphers:
  ssl_version: TLSv1_2
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false


smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: cloud
  from_address: cloud@example.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 7654dec232b39307e84f2f5d037fe34b09c91619ee5a1d2f9022ec71f82883d449d5e685fb7f057324f7811076c758ace778bd62bb7db08fbf0c92552e30983e4c3fc006f8c7791c77a00b18a885715ad3614c8aa324a0c94ebb9c7bbe15a88e85faeffd6e402d2e8619efc9110c98deade3f5416d83be20061bdf97e8076deb




/etc/nginx/sites-enables/default:-

server {
    listen 167.114.112.240:80;
    server_name cloud.example.com;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 167.114.112.240:443 ssl;
    root /opt/postal/app/public;
    server_name cloud.example.com;
    ssl_certificate      /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/cloud.example.com/privkey.pem;

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }
}



**root@cloud:~# ifconfig**

ens3      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX
          inet addr:167.114.112.240  Bcast:167.114.112.240  Mask:255.255.255.255
          inet6 addr: XX.XX.XX.XX.XX:XXXX/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4799408 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3379866 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:426292500 (426.2 MB)  TX bytes:448464472 (448.4 MB)

ens3:1    Link encap:Ethernet  HWaddr XX.XX.XX.XX:XX
          inet addr:54.39.153.120  Bcast:54.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

ens3:2    Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX
          inet addr:54.39.153.121  Bcast:54.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

**Comment by willpower232** [comment]
The easiest way of seeing what is wrong is running the command from `postal status` directly so to see what is wrong with the fast server, try running `bundle exec rake postal:fast_server` and see what the output is. Usually it is related to IP addresses but could be something else.

**Comment by zeba121** [comment]
Hello @willpower232 thank you for replying to me.

see the postal status:-

root@cloud:~# postal status
Procodile Version   1.0.25
Application Root    /opt/postal/app
Supervisor PID      2808
Started             2020-04-23 10:23:55 -0400

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      23/04/2020   pid:2814     respawns:0      port:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.2           Running      23/04/2020   pid:9192     respawns:0      port:-        tag:-

|| worker
|| Quantity            4
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.5         Running      23/04/2020   pid:9170     respawns:0      port:-        tag:-
|| => worker.6         Running      23/04/2020   pid:9172     respawns:0      port:-        tag:-
|| => worker.7         Running      23/04/2020   pid:9174     respawns:0      port:-        tag:-
|| => worker.8         Running      23/04/2020   pid:9176     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      23/04/2020   pid:9198     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      23/04/2020   pid:9183     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Running      23/04/2020   pid:9194     respawns:0      port:-        tag:-

**bundle exec rake postal:fast_server**

root@cloud:~# bundle exec rake postal:fast_server
Could not locate Gemfile or .bundle/ directory
root@cloud:~#

**Comment by willpower232** [comment]
Well your fast server seems to be running now so do you still have a problem?

**Comment by zeba121** [comment]
yes,  

I don't no how can I configure it because open and click tracking is not working.

**Comment by willpower232** [comment]
`Hello` means that it is working.

Now you have to add a tracking domain in the Postal UI. It should be next to the domains list. Once you have that, the emails you send through that Postal organization should be tracked.

**Comment by zeba121** [comment]
@willpower232 

Where I should have added track.example.com in the Postal UI.

Because I have to try to add track.example.com postal could not be added to this domain.

![image](https://user-images.githubusercontent.com/46315368/80566944-b55bf080-8a11-11ea-9ccb-ce217a17420b.png)


Please check is this correct or not because track.cloud.example.com is the subdomain of example.com.

and I have seen in the previous issue https://github.com/postalhq/postal/issues/937#issuecomment-565839003

he has added the click.example.com domain where he was added.


And where is this option available in Postal UI?
https://github.com/postalhq/postal/issues/707#issuecomment-446160020

**Comment by zeba121** [comment]
Hello  @willpower232 

I have to add a tracking domain in the Postal UI.

![image](https://user-images.githubusercontent.com/46315368/80583015-48565400-8a2d-11ea-96df-f43e7061760d.png)


Now how can I track open or click Because my application is PHP based?

**Comment by willpower232** [comment]
You have a domain added but judging by the last screenshot, your fast server may not be on the right ports, can you share the output of `netstat -lnp`?

As you can see in the UI, if you've set up the DNS correctly then Postal will be able to create its own SSL certificates for the tracking domain provided you have run the `register-lets-encrypt` command as per https://github.com/postalhq/postal/wiki/Click-&-Open-Tracking.

Once it is working, Postal should automatically track messages sent in that organization so you can use webhooks to report that activity back to your application (https://github.com/postalhq/postal/wiki/Webhook-Events-&-Payloads) or just keep going into Postal.

**Comment by zeba121** [comment]
root@cloud:~# netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1851/sshd
tcp        0      0 167.114.112.240:443     0.0.0.0:*               LISTEN      14669/nginx -g daem
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      14512/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1590/beam
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      31610/mysqld
tcp        0      0 167.114.112.240:80      0.0.0.0:*               LISTEN      14669/nginx -g daem
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1802/epmd
tcp        0      0 54.39.153.120:5010      0.0.0.0:*               LISTEN      14514/[postal] fast
tcp        0      0 54.39.153.120:5011      0.0.0.0:*               LISTEN      14514/[postal] fast
tcp6       0      0 :::22                   :::*                    LISTEN      1851/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      14669/nginx -g daem
tcp6       0      0 :::5672                 :::*                    LISTEN      1590/beam
tcp6       0      0 :::587                  :::*                    LISTEN      14529/[postal] smtp
tcp6       0      0 :::80                   :::*                    LISTEN      14669/nginx -g daem
tcp6       0      0 :::4369                 :::*                    LISTEN      1802/epmd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           25769/dhclient
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     8630     1/init              /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     17424    2213/systemd        /run/user/0/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     9149     1/init              /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     8635     1/init              /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     8637     1/init              /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     8638     1/init              /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     12738    1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     12737    1/init              /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     22569532 14506/app)          /tmp/postal/pids/procodile.sock
unix  2      [ ACC ]     STREAM     LISTENING     2180267  31610/mysqld        /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     12722    1/init              /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     12723    1/init              /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     12741    1/init              /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     12721    1/init              /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     12883    1577/iscsid         @ISCSIADM_ABSTRACT_NAMESPACE
root@cloud:~#

**Comment by zeba121** [comment]
Nestat -tnp Output:-

![image](https://user-images.githubusercontent.com/46315368/80681558-8e1f2500-8ade-11ea-819b-64b2e26dd0a8.png)

**Comment by willpower232** [comment]
Apparently you have changed the fast_server ports to 5010 and 5011 so you should change those to be 80 and 443 and then make sure your tracking domain goes to the 54.39.whatever IP address.

**Comment by zeba121** [comment]
![image](https://user-images.githubusercontent.com/46315368/80700905-1fe95b00-8afc-11ea-8409-76c78f2c4461.png)

**Comment by zeba121** [comment]
Hello @willpower232 

Please help me on open and click tracking is not working. please guide where I did misconfigure in this.

**Comment by willpower232** [comment]
It looks like it is set up fine, when you say it isn't working, what do you mean?

**Comment by zeba121** [comment]
I mean to say open and click tracking is not track in the postal organization.

See this

![image](https://user-images.githubusercontent.com/46315368/81267532-40696600-9064-11ea-9d7f-a9b1f9e24a3b.png)


but the tracking click is not working when I click on this link.

**Comment by willpower232** [comment]
If you see "the page you were looking for doesn't exist" then that means you've linked to the Postal UI instead of the click tracking in the DNS.

If you see `NXDOMAIN` it means that the DNS is missing completely.

Either way it sounds like your DNS records are very wrong.
