### ISSUE TITLE
Can't verify but the value is there... ?

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#1058]
Hello, I am getting this error:

> There seems to be something wrong with your DNS records. Check below for information.

When I check this via SSH
dig -t txt domain

I do get the values, which I can also see using other tools like Google Toolbox DNS. 

So the DNS records are added to the domain, and can be seen using online tools like Whatsmydns, but my Postal install is returning this error instead of showing me verified.

What may be causing this problem?

**Comment by navinp** [comment]
Okay. 

Weird things are happening.

Using Google's Toolbox and WhatsMyDNS I see the DNS values, but using MXToolbox, I don't see any value...

**Comment by AndersonOuverney** [comment]
Hello
Are you sure that your domain's DNS records are correct and propagated across all servers?

You can try to clear your domain's DNS cache on google.

Any questions be sure to ask.

**Comment by willpower232** [comment]
Do you have a CNAME as your root record or anything else overlapping in your DNS zone?
