### ISSUE TITLE
Hard Fail 550 Action not taken In Postal after setup every Dns setting ok except delivery

### ISSUE THREAD

**Issue by mishudm** [postalhq/postal#1059]
Hello, i install Postal a mail server. I setup dns setting like this

Type	Name	Value	TTL	
A	@	134.122.9.60	
A	mail	134.122.9.60	
A	rp.mail	134.122.9.60	
A	track.mail	134.122.9.60	
CNAME	psrp	rp.mail.tagtagpro.club
MX	@	mx.mail.tagtagpro.club (Priority: 10)
MX	@	mail.tagtagpro.club (Priority: 10)	
MX	routes.mail	mail.tagtagpro.club (Priority: 10)	
MX	rp.mail	mail.tagtagpro.club (Priority: 10)	1 Hour
TXT	@	v=spf1 a mx include:spf.mail.tagtagpro.club ~all	
TXT	postal-g5uaqq._domainkey	v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDaFynZpq7yJBF7Ug6JMAnA1CkaFFgVtH1v08V25+noNoJHcjnIOrESCHCzy4mRnolgaMA5VZsFYxihTnwTrO/LQNxEFZJNaDjmbiXXqMTucW4Dt6PNjnL6OiJ7XhYOl+idh670tgIkCKOBPpKa+oqIi3pUyQ7/ZZMYdsWIuccUEQIDAQAB;	1 Hour	Edit
TXT	rp.mail	v=spf1 a mx include:spf.mail.tagtagpro.club ~all
TXT	spf.mail	v=spf1 ip4:134.122.9.60 ~all	
TXT	_dmarc	v=DMARC1; p=reject; sp=reject; rua=mailto:postmaster@tagtagpro.club

/opt/postal/config
web:
  # The host that the management interface will be available on
  host: mail.tagtagpro.club
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mail.tagtagpro.club
  smtp_server_hostname: mail.tagtagpro.club
  spf_include: spf.mail.tagtagpro.club
  return_path: rp.mail.tagtagpro.club
  route_domain: routes.mail.tagtagpro.club
  track_domain: track.mail.tagtagpro.club

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: mail@tagtagpro.club

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 31c4ebce082f79552f3083b6bc38019d39f9c5c4f08d17627176e516d9248633a59eb4f7cdaa0d16fbe97115e4cdccd006fde1eb00c2ddcfb0f414746802317d95ed47c152bcd07fd5fc045580b2cc02ec2849230790753f9ab69414d5281aeec7d0ca3d42ac4b834f0a679566fb658a5b30d925b8c23959be4db70ea54e9a74

Also i checked everything is ok, no ip blacklisted. And my port 25 is open. 
but no mail is delivering. every mail is failed to send mail. 
getting this error
Permanent SMTP delivery error when sending to mta5.am0.yahoodns.net (67.195.204.73)
Hard Fail
550 Action not taken
Support Ref: MHSXUXRP
I have tried every possible domain, Result is same
If anyone can help me , want to see in log in mail me at mishudm12@gmail.com , i will give full acceess to postal and Dns. Please , I can pay if anyone fix this

**Comment by AndersonOuverney** [comment]
Hello.
Can you guarantee that all changes in your DNS zones are reached by any host on the internet, or have you made the changes only on the postal server?

**Comment by mishudm** [comment]
I can guaranteed that everything i did is ok. What i give above is like dns i setup in domain. And also i made every thange in postal

**Comment by willpower232** [comment]
Do you get the same error message from all the emails you are trying to send? You can expand them a little to get some more information in the UI

**Comment by mishudm** [comment]
yes, getting same error

**Comment by willpower232** [comment]
Have you tried emailing a different address? This error usually means the recipient doesn't exist or their inbox is full.

**Comment by mishudm** [comment]
of course i send diferrent mail and also to different domain, i mean to , gmail, yahoo hotmail also in custom domain. I mentioned it on my discription. otherwise why would i give post here? also i give every details i made on my setup

**Comment by willpower232** [comment]
Are you getting the same error message for all the different addresses you're trying?
