### ISSUE TITLE
Postal Telnet

### ISSUE THREAD

**Issue by AndersonOuverney** [postalhq/postal#1060]
How to perform postal test with telnet?

Hello guys, I'm trying to do a test via telnet, I don't know if that is possible.
What I'm trying to do is simulate email delivery via the command line.

telnet mypostal.com 25
EHLO mylocalserver.com
AUTH LOGIN
(username in base64)
(base64 user password)

I have the following response from the postal
SMTP << 235 Granted for (my username)

Following to test the message:

MAIL FROM: teste@mydomain.com (This domain is configured correctly in postal, SPF and DKIM)
RCPT TO: teste@mydomain2.com
DATE
Here I write what I want to test

(. to end)
.
Finally I get the following return message
SMTP << 530 From / Sender name is not valid

I've already consulted the following links here
https://github.com/postalhq/postal/issues/863
https://github.com/postalhq/postal/issues/728

None of them can solve the problem.

NOTE: Remembering that through an email client, I can send emails normally through the domain "mydomain.com"

**Comment by willpower232** [comment]
This indicates that the credential you are using (i.e. the username) does not cover the domain you are using.

See also #863 and #728

**Comment by AndersonOuverney** [comment]
Hello.
I read it, read it again and for sure I read the 2 topics again.
What I currently do is:
I'm going to the organization/server
There are dozens of domains already created, authenticated and functioning.

When I refer to domains created, authenticated and functioning, I mean that I created a credential on the SMTP server, on my EXIM server I can authenticate without problems and send emails through *@domain.com. These emails are sent through an email client as a roundcube.

The problem is when I am going to connect via SMTP, I am not sure if I am doing it right.

I am inserting the user in org/server format and the password generated by the postal.
Both are available in the url (help/outgoing)

What am I missing?

**Comment by willpower232** [comment]
The domain in the FROM address (mydomain.com in your example) must be in the same organization as the credential you're using. Do you have multiple organizations in your Postal setup?

**Comment by rohitthakral** [comment]
I have exact same problem and no we don't have multiple organisations in our postal setup. 

The problem is only with the telnet. PHP Mails etc are working fine.

**Comment by Kosha-account** [comment]
Hello, I failed into same problem, not sure what I do wrong, would be highly appretiate any help.
Below is the server configuration and my tries using swaks
Organization: test-org
Mail server: test-server
Domain: vseki.bg
From: test@vseki.bg

![Image](https://github.com/user-attachments/assets/1863a73f-8f82-48b6-a84a-6fc171c2ba9c)

![Image](https://github.com/user-attachments/assets/d534f4a2-db32-4873-ac96-af235d33a0a9)

![Image](https://github.com/user-attachments/assets/811344d6-00d1-4467-ae97-57cd419e90ab)

![Image](https://github.com/user-attachments/assets/5247b815-6047-4a59-abd6-90e9ae91b6c5)

![Image](https://github.com/user-attachments/assets/0b7fa493-5c34-46b4-809f-df2b3b29cd27)
