### ISSUE TITLE
(HELP! still got an issue) after a few intensive days, i finally got it working with mailwhizz

### ISSUE THREAD

**Issue by wrt12345** [postalhq/postal#1061]
Hi Postal Users,
If someone with more experience could point me in the right direction..... 

i'm surprised i actually made it this far :) bit of a noob 

1. my mails will only send with my ip address, how do i change it to my hostname ?
2. how do i change the sender address, at present its something like admin@aaaa.bbbb.com
i would like it to be admin@bbbb.com and remove the sub domain part,
i am presuming i should be editing something else rather than the postal.ybl file 

thanks for viewing & thanks in advance and all stay safe......
Wayne

**Comment by gacott** [comment]
Please share how you fixed this so that others could benefit.

**Comment by wrt12345** [comment]
> Please share how you fixed this so that others could benefit.

i honestly dont know tbh , but it defo has something to do with my domain name as i cant login to postal only from the ip i will fully update people when i figure it out , but it is working from mailwhizz .

**Comment by willpower232** [comment]
1. You will need to have pointed a DNS record at your servers IP address at some point so you should be able to use that?

2. if you can't add `bbbb.com` to Postal in the UI then you could have a look at the Send As Any setting which might help but could complicate your integration with your other software.

**Comment by wrt12345** [comment]
>     1. You will need to have pointed a DNS record at your servers IP address at some point so you should be able to use that?
> 
>     2. if you can't add `bbbb.com` to Postal in the UI then you could have a look at the Send As Any setting which might help but could complicate your integration with your other software.

hi, i sorted out this issue out, thanks anyway..... can someone point me to an example postal.yml file completed and filled out, i have everything working from mailwhizz just having an issue getting a 10/10 score dmarc dkim spf errors even though postal saying we all good and my mind is bamboozled on what postal.yml needs to be properly configured

**Comment by willpower232** [comment]
Postal merges in the defaults so you probably have what you need covered. What errors do you have?

**Comment by wrt12345** [comment]
I have 1 fully working vultr server running postal sending fine.
QUESTION: has the files for postal changed in the last fews days or something? 
as i have just added a second server for testing and i have just done the normal install, and now getting softmail when i send, scratching my head is an understatement right now with 1 working and 1 not working and i have tried 6 times,am i missing something as i have done nothing different but everytime i try now, i am getting softfail done nothing different at all......
