### ISSUE TITLE
Postal changes DKIM prefix dynamically.

### ISSUE THREAD

**Issue by Unumus** [postalhq/postal#1063]
Hello!

I got an issue. The postal changes the DKIM prefix key dynamically like once in 24h. So the DKIM records are become not valid. 

One day it is was like:
postal-dv5esd._domainkey

And now it becomes:
postal-ek3edu._domainkey

Why may this happen? How can I get a static DKIM key prefix?

**Comment by Unumus** [comment]
I found the keys in the database. However, that is a better approach to add both keys or delete and leave one?

**Comment by willpower232** [comment]
Postal doesn't change the prefix for a domain but if you added a new domain, or deleted and re added one, it would probably change. You also only have the one installation of Postal and one database server right?

You should use whatever is currently displayed on the DNS page.

**Comment by Unumus** [comment]
@willpower232 
In my DB have two dkim identifier: the first organization, the second server(it was by default). In my DNS setting panel, these keys alternate. And I get an error when this happens. Currently, I added both keys to my DNS records, and it seems that it works. However, why it may happen? And what is a better approach to fix it?

<img width="298" alt="Снимок экрана 2020-04-28 в 12 17 44" src="https://user-images.githubusercontent.com/52177550/80470152-449dd100-894a-11ea-80bd-663a8369645d.png">

**Comment by Unumus** [comment]
I found more detailed behavior. We have one user in  Postal(admin).  And two-person login to there. The first user in the admin panel sees one DKIM, the second another.

**Comment by willpower232** [comment]
If the server you added the domain to is in the organization that already had it, you don't need to add the domain again.

If you added a user in the UI, they aren't an admin by default so can't see as much of the system. We've just been using the original make user command from the CLI to create our users as we don't need to differentiate between them.
