### ISSUE TITLE
Error 500 on queue list messages 

### ISSUE THREAD

**Issue by ammonavis** [postalhq/postal#1064]
![image](https://user-images.githubusercontent.com/26895875/80398220-8f223d80-88b7-11ea-949d-a9b4894fad93.png)

When i click on queue list i have always the same error : 

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

I don't find the log file to look ....

**Comment by willpower232** [comment]
You will find the log files in `/opt/postal/log`, you might find the answer in `puma.log` or `rails.log`.

**Comment by BornTKill** [comment]
Hello,

Have the same error 👍 

==> rails.log <==
[web.1:8747] [2020-10-02T15:16:09.128] INFO -- : Started GET "/org/quicksign/servers/prod-smtp-01/queue" for 127.0.0.1 at 2020-10-02 15:16:09 +0200
[web.1:8747] [2020-10-02T15:16:09.130] INFO -- : Processing by ServersController#queue as HTML
[web.1:8747] [2020-10-02T15:16:09.130] INFO -- :   Parameters: {"org_permalink"=>"quicksign", "id"=>"prod-smtp-01"}
[web.1:8747] [2020-10-02T15:16:09.150] INFO -- :   Rendering servers/queue.html.haml within layouts/application
[web.1:8747] [2020-10-02T15:16:09.158] INFO -- :   Rendered servers/_sidebar.html.haml (7.4ms)
[web.1:8747] [2020-10-02T15:16:09.181] INFO -- :   Rendered servers/_header.html.haml (22.6ms)
[web.1:8747] [2020-10-02T15:16:09.182] INFO -- :   Rendered messages/_header.html.haml (0.6ms)
[web.1:8747] [2020-10-02T15:16:09.194] INFO -- :   Rendered messages/_list.html.haml (11.3ms)
[web.1:8747] [2020-10-02T15:16:09.195] INFO -- :   Rendered servers/queue.html.haml within layouts/application (44.7ms)
[web.1:8747] [2020-10-02T15:16:09.195] INFO -- : Completed 500 Internal Server Error in 65ms (ActiveRecord: 7.3ms)
[web.1:8747] [2020-10-02T15:16:09.196] FATAL -- :   
[web.1:8747] [2020-10-02T15:16:09.196] FATAL -- : ActionView::Template::Error (No message found matching provided query {:id=>95609}):
[web.1:8747] [2020-10-02T15:16:09.196] FATAL -- :     1: %ul.messageList
    2:   - for message in messages
    3:     - if message.is_a?(QueuedMessage)
    4:       - message = message.message
    5:     %li.messageList__message
    6:       = link_to organization_server_message_path(organization, @server, message.id), :class => 'messageList__link' do
    7:         .messageList__details{:class => 'messageList__details--' + message.scope}
[web.1:8747] [2020-10-02T15:16:09.196] FATAL -- :   
[web.1:8747] [2020-10-02T15:16:09.196] FATAL -- : lib/postal/message_db/message.rb:13:in `find_one'
lib/postal/message_db/database.rb:36:in `message'
app/models/concerns/has_message.rb:8:in `message'
app/views/messages/_list.html.haml:4:in `block in _app_views_messages__list_html_haml__3508256687253355118_59368040'
app/views/messages/_list.html.haml:2:in `each'
app/views/messages/_list.html.haml:2:in `_app_views_messages__list_html_haml__3508256687253355118_59368040'
app/views/servers/queue.html.haml:21:in `_app_views_servers_queue_html_haml__3414764610165927746_58862340'

==> puma.log <==
10.10.7.113 - - [02/Oct/2020:15:16:09 +0200] "GET /500 HTTP/1.0" 500 1477 0.0708

**Comment by willpower232** [comment]
Can you try https://github.com/postalhq/postal/issues/521#issuecomment-430258301?

**Comment by BornTKill** [comment]
@willpower232 That fix my issue ! Thanks !
