### ISSUE TITLE
spf not recognized

### ISSUE THREAD

**Issue by cyayung** [postalhq/postal#1065]
Trying to send mail into China services but receiving hard fails blocked by anti spam. Works on other servies. Seems like the spf used wasn’t recognized in China. Currently hosting on AWS and Route 53. What are my options?

**Comment by willpower232** [comment]
What are the details of the error message that Postal tells you? You should be able to see this in the UI but might have to expand it to get more information.

If you're using AWS, did you ask them to set up reverse DNS for your server and also to allow you to send email from your instances?

**Comment by willpower232** [comment]
You could try using https://whatsmydns.net to see how your SPF record appears around the world, it might not be as you think. I think https://mxtoolbox.com also has an SPF checker in it.

It might be that whatever you're emailing is particularly strict about SPF so make any minor problem with your record sound really bad, I can't say I've seen such an error from an email provider before.
