### ISSUE TITLE
MX record clarification

### ISSUE THREAD

**Issue by shankardevy** [postalhq/postal#1066]
The document says

> 
> Route domain - if you wish to receive incoming e-mail by sending messages directly to created routes in Postal, you'll need to configure a domain for this just to point to your MX servers.
>
> `
> routes.mail.yourdomain.com.   IN    MX    10 mx.mail.yourdomain.com
> `

1. What record needs to be created for `mx.mail.yourdomain.com` ?
2. Is it `mx.mail.yourdomain.com` or just `mail.yourdomain.com` ?

The google groups link in the repo's readme is giving me access denied message. So I couldn't use that for asking support questions.

**Comment by willpower232** [comment]
see #1051
