### ISSUE TITLE
Spf TEMPERROR--Urgent

### ISSUE THREAD

**Issue by omkarwebservice** [postalhq/postal#1068]
I updated dns but showing Spf TEMPERROR. I tried everything but no progress.
Please any body know about it then please help to resolve this issue.

**Comment by omkarwebservice** [comment]
![spf-error](https://user-images.githubusercontent.com/64598471/80724192-2fc66680-8b1f-11ea-9037-578fa04d7516.png)
![dns](https://user-images.githubusercontent.com/64598471/80724207-3359ed80-8b1f-11ea-89fa-6a3d7e05ca68.png)

**Comment by omkarwebservice** [comment]
![spf-error](https://user-images.githubusercontent.com/64598471/80724883-f8a48500-8b1f-11ea-8963-85e405d9ddcd.png)
![postal](https://user-images.githubusercontent.com/64598471/80724897-fc380c00-8b1f-11ea-9b80-c75b5b6582e5.png)

**Comment by willpower232** [comment]
The wiki mentions that you should have an `spf.postal.yourdomain.dom` record which is an SPF record permitting the Postal server.

The domain you add to Postal will then reference this record.

Have you created that record?

**Comment by omkarwebservice** [comment]
![dns](https://user-images.githubusercontent.com/64598471/80768195-5c9e6c00-8b67-11ea-99e3-30030ac73aa0.png)
![PANEL](https://user-images.githubusercontent.com/64598471/80768203-6031f300-8b67-11ea-8594-b3171f73cda9.png)

**Comment by omkarwebservice** [comment]
KINDLY FIND THE ATTACHMENTS

**Comment by omkarwebservice** [comment]
Kindly find the attachments. I tried everything. In mx tool its showing my
spf record approved but when i send mail to gmail, yahoo or any other isp
its showing me temperror.

**Comment by omkarwebservice** [comment]
i made the changes in yml file and added my domain

**Comment by omkarwebservice** [comment]
Problem solved
