### ISSUE TITLE
Ubuntu LTS 20.05  error

### ISSUE THREAD

**Issue by diegolr62** [postalhq/postal#1069]
The quick installation script is not working, the error says:

Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Is there any  work around?

Regards
DiegoL
![imagen](https://user-images.githubusercontent.com/64618045/80767536-c558fa80-8b0d-11ea-9157-f47318a03e67.png)

**Comment by jtraulle** [comment]
The quick installation script is for Ubuntu 16.04, not 20.04 :wink:

**Comment by willpower232** [comment]
It seems that PPA is for providing ruby versions that aren't included by default, its not immediately obvious whether they intend to support 20.04, its likely that they will do but thats down to them.

Fortunately, its likely that the new version of ubuntu includes a more recent version of ruby so the need for this PPA isn't necessarily immediate. You could download a copy of the script and edit it to install whichever version of ruby is available to you.

**Comment by jtraulle** [comment]
I installed it manually on Ubuntu LTS 20.04 without problem using ruby version (2.6) provided in the distro repos.
