### ISSUE TITLE
Unable to activate SSL/TLS SMTP, no error message

### ISSUE THREAD

**Issue by irdsol** [postalhq/postal#1070]
Hello!

Hi have added at the end of the file (/opt/postal/config/postal.yml)

smtp_server:
  port: 587
  tls_enabled: true
  tls_certificate_path: /etc/postal/certs/smtp.cert
  tls_private_key_path: /etc/postal/certs/smtp.key

And generated smtp.cet and smtp.key in /etc/postal/certs/ with command :
openssl req  -nodes -new -x509  -keyout smtp.key -out smtp.cert

After rebooting the server, TLS isn't activated.

I have also tested with let's encrypt certificates  with :  
smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.example.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.example.com/privkey.pem

(with my FQDN in the path)

And rebooted, but same thing, TLS not fonctionning.

In both cases SMTP connection with no encryption work perfectly, but I need a secured connection.

When I say Isn't working I mean SMTP client makes encryption errors when SSL/TLS enabled.

Any Ideas?

Thanks for your help!

**Comment by willpower232** [comment]
You say you added those lines at the end, were they not already present higher up?

**Comment by irdsol** [comment]
No, I checked first.

Plus the SMTP server is listening on port 587, this proves that the port setting has been applied.

But strangely the SMTP server is working on port 587 with no encryption because TLS not working at all..

**Comment by willpower232** [comment]
Oh I missed that. Postal SMTP is intended to run on port 25 so I'm not sure if that will be a problem.

Can you tell us what error you're getting? If you aren't getting one you'll have to watch the smtp_server log file to see what the problem is.
