### ISSUE TITLE
Using Django core mail package with Postal - Tag functionality

### ISSUE THREAD

**Issue by shravin** [postalhq/postal#1072]
I am using django core mail package with Postal. I am able to send messages via Postal. This was quick to setup and work, so thats great.

I am not able to set the tags in the email through the library by either doing message.__set_attr or by sending 'tag'

I see that there is no python integration provided. Any reason why you have not been able to support python or its supported frameworks?

Will be extremely thankful if you can help me out with this.

**Comment by willpower232** [comment]
Interesting, I seem to remember someone else having problems with this but couldn't find it again. Are you able to share your code?

I assume python hasn't been anyones speciality that has been involved with Postal so far so it hasn't been made. If you're able to create a python library, that would be cool.

**Comment by tiltec** [comment]
FYI, I'm using postal+django with a self-written extension for [django-anymail](https://github.com/anymail/django-anymail). I have plans to eventually get the extension merged, but there's still some stuff missing: https://github.com/anymail/django-anymail/pull/166
It should support tags already, but I didn't test that yet.

Not sure if that's interesting to you, I guess you are going the SMTP route with django core mail?

**Comment by shravin** [comment]
@tiltec - Thank you so much for the reply, I will take a look. (Sorry, for the delayed response). 
@willpower232 - 

Thank you for the reply. Here is the code:

```
headers = {"tag": "1234"}
msg = EmailMessage(subject, message, DART.settings.FROM_EMAIL_ADDRESS, allowed_receivers, headers=headers)

//The headers get set in the extra_headers attribute inside EmailMessage

msg.send(fail_silently=False)

```

**Comment by willpower232** [comment]
Thanks for letting us know, feel free to close the issue if its all sorted.

**Comment by shravin** [comment]
Closing the issue. Thanks for all the responses.
