### ISSUE TITLE
SoftFail Issues

### ISSUE THREAD

**Issue by wrt12345** [postalhq/postal#1073]
I have 1 fully working vultr server running postal & sending fine.
QUESTION: has the files for postal changed in the last fews days or something?
as i have just added a second server for testing and i have just done the normal install, and now getting softfail when i send, scratching my head is an understatement right now with 1 working and 1 not working and i have tried 6 times,am i missing something as i have done nothing different but everytime i try now, i am getting softfail done nothing different at all......

**Comment by willpower232** [comment]
I don't think there has been any changes.

I presume you mean softfail, can you share the exact error message?

**Comment by wrt12345** [comment]
here is a screenshot i have just tried to send to mail-tester

<img width="669" alt="Screenshot 2020-05-05 at 09 52 40" src="https://user-images.githubusercontent.com/64301387/81049524-491c3980-8eb6-11ea-90a1-690f0157f5aa.png">

**Comment by willpower232** [comment]
Please see https://github.com/postalhq/postal/issues/113#issuecomment-299694318

**Comment by wrt12345** [comment]
Thanks for your help.
My working vultr telnet command to port 25 is exactly the same as my non working one so the connection is working is there anyway to fully tell if they are allowing one without the other ?

**Comment by willpower232** [comment]
You would have to take that up with vultr support, I think they've been discussed in a few other issues to be fair.

**Comment by wrt12345** [comment]
> You would have to take that up with vultr support, I think they've been discussed in a few other issues to be fair.

Okay thanks will

**Comment by wrt12345** [comment]
@willpower232 is there a way to change the port postal uses to get round this issue with vultr blocking port 25, i am reading something about iptables and change the port, is there a tutorial somewhere on how to do this and will it work just normal ?

**Comment by willpower232** [comment]
In this case, iptables is mainly used to receive email on multiple ports. Its likely that vultr is blocking outbound connections on port 25 so even if you change Postal, you won't be able to connect to any other email server as 25 is the standard they'll be using.

The `smtp_server` port can be changed in the config https://github.com/postalhq/postal/blob/master/config/postal.defaults.yml

**Comment by wrt12345** [comment]
Thanks @willpower new provider then :) do you know of any providers that don't block this port?

**Comment by willpower232** [comment]
AWS will if you ask them nicely, I think DigitalOcean works for others quite well.

**Comment by wrt12345** [comment]
@willpower232 so i moved to a new host got a 10/10 score all good,
I can send from inside the postal system
but now i cant do an smpter test, its failing, any ideas ? have done a netstat port 25 check and its good here is my netstat output if this helps
<img width="815" alt="Screenshot 2020-05-08 at 14 20 35" src="https://user-images.githubusercontent.com/64301387/81409523-2ba9d280-9137-11ea-8b2c-96b8cb9c1c3a.png">

**Comment by willpower232** [comment]
Your netstat implies you are running postfix which has bound to port 25 so your telnet isn't talking to postal.

**Comment by wrt12345** [comment]
thanks
