### ISSUE TITLE
Incoming Messages : "550 Loop detected"

### ISSUE THREAD

**Issue by rohitkatiyar1984** [postalhq/postal#1074]
Hi Postal Team,

Thanks for the awesome SMTP tool that you have created.

I installed and setup the Postal SMTP tool in an OVH server separate from my Web server.

The outgoing messages are working fine. 

However, for incoming messages, I am facing an issue where as soon as an incoming message is received, it's followed by a series of 3 messages sent from my 'return path' followed by "HARD FAIL" msg (2 Sent, 1 Hard Fail) . The error in the Hard Fail msg that I can see is  'Permanent SMTP delivery error ' with reason as '550 Loop detected'.

Can someone please help to resolve it?

Regards,
Rohit

**Comment by willpower232** [comment]
that may be coming from Postal itself, https://github.com/postalhq/postal/blob/0fb323af3f37201eed492646007ed355f3617b51/lib/postal/smtp_server/client.rb#L389

Are you sending a message from your Postal server to itself or something?

**Comment by rohitkatiyar1984** [comment]
No..  atleast not intentionally...

Following is the setup..
A, mail.mydomain.com points to IP of server where Postal is installed.
MX , mail.mydomain.com points to IP of server where Postal is installed.
A, rp.mail.mydomain.com points to IP of server where Postal is installed.
MX, rp.mail.mydomain.com points to mail.mydomain.com
CNAME, psrp points to  rp.mail.mydomain.com
MX, routes.mail.mydomain.com points to mx.mail.mydomain.com

**Comment by rohitkatiyar1984** [comment]
Would anyone be able to help with the above DNS configuration if it's correct?? or is that the reason for the issue....

**Comment by willpower232** [comment]
It sounds like the domain you're sending to has Postal as its MX records so Postal is trying to send a message to itself or something along those lines. Do you know the email provider of where you're trying to send an email?

**Comment by rohitkatiyar1984** [comment]
I am sending email from GMAIL to postal (hosted on OVH server)..

**Comment by rohitkatiyar1984** [comment]
on further investigation, i think it's due to the Address endpoint which points to the same domain address...

**Comment by jefersonsilva** [comment]
Sorry, I'didn't understand. 

I'm having the same issue and I don't know how solving.
