### ISSUE TITLE
SMTP stopped when requeue

### ISSUE THREAD

**Issue by velaskes** [postalhq/postal#1078]
Hi, I'm install Postal, when I start with "postal run", i read this:

~# postal run
17:16:14 system             | Procodile supervisor started with PID 5445
17:16:14 system             | Application root is /opt/postal/app
17:16:14 system             | Automatic respawning is disabled
17:16:14 system             | Reloading configuration
17:16:14 web.1              | Started with PID 5449
17:16:14 worker.1           | Started with PID 5451
17:16:14 cron.1             | Started with PID 5453
17:16:14 control            | Listening at /tmp/postal/pids/procodile.sock
17:16:14 smtp.1             | Started with PID 5455
17:16:14 requeuer.1         | Started with PID 5457
17:16:19 web.1              | => Puma starting in single mode...
17:16:19 web.1              | => * Version 3.12.0 (ruby 2.3.8-p459), codename: Llamas in Pajamas
17:16:19 web.1              | => * Min threads: 5, max threads: 5
17:16:19 web.1              | => * Environment: production
17:16:35 requeuer.1         | => [requeuer.1:5457] [2020-05-07T17:16:35.483] INFO -- : Running message requeuer...
17:16:35 smtp.1             | => rake aborted!
17:16:35 smtp.1             | =>
17:16:35 smtp.1             | => Errno::EACCES: Permission denied - bind(2) for "::" port 25
17:16:35 smtp.1             | =>
17:16:35 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `initialize'
17:16:35 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `open'
17:16:35 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `listen'
17:16:35 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:258:in `run'
17:16:35 smtp.1             | => /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
17:16:35 smtp.1             | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
17:16:35 smtp.1             | =>
17:16:35 smtp.1             | => Tasks: TOP => postal:smtp_server
17:16:35 smtp.1             | =>
17:16:35 smtp.1             | => (See full trace by running task with --trace)
17:16:35 smtp.1             | =>
17:16:35 cron.1             | => [cron.1:5453] [2020-05-07T17:16:35.561] INFO -- : Starting clock for 8 events: [ every-1-minutes every-15-minutes every-15-minutes every-15-minutes every-15-minutes every-hour every-hour every-day ]
17:16:35 cron.1             | => [cron.1:5453] [2020-05-07T17:16:35.575] INFO -- : Triggering 'every-1-minutes'
17:16:38 worker.1           | => [worker.1:5451] [2020-05-07T17:16:38.168] INFO -- : Worker running with 4 threads
17:16:38 worker.1           | => [worker.1:5451] [2020-05-07T17:16:38.188] INFO -- : [VNN1319ZIZ] Started processing RequeueWebhooksJob job
17:16:38 worker.1           | => [worker.1:5451] [2020-05-07T17:16:38.189] INFO -- : Joined main queue
17:16:38 worker.1           | => [worker.1:5451] [2020-05-07T17:16:38.189] INFO -- : [ABIERG5TXM] Started processing SendNotificationsJob job
17:16:38 smtp.1             | Process has stopped. Respawning not available.
17:16:38 smtp.1             | Removed PID file
17:16:38 web.1              | => * Listening on tcp://127.0.0.1:5000
17:16:38 web.1              | => Use Ctrl-C to stop
17:16:38 worker.1           | => [worker.1:5451] [2020-05-07T17:16:38.500] INFO -- : [VNN1319ZIZ] Finished processing RequeueWebhooksJob job in 0.311927713s
17:16:38 worker.1           | => [worker.1:5451] [2020-05-07T17:16:38.506] INFO -- : [ABIERG5TXM] Finished processing SendNotificationsJob job in 0.316721864s

I I have not been able to find the solution to why it stops....

thanks in advance!

**Comment by willpower232** [comment]
> 17:16:35 smtp.1 | => Errno::EACCES: Permission denied - bind(2) for "::" port 25

Either you didn't give ruby permission to bind to port 25 or something else already is.
