### ISSUE TITLE
Can I disable DNS verification

### ISSUE THREAD

**Issue by ercan412** [postalhq/postal#1080]
I'll send mails to SMTP relay server from postal. I'dont need do verify any dns settings. I've commented out DNS lines from config but it doesn't worked.

**Comment by willpower232** [comment]
what in particular doesn't work? are there error messages you can see?

**Comment by ercan412** [comment]
The web ui gaves error on domain and messeage pages. Is there any way to disable DNS verification and use SMTP relay with Postal?

**Comment by willpower232** [comment]
If you're a superuser, you should be able to put the config back, add the domain in the UI, and ignore the DNS warnings and it should allow you to send.

What error are you seeing on the message pages?
