### ISSUE TITLE
Need urgent help with HTTP API

### ISSUE THREAD

**Issue by rohitkatiyar1984** [postalhq/postal#1081]
Hi all,

Can someone help with the the CURL format for sending emails via HTTP API?

I have tried with the documentation in place and not able to get it work..

FYI.. my app is based on PHP.. and I would like to use CURL to send bulk emails...

**Comment by rohitkatiyar1984** [comment]
Is https mandatory for access to API.. Can't we use it via http?

I get an error : "301 Moved Permanently" while trying to access it via http link!

**Comment by willpower232** [comment]
if you're using PHP, do you have access to composer? you could make use of the PHP library for sending Postal messages.

In theory you could get around HTTPS access by editing your nginx config, that is probably what you are seeing in the API response.

**Comment by rohitkatiyar1984** [comment]
Yes, I am using PHP Mailer for sending SMTP messages.. which works fine.

However I want to use HTTP API as I scale to more messages.. since the deliverability will be high...

Thanks, I edited the nginx file to not redirect to https.. However now i get an error as. : "404 Not Found" :( .. I am not able to find any documentation on how do I make the correct curl request..

**Comment by willpower232** [comment]
404 means your nginx config file needs further work, you should be able to combine the two bits in the nginx config so its something like

```
listen 80;
listen 443 ssl http2;
```

I don't think curl has been explicitly documented, you may be interested in the raw documentation https://krystal.github.io/postal-api/index.html and the source code of the PHP library https://github.com/krystal/postal-php

**Comment by rohitkatiyar1984** [comment]
Thanks.. 
A very basic question:
In the link : https://github.com/krystal/postal-php, shall I put the http api key or the smtp API key?

**Comment by willpower232** [comment]
the library only uses the HTTP API so you need to make sure the credential you're using is NOT for SMTP

**Comment by rohitkatiyar1984** [comment]
Thanks that's pretty helpful.. .i will try out with the PHP library then..

**Comment by rohitkatiyar1984** [comment]
I tried out the PHP library on Localhost Mac with Xampp ..    Installed Composer successfully..

But I get this error : Fatal error: Uncaught Error: Class 'Postal\Client' not found in /Applications/XAMPP/xamppfiles/htdocs/..........

**Comment by rohitkatiyar1984** [comment]
Can someone help on this please??

**Comment by willpower232** [comment]
If you're using just PHP without a framework, have you done this at the top of your main file?

```php
<?php

require 'vendor/autoload.php';
```

Also did you definitely `composer require postal/postal`?
