### ISSUE TITLE
Email Credit for Organizations

### ISSUE THREAD

**Issue by saporus** [postalhq/postal#1083]
Hello,

Does anyone knows how to configure email credit for each organization on Postal?

I can see from the Postal screenshot at https://camo.githubusercontent.com/26075a83524f896c8b6790df51c6c67dabe1911d/68747470733a2f2f73686172652e6164616d2e61632f31372f6b346c41354f75506c552e706e67 

that Postal has such feature.

Thanks

**Comment by willpower232** [comment]
Unfortunately that functionality is not part of Postal, it was part of its initial application called AppMail.

**Comment by saporus** [comment]
Hello @willpower232 ,

Thanks for your response.

Do you know of any custom configuration we could add into postal config file that would allow us to limit the amount of emails to be sent in 24 hours per user or organization?

Thanks

**Comment by willpower232** [comment]
There is already a built in feature which limits the email that can be sent hourly. Any emails sent over that amount will be held by Postal and would have to be sent again manually from the UI.

You might be able to change the code to increase it to 24 hours but I'm not sure how deep that goes in the code.
