### ISSUE TITLE
"Message is currently being processed"

### ISSUE THREAD

**Issue by iammattmartin** [postalhq/postal#1085]
We have changed a few IPs around and updated the pools, although we have one message that seems to be just stuck (12+ hours in that status).

Have tried a few of the earlier comments for stuck messages with no joy on this one and the usual steps have not worked.

Has anyone come across this and managed to unstick the message?

**Comment by willpower232** [comment]
does the database tell you if that particular message is locked by anything or did you already clear that bit?

does the UI page for it have any resend or re queue links?

**Comment by iammattmartin** [comment]
Ah, perfect. I did check in the DB but didn't spot that. 

Set the lock values to NULL and it pretty much vanished.

The buttons to resend/queue were not there, most likely due to being stuck.
