### ISSUE TITLE
* smtp.1 is not running (Failed)

### ISSUE THREAD

**Issue by wrt12345** [postalhq/postal#1091]
My server was working 100% then my host restarted my server for some reason.

I believe they have blocked port 25,  i cant understand why it just stops working but they insist they have not done anything.

when i start postal its fine, when i run postal status its fine,
but after about a minute running postal status again it then changes to * smtp.1 is not running (Failed)
so it runs then stops for some reason what would be causing this.

am getting very frustrated it working then not. hope someone can help me

<img width="608" alt="Screenshot 2020-05-24 at 09 01 28" src="https://user-images.githubusercontent.com/64301387/82748892-62215780-9d9d-11ea-9f1d-d2128458e30f.png">
<img width="225" alt="Screenshot 2020-05-24 at 09 01 21" src="https://user-images.githubusercontent.com/64301387/82748895-664d7500-9d9d-11ea-83f7-91b3018fc566.png">

<img width="707" alt="Screenshot 2020-05-24 at 09 09 20" src="https://user-images.githubusercontent.com/64301387/82749023-466a8100-9d9e-11ea-9775-b86707393bdd.png">

**Comment by wrt12345** [comment]
Solved From Post 
SMTP stopped working
#562

**Comment by willpower232** [comment]
Glad you figured it out. If you're still experimenting with SMTP servers or didn't want to remove postfix for another reason, you could have disabled it with `sudo systemctl disable postfix`
