### ISSUE TITLE
Link for API DOCS in sidebar WIKI is broken.

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1093]
There is a link to the API in the directory index. The link is broken.

**Comment by inspiretk** [comment]
You looking for this?
https://github.com/postalhq/postal/wiki/Using-the-API
https://krystal.github.io/postal-api/

Let me know if you know how to use it :D I just searched for postalhq api and those links came up.

**Comment by willpower232** [comment]
see #1030
