### ISSUE TITLE
About Return Path

### ISSUE THREAD

**Issue by hassancs91** [postalhq/postal#1095]
Hi, am trying to handle bounces with Mautic connected to Postal.
I see that when I send an email, the return path will be something like "abcded@rp.mydomain.com"
that's fine. but to handle bounces I need to access the returned emails on this address and handle it from my email marketing application. 

but when I set a route for this address, it failed, I think because the return path domain is the same as the sender domain.

anybody tried to handle bounces successfully with postal? 

Thank you!

**Comment by willpower232** [comment]
Your best bet would be webhooks but I don't know if someone has added Postal webhook support to Mautic.

**Comment by hassancs91** [comment]
I will do some research on this.
