### ISSUE TITLE
Multiple Domains

### ISSUE THREAD

**Issue by hassancs91** [postalhq/postal#1096]
In the postal yml config file we have the configuration to one domain.
how do we configure multiple domains inside postal? with different DNS configuration?

**Comment by willpower232** [comment]
The domain you use in the config file only refers to the server itself, you will want to send emails from different domains that you add into the UI.

The DNS of those different domains will point to the domain you used in the config file.

**Comment by hassancs91** [comment]
can you please explain this sentence:
The DNS of those different domains will point to the domain you used in the config file.

if I add a new domain, how I verify spf and other values, postal will read the main domain values by default.

**Comment by willpower232** [comment]
Set up the postal config and then go into the UI. In there you will be able to see how to add and verify other domains.

**Comment by hassancs91** [comment]
I think I got your point, Thanks for you time.
