### ISSUE TITLE
To: Returnpath is not routing

### ISSUE THREAD

**Issue by hassancs91** [postalhq/postal#1097]
Iam trying to handle bouncing in postal.
but the bounce emails that are incoming to return path are marked as hard fail.

any workaround?
![Capture](https://user-images.githubusercontent.com/51578605/83038569-c9613500-a045-11ea-8797-0ac121c14e5f.PNG)

**Comment by willpower232** [comment]
If you go into the message, you should be able to see why it hard failed.

**Comment by hassancs91** [comment]
When I open the message, I see this:
This message was a bounce but we couldn't link it with any outgoing message and there was no route for it.

But I added a route for this address. this problem happens when the return path is the same domain as the sending domain. 

so it's impossible to read bounce messaged in this way.
How do we use the return path address in postal then?

**Comment by willpower232** [comment]
The return path is for when Postal sends a message and then receives a bounce as it may not have failed straight away.

Was it supposed to correspond to a message Postal sent or did you email it directly?

**Comment by hassancs91** [comment]
This is the scenario:
I Setup Postal and everything is perfect, I sent a test email to my address and got the return-path address.

The return path address is the address used by other mail providers to send bounces back, yes?

so I got this return path address and I send a message to this address to test bounce handling.

I got the message in postal coming from my email address to the return path address
from: hassan.cs91@gmail.com
to: abxxdef@rp.mydomain.com

and I created a route for the return path address to another Gmail inbox, so I can read the bounces through IMAP from my mailing app (mautic)

The problem is that postal is not routing emails that are coming to the return path. all other routes are fine. but this is giving a hard fail. with the message, I sent you above.

I hope that I explained the scenario. 

am I doing something wrong?

Thank you!

**Comment by willpower232** [comment]
I see, it might be that as it isn't a genuine bounce, it won't get routed or something but I'm not sure.

You could try emailing an address that definitely doesn't exist or one you know is full maybe?

**Comment by hassancs91** [comment]
I tried sending a direct message to the return path address, and it shows the same error (cant route)
this is weird. I dont understand what's happing.

**Comment by dragoangel** [comment]
@hassancs91 if you send email to return path then if of course will be HardFail as your email can't be correct bounce.

**Comment by hassancs91** [comment]
@dragoangel Then how to handle bounces??

**Comment by dragoangel** [comment]
What you mean how handle bounce? Maybe you mean: how test bounce cases?

**Comment by hassancs91** [comment]
Hi. 
This is the scenario:
Mautic connected to Postal
When I send an email marketing campaign through mautic, some emails will bounce.
so emails will bounce in postal. I need to automatically blacklist those hard bounces in my email system (Mautic)
this is bounce handling.

usually bounces emails will go back to the return-path address. but the problem is that this address is autogenerated by postal so we can't read those emails. from other applications.
and there is no webhook that works with Mautic.

this is the problem.

**Comment by dragoangel** [comment]
So that's what you needed to start with. Hard bounce will be returned to postal. Postal will know which delivery would succeed and which failed. And yep you need webhooks developed which will work with postal

**Comment by hassancs91** [comment]
Thank you for your reply.
if postal can allows us to set custom return-path address. like a fixed one. then we can monitor bounces through Imap. but I dont think this is possible.

Thanks anyway.

**Comment by willpower232** [comment]
The wiki says that the `__returnpath__` route can only be a HTTP endpoint and that doesn't appear to have changed so the only way to monitor bounces is essentially without an inbox so it does not seem that what you want is currently possible with Postal.

**Comment by hassancs91** [comment]
Yeah, this is what I thought, thank you.
I hope this to be updated in the future so we can connect any app to postal.

**Comment by XenyFord** [comment]
> This is the scenario: I Setup Postal and everything is perfect, I sent a test email to my address and got the return-path address.
> 
> The return path address is the address used by other mail providers to send bounces back, yes?
> 
> so I got this return path address and I send a message to this address to test bounce handling.
> 
> I got the message in postal coming from my email address to the return path address from: [hassan.cs91@gmail.com](mailto:hassan.cs91@gmail.com) to: [abxxdef@rp.mydomain.com](mailto:abxxdef@rp.mydomain.com)
> 
> and I created a route for the return path address to another Gmail inbox, so I can read the bounces through IMAP from my mailing app (mautic)
> 
> The problem is that postal is not routing emails that are coming to the return path. all other routes are fine. but this is giving a hard fail. with the message, I sent you above.
> 
> I hope that I explained the scenario.
> 
> am I doing something wrong?
> 
> Thank you!

Dear Mr. Hassan,

YES! I've been facing the same problem, unable to replace kj2r1@psrp.domain.com bounce address to a custom address(bounce@domain.com)..Please, can you help me how to solve this? or Could you please be very kind to let me know If there is any other script/tool that can allow me to have custom bounce address?

Thank you in advance!
