### ISSUE TITLE
CNAME not configured correctly -- Click Tracking

### ISSUE THREAD

**Issue by RickoT** [postalhq/postal#1099]
Greetings!

I have followed the guide here: https://github.com/postalhq/postal/wiki/Click-&-Open-Tracking but to no avail.
I believe I have done everything correctly but it still seems to give an error about the CName

Here is my DNS setup:
 A record named tracker.mydomain.com pointed to the second IP on my VPS
 CName record named click.mydomain.com pointed to tracker.mydomain.com

I have verified that I am able to get to tracker.mydomain.com via a browser (received Hello. message) and click.mydomain.com, however in the configuration it still says the CName is not configured correctly, which I assume is preventing the SSL piece from performing configuration

Any assistance would be appreicated

Thanks!
~Rick

**Comment by willpower232** [comment]
It may be that the DNS needs time to update around the internet or your Postal server needs time to clear its DNS cache.

You should be able to see how the domain resolves from the command line on your server with `nslookup click.mydomain.com`.

**Comment by RickoT** [comment]
Good Morning,
I was able to verify that the server does resolve the host name from the command line using nslookup, but it still says that the CNAME Is not configured correctly.

**Comment by RickoT** [comment]
Actually, i just figured it out.  In the postal.yaml config file there is a setting called track_domain.  I had put the wrong host there.  Now that I fixed the setting and restarted postal, it shows that the cname is set up properly
