### ISSUE TITLE
 is it possible to set up an inbox service to work in tandem with postalhq

### ISSUE THREAD

**Issue by ivan006** [postalhq/postal#1104]

**Comment by ivan006** [comment]
maybe Roundcube will work? https://websiteforstudents.com/install-roundcube-webmail-on-ubuntu-16-04-18-04-with-apache2-and-php-7-2-support/

**Comment by willpower232** [comment]
I don't believe that Postal is capable of recording emails in an inbox itself, you could create an application to receive messages received by Postal and also send them but if you're looking for a traditional email system, there are numerous solutions which are less likely to be bodged together.

**Comment by ivan006** [comment]
I appreciate the help

**Comment by aaarocket** [comment]
Postal is focused on transaction mails, not general purpose mail services. For inbox services you need IMAPS support and better MSA support. Take a look at [MiaB](https://mailinabox.email ) or similar projects like Modoboa, Mailcow, Mailu or Poste.io

**Comment by ivan006** [comment]
i just thought of a work around. Is it perhaps posible to track replies?

**Comment by ivan006** [comment]
otherwise my only thoughts are why would anyone want to use postal anyway cause of IP pools?

**Comment by ivan006** [comment]
do any of these suprot IP pools (or at least the ability to have multiple virtual smtp/imap servers within the save installation)?

**Comment by aaarocket** [comment]
For multihomed solutions take a look at ZoneMTA + Dovecot or dockerized Haraka + Dovecot.

**Comment by willpower232** [comment]
Postals entire purpose is to provide software with the ability to send emails if it can't already.

It sounds like you want a full mail solution so you should investigate the recommended projects which will have much easier ways of sending messages without complicating something which does not completely fit.

**Comment by aaarocket** [comment]
Look for ZoneMTA + WildDuck or dockerized Haraka + WildDuck if you want multihoming general purpose mail solution. Better tell us exactly what is your user story for mail service?

**Comment by ivan006** [comment]
i intalled postfix with dovecot seems like a standard practice method 
i would like a scalable system if posible (can have more than one IP/virtual server per installation) but no biggy if its a mission (like postal can do this but is a mission cause has no imap which i obvious need for reply tracking etc)

**Comment by ivan006** [comment]
" Haraka makes no attempt to be a mail stor" - https://haraka.github.io/README.html

**Comment by aaarocket** [comment]
That is the point of dockerized microservices behind the load balancer. 

Please try to learn and understand the difference between MUA, MSA, MDA and MTA.

**Comment by ivan006** [comment]
mua is the client functionality and msa->mta->mta->mta->mda is all smtp then comes imap then ur back where us started at the mua

**Comment by ivan006** [comment]
dope shot man :) recently i learned that I can potentially just change the mx record to another service (like gmail) and then all incoming mail gets directed (by the MDA i presume) to gmail even though its getting sent through postal... Still need to confirm that though which i will do in the next couple of months as this isnt urgent at my company right now :)
