### ISSUE TITLE
Changing SMTP Server Address

### ISSUE THREAD

**Issue by saumyabratadutt** [postalhq/postal#1105]
How can I change SMTP server address from postal.example.com to postal.myaddress.com ?

**Comment by varundeva** [comment]
> How can I change SMTP server address from postal.example.com to postal.myaddress.com ?

in postal.yml ive changed all details. still everywhere showing example domain

**Comment by willpower232** [comment]
You will need to restart Postal to make the config changes apply.

**Comment by varundeva** [comment]
Yes. It worked..

But another problem..
I was tried by installing in AWS EC2 free tyre
So mails are not delivering outside the server..
Im able to send mails between various boxes of my server only

**Comment by willpower232** [comment]
You will need to request the ability to send emails from AWS as I believe they restrict them by default.

**Comment by saumyabratadutt** [comment]
> > How can I change SMTP server address from postal.example.com to postal.myaddress.com ?
> 
> in postal.yml ive changed all details. still everywhere showing example domain

You need to restart postal separately.

**Comment by Code-with-Shah** [comment]
> Yes. It worked..
> 
> But another problem..
> I was tried by installing in AWS EC2 free tyre
> So mails are not delivering outside the server..
> Im able to send mails between various boxes of my server only

How you Installed postal on EC2 AWS? Plz, let me know @varundeva
