### ISSUE TITLE
DNS Issues

### ISSUE THREAD

**Issue by Imsheryarkhan** [postalhq/postal#1106]
I'm trying to install Postal on google cloud with a single IP to test things out.

I am unable to setup DNS settings. I have been trying to do this for the last 3 days non stop.

Any help will be appreciated!

**Comment by Imsheryarkhan** [comment]
SPF Record
WARNING No SPF record exists for this domain

You need to add a TXT record at the apex/root of your domain (@) with the following content. If you already send mail from another service, you may just need to add include:spf.postal.example.com to your existing record.

v=spf1 a mx include:spf.postal.example.com ~all
DKIM Record
GOOD Your DKIM record looks good!

You need to add a new TXT record with the name postal-GprRIB._domainkey with the following content.

v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDjLVm3i//VlMa2XOrmyjdDN8xgXRtDnhj0C65bvj18wCNzm8lop3g0uriL318Wz5Bk3RswrU7Zb74cgJavIlGLyHyJO7S7G3Txn7JZPVFbk8/k4FsF30z7CepnbxiOGokoXCUO5oNBlSYw85gvP1iNS2ygyr19oqwGOkUx6adHDQIDAQAB;
Return Path
OK There's no return path for this domain. This is OK but we recommend adding the record to improve deliverability and achieve DMARC alignment.

This is optional but we recommend adding this to improve deliverability. You should add a CNAME record at psrp.drspy.ml to point to the hostname below.

rp.postal.example.com
MX Records
OK None of the MX records for this domain point to us. Incoming mail won't be sent to us.

If you wish to receive incoming e-mail for this domain, you need to add the following MX records to the domain. You don't have to do this and we'll only tell you if they're set up or not. Both records should be priority 10.

mx.postal.example.com

**Comment by Imsheryarkhan** [comment]
===============================
# Update : 
# 
# SPF Record
# WARNING No SPF record exists for this domain
# 
# You need to add a TXT record at the apex/root of your domain (@) with the following content. If 
 # you already send mail from another service, you may just need to add # 
#  include:spf.postal.example.com to your existing record.
# 
# v=spf1 a mx include:spf.postal.example.com ~all
# 
# Domain: domain.ml ( I am not using subdomain )
# 
# DKIM Record
# GOOD Your DKIM record looks good!
# 
#Any remarks on this?
#  Return Path
# OK There's no return path for this domain. This is OK but we recommend adding the record to 
# improve deliverability and achieve DMARC alignment.
# 
#Any remarks on these? 
# MX Records
# OK None of the MX records for this domain point to us. Incoming mail won't be sent to us.
# 
# Help me out with SPF ( no subdomain, plain root ) 
# 
# as a newbie and after 40+ hours, I made it this far =]

**Comment by inspiretk** [comment]
what's in your postal.yml file?

nano /opt/postal/config/postal.yml

Make sure you update it with your domain name. Then stop postal, initialize it, and start it.

**Comment by Imsheryarkhan** [comment]
> nano /opt/postal/config/postal.yml

Thank you.

I tried initializing it and got error


root@newbie:~# nano /opt/postal/config/postal.yml
root@newbie:~# postal stop
Stopped web.1 (PID: 30062)
Stopped worker.1 (PID: 30064)
Stopped cron.1 (PID: 30066)
Stopped smtp.1 (PID: 30069)
Stopped requeuer.1 (PID: 30071)
Supervisor will be stopped when processes are stopped.
Waiting for supervisor to stop...
Supervisor has stopped
root@newbie:~# postal initialize
Initializing database
rake aborted!
ActiveRecord::ProtectedEnvironmentError: You are attempting to run a destructive action against your 'production' database.
If you are sure you want to continue, run the same command with the environment variable:
DISABLE_DATABASE_ENVIRONMENT_CHECK=1
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:61:in `check_protected_environments!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)
root@newbie:~# postal initialize
Initializing database
rake aborted!
ActiveRecord::ProtectedEnvironmentError: You are attempting to run a destructive action against your 'production' database.
If you are sure you want to continue, run the same command with the environment variable:
DISABLE_DATABASE_ENVIRONMENT_CHECK=1
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:61:in `check_protected_environments!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)

**Comment by Imsheryarkhan** [comment]
DISABLE_DATABASE_ENVIRONMENT_CHECK=1 postal initialize


didn't help.

**Comment by inspiretk** [comment]
what's in your postal.yml file? Use command below, and paste here

nano /opt/postal/config/postal.yml

**Comment by willpower232** [comment]
`example.com` suggests your config file needed setting up fully first.

If your domain definitely has an SPF record, you can use whatsmydns.net to find out if that record is applying properly around the internet.

Lastly, do not run `postal initialise` if you are not installing as it can delete your data.
