### ISSUE TITLE
How can I use with auth like username password

### ISSUE THREAD

**Issue by RKurcan** [postalhq/postal#1107]
How can I use with auth like username password 
I try this but not worked https://rubygems.org/gems/socksify-with-auth/versions/1.7.1
`def tcp_socket(address, port,p_username = nil, p_password = nil)
addr = TCPSocket::SOCKSConnectionPeerAddress.new("ip adress", 14193,"username","password", address)
TCPSocket.open(addr, port, self.source_address)`

_Originally posted by @RKurcan in https://github.com/postalhq/postal/issues/605#issuecomment-638751791_

**Comment by willpower232** [comment]
Are you trying to connect **to** Postal from something else or connect to a proxy **from** Postal?

**Comment by RKurcan** [comment]
connect to a proxy from Postal?

**Comment by willpower232** [comment]
I'm not sure thats possible, have a read of #48
