### ISSUE TITLE
Additionnal headers in DKIM signature

### ISSUE THREAD

**Issue by jlnmrc** [postalhq/postal#1110]
RFC8058 specifies that the List-Unsubscribe and List-Unsubscribe-Post headers must be included in the DKIM signature.  These headers are widely used and even required for good deliverability on some platforms.
Unless I am mistaken, only the headers date, from, to, message-id and subject are currently included in the signature.
Is it possible to simply add the List-Unsubscribe* headers (or even others) into the signature or Postal cannot currently do this?

**Comment by willpower232** [comment]
I believe you could do this in the code, I'm not sure this would get added to the main code however.

**Comment by jlnmrc** [comment]
Thank you willpower232
I ended up adding the headers [here](https://github.com/postalhq/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/lib/postal/dkim_header.rb#L35)

**Comment by willpower232** [comment]
Ah glad it was simple to arrange! I wonder how far the RFC will get in implementation as this is the first time its been reported as an issue.

**Comment by jlnmrc** [comment]
All the email providers I've been able to check include these headers in the DKIM signature. The application of this RFC is moreover necessary for white list certification for many certifiers I have contacted ([example](https://certified-senders.org/document/one-click-unsubscribe-rfc8058-is-now-a-mandatory-csa-criteria/)).

**Comment by joeqrakz** [comment]
> Thank you willpower232
> I ended up adding the headers [here](https://github.com/postalhq/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/lib/postal/dkim_header.rb#L35)

So, I can confirm that the added header appears in the code of my postal instance, but for some reason my emails still do not include the list-unsubscribe header. Am I missing something?

**Comment by jlnmrc** [comment]
What do you mean 'my emails still do not include the list-unsubscribe header'?
The modification of the indicated code allows Postal to **add the selected headers to the DKIM signature** and not to add the headers to your emails. You still have to add all the additionnal headers you want when you send your emails.

**Comment by joeqrakz** [comment]
Ahhhhhh, I see. Any chance you can point me to some good instructions on that?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jlnmrc** [comment]
It totally depends on what you use to pass emails to Postal. You have to look in your script/library documentation to know how to add headers.
