### ISSUE TITLE
About WebHooks

### ISSUE THREAD

**Issue by hassancs91** [postalhq/postal#1111]
Hi, I enabled webhooks in postal, the problem is when I see the history: 
it shows 200 Ok response like this:
![Capture](https://user-images.githubusercontent.com/51578605/83946447-9115df80-a819-11ea-92e0-daadf0b8a823.PNG)
but when I open the hook to see details, it looks like this:
![Capture](https://user-images.githubusercontent.com/51578605/83946471-cc181300-a819-11ea-948b-a7e45f6d5304.PNG)

and the other problem is that other webhook events are working, only MessageDeliveryFailed is giving this problem, which is important to handle bounces.

**Comment by willpower232** [comment]
I think there is another issue somewhere about the history pages not working quite right.

Have you checked your app to see if the bounce has been received by it?

**Comment by hassancs91** [comment]
No, Iam not receiving the bounce in my app. this is the main problem.
the webhook is not working.

**Comment by willpower232** [comment]
the 200 has a later time on than the error message so that implies your app was happy with the response, are there any logs in your app that might tell you what happened?

**Comment by hassancs91** [comment]
Unfortunately, there are no logs for the webhooks. the only thing I see is that all webhooks are working except for the MessageDeliveryFailed
