### ISSUE TITLE
Request for advice on webhook for bounces for MailWizz

### ISSUE THREAD

**Issue by sac5120** [postalhq/postal#1113]
Hello 

Does anyone have a working webhook for bounces for MailWizz?
I am using verison 1.9.6 of mailwizz

And how can i use that i tried to use that but little confused here
Postal is sending webhook requests for MessageDeliveryFailed to mailwizz url http://www.mymailwizzistallaionurl.com/dswh/postal

![imageedit_1_7444947088](https://user-images.githubusercontent.com/66561511/83975641-6e1b2680-a912-11ea-8907-48ebe6ef1db6.png)

but don't know in my mailwizz apllication it's not showing any bounces over there and not removing from my list

Literally this webhook for bounces has left me stumped. Any help on this would be much appreciated.

Best,

sachin

**Comment by avangdev** [comment]
It solve in mailwizz 1.9.9, update your mailwizz.
