### ISSUE TITLE
Pending

### ISSUE THREAD

**Issue by eclanwide** [postalhq/postal#1119]
Here is my Postal status. I do see error messages and don't know if it's the reason of my pending.

root@server:~# postal status
Procodile Version 1.0.26
Application Root /opt/postal/app
Supervisor PID 1712
Started 2020-06-12 17:08:46 +0200

    worker.1 is not running (Failed)
    requeuer.1 is not running (Failed)

|| web
|| Quantity 1
|| Command bundle exec puma -C config/puma.rb
|| Respawning 5 every 3600 seconds
|| Restart mode usr1
|| Log path none specified
|| Address/Port none
|| => web.1 Running 17:08 pid:1718 respawns:0 port:- tag:-

|| worker
|| Quantity 1
|| Command bundle exec ruby script/worker.rb
|| Respawning 5 every 3600 seconds
|| Restart mode start-term
|| Log path none specified
|| Address/Port none
|| => worker.1 Failed 17:11 pid:1872 respawns:5 port:- tag:-

|| cron
|| Quantity 1
|| Command bundle exec rake postal:cron
|| Respawning 5 every 3600 seconds
|| Restart mode term-start
|| Log path none specified
|| Address/Port none
|| => cron.1 Running 17:08 pid:1722 respawns:0 port:- tag:-

|| smtp
|| Quantity 1
|| Command bundle exec rake postal:smtp_server
|| Respawning 5 every 3600 seconds
|| Restart mode usr1
|| Log path none specified
|| Address/Port none
|| => smtp.1 Running 17:08 pid:1724 respawns:0 port:- tag:-

|| requeuer
|| Quantity 1
|| Command bundle exec rake postal:requeuer
|| Respawning 5 every 3600 seconds
|| Restart mode term-start
|| Log path none specified
|| Address/Port none
|| => requeuer.1 Failed 17:10 pid:1865 respawns:5 port:- tag:-
root@server:~#

**Comment by eclanwide** [comment]
All running now but still having pending messages.

**Comment by willpower232** [comment]
It might be that the pending messages were claimed by processes that no longer exist which has been reported a few times in these issues. You should go in the database and check the queued_messages and clear the locked_by, locked_at, and retry_after fields or something along those lines.
