### ISSUE TITLE
Adding Postal Message ID in case it not provided by SMTP client

### ISSUE THREAD

**Issue by dragoangel** [postalhq/postal#1123]
No MID is bad practice, and some SMTP clients not adding it to email. Most Mail delivery servers will add own MID in case client not set it to original email, but Postal don't doing it. Is it posible to add such function or add option to enable it per server?

**Comment by willpower232** [comment]
Would this only be a problem if the message was sent via a raw endpoint? I think Postal constructs most of the other messages itself so those would have them in?

**Comment by dragoangel** [comment]
It the case if smtp endpoint was been used.

**Comment by willpower232** [comment]
yes that makes sense, are you not adding the message ID in your application then? or are you using some software which doesn't completely follow the spec?

**Comment by dragoangel** [comment]
yep, some existing software doesn't follow the specs =(

**Comment by dragoangel** [comment]
Just more info, from Wiki:
Message-IDs, if present, are generated by the client program sending the email (mail user agent, or MUA) or by the first mail server (mail submission agent, or MSA).
This just to say that this is normal behavior to add missing MID. Thanks

**Comment by willpower232** [comment]
> From address is not authorised to send mail

This means that the domain name you're using doesn't match the ones configured for the credential so you should be able to resolve that.

The raw endpoint does even less to the message before sending it, expecting you to have created it properly so definitely won't add the message ID.

The regular message endpoint appears to create a message ID as it receives the parts of the message separately.

**Comment by dragoangel** [comment]
> This means that the domain name you're using doesn't match the ones configured for the credential

I was checked that. I send successfully over same API key by not-RAW method, but get that answer over RAW ones.
