### ISSUE TITLE
Problem Deploy Hook Certbot restarting postal

### ISSUE THREAD

**Issue by alexander-rieder** [postalhq/postal#1124]
Hey Everyone,
i have the following problem: Certbot is renewing my LE-Certificate successful. After the renew I want certbot to trigger postal to restart. Therefore I modified the cronjob entry for crontab to the following:
`certbot -q renew --deploy-hook "postal restart"`
However postal won't restart.. In the certbot logs i found: 
```
2020-06-14 08:57:05,319:INFO:certbot.hooks:Running deploy-hook command: postal restart
2020-06-14 08:57:05,637:ERROR:certbot.hooks:Hook command "postal restart" returned error code 1
2020-06-14 08:57:05,638:ERROR:certbot.hooks:Error output from postal:
/usr/bin/postal: line 16: [: !=: unary operator expected
Error: Procodile supervisor isn't running
```

When I run `certbot -q renew --force-renew --deploy-hook "postal restart"` in the command-line, everything works (including postal restart). 

Can anyone help me? :)

Thank you in advance,

Alex

**Comment by dragoangel** [comment]
why you run postal restart from CertBot? Create systemd service and use it.

**Comment by alexander-rieder** [comment]
Thank you for your response. :)

I run postal restart from CertBot because only when i restart postal, the smtp service uses the new certificate

What exactly should i create a systemd service for?

**Comment by willpower232** [comment]
`/usr/bin/postal` is a bash script so its possible that when your renewal cron job gets executed there isn't a suitable environment for the script to run in (unless you have made changes to that file and there is a minor typo).

Using a systemd service may be a solution as then systemd would be responsible for issuing the restart command and it might work better in the cron job.
