### ISSUE TITLE
Test message not working

### ISSUE THREAD

**Issue by LickABrick** [postalhq/postal#1125]
Sending mail from my apps/mail server through postal works fine, but the test mail (e.g. `postal test-app-smtp user@example.com`) gives me the following error:

```
Message was not delivered successfully to SMTP server.
Error: OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello)
```

The smtp_server.log says the following:

```
ERROR -- : [TOXWNK] An error occurred while processing data from a client.
ERROR -- : [TOXWNK] Errno::EACCES: Permission denied @ rb_sysopen - /etc/letsencrypt/live/example.com/fullchain.pem
```

My smtp config looks like this:

```
smtp:
  port: 25
  from_name: postal
  from_address: postal@example
```

Postal runs as user postal and had Read/write permission on /etc/letsencrypt/live/example.com/fullchain.pem (is also owner of the file)

I run ruby 2.5.5p157

Anyone know how to fix this?

**Comment by LickABrick** [comment]
I have come a little further to a solution. When I run postal as root it works, but not if I run it as the postal user.

**Comment by willpower232** [comment]
Sounds like you need to change permissions on your letencrypt directory to allow the postal user to read the files.
