### ISSUE TITLE
Documentation regarding new releases/latest packages?

### ISSUE THREAD

**Issue by alnalda** [postalhq/postal#1126]
Hi, 
i have a Postal installation that i maintain. It is stable and i was wondering which improvements would have if i upgrade it. So i have two questions:
- Is there any documentation to know the improvements of each release/lastest package?
- How can i know which version i'm using and which one is the latest? (i installed it following the _Installation guide_ which downloads the latest package _https://postal.atech.media/packages/stable/latest.tgz_)

thanks in advance

**Comment by willpower232** [comment]
Unfortunately there is not currently a changelog, although that would be nice.

It seems there may be a few updates not present in the packages but nothing supremely major IIRC.

**Comment by alnalda** [comment]
Thanks for the info @willpower232 

Do you know how can i check which version i have installed in order to compare it with the last package?

**Comment by willpower232** [comment]
As you are using the packages, you can run `postal version` to see some version information.

The version information is not recorded in github so anyone using a direct git clone would get less useful information.
