### ISSUE TITLE
Block a domain 

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#1130]
Hello, 

What would be a simple way of preventing use of some domains.

For example a client is using 
Phishingdom

I suspended that account. The client added this in a different account. 

Is there a simple approach for this?

**Comment by willpower232** [comment]
Unfortunately, that isn't currently possible within Postal.

You will likely have to manage your client more directly to avoid bad behaviour.

**Comment by navinp** [comment]
Aight. Will post the solution here, if I have one.
