### ISSUE TITLE
Backup/restore

### ISSUE THREAD

**Issue by jlnmrc** [postalhq/postal#1131]
I'm trying to write my backup procedure so that I can reinstall a postal server that is causing me too much trouble with slowness.
Ideally, I want to keep the history and the global configuration and especially not to modify my DKIM DNS records (= keep the same default-dkim-record).

Does backing up 
1) all the postal-* databases 
2) the postal.yml file 
allow me to duplicate a postal server identically on a fresh installation?

**Comment by navinp** [comment]
If you're using DigitalOcean, you can use their snapshot feature

**Comment by willpower232** [comment]
Backing up all the databases and the postal.yml file should be sufficient for most cases.

If you have made changes to the code, you will likely want to back those up yourself as well.

A full server snapshot is suitable if you're running all of Postal on one server.

If you are considering moving to a new server Postal can be run as a cluster so you can have multiple installations running if they are pointing at the same database and rabbitmq (and your DNS records have been updated as necessary). This means you could run both to allow you to be more graceful in your moving if necessary.

**Comment by gadicc** [comment]
In case it helps anyone else... backup from a remote machine:

```bash
#!/bin/sh
HOSTNAME="postal.mydomain.com"
DATE=`date -I`

rsync -avzPe ssh root@$HOSTNAME:/opt/postal/config config-$DATE

USERNAME=$(yq -r .main_db.username config-$DATE/config/postal.yml)
PASSWORD=$(yq -r .main_db.password config-$DATE/config/postal.yml)

ssh root@$HOSTNAME \
  "docker exec postal-mariadb \
  mariadb-dump -u $USERNAME -p'$PASSWORD' --all-databases | gzip" > db-$DATE.sql.gz
```
