### ISSUE TITLE
SMTP Server connection timeout

### ISSUE THREAD

**Issue by reshadman** [postalhq/postal#1132]
Hello guys.

I periodically receive Connection timeout from the SMTP Server endpoint in my app.

I know this is something related to the i/o blocking smtp server. Does any one know any work around for this? Is there anyway to add more threads to the SMTP Server?

**Comment by willpower232** [comment]
Are you sending lots of SMTP traffic to Postal? You may be interested in #751

**Comment by reshadman** [comment]
Occasionally yes, I have also activated the firewall on the SMTP port to allow only defined IPs. I'm going to look at it. Thanks.

**Comment by cmmata** [comment]
We are having the same problem from time to time (explained at #466). If you find a solution please comment it here so we can all see how to deal with that.

**Comment by reshadman** [comment]
@cmmata for now I'm going to create an identical server reflecting the same credentials as the old one + putting a tcp proxy in front of them with the timeout half than the current setup, I haven't tested yet but I think it would work.

**Comment by willpower232** [comment]
@reshadman if you can point your multiple servers at the same database/rabbitmq then you won't have to mess around making sure the credentials are the same

**Comment by reshadman** [comment]
For anyone looking for a solution if they have the same problem, the following methods worked for us:

1. For our application server, we simply are using the HTTP send message endpoint, with some retry strategies tuned for network failures and response timeouts.
2. For our marketing app which only accepts SMTP server, we created a postfix relay pointing to the postal SMTP. postfix has [some nice requeueing configs](https://jrs-s.net/2013/04/17/configuring-retry-duration-in-postfix/) which are really useful.
