### ISSUE TITLE
Import/edit DKIM records

### ISSUE THREAD

**Issue by BornTKill** [postalhq/postal#1133]
Dear,

We plan to migrate from postfix/amavis/opendkim configuration to postal.
Is there a way to import/edit DKIM records into postal ?

We have many customers and we cannot impact them with this project.
Best regards.

**Comment by Code-with-Shah** [comment]
I can configure DNS records for you. I am providing my services on Fiverr.

fiverr.com/awaisshah_works

**Comment by BornTKill** [comment]
Not sure your answer is legit.

**Comment by willpower232** [comment]
There is not an import in the UI however most of the data is managed in the database so you may be able to add all your customers and then tweak the dkim records yourself.

**Comment by BornTKill** [comment]
@willpower232 Thank you to confirm this point. I am going to manage it like this.

**Comment by dragoangel** [comment]
@BornTKill you have as many dkims as you wany as stars on night sky while their selector is unique. What an issue to add needed record to DNS?)

**Comment by BornTKill** [comment]
@dragoangel It’s not a technical problem but an organisation one. The point is that we have customers and we would like not to bother them with our migration.

However we tryed to import existing dkim with DB update but because of dkim_identifier we failed. Even with dkim_identifer empty, the record stay -XxXx.domain.com : the hyphen remains unfortunately.

So we will contact our 50 customers to add new records.

**Comment by dragoangel** [comment]
Oh. Clean.

**Comment by willpower232** [comment]
@BornTKill thanks for updating us, I can see that would be annoying, I feel like a small change here would resolve it https://github.com/postalhq/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/app/models/domain.rb#L122

I wouldn't be sure how officially supported the absence of `dkim_identifier` should be but for your setup, it should be fine.

**Comment by BornTKill** [comment]
Hey!

Thank I found this also but don’t wanna modify original source to avoid future upgrade issue 👍 

Regards.

**Comment by willpower232** [comment]
Fair enough, I'm going to leave this open in case this minor change appeals to others.
