### ISSUE TITLE
Can I change outgoing port 25 to port 587 or any other port

### ISSUE THREAD

**Issue by Code-with-Shah** [postalhq/postal#1134]
Hi, How can I connect Postal with other SMTP Servers like Google’s SMTP using port 587 or another port (except port 25)?

Digitalocean doesn’t allow port 25 on New user account.

I installed Postal on Digitalocean. My SMTP cannot able to maintain a connection between receiving SMTP.

I created a ticket to open port 25 to DO Support team and they said to me that they don’t allow port 25 in any case
![1](https://user-images.githubusercontent.com/67752955/86385709-25088900-bcaa-11ea-8071-38f672fb23a5.png)
. Hope there will be a solution to that.

Regards
Awais Shah
awaishah008@gmail.com

**Comment by Code-with-Shah** [comment]
![setup-dedicated-smtp-server-send-unlimited-email-server](https://user-images.githubusercontent.com/67752955/86448243-eddcbb00-bd2f-11ea-8615-a308c25125ab.jpg)
![Uploading DO Support Team Reply.png…]()

**Comment by Code-with-Shah** [comment]
![DO Suppot Team Reply](https://user-images.githubusercontent.com/67752955/86448529-4e6bf800-bd30-11ea-8e7e-5fcd2548822e.png)

**Comment by willpower232** [comment]
I'm not sure if the outgoing port can be changed but DigitalOceans answer is certainly interesting. Are you able to clarify why they won't lift that restriction when it is already not in place for others?

**Comment by Code-with-Shah** [comment]
I don't know why they are not allowing port 25 for my account. I have a new account which I made 7 days ago.

**Comment by Code-with-Shah** [comment]
@willpower232 plz reply

**Comment by willpower232** [comment]
> I have a new account 

Its likely that they don't allow it for new accounts but I know they don't apply it to older accounts so you could ask how long until they will enable it for you or find another provider.

**Comment by Code-with-Shah** [comment]
Thanks @willpower232
