### ISSUE TITLE
Messages not being unqueued

### ISSUE THREAD

**Issue by tobeyadr** [postalhq/postal#1135]
Hi, we have `maximum_delivery_attempts` set to `1` but messages are still be requeued after a soft fail? This is causing a lot of issues for our customers. Any solution?

**Comment by tobeyadr** [comment]
Its not even respecting the default max delivery attempts of 18, it will keep re-queueing the email, some are at 27+ attempts

**Comment by willpower232** [comment]
Did you restart Postal after changing the configuration file?

**Comment by tobeyadr** [comment]
Yes, several times. still not luck

**Comment by willpower232** [comment]
I'm not sure how this is possible to be honest, unless you've made changes to app/jobs/unqueue_message_job.rb or you're saving the config file weirdly like putting quotes around the number or something.

You could check the database and see what the `attempts` count is for the message?

**Comment by tobeyadr** [comment]
We did an auto-upgrade and that appears to have resolved the problem.

**Comment by willpower232** [comment]
Good to know, it may be that some code changes were reverted or something else was cleared out during that process.

**Comment by gitbnitin** [comment]
is this resolved in some version?
