### ISSUE TITLE
Improve logging in smtp_sender.log file

### ISSUE THREAD

**Issue by nenominal** [postalhq/postal#1136]
Hello,

Currently we are implementing a centralized logging system using Elastic/Logstash/Kibana.
The logs from Postal are pushed using Filebeat to Logstash, imported in Elastic and view in Kibana.

It will be a great value if there we'll be a way to save in the **smtp_sender.log** the sender of the message, we have multiple domains from where we are sending e-mails but it's now really possible to identify the source of the sender from the log file.

**Comment by nenominal** [comment]
We've tested with gelf setting, it seems to be way better that filebeat in our case, I'm writing this here for anyone who wants to use ELK stack.

**Comment by willpower232** [comment]
The log entries in that file are roughly grouped by the reference in it so the detail is mostly gained from reading the whole group of entries. Are you able to group them in whatever you're using?

**Comment by nenominal** [comment]
After few days of using and testing it, the things that we are missing are the **from** field and we have to find a way to filter from log files the way that postal saves domain::message ID. 
Other than that, using gelf library, it works like a champ.
