### ISSUE TITLE
Huge Database 

### ISSUE THREAD

**Issue by rbustos** [postalhq/postal#1137]
Hi,
 Is there a way to clean up database size?
 Specially webhooks data.

```
82G	links.ibd.  <--- 
1.2G	messages.ibd
2.0G raw@002d2020@002d06@002d18.ibd
1.4G	raw@002d2020@002d06@002d19.ibd
1.5G	raw@002d2020@002d06@002d22.ibd
1.8G	raw@002d2020@002d06@002d23.ibd
2.3G raw@002d2020@002d06@002d25.ibd
1.7G	raw@002d2020@002d06@002d26.ibd
1.9G	raw@002d2020@002d06@002d30.ibd
2.9G raw@002d2020@002d07@002d01.ibd
1.7G	raw@002d2020@002d07@002d02.ibd
1.4G	raw@002d2020@002d07@002d03.ibd
19G	webhook_requests.ibd <---
```

**Comment by rbustos** [comment]
Looks like "links" are not cleaning as webhooks, clicks or messages do:

I've been testing by using following SQL:

```
SELECT t1.id, t1.message_id, DATE_FORMAT(FROM_UNIXTIME(t1.timestamp), '%e %b %Y') AS time, t1.url
  FROM links t1
  LEFT JOIN messages t2
    ON t2.id = t1.message_id
 WHERE t2.id IS NULL
 LIMIT 10
```

**As example:**
![image](https://user-images.githubusercontent.com/263415/86522505-ed761a00-be2c-11ea-90c8-cfca6b958df5.png)

**Comment by rbustos** [comment]
Not sure, but appears the job related don't consider "links" in the prune process defined at:

https://github.com/postalhq/postal/blob/51ba977bcc528b1977f12ec9541c3e07fc399b0e/lib/postal/message_db/provisioner.rb#L131

```
      #
      # Remove messages from the messages table that are too old to retain
      #
      def remove_messages(max_age = 60)
        time = (Date.today - max_age.days).to_time.end_of_day
        if newest_message_to_remove = @database.select(:messages, :where => {:timestamp => {:less_than_or_equal_to => time.to_f}}, :limit => 1, :order => :id, :direction => 'DESC', :fields => [:id]).first
          id = newest_message_to_remove['id']
          @database.query("DELETE FROM `#{@database.database_name}`.`clicks` WHERE `message_id` <= #{id}")
          @database.query("DELETE FROM `#{@database.database_name}`.`loads` WHERE `message_id` <= #{id}")
          @database.query("DELETE FROM `#{@database.database_name}`.`deliveries` WHERE `message_id` <= #{id}")
          @database.query("DELETE FROM `#{@database.database_name}`.`spam_checks` WHERE `message_id` <= #{id}")
          @database.query("DELETE FROM `#{@database.database_name}`.`messages` WHERE `id` <= #{id}")
        end
      end
```
Adding an extra line maybe fix this: 
` @database.query("DELETE FROM `#{@database.database_name}`.`links` WHERE `message_id` <= #{id}")`

Can you guys confirm?

Thanks

**Comment by willpower232** [comment]
The links table will be used to track clicks in emails but also if the links table is ever cleaned up, the links in those email messages will stop working so I would advise against clearing up that table if you can avoid it.

I guess the opposite argument would be if the links were all marketing-related so it might be more acceptable to have emails full of non-functional links if the email belongs to an older campaign which is no longer relevant but that is down to how you use Postal and your internal policies.

**Comment by rbustos** [comment]
We use Postal as SMTP Relay and it tracks daily emails only not a marketing gateway. In this way makes no sense to keep forever links data more than one day in our case. But we kept messages for 30 days long just for records on Postal. Everything is removed after that time but links. 

Our guess is that it should be cleaned somehow at least 60 days or a configurable time after message (timestamp). Otherwise it will keep growing as in our case.

We found data from 2018 in that table (links).

Hope it clarify the issue behind.

**Comment by willpower232** [comment]
For your particular use case, I'd say that 6months or a year as you have suggested would probably be fine for retaining links but Postal is not designed for that so I'd probably choose to apply a manual clear out process yourselves to remove older links.

**Comment by rbustos** [comment]
Thanks Will.
