### ISSUE TITLE
Notice: Finally Worked

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1138]
Hi, just wonder if the documentation and the installation script have differences. 

I tried to install Postal 2 times via the installation documentation with no success.  Then I tried via installation script and it worked. 
I customized the script for the password reasons and it was perfect. 

Just wanted to highlight this to your team.

**Comment by willpower232** [comment]
The documentation is a bit spread out so I think you would have to reference a couple of pages to get a fully finished setup in one go. What problems were you encountering?

**Comment by Igcorreia** [comment]
When manually Installing these are the 3 common error I found:

1.  When inviting admin users I always get an error. I understand now, that I need to get a SMTP server running than change the credentials until I figure that out, the common problem is that when I create a USER without the correct credentials, PostalHQ is not providing a proper error, so I had to go the ruby.log to figure out what was happening.

2. for some reason, the second time I installed Postal couldn't connect to Rabbit, again rails.log save me. At this point, I suggest a page in the admin area where we could see the last 1000 lines from the log files. That way we can easily debug the system.

3. Again from what I could figure out, It is not clear in the docs that the minimum requirements to create a smtp server is:
- smtp credentials
- smtp endpoint
- Router

If this is correct, maybe this could be added to the docs.

4. The default postal.yml config file has a few DNS lines that are less than what is possible, reading the docs, in the domain wiki page, I noticed that we can configure extra stuff, please consider adding the extra stuff to the default config, like: 

-   dkim_identifier: postal
-   domain_verify_prefix: postal-verification
-   custom_return_path_prefix: psrp

This was my experience after installing it 4 times. Hope this helps.
