### ISSUE TITLE
How to use Posatl mail server with Mailwizz.

### ISSUE THREAD

**Issue by skapati** [postalhq/postal#1139]
Hi, I built SMTP server using postal and when I am sending test mail working fine.
Postal mail server is installed on Do and port 25 is enabled here.
I want to use it with mailwizz which is installed on AWS and that doesn't have port 25 enabled.
How can I do this.Please help me.

**Comment by willpower232** [comment]
You can ask AWS to allow you to send email from your account which should allow the port to function for you.
