### ISSUE TITLE
How to get an SSL certificate for Postal SMTP Server?

### ISSUE THREAD

**Issue by Code-with-Shah** [postalhq/postal#1140]
How can I get an SSL certificate for Postal SMTP Server?

**Comment by willpower232** [comment]
You can either purchase one and install it to the server or get one from Lets Encrypt.

Either way, you will need to update the config file and restart Postal when you have certificates files on the server.

**Comment by Code-with-Shah** [comment]
Is there any guide for getting From let's Encrypt?

**Comment by willpower232** [comment]
You should follow their instructions relevant to your server OS and/or provider https://letsencrypt.org/getting-started/
