### ISSUE TITLE
Feature Request: wildcard email signature with wildcard subdomains for inbound and outbound

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1141]
After testing almost every single platform, I concluded that neither mandrill, postmark, aws ses, mailgun, spark, etc has the feature that I need, that is:

`[wildcard_signature]@[wildcard_sudbomain].[yourdomain].[extension]`

Let say I created Slack, and I want to use a custom domain prefix per space, so my space is going to be:

`postalhq.slack.com`

Now I need to send emails from this email, but another person creates:

`zoom.slack.com`

I need to send and receive emails from:

`*.slack.com`

so I need to verify * in the domain and * in the MX record

Now we need to add this domina to postal in order to set this up correctly so the final configuration would look like:

- add *.slack.com in the domain
- validate the domain, spf, dkim,returnpath and mx record
- add a custom domain we need to allow wild card  *@*slack.com
- create a routing system for the incoming emails so we can say that all emails coming from *@*.slack.com go to a HTTP enpoint to be integrated.

This is the reason that made me look for postal but unfriendly this is not possible, is it?

**Comment by willpower232** [comment]
I'm not sure you can get away without creating all the DNS records for each subdomain, regardless of Postals involvement.

I mean you may be able to modify Postal to achieve what you want but whether or not you will be able to actually convince other email systems to receive your email is another matter.

**Comment by Igcorreia** [comment]
So that only leaves me with one solution and that is to create a DNS record per each space (*.slack) and then create a wildcard inbound email. I was trying to avoid the need to create custom DNS records.

**Comment by willpower232** [comment]
It would be efficient but as I said, I don't think email itself was created to support that way.
