### ISSUE TITLE
Verify E-mail 

### ISSUE THREAD

**Issue by trancemanone** [postalhq/postal#1143]
Hi, 

My postal is working fine, even though I had to reinstall it fully yesterday on the same domain name. 

However, out of the blue its asking me to verify my email address and enter a 6 digits code. which I had never received even though I have tried for several hours. 

I have managed to change the email address but still no luck in receiving the magical code. 

The STMP server is working perfectly fine though. 

Thank you !

**Comment by willpower232** [comment]
This implies that your email address was changed within the system or maybe your user record was deleted and re added and there was some confusion.

If you haven't received the email, it may be that Postal has not been configured to send email through itself or something else so you may have to get into the database to set yourself as verified and continue using Postal.
