### ISSUE TITLE
Error inviting Admin Users

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1144]
This is the error regarding inviting admin users:

^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:10.924] INFO -- : Started POST "/org/MYORGANIZATION/users" for 000.00.000.00 at 2020-07-06 17:27:10 +0100
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:10.925] INFO -- : Processing by UsersController#create as JSON
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:10.926] INFO -- :   Parameters: {"utf8"=>"✓", "invite"=>"", "organization_user"=>{"email_address"=>"______@____.___", "admin"=>"true"}, "commit"=>"Add User", "org_permalink"=>"_____"}
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:10.953] INFO -- :   Rendering app_mailer/user_invite.text.erb
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:10.953] INFO -- :   Rendered app_mailer/user_invite.text.erb (0.1ms)
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:40.956] INFO -- : Sent mail to ______@_____.___(30002.6ms)
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:40.957] INFO -- : Completed 500 Internal Server Error in 30031ms (ActiveRecord: 12.8ms)
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:40.958] FATAL -- :
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:40.958] FATAL -- : Net::OpenTimeout (execution expired):
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:40.959] FATAL -- :
^[[34m[web.1:3786]^[[0m [2020-07-06T17:27:40.959] FATAL -- : config/initializers/smtp_extensions.rb:32:in `initialize'
config/initializers/smtp_extensions.rb:32:in `open'
config/initializers/smtp_extensions.rb:32:in `tcp_socket'
app/controllers/users_controller.rb:19:in `create'

I notice that testing the SMTP from external source I get this error:

![image](https://user-images.githubusercontent.com/1076409/86617320-f68ef480-bfae-11ea-9ab6-f1a90f5f774f.png)

Could that be the reason?

**Comment by Igcorreia** [comment]
I figure it out, after testing all combinations, the from_name needs to be with `""` and the remain must be used without `""`

**Comment by willpower232** [comment]
I'm confused, were you putting `"` in the form fields in the UI?

**Comment by Igcorreia** [comment]
Nope, in postal.yml @ smtp: config the from_name field.

**Comment by willpower232** [comment]
Ah yes, that is a YAML file so in order to have spaces and other certain characters as values, you need them to be wrapped in quotes are you've discovered.
