### ISSUE TITLE
Using ports 25 AND 2525 to receive emails from clients

### ISSUE THREAD

**Issue by areaeuro** [postalhq/postal#1148]
Hi

I have been using postal happily for over a year sending emails from different servers to postal on port 25.

However I now need to connect from an AWS EC2 instance (which has outgoing port 25 blocked by default).

When I set up the credentials for this server in web GUI I get the message that I can use Port 25 or 2525 for SMTP.
However my postal is not listening on port 2525:

netstat -lnp |grep 25
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1048/beam.smp   
tcp6       0      0 :::25                   :::*                    LISTEN      22756/[postal] smtp

Looking at that, it doesnt even seem its listening on port 25 for TCP V4, but it is.

Fire wall is OK for port 2525:
ufw status
Status: active

To                         Action      From
--                         ------      ----
22                      ALLOW       Anywhere                  
25                         ALLOW       Anywhere                  
80                         ALLOW       Anywhere                  
443                        ALLOW       Anywhere                  
2525                       ALLOW       Anywhere      

And I can happily telent in on port 25, but on port 2525 I get  "Connection refused"

The question is, what do I need to do to get postal to listen on both ports 25 (for existing clients) and port 2525 (for new AWS clients).

Any help greatly appreciated.

Regards

**Comment by willpower232** [comment]
You need to use iptables or ufw to use multiple ports, that used to be part of the standard installation but isn't the case any longer.

Have a read of https://github.com/postalhq/postal/issues/565, that seems to list your options.

**Comment by areaeuro** [comment]
@willpower232 Thanks for the info. Using port forwarding at firewall level worked just fine.

From the message inside GUI about port 2525 I was a little confused as to what was needed.

For anyone else who stumbles across this thread, here is what I did to get postal receiving emails on BOTH ports 25 AND 2525.

First enable port 2525 in UFW

> ufw allow 2525
> ufw reload
> ufw status


Then add the following to the top of /etc/ufw/before.rules:

> *nat 
> :PREROUTING ACCEPT [0:0] 
> :OUTPUT ACCEPT [0:0] 
> -A PREROUTING -d xxx.xxx.xxx.xxx -p tcp -m tcp --dport 2525 -j DNAT --to-destination xxx.xxx.xxx.xxx:25 
> -A OUTPUT     -d xxx.xxx.xxx.xxx -p tcp -m tcp --dport 2525 -j DNAT --to-destination xxx.xxx.xxx.xxx:25 
> COMMIT

^swap out xxx.xxx.xxx.xxx with your postal servers IP that is used to receive email from "clients"

Finally restart UFW:

> service ufw restart

And test from another box:

telnet your.postal.fqdn 2525

Thanks Will !!
