### ISSUE TITLE
How to change default Port SMTP port to 587 from 25 ?

### ISSUE THREAD

**Issue by bikramaaa** [postalhq/postal#1150]
Hello,
I am trying to build a mail server in GCP. As GCP has port 25 blocked I want to use port 587 to send out emails.
I have updated the port in postal.yml and restarted postal but still, it listens to port 25.
I have also added a firewall rule to allow port 587. But still no luck.
I have attached the screenshots.
Port 587 is open : [https://prnt.sc/tjdoni](url)
Postal Port: [https://prnt.sc/tjdoyq](url)

**Comment by willpower232** [comment]
You may be able to get your Postal to receive email on multiple ports (have a look at https://github.com/postalhq/postal/issues/565) but if your Postal is unable to communicate to other servers on port 25 then you may not be able to resolve this.

**Comment by dragoangel** [comment]
I use for this NAT.

**Comment by watchjobco** [comment]
@dragoangel 
Have you tried running the SMTP server on GCP?
Without Gsuite.

**Comment by dragoangel** [comment]
@watchjobco I doesn't think this is correct place to discuss stuff like hosting. This isn't Postal related. And just to answer your question: I doesn't have expirience in GCP.
