### ISSUE TITLE
Email Not Reaching Inbox or Spam

### ISSUE THREAD

**Issue by jamesjosh912** [postalhq/postal#1154]
I set up a postal SMTP server and I used smtper.net to test send an email to my personal email. It says it was sent successfully, but I checked my personal email and it was not there in the main inbox or spam. I used port 25. What could be the issue?

**Comment by willpower232** [comment]
If you expand the details in the Postal UI what does it say about the message?

Hotmail/Microsoft/Office 365 in particular is good at saying "Email queued for delivery" and deciding the message is spam so it never gets anywhere near you.
