### ISSUE TITLE
SMTP Send Timeout

### ISSUE THREAD

**Issue by AndyTempel** [postalhq/postal#1155]
I'm experiencing SMTP send timeouts when postal tries to forward mail to a specific server. 
```
[worker.4:3138] [2020-07-23T23:07:12.480] INFO -- : [RBHDZO3U] Cannot connect to ipv6-address:25 (redacted-domain.com) (Net::OpenTimeout: execution expired)
[worker.4:3138] [2020-07-23T23:07:42.483] INFO -- : [RBHDZO3U] Cannot connect to ipv4-address:25 (redacted-domain.com) (Net::OpenTimeout: execution expired)
[worker.4:3138] [2020-07-23T23:07:42.534] INFO -- : [RBHDZO3U] -> No SMTP server available for support.redacted-domain.com
[worker.4:3138] [2020-07-23T23:07:42.534] INFO -- : [RBHDZO3U] -> Hostnames: ["redacted-domain.com"]
[worker.4:3138] [2020-07-23T23:07:42.535] INFO -- : [RBHDZO3U] -> Errors: ["execution expired"]
[worker.4:3138] [2020-07-23T23:07:42.578] INFO -- : [RBHDZO3U] Finishing up
```

I'm able to connect via telnet to this specific server from the postal server:
```
root@vulture:~# telnet ipv4-address 25
Trying ipv4-address...
Connected to ipv4-address.
Escape character is '^]'.
220 redacted-domain.com ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
ehlo postal-redacted-domain.com
250-redacted-domain.com
250-PIPELINING
250-SIZE 134217728
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
quit
221 2.0.0 Bye
Connection closed by foreign host.
```

Postal is able to send and receive mail from eg. Gmail. And so is the server I'm trying to reach, that server also sends emails to postal that get processed correctly. Just connection from postal to that server timeouts. I don't even get any SMTP logs on the other side.
Are there any troubleshooting steps I can perform?

**Comment by willpower232** [comment]
Any chance it was a temporary error? I think you can try re sending the message in the Postal UI.

Might also be worth asking your server provider to see if there is anything on their end that would prevent consistent connections on port 25.

**Comment by AndyTempel** [comment]
I've re-tried delivery multiple times in the postal UI with the same results, both machines are on the same provider, I'll be contacting their support to be sure.

**Comment by willpower232** [comment]
telnet is certainly correct, I'd wonder if there was some kind of firewall internal to the provider that would be doing something to break the connection or if your Postal needs a restart maybe

**Comment by AndyTempel** [comment]
Is there a way to see from which IP is postal trying to send the message, or is there a way to force postal to use a specific address. I must add that I've enabled IP pools once, but since I've disabled them.

**Comment by hadifarnoud** [comment]
I get `No SMTP servers were available for bmsd.ir. Tried bmsd.ir Could not resolve bmsd.ir`error. is that related to this issue too?

It's worth noting the domain does resolve and have MX record set up as well. I have no idea why it does not send the email

**Comment by AndyTempel** [comment]
I've talked with technical support on my provider and they narrowed down the issue to a /64 IPv6 prefix that was causing the issue, removed it from the config and now it's sending emails correctly.
That said, is there a way to specify which IP address postal uses for sending?

**Comment by willpower232** [comment]
@hadifarnoud you should try using the `dig` command from the server to see if the DNS records are available to it, there might be a resolving error

@AndyTempel glad you figured it out, I believe it will use whatever the default IP address is like any other program that connects to the internet unless you're using the IP Pools feature
