### ISSUE TITLE
Postal.myl 

### ISSUE THREAD

**Issue by trancemanone** [postalhq/postal#1156]
Hi, 

Im trying to install multiple domains on one SMTP server, I have been facing some issues especially in the SPF record. 

Before diggining any deeper, is actually possible to have multiple domains on one Postal Server. If so then how to edit the Postal.myl file ? 

Thank you

**Comment by willpower232** [comment]
In postal.yml, you configure the main domain name for the server, how you will access it etc.

Then in the actual UI, you will add the domains that you want to send from.

(see also #1096)
