### ISSUE TITLE
This Site Can't Be Reached, 'mydomain' Refused to Connect

### ISSUE THREAD

**Issue by jamesjosh912** [postalhq/postal#1157]
I set up my postal smtp server and it was working fine and sending emails perfectly, but then all the sudden the webpage started saying "this site can't be reached, 'mydomain' refused to connect." I was trying to configure apache2 to this postal's ip, so maybe that messed it up somehow. How can I fix this?

**Comment by willpower232** [comment]
The default install makes use of nginx instead of apache so if you're working on the web server configuration, you'll need to make sure that apache is able to proxy to the UI port to see it.

You can also use `postal status` to verify that postal is still running.

**Comment by ImonAwesome** [comment]
Hello @willpower232 

Apology for opening an old issue,

I'm facing the same problem. I thought it's my server problem but I followed exact documentation but still getting "This site can’t be reached, domain.tld refused to connect."

I have tested on DO, Linode but still same. 

Postal Status
```
Pulling web    ... done
Pulling smtp   ... done
Pulling worker ... done
```

Caddyfile

```# Update this to match the hostname you wish to use for accessing the
# Postal web interface.
gregifinance.gastatus.com {
  reverse_proxy 185.116.236.38:5000
}
```

postal.yml - https://paste.mozilla.org/2a4yLsmR
