### ISSUE TITLE
Return-Path and SPF

### ISSUE THREAD

**Issue by AndrewBucklin** [postalhq/postal#1158]
If a **Return-Path** is included in an email header, the receiving mail server will use the domain specific in the **Return-Path** to check SPF. By default, the **Return-Path** is set to `psrp.domain.com`. More details about this topic can be found [here](https://mxtoolbox.com/dmarc/spf/setup/spf-return-path).

Here's the problem: On the DNS Setup page, it only asks the user to add an SPF record for the root domain (`domain.com`) and NOT the **Return-Path** domain (`psrp.domain.com`). As such, SPF lookups fail. You can test this by sending a test email with this utility: https://www.appmaildev.com/en/spf

I suggest one of the following solutions:
1. Allow for config setting in postal.yaml to set the Return-Path to match the root domain (`domain.com`). Currently the only option is to customize the _Return-Path prefix_ (subdomain).
- OR -
2. Update the DNS Setup page to ask the user to add a SPF record for the Return-Path domain (`psrp.domain.com`).

Thanks for such a wonderful product. I'm using this for personal-use; to replace MailGun.

**Comment by AndrewBucklin** [comment]
Ignore everything I said. I must be seeing things from lack of sleep. 😢

**Comment by willpower232** [comment]
The wiki tells you to create the SPF records for your return path domain https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

This means that the CNAME for psrp.yourdomain.com should lead any lookup to the SPF record.

![image](https://user-images.githubusercontent.com/1619102/88527172-d32af880-cff4-11ea-88be-b1a333ad76b5.png)

**Comment by AndrewBucklin** [comment]
You are right. Everything is working fine now. Maybe I missed something or maybe something was cached and cache has cleared by now.
