### ISSUE TITLE
The From address is not authorised to send mail from this server

### ISSUE THREAD

**Issue by akshaychauhan7737** [postalhq/postal#1161]
can you please send me curl request for send email api.

tryping 
curl --location --request POST 'https://139.59.70.136/api/v1/send/raw' \
--header 'X-Server-API-Key: <key here >' \
--header 'Content-Type: application/json' \
--data-raw '{
    "mail_from" : "support@primebachat.com",
    "rcpt_to" : ["akshaychauhan7737@gmail.com"],
    "data" : "aGV5IGhvdyBhcmUgeW91"
}'

response :
{
    "status": "error",
    "time": 0.0,
    "flags": {},
    "data": {
        "code": "UnauthenticatedFromAddress",
        "message": "The From address is not authorised to send mail from this server"
    }
}

NOTE : I have verified domain. 
Not able to send email from panel.

No SMTP servers were available for gmail.com. 
Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com

Technical specification
execution expired

**Comment by rbashish** [comment]
Is that the same domain you configured in `postal.yml` file?

**Comment by willpower232** [comment]
> The From address is not authorised to send mail from this server

This means that the credential you are using doesn't have primebachat.com as a domain in the same mail server so you will need to add it there.

> No SMTP servers were available

As per https://github.com/postalhq/postal/issues/369#issuecomment-665154718, your server provider is likely blocking port 25 or email sending so you should consult them to see if this is something that can be allowed for your server.

**Comment by akshaychauhan7737** [comment]
> Is that the same domain you configured in `postal.yml` file?

yes

**Comment by akshaychauhan7737** [comment]
> > The From address is not authorised to send mail from this server
> 
> This means that the credential you are using doesn't have primebachat.com as a domain in the same mail server so you will need to add it there.
> 
> > No SMTP servers were available
> 
> As per [#369 (comment)](https://github.com/postalhq/postal/issues/369#issuecomment-665154718), your server provider is likely blocking port 25 or email sending so you should consult them to see if this is something that can be allowed for your server.

i have added then email as i can send emails through smtp but not through api. I can send email using panel also

**Comment by akshaychauhan7737** [comment]
> > > The From address is not authorised to send mail from this server
> > 
> > 
> > This means that the credential you are using doesn't have primebachat.com as a domain in the same mail server so you will need to add it there.
> > > No SMTP servers were available
> > 
> > 
> > As per [#369 (comment)](https://github.com/postalhq/postal/issues/369#issuecomment-665154718), your server provider is likely blocking port 25 or email sending so you should consult them to see if this is something that can be allowed for your server.
> 
> i have added this email as i can send emails through smtp but not through api. I can send email using panel also
