### ISSUE TITLE
Can't receive incoming emails from other mail servers.

### ISSUE THREAD

**Issue by TheRealLunatite** [postalhq/postal#1163]
Hi , I have an issue where my domains isn't receiving incoming emails from other mail servers such as Google.

My web interface is being hosted on a subdomain <https://postal.luna-mail.xyz>.
I have all my DNS records configured for my domains correctly according to the webpage. 

### My MX record on namecheap
>![mx](https://i.vgy.me/9slVON.png)

### DNS Records for my email domains
> ![DNS Records](https://i.vgy.me/DlZObX.png)

### postal.yml
> dns:
>   mx_records:
>     - mx.postal.luna-mail.xyz
>   smtp_server_hostname: postal.luna-mail.xyz
>   spf_include: spf.postal.luna-mail.xyz
>   return_path: rp.postal.luna-mail.xyz
>   route_domain: routes.postal.luna-mail.xyz
>   track_domain: track.postal.luna-mail.xyz

Simulating a incoming / outgoing email by using the web interface works since my webhook is able to log the events and can be seen in my inbox.

I have my wildcard route sending all incoming messages from my domain to my HTTP endpoint.
![image](https://i.vgy.me/zQ3kGz.png)

I investigated this issue further but can't find a solution to this problem.
Anyone who can help with this problem thank you!

**Comment by willpower232** [comment]
`mx.postal.luna-mail.xyz` doesn't seem to exist in DNS unless I'm missing something?

**Comment by TheRealLunatite** [comment]
@willpower232 ah makes sense now. I don't have a DNS record for `mx.postal.luna-mail.xyz`. I'll refer back to this comment if I still stumble onto any issues.

**Comment by TheRealLunatite** [comment]
Thanks! I can receive incoming emails now when I set up my record.
