### ISSUE TITLE
 NoMethodError (undefined method `uuid' 

### ISSUE THREAD

**Issue by saschaarthur** [postalhq/postal#1164]
Hello,

When adding a user in the credentials section i get:

```
8:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.194] INFO -- : Processing by CredentialsController#create as JSON
08:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.194] INFO -- :   Parameters: {"utf8"=>"✓", "credential"=>{"type"=>"SMTP", "name"=>"", "key"=>"", "hold"=>"false"}, "commit"=>"Create credential", "org_permalink"=>"xx", "server_id"=>"xxx"}
08:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.211] INFO -- : Completed 500 Internal Server Error in 18ms (ActiveRecord: 5.8ms)
08:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.213] FATAL -- :
08:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.213] FATAL -- : NoMethodError (undefined method `uuid' for #<Credential:0x00007f2e60041c68>):
08:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.213] FATAL -- :
08:51:23 web.1              | => [web.1:28] [2020-08-05T08:51:23.213] FATAL -- : app/controllers/credentials_controller.rb:18:in `create'
08:51:23 web.1              | => 10.9.0.1 - - [05/Aug/2020:08:51:23 +0000] "POST /500 HTTP/1.1" 500 46 0.0239
```

How to solve this?!

**Comment by willpower232** [comment]
Have you recently upgraded? Was it a successful upgrade? Did you restart Postal after doing so?

**Comment by saschaarthur** [comment]
Hello

its a fresh install and i guess its somehow related to this commit here: https://github.com/postalhq/postal/commit/9a3d568b27f101610147d04f97d5940875e98258

**Comment by saschaarthur** [comment]
checked out 5c7802d218d408c1116f4db6f730145cbff4f878, and works without issues..

**Comment by willpower232** [comment]
interesting, did you install from the script? what is the output of `postal version`?

**Comment by saschaarthur** [comment]
using this container here: https://github.com/CatDeployed/docker-postal (ubuntu)

**Comment by willpower232** [comment]
I suggest you make an issue in their github repo because we can't support other peoples docker containers.

**Comment by moqmar** [comment]
For other people coming here: running [`postal upgrade`](https://github.com/postalhq/postal/wiki/Upgrading) fixes the issue - it can happen after a "manual" update (i.e. pulling a newer Docker image).

**Comment by saschaarthur** [comment]
> 
> 
> For other people coming here: running [`postal upgrade`](https://github.com/postalhq/postal/wiki/Upgrading) fixes the issue - it can happen after a "manual" update (i.e. pulling a newer Docker image).

Awesome! i will really  try this out if this solves my issues.. searched hours for a working solution.. i thought its some missing librarys or something like that..

**Comment by saschaarthur** [comment]
@moqmar thanks, this worked perfectly out !
