### ISSUE TITLE
How To Change Outbound Email Port

### ISSUE THREAD

**Issue by jamesjosh912** [postalhq/postal#1165]
Hi, I want to send emails with my postal smtp server from a port other than port 25 because my ISP blocks port 25. How can I change this?

**Comment by willpower232** [comment]
The block will likely prevent your Postal connecting to other email servers so changing your own port won't have any effect. If your provider will not ever remove the block, I'm afraid you would have to find another.

**Comment by jamesjosh912** [comment]
Do you know other smtp servers I can use that can use port 587 or others?
