### ISSUE TITLE
SPF record for psrp.domain FAIL when CNAME in place

### ISSUE THREAD

**Issue by uhlhosting** [postalhq/postal#1168]
Hi,

According to the test made https://www.mail-tester.com/test-vq47sogw4

Sender Policy Framework (SPF) is an email validation system designed to prevent email spam by detecting email spoofing, a common vulnerability, by verifying sender IP addresses.

You do not have a SPF record, please add the following one to your domain psrp.ecunative.eu:
`v=spf1 a mx ip4:92.222.242.243 ~all`
**_The Name Server handling the domain name psrp.ecunative.eu is post.uhlhosting.ch._**

```
dig +short TXT psrp.ecunative.eu :
post.uhlhosting.ch.
"google-site-verification=fMErSxqGdwID9T50TF-LL0SIG2A4kr1l0wcT2wUT628"
dig +short TXT @post.uhlhosting.ch. psrp.ecunative.eu :
;; connection timed out; no servers could be reached
spfquery --scope mfrom --id nk4d3v@psrp.ecunative.eu --ip 92.222.242.243 --helo-id post.uhlhosting.ch :
none
psrp.ecunative.eu: No applicable sender policy available
psrp.ecunative.eu: No applicable sender policy available
Received-SPF: none (psrp.ecunative.eu: No applicable sender policy available) receiver=ns303428.ip-94-23-206.eu; identity=mailfrom; envelope-from="nk4d3v@psrp.ecunative.eu"; helo=post.uhlhosting.ch; client-ip=92.222.242.243
```

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/6324047/89555023-dea9cb00-d80f-11ea-90dd-f01d435d7617.png">

- - - txt:psrp.ecunative.eu

 1 x.dns.eu 185.151.141.1 NON-AUTH 31 ms Received 2 Referrals , rcode=NO_ERROR  ecunative.eu. 86400 IN NS dns2.uhlhosting.ch,ecunative.eu. 86400 IN NS dns1.uhlhosting.ch,
 2 dns2.uhlhosting.ch 137.74.247.213 AUTH 94 ms Received 3 Answers , rcode=NO_ERROR  psrp.ecunative.eu. 14400 IN CNAME post.uhlhosting.ch,post.uhlhosting.ch. 14400 IN TXT v=spf1 a mx include:spf.post.uhlhosting.ch ~all,post.uhlhosting.ch. 14400 IN TXT google-site-verification=fMErSxqGdwID9T50TF-LL0SIG2A4kr1l0wcT2wUT628,

* Found CNAME on 'psrp.ecunative.eu' of 'post.uhlhosting.ch'

- - - txt:post.uhlhosting.ch

```
 1 g.nic.ch 194.0.1.40 NON-AUTH 0 ms Received 2 Referrals , rcode=NO_ERROR  uhlhosting.ch. 3600 IN NS dns1.uhlhosting.ch,uhlhosting.ch. 3600 IN NS dns2.uhlhosting.ch,
 2 dns1.uhlhosting.ch 178.209.50.201 AUTH 109 ms Received 2 Answers , rcode=NO_ERROR  post.uhlhosting.ch. 14400 IN TXT google-site-verification=fMErSxqGdwID9T50TF-LL0SIG2A4kr1l0wcT2wUT628,post.uhlhosting.ch. 14400 IN TXT v=spf1 a mx include:spf.post.uhlhosting.ch ~all,
Record returned is an RFC 4408 TXT record.<br/>
MAIL FROM: info@ecunative.eu
RETURN-PATH: nk4d3v@psrp.ecunative.eu
IP for SPF Authentication: 92.222.242.243

- - Ranges
- A:post.uhlhosting.ch
92.222.242.243/32

- - Subqueries
A:post.uhlhosting.ch
MX:post.uhlhosting.ch
TXT:spf.post.uhlhosting.ch


- - Results
TXT:spf.post.uhlhosting.ch = None
TXT:post.uhlhosting.ch = Pass
WebServer 1467ms
```
  

Any idea how to solve this issue since according to the way DNS works I cannot make a new entry of type TXT for domain psrp.ecunative.eu since I have a CNAME in place there pointing to post.uhlhosting.ch ?

**Comment by dragoangel** [comment]
> Any idea how to solve this issue since according to the way DNS works I cannot make a new entry of type TXT for domain psrp.ecunative.eu since I have a CNAME in place there pointing to post.uhlhosting.ch ?

Not use CNAME in this case for example, use A\AAA records & TXT.

**Comment by willpower232** [comment]
For more information on what DNS records are required, have a look in the wiki https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

**Comment by dragoangel** [comment]
Also want to note that `~all` in this manual better be changed to `-all` in terms of better spoofing protection.

**Comment by willpower232** [comment]
that would be nice to at least be noted in the wiki yes, unfortunately all I can do is reply here!

**Comment by dragoangel** [comment]
For me `~all` in SPF and `p=none|quarantine` in DMARC, it like: hey I have wrong configuration, but still please get my mail or spammers mail which send from unauthorized MTA using my domain =).

**Comment by chralg** [comment]
Hi,

Regarding SFP and psr.yourdomain.com being a CNAME. You need to do add the TXT SPF record to the reflected domain record.

Example.
$ host psrp.yourdomain.com
psrp.yourdomain.com is an alias for rp.mail.yourdomain.com.
rp.mail.yourdomain.com has address 192.0.0.4

$ dig +short TXT psrp.yourdomain.com
rp.mail.yourdomain.com.

Since psrp.yourdomain.com is reflecting rp.mail.yourdomain.com, your need to add the TXT SPF record to  rp.mail.yourdomain.com.

Result is

$ dig +short TXT psrp.yourdomain.com
rp.mail.yourdomain.com.
"v=spf1 mx include:spf.yourdomain.com -all"


Hope this helps.

Chris
