### ISSUE TITLE
ISP Blocks Port 25 Con't

### ISSUE THREAD

**Issue by jamesjosh912** [postalhq/postal#1169]
So am I basically hopeless in terms of doing a cold email campaign if port 25 is blocked by my ISP, since all smtp's have to use port 25. Is my only option signing up for a cold emailing subscription company? Could I hook up Gsuite (google's mass emailer) to a mass sending tool, or does that have to access port 25 as well?

**Comment by dragoangel** [comment]
Hi, you can buy any x86 Ubuntu based VPC for 5-10$/y with public IP & PTR (reverseDNS) and install Postal there. There nothing much to discus if your ISP not allow to use 25 and do not provide you PTR.

**Comment by willpower232** [comment]
I don't really have anything to add to the above except to say that Postals primary focus is not cold emailing so you will definitely be better served by other software.
