### ISSUE TITLE
Change date on Website from 2018

### ISSUE THREAD

**Issue by davidkartuzinski** [postalhq/postal#1170]
Hello! This is a simple issue on the website: https://postal.atech.media/

The copyright date says 2018 and that makes the project look unmaintained :( 

Thanks this project looks incredible and I look forward to testing it.

**Comment by willpower232** [comment]
I think a lot of that page needs updating haha

**Comment by davidkartuzinski** [comment]
I guess this issue can be closed as when ever you update the page, you will undoubtedly update the date! Good luck, this project looks promising and I know people are getting real benefit from it.
