### ISSUE TITLE
SMPT Server Unresponsive - please help

### ISSUE THREAD

**Issue by feedpeepxans** [postalhq/postal#1171]
Hi so I've setup my DNS records linking postal and my domain on godaddy, i've changed the config file in postal so that there's no longer postal.example.com addresses but now postal.(mydomain), I've added a user, and I've restarted postal numerous times. However, I cannot seem to connect to the SMPT server in any way shape or form. Cannot send a test email from anywhere.

I get this error on smtper when I use my domain for the host:
SMTP send error
The operation has timed out.

And I get this error on smtper when I use my SMPT server address as host (postal.mydomain)
SMTP send error
Failure sending mail.
No such host is known.

Please help, and let me know if more info is needed.

**Comment by willpower232** [comment]
You can use https://www.whatsmydns.net/ to check that your DNS records are working but it might also be firewall related

**Comment by feedpeepxans** [comment]
@willpower232 Thank you for replying. 
When checking my DNS records on that site I see that my A records point to my server IP, and my TXT records show my SPF records. In other words, on the postal site for my server it says my domain DNS records are successfully setup; every record is linked except for the Return Path, which is not mandatory.

It could be a firewall issue but I'm not sure. So far I have turned off my firewall on my mac computer, which is running GoPhish on a virtual machine.- But this has not fixed the issue

**Comment by willpower232** [comment]
The firewall is likely to be on your server or server provider rather than your local computer.

**Comment by feedpeepxans** [comment]
@willpower232 When checking the digitalocean ubuntu server via command prompt I see that the firewall is disabled- I checked this with ufw status.

On the digitalocean site there doesn't appear to be any firewall setup on my "droplet". I could enable a "private IP Network" on the server- not sure if this would do anything.

**Comment by willpower232** [comment]
digitalocean also has a cloud firewall feature which might need tweaking and we also know that some new digitalocean users are not allowed to use Port 25 by default so it might be worth checking with them as well.
