### ISSUE TITLE
Abort during initialize

### ISSUE THREAD

**Issue by bluebaroncanada** [postalhq/postal#1174]
During the installation, I'm getting an Abort error:

```
vagrant@vagrant:~$ postal initialize
Initializing database
/var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
/var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
/opt/postal/vendor/bundle/ruby/2.7.0/gems/faraday-0.15.2/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead

...

7fe72fbe4000-7fe72fbea000 r--p 0032c000 fd:00 3414330                    /usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7.0
7fe72fbea000-7fe72fbeb000 rw-p 00332000 fd:00 3414330                    /usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7.0
7fe72fbeb000-7fe72fc07000 rw-p 00000000 00:00 0
7fe72fc07000-7fe72fc0e000 r--s 00000000 fd:00 3410741                    /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7fe72fc0e000-7fe72fc0f000 r--p 00000000 fd:00 3410760                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fe72fc0f000-7fe72fc32000 r-xp 00001000 fd:00 3410760                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fe72fc32000-7fe72fc3a000 r--p 00024000 fd:00 3410760                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fe72fc3b000-7fe72fc3c000 r--p 0002c000 fd:00 3410760                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fe72fc3c000-7fe72fc3d000 rw-p 0002d000 fd:00 3410760                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fe72fc3d000-7fe72fc3e000 rw-p 00000000 00:00 0
7ffd4a1d2000-7ffd4a9d1000 rw-p 00000000 00:00 0                          [stack]
7ffd4a9f1000-7ffd4a9f4000 r--p 00000000 00:00 0                          [vvar]
7ffd4a9f4000-7ffd4a9f5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]


/usr/bin/postal: line 19: 29289 Aborted                 sudo -u postal bundle exec rake db:schema:load db:seed
```

Here's my Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
   config.vm.provision "shell", inline: <<-SHELL
		set -xv
		sudo apt-get update -y
		sudo apt-get install curl gnupg ruby ruby-dev build-essential libmysqlclient-dev nodejs mysql-server -y
		sudo mysql -e "CREATE DATABASE postal CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;"
		sudo mysql -e "CREATE USER 'postal'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'postal'@'localhost'; FLUSH PRIVILEGES;"
		sudo mysql -e "CREATE USER 'postal'@'127.0.0.1' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON \`postal-%\` . * to 'postal'@'127.0.0.1';"
		curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -
		sudo apt-get install apt-transport-https
		sudo useradd -r -m -d /opt/postal -s /bin/bash postal
		sudo echo deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang >> /etc/apt/sources.list.d/bintray.rabbitmq.list
		sudo echo deb https://dl.bintray.com/rabbitmq/debian bionic main >> /etc/apt/sources.list.d/bintray.rabbitmq.list
		sudo apt-get update -y
		sudo apt-get install rabbitmq-server -y --fix-missing
		sudo rabbitmqctl add_vhost /postal
		sudo rabbitmqctl add_user postal password
		sudo rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"
		sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.7
		sudo gem install bundler
		sudo gem install procodile
		gem install bundler:1.17.2
		sudo -i -u postal mkdir -p /opt/postal/app
		wget https://postal.atech.media/packages/stable/latest.tgz -O - | sudo -u postal tar zxpv -C /opt/postal/app
		sudo ln -s /opt/postal/app/bin/postal /usr/bin/postal
		postal bundle /opt/postal/vendor/bundle
		postal initialize-config
		sudo sed -i 's/password\\:.*/password\\: password/' /opt/postal/config/postal.yml
		#postal initialize
   SHELL
end

```

**Comment by willpower232** [comment]
It may be that ruby 2.7 isn't supported, I can see from the Dockerfile in the repository that 2.6 has been successfully used. Are you able to try Vagrant with ruby 2.6?

**Comment by bluebaroncanada** [comment]
Okay, that works.  You should probably triage this as a bug instead of support, then.

**Comment by bluebaroncanada** [comment]
btw, this is a critical issue if you're using Ubuntu 20.04, because Ruby 2.6 is not yet available for 20.04.

**Comment by bluebaroncanada** [comment]
I actually had to change to 18.04 to get it to work.  Here's my new script.

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.box = "bento/ubuntu-18.04"
   config.vm.provision "shell", inline: <<-SHELL
		set -xev
		sudo apt-get update -y
		sudo apt-get install curl gnupg ruby ruby-dev build-essential libmysqlclient-dev nodejs mysql-server nginx -y
		sudo mysql -e "CREATE DATABASE postal CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;"
		#sudo mysql -e "CREATE USER 'postal'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'postal'@'localhost'; FLUSH PRIVILEGES;"
		#sudo mysql -e "CREATE USER 'postal'@'127.0.0.1' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON \`postal-%\` . * to 'postal'@'127.0.0.1';"
		
		sudo mysql -e " GRANT ALL PRIVILEGES ON *.* TO 'postal'@'localhost' identified by 'password'; FLUSH PRIVILEGES;"
		
		curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -
		sudo apt-get install apt-transport-https
		sudo useradd -r -m -d /opt/postal -s /bin/bash postal
		sudo echo deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang >> /etc/apt/sources.list.d/bintray.rabbitmq.list
		sudo echo deb https://dl.bintray.com/rabbitmq/debian bionic main >> /etc/apt/sources.list.d/bintray.rabbitmq.list
		sudo apt-get update -y
		sudo apt-get install rabbitmq-server -y --fix-missing
		sudo rabbitmqctl add_vhost /postal
		sudo rabbitmqctl add_user postal password
		sudo rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"
		sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby2.5
		sudo gem install bundler
		sudo gem install procodile
		gem install bundler:1.17.2
		sudo -i -u postal mkdir -p /opt/postal/app
		wget https://postal.atech.media/packages/stable/latest.tgz -O - | sudo -u postal tar zxpv -C /opt/postal/app
		sudo ln -s /opt/postal/app/bin/postal /usr/bin/postal
		postal bundle /opt/postal/vendor/bundle
		postal initialize-config
		sudo sed -i 's/password\\:.*/password\\: password/' /opt/postal/config/postal.yml
		postal initialize
		postal start
		
		cat << 'EOF' >> /etc/nginx/sites-enabled/postal
server {
    listen [::]:80;
    listen 0.0.0.0:80;

    root /opt/postal/app/public;
    server_name _;

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }
}
EOF

		service nginx restart
		
   SHELL
end

**Comment by willpower232** [comment]
as Postals support for Ubuntu 20.04/ruby 2.7 support has not happened yet, downgrading is the solution for now.
