### ISSUE TITLE
Consumers not re-registering with MQ after unexpected closure of MQ

### ISSUE THREAD

**Issue by DandyDeveloper** [postalhq/postal#1176]
I have occasional issues with the deploy RabbitMQ instance on Kubernetes that is used for managing the messages from Postal. 

This causes the RabbitMQ container to restart, which seems to drop the consumers from the Postal worker.

There's a small error that shows the consumers dropping, but Postal doesn't seem to recover from this unless the container is forcibly restarted. 

Postal for whatever reason still sends messages to the queues, it's just the consumers that never come back,

**Comment by willpower232** [comment]
Are you able to share the command you're running on the consumers pod?

**Comment by DandyDeveloper** [comment]
@willpower232 

I've ripped out the chart which apparently is just calling:

```
  postal run
```

With the following in the config: 
```
    workers:
      quantity: 5
      threads: 4
```

Nothing explicitly spinning up a worker process, all within the core Postal service.

**Comment by willpower232** [comment]
I can't find it explicitly documented but I believe a better kubernetes approach is to run each of Postals commands in separate pods, you can see the individual commands here: https://github.com/postalhq/postal/blob/master/Procfile

That way, kubernetes should restart the pod if the command fails.

@adamcooke said there had been some progress running it in kubernetes a while ago so it would be good to get a bit of clarification and/or an update on that

**Comment by DandyDeveloper** [comment]
@willpower232 I can make some huge adjustments to the helm chart, unless those already exists? I was using what at the time was deprecated, is there a new version anywhere?

**Comment by willpower232** [comment]
I'm not aware of an official helm chart for postal unless its somewhere I'm not seeing :sweat_smile:

**Comment by DandyDeveloper** [comment]
@willpower232 It may have been unofficial, I don't even remember where I pulled it from. 

I'll make some adjustments based on the procfile commands to have dedicated workers. I think the larger issue may be that this Postal container is running from an entrypoint managing several processes. So if PID 1 isn't terminating (main postal) the container doesn't restart, so consumers stay permanently dropped. 

I'll get this separation sorted.

**Comment by DandyDeveloper** [comment]
@willpower232 I think we can close this. I'v procured a chart that separates things into their own component pods and tested this to produce a similar failure scenario, seems like it recovers when the processes are correctly sharded into their own containers. 

Seems to have resolved things long term for us with regards to the MQ recovery.

**Comment by willpower232** [comment]
Thanks for letting us know, are you able to share the helm chart? I'm sure others would be interested.

**Comment by DandyDeveloper** [comment]
@willpower232 I am looking into opensourcing it within my company itself, which will take a little longer then doing it myself. I'll report here when it's available and would absolutely welcome some adjustments.
