### ISSUE TITLE
Uninstall Postal

### ISSUE THREAD

**Issue by trancemanone** [postalhq/postal#1177]
Hi, 

Well, I did screw up. 

I have tried to install Postal on The same vps as Mautic. 

The installation returned an error (of course) but mautic kept on working fine and collapsed few days later. It still worked (still sent emails as per the planned queue) but I couldnt access it via url. 

My last hope is to uninstall postal ( Nginx too) to hopefully get mautic back. 

Any ideas ? 

Thanks !

**Comment by willpower232** [comment]
Unfortunately for this problem, Postal does not have an uninstaller but there are a couple of things you can check. It might be that Mautic requires access to port 25 so you could change Postal so it uses a different port.

Regarding nginx, its possible that both bits software are trying to make use of the "default" nginx file so you could try configuring nginx separately and make use of a different (sub)domain for one of them.

**Comment by trancemanone** [comment]
I think I have found a clue. 

Postal requires Nginx server .. while Mautic was built on Apache. 

Ill let you know what happens next if I uninstall Nginx.

**Comment by trancemanone** [comment]
> I think I have found a clue. 
> 
> Postal requires Nginx server .. while Mautic was built on Apache. 
> 
> Ill let you know what happens next if I uninstall Nginx. 

Worked like a charm. 

Had to reinstall dmaria and fix sone erorrs 

Also reinstall SSL certificates and make sure Mautic required installations are set up correctly.

**Comment by willpower232** [comment]
glad you figured it out, you should be able to get apache to proxy to port 5000 to access the UI, or modify the nginx configuration to bind to a different port/IP address depending on what you have available.

**Comment by alishehryar1** [comment]
Hi, Hope u guys doing well. I really need your help. Kindly guide me to install Postal and Mautic Perfectly on Same VPS
