### ISSUE TITLE
Soft fail on all deliveries

### ISSUE THREAD

**Issue by datgb** [postalhq/postal#1178]
Unable to send emails to Tutanota or Protonmail addresses. tuta.io

Host Digital Ocean. Port 25 is open. Shows ipv6 not enabled in backend.

```
No SMTP servers were available for tuta.io. Tried mail.tutanota.de

execution expired

Support Ref: ABYFJFGA
```
Same error with protonmail
```

No SMTP servers were available for protonmail.com. Tried mail.protonmail.ch and mailsec.protonmail.ch

execution expired

Support Ref: ED1JVFCJ
```

**Update**

Enabled ipv6 to test again and still soft fail.

**Update:** Port is open where I can reach protonmail. But I still get soft fail on Tutanota

```
August 17, 2020 22:11
Soft fail

Temporary SMTP delivery error when sending to mail.tutanota.de (81.3.6.162)
```

**Comment by datgb** [comment]
decided to enable ipv6 and was able to ping6 google but was unable to access the website to test it. 502 error.

**Comment by datgb** [comment]
Enabled ipv6 to test again and still soft fail.

**Comment by grrinch** [comment]
Hey,

I just tested it on my server, also Digital Ocean, and it went through fine:

![image](https://user-images.githubusercontent.com/5729796/90748920-15cdb100-e2d3-11ea-8a7e-6e39212a1975.png)

Are you sure you don't hold your emails and then you're trying to release them after too long?

Execution expired would suggest that the mail was sitting in the queue for too long?

**Comment by willpower232** [comment]
>No SMTP servers were available

This means your server wasn't able to connect to their servers. If your account with Digital Ocean is new, then it may port 25 is being blocked by them. Alternatively, the IP address you're using may be on a block list.

**Comment by datgb** [comment]
Its an old account and I contacted DO support to ensure my ports werent blocked. They're open. And I got thru to protonmail so not sure why it wasnt going thru to tuta. Will try a few other emails.

**Comment by willpower232** [comment]
It might also be worth using the `dig` command from the server to see if you are able to resolve those DNS addresses in case theres some kind of DNS problem.

**Comment by aliyenidede** [comment]
try this spf

"v=spf1 ip4:XX.XX.XX.XX ip6:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX ~all"

its works for me
