### ISSUE TITLE
List of routes returns err 500 if you delete an endpoint with a route attached to it

### ISSUE THREAD

**Issue by grrinch** [postalhq/postal#1179]
Hi all,

Postal is great - I've been using it for a little while and I must say that it works wonders.

One issue I have come across recently (today) is when you delete an endpoint (HTML, smtp or address) to which there are routes still attached.

It makes sense that the Routes tab comes up with an internal server error as there are routes with no endpoint.

Is there a way to remove this route through a console or somehow else? I have the deleted endpoint's id.

Here's the rails.log:

```[web.1:2127] [2020-08-18T18:19:57.256] INFO -- : Processing by RoutesController#index as HTML
[web.1:2127] [2020-08-18T18:19:57.256] INFO -- :   Parameters: {"org_permalink"=>"blue-starling-media-2", "server_id"=>"bsm-mailgun-server"}
[web.1:2127] [2020-08-18T18:19:57.282] INFO -- :   Rendering routes/index.html.haml within layouts/application
[web.1:2127] [2020-08-18T18:19:57.289] INFO -- :   Rendered servers/_sidebar.html.haml (6.5ms)
[web.1:2127] [2020-08-18T18:19:57.301] INFO -- :   Rendered servers/_header.html.haml (11.5ms)
[web.1:2127] [2020-08-18T18:19:57.302] INFO -- :   Rendered routes/_header.html.haml (0.6ms)
[web.1:2127] [2020-08-18T18:19:57.315] INFO -- :   Rendered routes/index.html.haml within layouts/application (33.0ms)
[web.1:2127] [2020-08-18T18:19:57.316] INFO -- : Completed 500 Internal Server Error in 60ms (ActiveRecord: 7.8ms)
[web.1:2127] [2020-08-18T18:19:57.317] FATAL -- :
[web.1:2127] [2020-08-18T18:19:57.318] FATAL -- : ActionView::Template::Error (undefined method `description' for nil:NilClass):
[web.1:2127] [2020-08-18T18:19:57.318] FATAL -- :     40:             .routeList__details
    41:               %p.routeList__endpoint{:class => "routeList__endpoint--#{route.endpoint_type&.underscore || 'none'}"}
    42:                 - if route.mode == 'Endpoint'
    43:                   = route.endpoint.description
    44:                 - else
    45:                   = t("route_modes.#{route.mode.underscore}")
    46:               %p.routeList__spamMode= t("route_spam_modes.#{route.spam_mode.underscore}")
[web.1:2127] [2020-08-18T18:19:57.318] FATAL -- :
[web.1:2127] [2020-08-18T18:19:57.318] FATAL -- : app/views/routes/index.html.haml:43:in `block (2 levels) in _app_views_routes_index_html_haml___3461407834323555939_49547040'
app/views/routes/index.html.haml:38:in `block in _app_views_routes_index_html_haml___3461407834323555939_49547040'
app/views/routes/index.html.haml:36:in `each'
app/views/routes/index.html.haml:36:in `_app_views_routes_index_html_haml___3461407834323555939_49547040'```

**Comment by grrinch** [comment]
OK, I figured it out...

In my case I only had 1 route with a SMTP Endpoint, so I went to Postal console and after a little bit of trial and error, queried this:

```Route.find_by_sql('SELECT * FROM `routes` WHERE `endpoint_type` = "SMTPEndpoint"')```

And it returned me something like this:

```[#<Route id: 23, uuid: "6ba9b662-7e3e-4a2b-808d-c172c3198edd", server_id: 2, domain_id: 4, endpoint_id: 1, endpoint_type: "SMTPEndpoint", name: "test", spam_mode: "Mark", created_at: "2020-08-18 18:02:04", updated_at: "2020-08-18 18:02:04", token: "fj9f3gTZ", mode: "Endpoint">]```

After which I could delete it with the following command:

```Route.delete(23)```

I had no idea what `delete()` was meant to get as an argument, but I was guessing it takes the route's id. It did 😄 

After which I could check if that route was removed using the same command as previously: 
```Route.find_by_sql('SELECT * FROM `routes` WHERE `endpoint_type` = "SMTPEndpoint"')```

Since it returned no records `[]` I went to the web UI and tried accessing the routes again (`/org/[organisation-name]/servers/[server-name]/routes`) and this time it worked :)

Hope it helps someone hitting the same issue!

**Comment by willpower232** [comment]
I'm going to open this for further investigation

**Comment by adamcooke** [comment]
Can't reproduce this.
