### ISSUE TITLE
Outbound message hitting spam threshold cannot be redelivered

### ISSUE THREAD

**Issue by grrinch** [postalhq/postal#1180]
Hi,

I just had a message trigger an outbound spam threshold set to quite low and the spamassassin's classification not being something I want to worry about (for curious of you, it's LH_URI_DOM_IN_PATH - URI: Long-host URI having a domain name in the path part).

The message rightfully hit a Hard Fail:

![image](https://user-images.githubusercontent.com/5729796/90680842-c354ac00-e262-11ea-922d-64722c236d5a.png)

And it's OK, but I then wanted to increase the threshold to let this one through, so I went to advanced settings and set it to 3.2. For my surprise, this happened:

![image](https://user-images.githubusercontent.com/5729796/90680943-e67f5b80-e262-11ea-96c1-a7dcd8b213dc.png)

Tried restarting Postal and spamassassin, but nothing budged. 

So I thought to myself - hmm, ok, let me set it higher. Still, nothing helped:

![image](https://user-images.githubusercontent.com/5729796/90681018-06168400-e263-11ea-85f8-cc780878437a.png)

I think that an outbound message once marked as spam, won't be re-evaluated, hence, creating this issue.

**Comment by willpower232** [comment]
Definitely something awry here

**Comment by adamcooke** [comment]
Spam checks are run when the message arrives with Postal not when delivery is attempted to an external destination. In this case the message was detected as spam and won't be rechecked on subsequent delivery attempts.
