### ISSUE TITLE
Allot multiple IP pools to a mail-server

### ISSUE THREAD

**Issue by JaiBansal24** [postalhq/postal#1190]
Hi,
I have recently added 5 new IP to my Postal server.  So, now I have 6 IP addresses.  Let's say IP 1 to 6.

Issue:
There are several users whom I want to assign customized resources.

I setup the IP pools:
   IP-Pool-A with IP 1,2,3
   IP-Pool-B with IP 4
   IP-Pool-C with IP 5
   IP-Pool-D with IP 6

I assign all of the above pools to one organization using a very friendly check box !

Problem:
In Mail Server Settings, I can choose (and allot) only one of the IP pools :(

![image](https://user-images.githubusercontent.com/47874965/91503629-964e6c00-e8e8-11ea-97bc-197d61e88456.png)

As a result, this customer can use only one IP pool, even if he pays me for 6 IP ?????
and even though I allotted all 6 IP to him.

Now, if I make a new pool with all 6 IP, then I cannot create any other single-IP pools for other customers, as it says "Ipv4 has already been taken"

![image](https://user-images.githubusercontent.com/47874965/91503730-e299ac00-e8e8-11ea-879b-52d722d95d06.png)

As a result, only one 6-IP pool will be created and then I will have to give it to everyone for free

Suggestion:

Option-1 (better) :   The customer should get option to select multiple IP pools using the check-box system instead of a Drop-down.

![image](https://user-images.githubusercontent.com/47874965/91503801-09f07900-e8e9-11ea-9411-ebb7c58a6591.png)

Option-2 :   Allow same IP to be added in multiple IP pools to enable custom packages

Rgds,
Jai

**Comment by willpower232** [comment]
I believe IP Pools should be used exclusively by one organization/customer otherwise anyone using the pool could affect the other customers using the pool and then they don't really have exclusivity or reliability on the IP address(es), or have I misunderstood what you're doing?

**Comment by JaiBansal24** [comment]
That is Partly correct for a single unique scenario only.

But sometimes, we need to an IP to be 'shared' with multiple users.

You don't pay me extra, so you get a certain combo of IPs that all regular users get.
And someone else gets his own purchased IP + the shared one(s) also !

Therefore, a Check-Box option to Multiple-Select IP-Pools will be better than a drop-down.

Let's allow the Admin to decide whether he wants to give an exclusive IP to someone or allot multiple to someone else.

**Comment by AndersonOuverney** [comment]
Hello guys, good afternoon.

We are working with postal and we are having great results. We were able to integrate via api with control panels like cpanel and directadmin.

We are working on product improvements, right now this is exactly what we are seeing, improving the way we deliver messages and speeds.

We are creating custom rules for each new server, in these rules we are looking to add more than one pool of ips, so we will be able to create large rotations and maximize possible combinations.

Example

Pool A - / 27
Pool B - / 27
Pool C - / 24
Pool D - / 24
Pool E - / 24

The abc client has 1 or more servers, on each server he can create rules and add as many origin domains as he wants, after that he selects which Pools he would like to send the emails to.

We are currently working on it and soon if all goes well I will bring the results.

**Comment by therealelyayo** [comment]
whats the update on this please

**Comment by Riyad264** [comment]
You just can try this article simply: [How to set up IP Pool for the Postal SMTP server? (Latest Updated Guide)](https://inboxhujur.com/how-to-set-up-ip-pool-for-the-postal-smtp-server-latest-updated-guide/)
