### ISSUE TITLE
Tracking Domains break email body if used with SMTP.

### ISSUE THREAD

**Issue by uhlhosting** [postalhq/postal#1192]
Hi,

We use a simple phpmailer script to send mails from our wordpress via Postal, some of our emails arrive like this;
```
Additional Headers

MIME-Version: 1.0
Content-type: text/html; charset=UTF-8
```

https://gist.github.com/uhlhosting/343e16da0ca6ae8abf89a3e8cb6b2273
I attached here the .eml broken one sent via postal

and here the normal one not sent via postal
https://gist.github.com/uhlhosting/4461e455e864e712c545d3468624f4ca

<img width="955" alt="image" src="https://user-images.githubusercontent.com/6324047/91584534-101b3f80-e953-11ea-9582-8aaf607974bf.png">

And are sent like:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/6324047/91584564-1b6e6b00-e953-11ea-8ce3-aa80990ac4c0.png">

anyone has any ideas what could cause this?

**Comment by willpower232** [comment]
It sounds like there is some problem with character encoding which has been hinted at in some other issues. Do you have click tracking set up for these emails? Are you able to share the script you're using to send the messages?

**Comment by uhlhosting** [comment]
@willpower232 I have indeed click tracking enabled, i just use a phpmailer custom function in wordpress.

**Comment by willpower232** [comment]
We have experienced that sending email with SMTP into a click tracking server will cause problems outputting the email contents, can you confirm that disabling click tracking clears the problem?

**Comment by uhlhosting** [comment]
Yes disabling click solves it, just that is one case only, anything else works.

**Comment by dragoangel** [comment]
I has same issue here. I get mail base64 encoded without decoding it back. This big issue which mean that tracking can't be used at all at current state?

**Comment by dragoangel** [comment]
As I can see this related to `crlf` EOL symbol issue, it converted to `=0Dlf`.

**Comment by dragoangel** [comment]
No update on issue? This blocks usage of track links 😢
