### ISSUE TITLE
 smtp only has 2 instances (should have 1)  * smtp.2 is not running (Failed) postal

### ISSUE THREAD

**Issue by samg8520** [postalhq/postal#1193]
I have recently installed postal mail server on my VPS. After that when I am trying to connect to my sever using smtp credentials i am not able to do so. I am getting error. After doing 'postal restart' I got the result given below. I checked my  netstat -lnp and the result is also given below. please help me fix the issue. need help @willpower232

root@postal:~# postal restart
Stopped smtp.2
Restarted web.1
Restarted worker.4 -> worker.5
Restarted cron.4 -> cron.5
Restarted smtp.3
Restarted requeuer.4 -> requeuer.5

root@postal:~#  netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      381/nginx: master p
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      441/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      360/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1024/exim4
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      381/nginx: master p
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      1282/[postal] web.1
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      296/beam.smp
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      575/mysqld
tcp6       0      0 :::80                   :::*                    LISTEN      381/nginx: master p
tcp6       0      0 :::4369                 :::*                    LISTEN      441/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      360/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1024/exim4
tcp6       0      0 :::443                  :::*                    LISTEN      381/nginx: master p
tcp6       0      0 :::5672                 :::*                    LISTEN      296/beam.smp
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     692941580 1/init               /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     692944182 276/saslauthd        /var/run/saslauthd/mux
unix  2      [ ACC ]     STREAM     LISTENING     693546224 1276/[procodile] Po  /tmp/postal/pids/procodile.sock
unix  2      [ ACC ]     SEQPACKET  LISTENING     692947316 1/init               /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     692929142 1/init               /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     692949172 1/init               /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     692892378 575/mysqld           /var/run/mysqld/mysqld.sock

**Comment by yomiit** [comment]
You are running another mail server software "Exim" using same SMTP port as Postal. 

You need to stop the Exim service and probably disable it, then issue a "postal restart".

**Comment by samg8520** [comment]
Thank you for your reply @yomiit

**Comment by samg8520** [comment]
@yomiit  when i did #service exim stop it gives me the result below

root@postal:~# service exim stop
Failed to stop exim.service: Unit exim.service not loaded.

**Comment by samg8520** [comment]
I have installed postal using "curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh
" this command. I am running ununtu 18.04. I have setup firewall using ufw. ufw status is given below

root@postal:~# ufw status
Status: active

To                         Action      From
--                         ------      ----
25/tcp                     ALLOW       Anywhere
465/tcp                    ALLOW       Anywhere
587/tcp                    ALLOW       Anywhere
22/tcp                     ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
25/tcp (v6)                ALLOW       Anywhere (v6)
465/tcp (v6)               ALLOW       Anywhere (v6)
587/tcp (v6)               ALLOW       Anywhere (v6)
22/tcp (v6)                ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)

**Comment by yomiit** [comment]
The service should be exim4.

`systemctl stop exim4`
`systemctl disable exim4`

**Comment by samg8520** [comment]
hello. thanks for the help. Now postal is listening to port 25, and only listening to port 25. I can not connect to postal using 465 & 587, need help with that. plz @willpower232 @yomiit

**Comment by willpower232** [comment]
Connecting on other ports shouldn't be required but if you want it, you will have to use something like iptables to forward ports internally.

**Comment by samg8520** [comment]
> Connecting on other ports shouldn't be required but if you want it, you will have to use something like iptables to forward ports internally.

@willpower232  plz help me to do it, as this is my first time doing this.
