### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by uhlhosting** [postalhq/postal#1194]
I have this issue it seems I am able to send mails from any domain to infox@uhlhosting.ch yet not from xxxxx@uhlhost.net domain. I will receive:

```
This is the mail system at host mail.uhlhost.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<info@uhlhosting.ch>: host post.uhlhosting.ch[] said: 530
   Authentication required (in reply to RCPT TO command)
Reporting-MTA: dns; mail.uhlhost.net
X-Postfix-Queue-ID: 9EA89A55F1
X-Postfix-Sender: rfc822; cosminx@uhlhost.net
Arrival-Date: Sat, 29 Aug 2020 07:54:38 +0200 (CEST)

Final-Recipient: rfc822; infox@uhlhosting.ch
Original-Recipient: rfc822;infox@uhlhosting.ch
Action: failed
Status: 5.0.0
Remote-MTA: dns; post.uhlhosting.ch
Diagnostic-Code: smtp; 530 Authentication required
```

I sent from Office 365 and other domains not via mail.uhlhost.net and they worked fine. Any idea? This is surely maybe some missconfiguration somewhere yet i cannot seem to find it.

Domain @uhlhosting.ch has 2 MX servers one with 0 priority and one with 10. The 0 priority mailbox should be the first one to get the mail, yet @uhlhost.net sends it to the 10 priority @postal. And postal rejects it.

**Comment by willpower232** [comment]
I'm confused about your setup,  the error message makes it sound like there is some relaying involved?

**Comment by uhlhosting** [comment]
cosmin@uhlhost.net hosted in ZImbra.
info@uhlhosting.ch hosted in cpanel and domain is in postal

Only uhlhosting.ch is added in postal. while @uhlhost.net is self hosted in zimbra and has nothing to do with postal.

**Comment by willpower232** [comment]
The only reason you would get this message would be if you haven't set up an incoming route. I note that the error message mentions `infox@` and you're talking about `info@` so is it just a typo?

**Comment by uhlhosting** [comment]
Is not a typo i made it so against spambots, correct its info@ . It seems not one single mail from @uhl.site also @uhlhosting.ch cant be sent to @uhlhost.net and same with anything hosted in cpanel and in aapanel.

I other words @uhlhost.net rejects any mails routed via Postal. no matter if @uhlhosting.ch or @uhl.site

**Comment by willpower232** [comment]
Do you have other error message examples that don't say `infox@`?

**Comment by uhlhosting** [comment]
```
<info@ecunative.eu>: host post.uhlhosting.ch[92.222.242.243] said: 530
   Authentication required (in reply to RCPT TO command)
Reporting-MTA: dns; mail.uhlhost.net
X-Postfix-Queue-ID: D0E30A562E
X-Postfix-Sender: rfc822; cosmin@uhlhost.net
Arrival-Date: Fri,  4 Sep 2020 11:46:34 +0200 (CEST)

Final-Recipient: rfc822; info@ecunative.eu
Original-Recipient: rfc822;info@ecunative.eu
Action: failed
Status: 5.0.0
Remote-MTA: dns; post.uhlhosting.ch
Diagnostic-Code: smtp; 530 Authentication required

From: Viorel-Cosmin Miron <cosmin@uhlhost.net>
Subject: Fwd: Undelivered Mail Returned to Sender
Date: 4 September 2020 at 11:49:15 CEST
To: info@ecunative.eu
```

**Comment by willpower232** [comment]
So have you set up incoming routes for all these addresses?

**Comment by uhlhosting** [comment]
@willpower232 yes.

**Comment by willpower232** [comment]
You can see in the code https://github.com/postalhq/postal/blob/9a3d568b27f101610147d04f97d5940875e98258/lib/postal/smtp_server/client.rb#L325

The ways to get this in your setup are either you don't have routes set up or you aren't talking to Postal.

**Comment by uhlhosting** [comment]
@willpower232 Postal passes all validations, still could not track yet what is causing this.
