### ISSUE TITLE
How to setup Click and Open Tracking step by step ?

### ISSUE THREAD

**Issue by Rahul-Singla** [postalhq/postal#1196]
Hi,

I did setup of PostalHQ on Digital Ocean Droplet. Everything is going fine other than tracking of emails. 
I only has Single IP for my droplet so How I can enable fast server for tracking. It would be great if you also elaborate little about any nginx changes. 

Thanks

**Comment by willpower232** [comment]
If you do not have a second IP address then you would have to reconfigure nginx to use different ports.

I believe DigitalOcean can provide a floating IP address which effectively gives you a second address?

**Comment by Rahul-Singla** [comment]
How I can do nginx reconfiguration. Any step by step guide to help me out ?

Oh, I don't know about that, I will check for it as well.

**Comment by Rahul-Singla** [comment]
Hi,

I enabled IPv6 on Droplet, So I got 16 additional IPv6 range. In postal.yml, I entered IPv6 and enabled fast_server but fast_server is not showing up in postal status command. If I missed anything ?

**Comment by willpower232** [comment]
You will have to have a look at the log files to see what has gone wrong or run the command yourself to see what happens.
