### ISSUE TITLE
How to open port 587 on postal to connect with mailing application?  

### ISSUE THREAD

**Issue by mishudm** [postalhq/postal#1197]
Hello. In posta i have port 25 open.  But i need to open port 465 or 587. The reason is i need to connect smtp with sendbluster or ultramailer. Those application use local network port and local network close port 25.  Thats why i cant connect postal smtp with those applicatio.  
Do anyone know how can i fo that with full process?

**Comment by willpower232** [comment]
Connecting on other ports shouldn't be required but if you want it, you will have to use something like iptables to forward ports internally.

**Comment by mishudm** [comment]
> Connecting on other ports shouldn't be required but if you want it, you will have to use something like iptables to forward ports internally.

if i forward port 25 to 587 then will port 25 be stop? i want both port 25 and 587 open and also if i do that dont i need to configure anything in postal?

**Comment by willpower232** [comment]
Postal can only bind to one port. Using iptables to forward the other ports to 25 means that effectively they're all open. As its part of the network configuration of the server, you don't have to configure anything in Postal.

**Comment by mishudm** [comment]
> Postal can only bind to one port. Using iptables to forward the other ports to 25 means that effectively they're all open. As its part of the network configuration of the server, you don't have to configure anything in Postal.

i forwared it by 
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 25 -j REDIRECT --to-port 2525
sudo /sbin/iptables-save
but still port 587 not connecting with send bluster

**Comment by willpower232** [comment]
If you ran that command, you'll see it ends with 2525 which is port 2525. If you want a different port, specify a different one.

**Comment by mishudm** [comment]
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 25 -j REDIRECT --to-port 587
sudo /sbin/iptables-save
result is same. if you can hep i can give you my server info so you can check

**Comment by mishudm** [comment]
> If you ran that command, you'll see it ends with 2525 which is port 2525. If you want a different port, specify a different one.

iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 25 -j REDIRECT --to-port 587
sudo /sbin/iptables-save
result is same. if you can hep i can give you my server info so you can check

**Comment by navinp** [comment]
Hello,

What's the response you get when doing:

telnet domain 587

**Comment by navinp** [comment]
Also did you restart the server afterwards?

**postal restart**

**Comment by mishudm** [comment]
> Also did you restart the server afterwards?
> 
> **postal restart**

yes i did. also i did too many things now and reinstall postal for need experiment for this.
but i dont thing i will get solution here. because no one replying and you are repling but not giving full things and replying in every 10 to 12 hour. i cant sit idle. so if you really want to help please give me like full coomand one by one or give your mail address. thanks

**Comment by yomiit** [comment]
See [here](https://github.com/postalhq/postal/issues/565)
