### ISSUE TITLE
when I am relaying emails from email sending app I am getting error : too many emails per connections. :postal

### ISSUE THREAD

**Issue by samg8520** [postalhq/postal#1200]
I have setup postal and everything is working fine. I am able to send send emails using postal interface but when I tried to send email using smtp relay on port 25 I got error: too many emails per connections. previously I consulted with my vps provider they said they allow sending 5 emails per minute, so I setup app to send emails in 20sec interval. so I should be good  but still facing problem on relaying the emails from app. I am using super email sender v3.1 and sendblaster. need help @yomiit @willpower232

**Comment by willpower232** [comment]
Can't really offer any advice apart from increasing the interval to a minute to see if it actually helps or if there is another problem.

**Comment by samg8520** [comment]
thanks for the reply @willpower232 , I am doing it now. But it would be very slow. Anything else can i do to improve rate of sending?

**Comment by samg8520** [comment]
hello @willpower232 I set the interval to 60sec and timeout to 120sec but after sending about 9 emails i got error: too many emails per connection. Need your urgent help. plz

**Comment by willpower232** [comment]
If your provider is limiting you, there is nothing really Postal can do about it. This limitation isn't very common and slowing down Postal as a whole would only increase your issues. If you aren't able to find another provider, you may have to find a different way of sending emails.
