### ISSUE TITLE
503 EHLO/HELO first please

### ISSUE THREAD

**Issue by vishnus** [postalhq/postal#1201]
Hi team,

We recently came across this error `503 EHLO/HELO first please` on long-standing SMTP connections and it gets disconnected. Could you shed some light on what this issue is and what could cause this? It happens once in maybe 3-4 hours when we send a massive campaign (2-3 million emails) after sending around 100-200k emails this error pops up and all connections gets disconnected.

**Comment by willpower232** [comment]
Do you mean you sending emails to Postal for it to send or are these errors coming up in Postals UI as it tries to send the messages on?

**Comment by vishnus** [comment]
We send to Postal for it to send via SMTP. No errors are coming in the UI.

We have a mailing list manager (https://listmonk.app ) that connects to Postal instance to send out emails. This app pauses the mailing when there are many SMTP errors. What has been happening is, after a couple of hours of sending emails, Postal terminates the SMTP connection with the error `503 EHLO/HELO first please`. I could find this error in Postal's logs also. The queue is empty, all CPU, memory metrics are all fine. But we couldn't figure out why this error is happening.

**Comment by willpower232** [comment]
You can see that Postal only emits this error once in its code https://github.com/postalhq/postal/blob/9a3d568b27f101610147d04f97d5940875e98258/lib/postal/smtp_server/client.rb#L232

It implies that the re use of the connection has somehow skipped a step or perhaps listmonk errored out halfway through a message and didn't reset Postal properly (or Postal failed to reset properly despite being told to).

Is it possible to reproduce the problem with smaller batches of emails or does it only occur after a number of hours?

**Comment by vishnus** [comment]
@willpower232 ah that makes sense.. will have to check if there's any race condition. we saw it happening once every couple of hours. No certain pattern. Let me investigate further and update here..
