### ISSUE TITLE
Change db difficulty

### ISSUE THREAD

**Issue by diegolr62** [postalhq/postal#1206]
Hello

We are thinking on change the db for Postal, and we don't have any exposition to Ruby. I just need to know how a change of db drivers  (from mysql to oracle), would take in terms of time, complexity and system stability 

Best regards

**Comment by willpower232** [comment]
Its a great question, there are a number of hardcoded SQL queries, particularly around the `MessageDB` so depending on how different Oracle is in terms of SQL language, it may not be a quick change.

**Comment by diegolr62** [comment]
Thanks Will

Regards,
