### ISSUE TITLE
Fast server not starting.

### ISSUE THREAD

**Issue by alkanna** [postalhq/postal#1207]
Hello, when postal starts up on its own, fast server is retried 5 times in under a minutes, then fails.
If I start it manually, it runs fine, and there is no output.
Is there something in particular I should be looking for here?
Nothing relevant in the logs either.

Thanks.

**Comment by willpower232** [comment]
When you start it manually, are you running as the postal user? It may be a permissions problem.

**Comment by alkanna** [comment]
I don't know what went wrong there. I just reinstalled everything.
