### ISSUE TITLE
TrackDomain dot issue

### ISSUE THREAD

**Issue by dragoangel** [postalhq/postal#1208]
Tracking links need exclude `.` if this is last chapter in http/https link. F.e. email body:
```
Hi! Some plug-ins have been automatically updated to their latest version on your site http://click.example.com/xx/yy No action is required on your part.
```
Link `http://click.example.com/xx/yy` actually redirect to `https://mydomain.com.` and due Track link picked up `.` as part of link - link can't be opened in browser, for most people this stopper actually.
In 99.99% cases I think this will mean end of sentence and doesn't part of link. If you want to be sure you can add check that will validate need of exclude `.` or not:
1. `.` is last symbol in line.
2. after `.` is space and next word start from uppercase.

**Comment by willpower232** [comment]
Good spot, can you try #296 to see if that covers it? It has been a while since I looked at it.

**Comment by dragoangel** [comment]
Hi @willpower232 thank you, I will check

**Comment by dragoangel** [comment]
Hi @willpower232 I checked how https://github.com/postalhq/postal/blob/95a3c71800980f1499da244e7edb921e43192fab/lib/postal/message_parser.rb#L100 works, and looks like it already must process links correctly, but it doesn't, I doesn't know why.
I used https://www.tutorialspoint.com/execute_ruby_online.php and:
```
url = "https://google.com/a.1/..1."
while url =~ /[^\w]$/ do
 theend = url.size - 2
 url = url[0..theend]
end
puts "#{url}"
```
which returns: `https://google.com/a.1/..1` as expected without `.` at end T_T.

**Comment by willpower232** [comment]
Unfortunately those who can merge do not have enough time at the moment.

Are you able to add the code yourself to see if it covers your problem?

**Comment by dragoangel** [comment]
I already applied changes from that pr, yes it fixed the problem

**Comment by willpower232** [comment]
Glad it resolved your problem. For the record, the project has maintainers however Postal is stable and suits the purpose it was intended for, so without serious issues, they do not have the time available for regular updates.
