### ISSUE TITLE
DKIM part of importand headers isn't signed

### ISSUE THREAD

**Issue by dragoangel** [postalhq/postal#1209]
As best practice mime-version & content-type headers need to be signed as well.

**Comment by willpower232** [comment]
see also #1110

**Comment by dragoangel** [comment]
Hi @willpower232 thank you.

**Comment by willpower232** [comment]
Unfortunately, those with the ability to decide what gets added don't have enough time at the moment.

Yes if you have made changes to Postal, they will be automatically overwritten so future upgrades need to be handled delicately.

**Comment by willpower232** [comment]
closing for #1218
