### ISSUE TITLE
TrackDomain isn't working

### ISSUE THREAD

**Issue by dragoangel** [postalhq/postal#1210]
If email send in:
```
MIME-Version: 1.0
Content-Type: text/html; charset=us-ascii
Content-Transfer-Encoding: quoted-printable
```
links will not be replaced by tracking domain and no hidden img will be added.

**Comment by willpower232** [comment]
Have you made sure that the domain name you are sending from matches one of your click tracking domains?

**Comment by dragoangel** [comment]
You mean that for any link domain to change them I need add dedicated track domain? Hm, doesn't know about this logic, will check, sorry & thanks in advance
