### ISSUE TITLE
Incoming

### ISSUE THREAD

**Issue by gh-hassan** [postalhq/postal#1212]
I just installed postal on my vps i have added my domain and added all four records (spf,dkim,mx, return path) I am using mautic for automation and I have connected it with the postal. Now the only problem I am facing is the incoming emails I don't know why I am not receiving any emails at my account do I have to add any endpoint route in the postal or what?

Note: my domain is at hostinger so I am using their webmail.

**Comment by willpower232** [comment]
Postal needs incoming routes to be added to handle incoming email otherwise it will be rejected.

**Comment by gh-hassan** [comment]
ok so how can I add a route should I just add a address endpoint as a route where I enter any of my email associate with the domain?

**Comment by willpower232** [comment]
![image](https://user-images.githubusercontent.com/1619102/94363947-bdea4d00-00bd-11eb-9822-632919e8a65f.png)

Incoming messages can be handled in several ways as you set up in the UI
