### ISSUE TITLE
routing issue

### ISSUE THREAD

**Issue by gh-hassan** [postalhq/postal#1213]
For incoming emails, I have tried to add the routing address which was the one that belongs to the domain that I used for the server I also added the SMTP endpoint as I am using hostinger for the webmail of the domains and hosting so I added the hostinger SMTP details but I thought that it would be easier If I simply add the email address for the routing but once I deleted the SMTP endpoint it just gives me error please see attached and guide. Thanks 
https://ibb.co/VYvRfnj

**Comment by willpower232** [comment]
That message means something should have been written to the log files to tell you what went wrong.
