### ISSUE TITLE
DKIM Signature Body Hash Did Not Verify

### ISSUE THREAD

**Issue by trancemanone** [postalhq/postal#1219]
Hello all,

I use Postal as my SMTP. I have all the DNS records installed correctly : SPF DKIM and DMARC and verified 10/10 on mail-tester.

When I test these records by sending a test directly from Postal to my gmail account and then test my email header with mxtoolbox or [appmaildev](https://www.appmaildev.com/site/testfile/dkim?lang=en)  I get a DKIM pass reply.

However, When I send a test email from Mautic to my gmail account and test the header with mxtoolbox or [appmaildev](https://www.appmaildev.com/site/testfile/dkim?lang=en) the DKIM authentication will fail!

The reason is: ".... Expected-Body-Hash: WIOFbA0nxr9LK59pSvSPyPaEz8meJEvP78rzNyVxlsA=
DKIM-Result: fail (wrong body hash: mILyW/egpTCSgQk90NKV5kWnYZOYwm92W2KqSz9SAP8=)"

At first I thought its mautic. but then I used SMTPER and the result was a failed DKIM authentication as well. 

Any Idea on how to solve this ? 

Thanks

**Comment by willpower232** [comment]
Have you seen #1175 ?

**Comment by trancemanone** [comment]
> Have you seen #1175 ?

I just did but I think it's irrelevant. 


Here is where I got so far by adding a DKIM setector to mautic subdomain: 

In my case DKIM is valid but in: 

maildev : its Valid and Authenticated 

Google tools app: its Valid and Authenticated

But in mxtoolsbox: 

Its valid and the body hash doesnt match.

**Comment by trancemanone** [comment]
The mxtoolsbox email header fails reading the authentication, however the https://mxtoolsbox.com/validator shows DKIM authentication. 

I hope its a bug in mxtools box!?

**Comment by willpower232** [comment]
My mistake, I got confused with #1192 

If its just one system reporting a problem and your recipients are able to receive then it must be a minor confusion but could be a wider issue.

**Comment by trancemanone** [comment]
I have turned off tracking on Mautic with no success. here is the result: 

https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx?huid=7c65fb70-1f86-4ef0-98a1-a849529567a0

**Comment by dragoangel** [comment]
This mxtool is buggy, do not trust it really
