### ISSUE TITLE
smtp_server stuck in DEBUG log 

### ISSUE THREAD

**Issue by joltcan** [postalhq/postal#1222]
Hi!

My smtp_server log is HUGE with DEBUG logging info, but I can't see that it is enabled anywhere. I have not configued the "logging" section in the config, and I don't have a smtp_server config.

Is there a way to change log level in the config?

Spam log example
```log
[smtp.1:55492] [2020-09-24T12:34:26.604] DEBUG -- : [KWXAAB] => 250 OK
[smtp.1:55492] [2020-09-24T12:34:26.690] DEBUG -- : [DVLARB]    Connection opened from ::ffff:212.70.149.52
[smtp.1:55492] [2020-09-24T12:34:26.691] DEBUG -- : [DVLARB]    Client identified as ::ffff:212.70.149.52
[smtp.1:55492] [2020-09-24T12:34:26.874] DEBUG -- : [NBOF1A] <= MTIzNDU2Nzg=
[smtp.1:55492] [2020-09-24T12:34:26.875] DEBUG -- : [NBOF1A] => 535 Invalid credential
```

**Comment by Igcorreia** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/1076409/94338943-2c5fda00-ffee-11ea-82b8-6bd10c47dc3d.png)

**Comment by willpower232** [comment]
That information is always logged IIRC, it can be used to identify problems with messages. In theory the logs should be rotated so the file size does not become a problem.

The settings identified above allow you to record the contents of message in the logs as well (which would cause a privacy and storage problem long term) and limit the information kept in the database to keep your storage usage under control.

**Comment by joltcan** [comment]
The are rotated just fine, but in other log examples from various tickets I see INFO log level etc, but mine are all DEBUG level, hence I assumed it was possible to change that somehow?
On 27/09/2020 14:48:42, Will Power <notifications@github.com> wrote:
That information is always logged IIRC, it can be used to identify problems with messages. In theory the logs should be rotated so the file size does not become a problem.
The settings identified above allow you to record the contents of message in the logs as well (which would cause a privacy and storage problem long term) and limit the information kept in the database to keep your storage usage under control.

**Comment by willpower232** [comment]
I do not believe it can be changed but I don't think there is any major reason to not add that in if someone has the time.

The references in these lines are referenced in the UI so it can be useful to get more information about a message when things go wrong.

**Comment by solracsf** [comment]
>  In theory the logs should be rotated so the file size does not become a problem.

In my case, logs are now >8GiB so it seems rotation is not working.
How can I check it?

**Comment by willpower232** [comment]
In 2025, you're hopefully using docker compose so log file management is different.

You are probably interested in https://github.com/orgs/postalserver/discussions/3234#discussioncomment-11289656

**Comment by solracsf** [comment]
Thanks 👍🏼
