### ISSUE TITLE
Is it possible to forward bounce reports to another email address?

### ISSUE THREAD

**Issue by Robmobius** [postalhq/postal#1227]
Is it possible to forward bounce reports to another email address?

I use Mautic to send emails via postal. Mautic can monitor an inbox for bounce and unsubscribe reports and then mark the contacts that have email addresses that bounce. 

I have not been able to figure out if it is possible to have postal fwd the bounced emails to a separate inbox.

Possible?
If so how?

**Comment by willpower232** [comment]
Unfortunately return path routing only supports HTTP endpoints, according to the wiki anyway, so I'm not sure if this is possible.

There are others here who have mentioned using Mautic so you could try searching the issues for it and see if there is any useful information.

**Comment by GemsFord** [comment]
Okay, by reading this page - https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces
I understood a lot of things.

If a mail is marked as hard fail in postal and mautic tries to send another email to that email address,
Will postal try again to send email to the same email address? If yes, can I prevent this?

**Comment by GemsFord** [comment]
How to change the limit of hard fail from 2 to 1, so that it directly added to the suppression list?

**Comment by willpower232** [comment]
You can control this setting specifying this value in your postal.yml https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/config/postal.defaults.yml#L14

But I don't think it is 2 by default unless you or someone has already set it

**Comment by GemsFord** [comment]
Are you sure this is hard fail setting and not soft fail setting? Trying 18 times for a hard fail is too much, isn't it?

**Comment by GemsFord** [comment]
![image](https://user-images.githubusercontent.com/35967121/96370120-6e59e700-117a-11eb-90fc-f67c3a623f1b.png)

How to customise Suppressions 30 days removal period?

**Comment by willpower232** [comment]
It might be you were getting to this point so there were related hardfails for the email address (i.e. more than 1) which would create that effect

https://github.com/postalhq/postal/blob/ccd6caf1472cac69af1988bdaadba28a66ef838a/app/jobs/unqueue_message_job.rb#L399

You can customise the 30 days here

https://github.com/postalhq/postal/blob/dcb2919cc6202cea579109e9de435e646fb1bd5f/config/postal.defaults.yml#L16

**Comment by GemsFord** [comment]
Thank you so much!
