### ISSUE TITLE
Increase Webhook Timeout/Await

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1228]
Hi, I need to increase the time that the webhook awaits before giving timeout. Can anyone point me in the right direction please?

Is it here: https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/app/models/webhook_request.rb#L57

![image](https://user-images.githubusercontent.com/1076409/95243990-49c04f80-0809-11eb-8fb3-ec2a087d3bdb.png)

**Comment by willpower232** [comment]
If you have found the line of code, you can change it yourself as you need but be warned that it may get reset if you update Postal.

5 seconds is already a long time to be waiting, does whatever receives the webhook need to be improved?

**Comment by Igcorreia** [comment]
@willpower232 agreed 100%. Yet at the near maximum, 14mg per email, 5s very rarely is not enough. Still working to improve the API. We manage to figure it out. we change this line:

https://github.com/postalhq/postal/blob/57cc0239bdf745c63cd18f366c4f3c36855cff2f/lib/postal/http.rb#L58

for this:

` timeout = 10 #options[:timeout] || 60 `
