### ISSUE TITLE
A Connection Attempt Failed

### ISSUE THREAD

**Issue by Software-Wolf** [postalhq/postal#1230]
Hello, I have been facing this issue for a while now. I am running postal on a digital ocean VPS server with the os ubuntu 16.04.6 x32 bit. I set it all up and made credentials. I used multiple online tools to test it, including https://www.gmass.co/smtp-test and https://www.smtper.net/ and they are both able to connect to the server and send emails fine. However, when I try to connect with a downloadable tool using my own pc, it does not connect. To make sure it is not just the tool I am using, I tried multiple, Super Email Sender, SMTPConsole, Atomic Mail Sender, & more. They all can not connect. But any online tool can. I also tried it with 2 other computers just to make sure it wasn't my computer and they both did not work. Is my IP blocked or something? I am not sure what is causing this, but it is hurting my head.

**Comment by Software-Wolf** [comment]
Has anyone else faced this issue?

**Comment by willpower232** [comment]
I believe other issues mention that new DigitalOcean accounts need to have the SMTP port opened, you could also try using the telnet command from your computer to verify where the problem is.

Can you see what the error message from your programs is?

**Comment by Software-Wolf** [comment]
I just don't understand why any online tool works, but I can't connect to it from my personal computer. The port is indeed opened because I checked it with an online tool, but when I try to check it from my IP it does not show up as open, my internet connection is having a problem reaching it for some reason, but any tool online can send emails fine.
**Error From Program:**
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 67.205.***.***:25

**Comment by Software-Wolf** [comment]
Also, I tried using a Google VPS, and it also could not connect, so it is not just me. But then why can online tools like https://www.gmass.co/smtp-test and others connect to it, and send emails perfectly. It just makes 0 sense.

**Comment by willpower232** [comment]
We know from other issues that Google VPS blocks SMTP so it might be that your ISP blocks the connection.

Are you able to try telnet from your computer?

**Comment by Nem1n** [comment]
Hi,
I got the same issue, when I try with Mautic and my Postal credential it doesn't work, but with smtper it works.
My VPS for postal is on OVH and Mautic is on my Desktop.
I tried with another domain and ovh smtp and Mautic it works event if the mails are going to the spam.
But with my postal credential I can't connect to my postal smtp

**Comment by blueseanj** [comment]
Hi guys, I have the same issue. Does anybody found a solution to this please ???
 Im using Contabo VPS, emails gets through from smtper.net just fine, but I cannot connect to Mautic or other mail apps using my Smtp credentials.
