### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by Robmobius** [postalhq/postal#1231]
A bit embarrassed to post this, but I have forgotten my password. Nowhere can I find a password recovery process. Searching the issues I see mention of a recovery process but I cannot find any thing in the UI

Help?

**Comment by willpower232** [comment]
There is a `Forgotten your password?` link on the login form.

**Comment by Robmobius** [comment]
@willpower232  thanks. Found the password recovery feature. But when I try use it I get the msg "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

I have no idea where to find the logs to check what the issue is. Hoping you can assist

**Comment by willpower232** [comment]
You'll have to look at the logs but the most likely cause of this problem is not configuring the `smtp` details in `postal.yml` so it can't send emails https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/config/postal.defaults.yml#L104-L110

**Comment by ImonAwesome** [comment]
**Sorry opening this thread again,**

If you forgot your password and reset password showing **"We're sorry, but something went wrong. If you are the application owner check the logs for more information."**

Then follow the below steps.

1. Login to Server
2. RUN `postal stop`
    _(WORNING IT WILL SHUT DOWN YOUR POSTAL SMTP)_

3. RUN `postal make-user`
4. Enter New Admin Information | Make sure your not using same email that have first/other admin email
5. Once finish entering all the information RUN `postal start`
6. Login to your website using newly create admin


Thanks!

**Comment by willpower232** [comment]
Just an FYI, you should not need to stop Postal in order to run `make-user` again, there should be no issue in keeping Postal running.

If you aren't able to reset your password, I direct your attention to my previously final message on the matter above https://github.com/postalserver/postal/issues/1231#issuecomment-720376655
