### ISSUE TITLE
Postal Test message is giving Soft Fail error

### ISSUE THREAD

**Issue by rajreddy251** [postalhq/postal#1233]
I have configured postal on Ubuntu v18 on aws ec2 instance with elastic ip. 

When I send the test message to my personal gmail, it is showing as a soft fail with below error.

`No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com`

```
execution expired
Support Ref: IH0JSLYP
```
postal status output is below,

`ubuntu@ip-172-31-9-182:~$ postal status
Procodile Version   1.0.26
Application Root    /opt/postal/app
Supervisor PID      1805
Started             2020-10-13 02:42:36 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      02:42        pid:1811     respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      02:42        pid:1813     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      02:42        pid:1815     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      02:42        pid:1817     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      02:42        pid:1820     respawns:0      port:-        tag:`

postal logs
from smtp_sender.log

```
^[[34m[worker.1:1789]^[[0m [2020-10-13T00:59:11.650] INFO -- : [ITONTICC] Cannot connect to 209.85.200.26:25 (alt4.gmail-smtp-in.l.google.com) (Net::OpenTimeout: execution expired)
^[[34m[worker.1:1789]^[[0m [2020-10-13T00:59:11.650] INFO -- : [ITONTICC] -> No SMTP server available for gmail.com
^[[34m[worker.1:1789]^[[0m [2020-10-13T00:59:11.650] INFO -- : [ITONTICC] -> Hostnames: ["gmail-smtp-in.l.google.com", "alt1.gmail-smtp-in.l.google.com", "alt2.gmail-smtp-in.l.google.com", "alt3.gmail-smtp-in.l.google.com", "alt4.gmail-smtp-in.l.google.com"]
^[[34m[worker.1:1789]^[[0m [2020-10-13T00:59:11.650] INFO -- : [ITONTICC] -> Errors: ["execution expired"]
^[[34m[worker.1:1789]^[[0m [2020-10-13T00:59:11.665] INFO -- : [ITONTICC] Finishing up
```

Also, I have setup the SSL for the subdomain using let'sencrypt. 
Configured spf & DKIM and verified the records in postal UI.

**Comment by willpower232** [comment]
You will likely need to request permission from AWS to send emails which is likely blocking your connection to other SMTP servers.

**Comment by rajreddy251** [comment]
Any other best hosting provider for SMTP servers? 
Because with amazon, I have earlier tried to take SES service and a dedicated ipaddress. They have rejected my request and no feedback, sighting the security concerns. 

Note: We don't want to spam any mail boxes because that will hurt our domain reputation itself.

**Comment by willpower232** [comment]
If you are aiming to send marketing messages you may be out of luck with the major providers as, according to several issues here, they all seem to require manual permission for sending large amounts of emails.

We have been using AWS for purely transactional reasons for several years with no problems.

**Comment by rajreddy251** [comment]
Got it. Thank you for the clarification.

**Comment by dsaydon90** [comment]
This issue saved my life, apparently AWS is blocking / restrict / limit the ability to send mails from AWS EC2 instances by default "to maintain the quality of Amazon EC2 addresses for sending email"

So in order to send mail from an AWS EC2 you will have to contact AWS support by [filling out this form](https://portal.aws.amazon.com/gp/aws/html-forms-controller/contactus/ec2-email-limit-rdns-request).

After the "removal of the EC2 email sending limitations", I was able to send mails.

more here: https://aws.amazon.com/ec2/faqs/?icmpid=docs_support_createcase_category_amazon-elastic-compute-cloud-linux_email-services#Are_there_any_limitations_in_sending_email_from_EC2_instances
