### ISSUE TITLE
New to postal and Usage help needed

### ISSUE THREAD

**Issue by Bobby0341** [postalhq/postal#1234]
Hi Team, I installed on digital ocean and configured postal for my domain. I am able to send emails from postal login but If I wanted to connect to a email client to have a nice UI for sending and receiving emails, how can i do it. I have a small company where we send weekly news letters for our existing customers. How can I have a email client like gmail, yahoo to create emails to our employees, send and receive emails via a nice UI. Please help.

**Comment by willpower232** [comment]
Honestly it sounds like you would get more use out of something like mailchimp rather than Postal.

Postal was not intended for use with traditional email clients and receiving emails requires you to have some software application to process it after receiving a specifically made request.

**Comment by Bobby0341** [comment]
Hi Willpower, We have 23,000 subscribers and mail chimp is very expensive for 23000 contacts to send weekly emails. So, I thought postal will come to my savings rescue. Please help me in showing some direction on how to take it further. 

Thanks,
Bobby

**Comment by lhitmedia** [comment]
Hi Bobby,

You could look at something like phplist and use postal as the sending email server.

https://github.com/phpList/phplist3

Regards,

James.

**Comment by willpower232** [comment]
as above, Postal is only half of your solution, phplist or similar would handle everything else for you.

**Comment by Bobby0341** [comment]
Hi Willpower,

Got it. I went with another method and got it done. Thank You for the
support.
