### ISSUE TITLE
Issues connecting Postal & Mautic

### ISSUE THREAD

**Issue by rivera664** [postalhq/postal#1235]
Hi everyone,

I am looking to connect Postal with Mautic but can't seem to find a way to do so anywhere.

Can anyone assist?

So far i get as far as going to the configuration on Mautic but it asks me for things i cannot find on the Postal Web App

Like: USERNAME FOR THE SELECTED MAIL SERVICE
And: PASSWORD FOR THE SELECTED MAIL SERVICE

HOST:
PORT:

Please help.

**Comment by lhitmedia** [comment]
Hi there,
In postal you should be able to find it in the help page of the mail server.
Org -> Mail Server -> Help 


Should list the following:

Hostname
Port: 25 or 2525
Username: <orgname>/<servername>
Password: <password>

Regards,

James.

**Comment by willpower232** [comment]
You will need to create an SMTP credential first but yes, that page should give you the details.
