### ISSUE TITLE
Maria DB binlog accumulation & low delivery throughput after pruning

### ISSUE THREAD

**Issue by Joe-Ng-1998** [postalhq/postal#1236]
1. Maria DB binlog accumulated and eventually filled up the disk.
2. As a result, Postal delivery stopped, a few thousands emails stuck at the pending state
3. Pruned Maria DB binlog from MySQL command line to free up disk space
4. Delivery speed slows to less than 1 emails per minute after rebooting the host

Looking at the worker log, I see a lot of this
```

[worker.1:3187] [2020-10-16T15:02:45.782] INFO -- : [ZBUC78RBLJ] [53::599188 3810086] Message requeued for trying later.
[worker.1:3187] [2020-10-16T15:02:45.784] INFO -- : [ZBUC78RBLJ] [53::599201 3810099] Got queued message with exclusive lock

[worker.1:3187] [2020-10-16T15:02:44.733] INFO -- : [JOVMORAZQD] [53::574657 3785526] Processing complete
[worker.1:3187] [2020-10-16T15:02:44.734] INFO -- : [JOVMORAZQD] [53::574667 3785536] Got queued message with exclusive lock

exclusive lock
[worker.1:3187] [2020-10-16T15:02:48.203] INFO -- : [JOVMORAZQD] [53::574671 3785540] Processing complete
[worker.1:3187] [2020-10-16T15:02:48.205] INFO -- : [JOVMORAZQD] [53::574701 3785570] Got queued message with exclusive lock

[worker.1:3187] [2020-10-16T15:02:53.608] INFO -- : [JOVMORAZQD] [53::574740 3785609] Processing complete
[worker.1:3187] [2020-10-16T15:02:53.610] INFO -- : [JOVMORAZQD] [53::574773 3785642] Got queued message with exclusive lock

[worker.1:3187] [2020-10-16T15:02:55.904] INFO -- : [ZBUC78RBLJ] [53::599818 3810716] Message requeued for trying later.
[worker.1:3187] [2020-10-16T15:02:55.906] INFO -- : [ZBUC78RBLJ] [53::599825 3810723] Got queued message with exclusive lock

```

SMTP sender log is reporting
```
550 Domain frequency limited
```

Normally when this happens, the message in the queue is requeued to be attempted at a later time. But an exclusive lock prevents the requeuing from happening, and so the same set of rabbitmq jobs gets picked up workers and loops infinitely.

So, how to remove the exclusive lock?

**Comment by willpower232** [comment]
You can see that log entry is part of normal sending flow here https://github.com/postalhq/postal/blob/ccd6caf1472cac69af1988bdaadba28a66ef838a/app/jobs/unqueue_message_job.rb#L33

The log entries after that point would give you an indication of what happened.

Other issues have reported that sometimes it is necessary to manually clear the lock columns in the database table if a message refuses to be sent but that does not seem to be the case here. Do you have the hard fail limit set very high or something?

If you are seeing that message from other email services, it might be worth consulting their documentation to see why you receive that message, I do not think that Postal gives that error message.

**Comment by CalZzz** [comment]
I see.

After cleaning the 100K queued_messages table in the main database, everything returned to normal.

Thanks @willpower232

**Comment by willpower232** [comment]
glad to hear it, feel free to close the issue if you have no more queries
