### ISSUE TITLE
Cannot send files in Excel format

### ISSUE THREAD

**Issue by aynurveysel** [postalhq/postal#1237]
Hello team, I cannot send files in Excel format with HTTP Payloads, only txt format files can be sent.
Please help me.
Thanks for your help in advance.
(https://user-images.githubusercontent.com/63716916/96272998-81808180-0fd7-11eb-8f65-490c6e1a169d.png)

**Comment by willpower232** [comment]
Can you see what the error log says for why there was a problem?

**Comment by aynurveysel** [comment]
I get 500 error, if I send the request to "data" in "attachments" in double quotes, ie as a string, I send it as a string, but since I want to send it in excel format, I have to send a part of the data as an array. However, I also share the log:
[web.1:1710] [2020-10-20T15:40:55.585] INFO -- : Started POST "/api/v1/send/message" for 88.247.145.134 at 2020-10-20 15:40:55 +0300
[web.1:1710] [2020-10-20T15:40:55.642] INFO -- : NoMethodError

**Comment by willpower232** [comment]
Is there more of the logs you can share? also I think you need to base64 encode the attachment but it doesn't appear to be readily documented.

**Comment by aynurveysel** [comment]
When I encode it as Base64 and send it, I cannot open excel from the incoming mail. I added it in the screenshot.
(https://user-images.githubusercontent.com/63716916/96709924-05ee4e00-13a4-11eb-82f1-66f17c00fab6.png)

**Comment by aynurveysel** [comment]
It was necessary to send the data in javada attachments with the Base64.encodeBase64String (data) function, not the Base64.encodeBase64 (data) function. The problem was solved when I sent it with Base64.encodeBase64String function. Thank you for your interest.
