### ISSUE TITLE
Slow mail delivery

### ISSUE THREAD

**Issue by jduncanator** [postalhq/postal#1239]
We've been using Postal successfully for the past three years now, and have had very little to no trouble at all with it. Recently, however, we've started onboarding a number of higher volume clients that need large amounts of mail delivered promptly.

Up until now, we've been fine with the 100 messages per minute sent figure, and never really bothered to look much further into it, but now that we have queues of emails to be sent out up in the 30K-40K figures, this takes an extremely long amount of time to process.

I've browsed through a number of the previous issues opened here, and have increased the worker count to 10 to see if we were able to extract extra performance, but to no avail. 

The servers utilisation is not an issue, whilst working through a 20,000 message queue with 10 workers, the CPU and memory usage practically sit idle (Postal/Ruby using around 2% CPU, and less then 30% memory).

I've seen others who have been able to send hundreds of messages _per second_ using Postal, so wondering if we're missing something critical here to our success.

Any insight would be appreciated, thanks.

We're running from latest HEAD: https://github.com/postalhq/postal/commit/2595481
```
ruby 2.5.5p157 (2019-03-15 revision 67260)
Procodile Version 1.0.26
```

**Comment by willpower232** [comment]
It may be that 10 workers isn't sufficient for email volume of that size, have a read of #290 and #235 for ideas on what adjustments can be made.

Unfortunately there isn't a one size fits all solution here so you will likely find yourself adjusting both Postal settings and also database settings to get the best throughput.

**Comment by jduncanator** [comment]
Thanks for the reply. We're seeing throughput of 100 emails per minute with 10 workers, which seems incredibly low. That's just less than 2 emails per second. 

I've read through most of the issues on here about poor performance, most of them just suggesting to up the worker count.

Surely there has to be something else wrong here? I'm running 10 workers, CPU usage is basically 0%, and I'm getting several orders of magnitude lower performance than other users who report being able to send 100's of emails _per second_ with just a single worker.

If there's nothing you can suggest, other than just increasing worker count, I suppose I'll have to diagnose the issue on our end. I refuse to believe that it can be so inefficient that with 10 workers, each worker can only deliver an email every 5 second, that seems incredibly slow.

**Comment by willpower232** [comment]
> being able to send 100's of emails per second with just a single worker

Where was this sorry?

If you have rabbit, mysql, and Postal all on the same server, I don't think there would be much optimisation apart from maybe some mysql settings for higher volumes. If you have CPU to spare, increasing the workers is the easiest approach to improving performance.

**Comment by jduncanator** [comment]
> Where was this sorry?

The OP here suggests they're able to hit 100 messages per second: https://github.com/postalhq/postal/issues/290

We can try increase the worker count further, but increasing from 2 workers to 10 workers made no noticeable difference for us, suggesting there is something else wrong that just scaling workers won't fix.

**Comment by willpower232** [comment]
Ah right I see. You should check `postal status` to make sure that all runners are working, surely adding more for a large queue of emails should make some difference.

**Comment by rbustos** [comment]
We use 2 postals + 1 rabbit + cluster mysql servers (all of them in separate servers) in hw 15K/SSD raid 10 disks and 10Gb ethernet.

From our history no matter how many workers do you change, it looks like there no gain increasing workers at all, evenmore it imply high costs on mysql memory due to the mysql concurrent connections. So maybe is the logic behind the code or some library (gems) that should be replaced.
