### ISSUE TITLE
Detection trojan virus from mail tracking (click.domain.com)

### ISSUE THREAD

**Issue by PlanetCreator** [postalhq/postal#1240]
During this week, I got some complaints from my clients that Showing hundreds of detected, infected emails as follows: by using Open / Click Tracking.

OVH send me abuse messages as follow,
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 Below is the list of URLs pointing to the phishing webpage you're hosting :
* hxxpx : / /click [.] xxxxxx[.] com/zpxyvp/eqTYcqOg
It is possible that some of those URLs are not accessible right now, because our anti-phishing system might have been activated, protecting victims of this type of fraud, while you're working to fix the problem.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

and ESET Internet Security as follow
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
__________ ESET Internet Security __________

Threats were found in this email:

QQ1618815406UD.doc - VBA/TrojanDownloader.Agent.UFY trojan - cleaned by deleting
Detection engine version: 22182 (20201020)

https://click.xxxxx.com/cvmhci/tkpZRuiq
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

The relay server compromised or please advise.

**Comment by willpower232** [comment]
Firstly, you should double check your DNS records to confirm that domain name is pointing at your Postal server.

Presuming you don't have any load balancers involved in your setup, you can then verify, using the netstat command, that Postal is still answering on the click tracking IP that you specified.

If it is, you should verify that this file is intact in your copy of Postal https://github.com/postalhq/postal/blob/master/lib/postal/fast_server/interface.rb

You can see that click tracking should only return the word `Hello` and definitely not anything else.
