### ISSUE TITLE
Receiving 500 on user creation and on create new mail server

### ISSUE THREAD

**Issue by soham-realtyx** [postalhq/postal#1241]
I have setup postal on digital ocean platform. All services are up and running.

root@bk:~# sudo -u postal postal status
Procodile Version   1.0.26
Application Root    /opt/postal/app
Supervisor PID      26559
Started             2020-10-23 13:41:21 +0000

 * worker.2 is not running (Failed)

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      13:41        pid:26565    respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.2         Failed       14:04        pid:28483    respawns:5      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.2           Running      14:04        pid:28406    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      14:04        pid:28399    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.2       Running      14:04        pid:28405    respawns:0      port:-        tag:-
root@bk:~# 

Here is nginx log:
13.235.242.142 - - [23/Oct/2020:14:08:04 +0000] "POST /org/mniacs/users HTTP/1.1" 500 46 "https://smtp.domain.com/org/mniacs/users/new" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"

Any solution on this issue?

**Comment by soham-realtyx** [comment]
My database name is postal

In log it shows postal-server-5
```
web.1:13945] [2020-10-24T04:49:57.316] FATAL -- : Mysql2::Error::ConnectionError (Access denied for user 'postaluser2'@'localhost' to database 'postal-server-5'):
[web.1:13945] [2020-10-24T04:49:57.316] FATAL -- :   
[web.1:13945] [2020-10-24T04:49:57.316] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'
```

**Comment by soham-realtyx** [comment]
I resovled it.

I added SMTP credentais in config file under SMTP section and it worked. https://mailtrap.io/

**Comment by fachryansyah** [comment]
@soham-realtyx how to add credential ? i'm already set config in /opt/postal/config/postal.yml but still error, can you give me step by step ?
