### ISSUE TITLE
Some Emails not Reaching Postal

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1242]
Hi, is there any reason why postal may not receive an email? We have checked the logs, settings, etc and we get reports, from time to time, that a specific email didn't reach postal. We have nothing on logs, so wonder if this problem is something that happens often.

**Comment by willpower232** [comment]
When you say not received an email, is someone else emailing an incoming route set up in Postal? If there are no log entries for the message then you would have to confirm with that other individual that the message was sent or what the response from Postal was.
