### ISSUE TITLE
Bounce Rules

### ISSUE THREAD

**Issue by saporus** [postalhq/postal#1243]
Hello,

Could anyone tell me where to locate bounce code rules?

I mean how Postal read bounce codes to determine either soft or hard fail.
For example: 553 5.3.0 (A code like this says it is hardfails whereas in PMTA it is soft. Sincerely, it supposed to be soft and that is what Postal has been lacking behind for some times now)

I need the file location where the codes/rules are.

Thanks

**Comment by willpower232** [comment]
I think that is mostly triggered here https://github.com/postalhq/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/lib/postal/smtp_sender.rb#L171-L176

The error code you mentioned `553` is greater than `500` implying the message won't be able to be delivered hence the hard fail. See also https://www.serversmtp.com/smtp-error/

**Comment by saporus** [comment]
Thanks @willpower232 ,

"553 5.3.0 alpd681 DNSBL:RBL 521< 51.xxx.x.xx >_is_blocked.For assistance forward this error to abuse_rbl@abuse-att.net"

The same type of error above should be soft and not hardfail because it is a temporary things.
That is why PMTA is still more powerful because same error code is regards as softfail on PMTA.

It should not be regard as hardfail or permanent error because even after Postal said hardfail, there was still button option to "Redeliver the message" I clicked on the redeliver button and the message was again sent successfully.

Some of the ISP may block an IP for some reasons. Sometimes because IP may be cold, reputation e.t.c and after some hours their system automatically release the IP from being blocked. But since Postal is marking them as hardfail, there's no way Postal could automatically redeliver the message except you manually click on the "Redeliver" button.

This issue also very relate to this #266 and also #787 and it hasn't yet be worked on.

Postal is lacking a lot of futures even as it is good with great UI.

How I wish the developer could put more effort to make Postal great.

If it requires donation, we would donate.

Thanks for your help tho.

**Comment by willpower232** [comment]
I understand the annoyance, I'd say this is a complicated topic and worthy of input from someone who is more familiar with the SMTP standards and RFCs.

I'd imagine that the current line is drawn between problems that are solved by time, like servers being offline, and problems that require manual intervention, like being blocked or emailing an address that doesn't exist.

Postal is using the one exception Ruby provides for this purpose and whilst that seems fine at a casual glance, it may not be the completely correct interpretation or it may be other email providers using the status codes inappropriately.
