### ISSUE TITLE
Sending attachments with the HTTP API

### ISSUE THREAD

**Issue by someshkar** [postalhq/postal#1244]
I was looking for a way to send attachments using postal's HTTP API, which is [documented here](https://krystal.github.io/postal-api/controllers/send/message.html), but I couldn't find any in depth information on the `attachments` key in the request's JSON body.

How exactly do you send files as attachments using that array? Can you provide an example request in the documentation?

**Comment by willpower232** [comment]
great question, the docs should be updated but I'm not sure how that needs to happen in moonrope.

The answer is each attachment should be represented as an array containing the files name, mime type, and base64 encoded contents.

Here is the code from the PHP library:
https://github.com/krystal/postal-php/blob/cddd9c5f34ec5234ccfcd9ce9193f7327802c2a6/src/SendMessage.php#L75-L84

**Comment by someshkar** [comment]
Yep, that works! Thanks for the quick reply :)

**Comment by willpower232** [comment]
I think we should leave this open as something to be resolved.

**Comment by adamcooke** [comment]
The new API (which will be powered by a new API framework) will be able to address this because its documentation generation capabilities are far better than Moonropes.
