### ISSUE TITLE
No SMTP servers were available for gmail.com

### ISSUE THREAD

**Issue by approached** [postalhq/postal#1247]
Hi@all

I have follow error:

_No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com

421 4.7.0 Try again later, closing connection._

Google said, postal use a **wrong SSL encryption**: https://support.google.com/mail/thread/40108790?hl=en

Does anybody hava a solution?

**Comment by willpower232** [comment]
The most likely cause of this issue is your server provider blocking SMTP connections. Have a look at #564, #738, #1178, and #1233.

This tends to happen with newer accounts and there may be a way for you to request opening the SMTP ports from them.

**Comment by approached** [comment]
@willpower232 thank you, for your comment. I asked my provider _hetzner_, they said: We don't have any outbound filter.

How i can test? I think it is a IPv6 problem.

```bash
root@postal ~ # telnet gmail-smtp-in.l.google.com 25
Trying 2a00:1450:400c:c0b::1a...
Connected to gmail-smtp-in.l.google.com.
Escape character is '^]'.
421 4.7.0 Try again later, closing connection.
Connection closed by foreign host.

root@postal ~ # telnet 64.233.184.27 25
Trying 64.233.184.27...
Connected to 64.233.184.27.
Escape character is '^]'.
220 mx.google.com ESMTP s134si13677047wme.134 - gsmtp
```

Is that possible to use only a IPv4 connection?

**Comment by willpower232** [comment]
I believe it is possible, you can have a look at #813 and #435

**Comment by approached** [comment]
@willpower232 thank you. My solution:

Disable ipv6 completely:
```bash
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
```

Than i'am reboot the server. I checked the configuration with **ifconfig**. It looks good.

Than i check the telnet connection:
```bash
root@postal ~ # telnet gmail-smtp-in.l.google.com 25
Trying 64.233.184.27...
Connected to gmail-smtp-in.l.google.com.
Escape character is '^]'.
220 mx.google.com ESMTP m18si23496243wrg.331 - gsmtp
```

Now postal works fine. I can not really explain where is error with gmail and IPv6.

**Comment by willpower232** [comment]
Its not a perfect solution but glad it works.

I imagine that sending verified email with IPv6 is stricter than with IPv4 so hopefully it will get easier as everything slowly switches over.

**Comment by acsfer** [comment]
Thanks, it solved the same problem for me.
But I don't understand why Google receives it on IPv6...after disabling it on Postal host...

> Message for *******@gmail.com accepted by gmail-smtp-in.l.google.com (2a00:1450:4010:c08::1b)

**Comment by willpower232** [comment]
You can verify that IPv6 is definitely off with the `netstat` command as you shouldn't see any `udp6` or `tcp6` lines.

**Comment by acsfer** [comment]
I had to explicitly disable it for `eth0`

`net.ipv6.conf.eth0.disable_ipv6 = 1` 👍

**Comment by SimonBiggs** [comment]
Hi, I am still having this same issue. 

Running the following gives:

```
simon@postal:~$ telnet gmail-smtp-in.l.google.com 25
Trying 2404:6800:4003:c11::1b...
```

But running the following gives:

```
simon@postal:~$ telnet 64.233.184.27 25
Trying 64.233.184.27...
Connected to 64.233.184.27.
Escape character is '^]'.
220 mx.google.com ESMTP d3-20020adfe843000000b002c594da9230si8396343wrn.887 - gsmtp
```

My error message within postal is:

```
No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com
```

And I have made the following changes to `/etc/sysctl.conf` followed by a reboot:

```conf
# Copied from https://github.com/postalserver/postal/issues/1247#issuecomment-721290912
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
```

**Comment by SimonBiggs** [comment]
From here (https://itsfoss.com/disable-ipv6-ubuntu-linux/)

I worked out my issue. I needed to follow the steps at that page:

---

If IPv6 is still enabled after rebooting, you must create (with root privileges) the file /etc/rc.local and fill it with:

```
#!/bin/bash
# /etc/rc.local

/etc/sysctl.d
/etc/init.d/procps restart

exit 0
```

Now use [chmod command](https://linuxhandbook.com/chmod-command/) to make the file executable:

```
sudo chmod 755 /etc/rc.local
```

What this will do is manually read (during the boot time) the kernel parameters from your sysctl configuration file.
