### ISSUE TITLE
Build a new mail server

### ISSUE THREAD

**Issue by JudgeAdil** [postalhq/postal#1251]
hello, i have an issue when building a mail server, installation went good on Ubuntu 18 server, hosted at Digitalocean, but after creating organization, i can't build a mail server, the green button just keeps showing that it's loading, but nothing happens. Thanks for your time

**Comment by kusobiz** [comment]
You can't use DO for postal because their port 25 is closed and they will not open.

**Comment by JudgeAdil** [comment]
I see, thank you for your answer, any company you suggest ?

**Comment by willpower232** [comment]
It may be worth asking digital ocean if they will allow you to send emails before changing providers.

Regarding your initial problem, it sounds like you are encountering a server problem so you should have a look at your logs to see what it is.

**Comment by JudgeAdil** [comment]
> 
> 
> It may be worth asking digital ocean if they will allow you to send emails before changing providers.
> 
> Regarding your initial problem, it sounds like you are encountering a server problem so you should have a look at your logs to see what it is.

thanks for your answer, can you point me to the logs i should check ?

**Comment by willpower232** [comment]
They are in `/opt/postal/log`, for your error I think you'll need the rails one but I could be mistaken.

**Comment by Xando235** [comment]
Hi, I am having the same problem and I am locally hosting the server.  My port 25 is open and smtp is listening on it, however, I am still unable to build a new mail server.  Any assistance will be greatly appreciated as I am new to this.

**Comment by willpower232** [comment]
@Xando235 as per my previous message, you will need to look at your own log files to see what is going wrong

**Comment by Lyamc** [comment]
Just thought I'd chime in. I ran into the same issue, in my case the error was in /opt/postal/logs/rails.log

`[web.1:32242] [2020-11-26T00:34:02.640] INFO -- : Started POST "/org/example/servers" for 127.0.0.1 at 2020-11-26 00:34:02 -0800
[web.1:32242] [2020-11-26T00:34:02.641] INFO -- : Processing by ServersController#create as JSON
[web.1:32242] [2020-11-26T00:34:02.641] INFO -- :   Parameters: {"utf8"=>"✓", "server"=>{"name"=>"Example Mail", "permalink"=>"", "mode"=>"Live"}, "commit"=>"Build server", "org_permalink"=>"example"}
[web.1:32242] [2020-11-26T00:34:02.659] INFO -- : Completed 500 Internal Server Error in 18ms (ActiveRecord: 8.8ms)
[web.1:32242] [2020-11-26T00:34:02.660] FATAL -- :
[web.1:32242] [2020-11-26T00:34:02.660] FATAL -- : Mysql2::Error::ConnectionError (Access denied for user 'postaluser'@'localhost' to database 'postal-server-3'):
[web.1:32242] [2020-11-26T00:34:02.660] FATAL -- :
[web.1:32242] [2020-11-26T00:34:02.660] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'`

I checked and my passwords in /opt/postal/config/postal.yml are correct, I have access to mysql with 
`mysql -u postaluser -p`

**Comment by Lyamc** [comment]
I fixed the issue. First thing I did was fix the mysql issues.

Next I double-checked my postal config: there was an issue. I was following two tutorials, one had "postaluser" and one had "postal" so I had been using the wrong user for the database! 🤦 

Anyways, once that was sorted out, I reinitialized postal and everything works!

**Comment by willpower232** [comment]
Glad you figured it out, which tutorial were you following? The quick install script should make all this easier to get going with rather than following individual steps

**Comment by Lyamc** [comment]
The quick install script is for Ubuntu 16.04, I'm running Ubuntu 20.04. I also had modified the tutorial a bit, but from what I can tell it's essentially the one provided here on github that someone modified a bit.

The biggest difference with the way I did it was that I didn't need to add any external repositories for the install. I did have to specify a particular version of something for a ruby package

I'm going to try modifying the current script to make it work on any standard 20.04 install and submitting it with a feature request for 20.04 support.

**Comment by Lyamc** [comment]
I'm still working on the script, but I found something interesting:

Both of the following work:
```
echo 'GRANT ALL ON `'$postaluser'`.* TO `'$postaluser'`@`127.0.0.1` IDENTIFIED BY "'$passgen'";' | sudo mysql -u root
echo 'GRANT ALL ON `'$postaluser'`.* TO `'$postaluser'`@`localhost` IDENTIFIED BY "'$passgen'";' | sudo mysql -u root
```
but logging in does not when using 127.0.0.1

```
$ mysql -u postal@localhost -p
Enter password:
ERROR 1698 (28000): Access denied for user 'postal@localhost'@'localhost'
$ mysql -u postal@127.0.0.1 -p
Enter password:
ERROR 1698 (28000): Access denied for user 'postal@127.0.0.1'@'localhost'
$ mysql -u postal -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 112
Server version: 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

I adjusted the commands:
```
$ mysql -u 'postal'@'127.0.0.1' -p
Enter password:
ERROR 1698 (28000): Access denied for user 'postal@127.0.0.1'@'localhost'
```

This is what caused my troubles! According to one tutorial I was supposed to use `127.0.0.1` while according to another I needed to use `localhost`

**Comment by Lyamc** [comment]
#1265

**Comment by sahil143780** [comment]
hi @Lyamc i am getting the same issue cant build the server, can you tell me clear steps , because i follow every tutorial cant work anything.

**Comment by sahil143780** [comment]
![Uploading Screenshot (106).png…]()

**Comment by antoniozh** [comment]
https://dba.stackexchange.com/a/115032

GRANT ALL PRIVILEGES ON `postal\-%`.* TO postal@'localhost';

what I did was add all privileges to any db with postal as prefix to my postal user on SQL. 
If the postal does not have all privileges this will be necessary since it creates one db for each mailserver.
