### ISSUE TITLE
High availability/geo replication setup

### ISSUE THREAD

**Issue by davidmia** [postalhq/postal#1253]
Hello

Is it possible to setup postal in a geo replicated environment with both servers running as masters? If so could someone briefly outline what needs to happen to make this work and I'll research on how to do it?

I have no understanding of ruby so I don't really know how postal works but my concern is if server1 receives an outgoing email, that may replicate onto server2 and then both servers may send the email.

The other concern is IP pools as different servers will have different IP pools available.

I'm assuming IP pools are stored in the database so if the databases are replicated, won't both servers presume to have each others IP pools available? (I hope I articulated that correctly)

Any advice is greatly appreciated.

**Comment by willpower232** [comment]
The best way to run Postal with redundancy is to centralise the Rabbit and MySQL parts, then there shouldn't be any problem with multiple instances of Postal running. If you're replicating the database and queue then yes there will be duplicates sent.

Based on others experiences, if you set up IP pools then messages will not send from the server that doesn't have the same IP addresses which kind of goes against the redundancy aspects.
