### ISSUE TITLE
How to fix "cannot find your reverse hostname"?

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1254]
Hi, I have setup postal as is:
![image](https://user-images.githubusercontent.com/1076409/98852454-9b36ac80-244f-11eb-9abb-507257f568dc.png)

When Postal tries to send an email to some emails I get his message: 

![image](https://user-images.githubusercontent.com/1076409/98852575-c6210080-244f-11eb-97db-467e7f4b72cc.png)

Is there a way to solve this?

**Comment by willpower232** [comment]
Your server provider will have a mechanism for creating a reverse DNS entry for your server.

**Comment by Igcorreia** [comment]
Your suggestion worked. Thanks
