### ISSUE TITLE
Fail2ban compatible log pattern

### ISSUE THREAD

**Issue by marcvanwijlick** [postalhq/postal#1255]
Hello,

Have you every configured fail2ban with Postal to block the IPs that try to brute force the SMTP authentication ?

For this, could you change the log message, so on the same line, the remote IP and number of wrong attempts are specified for the "Invalid credential" message ?

Thanks in advance,

Marc

**Comment by willpower232** [comment]
This won't be possible without making use of the database to track failed attempt counts.

I would advise against this as fail2ban does its own counting so it would be redundant.

If your code has the change from #1187 then it already has the sufficient line in it. If you want to modify that line, that is the place to do it.

**Comment by marcvanwijlick** [comment]
Thanks @willpower232, I hadn't seen this one. 
That's exactly what I was looking for !
