### ISSUE TITLE
Instant softfail

### ISSUE THREAD

**Issue by Robmobius** [postalhq/postal#1257]
Hi, 

I have created a new mail server account on a working set up of postal, ie I have mail server accounts happily sending email for different domains on this server

But for this new mail server, email is failing straight away with error message

undefined method `empty?' for nil:NilClass

Time: 0.02s

Support Ref: A8TU4ENO

No idea what this means. Can anyone assist?

**Comment by Robmobius** [comment]
here is what I can find in smtp_sender log

[34m[worker.1:6402][0m [2020-11-15T14:43:43.327] INFO -- : [MJKRQW5L] Connected to 2a00:1450:4013:c01::1b:25 (gmail-smtp-in.l.google.com)
[34m[worker.1:6402][0m [2020-11-15T14:43:43.328] INFO -- : [MJKRQW5L] NoMethodError: undefined method `empty?' for nil:NilClass
[34m[worker.1:6402][0m [2020-11-15T14:43:43.353] INFO -- : [MJKRQW5L] Finishing up

**Comment by Robmobius** [comment]
here is what I can find in smtp_sender log

`[34m[worker.1:6402][0m [2020-11-15T14:43:43.327] INFO -- : [MJKRQW5L] Connected to 2a00:1450:4013:c01::1b:25 (gmail-smtp-in.l.google.com)
[34m[worker.1:6402][0m [2020-11-15T14:43:43.328] INFO -- : [MJKRQW5L] NoMethodError: undefined method `empty?' for nil:NilClass
[34m[worker.1:6402][0m [2020-11-15T14:43:43.353] INFO -- : [MJKRQW5L] Finishing up
`

**Comment by willpower232** [comment]
You can use the support ref to search the smtp_sender.log files, the one in your example does not match the one in your first message.

**Comment by Robmobius** [comment]
Thanks Will, 

The error repeats each time I and send, so its identical. 

But here is the one the correlates to my original post. 

[33m[worker.5:17897][0m [2020-11-15T12:43:32.855] INFO -- : [A8TU4ENO] Connected to 2a00:1450:4013:c01::1a:25 (gmail-smtp-in.l.google.com)
[33m[worker.5:17897][0m [2020-11-15T12:43:32.879] INFO -- : [A8TU4ENO] NoMethodError: undefined method `empty?' for nil:NilClass
[33m[worker.5:17897][0m [2020-11-15T12:43:33.073] INFO -- : [A8TU4ENO] Finishing up

**Comment by Robmobius** [comment]
Is there anyone who can shed some light on this issue and help me out?

**Comment by willpower232** [comment]
its a bit difficult to see where that is coming from, is there definitely no lines between those last two lines? Sometimes there will be a stack trace to point at the line of code that errored.

**Comment by Robmobius** [comment]
Thanks Will, 

That's a direct past from the smtp_sender log so that's all I have. It's odd as there are other mail servers (as postal calls them, I think of them as accounts) on the same server under the same postal organisation, working 100%, ie using the same code base. I can see no difference in how I have set up this new server compared with the others. Logic suggests if its was a bug the issue would affect the other mail servers but it is not. I have even tried re installing the base code but the issue persists.

**Comment by Robmobius** [comment]
I see this in the rails 2 log - no idea what it means but the words "fatal" jump out at me

[34m[web.1:4428][0m [2020-11-16T01:51:15.909] INFO -- : Started POST "/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php" for 91.241.19.84 at 2020-11-16 01:51:15 +0000
[34m[web.1:4428][0m [2020-11-16T01:51:15.910] FATAL -- :   
[34m[web.1:4428][0m [2020-11-16T01:51:15.910] FATAL -- : ActionController::RoutingError (No route matches [POST] "/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"):
[34m[web.1:4428][0m [2020-11-16T01:51:15.910] FATAL -- :   
[34m[web.1:4428][0m [2020-11-16T01:51:15.910] FATAL -- : actionpack (5.2.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2.1) lib/rails/rack/logger.rb:28:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
secure_headers (6.0.0) lib/secure_headers/middleware.rb:13:in `call'
sentry-raven (2.7.4) lib/raven/integrations/rack.rb:51:in `call'
railties (5.2.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/commonlogger.rb:38:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'

**Comment by willpower232** [comment]
> Started POST "/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"

Looks like something scanning for vulnerabilities.

Does this happen to all emails you send to gmail or just emails in this specific server?

**Comment by Robmobius** [comment]
It’s all mail sent by this server. 

Is that file malware then? Ie not part of the source code, can I delete it? 

What is the best way to check for malware with postal?

**Comment by willpower232** [comment]
The file does not exist, someone was just scanning for it so you can ignore that error.

So your Postal cannot send any email at the minute? Are you using the quick install script to install?

**Comment by Robmobius** [comment]
Thanks Will, 

That explains why I can't find the file. 

The other mail servers under the organisation are able to send mail, but the new mailserver just set up, cannot. 

I installed via console of the digital ocan using the command curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh

This worked just fine as all the mail servers (I think accounts is a better name) under the postal organisation are working. 

I added the new mailserver using the postal interface "build new mail server"

**Comment by willpower232** [comment]
Very odd, you mentioned you reinstalled everything earlier but the issue came back, could it somehow be the name of the mail server that is to blame? Is there another with an identical name somewhere else in your Postal setup?

**Comment by Robmobius** [comment]
Hi Will, 

I am using mautic to create the emails. I have moved the Mautics (4 are connected to my postal server) to a new server. 2 are working just fine and 2 are giving this error. Nothing has changed besides the server the mautics are on and they are all on the same server. 

No, they all have different names. 

I am starting to think I must can this server and spin up and whole new postal server, but I have warmed up this IP so not keen on that. 

is there a way to delete (uninstall) postal and its database from a VPS (Digital Ocean linux) and start again? I am border line illiterate when it comes to Linux commands although I can cut and paste rather well....

**Comment by willpower232** [comment]
The only way to remove Postal is to manually delete `/opt/postal` and all the databases unfortunately.

There must be something unique about those messages, do they have any attachments or anything?

**Comment by Robmobius** [comment]
The messages are simple plain text emails. The same as are being happily sent by my other mautic / postal integrations. 

I get the same error regardless of the email address being sent or the type of email sent.

**Comment by willpower232** [comment]
I'm afraid it is difficult to diagnose what is going wrong without more information, you could try integrating Sentry.io to see if that can record a full stack trace to tell us which part of the code is not working.

**Comment by uhlhosting** [comment]
@willpower232 can you add more details on sentry and postal?

**Comment by willpower232** [comment]
My apologies, I thought this was documented but does not seem to be.

When you create a project within Sentry, you will be given a URL to report errors to. The Sentry dependency is already part of Postal so all you need to do is specify the URL in postal.yml and restart to apply the changes. The settings key is here:

https://github.com/postalhq/postal/blob/dcb2919cc6202cea579109e9de435e646fb1bd5f/config/postal.defaults.yml#L13

**Comment by uhlhosting** [comment]
@willpower232 guess we should be tracking mostly ruby?

**Comment by willpower232** [comment]
yes, its the Ruby gem for sentry that is installed, there is no javascript/client side tracking set up AFAICT
