### ISSUE TITLE
Fix FORGED_SPF_HELO

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1259]
Spammassasin check for: FORGED_SPF_HELO and usually we get a 1.0 spam value for this validation.

Is there a way to fix this? I have reverse DNS already implemented.

**Comment by willpower232** [comment]
Where are you seeing this message?

**Comment by Igcorreia** [comment]
In this section usually.

@willpower232 

![image](https://user-images.githubusercontent.com/1076409/99556677-bce8e400-29b9-11eb-8565-5f50052dc9be.png)

**Comment by willpower232** [comment]
There must be something not quite right with the specific domain you're using, you could try increasing the spam threshold and trying sending to https://www.mail-tester.com/ or similar and see if they can give you more information.

**Comment by Igcorreia** [comment]
With email tester, I get a 10/10, and these issues are confirmed, I have triple checked them. There are only 2 suggestions of improvements, one is the List-Unsusbcriber Header, I don't need that right now.

But they suggest to add this:

![image](https://user-images.githubusercontent.com/1076409/99568470-5b2f7680-29c7-11eb-8f79-4b1154cea44f.png)

do you think we should add this too all domains?

ps: you may close this issue.

**Comment by willpower232** [comment]
Perhaps Postal isn't completely satisfied with how it receives the messages then but if email tester gives you that score, you should be fine to leave the spam threshold higher for now.

DMARC is a relatively new feature but also involves someone receiving email reports of invalid messages so I would say is not for Postal to have a say in as it will depend on how you want to manage your own emails. If you want to apply that record then I'd advise you read up how DMARC works and what its for.

Feel free to close the issue if you have no more queries.

**Comment by Igcorreia** [comment]
Perfect. Thanks
