### ISSUE TITLE
Start Multiple SMTP Servers

### ISSUE THREAD

**Issue by matthewscalf** [postalhq/postal#1260]
What is the best way to start multiple smtp servers so I can load balance them?

**Comment by willpower232** [comment]
As per #334 (and assorted linked issues) all you need to do is run RabbitMQ and MySQL in a central location and then you can run multiple servers however you see fit.

**Comment by matthewscalf** [comment]
Thanks. I guess I meant if I wanted to run multiple instances of just the smtp server on the same machine that would be load balanced. I didn't really want to break it up into different servers, especially because I am not sure how that would work with the IP pools. But I would like to break the smtp up and load balance it because we are hitting limits of how many incoming requests the system can handle.

**Comment by willpower232** [comment]
> we are hitting limits of how many incoming requests the system can handle

Can you tell us what problems you are seeing? 

Load balancing within a single server is difficult because of access to specific ports, its easier to scale out to other servers. You can have a look at #324 for some worker ideas and #751 for some more SMTP-related ideas.
