### ISSUE TITLE
Please, I need serious help!

### ISSUE THREAD

**Issue by byte-entrepreneur** [postalhq/postal#1263]
I've been trying to configure my Postal SMTP for almost a week now, and apparently it has driven me nuts!
When I send a test message with Mautic to mail-tester.com, mail-tester.com says "you're not fully authenticated", further stating: 
"[SPF] psrp.bountymarketers.com does not allow your server 123.12.123.123 to use jzpz9m@psrp.bountymarketers.com - You do not have a SPF record, please add the following one to your domain psrp.bountymarketers.com:

v=spf1 a mx ip4:164.68.127.175 ~all 

Verification details:

dig +short TXT psrp.bountymarketers.com :
dig +short SPF @8.8.8.8 psrp.bountymarketers.com :
spfquery --scope mfrom --id jzpz9m@psrp.bountymarketers.com --ip 164.68.127.175 --helo-id server.bountymarketers.com :
none
psrp.bountymarketers.com: No applicable sender policy available
psrp.bountymarketers.com: No applicable sender policy available
Received-SPF: none (psrp.bountymarketers.com: No applicable sender policy available) receiver=ns303428.ip-94-23-206.eu; identity=mailfrom; envelope-from="jzpz9m@psrp.bountymarketers.com"; helo=server.bountymarketers.com; client-ip=164.68.127.175
"

- what does that even mean? I already setup the Return Path you guys asked me to add to my domain, including the SPF record you asked to add in my DNS! 

It didn't end there...

mail-tester.com also stated: "We didn't find a mail server (MX Record) behind your domain name psrp.bountymarketers.com - You may want to publish a DNS record (MX type) for the domain name psrp.bountymarketers.com or use a different bounce email address."

I have literally tried correcting this a hundred times, but can't because I don't even understand all these technical stuff.

If you run an MX Lookup on mxtoolbox.com on my domain (bountymarketers.com), you will notice it saying: 

**"mx.server.bountymarketers.com | {No A Record}"**

If you run an MX Lookup on mxtoolbox.com on psrp.bountymarketers.com, it says: **"DNS Record not found"**

**Also, I need your help to setup incoming emails into my postal, and also to setup Routing.** 
I'm willing to pay to have this setup for me please!!!!!!! Thanks.

**Comment by willpower232** [comment]
Regarding your SPF query, I think your DNS records aren't quite set up right. Compare yours (top) to one of ours (bottom) and see how we refer to the main SPF record

![image](https://user-images.githubusercontent.com/1619102/100455653-f3f47f00-30b6-11eb-9357-bfe7f00e5237.png)

This may explain your other issues, you could try referring to the wiki for the records that you need to fully link to your Postal server https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

**Comment by Igcorreia** [comment]
Hi @byte-entrepreneur please reach me directly maybe I can help.

**Comment by byte-entrepreneur** [comment]
@Igcorreia thank you for lending a helping hand. I had someone fix the issues on the day I posted this issue.

@willpower232 Thanks also. 

BTW, how can I change my Postal password?

**Comment by willpower232** [comment]
Presuming you are referring to an admin account, the best way is to configure Postal to send emails, either via itself or another SMTP service in the postal.yml config file, and then use the forgotten password link on the login form.
