### ISSUE TITLE
Unable to receive emails.

### ISSUE THREAD

**Issue by Software-Wolf** [postalhq/postal#1264]
I configured everything correctly and used the thing to check the DNS and everything (including the MX record) says "GOOD." However, it will not receive any emails. I have a proper route set up, and it simply just won't receive the emails. They are not in spam, hold, or queue. It IS accepting the emails, because there is no error when I send the email from the other side. But it is not receiving them, like they just disappear. I have no error logs or anything it is very weird.

**Comment by willpower232** [comment]
you can try watching the `smtp_server` log file to see if your message even makes it to the server, you can also verify your DNS records are pointing correctly around the internet using https://whatsmydns.net
