### ISSUE TITLE
port 25 is blocked on my country 

### ISSUE THREAD

**Issue by reviewoct** [postalhq/postal#1266]
hello 

i have installed the postal on a vps and configured it and it workd very greete to send and receive emails , but when i want to connect it with the sendblaster windows software to start some compagn , i see that port 25 is blocked by my internet provider and  all other providers are blocking it here 

also can you please tell me how to use an other port for smtp like the 587 port instease of the 25 port ?

thanks
amine

**Comment by willpower232** [comment]
If you are referring to your home/office internet connection, you can have a look at #565 and other mentions of iptables here for how to use iptables to open up other ports for you to send mail to Postal with. As part of the original setup for Postal, we have port 2525 in use as well as 25.

If your server provider is blocking the port then there is not a lot you can do.

**Comment by reviewoct** [comment]
hy 
thanks for your help 

also i have follwed your documentation on #565  but when install the ufw on the ubuntu server and ufw allow 587 and run 
telnet ipadress 587 it give this result :  
telnet: Unable to connect to remote host: Connection refused  aven when i allow port 25 it give me the same error 

is there any fix for this please ?

thanks
amine

**Comment by willpower232** [comment]
You should make sure that Postal is running and binding successfully to the ports, you can use `postal status` and `netstat -lnp` to see what is using which port
