### ISSUE TITLE
the web interface is broken

### ISSUE THREAD

**Issue by strelok899** [postalhq/postal#1268]
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.557] INFO -- : Started GET "/javascripts/application/application.js" for 212.116.160.142 at 2020-12-06 19:23:13 +0000
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.559] FATAL -- :   
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.560] FATAL -- : ActionController::RoutingError (No route matches [GET] "/javascripts/application/application.js"):
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.561] FATAL -- :   
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.562] FATAL -- : vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
19:23:13 web.1              | => vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'

i getting the same for application.js

19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.467] INFO -- : Started GET "/stylesheets/application/application.css" for 212.116.160.142 at 2020-12-06 19:23:13 +0000
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.470] FATAL -- :   
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.471] FATAL -- : ActionController::RoutingError (No route matches [GET] "/stylesheets/application/application.css"):
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.472] FATAL -- :   
19:23:13 web.1              | => [web.1:27440] [2020-12-06T19:23:13.473] FATAL -- : vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
19:23:13 web.1              | => vendor/bundle/ruby/2.3.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'

and for application.css

how to fix it? i stuck with this

**Comment by strelok899** [comment]
fixed it by mistake the problem is that autoprefixer-rails doesn't support nodejs 4.6

so i manually updated to nodejs 10

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs


ubuntu 16.04 and everything works

**Comment by willpower232** [comment]
thanks for letting us know, this was already reported in #971
