### ISSUE TITLE
Solve the problem

### ISSUE THREAD

**Issue by osama-2000-web** [postalhq/postal#1269]
How do I connect a server with SendBlaster?
Or how can I create an smtp account inside the server?

**Comment by willpower232** [comment]
You would probably need to create an SMTP credential for the domains etc you add to Postal and give that credential as the SMTP username/password in SendBlaster

**Comment by osama-2000-web** [comment]
How can I create own credentials in smtp?

**Comment by willpower232** [comment]
You need to use the UI to create the organization and server and then add domains and then you should see a credentials tab.
