### ISSUE TITLE
IP authentication - errors [doesn't work]

### ISSUE THREAD

**Issue by nenominal** [postalhq/postal#1270]
I'm trying to use the SMTP-IP feature but I think I hit a bug

I've created a profile for SMTP-IP and assigned just for test an IP and this is how it's saved
![Screenshot-20201210112411-964x688](https://user-images.githubusercontent.com/21262237/101752592-619ea300-3ada-11eb-931d-dc4454ed97bc.png)

Bellow is the info from database.
![Screenshot-20201210112811-1525x94](https://user-images.githubusercontent.com/21262237/101752991-ce19a200-3ada-11eb-9756-32221349c101.png)

And the logs from **smtp_server.log**

```
[smtp.1:14414] [2020-12-10T11:14:43.162] ERROR -- : [QQ19CC] An error occurred while processing data from a client.
[smtp.1:14414] [2020-12-10T11:14:43.162] ERROR -- : [QQ19CC] NoMethodError: undefined method `prefix' for #<IPAddr: IPv4:192.168.3.100/255.255.255.255>
[smtp.1:14414] [2020-12-10T11:14:43.163] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/client.rb:317:in `block in rcpt_to'
[smtp.1:14414] [2020-12-10T11:14:43.164] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
[smtp.1:14414] [2020-12-10T11:14:43.164] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
[smtp.1:14414] [2020-12-10T11:14:43.165] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/client.rb:317:in `sort_by'
[smtp.1:14414] [2020-12-10T11:14:43.166] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/client.rb:317:in `rcpt_to'
[smtp.1:14414] [2020-12-10T11:14:43.166] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/client.rb:79:in `handle_command'
[smtp.1:14414] [2020-12-10T11:14:43.167] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/client.rb:50:in `handle'
[smtp.1:14414] [2020-12-10T11:14:43.168] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/server.rb:160:in `block (2 levels) in run_event_loop'
[smtp.1:14414] [2020-12-10T11:14:43.169] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `select'
[smtp.1:14414] [2020-12-10T11:14:43.170] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `block in run_event_loop'
[smtp.1:14414] [2020-12-10T11:14:43.171] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `loop'
[smtp.1:14414] [2020-12-10T11:14:43.172] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `run_event_loop'
[smtp.1:14414] [2020-12-10T11:14:43.172] ERROR -- : [QQ19CC] /opt/postal/app/lib/postal/smtp_server/server.rb:260:in `run'
[smtp.1:14414] [2020-12-10T11:14:43.173] ERROR -- : [QQ19CC] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[smtp.1:14414] [2020-12-10T11:14:43.174] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
[smtp.1:14414] [2020-12-10T11:14:43.174] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
[smtp.1:14414] [2020-12-10T11:14:43.175] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
[smtp.1:14414] [2020-12-10T11:14:43.176] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
[smtp.1:14414] [2020-12-10T11:14:43.177] ERROR -- : [QQ19CC] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:14414] [2020-12-10T11:14:43.177] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
[smtp.1:14414] [2020-12-10T11:14:43.178] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
[smtp.1:14414] [2020-12-10T11:14:43.178] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
[smtp.1:14414] [2020-12-10T11:14:43.179] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
[smtp.1:14414] [2020-12-10T11:14:43.180] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
[smtp.1:14414] [2020-12-10T11:14:43.180] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
[smtp.1:14414] [2020-12-10T11:14:43.181] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
[smtp.1:14414] [2020-12-10T11:14:43.182] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
[smtp.1:14414] [2020-12-10T11:14:43.182] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
[smtp.1:14414] [2020-12-10T11:14:43.183] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
[smtp.1:14414] [2020-12-10T11:14:43.184] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
[smtp.1:14414] [2020-12-10T11:14:43.185] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
[smtp.1:14414] [2020-12-10T11:14:43.186] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:14414] [2020-12-10T11:14:43.186] ERROR -- : [QQ19CC] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```

**Comment by willpower232** [comment]
At first glance, it appears to be failing in sorting available IPs

https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/lib/postal/smtp_server/client.rb#L317

Does it work if you specify the appropriate `/whatever` in the credential?

**Comment by nenominal** [comment]
> At first glance, it appears to be failing in sorting available IPs
> 
> https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/lib/postal/smtp_server/client.rb#L317
> 
> Does it work if you specify the appropriate `/whatever` in the credential?

Pardon my english but I don't understand what should I do :-)
Do you mean to replace "credential" with "SMTP-IP" ?

**Comment by willpower232** [comment]
Try specifying network as `192.168.3.100/32` and see if you still get the error when trying to send mail with your Postal

**Comment by nenominal** [comment]
I tried with IP only, IP/32 and a full network /24, it doesn't work, same error.

**Comment by willpower232** [comment]
Thanks for confirming, I would presume that there is a quirk with how you're supposed to enter IP addresses that isn't covered by form validation in the UI, also I would have hoped that the `|| 0` in the code would have compensated in this regard but evidently not.

Can you also confirm the version of Ruby you are using? That may be relevant.

Otherwise @catphish or @adamcooke would be able to comment further.

**Comment by nenominal** [comment]
Ubuntu 18.04.5 with ruby version as bellow.

```
zulu@medea:~$ ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux-gnu]
```

**Comment by foggeri** [comment]
Hmm, quick and dirty fix what seems to be working (checks the ip and if it's not in IP-SMTP it does not authorize).

@credential = Credential.where(:type => 'SMTP-IP').all.sort_by { |c| c.ipaddr || 0 }.reverse.find do |credential|

Seems that the ipaddr library included on default ruby does not need that prefix option becouse the prefix is in x.x.x.x/y format in database so ipaddr.include knows howto compare it. (maybe i didnt do full debug)

**Comment by nenominal** [comment]
Hello @foggeri , thanks for the workaround, it works, I have tested with one IP and a subnet.
Do you have an idea how can I set for multiple IPs (not a subnet, just a list of IPs). I have tried to add a list of IPs, comma separated, but it doesn't work: `"Key must be a valid IPv4 or IPv6 address"`

**Comment by foggeri** [comment]
> Hello @foggeri , thanks for the workaround, it works, I have tested with one IP and a subnet.
> Do you have an idea how can I set for multiple IPs (not a subnet, just a list of IPs). I have tried to add a list of IPs, comma separated, but it doesn't work: `"Key must be a valid IPv4 or IPv6 address"`

Hello,

Just add new IP-SMTP credential from "Credentials" tab.
![image](https://user-images.githubusercontent.com/8983814/104296342-2d981280-54ca-11eb-9076-de6364af9865.png)

**Comment by adamcooke** [comment]
This is/was an issue with running Postal with Ruby 2.3. Upgrade to 2.6.x.
