### ISSUE TITLE
Every Email in Every Server is Pending

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1273]
Hi, I have already restarted postal, tried to find any error or reasons for this to happen? Don't know what to do. 
Any idea what may be causing this? I have already hundreds of emails on queue to be send but they keep pending.
![image](https://user-images.githubusercontent.com/1076409/102599421-59b3b400-4115-11eb-9caf-8188f3f39c22.png)

**Comment by willpower232** [comment]
If you run `postal status` is everything running?

**Comment by Igcorreia** [comment]
![image](https://user-images.githubusercontent.com/1076409/102626552-de66f800-413e-11eb-8703-b8c4ef806eee.png)

**Comment by willpower232** [comment]
Presuming this is also related to your comments in that other issue, I guess you'll have to look at the log files to see if there are any errors occurring that its not telling you. It might also be worth incorporating sentry.io to get more detail.

**Comment by Igcorreia** [comment]
Yup, nothing was telling me the error. Still, everything stopped. :/ we have reboot the system and noticed that port 25 was misconfigured for some reasons, that is fixed. Now the only thing missing is to make the queue send again. I think I noticed that the Rabbit has nothing there is it supposed to be empty? In terms of the queue, I have enough emails pending. 

Could I go to the pending_messages DB and change the message dates, or that is not necessary?

**Comment by Igcorreia** [comment]
Regarding sentry any suggestion of where to start? server or ruby ou rail?

**Comment by willpower232** [comment]
I think if you go into one of the messages, you should see a requeue link or redeliver button which would allow you to "send" the message again. I'm not sure how to accomplish this in the database directly sorry.

Regarding sentry, all you need to do is provide the URL sentry gives you and restart. See https://github.com/postalhq/postal/issues/1257#issuecomment-737882967

**Comment by Igcorreia** [comment]
Alrady did, waiting for events to appear.

**Comment by Igcorreia** [comment]
Nothing in Sentry :/ any idea why Postal or Rabbit are re-sending the email?

**Comment by Igcorreia** [comment]
Worker log has this info:

[34m[worker.1:10316][0m [2020-12-18T17:12:42.275] INFO -- : Joined [32mmain[0m queue
[34m[worker.1:10316][0m [2020-12-18T17:12:53.297] INFO -- : Exiting immediately because no jobs running
[35m[worker.2:10408][0m [2020-12-18T17:12:56.532] INFO -- : Worker running with 4 threads
[35m[worker.2:10408][0m [2020-12-18T17:12:56.538] INFO -- : Joined [32mmain[0m queue
[35m[worker.2:10408][0m [2020-12-18T17:13:02.554] INFO -- : Exiting immediately because no jobs running
[34m[worker.1:10511][0m [2020-12-18T17:13:07.510] INFO -- : Worker running with 4 threads
[34m[worker.1:10511][0m [2020-12-18T17:13:07.518] INFO -- : Joined [32mmain[0m queue
[34m[worker.1:10511][0m [2020-12-18T17:22:06.852] INFO -- : Exiting immediately because no jobs running
[34m[worker.1:11859][0m [2020-12-18T17:22:11.293] INFO -- : Worker running with 4 threads
[34m[worker.1:11859][0m [2020-12-18T17:22:11.305] INFO -- : Joined [32mmain[0m queue
[34m[worker.1:11859][0m [2020-12-18T17:22:47.334] INFO -- : Exiting immediately because no jobs running
[34m[worker.1:12024][0m [2020-12-18T17:22:54.768] INFO -- : Worker running with 4 threads
[34m[worker.1:12024][0m [2020-12-18T17:22:54.776] INFO -- : Joined [32mmain[0m queue
[34m[worker.1:12024][0m [2020-12-18T17:24:04.823] INFO -- : Exiting immediately because no jobs running
[35m[worker.2:12279][0m [2020-12-18T17:24:07.286] INFO -- : Worker running with 4 threads
[35m[worker.2:12279][0m [2020-12-18T17:24:07.296] INFO -- : Joined [32mmain[0m queue

**Comment by Igcorreia** [comment]
Solved, like others mentioned disc space was reached. for some reason I had the log folder limited. Thanks

**Comment by willpower232** [comment]
glad you figured it out, feel free to close this issue if you have no further problems
