### ISSUE TITLE
SPF Checking error

### ISSUE THREAD

**Issue by AboJasim** [postalhq/postal#1275]
Dear members
I contacted Gsuite support and they gave me an SPF record that combines my SMTP and Google spf records like this:
v=spf1 a mx include:spf.postal.MYDOMAIN.com include:_spf.google.com ~all

in Postal Domains checking it shows all correct as per follow
![image](https://user-images.githubusercontent.com/76620021/103153308-c3306400-47a0-11eb-97f9-5625b83e2110.png)

But using other SPF checking tools it shows error 

![image](https://user-images.githubusercontent.com/76620021/103153391-3639da80-47a1-11eb-819a-2323d69166c0.png)

Can you help me with that? does it affect my SMTP?

**Comment by willpower232** [comment]
That error message implies that you haven't set up the base records that point at the server properly. Have a read of https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

Basically, postal expects you to have one "set" of subdomains referring to the server and postal itself and then another "set" of domains or subdomains that use the first "set" to refer to postal.

**Comment by AboJasim** [comment]
it's solved!! Thank you so much
