### ISSUE TITLE
Postal and Mautic Perfect Installation on Same VPS

### ISSUE THREAD

**Issue by alishehryar1** [postalhq/postal#1276]
Hi, Hope u Everyone doing well. I really need your help. Kindly guide me to install Postal and Mautic Perfectly on Same VPS!

**Comment by layen67** [comment]
Use docker my friend

**Comment by alishehryar1** [comment]
Thanks for reply dear. Can u write steps for this? It would really help alot

**Comment by layen67** [comment]
do you have skype

**Comment by alishehryar1** [comment]
Yes I do. What's your Skype ID?

**Comment by dxxbdoobdxxb** [comment]
is this even possible? to have mautic and postal in the same vps?

**Comment by layen67** [comment]
Yes install first postal (normaly install) after install mautic whith docker + docker compose.

**Comment by dxxbdoobdxxb** [comment]
sorry i'm kinda new to all this.
I've already installed postal and it's running 10/10 now...
so next step is install docker
then docker compose
then mautic right?
Do you have any reference article with a step by step guide?
thanks for responding man!
