### ISSUE TITLE
Fast server fails

### ISSUE THREAD

**Issue by MrRichThomas** [postalhq/postal#1278]
Hi, I'm really struggling to get click tracking working on a new Postal installation on an Ubuntu 18 server.

I initially had some problems with the IP setup, in that I was trying to use the public IP in the NGINX config to force NGINX to only bind to the primary IP, but that was failing due to the network setup at my hosting provider. I've since changed to the local IP as they use NAT, and NGINX is now happy.

I then changed the Fast server config in postal.yml to also use the internal IP that points to the secondary external IP.

So now, when I start Postal the Fast server initially says running but then within a few mins it fails after 5 respawns.

I also have an issue whereby the tracking domains I set up are stuck in a 'SSL Setup in progress' state. I'm guessing this is because  of the failed fast server.

The only time I've had any success is if I manually run: bundle exec rake postal:fast_server

The first time I did this it finally created a fast_server.log file, but it just says that it started on ports 80 and 443 on the correct IP, but the click tracking links when clicked in Firefox show a security warning, as if SSL isn't setup correctly. Also, as soon as I try restarting Postal the Fast server dies again.

The only thing I've found is the comment from @willpower232 in this issue which suggests maybe there's an issue with click tracking in Ubuntu 18? https://github.com/postalhq/postal/issues/777

Any help would be much appreciated.

Thanks
Rich

**Comment by willpower232** [comment]
If the fast server isn't able to bind to the ports by itself, you may need to re run this part of the install process https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/script/install/ubuntu1804.sh#L52

I think the problem was https://github.com/postalhq/postal/issues/857 which should have been resolved.

**Comment by MrRichThomas** [comment]
Thanks for the reply @willpower232 I've been running that command each time I reboot the server or restart Postal, so it's not that unfortuntely.

I've just had to reboot the server and this is what happens every time after reboot: I run the setcap bind command, I start postal, then run postal status, I can see fast server is running, I run postal status again after a few seconds and can see fast respawns has increased from 0 to 1, I then run postal status again and can see respawns increase until it gets to 5 and then fast shows as failed. This all happens within the first minute or so.

I've checked the logs and there is nothing in fast_server.log. I've checked the other logs and syslog and there's nothing of any use.

**Comment by willpower232** [comment]
In theory, you only need to run setcap when ruby is updated so you shouldn't need to run it constantly unless you're doing something with docker or vagrant.

When you run the fast server manually, are you doing it as the Postal user? That might reveal some errors immediately. If it doesn't then it may be log file permissions.

**Comment by MrRichThomas** [comment]
Thanks @willpower232 I wasn't running manually as the postal user , but I've just tried and get the following:

`postal@mail:~/app$ bundle exec rake postal:fast_server
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /opt/postal/log/fast_server.log
/opt/postal/app/lib/postal/app_logger.rb:8:in `initialize'
/opt/postal/app/lib/postal/config.rb:91:in `new'
/opt/postal/app/lib/postal/config.rb:91:in `logger_for'
/opt/postal/app/lib/postal/fast_server/server.rb:23:in `block in run'
/opt/postal/app/lib/postal/fast_server/server.rb:20:in `each'
/opt/postal/app/lib/postal/fast_server/server.rb:20:in `each_with_object'
/opt/postal/app/lib/postal/fast_server/server.rb:20:in `run'
/opt/postal/app/lib/tasks/postal.rake:33:in `block (2 levels) in <top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => postal:fast_server
(See full trace by running task with --trace)`

Which as you suggested is permisssions on the log file, presumably because I initially ran the rake command as root. I've now changed the permissions on the fast_server.log file to be owned by postal and I re-ran the rake command as Postal, and I now get the following:

`Could not locate Gemfile or .bundle/ directory`

Any ideas why that might be?

**Comment by willpower232** [comment]
I'd make sure you were in the right directory when running the command but if you've changed the file permissions, it might be easier to try restarting Postal

**Comment by MrRichThomas** [comment]
Sorry just realised, I'm an idiot, I was in the wriong directory! Will try a restart, unfortunately this is a live server already sending email so I need to time it when there's nothing going through.

**Comment by MrRichThomas** [comment]
Ok I'm making progress. I rebooted and the fast server now starts and stays running, so previously the fact that it couldn't write to the fast_server.log due to the permissions was causing it to fail.

Now, I'm trying ot add a tracking domain and when I add one it still gets stuck on 'SSL setup in progress'.

If I run a curl command to the http click URL I get 'Hello' back which is good.

However if I try and follow a link in an email that has been converted to a tracking link Firefox displays: Did Not Connect: Potential Security Issue

And if I click Advanced the error is: The certificate is not trusted because it is self-signed.

Any thoughts?

**Comment by willpower232** [comment]
Did you register with Lets Encrypt already? https://github.com/postalhq/postal/wiki/Click-&-Open-Tracking#setup-lets-encrypt

I think it will be self-signed until its able to create a certificate from Lets Encrypt. There have been other issues here where it has taken random amounts of time

**Comment by MrRichThomas** [comment]
Thanks Will, yes I'd already registered. I just checked /opt/postal/log/lets_encrypt.log and just noticed a 'Certificate issued' entry, so it loks like it took 10 mins or so for the certificate request to go through. I now have a green tick on the tracking page. 👍 

I'm still getting the certificate warning in Firefox though, do I need to restart Postal or will it update automatically after a while?

**Comment by willpower232** [comment]
It should have updated instantly. Can you verify with a different browser or device or private mode?

**Comment by MrRichThomas** [comment]
I've tried in multiple browsers and in private mode, and the issue seems to be that it works the first time and then any subsequent attempts to follow the link I get the security warning error.

**Comment by willpower232** [comment]
You get the certificate first time but not second time? That is weird, you haven't got a proxy in place have you?

**Comment by MrRichThomas** [comment]
I was on the work VPN and behind a proxy, I've tried switching to just my home network and I'm getting the same issue. Very weird. I'll check the logs and see if there's any clues in there.

**Comment by MrRichThomas** [comment]
A Postal restart appears to have fixed it. :) 

One unrelated question, when I run 'postal stop', postal appears to successfully stop all the processes but then I get the message:

`Supervisor will be stopped when processes are stopped.
Waiting for supervisor to stop...
`

And that just seems to hang, and I have to Ctrl-C and then I reboot the server. Am I just being impatient and does it just take a while for all the processes to stop? I seem to remember on our previous installation stopping was pretty much instant.

**Comment by willpower232** [comment]
Glad you figured it out, I don't think you should need to wait for a long time but if it has been having some troubles with failing processes there might be something not quite right behind the scenes at that time.

That said, now everything is working, you could schedule another shutdown to confirm whether or not it is okay but hopefully it will be a long time before you need to manually stop postal!

**Comment by MrRichThomas** [comment]
Ok, yeah I'll try a stopping at a quiet time and see if it's quicker now that the fast server is working.

Thank you very much for your help on this Will, much appreciated. :)
