### ISSUE TITLE
Domain in 2nd Organization not accepting MAIL FROM for that domain

### ISSUE THREAD

**Issue by stratacorps** [postalhq/postal#1280]
I need to admit I'm a bit confused on the domain seeing at the organization level and the domain set at the mail server level, so this may be where I'm messing things up.

I have a working Postal server, new install. I set up a "Main" organization for testing and using internally for Postal's own SMTP server. In testing I can telnet to the Postal server, authenticate, and send an email by specifying the postal server's domain just fine.

I set up a 2nd Organization. Created a Mail server. Added the domain and set up the DNS. I get green across the board under the DNS setup.

I can send a test email from the Web GUI as well, in fact it is clear if the FROM email address in the test form isn't the domain in the organization, it won't send, so I know that is working.

But when I authenticate remotely for testing the 2nd organization's domain, I get "530 From/Sender name is not valid"

If I use the Postal test from the command line, that works, but of course it's using the smtp settings in the config file and I've entered the Main organization's mail server settings there.

Is there a way for me to debug why it's not finding the domain as valid in the 2nd organization? Do I need to add all domains at the organizational level or at the mail server level or both? (which I know doesn't make sense, but thought I'd ask!)

> [smtp.1:2333]   [2021-01-09T22:34:04.648] DEBUG -- : [SMG6FC] <= ehlo myseconorgdomain.com
[smtp.1:2333] [2021-01-09T22:34:04.776]   DEBUG -- : [SMG6FC] => 250-My capabilities are
[smtp.1:2333] [2021-01-09T22:34:04.776]   DEBUG -- : [SMG6FC] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:2333] [2021-01-09T22:34:14.304]   DEBUG -- : [SMG6FC] <= auth login
[smtp.1:2333] [2021-01-09T22:34:14.304]   DEBUG -- : [SMG6FC] => 334 VXNlc…
[smtp.1:2333] [2021-01-09T22:34:23.344]   DEBUG -- : [SMG6FC] <= xxxxxxxxx==
[smtp.1:2333] [2021-01-09T22:34:23.346]   DEBUG -- : [SMG6FC] => 334 UGF…
[smtp.1:2333] [2021-01-09T22:34:34.790]   DEBUG -- : [SMG6FC] <= xxxxxxxxxxxxxxxxxxxxxxz
[smtp.1:2333] [2021-01-09T22:34:35.042]   DEBUG -- : [SMG6FC] => 235 Granted for second/domain
[smtp.1:2333] [2021-01-09T22:34:48.507]   DEBUG -- : [SMG6FC] <= mail from:<sales@myseconorgdomain.com>
[smtp.1:2333] [2021-01-09T22:34:48.507]   DEBUG -- : [SMG6FC] => 250 OK
[smtp.1:2333] [2021-01-09T22:34:53.963]   DEBUG -- : [SMG6FC] <= rcpt to:external@email.com
[smtp.1:2333] [2021-01-09T22:34:53.964]   DEBUG -- : [SMG6FC] Added external address 'external@email.com'
[smtp.1:2333] [2021-01-09T22:34:53.964]   DEBUG -- : [SMG6FC] => 250 OK
[smtp.1:2333] [2021-01-09T22:34:55.658]   DEBUG -- : [SMG6FC] <= data
[smtp.1:2333] [2021-01-09T22:34:55.659]   DEBUG -- : [SMG6FC] => 354 Go ahead
[smtp.1:2333] [2021-01-09T22:35:00.804]   DEBUG -- : [SMG6FC] <= subject:testing #399393
[smtp.1:2333] [2021-01-09T22:35:00.804]   DEBUG -- : [SMG6FC] Not logging further message data.
[smtp.1:2333] [2021-01-09T22:35:03.973]   DEBUG -- : [SMG6FC] => 530 From/Sender name is not valid

note: this happens to any additional organizational domain (edited). If I put the same exact domain in the first organization, it works but I was needing the Orgs to separate users from each other.

**Comment by willpower232** [comment]
You will need a second credential for your second server to use the second domain.

**Comment by stratacorps** [comment]
> You will need a second credential for your second server to use the second domain.

I have two Organizations, each has a mail server, each mail server has a domain, and a credential.

Org1 — mailserver A — domain1.tld 
Org2 — mailserver B — domain2.tld

domain1.tld works.
domain2.tld authenticates, but smtp session ends with 530 error

If I add domain2.tld to Org1, it works (with the same credential). Again, anything I try for an additional organization fails with the 530, but using the first organization, I can have multiple domains all working fine.

**Comment by willpower232** [comment]
That message happens when the credential you're using isn't in the same server at the domain so if you have created credentials in both servers, your connection using the second server isn't currently using the correct credentials.

**Comment by stratacorps** [comment]
I am so afraid of being a total noob here. I even have TLS working for my connections! So I thought I was on my way to the next level! :) But obviously I'm missing something from what you're trying to help me with, so I apologize.

Here is the scenario, post installation when the Postal web GUI is ready for me to sign in with my first admin user created at the end of the installation.

1. The first/only option is to create my first Organization. I want to "white label" this installation so other organizations will be for different domains. I assumed my first organization was to be just the Postal server's own SMTP service to send out notifications. From the default configuration yaml file I understand I must first create my first Organization, then its mail server, and then a set of credentials, then come back to the postal.yml file and update the smtp section. Changing 2525 to 25, entering the username for the first Organization's credentials.

2. I am able to test from the command line as well as from the web gui (mail server, Messages, Send Message).

3. I now want to set up a second organization, a different domain, etc. So I create a new Organization, create a new Mail Server, and a new set of credentials. The domain is validated (SPF, DKIM, Return path, etc.). 

4. From Postal's web gui, I can select that organization, Mail server, and then send a test message just fine.

But if I try to set up a mail client (I am using telnet in the example above to connect to the Postal server), and authenticate with the credential created , I can submit an email, but Postal won't send it as noted (530).

So I am using the correct, and only, credential from the client. Is there something more in the Postal configuration that I need to do that the GUI doesn't do when I follow the step 3?

**Comment by stratacorps** [comment]
WAIT: Am I testing this wrong? I notice in the client.rb file the authenticated_domain shows as nil, can I not test the way I am doing and I've blown this all out of whack here? The command that is triggering the response is "find_authenticated_domain_from_headers" and since I'm in a telnet/command line session, there "be no" headers. Has this been it all along??

**Comment by willpower232** [comment]
That is referring to the headers of the message, not the headers of the connection. It has to happen at the end as the message can be drafted in any order so the headers of the message can be submitted or updated at any time.

Domains can exist at the organisation and mail server level but the credentials are only at the mail server level. This means the mail servers can use their parent organisations domains but not domains from other organisations or mail servers.

It might be that if you've added the same domain to multiple organisations that confuses things in the client.
