### ISSUE TITLE
SMTP Client does not handle empty RCPT TO

### ISSUE THREAD

**Issue by willpower232** [postalhq/postal#1281]
For whatever reason, one of our SMTP-based clients tried to do `RCPT TO:<>` and was met with an exception from the following code:

https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/lib/postal/smtp_server/client.rb#L254-L256

The problem is that `uname.split` will not work as `uname` isn't defined.

I have tried the following changes to no avail

![image](https://user-images.githubusercontent.com/1619102/104476470-2d764080-55b8-11eb-8d18-cca554cd1601.png)

Stack trace:

![image](https://user-images.githubusercontent.com/1619102/104476621-58f92b00-55b8-11eb-8bab-6ae010af74f7.png)

I don't know any ruby really so if someone could point me in the right direction, I would appreciate it.

**Comment by SilverCard** [comment]
I think you should null check the variable **rcpt_to** instead of **uname**.

**Comment by SilverCard** [comment]
Try to put the **return** keyword before the 550 error strings, maybe without it the code continues executing.

**Comment by rbozan** [comment]
Same as https://github.com/postalhq/postal/issues/1019

**Comment by willpower232** [comment]
Oh yeah, thanks for the link @rbozan. Fortunately, the process should be kept alive by Procodile but its not perfect.

Thanks for the tip @SilverCard, I'll try that later.

**Comment by willpower232** [comment]
closing in favour of #1019
