### ISSUE TITLE
Postal Messages Stuck In Queu

### ISSUE THREAD

**Issue by randysalars** [postalhq/postal#1284]
I'm having issues with messages stuck in the queue.  It was working fine until I did a reboot and now nothing will send.

![2021-01-19_18-09](https://user-images.githubusercontent.com/39238994/105113161-a4607d00-5a81-11eb-93d2-a87d0f3a55b4.png)

All services will run until I send and then the worker and requeuer will fail.

Have looked through previous issues and tried 

sudo postal stop
sudo rm -vf /tmp/postal/pids/*
sudo -u postal postal start  (or postal run which causes connection errors)

and

rabbitmqctl add_vhost /postal
rabbitmqctl add_user postal (password)
rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"

reboot, restart nginx, restart postal, and sudo rabbitmqctl start_app

cpu, disk space and memory look ok

Not that good at this stuff yet, but any help will be appreciated.

[smtp_sender.log](https://github.com/postalhq/postal/files/5839573/smtp_sender.log)

![2021-01-19_18-22](https://user-images.githubusercontent.com/39238994/105114197-a0355f00-5a83-11eb-9528-abd6bf606a02.png)

**Comment by willpower232** [comment]
It looks like all the affected messages are postal trying to send to itself so maybe you've somehow created an infinite loop?

**Comment by randysalars** [comment]
Hi;

I finally just ended reinstalling and got it working again.  thanks!

**Comment by willpower232** [comment]
Glad you figured it out, feel free to close the issue if you have no more questions
