### ISSUE TITLE
Mass resend of emails

### ISSUE THREAD

**Issue by modir** [postalhq/postal#1286]
We have the problem that one of the receiving mail servers blocked us because the spam filter accidentally thought that our emails are spam. The company has put our server in a white list. But new we have about 2500 emails that should be sent again. I find nowhere in the documentation how to do a mass resend. How would I have to do this? It would be great if the documentation would be updated with such examples.

**Comment by lokival** [comment]
I had to do this once, ended up using a spare laptop and a macro to click through each email -

[https://www.macrocreator.com/](url)

I agree with you a way to do it within postal would be better though

**Comment by willpower232** [comment]
If you're willing to get your hands dirty in the console, there are some ideas in #239 but the safer option would be to use the UI.

In the past, I have opened each affected message in a new tab and then clicked resend and Ctrl W to close the tab so I can do it faster :sweat_smile:

**Comment by modir** [comment]
@willpower232 I actually did it exactly as written there. I just thought it would be better to have a proper documentation about this.
