### ISSUE TITLE
Adding multiple domains to postal

### ISSUE THREAD

**Issue by seifouinbox** [postalhq/postal#1287]
hi i want to install multiple domains on my postal server everything is working fine for the main domain, but for the other ones i had issues with spf, MX and dikim record (i copied the values in the UI)
My question is: what are the modifications needed on the postal.yml in order to hoste multiple domains in postal ? 
and in case i wanted to use an ap address for the spf in the form of: "v=spf1 ip4:192.168.0.0 ~all" what are the configurations needed
thank you in advance

**Comment by willpower232** [comment]
See #1096
