### ISSUE TITLE
Ubuntu 16.04 LTS is approaching its "End of Standard Support" in April 2021

### ISSUE THREAD

**Issue by bluepuma77** [postalhq/postal#1288]
Just wanted to share that Ubuntu 16.04 LTS is approaching its ["End of Standard Support" in April 2021](https://wiki.ubuntu.com/Releases) - that's not too far away.

Not sure if that just means an update to the documentation where Ubuntu 16 in mentioned multiple times or if this has more serious implications to change over to Ubuntu 18 LTS or directly to Ubuntu 20 LTS.

While at it, it would be lovely to see a simple containerised environment for production :-)

**Comment by willpower232** [comment]
Good observation!

You can see that there has been an official [Dockerfile](https://github.com/postalhq/postal/blob/master/Dockerfile) added already which affirms support for Ruby 2.6 which means 18.04 is covered (and there has been an install script added recently for it) however others have reported problems with some features in Ruby 2.7 so 20.04 is not really an option IIRC.

I've been making use of the Dockerfile in local testing which has been a massive time saver compared to maintaining a real server for it but some more documentation on it would be nice.

**Comment by bluepuma77** [comment]
Great to see the Dockerfile. Now we only need a tiny bit of documentation ;-)

According to docs Postal needs MySQL/MariaDB, RabbitMQ, NodeJS and Nginx.

This could all be included in a Docker Compose file or a simple shell script.

**Comment by willpower232** [comment]
Quite, I've done some messing around with a docker-compose file over here https://github.com/SynergiTech/postal/blob/docker-experimentation/docker-compose.yml

This is mostly being discussed in #974

**Comment by donatid** [comment]
Hi,

I have Postal running on Ubuntu 18.04 Bionic (LTS), there is few more step to resolve some issue.
Please refer to #777 for more details.

Thank you
