### ISSUE TITLE
"postal run" does not work in container

### ISSUE THREAD

**Issue by bluepuma77** [postalhq/postal#1290]
I am trying to use postal in a container with the provided Dockerfile. Strangely enough `help`, `initialize-config` and `initialize` work, but `run` returns an error `/opt/postal/app/bin/postal: line 23: procodile: command not found`.

How to reproduce:
```
# run default mariadb
# ports are not exposed externally
# database files are stored on host to survive container upgrade
docker run --detach \
  --name postal-mariadb \
  --hostname postal-mariadb \
  --restart=unless-stopped \
  -v /data/postal/mariadb_datadir:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=my-secret-pw \
  -e MYSQL_DATABASE=postal \
  -e MYSQL_USER=postal \
  -e MYSQL_PASSWORD=postal \
  --log-opt max-size=100m --log-opt max-file=1000 \
  mariadb:10.5 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


# run default rabbitmq
# WARNING: port 15672 is exposed as login through nginx-proxy does not work
docker run --detach \
  --name postal-rabbit \
  --hostname postal-rabbit \
  --restart=unless-stopped \
  -p 15672:15672 \
  -e RABBITMQ_DEFAULT_VHOST=postal \
  -e RABBITMQ_DEFAULT_USER=postal \
  -e RABBITMQ_DEFAULT_PASS=postal \
  --log-opt max-size=100m --log-opt max-file=1000 \
  rabbitmq:3-management


# build postal container image
git clone https://github.com/postalhq/postal
cd postal
docker build -t postal:latest .


# create folder on host to persist config
mkdir -p /data/postal/config
chmod a+rw /data/postal/config

# start container and use shell for setup
docker run -it --rm \
  --hostname postal \
  -v /data/postal/config:/opt/postal/config \
  --link postal-mariadb:mariadb \
  --link postal-rabbit:rabbitmq \
  postal bash

# within container - initialize config
/opt/postal/app/bin/postal initialize-config

# within container - adapt config (db host: postal-mariadb, mq host: postal-rabbit, passwords: postal)
nano /opt/postal/config/postal.yml

# within container - initialize database
/opt/postal/app/bin/postal initialize

# within container - run in foreground
/opt/postal/app/bin/postal run


# ALTERNATIVE run detached container

# run container with postal in foreground
docker run --detach \
  --name postal \
  --hostname postal \
  -v /data/postal/config:/opt/postal/config \
  --restart=unless-stopped \
  --link postal-mariadb:mariadb \
  --link postal-rabbit:rabbitmq \
  postal /opt/postal/app/bin/postal start

# show logs
docker logs -f -t postal


# clean up
docker rm -fv postal postal-rabbit postal-mariadb
# rm -rf /data/postal
```

**Comment by bluepuma77** [comment]
By the way, does postal include a SMTP server / "Mail Transfer Agent" like Postfix or is this another dependency?

**Comment by bluepuma77** [comment]
Adding `RUN gem install procodile --no-doc` to Dockerfile leads to a different error.

```
postal@postal:~/app$ /opt/postal/app/bin/postal run
Error: Could not find Procfile in /opt/postal/app/Procfile
```

**Comment by willpower232** [comment]
This is missing as the Dockerfile is intended to run each process separately rather than all processes for easier deployment to kubernetes.

Postal has its own SMTP server code to handle SMTP connections directly.

https://github.com/adamcooke/procodile/blob/f2ad165f92273f947b70d5603abc6912eb671a8d/bin/procodile#L60

The error implies that the file exists but is empty or broken in some way so not sure whats gone wrong there. You can probably shell in to see what the contents are like inside the container.

**Comment by bluepuma77** [comment]
I checked and I think the Procfile is missing in the container because it's included in the [.dockerignore file](https://github.com/postalhq/postal/blob/master/.dockerignore).

If I don't use `postal run` in a container, how else would I start it? Several containers each with a line from the [Procfile](https://github.com/postalhq/postal/blob/master/Procfile)?

**Comment by willpower232** [comment]
Ah yes so it won't be in the build but you can mount it in from your commands if you want.

Correct, you probably only need one requeuer and cron but others could come in multiples depending on how you wanted to structure your setup.

**Comment by bluepuma77** [comment]
Slowly getting there, removed it from `.dockerignore`, now it starts.

I also had to change the rabbit lines to include a slash: `-e RABBITMQ_DEFAULT_VHOST=/postal`


Now I get another error. It's probably because the postal user does not have root privileges:

```
13:03:08 smtp.1             | Started with PID 20
13:03:10 smtp.1             | => rake aborted!
13:03:10 smtp.1             | =>
13:03:10 smtp.1             | => Errno::EACCES: Permission denied - bind(2) for "::" port 25
13:03:10 smtp.1             | =>
13:03:10 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `initialize'
13:03:10 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `open'
13:03:10 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `listen'
13:03:10 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:258:in `run'
13:03:10 smtp.1             | => /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
13:03:10 smtp.1             | => /usr/local/bundle/bin/bundle:23:in `load'
13:03:10 smtp.1             | => /usr/local/bundle/bin/bundle:23:in `<main>'
13:03:10 smtp.1             | =>
13:03:10 smtp.1             | => Tasks: TOP => postal:smtp_server
```

Is there an easy way to change the listening port? Outside Docker I can use 25 and just map it to a different internal port.

**Comment by bluepuma77** [comment]
Strange that the web server port is not shown in the logs ("listening on port xx").

`postal.yml` is missing the entry `web_server:` `port: 5000` (via [puma.rb](https://github.com/postalhq/postal/blob/master/config/puma.rb)), but the template uses `web:`?

**Comment by willpower232** [comment]
You can reference the defaults file for the full list of options
https://github.com/postalhq/postal/blob/master/config/postal.defaults.yml

**Comment by bluepuma77** [comment]
Maybe I just don't understand what the difference is.
`web:` vs `web_server:`
`smtp:` vs `smtp_server:`

**Comment by bluepuma77** [comment]
Will switch to [iRedMail dockerized](https://github.com/iredmail/dockerized) for now, to send some transactional emails.

**Comment by willpower232** [comment]
`web` is for the address of the Postal UI site

`web_server` is how Postal creates the unix socket for the Postal UI as you likely have some kind of proxy such as nginx involved.

`smtp` is for how Postal itself should send emails like password resets

`smtp_server` is for configuring the SMTP server that Postal can receive messages from if you aren't using the API or are receiving bounce backs.
