### ISSUE TITLE
How can I add List Unsubscribe header in Postal? Please Help!

### ISSUE THREAD

**Issue by fardeen0424** [postalhq/postal#1292]
Hello,

First of all a big salute to the developers and contributors

I wanted to add a list-unsubscribe header for my postal server

Please help me out with this.

Thanks!

Best Regards :-)
![Screenshot (22)](https://user-images.githubusercontent.com/56260586/106696345-8575f500-6602-11eb-81f7-cfc8ee7f6ced.png)

**Comment by Igcorreia** [comment]
This list that you want is per server? or for the entire POstal?

**Comment by willpower232** [comment]
Postal supports custom headers with your messages so if what you are sending from has support for the header, then there should be no problem.

**Comment by fardeen0424** [comment]
Thank You for your replies @willpower232 @Igcorreia  You are right I want to add list-unsubscribe header for entire postal. I.E every outgoing mail should contain list-unsubscribe header in it. Please help and guide me how can I do it, I'm not a tech person detailed explanation is appreciated.

Thanks, Brothers, @Igcorreia @willpower232 

Best Regards

**Comment by Igcorreia** [comment]
If I am not mistaken like @willpower232  said Postal accept custom headers: 
https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/api/controllers/send_api_controller.rb#L50

There is an issue or a pull request that has an explanation of how to add custom headers. I have used it and customized postal to my needs. (I did a quick search couldn't find it do :/)

**Comment by fardeen0424** [comment]
Thanks for your patience , but I have'nt understand because I have very less coding experience. Where can I add headers? I mean which file should I edit to add headers.

**Comment by fardeen0424** [comment]
Hello Brother @dragoangel I think you can answer my question. Please help me, Thanks in advance

**Comment by dragoangel** [comment]
@fardeen0424 to clarify: you need have unsubscribe link in your webservice first. postal is simply MTA, he not manage subscriptions links. If you send mail over smpt - then smtp sender need add this header in original email. if you send this as rest api described here https://krystal.github.io/postal-api/controllers/send/message.html then you know what to do ;)
