### ISSUE TITLE
Repo not found

### ISSUE THREAD

**Issue by burakdotto** [postalhq/postal#1294]
Quick install is not working anymore (https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1804.sh).
Repo "http://www.rabbitmq.com/debian" does not exist.

**Comment by willpower232** [comment]
It seems like they are migrating to a new hosting provider so it might be a little while until they get back up

https://twitter.com/RabbitMQ/status/1357617252795895808

**Comment by Josh-G** [comment]
Looks like they deprecated (and now removed) hosting their own apt repository: https://github.com/rabbitmq/rabbitmq-server/issues/1668#issuecomment-412305779
The recommendation is to now get it from package cloud (bintray is shutting down)

**Comment by abdallahtaleb** [comment]
Any idea when the repository issue would be solved?

**Comment by willpower232** [comment]
Unfortunately this will require you to do some configuring manually.

First you will need to manually edit /etc/apt/sources.list to remove the existing references to rabbitmq.com.

Then you can either run the official package cloud installer https://packagecloud.io/rabbitmq/rabbitmq-server/install or add the following line directly to your sources.list (this is for ubuntu 16.04) `deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ xenial main`

If you're editing your files manually, you will need the GPG key as well
`wget -O - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo apt-key add -`

I don't know if @adamcooke or @catphish have any preference or alternate provider they are using now.

**Comment by abdallahtaleb** [comment]
I was able to install by installing erlang and rabbitmq using below commands. 

wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -
echo "deb https://packages.erlang-solutions.com/ubuntu bionic contrib" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
sudo apt-get update
sudo apt-get install erlang

curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
sudo apt-get install rabbitmq-server 

I have done a full [guide](https://blog.h-educate.com/smtp-server-configuration/) if anyone is interested.

**Comment by JaiBansal24** [comment]
> 
> 
> I was able to install by installing erlang and rabbitmq using below commands.
> 
> wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -
> echo "deb https://packages.erlang-solutions.com/ubuntu bionic contrib" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
> sudo apt-get update
> sudo apt-get install erlang
> 
> curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
> sudo apt-get install rabbitmq-server
> 
> I have done a full [guide](https://blog.h-educate.com/smtp-server-configuration/) if anyone is interested.



> 
> 
> I was able to install by installing erlang and rabbitmq using below commands.
> 
> wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -
> echo "deb https://packages.erlang-solutions.com/ubuntu bionic contrib" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
> sudo apt-get update
> sudo apt-get install erlang
> 
> curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
> sudo apt-get install rabbitmq-server
> 
> I have done a full [guide](https://blog.h-educate.com/smtp-server-configuration/) if anyone is interested.

Commands 1 and 2 go ok.   On 3rd, "sudo apt-get update" ends with error below.   Same as when running original script.

_Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://packages.erlang-solutions.com/ubuntu/dists/bionic/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead._

**Comment by abdallahtaleb** [comment]
> > I was able to install by installing erlang and rabbitmq using below commands.
> > wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -
> > echo "deb https://packages.erlang-solutions.com/ubuntu bionic contrib" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
> > sudo apt-get update
> > sudo apt-get install erlang
> > curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
> > sudo apt-get install rabbitmq-server
> > I have done a full [guide](https://blog.h-educate.com/smtp-server-configuration/) if anyone is interested.
> 
> > I was able to install by installing erlang and rabbitmq using below commands.
> > wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -
> > echo "deb https://packages.erlang-solutions.com/ubuntu bionic contrib" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
> > sudo apt-get update
> > sudo apt-get install erlang
> > curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
> > sudo apt-get install rabbitmq-server
> > I have done a full [guide](https://blog.h-educate.com/smtp-server-configuration/) if anyone is interested.
> 
> Commands 1 and 2 go ok. On 3rd, "sudo apt-get update" ends with error below. Same as when running original script.
> 
> _Reading package lists... Done E: The method driver /usr/lib/apt/methods/https could not be found. N: Is the package apt-transport-https installed? E: Failed to fetch https://packages.erlang-solutions.com/ubuntu/dists/bionic/InRelease E: Some index files failed to download. They have been ignored, or old ones used instead._

This is because the repository is still there from the quick command.

**Comment by JaiBansal24** [comment]
Can someone please update the quick command ?   Most users are not too good with scripts or research work.   It was great till it would simply install with 1-2 commands.   Now I am having to delete 1-2 more VPS that I had formatted for a fresh install.

@ Adam, WillPower, others... update pls ??

**Comment by SaasX** [comment]
JaiBansal24 is right.
The quick installation is very comfortable and the step-by-step installation quite complicated for many people.

**Comment by biswajitnet** [comment]
I was able to install it this way on a Ubuntu Machine.. 

sudo apt-get install software-properties-common

sudo apt-add-repository ppa:brightbox/ruby-ng 

curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash

wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb

sudo dpkg -i erlang-solutions_2.0_all.deb

Once that is done . Go to cd /etc/apt/sources.list.d/

You should now see the rabbitmq_rabbitmq-server.list  Add the below Repos into the rabbitmq_rabbitmq-server.list

**deb http://archive.canonical.com/ubuntu bionic partner
deb-src http://archive.canonical.com/ubuntu bionic partner**

_You can do that by doing a_ **nano rabbitmq_rabbitmq-server.list** _and then paste the above lines on a  new line._ 

Find the [complete guide here](https://www.biswajitpradhan.com/postal-setup-2021-guide/)

**Comment by nhCoder** [comment]
I fixed the quick installation check this gist https://gist.github.com/nhCoder/e14b272137f146e6cc26eefdf72e017b

Usage

`curl https://gist.githubusercontent.com/nhCoder/e14b272137f146e6cc26eefdf72e017b/raw/6728a173eb8666afb52b457cc40812ef7badd8d4/install_postal.sh | sh`

**Comment by willpower232** [comment]
I've made a PR with the necessary changes but it has not been reviewed as yet

https://github.com/postalhq/postal/pull/1310
