### ISSUE TITLE
RabbitMQ Installation Failed

### ISSUE THREAD

**Issue by topmaker2019** [postalhq/postal#1301]
Hello, I use this command for install on Ubuntu 16.04:

curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh

and it's failed, please help:

Reading package lists... Done
E: The repository 'http://www.rabbitmq.com/debian testing Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by willpower232** [comment]
Please see #1294
