### ISSUE TITLE
SSL/TLS Supported in Postal?

### ISSUE THREAD

**Issue by uhlhosting** [postalhq/postal#1302]
It seems I have meet several issues with such errors:

`SSL_connect returned=1 errno=0 state=error: dh key too small`

This is when trying to use custom SMTP server with Zammada helpdesk software.

It fails same with BTCPayServer when using SSL, is there support and proper documentation how this can be achieved?

The main domain post.uhlhosting.ch has already SSL in place, just there is no other settings to explain the SSL on the SMTP side, or maybe I missed something.

**Comment by willpower232** [comment]
Have a look at #943 and #878 and reply again if they don't cover what you're seeing

**Comment by uhlhosting** [comment]
Im not sure i get this, i need to change freessl to another ssl? I have read these older tickets still does not count to me as documentation for this certain situation it seems.

**Comment by willpower232** [comment]
Unfortunately the way Postal creates keys doesn't create them long enough for newer SSL based software so you have to either downgrade your client software (not ideal) or do something like this https://github.com/postalhq/postal/issues/878#issuecomment-700769804

**Comment by uhlhosting** [comment]
@willpower232 any plans to add this into a PR maybe?

**Comment by willpower232** [comment]
re reading my past comments, I see this is a ruby 2.3 problem so I don't think this will be changed in the code because it would be easier to host on a newer ruby version now.

**Comment by uhlhosting** [comment]
So this means I have to upgrade my local ruby?

**Comment by willpower232** [comment]
or change your code, yes

**Comment by uhlhosting** [comment]
> re reading my past comments, I see this is a ruby 2.3 problem so I don't think this will be changed in the code because it would be easier to host on a newer ruby version now.

When you mentioned a newer ruby version I did not knew this will not work with latest ruby version 3.0

```
Installing dependencies
/opt/postal/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /opt/postal/app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
        from /opt/postal/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
        from /opt/postal/.rbenv/versions/3.0.0/bin/bundle:23:in `<main>'
Failed to run: postal bundle /opt/postal/vendor/bundle
postal@post:/etc/ssl$ bundle update --bundler
```

And this goes on by:

```
postal@post:~/app$ bundle update --bundler
Fetching gem metadata from https://rubygems.org/............
Fetching https://github.com/mikel/mail.git
minitest-5.14.1 requires ruby version ~> 2.2, which is incompatible with the
current version, ruby 3.0.0p0
postal@post:~/app$ 
```

Please advise.

**Comment by willpower232** [comment]
Ah I didn't know there was a 3! I think the latest fully-supported version is 2.6.

**Comment by uhlhosting** [comment]
> Ah I didn't know there was a 3! I think the latest fully-supported version is 2.6.

Can you make sure of that? Before I bump the version again. It is weird, I am now on 2.7 and I got the above errors, while version 3 is not working at all.

**Comment by uhlhosting** [comment]
A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host post.uhlhosting.ch :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number)

Got this with ruby 2.7, so this is out of question a fix. I will now try the ruby editing. I still do not get It why this is not fixed on main packages, when clearly the issue is present.

**Comment by willpower232** [comment]
That error seems to be related to a missing or not enough permission for an SSL certificate, have a look at #366 

The official dockerfile uses ruby 2.6 so that is the best option for now.

**Comment by uhlhosting** [comment]
Well I think the issue is somewhere else, first of all these SSL should not go in postfix or such services? Is there a documentation on how to secure the mail server, not the Nginx proxy domain? Aren't a difference between the two. Hence many apps have the ssl on their level, such as mysql server also supports ssl, alto many don't us It does. I think this could be the case or? Because such ssl errors, if were to be on server, Nginx would not allow them unnoticed. Then we need to know if the apps are limited with the free Certs like lets encrypt.

**Comment by willpower232** [comment]
If you have a look specifically at https://github.com/postalhq/postal/issues/366#issuecomment-334193135 then you'll see how a certificate can be configured for the SMTP connection specifically. Postal manages its own SMTP connection without any other software so it is directly responsible for that.

**Comment by uhlhosting** [comment]
In this case I supposed that is not handled by the Lets encrypt ssl by default unless specified. Why cant it take the same variables from the domain SSL, hence its same domain in our case smtp and web.

**Comment by uhlhosting** [comment]
smtp_server:
  tls_enabled: true
  tls_certificate_path: "/opt/postal/certificates/post.uhlhosting.ch/fullchain.$
  tls_private_key_path: "/opt/postal/certificates/post.uhlhosting.ch/privkey.pe$
  log_connect: true

The certs are in place.


I got this on later on smtp settings, is this correct usage? I think some issue might be here:

```
smtp:
  host: post.uhlhosting.ch
  port: 25
  username: username
  password: password
  from_name: "Postal"
  from_address: "postal@uhlhosting.ch"
```

**Comment by willpower232** [comment]
The `smtp:` section is for when Postal needs to send emails itself, i.e. password resets.

You can use the same certificate for web and SMTP but you will have to manually tell both nginx and Postal what the domain name is.

Does the Postal user definitely have access to that directory?

**Comment by uhlhosting** [comment]
/opt/postal/certificates/ meaning this one? Well its inside postal should have, il double check.
