### ISSUE TITLE
How to disabled logs sent via SMTP?

### ISSUE THREAD

**Issue by updates5839** [postalhq/postal#1303]
How to disabled logs sent via SMTP?

It's very urgent, don't need to log or view message anyhow.

Kindly help :)

Thanks

**Comment by willpower232** [comment]
Is your answer in #1222 or do you mean something else?

**Comment by updates5839** [comment]
Thanks for your reply. I actually meant 0 logs retention, basically I in each setting field I have set 0 but still Postal stores date for a day. If anything can be done? Please help. thanks

**Comment by willpower232** [comment]
As you can see in #1222 this isn't currently possible and I don't believe anyone has made any PR to remove the logging to file.

**Comment by updates5839** [comment]
If there is any simple option to disable log (what's sent & when) in future, that will be great help!
