### ISSUE TITLE
hello, i have the same problem, installation went good on ubuntu 18 server hosted at Digitalocean, but after creating organization, i can't build  a mail server, the green button just keeps showing that it's loading, but nothing happens. Thanks for your time

### ISSUE THREAD

**Issue by ahmedkuah** [postalhq/postal#1304]
hello, i have the same problem, installation went good on ubuntu 18 server hosted at Digitalocean, but after creating organization, i can't build  a mail server, the green button just keeps showing that it's loading, but nothing happens. Thanks for your time

_Originally posted by @JudgeAdil in https://github.com/postalhq/postal/issues/1089#issuecomment-722371491_

**Comment by willpower232** [comment]
@JudgeAdil will need to check their log files to see what the problem is.

**Comment by layen67** [comment]
Hello, recreate user for rabbit ssh console do, after do this every is ok

#
# RabbitMQ
#
rabbitmqctl add_vhost /postal;
rabbitmqctl add_user postal YOUR_PASSWORD;
rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*";

**Comment by limenleap** [comment]
I am also facing the exact same problem! When I try to create a new server, the button keeps showing some activity but nothing happens. I would love to see the error log for postal -- may I know where is that located?

**Comment by willpower232** [comment]
@limenleap if you select the response in the network tab, it should open up to receive more detail and one of the items you can look at is Response which may include some detail as to the exception that occurred.

Log files are located at `/opt/postal/log/`

**Comment by ebanodev** [comment]
I have the same problem. 
First the problem was rabbitmq-server authentication. But I fixed it. 
So, now the rabbitmq-server is authenticating and the postal status is ok. But POST returns 500 (internal server error).

**The worker.log shows:**
> [worker.1:12136] [2021-07-07T03:47:39.007] WARN -- : [SZSIBYOK1B] /opt/postal/app/lib/postal/worker.rb:55:in `receive_job'
> [worker.1:12136] [2021-07-07T03:47:39.007] WARN -- : [SZSIBYOK1B] /opt/postal/app/lib/postal/worker.rb:88:in `block in join_queue'
> [worker.1:12136] [2021-07-07T03:47:39.007] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/consumer.rb:56:in `call'
> [worker.1:12136] [2021-07-07T03:47:39.008] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/channel.rb:1768:in `block in handle_frameset'
> [worker.1:12136] [2021-07-07T03:47:39.008] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
> [worker.1:12136] [2021-07-07T03:47:39.008] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/consumer_work_pool.rb:103:in `loop'
> [worker.1:12136] [2021-07-07T03:47:39.008] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/consumer_work_pool.rb:103:in `block in run_loop'
> [worker.1:12136] [2021-07-07T03:47:39.008] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/consumer_work_pool.rb:102:in `catch'
> [worker.1:12136] [2021-07-07T03:47:39.008] WARN -- : [SZSIBYOK1B] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.14.4/lib/ bunny/consumer_work_pool.rb:102:in `run_loop'
> [worker.1:12136] [2021-07-07T03:47:39.008] INFO -- : [SZSIBYOK1B] Finished processing SendNotificationsJob job in 5.002435213s
> [worker.1:12136] [2021-07-07T03:48:34.009] INFO -- : [G16G8H48JA] Started processing RequeueWebhooksJob job
> [worker.1:12136] [2021-07-07T03:48:34.011] INFO -- : [HWFB08VGUA] Started processing SendNotificationsJob job
> [worker.1:12136] [2021-07-07T03:48:34.070] INFO -- : [G16G8H48JA] Finished processing RequeueWebhooksJob job in 0.060490655s
> [worker.1:12136] [2021-07-07T03:48:39.012] WARN -- : [HWFB08VGUA] ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5,000 seconds (waited 5,000 seconds); all pooled connections were in use
> [worker.1:12136] [2021-07-07T03:48:39.013] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:201:in `block in wait_poll'
> [worker.1:12136] [2021-07-07T03:48:39.013] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:190:in `loop'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:190:in `wait_poll'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:151:in `internal_poll'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:277:in `internal_poll'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:145:in `block in poll'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:155:in `synchronize'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:145:in `poll'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:818:in `acquire_connection'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
> [worker.1:12136] [2021-07-07T03:48:39.014] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/ active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
> [worker.1:12136] [2021-07-07T03:48:39.015] WARN -- : [HWFB08VGUA] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib 

**The smtp_server.log shows:**

> 
> tp.1:12142] [2021-07-07T03:26:32.527] DEBUG -- : [FBBPJL] => 250 AUTH CRAM-MD5 PLAIN LOGIN
> [smtp.1:12142] [2021-07-07T03:26:33.041] DEBUG -- : [FBBPJL] <= Rset
> [smtp.1:12142] [2021-07-07T03:26:33.042] DEBUG -- : [FBBPJL] => 250 OK
> [smtp.1:12142] [2021-07-07T03:26:33.280] DEBUG -- : [FBBPJL] <= Mail from:<spameri@tiscali.it>
> [smtp.1:12142] [2021-07-07T03:26:33.286] DEBUG -- : [FBBPJL] => 250 OK
> [smtp.1:12142] [2021-07-07T03:26:33.524] DEBUG -- : [FBBPJL] <= RCPT to:<spameri@tiscali.it>
> [smtp.1:12142] [2021-07-07T03:27:51.486] DEBUG -- : [FBBPJL] => 530 Authentication required
> [smtp.1:12142] [2021-07-07T03:27:51.725] DEBUG -- : [FBBPJL] <= Quit
> [smtp.1:12142] [2021-07-07T03:27:51.726] DEBUG -- : [FBBPJL] => 221 Closing Connection
> [smtp.1:12142] [2021-07-07T03:27:51.726] DEBUG -- : [FBBPJL]    Connection closed

**The rails.log shows:**
ps: That log is not at the same time. But I repeated the build server procedure to result in this log. 

> web.1:12134] [2021-07-07T03:54:18.207] INFO -- : Started POST "/org/amc/servers" for 177.41.46.1 at 2021-07-07 03:54:18 -0300
> [web.1:12134] [2021-07-07T03:54:18.251] INFO -- : Processing by ServersController#create as JSON
> [web.1:12134] [2021-07-07T03:54:18.251] INFO -- :   Parameters: {"utf8"=>"✓", "server"=>{"name"=>"Aulamagna-server", "permalink"=>"", "mode"=>"Live"}, "commit"=>"Build server", "org_permalink"=>"amc"}
> [web.1:12134] [2021-07-07T03:54:23.549] INFO -- : Completed 500 Internal Server Error in 5293ms (ActiveRecord: 800.3ms)
> [web.1:12134] [2021-07-07T03:54:24.254] FATAL -- :
> [web.1:12134] [2021-07-07T03:54:24.255] FATAL -- : Mysql2::Error::ConnectionError (Access denied for user 'postaluser'@'localhost' to database 'postal-server-37'):
> [web.1:12134] [2021-07-07T03:54:24.255] FATAL -- :
> [web.1:12134] [2021-07-07T03:54:24.260] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'
**> lib/postal/message_db/database.rb:311:in `block in query'
> lib/postal/message_db/mysql.rb:20:in `client'
> lib/postal/message_db/database.rb:342:in `with_mysql'
> lib/postal/message_db/database.rb:310:in `query'
> lib/postal/message_db/provisioner.rb:46:in `drop'
> lib/postal/message_db/provisioner.rb:13:in `provision'
> app/models/server.rb:86:in `block in <class:Server>'
> app/controllers/servers_controller.rb:36:in `create'**

**Comment by ebanodev** [comment]
Because of rails.log, I droped the mysql user and create a new one. Now its working.
