### ISSUE TITLE
Postal not respecting the sending attempt maximum of 18

### ISSUE THREAD

**Issue by user456219** [postalhq/postal#1307]
Hello friends,

I get the following behavior when sending to a known bounce email due to the domain not existing, such as "another@nosuchdomain.comxxx".

Postal tries its default 18 attempts, but then blasts through the 18 maximum, and continues trying to send the message forever...

(Read from bottom up - New data at top)

....continues forever....
Error - An internal error occurred while sending this message. This message will be retried automatically. If this persists, contact support for assistance. FrozenError: can't modify frozen String: ""
Hard fail - Maximum number of delivery attempts (20) has been reached. Added another@nosuchdomain.comxxx to suppression list because delivery has failed 20 times.
Error - An internal error occurred while sending this message. This message will be retried automatically. If this persists, contact support for assistance. FrozenError: can't modify frozen String: ""
Hard fail - Maximum number of delivery attempts (19) has been reached. Added another@nosuchdomain.comxxx to suppression list because delivery has failed 19 times.
Error - An internal error occurred while sending this message. This message will be retried automatically. If this persists, contact support for assistance. FrozenError: can't modify frozen String: ""
Hard fail - Maximum number of delivery attempts (18) has been reached. Added another@nosuchdomain.comxxx to suppression list because delivery has failed 18 times.
... 10 more Soft fails for a toal of 18 Soft fails
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx
Soft fail - No SMTP servers were available for nosuchdomain.comxxx. Tried nosuchdomain.comxxx

If I set   
maximum_delivery_attempts: 2
the same pattern happens, starting at 2.  Images attached.

![p2](https://user-images.githubusercontent.com/79667371/109215413-2169cb00-7781-11eb-89f3-18ed99a1179e.png)
![p1](https://user-images.githubusercontent.com/79667371/109215415-2169cb00-7781-11eb-9604-3f7df714d5f7.png)
Suggestions?

**Comment by willpower232** [comment]
If the email address was added to the suppression list and sending carried on anyway then either it failed to be added to the list or something else went wrong like you're running multiple Postal installations weirdly. Can you see it in your suppression list?

**Comment by user456219** [comment]
Hi Will,

I can see the email in the suppression list and only 1 Postal install on this new server.  Do you have any additional ideas?

Thanks

**Comment by willpower232** [comment]
What is the output if you run `postal status`?

Also what are the technical details for the error entries in your screenshot?

**Comment by user456219** [comment]
Will,

Thanks I found a solution to the problem.  Here it is:

sudo apt remove postal
sudo apt install postfix

Works like a charm.  Thanks again!

**Comment by willpower232** [comment]
No need to be a jerk if you aren't going to help me help you

**Comment by user456219** [comment]
Sorry, bad joke.  Seriously, thank you for the effort.

**Comment by willpower232** [comment]
no hard feelings, Postal doesn't fit every use case

**Comment by jeffreyzant** [comment]
I've been seeing the same issue setting up Postal from scratch. 

Solution seems to add .dup to line 53 of the app/lib/postal/message_db/delivery.db:
`:output => self.output.to_s.dup.force_encoding('UTF-8').scrub,`

Not sure why this issue happens on newer setups. Never had any problems on our old server setup.

```
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] Internal error: FrozenError: can't modify frozen String: ""
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/message_db/delivery.rb:53:in `force_encoding'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/message_db/delivery.rb:53:in `webhook_hash'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/message_db/delivery.rb:44:in `send_webhooks'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/message_db/delivery.rb:11:in `create'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/message_db/message.rb:128:in `create_delivery'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/app/jobs/unqueue_message_job.rb:75:in `block in perform'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/app/jobs/unqueue_message_job.rb:30:in `each'
[worker.163:4060854] [2021-04-19T14:51:11.627] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/app/jobs/unqueue_message_job.rb:30:in `perform'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/worker.rb:55:in `receive_job'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/app/lib/postal/worker.rb:88:in `block in join_queue'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer.rb:56:in `call'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/channel.rb:1768:in `block in handle_frameset'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `loop'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `catch'
[worker.163:4060854] [2021-04-19T14:51:11.628] INFO -- : [TJYHQHZL3A] [19::10 18053919] /opt/postal/vendor/bundle/ruby/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `run_loop'
```

**Comment by jeffreyzant** [comment]
Guessing that if it should be added here it should be added to app/lib/postal/app_logger.rb aswell on line 19.
