### ISSUE TITLE
smtp_server.log stores credentials data in base64 plaintext

### ISSUE THREAD

**Issue by dragoangel** [postalhq/postal#1308]
For what a point write credentials in logs all the time by default in "production" without option to turn this off? Key in all logs lines in this file says: "DEBUG", such data must be optional and not be logged by default.

**Comment by willpower232** [comment]
There have also been numerous instances of people pasting their credentials in log file excerpts in these issues so it would be nice to save people from themselves.

**Comment by dragoangel** [comment]
Obviously because their credentials are base64 encoded and they even don't know that gudyhddg== can be password

**Comment by dragoangel** [comment]
And for me thos more 🔐 security issue then future

**Comment by dragoangel** [comment]
@willpower232 can you please set security tag?

**Comment by adamcooke** [comment]
This is now resolved in https://github.com/postalhq/postal/commit/fcb63616e1ce578d7d4fd1c96ddc4ee0f7a71534
