### ISSUE TITLE
Is anyone working on a new quick install?

### ISSUE THREAD

**Issue by SaasX** [postalhq/postal#1309]
I saw that several posts were open on the problem with the quick installation.

Is the problem being resolved or is it over? (manual only)

**Comment by willpower232** [comment]
#1294 needs resolving, if you have the time and knowledge to submit a PR then go ahead.

**Comment by SaasX** [comment]
I am not an IT professional, but a marketing manager. 
I do think that a lot of people are annoyed by the fact that the quick install is down.
The project must continue to be simple to remain active with many people.

**Comment by nhCoder** [comment]
I fixed the quick installation check this gist https://gist.github.com/nhCoder/e14b272137f146e6cc26eefdf72e017b

Usage 

`curl https://gist.githubusercontent.com/nhCoder/e14b272137f146e6cc26eefdf72e017b/raw/6728a173eb8666afb52b457cc40812ef7badd8d4/install_postal.sh | sh`

**Comment by willpower232** [comment]
I've made a PR with the necessary changes but it has not been reviewed as yet

https://github.com/postalhq/postal/pull/1310
