### ISSUE TITLE
problem postal smtp connection

### ISSUE THREAD

**Issue by Matthew3111** [postalhq/postal#1311]
Hi !
I have made my own postal smtp server, using an SSH client : Putty  , all was right and Postal Domain Configuration also I was able to connect to my postal, and now i'm not able to connect (i don't know why and where comes from the problem), i have got a blank page with ERR_CONNECTION_REFUSED   ?
What can I do to try to reconnect to my server ? 
Thanks

**Comment by willpower232** [comment]
If you're getting this in your browser then you can try `postal status` from the terminal to confirm that Postal is running.

If it is then you may need to check nginx or your firewall.
