### ISSUE TITLE
Postal IP rotation

### ISSUE THREAD

**Issue by mjml1982** [postalhq/postal#1313]
Hi, 

When we do IP rotation, do we need to add additional IP's in the postal configuration file in order to work them correctly? I have done the rest of the things but postal not sending emails from additional IP's.

Thanks.

**Comment by willpower232** [comment]
Are you talking about IP Pools? https://github.com/postalhq/postal/wiki/Configuring-IP-Pools

**Comment by mjml1982** [comment]
Yes, i have followed this and created IP pool, i have also created the mailserver after adding the IP's, but postal is sending emails only from main IP not addition IP's.

Thanks


________________________________

**Comment by mjml1982** [comment]
@willpower232 brother, really sorry for the inconvenience poor guy didn't add IPs to the network, now it's working like charm!

**Comment by willpower232** [comment]
Not a problem, glad you figured it out. Feel free to close if there are no other problems.

**Comment by bakgaard** [comment]
@mjml1982 - how did you add these? 
Can you give me an explanation, or a link to a guide?
