### ISSUE TITLE
Can't Receive Incoming Emails

### ISSUE THREAD

**Issue by Software-Wolf** [postalhq/postal#1314]
Hello, postal community. :) I recently set up a new postal server for some personal projects, and while it can send emails perfectly, there is one issue. When I send emails to it, it does not receive them. It does not even show them as a "fail" or a "bounce." Postal has no idea that I even sent an email to it. According to postal, I did set up my domain correctly. I think I set up routing correctly, but in case I didn't if someone could give me a good explanation of how to set up routing. I click the "how to receive emails" thing, but it did not help. If someone could please show me how to set up routing it would be a huge help.

![image](https://user-images.githubusercontent.com/72639865/111236373-ee606d80-85af-11eb-9811-1524cac7ef73.png)

**Comment by willpower232** [comment]
You could try using `telnet postal.whatever.com 25` to see if you are able to connect to it from a different server.

I think you should always see the incoming message in Postal even if you don't have routes set up.

**Comment by Software-Wolf** [comment]
I can't connect to it. But I can send mail from it.. Honestly, at this point, I don't care about the privacy of the domain. So here is an image below of my attempts to connect to it. **The domain is xsendmail.ml** It is just so weird that I can send emails but not receive them.
![image](https://user-images.githubusercontent.com/72639865/111393274-a9067380-8675-11eb-8a49-53130e4c660f.png)

**Comment by willpower232** [comment]
It doesn't look like there are any DNS records set up for postal.xsendmail.ml which is why you're getting that message.

Whilst you can configure Postal with any domains you like and it will tell you whether or not your clients domain is set up right, it does not verify that the configuration you gave it is correct.

Does that make sense?

**Comment by Software-Wolf** [comment]
I am still a bit confused. I set up all the records like it asked for. If it is a matter of fixing DNS records can you tell me what to add or remove? Or is it more complicated than that?

![image](https://user-images.githubusercontent.com/72639865/111729490-6f2b9d80-882c-11eb-8d55-16c444e7d6bf.png)

**Comment by willpower232** [comment]
You set up the records it asked for yes but the records that point at the server do not exist so whoever set up the server did not create the records it was configured with.

Have a look at https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

**Comment by Software-Wolf** [comment]
I understand now. I will try my best to fix it. Thank you for your help.
