### ISSUE TITLE
Unable to install Postal on any VPS

### ISSUE THREAD

**Issue by pranavmishra** [postalhq/postal#1317]
Hi,

I tried installing Postal on multiple vps but all had a same issue:
The command I used was: 

**curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh**

The issue I got:
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:2 http://mirrors.digitalocean.com/ubuntu xenial InRelease [247 kB]
Hit:3 http://mirrors.digitalocean.com/ubuntu xenial-updates InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu xenial-backports InRelease
Hit:6 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu xenial InRelease
Hit:7 http://mirrors.coreix.net/mariadb/repo/10.1/ubuntu xenial InRelease
Ign:5 https://www.rabbitmq.com/debian testing InRelease
Err:8 https://www.rabbitmq.com/debian testing Release
  404  OK
Reading package lists... Done
E: The repository 'http://www.rabbitmq.com/debian testing Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by willpower232** [comment]
Please see #1294 and #1310
