### ISSUE TITLE
Does postal by default enables spamassassian and Clam AV or do we have to manually enable it in postal.yml file ???

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1318]
Does postal by default enables SpamAssassin and Clam AV or do we have to manually enable it in the postal.yml file ???

If Yes, then can anyone guide me on this

**Comment by willpower232** [comment]
You can see more about this here https://github.com/postalhq/postal/wiki/Spam-&-Virus-Checking

**Comment by gitaayush** [comment]
@willpower232  thank you !! Also I have postal running on an public IP address, so will i have to add the public ip on the host section or leave it as 127.0.0.1

spamd:
  enabled: true
  host: 127.0.0.1 or public ip ?????? confused.
  port: 783

**Comment by willpower232** [comment]
it is likely to be 127.0.0.1 unless you are using spamassassin from a different server

**Comment by gitaayush** [comment]
Also can i install clamav and Amavis on postal ?? If yes how, and can you please guide me on this.. I have successfully installed spamassassin thanks to you.. Now going for clamav and amavis

**Comment by willpower232** [comment]
You can enable clamav if you wish however judging by #1293 I'm not sure this does much.

Postal currently has no integration with amavis.

**Comment by gitaayush** [comment]
Thank you @willpower232 I will look into it
