### ISSUE TITLE
DNS ISSUES - Postal unable to verify SPF and DKIM records.

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1320]
I am having trouble with postal unable to verify the spf and dkim records for the domain. I have updated all the necessary dns records required for the postal and have made the necessary changes highlighted on postal for dummies dns section. 

Mx tool box, and other sites verifies the spf and dkim records, but postal is not able to verify the domain.  My dns record in postal.yml file is as follows; (Note mycompany is set for privacy purpose)

dns:

  mx_records:
    - relay.mycompany.com.np
  smtp_server_hostname: relay.mycompany.com.np
  spf_include: spf.relay.mycompany.com.np
  return_path: rp.relay.mycompany.com.np
  route_domain: routes.relay.mycompany.com.np
  track_domain: track.relay.mycompany.com.np

My spf record generated by postal :  v=spf1 a mx include:spf.relay.mycompanycom.np ~all
I have added the above spf record on my nameserver along with the record: spf.relay IN TXT v=spf1 ip4:MyPublicIp ~all

Only postal is unable to resolve my domain. Its says No SPF record exist for this domain and same for the DKIM as well.
Pleas guide me on this. I have applied every solution possible from my end, changed the dns record 100 times but didn't solve the issues.

**Comment by willpower232** [comment]
If you use https://whatsmydns.net can you confirm your DNS record value is correct around the world?

**Comment by gitaayush** [comment]
@willpower232 the A record for my domain is resolved to corresponding to public ip address. Its correct around the world. The MX record, TXT record are also correct.

**Comment by willpower232** [comment]
Good to know, so the problem must be with how your server looks up records.

You can use the `dig any spf.relay.mycompany.com.np` command on your server to see if it is able to look up the records.

If it can't then it might be worth asking for help from your server provider.

**Comment by gitaayush** [comment]
@willpower232  I have use the dig command for my domain and it returning the result as expected. Also when i issue the command  "dig mydomain.com.np +trace", the trace result shows the correct **Nameserver** where my dns record are hosted.
So to conclude, my postal server is able to dig the dns record, however it is not able to resolve the issues via postal GUI

**Comment by gitaayush** [comment]
@willpower232 The issues has been resolved. Dont know what resolved the issues, but thank you for your support.
Closing the issues now.
