### ISSUE TITLE
Server is unable to send email from external app

### ISSUE THREAD

**Issue by pranavmishra** [postalhq/postal#1321]
Hi,

So I have installed postal & configured everything properly & there is a success in sending test emails from postal itself.

But,

When I tried sending email from an external app (smtper.net) 

I gest an error 

**SMTP send error
The operation has timed out.**

**Comment by willpower232** [comment]
A good first step would be using telnet from your local computer to verify that your Postal server port is open and responding

`telnet your.postal.server.whatever 25`

**Comment by pranavmishra** [comment]
The server had issues in it - bought a new server on Contabo & ran a command..

( curl https://gist.githubusercontent.com/nhCoder/e14b272137f146e6cc26eefdf72e017b/raw/6728a173eb8666afb52b457cc40812ef7badd8d4/install_postal.sh | sh ) as per https://gist.github.com/nhCoder/e14b272137f146e6cc26eefdf72e017b

But I got this.. 

Fetching gem metadata from https://rubygems.org/............
Fetching https://github.com/mikel/mail.git
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that
means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to
install.

**Comment by willpower232** [comment]
It looks like they changed the license and pulled the package for some reason, will have to keep an eye on https://github.com/minad/mimemagic/issues/97 to see what happens.
