### ISSUE TITLE
Unable to receive incoming mails

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1322]
Hello, I am able to send emails from my postal but I am not able to receive the reply mails (Incoming Mails).
postal gives the following error:

Connection reset by peer - SSL_connect

Support Ref: PBFAPVPN

**Comment by willpower232** [comment]
Is this the error you're seeing in Postal or on another service?

**Comment by gitaayush** [comment]
The error is seen on the postal. When I try to send an email from anotherdomain.com to mydomain.com through postal, the ssl_connect error is seen. The mydomain.com has MX record pointed to my postal mail server. So mydomain will send and receive the emails via postal mailing server. However I am able to send email via postal mail server, but cany receive the reply or incoming mails.

**Comment by willpower232** [comment]
Have you enabled the SMTP TLS settings?

https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/config/postal.defaults.yml#L75-L77

You can verify this from your terminal `openssl s_client -connect yourpostalserver.whatever.com:25 -starttls smtp`

**Comment by gitaayush** [comment]
@willpower232  
 
here are my postal settings for SMTP Tls
smtp:
 
  host: mydomain.com.np
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

smtp_server:

  port: 25
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/mydomain.com.np/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/mydomain.com.np/privkey.pem
  tls_ciphers: TLSv1_1
  ssl_version: TLSv1_1
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14

**Comment by willpower232** [comment]
`smtp` is for allowing Postal to send its own emails like password resets so isn't part of this problem.

It looks like you have everything correct but I'm not sure about `tls_ciphers: TLSv1_1`, if you set this as blank and restart Postal, does that fix the problem?

**Comment by gitaayush** [comment]
Suppose I have an email address admin@mydomain.com, how will I configure the address endpoint and routing such that the mail received from any address will be received on admin@mydomain.com. What will be on the Name field on below Image, also i have configured the address point to be admin@mydomain.com

![image](https://user-images.githubusercontent.com/47238161/112660071-25226780-8e7d-11eb-96ed-1fa2446bb625.png)

**Comment by willpower232** [comment]
The endpoint will need to be either an email address (like your gmail) or another system that can handle email (like some custom code).

If you want an inbox for admin@mydomain.com then that is not Postals job.

**Comment by gitaayush** [comment]
@willpower232 I have my domain setup in Cpanel, so I am using Roundcube as my email client. I am sending emails from roundcube with email address admin@mydomain.com via mail server = postal.  When I send emails from admin@mydomain.com from roundcube, i want all the replies/incoming emails to admin@mydomain.com.  Is it possible ?

Also are there any specific firewall rules for postal. For now i have allowed port 443,25,465,5672.

**Comment by willpower232** [comment]
You should be able to set the reply address to your email at some point, I'm not sure how Roundcube works. The reply address is different to the return path address.

You only need to open 80 and 443 for the web UI and 25 for SMTP. All other traffic would be internal to the server so would not be a concern for your firewall.
