### ISSUE TITLE
Is there any option for adding unsubscribe header / URL on the outgoing emails ?

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1323]
Is there any option for adding unsubscribe header / URL on the outgoing emails  through postal ?

**Comment by gitaayush** [comment]
When I test the email from the mail-tester.com it gives following error:

Your message does not contain a List-Unsubscribe header
The List-Unsubscribe header is required if you send mass emails, it enables the user to easily unsubscribe from your mailing list.

**Comment by willpower232** [comment]
If you have an unsubscribe URL for your application, you can supply this when you send the message via Postal.

Have a look at #1292

**Comment by gitaayush** [comment]
Also, now the mail tester is showing your mail is not signed with DKIM. I have added the necessary DKIM records provided by the postal during domain creation and postal is also able to resolve the DKIM records. What could be the reason why mail-tester.com is showing "Your message is not signed with DKIM" error ???

The score for my test is 9/10 on mail tester, the two parameters affecting my perfect score are
1) The DKIM error and
2)  Your message does not contain a List-Unsubscribe header error

Please guide me on the DKIM error and also I am confused on the Unsubscribe solution.

**Comment by omueller** [comment]
@gitaayush to be able to help at all, the corresponding mail-tester.com result url would help, or at least a copy of the relevant part for DKIM (including records, etc.).     For the List-Unsubscribe, https://github.com/postalhq/postal/issues/1292 ist most probably still the way to go.  Good luck!

**Comment by gitaayush** [comment]
@omueller Please find below the snapshot for the output result by mail tester

![image](https://user-images.githubusercontent.com/47238161/112693142-39c82500-8ea8-11eb-9746-dd6e96602f60.png)

![image](https://user-images.githubusercontent.com/47238161/112693203-54020300-8ea8-11eb-98db-1721b267fe9d.png)

**Comment by omueller** [comment]
@gitaayush I meant the real https://www.mail-tester.com/test-xxxyyyzzzz link of your test (it will expire within 7 days), the screenshot is not really displaying anything useful unfortunately.    And have you tested the DNS setup in Postal ? 
(https://postal.example.org/org/*yourorg*/servers/*yourserver*/domains).

**Comment by willpower232** [comment]
Yes this sounds like the DNS record is not present or is invalid somehow.

Regarding the header, you will need to add that to the message yourself in whatever system you are using to send messages to Postal.

**Comment by gitaayush** [comment]
Thank you, the issues is resolved not. It was indeed the DNS record problem.
