### ISSUE TITLE
Your bundle is lcoked to mimematic

### ISSUE THREAD

**Issue by mjml1982** [postalhq/postal#1324]
Hello,

When I run the following command `postal bundle /opt/postal/vendor/bundle` getting the following error messages, any hlep would be highly appriciated!

```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.
```
Thanks.

**Comment by Code-with-Shah** [comment]
I had same issue today.
Don't know what to do?

**Comment by willpower232** [comment]
This is now a known problem and several Ruby packages will be having difficulties. We have to wait until something gets resolved I'm afraid

See also https://github.com/postalhq/postal/issues/1321#issuecomment-806498859

**Comment by Code-with-Shah** [comment]
But What if I need this resolve today?

**Comment by willpower232** [comment]
Until @adamcooke or someone commits a fix and creates a new release on their server, I don't think anything can be done. You might be able to change the version of that package yourself but that might complicate things long term depending on your setup.

**Comment by wh4u** [comment]
this is about the ruby-mimemagic package?

root@smtp:~# aptitude search mimemagic
i   ruby-mimemagic                                                                                  - fast MIME detection by extension or content

**Comment by Code-with-Shah** [comment]
> this is about the ruby-mimemagic package?
> 
> root@smtp:~# aptitude search mimemagic
> i ruby-mimemagic - fast MIME detection by extension or content

Can you explain How it can be solved?

**Comment by wh4u** [comment]
what the output of the following command on your server?
aptitude versions ruby-mimemagic or apt list -a ruby-mimemagic

**Comment by willpower232** [comment]
@wh4u this is nothing to do with the aptitude package and everything to do with a ruby gem that is a dependency listed in Gemfile.lock

This situation cannot be resolved until the Gemfile.lock and/or the Gemfile are updated.

**Comment by mjml1982** [comment]
Do we have any updates on this? not able to install postal through quick command as well!

**Comment by mikea62** [comment]
I install Ruby 3.0.0 using this guide "https://linoxide.com/how-to-install-ruby-on-rails-on-ubuntu-20-04". It worked for me.

**Comment by Bizcrony** [comment]
same issue i am getting installing Postal on UBUNTU 18.04
```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that
means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.
```

**Comment by Bizcrony** [comment]
> Do we have any updates on this? not able to install postal through quick command as well!

same here not able to install Postal on Ubuntu 18.04

**Comment by Bizcrony** [comment]
@willpower232 what we need to?

**Comment by willpower232** [comment]
>This situation cannot be resolved until the Gemfile.lock and/or the Gemfile are updated.

There is nothing we can do until @adamcooke or someone uploads a fix.

It looks like Ruby on Rails has a new minor version out with a changed dependency in it so that might be the answer unless Postal is using the dependency directly.

**Comment by Bizcrony** [comment]
@willpower232 Thanks for update so we have to wait i guess

**Comment by willpower232** [comment]
As mentioned on Slack, the answer to this situation is to upgrade Ruby on Rails but that also requires more testing to happen. @adamcooke will do a new release when it has been tested properly but, as a ruby developer, has several projects requiring attention at the moment for this same problem.

**Comment by pranavmishra** [comment]
Hi @willpower232 , I see @adamcooke had committed last week - is it working fine now?

**Comment by Bizcrony** [comment]
@pranavmishra @willpower232 @willpower232 Not working at all yet :(

**Comment by dhiraj-r** [comment]
Follow this guide and you will be able to install. https://inguide.in/build-postal-smtp-server-send-bulk-emails-ubuntu-18-04/

**Comment by pranavmishra** [comment]
I'm facing a small problem with this, when I'm trying to send an email from Postal after installation, 

The send button is consistently loading & emails are not being sent.

![image](https://user-images.githubusercontent.com/4854070/113550357-8fbb6c00-9610-11eb-8359-6e9bd96f24c0.png)


> Follow this guide and you will be able to install it. https://inguide.in/build-postal-smtp-server-send-bulk-emails-ubuntu-18-04/

**Comment by pranavmishra** [comment]
I'm facing a small issue into this, when I'm trying to send emails from Postal after installation the send button is continuously loading & hence the emails are not being sent. Ss attached below.

![Uploading image.png…]()


> Follow this guide and you will be able to install. https://inguide.in/build-postal-smtp-server-send-bulk-emails-ubuntu-18-04/

**Comment by Code-with-Shah** [comment]
> I'm facing a small issue into this, when I'm trying to send emails from Postal after installation the send button is continuously loading & hence the emails are not being sent. Ss attached below.
> 
> ![image](https://user-images.githubusercontent.com/4854070/113550627-ffc9f200-9610-11eb-83b2-fee8e52fcc0b.png)
> 
> > Follow this guide and you will be able to install. https://inguide.in/build-postal-smtp-server-send-bulk-emails-ubuntu-18-04/

Maybe port 25 is blocked on your VPS

**Comment by pranavmishra** [comment]
> > I'm facing a small issue into this, when I'm trying to send emails from Postal after installation the send button is continuously loading & hence the emails are not being sent. Ss attached below.
> > ![image](https://user-images.githubusercontent.com/4854070/113550627-ffc9f200-9610-11eb-83b2-fee8e52fcc0b.png)
> > > Follow this guide and you will be able to install. https://inguide.in/build-postal-smtp-server-send-bulk-emails-ubuntu-18-04/
> 
> Maybe port 25 is blocked on your VPS

Would it not be after the email is sent & then get a rejection due to port 25?

Because, I'm contabo itself?

**Comment by willpower232** [comment]
There will be a new release when the update has been properly tested so whilst you should be able to install Postal if you used git manually but it has not been fully tested.

@pranavmishra your installation of Postal experienced an exception. You will need to look in your log files to see what the problem was (or use your browser dev tools to see what happens when the button is clicked). Have you filled out the `smtp` settings in the config file? (not to be confused with `smtp_server`)

**Comment by layen67** [comment]
Hello,
Just do 

cd /opt/postal/app
bundle update --all

**Comment by willpower232** [comment]
Postal has not yet been officially fully tested with the updated gems so do be careful even if it looks like it works.

**Comment by redshiftltd** [comment]
> Hello,
> Just do
> 
> cd /opt/postal/app
> bundle update --all
> 
> working fine

This got me through the setup to do a basic install. Without that I was stuck.

**Comment by Padrio** [comment]
So this issue hasn't been touched since 23 Days.  
Since without a fix new users can't install the application, in my opinion this is urgent and needs to be fixed **now**.

How can you just leave such an issue open without doing anything? @adamcooke

**Comment by blakilox** [comment]
Hello,
Just do

cd /opt/postal/app
bundle update --all

working fine

> Hello,
> Just do
> 
> cd /opt/postal/app
> bundle update --all
> 
> working fine

The Regular Auto Upgrade command failed with this error, so I tried this next. that Killed my Mail Server, I had to restore from Backup

**Comment by blakilox** [comment]
Ahh thanks for the update Abduns, I was wondering if it was worth a re-try of the update, you save me some work

**Comment by blakilox** [comment]
Anybody tested the Update yet?

**Comment by DandyDeveloper** [comment]
@blakilox Have you just tried building an image from the latest Dockerfile and running it? 

It is working, I haven't experienced any issues using `master` and building from the Dockerfile that way.

**Comment by blakilox** [comment]
> @blakilox Have you just tried building an image from the latest Dockerfile and running it?
> 
> It is working, I haven't experienced any issues using `master` and building from the Dockerfile that way.

Hi Dandy Developer Im sure it works on Docker, but we are experiencing issue when upgrading an existing install.  because Mimemagic throws an error I think its waiting on something to get resolved on Mimemagic, I will do a backup and try it

**Comment by willpower232** [comment]
unless @adamcooke forgot to mention, I don't think there has been a release with the updated Gemfiles yet

**Comment by adamcooke** [comment]
This will be fully fixed in the next release of Postal.
