### ISSUE TITLE
is there any api to create smtp user? [Looking for help]

### ISSUE THREAD

**Issue by adnankhanakib** [postalhq/postal#1326]
Hello, I started using postal recently. I found API in postal but they are not for creating SMTP Credentials.

Is there any way I can create SMTP credential through API? or what command should I run to create a SMTP user?

How can I create SMTP user without user interface

**Comment by adnankhanakib** [comment]
Is there any command by which executing I can create smtp credential?

**Comment by willpower232** [comment]
Credentials can only be managed in the web UI.

**Comment by adnankhanakib** [comment]
I mean, script also execute some command? :/

**Comment by willpower232** [comment]
This is the only way to add an SMTP credential

![image](https://user-images.githubusercontent.com/1619102/113265020-9160f900-92cb-11eb-891a-f156a6c07aa7.png)

**Comment by adnankhanakib** [comment]
Okay thank you.
