### ISSUE TITLE
Rabbitmq testing Release unavailable

### ISSUE THREAD

**Issue by Phennim** [postalhq/postal#1327]
I think I used this script to install postal on Ubuntu 18:
`https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh`
It added this repo:
`add-apt-repository 'deb http://www.rabbitmq.com/debian/ testing main'`

But now `$ apt-get update` gives this error:
```
Err:8 https://www.rabbitmq.com/debian testing Release
  404  OK [IP: 2606:4700:10::ac43:1019 443]
Reading package lists... Done
E: The repository 'http://www.rabbitmq.com/debian testing Release' does not have a Release file.
```

Is it safe to remove the repo and use Ubuntu's 3.8 version instead?

```
$ apt-cache policy rabbitmq-server
rabbitmq-server:
  Installed: 3.6.15-1
  Candidate: 3.6.15-1
  Version table:
     3.8.2-0ubuntu1~ubuntu18.04.1 100
        100 http://mirror.transip.net/ubuntu/ubuntu bionic-backports/main amd64 Packages
        100 http://mirror.transip.net/ubuntu/ubuntu bionic-backports/main i386 Packages
 *** 3.6.15-1 500
        500 http://www.rabbitmq.com/debian testing/main amd64 Packages
        500 http://www.rabbitmq.com/debian testing/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by Phennim** [comment]
Thanks for the quick reply and sorry for not searching good enough.

So postal is compatible with any rabbitmq version?

**Comment by willpower232** [comment]
I don't know the specifics but I'm not aware of any limitations however as I mentioned previously, official apt repos tend to be more up to date than the default ones so tend to be the better choice.

Interestingly, I see ours isn't prompting to update from 3.6 to 3.8 either so :shrug:
