### ISSUE TITLE
Increase max_message_size gives unknown error

### ISSUE THREAD

**Issue by Phennim** [postalhq/postal#1328]
I have an email with about 12MB in attachments that gave error:
`Expected response code 250 but got code "552", with message "552 Message too large (maximum size 14MB)`

Setting max_message_size to 15:
`Expected response code 250 but got code "552", with message "552 Message too large (maximum size **15MB**)`

Setting it higher gives:
`Expected response code 250 but got code "", with message ""`

The `data` columns in the `raw-yyyy-mm-dd` tables are type `LONGBLOB`

Is there another setting I need to change? 

(The `max_message_size` was implemented in ticket #268)

**Comment by willpower232** [comment]
If you're very close to the limit, it might be that you're over without realising it as there can be extra overhead or byte size calculated differently depending on what you're looking at.

Are you restarting Postal when changing the configuration? The empty response suggests something else went wrong, are you able to see anything relevant in the log files?

**Comment by Phennim** [comment]
Right, the log files...

`[smtp.1:31311] [2021-03-31T14:06:30.194] ERROR -- : [JYHMXV] Mysql2::Error: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.`

Increasing innodb_log_file_size fixed it.

Thanks

**Comment by willpower232** [comment]
ah good to know, I'll write that down
