### ISSUE TITLE
Hostnames in IP rotation

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1329]
Can i add IP pools with following details ???

IP Address                      Hostname
192.168.1.2                     mydomain.com
192.168.1.3                     mydomain.com
192.168.1.4                     mydomain.com 

or the hostname for **each unique ip address** should be **different**, like mydomain1.com, mydomain2.com ??? like

IP Address                      Hostname
192.168.1.2                     mydomain1.com
192.168.1.3                     mydomain2.com
192.168.1.4                     mydomain3.com

**Comment by gitaayush** [comment]
I think hostname parameter doen't affect much. I have added different ip addresses for same hostname. Also the IP rotation is working properly.

**Comment by willpower232** [comment]
I'm not sure what the hostname means but if all the IP addresses are pointing at your Postal server and have the same hostname, I don't think there will be a problem

**Comment by gitaayush** [comment]
Yes the issues has been resolved. I am able to send emails via by IP pools. Thank you
