### ISSUE TITLE
SMTP Test tool failed to test emails

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1331]
I used **Gmass for smtp test.** When i tried to test my postal server setup, following error occurs: 

![image](https://user-images.githubusercontent.com/47238161/113273671-9c804d00-92fc-11eb-8b56-55512db54774.png)

I have used **lets encrypt** for certificates. Aslo below are my postal config for TLS setting

smtp:
 
  host: mydomain.com
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/mydomain.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/mydomain.com/privkey.pem
  tls_ciphers:
  ssl_version: TLSv1_1
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14

spamd:
  enabled: true
  host: 127.0.0.1
  port: 783

clamav:
  enabled: true
  host: 127.0.0.1
  port: 2000

**Comment by gitaayush** [comment]
Should i need to allow port 587 for this purpose ?

**Comment by gitaayush** [comment]
The issues has been resolved now. The issue was with the SSL_Version. Which was set to tls1.1, changing the version to 1.2 solved the issues.

**Comment by willpower232** [comment]
Good to know, glad you figured it out
