### ISSUE TITLE
Postal as smarthost/relay

### ISSUE THREAD

**Issue by NixNotCastey** [postalhq/postal#1333]
Hello,
Is it possible to use Postal as relay/smarthost or just add wildcard for domains?
I would like to use postal (because of ip pools) as relay host, but I have many domains on few servers and manual addition correct domain to correct server would be painful.

It would be nice to have the ability to disable the requirement of adding every domain to postal or just add wildcard.

**Comment by willpower232** [comment]
To be honest, it sounds like you want a traditional email server like Postfix or similar.

As well as domains, you may also need to configure routes and Postal could also change how any bounces to the message are received which may impact your workflow.

Postals primary purpose is to enable software to send email which it sounds like you are already taking care of.

**Comment by NixNotCastey** [comment]
I looked for alternative for Exim as only outgoing email gateway and Postal looks like great candidate mostly because of easy ip pool management and dashboard.
I get it, It's another purpose. Thank you, for a reply.
