### ISSUE TITLE
Unable to send email via SMTP 

### ISSUE THREAD

**Issue by dhiraj-r** [postalhq/postal#1334]
Hi,
I am unable to send emails via SMTP from external app. Apart from that everything else working fine. I am able to connect over web API and send emails. Also emails are going through postal web ui. 
Basically, the error I am getting is 
"_Failed to authenticate on SMTP server with username "swhsv-mail" using 2 possible authenticators_"

Port 25 is open for both outgoing and incoming traffic.

Thanks

**Comment by willpower232** [comment]
> I am able to connect over web API and send emails.

Have you created a separate SMTP credential for use with SMTP?

**Comment by dhiraj-r** [comment]
Yes, I did. In fact, when I tested Postal with smpter.net it works flawlessly, but not working with EMA like Mailwizz.

**Comment by willpower232** [comment]
Ah good find. Have you tested with a secure connection from smtper.net?

It is possible that you need to specify what kind of authentication Mailwizz is using. You can see precise details by clicking on this link on the Credentials page

![image](https://user-images.githubusercontent.com/1619102/113600885-8cd47180-9638-11eb-941c-d72165f94c2f.png)

**Comment by dhiraj-r** [comment]
Secure connection from smtper.net is not working. I did the test with precise details. Basically, in Mailwizz it's failing to authenticate in the first place. I also couldn't see anything in the log s for Mailwizz or perhaps I have been looking at the wrong place.

**Comment by willpower232** [comment]
If you're able to have a look at `smtp_server.log` you should see what, if any, messages were sent from smtper.net and Mailwizz. There may be other messages from people poking around for port 25 so don't be disheartened at the first failure you see!

**Comment by dhiraj-r** [comment]
Yes, I could see people poking around. They were so many I am unable to locate relevant logs.

**Comment by willpower232** [comment]
did you set `tls_enabled: true` and fill out the certificates in the config file?

**Comment by dhiraj-r** [comment]
Yes, I did. I also installed Let's Encrypt certificate.

**Comment by dhiraj-r** [comment]
![Capture](https://user-images.githubusercontent.com/9990832/113721638-54529780-970d-11eb-9e02-d3f3563a5426.PNG)
Though Postal says it support **AUTH CRAM-MD5 PLAIN LOGIN** but when CRAM-MD5 is tried, it says access denied and accept LOGIN. Do you think that would be the case with MailWizz or other SMTP software.

**Comment by willpower232** [comment]
Decoding your attempt at CRAM-MD5 it looks like you didn't specify the username as `swdlv/swdlv` (or whatever made the response didn't include some of the username). AUTH PLAIN is simpler in this case because Postal does not verify the username.

**Comment by dhiraj-r** [comment]
Yes, you are right. I also realized this. 
Thank you very much for prompt reply.
