### ISSUE TITLE
How to add custom header in postal 

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1335]
How to add custom header in postal ? I want to add unsubscribe link  in the header section. 
Please guide me on this

**Comment by willpower232** [comment]
As mentioned previously (in #1323 and originally discussed in #1292) you will need to include this header when you give the message to Postal.

This is entirely down to the software you are using so you should have a look at the support for that (or include the header if you are coding it yourself).

**Comment by gitaayush** [comment]
Thank you @willpower232  i will have a look into it.
