### ISSUE TITLE
Outgoing mail not sent over secure connection

### ISSUE THREAD

**Issue by Jimver** [postalhq/postal#1336]
Hello, I have a small issue where outgoing mail is not being sent over a secure connection. 

Right now all emails don't have the 'lock' next to the sent status. Which is supposed to be there according to https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/app/views/messages/_deliveries.html.haml#L38-L39

Outgoing message has no lock next to the sent status:

![Screenshot 2021-04-07 001322](https://user-images.githubusercontent.com/7677699/113784917-76144480-9736-11eb-998f-a7924dbedf61.png)

This means the messages are sent without a secure connection. This is quite strange as you would expect things like gmail and other big mail providers to use secure connections.

The log below shows it connects to port 25, but I would assume it uses STARTTLS which should upgrade it to an encrypted connection.

```
[worker.1:850] [2021-04-06T20:26:21.617] INFO -- : [ALSXBADZ] Connected to 2a00:1450:4013:c05::1b:25 (gmail-smtp-in.l.google.com)
[worker.1:850] [2021-04-06T20:26:21.618] INFO -- : [ALSXBADZ] Sending message 1::233319 to REDACTED@gmail.com
[worker.1:850] [2021-04-06T20:26:21.939] INFO -- : [ALSXBADZ] Message sent #233319 to gmail-smtp-in.l.google.com (2a00:1450:4013:c05::1b) for REDACTED@gmail.com
[worker.1:850] [2021-04-06T20:26:21.954] INFO -- : [ALSXBADZ] Finishing up
```
Is there anything else I can do to debug this or is this expected behavior?

Or alternatively a setting to force secure connections?

Thanks in advance!

**Comment by willpower232** [comment]
You can see in [lib/postal/smtp_sender.rb](https://github.com/postalhq/postal/blob/master/lib/postal/smtp_sender.rb) that it normally defaults to automatic unless it has been forced because routing is involved.

I will admit that I can't recall ever seeing the padlock but I haven't really been looking for it.

**Comment by Jimver** [comment]
Ok I did some more tests and gmail shows that the received mail used TLS encryption:

![Screenshot 2021-04-07 225204](https://user-images.githubusercontent.com/7677699/113932519-ffd61780-97f3-11eb-9205-76d20c84b829.png)

Wouldn't this then be a bug where postal doesn't properly detect if it used a secure connection?

**Comment by Jimver** [comment]
Ok so after debugging some more I discovered the bug in postal and fixed it! Turns out the `secure_socket` check method was wrong. See #1338 for the PR.

**Comment by willpower232** [comment]
Great spot, thank you
