### ISSUE TITLE
Softfail, i cant test my email

### ISSUE THREAD

**Issue by Haiqal10** [postalhq/postal#1337]
hello
can anyone help me i can't send an email.
even though I have configured SPF, DKIM, and others, I always get softfail
thank you
![mrtoolbox](https://user-images.githubusercontent.com/80629139/113880918-20977080-97e6-11eb-88a6-de5d3eab9a18.png)
[my setting postal.txt](https://github.com/postalhq/postal/files/6272203/my.setting.postal.txt)
![outgoing smtp](https://user-images.githubusercontent.com/80629139/113880928-22f9ca80-97e6-11eb-8f0d-ea8123f0680d.png)
![port](https://user-images.githubusercontent.com/80629139/113880932-23926100-97e6-11eb-80b0-c7154857e90e.png)
![SPF DKIM MX ](https://user-images.githubusercontent.com/80629139/113880933-242af780-97e6-11eb-8bb2-5d311a342005.png)

**Comment by willpower232** [comment]
Are you able to send emails to other addresses at all?

It might also be that your server provider is blocking you from sending emails.

**Comment by Haiqal10** [comment]
> 
> 
> Are you able to send emails to other addresses at all?
> 
> It might also be that your server provider is blocking you from sending emails.

I use a provider from aws ec2 and my IP is not blacklisted, do you have a solution that I should try?
![Screenshot 2021-04-08 001302](https://user-images.githubusercontent.com/80629139/113907227-4e3ce380-97ff-11eb-9512-0b6282776d3d.png)

**Comment by Haiqal10** [comment]
> 
> 
> Are you able to send emails to other addresses at all?
> 
> It might also be that your server provider is blocking you from sending emails.

 do you think my domain from namecheap the cause of Softfail?

**Comment by willpower232** [comment]
It is unlikely that your domain is causing problems.

It is more likely that you need to request permission from AWS to send many emails from your server/IP address. You should ask them about which forms to fill in.

You will also need to complete the reverse DNS form.

I presume you are using an elastic IP address for this?

**Comment by Haiqal10** [comment]
> 
> 
> It is unlikely that your domain is causing problems.
> 
> It is more likely that you need to request permission from AWS to send many emails from your server/IP address. You should ask them about which forms to fill in.
> 
> You will also need to complete the reverse DNS form.
> 
> I presume you are using an elastic IP address for this?

this has been solved, I asked AWS customer services. aws ec2 didn't open port 25, they told me to use AWS SES.
thank you for replying

**Comment by willpower232** [comment]
Not a great answer from AWS but hope it works out for you.
