### ISSUE TITLE
Problem to send and receive message with postal after allow port 2525

### ISSUE THREAD

**Issue by Matthew3111** [postalhq/postal#1339]
Hi community

I have a problem on my postal server, i'm still able to connect and see all my dasboard but i'm not able to receive and send email, and it happens since i have put a line of command to allow port 2525

The line was here :
/sbin/iptables -t nat -I PREROUTING -d xxx.xxx.xxx.xxx -p tcp -m tcp --dport 2525 -j DNAT --to-destination xxx.xxx.xxx.xxx:25
/sbin/iptables -t nat -I OUTPUT     -d xxx.xxx.xxx.xxx -p tcp -m tcp --dport 2525 -j DNAT --to-destination xxx.xxx.xxx.xxx:25

Don't hesitate to send me suggestion

Thank you friends

**Comment by willpower232** [comment]
Is Postal running? You can see with `postal status`

The IP addresses that you used in your command, do they definitely exist on the server? You can see with `ip a`

Is Postal definitely listening on port 25? You can see with `netstat -lnp`

**Comment by Matthew3111** [comment]
Postal is running except for "worker.1" and "requeuer1"

The IP seems ok, i have the same adress but with /32 ? xxx.xxx.xxx.xxx/32 ? My adress is the same and ok but i don't know what is the /32.

I'm not able to run netstat -lnp this command is no found

Thanks

**Comment by Matthew3111** [comment]
But when iput the command sudo lsof -i -h -p, i can see all my py port, and the port 25 is listening 

When i check my server adress on mx i see an error with SMTP TLS ? "does not support tls" , 530 Authentication required [150 ms]

**Comment by willpower232** [comment]
> Postal is running except for "worker.1" and "requeuer1"

This is probably where your issues lie, are you able to restart your server or Postal to see if they come back?

**Comment by Matthew3111** [comment]
No Unfortunately i can't see anything now ... i have done the command (that i have seen in a subject of the forum)
 "sudo postal stop"
"sudo rm -vf /tmp/postal/pids/*
sudo postal run"

And now i have a message "cannot be started in the foreground because supervisor already running" 
This is a new problem

**Comment by willpower232** [comment]
are you able to fully restart the server to clear up any random processes and start fresh?

**Comment by Matthew3111** [comment]
Fully restart i don't know but when i have put the this command : "sudo postal restart" and i have this : 
Restarted web.1
Restarted worker.1 -> worker.2
Restarted cron.1 -> cron.2
Restarted smtp1
Restarted requeur.1 -> requeur.2

**Comment by Matthew3111** [comment]
root@vmi540172:~# clear
root@vmi540172:~# sudo postal restart
Restarted web.1
Restarted worker.1 -> worker.2
Restarted cron.1 -> cron.2
Restarted smtp.1
Restarted requeuer.1 -> requeuer.2
root@vmi540172:~# postal run
Error: Cannot be started in the foreground because supervisor already running
root@vmi540172:~# postal start
No processes to start.
root@vmi540172:~# postal stop
Stopped web.1 (PID: 1616)
Stopped worker.2 (PID: 2120)
Stopped cron.2 (PID: 1990)
Stopped smtp.1 (PID: 1979)
Stopped requeuer.2 (PID: 2099)
Supervisor will be stopped when processes are stopped.
Waiting for supervisor to stop...
Supervisor has stopped
root@vmi540172:~# sudo -u postal start
sudo: start: command not found
root@vmi540172:~# sudo -u postal postal start
`/root` is not writable.
Bundler will use `/tmp/bundler20210412-2413-y9eh712413' as your home directory t        emporarily.
Started Procodile supervisor with PID 2418

**Comment by Matthew3111** [comment]
# clear
# sudo postal restart
Restarted web.1
Restarted worker.1 -> worker.2
Restarted cron.1 -> cron.2
Restarted smtp.1
Restarted requeuer.1 -> requeuer.2
# postal run
Error: Cannot be started in the foreground because supervisor already running
# postal start
No processes to start.
# postal stop
Stopped web.1 (PID: 1616)
Stopped worker.2 (PID: 2120)
Stopped cron.2 (PID: 1990)
Stopped smtp.1 (PID: 1979)
Stopped requeuer.2 (PID: 2099)
Supervisor will be stopped when processes are stopped.
Waiting for supervisor to stop...
Supervisor has stopped
# sudo -u postal start
sudo: start: command not found
~# sudo -u postal postal start
/root is not writable.
Bundler will use `/tmp/bundler20210412-2413-y9eh712413' as your home directory t emporarily.
Started Procodile supervisor with PID 2418

**Comment by Matthew3111** [comment]
i have also made the postal status and i have a problem with worker1 (is not running failed) and requeuer1 ( is not running (failed))

**Comment by Matthew3111** [comment]
update : I'm now able to connect to my postal server but still enable to send message (always on pending statut) since i have put the line of command to enable port 2525

When i have used Atomic email sender (to send my email, it's a software as sendblaster), i was no able to send on SSL with 2525 but just with TSL

**Comment by Matthew3111** [comment]
update : I'm now able to connect to my postal server but still Unable to send message (always on pending statut) since i have put the line of command to enable port 2525

When i have used Atomic email sender (to send my email, it's a software as sendblaster), i was no able to send on SSL with 2525 but just with TSL

**Comment by Matthew3111** [comment]
update : I'm now able to connect to my postal server adress but still Unable to send message (always on pending statut) since i have put the line of command to enable port 2525

**Comment by Matthew3111** [comment]
It also seem comes from RABBITMQ and TLS also, when i went to etc/rabbitmq, i have no file ... on my postal.yml i have that :

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  # if you have more than one RabbitMQ server (cluster), you can use array like this:
  # host:
  #   - 10.1.1.1
  #   - 10.1.1.2
  #   - 10.1.1.3
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

**Comment by willpower232** [comment]
When I said restart the server, I was talking about the computer itself, i.e. the command `reboot` or `shutdown -r now`. I suggest you try this first to see if you can run `postal status` and see everything running correctly.

Regarding your other attempts,

`postal run` is mainly for debugging Postal and could be useful here to see if your processes are having problems but you will need to run `postal stop` first.

`sudo -u postal...` means `as the user postal ...` this part is handled by the code so you should not need to use that.

If you installed Postal with the quick installer then you should have it running, you can test with `sudo rabbitmqctl status`.

**Comment by Matthew3111** [comment]
Hi Will, and thanks to help me ^^

I have restart the the server with the commande shutdown -r now, and with postal status so it's the same problem :  worker1 (is not running failed) and requeuer1 ( is not running (failed))

Then i have made postal stop and postal run and it seems to have errors  :  



04:00:03 system             | Procodile supervisor started with PID 1444
04:00:03 system             | Application root is /opt/postal/app
04:00:03 system             | Automatic respawning is disabled
04:00:03 control            | Listening at /tmp/postal/pids/procodile.sock
04:00:03 system             | Reloading configuration
04:00:03 web.1              | Started with PID 1448
04:00:03 worker.1           | Started with PID 1451
04:00:03 cron.1             | Started with PID 1454
04:00:03 smtp.1             | Started with PID 1457
04:00:03 requeuer.1         | Started with PID 1460
04:00:04 web.1              | => Puma starting in single mode...
04:00:04 web.1              | => * Version 4.3.5 (ruby 2.3.8-p459), codename: My                                                                                                                     sterious Traveller
04:00:04 web.1              | => * Min threads: 5, max threads: 5
04:00:04 web.1              | => * Environment: production
04:00:07 smtp.1             | => [smtp.1:1457] [2021-04-13T04:00:07.436] INFO --                                                                                                                      : Listening on port 25
04:00:07 requeuer.1         | => [requeuer.1:1460] [2021-04-13T04:00:07.589] INF                                                                                                                     O -- : Running message requeuer...
04:00:07 cron.1             | => [cron.1:1454] [2021-04-13T04:00:07.608] INFO --                                                                                                                      : Starting clock for 8 events: [ every-1-minutes every-15-minutes every-15-minu                                                                                                                     tes every-15-minutes every-15-minutes every-hour every-hour every-day ]
04:00:07 cron.1             | => [cron.1:1454] [2021-04-13T04:00:07.609] INFO --                                                                                                                      : Triggering 'every-1-minutes'
04:00:07 cron.1             | => [cron.1:1454] [2021-04-13T04:00:07.637] ERROR -                                                                                                                     - : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:00:07 cron.1             | => [cron.1:1454] [2021-04-13T04:00:07.637] INFO --                                                                                                                      : Triggering 'every-15-minutes'
04:00:07 cron.1             | => [cron.1:1454] [2021-04-13T04:00:07.649] ERROR -                                                                                                                     - : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:00:08 requeuer.1         | => rake aborted!
04:00:08 requeuer.1         | => Bunny::NotAllowedError: Connection-level error:                                                                                                                      NOT_ALLOWED - vhost /postal not found
04:00:08 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny                                                                                                                     -2.14.4/lib/bunny/session.rb:1275:in `raise'
04:00:08 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny                                                                                                                     -2.14.4/lib/bunny/session.rb:1275:in `open_connection'
04:00:08 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny                                                                                                                     -2.14.4/lib/bunny/session.rb:320:in `start'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/rabbit_mq.rb:23:in `                                                                                                                     create_connection'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/rabbit_mq.rb:28:in `                                                                                                                     create_channel'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/worker.rb:195:in `jo                                                                                                                     b_channel'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/worker.rb:201:in `jo                                                                                                                     b_queue'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/job.rb:38:in `queue'
04:00:08 requeuer.1         | => /opt/postal/app/app/models/queued_message.rb:46                                                                                                                     :in `queue'
04:00:08 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/activ                                                                                                                     erecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
04:00:08 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/activ                                                                                                                     erecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
04:00:08 requeuer.1         | => /opt/postal/app/app/models/queued_message.rb:11                                                                                                                     9:in `requeue_all'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/message_requeuer.rb:                                                                                                                     11:in `block in run'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/message_requeuer.rb:                                                                                                                     9:in `loop'
04:00:08 requeuer.1         | => /opt/postal/app/lib/postal/message_requeuer.rb:                                                                                                                     9:in `run'
04:00:08 requeuer.1         | => /opt/postal/app/lib/tasks/postal.rake:18:in `bl                                                                                                                     ock (2 levels) in <top (required)>'
04:00:08 requeuer.1         | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-                                                                                                                     12.3.3/exe/rake:27:in `<top (required)>'
04:00:08 requeuer.1         | => Tasks: TOP => postal:requeuer
04:00:08 requeuer.1         | => (See full trace by running task with --trace)
04:00:08 web.1              | => * Listening on tcp://127.0.0.1:5000
04:00:08 web.1              | => Use Ctrl-C to stop
04:00:08 worker.1           | => [worker.1:1451] [2021-04-13T04:00:08.720] INFO                                                                                                                      -- : Worker running with 4 threads
04:00:08 worker.1           | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny                                                                                                                     -2.14.4/lib/bunny/session.rb:1275:in `raise': Connection-level error: NOT_ALLOWE                                                                                                                     D - vhost /postal not found (Bunny::NotAllowedError)
04:00:08 worker.1           | =>        from /opt/postal/vendor/bundle/ruby/2.3.                                                                                                                     0/gems/bunny-2.14.4/lib/bunny/session.rb:1275:in `open_connection'
04:00:08 worker.1           | =>        from /opt/postal/vendor/bundle/ruby/2.3.                                                                                                                     0/gems/bunny-2.14.4/lib/bunny/session.rb:320:in `start'
04:00:08 worker.1           | =>        from /opt/postal/app/lib/postal/rabbit_m                                                                                                                     q.rb:23:in `create_connection'
04:00:08 worker.1           | =>        from /opt/postal/app/lib/postal/rabbit_m                                                                                                                     q.rb:28:in `create_channel'
04:00:08 worker.1           | =>        from /opt/postal/app/lib/postal/worker.r                                                                                                                     b:195:in `job_channel'
04:00:08 worker.1           | =>        from /opt/postal/app/lib/postal/worker.r                                                                                                                     b:17:in `work'
04:00:08 worker.1           | =>        from script/worker.rb:3:in `<main>'
04:00:09 worker.1           | Process has stopped. Respawning not available.
04:00:09 worker.1           | Removed PID file
04:00:09 requeuer.1         | Process has stopped. Respawning not available.
04:00:09 requeuer.1         | Removed PID file
04:00:36 cron.1             | => E, [2021-04-13T04:00:36.640051 #1454] ERROR -- #<Bunny::Session:0x5630303a96f0 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:00:36 cron.1             | => E, [2021-04-13T04:00:36.651285 #1454] ERROR -- #<Bunny::Session:0x56303033e1e8 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:01:07 cron.1             | => [cron.1:1454] [2021-04-13T04:01:07.001] INFO -- : Triggering 'every-1-minutes'
04:01:07 cron.1             | => [cron.1:1454] [2021-04-13T04:01:07.005] ERROR -- : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:01:36 cron.1             | => E, [2021-04-13T04:01:36.005803 #1454] ERROR -- #<Bunny::Session:0x563030115240 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:02:07 cron.1             | => [cron.1:1454] [2021-04-13T04:02:07.001] INFO -- : Triggering 'every-1-minutes'
04:02:07 cron.1             | => [cron.1:1454] [2021-04-13T04:02:07.005] ERROR -- : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:02:36 cron.1             | => E, [2021-04-13T04:02:36.005874 #1454] ERROR -- #<Bunny::Session:0x56302fe8dd38 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:03:07 cron.1             | => [cron.1:1454] [2021-04-13T04:03:07.001] INFO -- : Triggering 'every-1-minutes'
04:03:07 cron.1             | => [cron.1:1454] [2021-04-13T04:03:07.004] ERROR -- : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:03:36 cron.1             | => E, [2021-04-13T04:03:36.005249 #1454] ERROR -- #<Bunny::Session:0x56302f5c8f40 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:04:07 cron.1             | => [cron.1:1454] [2021-04-13T04:04:07.001] INFO -- : Triggering 'every-1-minutes'
04:04:07 cron.1             | => [cron.1:1454] [2021-04-13T04:04:07.005] ERROR -- : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:04:36 cron.1             | => E, [2021-04-13T04:04:36.005894 #1454] ERROR -- #<Bunny::Session:0x563032062dc8 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:05:07 cron.1             | => [cron.1:1454] [2021-04-13T04:05:07.001] INFO -- : Triggering 'every-1-minutes'
04:05:07 cron.1             | => [cron.1:1454] [2021-04-13T04:05:07.006] ERROR -- : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:05:36 cron.1             | => E, [2021-04-13T04:05:36.007199 #1454] ERROR -- #<Bunny::Session:0x563031fb26f8 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:06:07 cron.1             | => [cron.1:1454] [2021-04-13T04:06:07.001] INFO -- : Triggering 'every-1-minutes'
04:06:07 cron.1             | => [cron.1:1454] [2021-04-13T04:06:07.005] ERROR -- : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:06:36 cron.1             | => E, [2021-04-13T04:06:36.006120 #1454] ERROR -- #<Bunny::Session:0x563031ec0ce0 postal@127.0.0.1:5672, vhost=/postal, addresses=[127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.436] INFO --                                                                                                                      : Started GET "/" for 92.118.160.5 at 2021-04-13 04:06:52 -0500
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.438] INFO --                                                                                                                      : Processing by OrganizationsController#index as HTML
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.458] INFO --                                                                                                                      : Redirected to https://mentorbooth.com/login?return_to=%2F
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.459] INFO --                                                                                                                      : Filter chain halted as :login_required rendered or redirected
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.459] INFO --                                                                                                                      : Completed 302 Found in 21ms (ActiveRecord: 5.6ms)
04:06:52 web.1              | => 92.118.160.5 - - [13/Apr/2021:04:06:52 -0500] "                                                                                                                     GET / HTTP/1.0" 302 - 0.0448
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.594] INFO --                                                                                                                      : Started GET "/login?return_to=%2F" for 92.118.160.5 at 2021-04-13 04:06:52 -05                                                                                                                     00
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.602] INFO --                                                                                                                      : Processing by SessionsController#new as HTML
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.602] INFO --                                                                                                                      :   Parameters: {"return_to"=>"/"}
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.606] INFO --                                                                                                                      :   Rendering sessions/new.html.haml within layouts/sub
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.614] INFO --                                                                                                                      :   Rendered sessions/new.html.haml within layouts/sub (7.3ms)
04:06:52 web.1              | => [web.1:1448] [2021-04-13T04:06:52.619] INFO --                                                                                                                      : Completed 200 OK in 17ms (Views: 14.2ms | ActiveRecord: 0.5ms)
04:06:52 web.1              | => 92.118.160.5 - - [13/Apr/2021:04:06:52 -0500] "                                                                                                                     GET /login?return_to=%2F HTTP/1.0" 200 - 0.0272
04:07:07 cron.1             | => [cron.1:1454] [2021-04-13T04:07:07.001] INFO --                                                                                                                      : Triggering 'every-1-minutes'
04:07:07 cron.1             | => [cron.1:1454] [2021-04-13T04:07:07.007] ERROR -                                                                                                                     - : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:07:36 cron.1             | => E, [2021-04-13T04:07:36.005423 #1454] ERROR --                                                                                                                      #<Bunny::Session:0x563031d74be8 postal@127.0.0.1:5672, vhost=/postal, addresses=                                                                                                                     [127.0.0.1:5672]>: I/O error in the hearbeat sender: closed stream
04:08:07 cron.1             | => [cron.1:1454] [2021-04-13T04:08:07.001] INFO --                                                                                                                      : Triggering 'every-1-minutes'
04:08:07 cron.1             | => [cron.1:1454] [2021-04-13T04:08:07.008] ERROR -                                                                                                                     - : Connection-level error: NOT_ALLOWED - vhost /postal not found
04:08:36 cron.1             | => E, [2021-04-13T04:08:36.008655 #1454] ERROR --

**Comment by Matthew3111** [comment]
I precise that i don't know the mentorbooth.com ....

**Comment by Matthew3111** [comment]
/etc/network/interface


# ifupdown has been replaced by netplan(5) on this system.  See
# /etc/netplan for current configuration.
# To re-enable ifupdown on this system, you can run:
#    sudo apt install ifupdown

----------------------------------------------------------------------------------------------

NETPLAN /etc/netplan/01

network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        macaddress: 00:50:56:41:d0:ec
      addresses: 
        - XXX.XXX.XXX.XXX/32 <---------------------------------------------------XXXX is ok, but /32 ??
        #- 2605:a140:2054:0172:0000:0000:0000:0001/64
      #gateway6: fe80::1 
      routes:
        - to: 0.0.0.0/0
          via: 207.244.224.1 <-------------------------Not my adress
          on-link: true
      nameservers:
        search: [ invalid ]
        addresses:
          - 209.126.15.52  <------------- Don't Know that adress
          - 209.126.15.51 <-------------- Don't Know that adress
          #- 2605:a140:5028::2:53
          #- 2605:a140:5028::1:53
------------------------------------------------------------------------------------------------------------------------

**Comment by willpower232** [comment]
> Bunny::NotAllowedError: Connection-level error: NOT_ALLOWED - vhost /postal not found

It looks like either RabbitMQ was reinstalled after Postal or the install script failed to complete the setup within RabbitMQ.

You can try repeating these commands and then restarting again to see if you can get worker and requeuer going

https://github.com/postalhq/postal/blob/a735219783127cd0495246ccee89422069da1a1c/script/install/ubuntu1804.sh#L44-L46

**Comment by Matthew3111** [comment]
@willpower232  it's ok, it works again, thanks for your help!
