### ISSUE TITLE
Send through API and always return "norcipients"

### ISSUE THREAD

**Issue by dowe-are** [postalhq/postal#1340]
I have been looking for a long time, but I can't find the answer, so I can only ask you。
![1)U4IL5 LK{$ )JQGP@W~5Q](https://user-images.githubusercontent.com/82209815/114161419-9b819800-995a-11eb-8995-5fd113f3434f.png)

**Comment by dowe-are** [comment]
I need you help

**Comment by dowe-are** [comment]
I need your help

**Comment by dowe-are** [comment]
I need you

**Comment by willpower232** [comment]
I think you need to use `to[]` instead of `to`

**Comment by dowe-are** [comment]
Thank you for your reply, but it doesn't seem to work. It's still "NoRecipients"
![HPP HNG@{WCG7U7ZXWEY~M5](https://user-images.githubusercontent.com/82209815/114163357-a9d0b380-995c-11eb-9300-506f9ade68c0.png)

**Comment by willpower232** [comment]
What program are you using?

**Comment by dowe-are** [comment]
''apipost''. 
Similar to "Postman"

**Comment by willpower232** [comment]
Unfortunately I don't know how to work apipost or if it has an english version :sweat_smile: 

The API accepts JSON so I assume the page you're filling out creates a JSON object to send otherwise you would get a different error message.

If you are able to see what it is sending, you need to make it look something like this

![image](https://user-images.githubusercontent.com/1619102/114167184-8c80f280-9926-11eb-8be9-b5b006c17d7f.png)

**Comment by dowe-are** [comment]
I tried to imitate you, and I succeeded. Thank you very much.
![2}R{ $(KPVBVP8 4K 06BC5](https://user-images.githubusercontent.com/82209815/114168538-f8814c00-9962-11eb-8066-65472d8b44b8.png)

**Comment by willpower232** [comment]
Glad you figured it out, feel free to close the issue if there are no other problems.

**Comment by rccess** [comment]
@willpower232 
i am using same process but still "norcipients" issue 
can you please advise on it

{
    "to": [
        "xxxxxxxxxxxxx@gmail.com"
    ],
    "from": "xxxxxxxxxxx@xxxxxx.lt",  
    "subject": "Email API Test",
    "plain_body": "hello this email api checking"
}

<img width="440" alt="image" src="https://user-images.githubusercontent.com/32220165/203772912-bf4617ec-ffe9-48e9-8f0d-785d6253cb05.png">

**Comment by rvIceBreaker** [comment]
I'm also having this issue, submitting a request from golang
```
{"to":["me@email.com"],"from":"no-reply@email.com","sender":"no-reply@email.com","subject":"test","plain_body":"this is a test"}
```
returns
```
"status":"error","time":0.0,"flags":{},"data":{"code":"NoRecipients","message":"There are no recipients defined to receive this message"}}
```
