### ISSUE TITLE
Postal UI clicking the "Credentials" give the message check the logs

### ISSUE THREAD

**Issue by sheikhsherazali** [postalhq/postal#1341]
While logged into the Postal UI clicking the "Credentials" link results in a "We're sorry, but something went wrong - If you are the application owner, check the logs for more information".

I have checked all the logs including the rails.log all the logs are not stating the error. 

After that, I made another organization and click on the "Credentials" link everything come properly. 

I have made a small video. Here is the link so support people can see the same what exactly the problem I am facing

http://www.youtube.com/watch?v=fy_ERBiUQIo

Appreciate your support in this connection.

**Comment by willpower232** [comment]
The error message should be appearing in rails.log, you're looking for something like this where it looks very different
![image](https://user-images.githubusercontent.com/1619102/114199907-9e758c00-994c-11eb-8a6b-e62552e4f68a.png)

It might also be worth trying this incognito in your browser in case your browser has cached an error page.

**Comment by sheikhsherazali** [comment]
Please check this log

^[[34m[web.1:12688]^[[0m [2021-04-09T17:06:33.582] INFO -- : Completed 500 Internal Server Error in 147ms (ActiveRecord: 31.2ms)
^[[34m[web.1:12688]^[[0m [2021-04-09T17:06:33.593] FATAL -- :
^[[34m[web.1:12688]^[[0m [2021-04-09T17:06:33.593] FATAL -- : ActionView::Template::Error (undefined local variable or method `uuid' for #<Credential:0x0000000007f15ac0>):
^[[34m[web.1:12688]^[[0m [2021-04-09T17:06:33.594] FATAL -- :     21:     %ul.credentialList.u-margin
    22:       - for credential in @credentials
    23:         %li.credentialList__item
    24:           = link_to [:edit, organization, @server, credential], :class => 'credentialList__link' do
    25:             .credentialList__type
    26:               %span.label{:class => "label--credentialType-#{credential.type.underscore}"}= credential.type.split('-').last
    27:             .credentialList__properties
^[[34m[web.1:12688]^[[0m [2021-04-09T17:06:33.594] FATAL -- :
^[[34m[web.1:12688]^[[0m [2021-04-09T17:06:33.595] FATAL -- : app/models/credential.rb:45:in `to_param'
app/views/credentials/index.html.haml:24:in `block in _app_views_credentials_index_html_haml___3283790097015923786_25407060'
app/views/credentials/index.html.haml:22:in `each'
app/views/credentials/index.html.haml:22:in `_app_views_credentials_index_html_haml___3283790097015923786_25407060'

I think this might be the error if you want i can attach the whole log for your ease.

**Comment by sheikhsherazali** [comment]
your ease I have copy-pasted the screenshot 

![image](https://user-images.githubusercontent.com/13349939/114202445-9f201980-9970-11eb-9cfe-161794006eec.png)

**Comment by willpower232** [comment]
Did you upgrade your Postal recently? It sounds like the database was not migrated for some reason.

I think you can fix this with `bundle exec rake db:migrate` but you may want to take downtime and a backup first just in case

https://github.com/postalhq/postal/blob/a735219783127cd0495246ccee89422069da1a1c/bin/postal#L62

**Comment by sheikhsherazali** [comment]
Many thanks for the command the database is migrated and the credentials are working fine now. When I would like to edit  the credentials the rail is still having the problem i.e.

![image](https://user-images.githubusercontent.com/13349939/114221122-54a99780-9986-11eb-8bfe-683123648a59.png)

Please can you advise how I can proceed now in this connection?

**Comment by sheikhsherazali** [comment]
Boss I have rebooted the server and start the postal service again and it is working perfectly fine now. 

Please close the support ticker and once again thanks for your wonderful support.
