### ISSUE TITLE
Error during postal initialize ..please help

### ISSUE THREAD

**Issue by isiddiquebd** [postalhq/postal#1342]
I have got this two error during postal initialize and postal make-user
![image](https://user-images.githubusercontent.com/61184355/114227380-bb36b180-9996-11eb-8e75-9b18780c8b5f.png)
please, can anyone help me about this issue

**Comment by willpower232** [comment]
> access denied for user postal@localhost

It sounds like your MySQL server isn't running or you have the wrong details in your configuration file.
