### ISSUE TITLE
Error Cert 

### ISSUE THREAD

**Issue by raf-rodrigues** [postalhq/postal#1343]
I have a problem using TLS on my server.

Postal is fetching files from the main domain.com and not from postal.domain.com

How to fix this error?

```

[smtp.1:1067] [2021-04-09T14:45:06.104] DEBUG -- : [D8NGJP] => 250-STARTTLS
[smtp.1:1067] [2021-04-09T14:45:06.104] DEBUG -- : [D8NGJP] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:1067] [2021-04-09T14:45:06.144] DEBUG -- : [D8NGJP] <= STARTTLS
[smtp.1:1067] [2021-04-09T14:45:06.144] DEBUG -- : [D8NGJP] => 220 Ready to start TLS
[smtp.1:1067] [2021-04-09T14:45:06.144] ERROR -- : [D8NGJP] An error occurred while processing data from a client.
[smtp.1:1067] [2021-04-09T14:45:06.144] ERROR -- : [D8NGJP] Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/letsencrypt/live/domain.com

```

**Comment by willpower232** [comment]
Either that folder doesn't exist or the postal user has no read permissions on it so it cannot access the file.

**Comment by raf-rodrigues** [comment]
Thanks for the answer.

But he doesn't really have that folder, because he's looking for the main domain.com file. And not from the subdomain of postal.domain.com

You got it? That is why it is giving encryption error in emails because the postcard does not match the certificates of the subdomain, but of the main domain.

How to make the postcard look for the subdomain certificate?

**Comment by willpower232** [comment]
It will be looking for whatever has been configured in the config file, I do not believe it needs to account for multiple domains here. 

As long as it is a real SSL certificate it can be used, regardless of the domain.
