### ISSUE TITLE
S/MiME functionality is available in the postal 

### ISSUE THREAD

**Issue by sheikhsherazali** [postalhq/postal#1344]
Hi 

First of all many thanks for developing such wonderful software. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/13349939/114548242-f0821e80-9c78-11eb-887a-1fbf26598a02.png)

The screenshot is one of the emails sent to the Gmail id from the postal server. 

If you see I highlighted the encryption part. These are the extract for google about the type of encryption supported by the smtps.

![image](https://user-images.githubusercontent.com/13349939/114548747-99c91480-9c79-11eb-9591-19f5478b95a6.png)
 
My question is do postal support S/MIME enhanced encryption fu yes how we can implement that. 

If not do you guys have any plan to implement them. 

Once again thanks in advance for your wonderful support.

**Comment by willpower232** [comment]
I don't know a lot about it but if you don't have click tracking enabled and are using SMTP, you can probably construct an S/MIME message yourself and send it using Postal.

**Comment by sheikhsherazali** [comment]
Many thanks.

I got your point.  I am closing this ticket.
