### ISSUE TITLE
Question: Has anyone used postal as backup mx?

### ISSUE THREAD

**Issue by wh4u** [postalhq/postal#1345]
Postal has the ability to deliver incoming messages, there is an mx record available.
Combined with the smtp endpoint feature, is it possible to achieve such a scenario? To hold incoming messages for other mailservers in case of failure etc.

**Comment by willpower232** [comment]
Postal cannot store messages long term, it is made to let emails flow through it.

You would be better off using a tool devoted to the purpose instead.
