### ISSUE TITLE
Expected response code 250 but got code "530", with message "530 From/Sender name is not valid

### ISSUE THREAD

**Issue by pranavmishra** [postalhq/postal#1346]
Any reason, why i'm getting this?

"Expected response code 250 but got code "530", with the message "530 From/Sender name is not valid ""

![image](https://user-images.githubusercontent.com/4854070/115141364-762b1300-a059-11eb-8c6a-881c77e1acb7.png)

**Comment by willpower232** [comment]
> From/Sender name is not valid

The domain name in the from email address has not been added as a domain in the same mail server as the credential.

Looking at your screenshot, you're trying to send from gmail.com which is highly unlikely to work in reality, even if you could convince Postal to add it.
