### ISSUE TITLE
How to setup custom ports for Postal web UI?

### ISSUE THREAD

**Issue by clarkycal** [postalhq/postal#1347]
Hello, see the below comment by @willpower232
https://github.com/postalhq/postal/issues/869#issuecomment-527445740

I have checked the documentation and issues here on github. I can't find any docs on how to change the postal web UI ports to run on http://MyPostalServer:8080 for example.

Can anyone throw me some tips/hints?

Cheers

**Comment by willpower232** [comment]
If you have competition for port 5000 within your server, you can customise that here https://github.com/postalhq/postal/blob/a735219783127cd0495246ccee89422069da1a1c/config/postal.defaults.yml#L19-L21

If you're referring to how to access the UI, you can specify which port is used in the nginx configuration.
