### ISSUE TITLE
Multiple Tries made by the postal on the softfail 

### ISSUE THREAD

**Issue by sheikhsherazali** [postalhq/postal#1348]
HI

Please see the screenshot below:

![image](https://user-images.githubusercontent.com/13349939/115270320-a22bbe80-a155-11eb-9b37-8b8a5c375c5c.png)

When the soft fail is made but for any reason, the postal keep on retrying to send the message can create a continuous array of messages for the soft fail and keep on retrying after certain internal.

The other server treats this behavior as an attack and blocks the IP and mark the IP in many ways. 

What we are requesting is there any setting in the postal of soft fail email in connection with the following:

1. Not of retries to be made.
2.. Time interval of retry 

What I want is to set max 3 retries  with a time interval of 2 minutes after that the message should be marked as a status that it should not be retried

IF there is an extended facility for certain domains then it would be a blessing.  For example, the X no of domains will only be retry 3 times the rest will be 4 time,s and accordingly the time internal.

**Comment by willpower232** [comment]
The maximum delivery attempts can be configured here
https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/config/postal.defaults.yml#L14

The retry interval already increases automatically, I think the code for that is here
https://github.com/postalhq/postal/blob/2595481b266199d8e29347dea2764f2c10202805/app/models/queued_message.rb#L97

There isn't normally a problem with this logic, the exponentially increasing retry interval is usually enough for most temporary problems.

If you click on "Show technical details" you should see why the message is failing.

**Comment by sheikhsherazali** [comment]
Many thanks for the great response. 

I would just like to know is there a file where we can code the rules for sending the emails related to domains

Such that 100 emails need to be sent in an hour for yahoo and similarly for Gmail.

Plus are there any extensions or plugins to increase the productivity of postal already in the market?

Does the postal support such type of expandablity.

**Comment by willpower232** [comment]
There is no configuration available as you describe.

Postal does not have any extension or plugin capacity. The source code is not concealed from you so any changes you want to make can be made if you want to code them.

**Comment by sheikhsherazali** [comment]
Many thanks, @willpower232 one of the best support are provided by you.
