### ISSUE TITLE
Err outputs for postal bundle command line (ruby version) ?

### ISSUE THREAD

**Issue by Keepshango** [postalhq/postal#1349]
**/// TEST ENVIRONMENT ///**
Machine : remote VPS 2vCore
OS distro : Ubuntu 18.04 (bionic beaver)
**User :  postal**
Web server : apache 2.4
Cpanel : ISPConfig 3.2.2

Hi, 

I installed the latest stable release that is **ruby 3.0.1 (running)**
(the latest shown in the output for “rvm list known“ is 3.0.0)

**/// AS POSTAL USER ///** 
Please also consider third and last **[UNSOLVED]** in **below command line outputs description**, and my **questions ending this post.**

[SOLVED]
At first launch, command line **“postal bundle /opt/postal/vendor/bundle“** could not find **“bundler 1.17.2“**, and prompted me to install it. **I did installed it successfully.** 

[SOLVED]
A second launch of **same command line** as above had output such this **issue message :**
_Your bundle is locked to **mimemagic (0.3.5)**, but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.5) has removed it. **You'll need to update your bundle to a version other than mimemagic (0.3.5)** that hasn't been removed in order to install._

Command line **“bundle update --conservative mimemagic**“ helped me to **get rid of this message**.

**[UNSOLVED]**
At third launch, command line **“postal bundle /opt/postal/vendor/bundle“** have output such this **other issue message :**
_**minitest-5.14.1** requires ruby version ~> 2.2**, which is incompatible with the **current version, ruby 3.0.1p64**_

**/// QUESTIONS ///** 

- Do I need “minitest-5.14.1“?
- If yes, what is recommended : upgrade “minitest-5.14.1“ to latest, or run ruby 2.2 instead of ruby 3.0.1 ?
- If no, can someone tell me what ruby version is actually recommended for POSTAL to run properly on my machine (see top of this post) ?

Regards

**Comment by willpower232** [comment]
It sounds like you aren't following the quick installer which is the recommended way of installing Postal for new users, it has recently been updated for Ubuntu 18.04
https://github.com/postalhq/postal/blob/a735219783127cd0495246ccee89422069da1a1c/script/install/ubuntu1804.sh

It also sounds like you are running other software on the same server as Postal, just so you know, this is likely to cause you problems as there might not be enough resources for everything you want to run. Postal is best installed on an otherwise empty server.

You will need to run at most Ruby 2.6 and at least Ruby 2.3 for Postal to install and work properly.

**Comment by Keepshango** [comment]
> this is likely to cause you problems as there might not be enough resources for everything you want to run

Thank U,

For now, only the ISPConfig control panel is installed, and it allows me to create several root directories, because I have indeed planned to install not only POSTAL, but other webapps on this remote VPS. But you seem to mean that my VPS is not capable enough to run other programs at side of POSTAL that is heavily disk resources consuming. 

Don’t you think that this commonly depends on what my VPS capacity is (infos below) and on how much resources other programs may require ?

**/// VPS CAPACITY ///**
2 vCore
4 Go 
80 Go SSD NVMe 
500 Mbit/s illimited*

**Comment by willpower232** [comment]
Mainly, Postal needs a lot of system resources so if you're running multiple web software applications on the same server as it, you will probably run out of resources.

The quick install script also installs nginx, MariaDB, and RabbitMQ which you may not want on the server or already have similar software set up so there can be a lot of collisions if you are not running the quick install on an empty server.
