### ISSUE TITLE
Configure postal on client requiring for PHPMailer settings ?

### ISSUE THREAD

**Issue by Keepshango** [postalhq/postal#1352]
**/// TEST ENVIRONMENT ///** 
Machine : remote VPS 2vCore
 OS distro : Ubuntu 18.04 (bionic beaver) 
**User : Postal** 
Web server : apache 2.4 
Cpanel : ISPConfig 3.2.2

Hi,

I do need Postal on remote VPS to relay messages sent from email marketing app on my laptop, but I wonder if someone ever experimented to configure it on Ubuntu OS, for a **client webapp that requires “PHPMailer“** or “**PHP mail()“settings**.
 I precisely think of one webapp of a kind, whose **notification email sending is automatically triggered on users various actions**. Parameters to be set are the followings :

Mailer : 
SMTP Host : 
SMTP Port : 
SMTP Username :
 SMTP password : 
From Email : SMTP Authentication : [0 or 1]

Is **Postal** only designed for email marketing , or **can it also be configured** (like Postfix) to get **“PHPMailer“** or “**PHP mail()“**.working on third-party OS ?

Regards

**Comment by willpower232** [comment]
Postal is designed to send any email message you give it, you can add an SMTP credential and then set up the details in whichever SMTP program you have (PHPMailer or mail()).

Postal is designed for transactional email, that doesn't stop you sending marketing emails with it but Postal has no marketing-specific features like mailing lists or campaigns.
