### ISSUE TITLE
Can other programs be run on a VPS at side of Postal ?

### ISSUE THREAD

**Issue by Keepshango** [postalhq/postal#1353]
Hi,

On a previous post I have been advised to install Postal on an empty server !
As this is not what I initially planned (and not my habit), may someone tell me why should I follow such an advice ?

I would greatly appreciate somehow documented reply.

Regards

**Comment by willpower232** [comment]
Mainly, Postal needs a lot of system resources so if you're running multiple web software applications on the same server as it, you will probably run out of resources.

The quick install script also installs nginx, MariaDB, and RabbitMQ which you may not want on the server or already have similar software set up so there can be a lot of collisions if you are not running the quick install on an empty server.

**Comment by sheikhsherazali** [comment]
Just one quick question if we run the docker instance of postal. Will there be still collisions. 

Just checking the same as it might be helpful for me as well to use one server for multiple things. 

Thanks for your awesome support @willpower232 

You are the best.

**Comment by willpower232** [comment]
Running in docker would allow you to pick how your ports work a little better so might help you depending on what else you're planning to run.
