### ISSUE TITLE
Routing not working with Address Endpoints

### ISSUE THREAD

**Issue by Faastio** [postalhq/postal#1356]
I set up postal and Mautic with no issues, and all DNS seems set up properly. I've configured an endpoint address as well as saved a route. Sent emails are delivered with no problem, but when I try to reply to test the routing, I never get a response into my endpoint mailbox.

![image](https://user-images.githubusercontent.com/83260431/116177093-3c08e380-a6e1-11eb-9dad-4b03cea8b783.png)

![image](https://user-images.githubusercontent.com/83260431/116177162-517e0d80-a6e1-11eb-8e73-6e3b0b8f6243.png)

**Comment by willpower232** [comment]
`afsbio.net` does indeed have `mx.postal.afsbio.net` as its MX record which is correct.

However `mx.postal.afsbio.net` does not seem to exist in DNS so your email messages don't go anywhere.

**Comment by Faastio** [comment]
> `afsbio.net` does indeed have `mx.postal.afsbio.net` as its MX record which is correct.
> 
> However `mx.postal.afsbio.net` does not seem to exist in DNS so your email messages don't go anywhere.

Thanks for your reply! Do you know I should do to add it to DNS?

**Comment by willpower232** [comment]
You should follow the information from the wiki here and enter all the records into your DNS provider https://github.com/postalhq/postal/wiki/Domains-&-DNS-Configuration

**Comment by Faastio** [comment]
`dns:
  mx_records:
    - postal.afsbio.net
  smtp_server_hostname: postal.afsbio.net
  spf_include: spf.postal.afsbio.net
  return_path: rp.postal.afsbio.net
  route_domain: routes.postal.afsbio.net
  track_domain: track.postal.afsbio.net
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp
`
The above is in my postal.yml file, and I've set up DNS domain routing below:

![image](https://user-images.githubusercontent.com/83260431/116287167-179f1c80-a75e-11eb-8340-7c1b1b3b3472.png)

As well as setting up the return path:
![image](https://user-images.githubusercontent.com/83260431/116288485-90eb3f00-a75f-11eb-8a35-cc54bde4fefe.png)

It is still not routing, please let me know if I did anything wrong!

**Comment by Faastio** [comment]
Fixed.
