### ISSUE TITLE
DNS not validated using internal dns

### ISSUE THREAD

**Issue by pcarr-m3** [postalhq/postal#1357]
In my environment I need to use dnsmasq to cache and route DNS queries, however I'm having a problem verifying the DNS config for my domain.  I'm also using Route53 split horizon DNS.  I have replicated the DNS records in both the public and private view.  I can manually look up via nslookup the records against each server, and have even added a static txt record in dnsmasq for DKIM but nothing works.  

The DNS record for DKIM is postal-SZHgxM._domainkey.domain.com.  I have verified that nslookup finds the correct record.

```
# nslookup -type=txt postal-SZHgxM._domainkey.domain.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
postal-SZHgxM._domainkey.domain.com   text = "v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCSsP2ehtFA235dud8yPaJJA9e0Ae7jC6/5DDBG4dD75KKlqG7J/c1bthPHLtueQRhuyyKZ9CbxQy7qZjzN+0G4mYBxewXeTEqhKwa1GtiKm4/WycJ4dj4yfUrCvV4TnT5TSu6yvW+OgomIPSHk+LhEbNOknkZ3Y0PxCOKmoXkQwIDAQAB;"
```

If I set resolv.conf directly to the AWS DNS listener nslookup finds the record but Postal will still not verify the record.

```
# nslookup -type=txt postal-SZHgxM._domainkey.domain.com 172.18.0.2
Server:         172.18.0.2
Address:        172.18.0.2#53

Non-authoritative answer:
postal-SZHgxM._domainkey.domain.com   text = "v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCSsP2ehtFA235dud8yPaJJA9e0Ae7jC6/5DDBG4dD75KKlqG7J/c1bthPHLtueQRhuyyKZ9CbxQy7qZjzN+0G4mYBxewXeTEqhKwa1GtiKm4/WycJ4dj4yfUrCvV4TnT5TSu6yvW+OgomIPSHk+LhEbNOknkZ3Y0PxCOKmoXkQwIDAQAB;"
```

If I set resolv.conf to 8.8.8.8 the DNS records verify successfully but that breaks other parts of the system.  

```
# nslookup -type=txt postal-SZHgxM._domainkey.domain.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
postal-SZHgxM._domainkey.domain.com   text = "v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCSsP2ehtFA235dud8yPaJJA9e0Ae7jC6/5DDBG4dD75KKlqG7J/c1bthPHLtueQRhuyyKZ9CbxQy7qZjzN+0G4mYBxewXeTEqhKwa1GtiKm4/WycJ4dj4yfUrCvV4TnT5TSu6yvW+OgomIPSHk+LhEbNOknkZ3Y0PxCOKmoXkQwIDAQAB;"
```

I don't understand why  Postal can't verify the record when nslookup and dig can find the record without any problem.  Can anyone help?

**Comment by willpower232** [comment]
Is it just the DKIM record that is affected or are the other ones not verifying either?

Postal does have a setting for using local nameservers which may be of use in this situation but it is in the config file so don't forget to restart Postal after setting it to true
https://github.com/postalhq/postal/blob/a735219783127cd0495246ccee89422069da1a1c/config/postal.defaults.yml#L17

**Comment by pcarr-m3** [comment]
Yes, that was the issue!  Thanks for pointing this out!
