### ISSUE TITLE
Add native support for systemd

### ISSUE THREAD

**Issue by isodude** [postalhq/postal#1359]
Since systemd offers the same features as procodile, is it possible to use systemd services directly on systemd systems?

An example
```
[Unit]
Description=Postal (smtp)
After=mysqld.service rabbitmq-server.service
Wants=mysqld.service rabbitmq-server.service

[Service]
Type=exec
User=postal

Environment="LOG_TO_STDOUT=true RAILS_LOG_TO_STDOUT=true"
ExecStart=/usr/bin/bundle exec rake postal:smtp_server
WorkingDirectory=/opt/postal/app
```

There are of course more options to add here, to lock down the service even further.

**Comment by willpower232** [comment]
I believe this is possible but definitely a more advanced and complicated setup IMHO. Officially, I think there is more interest in using Docker or Kubernetes as the basis than tying into systemd but if you want to give it a go and ask questions here, I would say that someone will find it useful.

On a less advanced level, Postal leaves it down to whoever installs it to ensure it is running when the server boots (or reboots). This already includes using systemd if that's how you want to do it.

This is covered in the wiki https://github.com/postalhq/postal/wiki/Starting-on-boot

**Comment by isodude** [comment]
What we did was adding one systemd service for each service, and adding them all to a target, which means you can easily restart all of them by systemctl restart postal.target. It would even be quite easy to integrate it into the `postal` command, letting the user run `postal restart` etc.

Should I add a PR for the docs or can I put the files in an example folder?

**Comment by willpower232** [comment]
if you want to PR against the existing resource folder, that seems to be the most appropriate. If you created a subfolder called systemd-by-process or something, you could include your files and a readme.

Even if it wasn't merged, it would still be useful information.

**Comment by isodude** [comment]
I will look into this.

**Comment by adamcooke** [comment]
Postal 2.x will run everything through a container and won't need support for systemd.

**Comment by arendvw** [comment]
> Postal 2.x will run everything through a container and won't need support for systemd.

Should you have a vanilla VPS with docker-compose installed, it did not automatically start postal on restart of the supervisor for me.

You can still use this systemd wrapper around the postal script. It expects a postal script symlink, but this should ultimately point to [install-git-repo]/bin/postal

Make sure that the docker service is enabled: systemctl enable docker


	[Unit]
	Description=Postal docker service
	After=network.target docker.service
	Wants=network-online.target docker.service

	[Service]
	Type=simple
	RemainAfterExit=true
	ExecStart=/usr/bin/postal start
	ExecStop=/usr/bin/postal stop

	[Install]
	WantedBy=multi-user.target
