### ISSUE TITLE
How to add preheader and sender name to an email?

### ISSUE THREAD

**Issue by ramioooz** [postalhq/postal#1364]
Hello Postal team,

I would like to add a preheader text in the emails I am sending using postal
I don't find a way or documentation about that.
I'd also like to know how to add a name for my sender besides the email address. something like :
Support Team, support@myserver.com

Your feed back is much appreciated,
Thank you

**Comment by willpower232** [comment]
This is entirely down to how you make the email message. Your software should allow you to specify a from name for SMTP or if you are using the API then you may need to make use of an extra argument.

**Comment by ramioooz** [comment]
> This is entirely down to how you make the email message. Your software should allow you to specify a from name for SMTP or if you are using the API then you may need to make use of an extra argument.

Hello @willpower232 ,
Thank you very much  for your reply,
Yes, I am using API access to postal to send emails. but I don't know how to make use of an **extra argument.** 
I could not find details about it in Send message/API documentation found here: 
https://krystal.github.io/postal-api/controllers/send/message.html

would you please show us how to do it?
Thank you

**Comment by willpower232** [comment]
Postal has a variety of API libraries which could make your development a little easier

https://github.com/krystal?q=postal

However it seems I was slightly mistaken but anyway the expected format would be something like `Support Team <support@myserver.com>`

**Comment by ramioooz** [comment]
> Postal has a variety of API libraries which could make your development a little easier
> 
> https://github.com/krystal?q=postal
> 
> However it seems I was slightly mistaken but anyway the expected format would be something like `Support Team <support@myserver.com>`

I tried that and it works.
instead of sending email to :
`support@myserver.com
`I added the name I wanted to the front  of the email address and put  the email between <> signs, just like you mention:
`Support Team <support@myserver.com>
`
Thank you very much for that 👌.

regarding the **preheader** 
I found out it is something I should add to the body of the  HTML version  of  my  email as described here:
https://stackoverflow.com/questions/32888872/how-to-define-html-email-preheader

Ok, I think that's all. I will close this issue now. 
feel free to re-open it should you wanted to add anything related here.

Thank you
