### ISSUE TITLE
Changing Postal Port from 25 to 2525

### ISSUE THREAD

**Issue by pranavmishra** [postalhq/postal#1365]
Hi, 

I want to change postal server port for mail sending from 25 to 2525??

Can I do it via the Postal.yml? & will it work or is there any other way?

**Comment by willpower232** [comment]
You can change it in the config if you like however you will not be able to receive any bounces to your emails.

If you'd like to receive on 25 and 2525, have a look at #565

**Comment by pranavmishra** [comment]
But, in my configuration the default port mentioned in 2525 itself but whenever I'm trying to connect to 2525 it's not work & it's only connecting via port 25.

![image](https://user-images.githubusercontent.com/4854070/117674527-5bb40780-b1c9-11eb-8161-edd5c0dca227.png)
