### ISSUE TITLE
Problem conecting with another APP with starttls, and return a timeout

### ISSUE THREAD

**Issue by marcodavilates** [postalhq/postal#1366]
I'm trying to connect with an app called neverspam, and I put the credentials, and the server returns a timeout. I used port 25
![image](https://user-images.githubusercontent.com/61389946/117749749-4a2a2a00-b1e0-11eb-844d-71d9263b4ccf.png)

**Comment by marcodavilates** [comment]
Or how is the procees to do it?

**Comment by willpower232** [comment]
You need to change these settings in your main Postal config file if you haven't already

https://github.com/postalhq/postal/blob/a735219783127cd0495246ccee89422069da1a1c/config/postal.defaults.yml#L75-L77

You can either buy a certificate or use a Lets Encrypt generated one for free, you should be able to re use whatever certificate you're using to make the UI HTTPS.
