### ISSUE TITLE
Cannot access to server by postal web aplication 

### ISSUE THREAD

**Issue by MrPeanutButter99** [postalhq/postal#1367]
Hi,

I have a problem with the postal web interface. I can work in the server by console and the server is running okay. But, when i try to see the server in the postal web client i see this error.

![image](https://user-images.githubusercontent.com/72225358/118533538-9284a300-b71e-11eb-8a5a-1a9b0df76ed7.png)

Plus, the problem happen when i try to enter in the server (web client). I can log me in the postal web client and see the organizations there. But when i go to te server of the organization i see the error

![image](https://user-images.githubusercontent.com/72225358/118533503-88fb3b00-b71e-11eb-89e0-c8b065ead369.png)

I think is a problem with some table of the DB.

I hope you can help me

Thank you!

**Comment by willpower232** [comment]
> I think is a problem with some table of the DB.

This is certainly a possibility, you will need to look in the log files to see what has happened.
