### ISSUE TITLE
Django and postal email integration

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1370]
Hi, i am configuring Django python to integrate with the postal email server using the SMTP credentials. Here are the details of my configuration:

DEFAULT_FROM_EMAIL = 'test@mydomain.com'
EMAIL_BACKEND = 'django.core.mail.backend.EmailBackend'
EMAIL_PORT = 25
EMAIL_USE_TLS = True
EMAIL_HOST ='mypostalserver.com'
EMAIL_HOST_USER = 'SMTP username'
EMAIL_HOST_PASSWORD = 'SMTP somepassword'

However, i am getting this error

SMTPConnectError at /api/v1/mail/
(451, b'Spam email. Email Session ID: {60A76166-6-4274C-F5E89638}')
Request Method:    GET
Request URL:    http://127.0.0.1:8000/api/v1/mail/
Django Version:    3.2.2
Exception Type:    SMTPConnectError
Exception Value:    
(451, b'Spam email. Email Session ID: {60A76166-6-4274C-F5E89638}')

Am I missing something ???

**Comment by willpower232** [comment]
I presume `/api/v1/mail/` is your own app rather than part of Postal?

Are you able to see the `smtp_server.log` logs from your Postal server to see what communication did happen?

**Comment by gitaayush** [comment]
yes /api/v1/mail is my own app. As my app is unable to communicate with postal i dont have any smpt_server.log related to my app.

**Comment by willpower232** [comment]
`smtp_server.log` should feature at least a few lines regarding your app unless it has completely failed to find your server at all (i.e. your server address or port is wrong)

If these are definitely correct, you could try setting `EMAIL_USE_TLS` to false to see if that helps. That would indicate that you haven't set up a certificate for `smtp_server` in the config file.

**Comment by gitaayush** [comment]
Hi @willpower232, the api issues has been resolved. It was due to the misconfiguration on the django part. 
Thank you for the response.
