### ISSUE TITLE
Messages pending in the queue.

### ISSUE THREAD

**Issue by legolas145** [postalhq/postal#1371]
Hi  I have set up a email server using postal.I was getting the emails fine but all of a sudden the messages got starting to get queued in the message queue with pending status with message stating that 'No delivery attempts yet.'Here are the few things i noticed

1.Have tried restarting the postal server.But still the issue seems to be persisting.The postal status shows all the components of the mail server to be in running state.
2.I noticed that in the log files of the worker.log there seems to be an error like 
[worker.4:3866] [2021-05-25T16:12:56.912] WARN -- :  NoMethodError: undefined method `find_by_id' for #<Class:0x000055fd307a0570>.Is this error something that is resulting in the messages not being sent from the queue?If so what might be the fix for it.
3.My server cpu and memory seems to be under 50% utilization.
4.I even tried flushing out the data in the queued_messages table.But still the newer messages coming in are stuck at pending status with 'No delivery attempts yet.'
5.I also noticed that the locked by,locked at and retry after values are NULL for all the entries in the queued_messages table.What might be the reason for it?

On an another note is there like an architectural diagram for the email server that you guys have written? I want to know how the overall system works.That would be greatly helpful.

Thanks in advance!

**Comment by willpower232** [comment]
Can you share the output of `postal status`? That would confirm that all parts of Postal are running.

There is not an architectural diagram that I am aware of, you can see here that Postal is made up of 6 processes (5 if you are not using click tracking) 
https://github.com/postalhq/postal/blob/master/Procfile

**Comment by legolas145** [comment]
Hi 
I have attached below the snapshot of the postal status.
![image](https://user-images.githubusercontent.com/50871534/120017539-9dcfac80-c003-11eb-991d-6a5c638d924b.png)

**Comment by willpower232** [comment]
Looks like you've already eliminated all the usual suspects then.

The log entry you mentioned can we see it and any following lines which may be related?

**Comment by charlesmudy** [comment]
I am having this issue too, over 9K messages are currently in queue and no clue what to do with them.

Any ideas how to retry them? I used this code: `Server['yournotify/yournotify'].message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }` but it seems I have to now manually release them which I don't want.

How to force retry all messages in queue/held mode?
