### ISSUE TITLE
Mail status and rabbitmq service error.

### ISSUE THREAD

**Issue by applewood524** [postalhq/postal#1372]
I have some problems. 
All mails are pending now and so I had checked server's status.
All status are fine. 
But I can not run rabbitmq service.
I think this is the reason what all mails are pending.
If I run "sudo rabbitmqctl start_app" command, 
![image](https://user-images.githubusercontent.com/75241560/119598673-f5102a00-be15-11eb-9cf8-31b50708daef.png)
like this message appear.
Please help me.
Best Regards.

**Comment by willpower232** [comment]
Its likely that RabbitMQ is already running and being managed by systemd.

If you run `netstat -lnp` you should see whether something is already running on that port.

If it is, you can verify systemd is running it with `sudo systemctl status rabbitmq-server.service`

**Comment by applewood524** [comment]
thanks suppert.
![Uploading image.png…]()

**Comment by applewood524** [comment]
thanks to support.
I have done your command but the result is like this.
![image](https://user-images.githubusercontent.com/75241560/119658828-27df1000-be60-11eb-943b-809a91a786bc.png)

**Comment by willpower232** [comment]
What was the output of `netstat -lnp`?

**Comment by applewood524** [comment]
![image](https://user-images.githubusercontent.com/75241560/119707459-bfa72300-be8d-11eb-92fa-9608f23c9d95.png)

Thanks.

**Comment by willpower232** [comment]
you can see that your computer already has something on port 4369 which means either you have multiple RabbitMQs trying to run or something else has been configured to use that port.

If you re run the command with `sudo` then it may be able to tell you which program is responsible.

**Comment by applewood524** [comment]
How can I fix it?
How can I restart finally? I already have done it but something went same.
So hope you help me.
Thanks for good service.

**Comment by willpower232** [comment]
If you run `sudo netstat -lnp` then you'll see exactly what is using `:::4369`
