### ISSUE TITLE
Wildcard IP-rule?

### ISSUE THREAD

**Issue by olegbliaher** [postalhq/postal#1373]
Hi there,

I have a Server within my Postal server with a designated credential and an IP-pool. I would like so that any email sent with these credentials, with any From-address (I've allowed Sender Header for that Server), will be sent with the designated IP-pool, and not the server's default IP. E.g without adding every domain name to Settings -> IP Rules on that Server.

Can that be accomplished? Thanks

**Comment by willpower232** [comment]
I'm not that familiar with IP Pools but are IP Rules actually required to make use of the Pool?

**Comment by olegbliaher** [comment]
@willpower232 I've tried sending emails without IP rules, without rules emails just get sent with the server's main/default IP.

**Comment by willpower232** [comment]
I guess that is your answer then, you'll have to add the domains you wish to send from to Postal one way or the other.
