### ISSUE TITLE
SPAM issues 

### ISSUE THREAD

**Issue by gitaayush** [postalhq/postal#1374]
Hello every one,

 Recently i am facing trouble with my emails going through postal to spam on gmails and outlook.  I am using my Django application to connect to postal via API. I have also added mydomain.com in domain section and added the spf and dkim records. Postal has verified my domain. However when I test my email using mail tester my score is below 5.  The report states that the DKIM signature is not valid and also the following message:

-1.985 | PYZOR_CHECK | Similar message reported on Pyzor (http://pyzor.org)https://pyzor.readthedocs.io/en/latest/Please test a real content, test Newsletters will always be flagged by PyzorAdjust your message or request whitelisting (http://public.pyzor.org/whitelist/)
-- | -- | --

Why is my dkim records being rejected ???

**Comment by willpower232** [comment]
Have you verified that your DKIM record is working around the world with https://whatsmydns.net?

**Comment by gitaayush** [comment]
hello @willpower232  the Txt records in whatsmydns.net shows the correct spf records and i have added the google site verification as my txt record. So overall the records are working around the world. Also, it is necessary to add the domain in postal when they are only connected via API ??  I think there is a mismatch in dkim as i am using the dkim selector provided by postal but the message header content is searching for the selector s=domain

**Comment by willpower232** [comment]
You will need to add every domain you intend to send from (or have as sender header) to Postal otherwise Postal will reject your attempt.

Can you link to your email test results?

**Comment by gitaayush** [comment]
the spam score is now 9.8 out of 10. But still the emails are landing on the SPAM. I also have added the google domain verification as txt record for verifying the domain which is a requirement for google. But still it lands in spam.  Howeve i think the spam issues is related to the ip reputation as both my ip's are fresh.

**Comment by willpower232** [comment]
If you have a high score then there is not a lot more that you can do other than pleading with Google directly
