### ISSUE TITLE
Install Script doesn't work any more.

### ISSUE THREAD

**Issue by compwiz21** [postalhq/postal#1375]
Can we get a new install script for Ubuntu 18.04 or 20? Thank you.

**Comment by andrekutianski** [comment]
same on #777

**Comment by willpower232** [comment]
Unfortunately #1294 and #1324 are blocking new installations right now

**Comment by Trapulo** [comment]
is there any official docker version?

**Comment by willpower232** [comment]
There is an official Dockerfile if you wanted to build your own image.
