### ISSUE TITLE
Infinite loop in resolv after 64k DNS-lookups

### ISSUE THREAD

**Issue by elektro-wolle** [postalhq/postal#1377]
After several days, the postal bundle uses 100% CPU, caused by https://github.com/ruby/resolv/issues/11
Unless a version 0.3.0 of `resolv` is released, the current master could be used in the Gemfile:

```
gem 'resolv', :git => 'https://github.com/ruby/resolv.git', :branch => 'master'
```

**Comment by willpower232** [comment]
Good to know, thanks for sharing. It looks like they've released 0.2.1 now so does that resolve the problem for you? (pun unintended)

**Comment by elektro-wolle** [comment]
Added PR #1381 as a quick fix.

**Comment by ArmiT** [comment]
We have the same problem on our "postal" instance.
Do you have an idea when there will be a release with the fix?
