### ISSUE TITLE
New Feature: Official Docker Image

### ISSUE THREAD

**Issue by jaydrogers** [postalhq/postal#1379]
Hey folks,

We have an ongoing discussion with the future of Postal here: #917 

Long story short for the discussion above:
* @adamcooke is busy with life and we're grateful for his work. Although he is busy, it is best for Postal to wait until he has more freetime. The best way to revive Postal is to have @adamcooke come up with a testing suite for the core, then accept updates from there (to make sure nothing gets broken)

# Problem
* Postal is continuing to get stale and is becoming difficult to make this app "disposable and repeatable"
* As our production servers get older, the more difficult this becomes to bring these services back up if there was a server failure

# Proposed solution
Create an official docker image on GitHub Container Registry.

**☝️ Creating an official Docker Image solves many problems:**
* The entire app becomes "disposable & repeatable"
* There is a "single source of truth" on how the app should be deployed
* Installations will be _**much**_ easier than dealing with all the intricacies of legacy dependencies

# Proof of demand
There are a number of discussions all asking the same questions:
* #1008
* #777
* #1071
* #1288
* #974 
* #1265

# What "done" looks like
- [x] Having an official image hosted on [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/)
- [x] Creating documentation on how to run that image (which volumes to mount, sample Docker commands, sample Docker Compose file, etc)
- [x] Automate image updates via Github Actions (**when manually tagged for release**)

**Comment by willpower232** [comment]
This is definitely a great idea, there is already an official Dockerfile but it is tailored more towards a kubernetes style environment so it might be nice to have an official docker-compose to include all the necessary processes because the Dockerfile is missing Procodile so could be confusing to new users in the absence of any documentation.

Regarding docker hub, whilst that would be the default, they recently changed their policies so that freely hosted images are removed if not pulled for some time so I think it might be better to make use of githubs registry instead. This would also make it easier for github actions to create the image.

That said, before any automation should be trusted, Postal would need a test suite to guarantee that the master branch functions before automatically rolling out an image to everyone.

**Comment by jaydrogers** [comment]
Great points!

I just updated the original comment to have:

- Docker image stored with GitHub Container Registry
- Automated build **on manually tagged release**

@adamcooke: Would you support something like this above?

**Comment by lucaforni** [comment]
How do you think to manage ip pools in container environment (docker or kubernetes)?

**Comment by jaydrogers** [comment]
Just wanted to give everyone an update on this. I spoke with @adamcooke today on Slack.

### Tentative plan is:
1. @adamcooke will start working on getting the deployments configured
2. We'll then work on the documentation to get the existing app deployed. Examples and easy onboarding will be provided as well

### Full conversation
Just to keep discussions organized, I wanted to include a screenshot of the discussion regarding this issue.

![Slack](https://user-images.githubusercontent.com/3174134/121707767-87623000-ca9c-11eb-87b0-91937d0dfba7.jpg)

**Comment by willpower232** [comment]
@lucaforni Docker should be relatively straightforward as its all on the same host so you could map the IP addresses (or run it in host networking which is less good long term) however kubernetes would be more challenging as its networking is much more advanced and multi layered.

**Comment by jaydrogers** [comment]
We can definitely provide examples on this as we go too.

I am currently not running Kubernetes in production, but I think if we start with Docker and go from there, we'll just keep making it easier for people to run.

**Comment by dtrckd** [comment]
Hi there,

I just wanted to mention two independent projects that dockerized Postal (with docker-compose) : 
- https://github.com/tiredofit/docker-postal
- https://github.com/CatDeployed/docker-postal

I am currently working with the second one, which deploy fine.
Maybe it can help.

**Comment by RamonSmit** [comment]
Yes, I'm using `CatDeployed/docker-postal` too, I've created some kubernetes specs for it too so I can run this inside my cluster. If any help is needed, give me a notice.

**Comment by willpower232** [comment]
Those projects are definitely interesting however the official Dockerfile is geared towards running each part of Postal separately (i.e. replacing procodile with kubernetes itself) so there will be some significant differences in the final product.

**Comment by RamonSmit** [comment]
Thats totally fine. When you're ready, I'm willing to create some awesome yaml files or helm charts to make this happen.

**Comment by cedricve** [comment]
Is there any update on this? I would spin this up directly. Awesome stuff!!

**Comment by jaydrogers** [comment]
I followed up yesterday with Adam in the Slack channel. This is what he posted 🥳

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/3174134/125621728-8f93e63d-769d-4e9f-a5e7-c189cc25c2a6.png">

**Comment by cedricve** [comment]
Great news @jaydrogers ;)

**Comment by jaydrogers** [comment]
Just letting everyone know that @adamcooke was able to publish his first iteration of an official docker install: https://github.com/postalhq/install

More details on the Slack channel:
![image](https://user-images.githubusercontent.com/3174134/127224805-e1816b4f-b2c3-420f-990a-766a9533d0f7.png)
