### ISSUE TITLE
Sender address rejected: Domain not found

### ISSUE THREAD

**Issue by geist-ahnen** [postalhq/postal#1380]
Hi!

### PROBLEM

When I try to send an email to the following email example@pucp.edu.pe (which is in Peru) from Spain I got the following error

Temporary SMTP delivery error when sending to alcione.pucp.edu.pe (200.16.1.214)
450 4.1.8 <f2anry@psrp.emailsender.club>: Sender address rejected: Domain not found
Time: 0.74s
Support Ref: SUJ9N7CW

### CURRENT CONFIG

This is my current configuration is

  mx_records:
    - smtp.emailsender.club
  smtp_server_hostname: smtp.emailsender.club
  spf_include: spf.smtp.emailsender.club
  return_path: rp.smtp.emailsender.club
  route_domain: routes.smtp.emailsender.club
  track_domain: track.smtp.emailsender.club

Current DNS config:

smtp.emailsender.club. | 1200 | IN | A | 62.171.146.178
www.smtp.emailsender.club. | 1200 | IN | A | 62.171.146.178
smtp.emailsender.club. | 1200 | IN | AAAA | 2a02:c207:2060:2377:0:0:0:1
postal._domainkey.rp.smtp.emailsender.club. | 1200 | IN | TXT -> value generated by postal default-dkim-record
rp.smtp.emailsender.club. | 1200 | IN | MX | Priority:&nbsp;10Destination:&nbsp;smtp.emailsender.club
rp.smtp.emailsender.club. | 1200 | IN | A | 62.171.146.178
rp.smtp.emailsender.club. | 1200 | IN | AAAA | 2a02:c207:2060:2377:0:0:0:1
rp.smtp.emailsender.club. | 1200 | IN | TXT | "v=spf1 a mx include:spf.smtp.emailsender.club ~all"

### SOLUTION TRIED
I changed my VPS nameserver to use google's 8.8.8.8, but the problem persists. 

Is there any configuration extra I need to add so I don't get that error?

The rest of the emails work fine, especially Gmail.

**Comment by willpower232** [comment]
It seems their email server does not like something about how the return path has been set up. This is likely not your fault.

It is possible that you only set up the domain recently and their system hadn't picked up the new records at the time. Are you still getting these bounces?

**Comment by geist-ahnen** [comment]
@willpower232 

Thanks a lot for your reply. Yes, my domain and server have only 3 days, so they are fairly new. Would you recommend to sit a wait and try again in a 1 week or so? 

I am still getting the bounces, yes.

**Comment by willpower232** [comment]
Glad that sorted itself out, re hotmail you should have a look at using a checker like this one to see if you're on any lists https://mxtoolbox.com/blacklists.aspx

You can find out who manages any list that you're on and they will have some kind of removal system to try.

**Comment by geist-ahnen** [comment]
@willpower232 

Great. Please mark this as resolved.
