### ISSUE TITLE
Multiple HTTP endpoints for multiple domains?

### ISSUE THREAD

**Issue by olegbliaher** [postalhq/postal#1382]
Hi there,

I have a postal server with lots of different organizations, with one domain per organization.

I'd like to route the bounces to an HTTP endpoint. I am doing this successfully with one organization/server, but when I try to add it on another I get the following error:

`A return path route already exists for this server`

I am simply writing `__returnpath__` (without domain) under **NAME**. So I can see how it becomes a duplicate (without a server following). But is there any way to patch it easily? I'm not a ruby expert as you might have guessed...

I am running postal 1.0.0-1ef7dbd67e-stable.

**Comment by willpower232** [comment]
There is not a code problem here, there can only be one return path route per server so if you want multiple, you will need multiple servers.

**Comment by olegbliaher** [comment]
@willpower232 Does that mean that if I have the following structure on my server:

Organization 1
  `firstdomain.com`
  
Organization 2
  `seconddomain.com`
  
I can only set up one single return path route, for only one of those domains? And that if I have it set up for `firstdomain.com` then I must move `seconddomain.com` to a separate Postal service altogether, if I want to be able to forward the bounces to an HTTP endpoint?

**Comment by willpower232** [comment]
Oh sorry I misread your setup, that is odd. I'll give it a try later to see if I can reproduce

**Comment by willpower232** [comment]
This seems to be working for me unless I've missed something...

![image](https://user-images.githubusercontent.com/1619102/121059188-14656a80-c7b9-11eb-9b94-53f2003a401c.png)

**Comment by olegbliaher** [comment]
The HTTP Endpoints are not a problem to set up, the Routes are. I was following the documentation here: https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces

> If you wish to route mail which is sent to your return path address to your application, you can set up a return path route. This is the same as a normal route except you should enter the name as __returnpath__ and leave the domain field blank. You can only choose HTTP endpoints for this type of route. Once added, messages sent to your return path that aren't detected as bounces will be sent to HTTP endpoint you choose.

However, it seems to be working as it should if I *do* select the domain name, as well as enter __returnpath_ before the *@*. Otherwise I simply get this error: `A return path route already exists for this server`.
