### ISSUE TITLE
Anyone Knows How To Connect Desktop Mailer To Postal If Port 25 Has Been Block By Local ISP?

### ISSUE THREAD

**Issue by dxxbdoobdxxb** [postalhq/postal#1383]
I've tried vpn, proxies and they appear to block port 25 as well.
Anyone has any creative ways to get Postal SMTP to work in desktop emailer?

**Comment by willpower232** [comment]
If your server provider is blocking port 25, it is unlikely you will be able to work around it. Even if you can get your messages into Postal, they will not be able to be sent to other mail servers.

**Comment by dxxbdoobdxxb** [comment]
:( sad for me.. looks like I need to use webmailers instead zzz
