### ISSUE TITLE
Change Main IP of Postal

### ISSUE THREAD

**Issue by dhiraj-r** [postalhq/postal#1386]
Hi, 

My VPS has multiple IPs and it was preconfigured into the server. When I installed Postal, to my surprise, it picked up a rotating IP as the main IP. I want to change that to main IP. I do not have any other issue with VPS.
Any idea would he helpful.

Thank you.

**Comment by willpower232** [comment]
You should make use of IP Pools to limit which outgoing IP addresses are used by your Postal installation.

You can see more here https://github.com/postalhq/postal/wiki/Configuring-IP-Pools

**Comment by dhiraj-r** [comment]
Yeah, I figured it out. Thanks for your support.
