### ISSUE TITLE
email stay pending

### ISSUE THREAD

**Issue by david0003** [postalhq/postal#1387]
Hi, I’m david -I build my system postal but when I check the postal status :
worker.1 is not running (Failed)
requeuer.1 is not running (Failed) i have the 25 port Open but when i send email whith mautic or with smtper tester he stay pending... help please

**Comment by david0003** [comment]
there is  the output of postal status
![statu1](https://user-images.githubusercontent.com/85866422/121857995-714fac00-ccf6-11eb-9898-1370dbcba4ae.png)
![statu2](https://user-images.githubusercontent.com/85866422/121858011-76146000-ccf6-11eb-9f0f-c1bfe8a0f24a.png)

**Comment by david0003** [comment]
also when I test to send from smtper.net I receive this error
SMTP send error
Failure sending mail.
Unable to read data from the transport connection: The connection was closed.

**Comment by willpower232** [comment]
Without the worker and requeuer, your Postal cannot send any emails. You will need to figure out what is wrong with them.

You should be able to see any error messages in the logs or you can try running the command shown in `postal status` as the user postal to see what the output is directly.

**Comment by david0003** [comment]
> Without the worker and requeuer, your Postal cannot send any emails. You will need to figure out what is wrong with them.
> 
> You should be able to see any error messages in the logs or you can try running the command shown in `postal status` as the user postal to see what the output is directly.

How do I try running the command shown in postal status as the user postal...
sorry I'm new to this field

**Comment by willpower232** [comment]
You can see in `postal status` that each part of Postal has a `Command:` which starts with `bundle exec` so if you did something like

`sudo -u postal bundle exec rake postal:requeuer` then you should see some error output to tell you what problem it is having

**Comment by medito** [comment]
Hi @willpower232, 
How we can configure workers manually please ?
Thanks.

**Comment by Greg1116** [comment]
I am having this same issue
I have set up an SMTP server and installed Postal

When I send a test email / my email says "Pending"

smtper.net I receive this error:

**SMTP send error
Failure sending mail.
Unable to read data from the transport connection: The connection was closed.**

Gmail responded:
530 Authentication required

When I run Postal Status:

root@postal:~# postal status
      Name                     Command               State    Ports
-------------------------------------------------------------------
postal_cron_1       /docker-entrypoint.sh post ...   Up
postal_requeuer_1   /docker-entrypoint.sh post ...   Exit 1
postal_smtp_1       /docker-entrypoint.sh post ...   Up
postal_web_1        /docker-entrypoint.sh post ...   Up
postal_worker_1     /docker-entrypoint.sh post ...   Exit 1

How do I get all of these to say "up" ??
Please help..

Greg

**Comment by mail2sathishkumar008** [comment]
@Greg1116 Im also facing the same issue. u resolved it?

**Comment by logicdelta** [comment]
I also facing the same issue

SMTP send error
Failure sending mail.
Unable to read data from the transport connection: The connection was closed.

Any one resolved it?

**Comment by logicdelta** [comment]
Found the solution for my issue. In my case Rabbitmq was not connecting.
