### ISSUE TITLE
Unable to add SPF to domain as CNAME already uses the TXT Value

### ISSUE THREAD

**Issue by biswajitnet** [postalhq/postal#1392]
Hello All, 

I came across a scenario where I am unable to add SPF records to my host because the CNAME already exists with the same txt value. 
in my case: I have a cname going from psrp.domain.com to rp.postal.domain.com

Now When I run a mail-tester scan- I am getting no valid spf found. The issue is I ve an SPF for @ TXT Value. but unable to add SPF on psrp again because cname uses the same name. 
Is there  a solution that I am missing here. I can share the domain name personally. 

![image](https://user-images.githubusercontent.com/67558955/123306069-71de1300-d53e-11eb-86a9-d577793f9998.png)

How to get this fixed. I am just 1 point away on Mail-tester and want to nail it. 
![image](https://user-images.githubusercontent.com/67558955/123306231-a81b9280-d53e-11eb-9c19-eaf3f71b8ee0.png)

Regards,
Biswajit.

**Comment by biswajitnet** [comment]
@willpower232  Can you guide me on this, please!

**Comment by willpower232** [comment]
Unfortunately a CNAME means that all records for that subdomain get passed on so the only resolution for this problem is to use A/AAAA records instead
