### ISSUE TITLE
Latest Version not sending with default STARTTLS over the Secure MIME

### ISSUE THREAD

**Issue by rccess** [postalhq/postal#1397]
Hello Community 

Latest Postal version not picking **MIME** over the STARTTLS Default encryption which were used in past version

![image](https://user-images.githubusercontent.com/32220165/124222363-3c798c80-db1f-11eb-88fe-717c9a454b93.png)

is there anything which should be configured in Latest version

**Comment by willpower232** [comment]
#1344 suggests it was previously possible.

Have you definitely configured these settings?

https://github.com/postalhq/postal/blob/8145dba1576256b2e659d6419cfada087b748a59/config/postal.defaults.yml#L73-L77

**Comment by rccess** [comment]
Defined tls key properly and send email over tls but red lock still showing in mail

please do advise ,

In previous postal without tls it took starttls by default but not taking in latest version

**Comment by rccess** [comment]
any update , on the same ?

**Comment by willpower232** [comment]
Did you restart Postal after changing the settings? Have you tested that the postal user can access the files you have specified?

**Comment by rccess** [comment]
restarted and reboot the system , 

checked 
smtp_server.log 

.pem files are reading by the server but red lock 
![image](https://user-images.githubusercontent.com/32220165/124452023-a013ec00-dda3-11eb-8e8c-784c166f6f8f.png)
 not removed on receiving the same (gmail).

the important point is that 

Last time we deployed postal many times and we never received red lock on gmail but not i have installed more than 6 postal on different servers each receiving red lock
--------------------------------------
Old Postal:
SMTP host: xxxxxxxx
Port: 587
Use SLL: False
Use Authentication: True
Authentication name: support
Authentication password: [not applicable]
Email from: info@xxxxxxxo.cxxxxxe
Email to: fexxxxxxxxxx@gmail.com
**Old Postal**
![image](https://user-images.githubusercontent.com/32220165/124451269-d866fa80-dda2-11eb-8d67-b025f717f597.png)

**New postal** 
![image](https://user-images.githubusercontent.com/32220165/124451837-6e9b2080-dda3-11eb-9033-6b275a4f6601.png)


SMTP host: xxxxxxxxxx
Port:  587
Use SLL: False
Use Authentication: True
Authentication name: smtp1
Authentication password: [not applicable]
Email from: info@xxxxxxx.xrx
Email to: fexxxxxxxxxx@gmail.com

--------------------------------------------
Old postal without TLS/SSL >> no redlock
New (Latest Postal) without TLS/SSL or with TLS >> 
![image](https://user-images.githubusercontent.com/32220165/124451990-99857480-dda3-11eb-87bf-76c455baf799.png)
 redlock

**Comment by willpower232** [comment]
Comparing the old postal and the new postal screenshots, it looks like the mailed-by is quite different when it should look somewhat similar so have you changed how you set up the domains are they accidentally different?

**Comment by rccess** [comment]
Mailed by just a spf for 2 different domain

major challenge is red lock is not removing with or without tls which were not happen in older postal version

i think it is related to some ruby version 
Because auto installer script is not working for any server (Ubuntu16 and Ubuntu 18)

**Comment by rccess** [comment]
The logs for TLS 
-------------------------------------------
root@vmta:~# openssl s_client -connect hxxta.xxxxxxxxa.online:587 -starttls smtp
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = hxxta.xxxxxxxxa.online
verify return:1
---
Certificate chain
 0 s:CN = hxxta.xxxxxxxxa.online
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFLDCCBBSgAwIBAgISBFp2e/KL3e6I7iyVupM74GqdMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTA3MDUxMDA0MTZaFw0yMTEwMDMxMDA0MTVaMB4xHDAaBgNVBAMT
E2htdGEubWlnb210YS5vbmxpbmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDNCtj8ZxX8BcF0TwePdK4vqJNHU/jjKvwBI1KNRMuk0T2tvfEyG4uuWDPl
aZ2tTwe4rPPudXFY8hbbvdH8czUs6ZBHZrm2BavaErmhNFcRc9ZyniMcdyLvZApJ
+x+t+u+A4a7o5Lng+Gifnfe8eyjmK36jGVP+/LfQMDnNq4m/Famsbqt5Vxy718kt
OiM56bemEi21wH+jBkyqqwVBd5TAgrMrMlOMEVcjgmhPxkcqtlxdiJqkGyiSo0Jt
rdAhs6x8rb31DClpRfOBq7cbN2g2i9tA3TKnkedpPnIwd7PXQ/loutqzbJOyzcWn
JrFv1naT6mm/TYBbSPv24wUVHJnNAgMBAAGjggJOMIICSjAOBgNVHQ8BAf8EBAMC
BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
HQYDVR0OBBYEFKWNZptHNppL8JMZXq7DjHwSbN8fMB8GA1UdIwQYMBaAFBQusxe3
WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0
cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5j
ci5vcmcvMB4GA1UdEQQXMBWCE2htdGEubWlnb210YS5vbmxpbmUwTAYDVR0gBEUw
QzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDov
L2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgBE
lGUusO7Or8RAB9io/ijA2uaCvtjLMbU/0zOWtbaBqAAAAXp2VxexAAAEAwBHMEUC
IQDmisVSWSTy47AOkqQXgXZ4M5WZIgilvA0yky94IgvRwgIgWfidpDpKBibiVk2C
LTMdqssX0g2YXakK1vRql2gMayAAdgB9PvL4j/+IVWgkwsDKnlKJeSvFDngJfy5q
l2iZfiLw1wAAAXp2VxfOAAAEAwBHMEUCIQDm4Lx8rmXIYSPIsHget43MGRFKADxW
PYVqIUflps9AsAIgPTb5NfMZDjP4CZIer+GYFFEjPOlEASqdhqmzxUjmc14wDQYJ
KoZIhvcNAQELBQADggEBAIr0HYrL7UrlVgVphW+bXEVDnQUO46zOGvXkUmchjzwn
vNoOIjhFKlGWpSR+JAJXWe7mtxyAvY8JnfyfDv1Mq2zjLQQwFO14HAGwJics9VQv
3lecDoK8PZ7etKUNfJ1tHOOtoRXFCLyP5n2fTBxqyZl1YxqrfNKcgASbzfKxqXr/
BJu6PjWEdFnZzdZ54rRVAoQkYE90LxLEJoePPsfyfbNeY3SXyZXsBrE4sgj1x13e
yUW7BcvFytUpAgudxI7CbFBawKGBwev9CqrbYImcBcDsv8jPUDJ3QVn021nepffX
kFuLUZDX+XYKsNlm8S4flBP7SGkGan6QjI1dzZgmcts=
-----END CERTIFICATE-----
subject=CN = hxxta.xxxxxxxxa.online

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4829 bytes and written 480 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 5F83EC54BFB2EF12B380A1A84B8E404E38877C4BF490971C4E20E53A09EAD359
    Session-ID-ctx: 
    Master-Key: 5FFDC1D602381FC1E0A3D4B7077ACC21A3CB68BDF5F7F0F86B9D3BAB4D6CC3F14FC986EF36E6C28B2576FF901E1D14F6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 85 5e c1 cd d1 cc 80 a2-8d 2f 05 ec a3 fa 0e 7f   .^......./......
    0010 - ae bb a5 b0 e9 60 7c 47-48 00 3a f7 86 70 e4 a1   .....`|GH.:..p..
    0020 - be 99 65 e5 f6 81 df e7-06 e0 49 94 47 04 68 e5   ..e.......I.G.h.
    0030 - a2 fc 83 7c a8 c6 ce 70-55 a6 6d ea de 67 44 ec   ...|...pU.m..gD.
    0040 - e6 fc f3 e6 df 78 49 d5-6d ca df 83 6f 25 7d d8   .....xI.m...o%}.
    0050 - 16 93 b7 16 f6 a2 7e 2d-43 6b 54 7f 49 97 20 75   ......~-CkT.I. u
    0060 - 91 56 ce da 25 1e df a1-05 5c 69 a2 86 a9 e6 45   .V..%....\i....E
    0070 - 3a 73 87 24 d2 e5 8b 40-bf dd 5b 3a e9 b7 e7 c7   :s.$...@..[:....
    0080 - dd 8b 6a d7 ed 8a 90 ac-82 16 ff 0d 36 b6 f1 f8   ..j.........6...
    0090 - 89 17 39 e0 64 ee ed e5-a1 eb c2 c4 1e 02 20 c2   ..9.d......... .
    00a0 - 71 db 11 cd 25 42 bf 56-3e 88 16 33 22 f4 32 87   q...%B.V>..3".2.

    Start Time: 1625539035
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
250 AUTH CRAM-MD5 PLAIN LOGIN

--------------------------------------------------------------
This mail was directly sent by hxxta.xxxxxxxxa.online.

SMTP host: hxxta.xxxxxxxxa.online
Port: 587
Use SLL: True
Use Authentication: True
Authentication name: smtp1
Authentication password: [not applicable]
Email from: info@cxxxxxta.live
Email to: hxxxxxxxxxxxxx@gmail.com

![image](https://user-images.githubusercontent.com/32220165/124534348-b4062f00-de31-11eb-86b3-9d37d8af46ad.png)

**Comment by rccess** [comment]
@willpower232 @adamcooke 
Do we have chance to review once , i already checked all old threads which were related to similar concern but no chance to get it solved

**Comment by willpower232** [comment]
Between the domains I mentioned previously and your use of port 587, it looks like you have configured Postal in quite a different way which may lead to this problem. Are you using a proxy or can you tell us a bit more about how you are setting it up this time?

**Comment by rccess** [comment]
Hello @willpower232 

Thanks for the update

i just followed manual installation 

https://github.com/postalhq/postal/wiki/Installation

do you have any quick install script which can install without any package issue or version dependency issue 

please you can share your email id for test , i will send one test email to you or can share header file with you, 

waiting for your reply

thank you !

**Comment by willpower232** [comment]
How are you making use of port 587 instead of the default 25?

**Comment by rccess** [comment]
![image](https://user-images.githubusercontent.com/32220165/124931199-9ac2d580-e01f-11eb-825f-6f8f4b42baa7.png)

**Comment by rccess** [comment]
![image](https://user-images.githubusercontent.com/32220165/124931400-ce9dfb00-e01f-11eb-919b-af0ed74da78d.png)

**Comment by rccess** [comment]
postal.yml
-----------------------
web:
  # The host that the management interface will be available on
  host: vtp.xxxxxxxxxx.care
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  # if you have more than one RabbitMQ server (cluster), you can use array like this:
  # host:
  #   - 10.1.1.1
  #   - 10.1.1.2
  #   - 10.1.1.3
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.vtp.xxxxxxxxxx.care
  smtp_server_hostname: vtp.xxxxxxxxxx.care
  spf_include: spf.vtp.xxxxxxxxxx.care
  return_path: rp.vtp.xxxxxxxxxx.care
  route_domain: routes.vtp.xxxxxxxxxx.care
  track_domain: track.vtp.xxxxxxxxxx.care

smtp_server:
  port: 587
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/vtp.xxxxxxxxxx.care/fullchain.pem  # Defaults to config/smtp.cert
  tls_private_key_path: /etc/letsencrypt/live/vtp.xxxxxxxxxx.care/privkey.pem # Defaults to config/smtp.key
  
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 5086c570dcc6e3d896491f71f99649a05638c2d9ffd2964c7f0a909dad4dc6662f743a767d821a816941a56c3edfaba09ccbf0b3716ffd33f52663a582945279254e71db0d4e6ecf94722a20c524b8f1cd683c9e38361c19e59ee41a5afff2030729ce835bd3ae5892969ef25b05e4f8b24d1b2fd492c1145e583c5a674f89a7

---------------------------------------------
SSL Letsencrypt 

openssl s_client -connect vtp.xxxxxxxxxx.care:587 -starttls smtp

![image](https://user-images.githubusercontent.com/32220165/124956749-ebddc400-e035-11eb-9e0e-1a122b2e29a0.png)

smtp_server.log

![image](https://user-images.githubusercontent.com/32220165/124956915-27788e00-e036-11eb-99df-5a8f6ed0d25b.png)
---------------
Output 

![image](https://user-images.githubusercontent.com/32220165/124957120-5abb1d00-e036-11eb-806e-9f144f9cc876.png)

**Comment by willpower232** [comment]
changing the port to 587 might make it difficult for other servers to send you messages but I'm not sure if that would cause google to think encryption wasn't used

**Comment by rccess** [comment]
issue fixed with VPS provider doesn't support TLS on network level by default
