### ISSUE TITLE
How to send mail using port 587 or 2525

### ISSUE THREAD

**Issue by itsdevil65** [postalhq/postal#1403]
Hey,
My service provider block my **port 25**. So I got execution expired error.

How can I send by using **port 587 or 2525**?

Because some person send mail by using port 587. 
Anyone help me?

**Comment by willpower232** [comment]
You can change the port in the config file however if you are unable to receive email on port 25, it is likely you will have problems receiving bouncebacks and other messages and your server provider may already block the other email ports so you should either ask your provider to allow you to use those ports or move provider.

**Comment by itsdevil65** [comment]
I checked port 587 and 2525 is open for mailing. Just guide me how to change the port 25 to 587. 

I don't want to receive bouncebacks and other messages. I will handle this by webhook or other method.

**Comment by willpower232** [comment]
The bouncebacks may not make it to your Postal server if you don't have port 25 so you wouldn't get webhooks triggered.

The port is in the config file.

**Comment by itsdevil65** [comment]
@willpower232 
If I change this in config file,

smtp:
  host: 127.0.0.1
  port: 587
  username:
  password:
  from_name: Postal
  from_address: postal@yourdomain.com
  
smtp_server:
  port: 587
  
It doesn't work for me.It's show error failed to connect smtp

**Comment by willpower232** [comment]
Did you restart Postal to apply the config file changes?

You can also use `sudo netstat -lnp` to verify which port is being used (and what is listening on it)
