### ISSUE TITLE
Sorting of MX resources in smtp_sender.rb

### ISSUE THREAD

**Issue by ctmarc** [postalhq/postal#1405]
Hi, we noticed a small issue when attempting to send a message to a group of servers with same MX preference value.
The list of servers is not randomized in that case, and every submission will go to the same receiving server.

The "sort" function in this line will sort the servers by preference, but will not randomize servers with same preference. I think that adding a explicit sort method that randomizes the `==` case would already solve it:

`mx_servers = dns.getresources(@domain, Resolv::DNS::Resource::IN::MX).map { |m| [m.preference.to_i, m.exchange.to_s] }.sort.map{ |m| m[1] }`

RFC 5321:
> If there are multiple destinations with the same preference and there is no clear reason to favor one (e.g., by recognition of an easily reached address), then the sender-SMTP MUST randomize them to spread the load across multiple mail exchangers for a specific organization.

**Comment by willpower232** [comment]
Interesting spot, definitely worth a quick fix. Do you have the time to make a PR for it?

**Comment by ctmarc** [comment]
Yes I'll try to do it during the next days.

**Comment by ctmarc** [comment]
https://github.com/postalhq/postal/pull/1408
