### ISSUE TITLE
Failed to build a new mail server

### ISSUE THREAD

**Issue by mdobydullah** [postalhq/postal#1406]
Hi Postal team, thanks for creating the great tool.

I've followed the documentation and set up everything. Added domain and verified SPF, DKIM, MX & return path.

But I faced an issue. I tried to build a mail server but it shows **500** error. Please take a look at the screenshots:

![postal1](https://user-images.githubusercontent.com/13184472/125605117-c8e2ec14-5466-4ca8-ab8d-ec05a3b07c6e.png)

![postal2](https://user-images.githubusercontent.com/13184472/125605123-f6234c82-f8c7-409a-8b48-9d86a6fafb98.png)

How can I solve the error?

Thank you.

**Comment by willpower232** [comment]
You will need to look in the log files to see what the problem was. In this case, I believe you are having a problem with database permissions but you need the extra detail from the log files to confirm.

**Comment by mdobydullah** [comment]
Hi @willpower232,

Thank you so much for your prompt response. I'll check and let you know. :blush:
