### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by SemperFortis** [postalhq/postal#1409]
The current docs for the API point to https://krystal.github.io/postal-api and https://atech.github.io/postal-api. However, both links are broken. I hope in the near future the documentation can either be included in the Wiki or have a permanent page as they are currently hard to find and breaks every so often.

**Comment by willpower232** [comment]
Thanks for letting us know, looks like more repos were moved to postalhq so the link is now https://postalhq.github.io/postal-api/

I found an old ticket for this so will update there.
