### ISSUE TITLE
Slow Sending Rate 🐌

### ISSUE THREAD

**Issue by ffsandi** [postalhq/postal#1413]
Dear teams,

I would like to ask why I only get about 10-35 emails/ minute when sending using SMTP from my Mautic.

I currently run on VPS with 4 core 8GB ram, and I also already try with 2 different VPS providers with the same specs.

I try several combinations, from 10 to 40 workers, and it doesn't give the significant result that I expect. 

40 workers consuming around 50% ram, but not increasing the sending rate speed.

I see another member here could hit 900 emails/minute.

Do you have any troubleshooting guide to solve this problem?

Because it will need more than 2 days to finish sending emails to over 50K subscribers, it feels that I could get older faster waiting for this to finish 🤣

Thanks.

@adamcooke @willpower232

**Comment by willpower232** [comment]
That is quite slow, is it possible that Mautic is having trouble sending that many messages quickly? Is your database on the same server as Postal? It might be fighting for memory. Is Mautic on a different server entirely to Postal?

**Comment by ffsandi** [comment]
I don't think my mautic is the problem, because before this I am using
amazon ses via smtp, and there is no problem sending big number of email up
to 100k per day.

The postal is running on separate and clean vps as your doc and I already
did some tips from this forum. Such as increase worker, threads, and edit
mysql configuration.

Thanks

**Comment by willpower232** [comment]
I assume Postal and Mautic are on different servers with the same company?
Aside from your worker processes, how much free memory does your Postal server have?
Is Postals database on the same server as Postal?

**Comment by ffsandi** [comment]
Postal & mautic are on different vps from same companies.

My free ram around 3-4 from 8gb total.

Postal database on same server.

**Comment by willpower232** [comment]
Actually I guess the most relevant question would be how any CPU threads are available.

You could get this information from neofetch or htop if you have either of those installed.
