### ISSUE TITLE
How to add domains via API?

### ISSUE THREAD

**Issue by sharrc** [postalhq/postal#1414]
Hello, I have a basic setup with postal on Ubuntu 18.04.

And I have to allow users to be able to add a domain using an API and get a DKIM public key back in response which they can they add into their DNS records.

Is there a way this is possible right now? Or do I have to use alternatives like a mix of Postfix + Amavis + Dovecot, or something on those lines...?

My requirements include:
1. Allowing multiple domains to be added anytime
2. Only sending emails from any user on that domain (No receiving)
3. Being able to customize the DNS records like the DKIM's selector, which looks something like: postal_Nkj24._domainkey.example.com
Would like to replace the "postal" bit here...

There is a commit actually that comes close to what I want: https://github.com/postalhq/postal/commit/2dd44e894e6522e485d91e9cd404f76959173af3

But this is not merged into the latest master version, and also there's no documentation for it.

Please help! Thanks!

Tagging: @willpower232 @adamcooke

**Comment by willpower232** [comment]
Also in the list of PRs is https://github.com/postalhq/postal/issues/1413 which sounds much closer to what you want.

These feature requests have not been merged as there are other priorities and no guarantee they will be merged. If you want to make use of that code, you wlil have to fork Postal and merge it yourself to create the version of Postal you desire but you would have to figure out how to use it on your own.
