### ISSUE TITLE
Multiple domains without authentication

### ISSUE THREAD

**Issue by Muneeb-Ahmed-Khan** [postalhq/postal#1416]
I have a WHM setup with 25 accounts at AWS, I want to use Postal as smartHost because AWS blocks port 25 on my server.
I had postal installed on fresh server and configured it. After creating an organization and server I was not able to send emails without authenticating the domain first. I did it for one domain and sending of email worked but this process is not suitable because I have to repeat the process for all other domains and whenever a new account is created at WHM I have to do the same step again. 
Is there any way with postal to use existing SPF,DKIM from WHM and not authenticate domains ? 
Like if I have 100 accounts i don't want to do the domain authentication but want to send emails with postal. I already have SPF, DKIM at my WHM for all those domains but the manual step is very hectic and not suitable for production.
Thanks.

**Comment by willpower232** [comment]
I don't think Postal is what you need here, you would want something more generalised like Postfix or similar.

See also https://github.com/postalhq/postal/issues/1333
