### ISSUE TITLE
Postal send email with my personal IP Adress

### ISSUE THREAD

**Issue by Stam2000** [postalhq/postal#1417]
Hi, I installed postal on a contabo VPS. when I send an email to a mail-tester.com email address, I notice that Postal uses my ip address to send mail.

I would like postal to be able to use the ip address assigned to my vps.
![Screenshot (42)_LI](https://user-images.githubusercontent.com/87859657/126907593-cf96e9ed-2479-46b2-8f8e-641da708b319.jpg)

**Comment by adamcooke** [comment]
Postal can only send mail from IP addresses on the server on which it is installed. If you're seeing your own IP here, then whatever is running the check is using the `Received` headers to check IPs. If you use SMTP, Postal will always add your client IP to the received headers as is standard practice.
