### ISSUE TITLE
Want to Add X-Originating-IP in Header

### ISSUE THREAD

**Issue by rccess** [postalhq/postal#1418]
Hello @willpower232 

I want to add X-Originating-IP in header which is server sending IP

I tried to add in client.rb  with the following pattern with 4 options , none working

headers << "X-Originating-IP: #{self.ip_address}"
headers << "X-Originating-IP: #{@ip_address}"
headers << "X-Originating-IP: #{self.server.ip_address}"
headers << "X-Originating-IP: #{server.ip_address}"

Please do advise on the same

**Comment by adamcooke** [comment]
Assuming you're talking about `lib/postal/fast_server/client.rb`, you could try adding this to the `request` hash.

```ruby
"HTTP_X_ORIGINATING_IP" => remote_ip
```

**Comment by rccess** [comment]
i need to add in this 

postal/lib/postal/message_db/message.rb

https://github.com/postalhq/postal/blob/1d22ca0f85b58b04aedde9071d9fc5ecd44af4de/lib/postal/message_db/message.rb#L409

Need to add here

Please do advise on the same

**Comment by willpower232** [comment]
I'm not sure what you want is possible because I don't think the actual sending process would be able to add a header to the message it has been asked to send.

**Comment by rccess** [comment]
![image](https://user-images.githubusercontent.com/32220165/126989593-e9e8d9aa-56ba-4dbf-ad9a-4c5f1cda9316.png)

i want to try this to track the email comes from which ip

**Comment by rccess** [comment]
@willpower232 @catphish 
Would like to have an update on this !
