### ISSUE TITLE
Documentation: ⚠️ API Documentation is no longer working

### ISSUE THREAD

**Issue by jaydrogers** [postalhq/postal#1424]
# Problem
* The Wiki links to the [API Documentation](https://atech.github.io/postal-api)
* This link no longer works

# Next steps
@adamcooke: Are we able to bring this back online? https://github.com/postalhq/postal-api

**Comment by jaydrogers** [comment]
Simple fix... the link just needs to be updated to: https://postalhq.github.io/postal-api/

**Comment by adamcooke** [comment]
Fixed
