### ISSUE TITLE
Whether we are going to add multi-language support?

### ISSUE THREAD

**Issue by kaneawk** [postalhq/postal#195]
Postal is a very magical mail server. I think adding multi-language support is very meaningful. 😄 

By the way, I can help Postal add Simplified Chinese languages.

**Comment by chocochrispi** [comment]
I can do french

**Comment by infooer** [comment]
i can do chinglish
![image](https://cloud.githubusercontent.com/assets/28818681/26797661/2faf6456-4a60-11e7-9d80-ca07e2d85662.png)

**Comment by infooer** [comment]
youdaoli

**Comment by treiero** [comment]
Eu posso fazer Português Brasil

**Comment by treiero** [comment]
Eu faço pt-br

**Comment by willpower232** [comment]
closing in favour of #393
