### ISSUE TITLE
Messages get pulled twice from the queue

### ISSUE THREAD

**Issue by Naugrimm** [postalhq/postal#198]
For every message I send via the "Send Message" page on the webinterface, there will be two emails sent. This happens with incoming messages as well as outgoing messages.

Outgoing Message:

![bildschirmfoto 2017-05-30 um 17 33 00](https://cloud.githubusercontent.com/assets/5753604/26591791/09d25ac8-455f-11e7-9b04-5e403bb8f89d.png)

Incoming Message:

![bildschirmfoto 2017-05-30 um 17 33 09](https://cloud.githubusercontent.com/assets/5753604/26591823/2734bed0-455f-11e7-9b0c-9ee0975cdffb.png)

Note: The message at 17:23 got only sent once - I have no idea why. All other messages got duplicated.

First I suspected that this has something to to with the underlying MySQL cluster (3 Nodes, Read-Write-Split via Maxscale), but the problem also occurs, when all but one server are removed from the configuration.

The debug log reveals the following sequence of SQL queries, that are executed to put a message in the queue and retrieve it later on:

```sql
INSERT INTO `queued_messages` (`server_id`, `message_id`, `domain`, `created_at`, `updated_at`, `route_id`, `manual`, `batch_key`) VALUES (4, 22, 'postal01.hh', '2017-05-30 14:40:34', '2017-05-30 14:40:34', 7, 1, 'incoming-rt:7-ep:-');
```

The message gets inserted once. Fine.

Now a lock on the **original** message is obtained in `app/jobs/unqueue_message_job.rb`.

```sql
UPDATE `queued_messages` SET `queued_messages`.`locked_by` = 'host:postal01.hh pid:13538 procname:worker.1 job:EZKBOL5ILK', `queued_messages`.`locked_at` = '2017-05-30 14:40:34' WHERE `queued_messages`.`id` = 70 AND `queued_messages`.`locked_by` IS NULL AND `queued_messages`.`locked_at` IS NULL;
```
Then the `perform` method in the same file tries to find other **batchable** messages to lock:

```sql
SELECT `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`batch_key` = 'incoming-rt:7-ep:-' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` = 'host:postal01.hh pid:13538 procname:worker.1 job:EZKBOL5ILK' AND `queued_messages`.`locked_at` = '2017-05-30 14:40:34';
```
This sadly returns the **original** message too. Later in the `app/jobs/unqueue_message_job.rb` the **original** message gets merged into the list of **other** batchable messages and this leads presumably to two messages being sent.

This assumption comes from a quick overview over the code. I'm not entirely sure if there is some kind of race condition as all log events occur within a few milliseconds.

The complete debug log can be provided if needed.

Thanks in advance for trying to debug this :muscle:

**Comment by catphish** [comment]
Thank you for the very detailed report. We will look into this for you.

**Comment by adamcooke** [comment]
The fact the deliveries have the same support ID suggests they aren't being pulled from the queue multiple times at all because this is a random reference that is decided after the message has been taken from the queue.

**Comment by joltcan** [comment]
Very weird, I just started to have the same issue. Tried to restart all services (just one sql-server included, no cluster).

Here is the message details. It's a single message, but delivered twice!
![image](https://user-images.githubusercontent.com/537157/94155500-4cbd5680-fe7f-11ea-8f39-060988c640e4.png)

**Comment by rbustos** [comment]
Same issue here with Stable and Beta version. Any advice?

**Comment by willpower232** [comment]
can you expand the details to confirm if the support references are the same or different?

**Comment by joltcan** [comment]
What does "support references" mean?

**Comment by rbustos** [comment]
Another test:

Simulate send by postal itself (Messages > Send Message) in development mode.

Its immediately generate two identical deliveries (on held of course).

The raw table show those duplicate entries for each single test. 

SQL trace (for one single test):

```
SELECT `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`locked_at` IS NULL AND (retry_after IS NULL OR retry_after <= '2020-09-30 01:52:51')

INSERT INTO `queued_messages` (`server_id`, `message_id`, `domain`, `created_at`, `updated_at`, `manual`, `batch_key`) VALUES (19, 38970, 'domain.tst', '2020-09-30 01:52:23', '2020-09-30 01:52:23', NULL, 'outgoing-domain.tst') s_ 7
SELECT  `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`id` = 6271218 LIMIT 1

UPDATE `queued_messages` SET `queued_messages`.`locked_by` = 'host:postal-17 pid:2001 procname:worker.16 job:MHASPWUEPW', `queued_messages`.`locked_at` = '2020-09-30 01:52:23' WHERE `queued_messages`.`id` = 6271218 AND `queued_messages`.`locked_by` IS NULL AND `queued_messages`.`locked_at` IS NULL
UPDATE `queued_messages` SET `queued_messages`.`locked_by` = 'host:postal-17 pid:2001 procname:worker.16 job:MHASPWUEPW', `queued_messages`.`locked_at` = '2020-09-30 01:52:23' WHERE (retry_after IS NULL OR retry_after <= '2020-09-30 01:52:53') AND `queued_messages`.`batch_key` = 'outgoing-domain.tst' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` IS NULL AND `queued_messages`.`locked_at` IS NULL LIMIT 100 5m<

SELECT COUNT(*) FROM `queued_messages` WHERE `queued_messages`.`batch_key` = 'outgoing-domain.tst' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` = 'host:postal-17 pid:2001 procname:worker.16 job:MHASPWUEPW' AND `queued_messages`.`locked_at` = '2020-09-30 01:52:23'
SELECT `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`batch_key` = 'outgoing-domain.tst' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` = 'host:postal-17 pid:2001 procname:worker.16 job:MHASPWUEPW' AND `queued_messages`.`locked_at` = '2020-09-30 01:52:23'

DELETE FROM `queued_messages` WHERE `queued_messages`.`id` = 6271218
```

**Comment by catphish** [comment]
Thanks for the SQL trace. This certainly suggests that it's only being pulled from the queue once, by one worker `host:postal-17 pid:2001 procname:worker.16 job:MHASPWUEPW`. So the question is why it's being processed twice (presumably by the same worker).

**Comment by catphish** [comment]
A cursory look at the code would suggest that @Naugrimm is correct.

`batchable_messages` returns all messages in a batch *including* the original message. The original message is then added back to the batch.

The question I need to answer though is why this only affects some people some of the time. If this problem were as fundamental as it seems, everyone would have this problem all the time.

**Comment by catphish** [comment]
```
QueuedMessage.where(:batch_key => self.batch_key, :ip_address_id => self.ip_address_id, :locked_by => locker, :locked_at => time)
```

I see it now. The query to fetch additional batched messages will only fetch the original message again if the second query runs within 1 second of the original query being locked, so this is likely happening more on new installs on fast servers!

**Comment by catphish** [comment]
Would anyone be able to test the fix here? https://github.com/postalhq/postal/pull/1225/files

**Comment by joltcan** [comment]
No doubles sent, only a single! I have just tried via the "send message" function though.

**Comment by joltcan** [comment]
Confirmed via API and SMTP as well, no doubles so far!

**Comment by joltcan** [comment]
Maybe the problem is the speed? I have a very idling system right now, and I didn't have duplets before.

**Comment by catphish** [comment]
Thank you for checking. I will wait to hear from @rbustos too and then I will merge this.

**Comment by joltcan** [comment]
Thanks for a quick fix!

**Comment by catphish** [comment]
> Thanks for a quick fix!

Not quite. This was reported in detail in 2017  :slightly_frowning_face: but you're welcome!

**Comment by rbustos** [comment]
Ok, I did manually those changes in the code (according @catphish ) suggestions and yes.. now it send just only one.


SQL trace:
```
SELECT  `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`id` = 6271920 LIMIT

SELECT column_name FROM information_schema.key_column_usage WHERE constraint_name = 'PRIMARY' AND table_schema = database() AND table_name = 'queued_messages' ORDER BY ordinal_position

SELECT COUNT(*) FROM `queued_messages` WHERE `queued_messages`.`server_id` = 19 AND (retry_after IS NULL OR retry_after <= '2020-09-30 12:44:34')

SELECT  `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`message_id` = 38976 AND `queued_messages`.`server_id` = 19 ORDER BY `queued_messages`.`id` ASC LIMIT

UPDATE `queued_messages` SET `queued_messages`.`locked_by` = 'host:postal-17 pid:13508 procname:worker.6 job:JGRB6LC6TI', `queued_messages`.`locked_at` = '2020-09-30 12:44:05' WHERE `queued_messages`.`id` = 6271920 AND `queued_messages`.`locked_by` IS NULL AND `queued_messages`.`locked_at` IS NULL
UPDATE `queued_messages` SET `queued_messages`.`locked_by` = 'host:postal-17 pid:13508 procname:worker.6 job:JGRB6LC6TI', `queued_messages`.`locked_at` = '2020-09-30 12:44:05' WHERE (retry_after IS NULL OR retry_after <= '2020-09-30 12:44:35') AND `queued_messages`.`batch_key` = 'domain.tst' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` IS NULL AND `queued_messages`.`locked_at` IS NULL LIMIT 100

SELECT COUNT(*) FROM `queued_messages` WHERE `queued_messages`.`batch_key` = 'domain.tst' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` = 'host:postal-17 pid:13508 procname:worker.6 job:JGRB6LC6TI' AND `queued_messages`.`locked_at` = '2020-09-30 12:44:05' AND `queued_messages`.`id` != 6271920

SELECT `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`batch_key` = 'domain.tst' AND `queued_messages`.`ip_address_id` IS NULL AND `queued_messages`.`locked_by` = 'host:postal-17 pid:13508 procname:worker.6 job:JGRB6LC6TI' AND `queued_messages`.`locked_at` = '2020-09-30 12:44:05' AND `queued_messages`.`id` != 6271920
SELECT `queued_messages`.* FROM `queued_messages` WHERE `queued_messages`.`locked_at` IS NULL AND (retry_after IS NULL OR retry_after <= '2020-09-30 12:44:35')

DELETE FROM `queued_messages` WHERE `queued_messages`.`id` = 6271920 }
```

![image](https://user-images.githubusercontent.com/263415/94687257-6b4da280-0302-11eb-96f0-2063d4c2d1c7.png)

I'd say it fixed the original issue reported.

Maybe other could run it own tests to double verification.
