### ISSUE TITLE
Missing zoneinfo causes application to not start

### ISSUE THREAD

**Issue by bradserbu** [postalhq/postal#207]
Hello, here is an issue I received after provisioning a `Ubuntu 16.04` server instance and attempted to run the `quick-install` script...

```
When you HTTParty, you must party hard!
Created example config file at /opt/postal/config/postal.yml
Created new private key for Let's Encrypt
Created new signing key for DKIM & HTTP requests
Created new private key for default fast server TLS connections
Created new self signed certificate for default fast server TLS connections
Initializing database
D, [2017-06-02T21:54:18.919053 #25692] DEBUG -- sentry: ** [Raven] tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install excluded from capture due to environment or should_capture callback
rake aborted!
TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:19:in `block in <class:Railtie>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
/opt/postal/app/config/environment.rb:5:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
TZInfo::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::ZoneinfoDataSource.search_path are valid zoneinfo directories.
/opt/postal/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_data_source.rb:180:in `initialize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:180:in `new'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:180:in `create_default_data_source'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:40:in `block in get'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:39:in `synchronize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:39:in `get'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:20:in `block in <class:Railtie>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
/opt/postal/app/config/environment.rb:5:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:load => environment
(See full trace by running task with --trace)
```

**Comment by adamcooke** [comment]
It sounds like you're Linux doesn't have a zoneinfo directory. It should be in `/usr/share/zoneinfo`. Does that directory exist for you? If not, how did you install Ubuntu?

**Comment by bradserbu** [comment]
Adam, 

I have already done a pull that adds the `tzinfo-data` to the gem file that I can confirm fixes this issue.  

I already tore down the Ubuntu 16.04 server I provisioned for my testing, so I cannot verify whether the `/usr/share/zoneinfo` folder was present or not.

Thanks, Brad

**Comment by adamcooke** [comment]
While adding the gem would fix it (although your pull request is incomplete because it doesn't update the lockfile), it shouldn't be necessary to have the gem as it's just a workaround for missing zoneinfo on the server.

I'd like to know how common place it is for an Ubuntu server not to have zoneinfo available. How was your server installed?

**Comment by bradserbu** [comment]
Okay.  I understand now.  Thanks for letting me know about the lock file.  This is was the first time I have ever made any changes to a `Ruby` project.  

I can say that it might be very common for the following scenario occur more frequently in the future with regards to:
- Server Environments
- Including "cloud servers" (Public and Private)

The current trend seems to be continuing down the base of increasingly "lean" base images.

As far as the particular server instance in this case, It was a public cloud provider with a `Ubuntu 16.04 Server` base image provisioned on "Bare Metal".  The was no guided 'setup' process, and pretty much the only package/software installed out-of-the-box was OpenSSH...

I hope that helps...

**Comment by bradserbu** [comment]
FYI: The `quick setup` process worked as expected after making this one change...

**Comment by catphish** [comment]
It seems that the correct solution here is to install the missing zoneinfo and git packages before attempting to install Postal using the automated installer. This should bring the VM into the state we expect.

This installer assumes a standard installation of Ubuntu 16.04 server, and unfortunately, it is not possible to guess which packages certain providers have stripped from the standard installation.

With that said, I see no harm in adding these packages to the automatically installed dependencies. If they're already present, they will simply be left as-is or upgraded to the latest version.
