### ISSUE TITLE
HTTP API Documentation

### ISSUE THREAD

**Issue by thatjpcsguy** [postalhq/postal#209]
> For full information about how to use our HTTP API, please see the documentation.

This link to see the documentation goes to https://gopostal.io/~/http-sending which returns a 404.

I suppose there should be a documentation section on the actual installation instance.

**Comment by adamcooke** [comment]
I'll update the link. 

https://github.com/atech/postal/wiki/Using-the-API

**Comment by willpower232** [comment]
Closing in favour of #1030
