### ISSUE TITLE
worker.1 is not running 

### ISSUE THREAD

**Issue by ajaymishra8423** [postalhq/postal#270]
https://www.screencast.com/t/LYYcqUsVO

**Comment by catphish** [comment]
Please provide as much relevant log output as possible.

**Comment by ajaymishra8423** [comment]
its not genertaing any log,whereas this is the old log
[worker.3:9014] [2017-07-11T22:16:30.448] INFO -- : [SUNIOHQOFT] [1::22995 23002] Message inspected successfully
[worker.3:9014] [2017-07-11T22:16:36.509] INFO -- : [SUNIOHQOFT] [1::22995 23002] Processing complete
[worker.3:9014] [2017-07-11T22:16:36.670] INFO -- : [SUNIOHQOFT] [1::88854 88861] Got queued message with exclusive lock
[worker.3:9014] [2017-07-11T22:16:36.839] INFO -- : [SUNIOHQOFT] [1::88854 88861] Parsing message content as it hasn't been parsed before
[worker.3:9014] [2017-07-11T22:16:36.978] INFO -- : [SUNIOHQOFT] [1::88854 88861] Inspecting message
[worker.3:9014] [2017-07-11T22:16:37.160] INFO -- : [SUNIOHQOFT] [1::88854 88861] Message inspected successfully
[worker.3:9014] [2017-07-11T22:16:38.554] INFO -- : Exit requested but job is running. Waiting for job to finish.
[worker.3:9014] [2017-07-11T22:16:39.818] INFO -- : [SUNIOHQOFT] [1::88854 88861] Processing complete
[worker.3:9014] [2017-07-11T22:16:40.106] INFO -- : [SUNIOHQOFT] Finished processing UnqueueMessageJob job in 10.270769806s
[worker.3:9014] [2017-07-11T22:16:40.107] INFO -- : Exiting because a job has ended.

**Comment by ajaymishra8423** [comment]
Smtp server logs
https://www.screencast.com/t/BsssbR6px0
[worker.2:9244] [2017-07-13T16:48:58.111] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[requeuer.2:9272] [2017-07-13T16:49:03.545] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[worker.2:9270] [2017-07-13T16:49:04.126] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[requeuer.2:9322] [2017-07-13T16:49:07.147] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[worker.2:9320] [2017-07-13T16:49:07.300] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[worker.2:9371] [2017-07-13T16:49:09.975] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[requeuer.2:9373] [2017-07-13T16:49:10.033] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.
[requeuer.2:9421] [2017-07-13T16:49:13.798] INFO -- : ** [Raven] Raven 2.1.0 configured not to capture errors.

**Comment by adamcooke** [comment]
Nothing you've provided there can help us debug this.

**Comment by ajaymishra8423** [comment]
=>"ajay.mishra@laitkor.com", "subject"=>"Test Message at July 13, 2017 18:07", "plain_body"=>"This is a message to test the delivery of messages through Postal."}, "commit"=>"Send Message", "org_permalink"=>"migo01", "server_id"=>"mta-migo01-net"}
18:07:14 web.1           | => [web.1:31056] [2017-07-13T18:07:14.323] INFO -- : Completed 500 Internal Server Error in 210ms (ActiveRecord: 30.0ms)
18:07:14 web.1           | => [web.1:31056] [2017-07-13T18:07:14.324] FATAL -- :
18:07:14 web.1           | => [web.1:31056] [2017-07-13T18:07:14.324] FATAL -- : Bunny::NotAllowedError (Connection-level error: NOT_ALLOWED - access to vhost 'postal' refused for user 'postal'):
18:07:14 web.1           | => [web.1:31056] [2017-07-13T18:07:14.325] FATAL -- :
18:07:14 web.1           | => [web.1:31056] [2017-07-13T18:07:14.325] FATAL -- : lib/postal/rabbit_mq.rb:15:in `create_connection'

**Comment by catphish** [comment]
This definitely looks like it might explain the problem. Was this an automated installation, or did you configure things manually?

**Comment by ajaymishra8423** [comment]
I have configured manually

**Comment by ajaymishra8423** [comment]
Please suggest how to clera queue message.
https://www.screencast.com/t/2pTt5damB

**Comment by willpower232** [comment]
I created a fresh testing environment for postal yesterday and for whatever reason the script didn't create the user, queue, or permissions in rabbitmq. I saw similar errors about not being able to connect.

Repeating the commands from the bash script and restarting postal resolved the issue.

```
rabbitmqctl add_vhost /postal
rabbitmqctl add_user postal p0stalpassw0rd
rabbitmqctl set_permissions -p /postal postal ".*" ".*" ".*"
```

**Comment by ajaymishra8423** [comment]
Please suggest how to clear queue message.
https://www.screencast.com/t/2pTt5damB

**Comment by catphish** [comment]
I assume these are messages that are queued but were not able to be added to the RabbitMQ queue. Di you still wish to send them?

**Comment by ajaymishra8423** [comment]
yes I would like to messages to be send
