### ISSUE TITLE
Internal SMTP relay

### ISSUE THREAD

**Issue by igerzog** [postalhq/postal#275]
Is it possible to relay from one postal mail server with some verified domains to another one by condition? In other words is it possible to configure outgoing routes?

**Comment by mattmartincouk** [comment]
You can add a smarthost as per #251 but this is for all email.

**Comment by igerzog** [comment]
Yes, I have seen this, but the idea is to route messages inside postal.

**Comment by mattmartincouk** [comment]
The outgoing message from postal will always use the MX for the domain. All message scan go to a remote host in the config but there isn't anyway to selectively do this as far as I can see.

Incoming messages to postal can go to any other SMTP host but probably not want you want.

**Comment by igerzog** [comment]
Well I think this idea can be an enhancement of some kind. For example if you wish to send letters from subdomains and make special route for these messages.

**Comment by Rodri9o** [comment]
Hello, and thanks for the awesome piece of software.
Is it possible to use Postal as a mail-relay only host without mailboxes ?
Thanks in advance.
Rod

**Comment by willpower232** [comment]
Postal doesn't whitelist (or blacklist for that matter), it only blocks sending if it is unsure whether the email will be delivered.
