### ISSUE TITLE
SEND AS ANY 

### ISSUE THREAD

**Issue by billyprice1old** [postalhq/postal#277]
hi there how do i enable SEND AS ANY i cant seem to get it working

i get a 530 error as i cant hard code the program to send from outbound.ibilly.me what can i do it use its own thing blog.ibilly.me i dont want to have to make a new domain thing

**Comment by vardhamanshetti** [comment]
@billyprice1  Did you find solution for this?

**Comment by igerzog** [comment]
If you configured your domain `blog.ibilly.me` and want to send messages as `<some name>@outbound.ibilly.me` you can do this. To enable Send as Any you should go here `Settings - Advanced Settings - Allow Sender Header` and set it to `Yes`. If you want to send from any other domain than `blog.ibilly.me` you should add `Sender` header to your message.
For example:
- From: `test1@outbound.ibilly.me`
- Sender: `anyname@blog.ibilly.me`
- To:

**Comment by masihfathi** [comment]
Hi, about this issue, is it possible to send via any domain? like many ESP, you can send email without verify domain (but with a higher risk of spamming), 
For example i verify example.com but want able send via example..@gmail.com

**Comment by ingo-lorenz** [comment]
In my case the "send as any" option is active and the "sender" header is added, but mails are still rejected with 530.

**Comment by isnuryusuf** [comment]
> In my case the "send as any" option is active and the "sender" header is added, but mails are still rejected with 530.

its also happening on me
