### ISSUE TITLE
Message Injection & Connections

### ISSUE THREAD

**Issue by longhorninmd** [postalhq/postal#283]
Does Postal allow injection threads/connections to be changed within the config?  For example, in periods of higher email volume, it would be helpful to allocate more connections to handle the injection of a higher message amount.  

Thx,
Russ

**Comment by mattmartincouk** [comment]
I'm not sure but I think the workers value can be increased to help higher loads..

**Comment by catphish** [comment]
I am not sure I understand what you mean by "injection". Do you simply want to run more workers to clear the message queue faster?

**Comment by longhorninmd** [comment]
submitting mail to the MTA.
