### ISSUE TITLE
Test message error

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#286]
hello

i am testing email but i got below error so could you please tell me how to fix this?

Message was not delivered successfully to SMTP server.
Error: Timeout::Error (execution expired)

**Comment by matthewbloch** [comment]
Hi Sahil, I don't think there's enough to go on here for anyone to help. The default Postal configuration tries to deliver to localhost:2525, so if you don't have an SMTP server running on there it may time out like this when trying to send e.g. new user invitations.

Alternatively edit config/postal.yml and change the settings under smtp_server: to correspond to the server on your local network.
