### ISSUE TITLE
Sudden errors started coming and Postal stopped working!

### ISSUE THREAD

**Issue by webhostinggeek** [postalhq/postal#288]
Following was the 'postal status' output for smtp which was failing and given below errors were being logged. To resolve, I had to stop Postal and manually issue 'postal run' command instead of postal start which gave the same issue everytime it was started. What could be the issue?

````
============================================
|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Stopped                   pid:1664     respawns:5      port:-        tag:-
|| => smtp.4           Failed       06:10        pid:3553     respawns:5      port:-        tag:-
============================================
[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
^[[34m[smtp.1:1282]^[[0m [2017-07-31T05:09:55.212] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
============================================
```

**Comment by adamcooke** [comment]
Not enough information there for us to debug that, I'm afraid.

**Comment by webhostinggeek** [comment]
Let me know what else would be required. Shared the /opt/postal/log/smtp_server.log and postal status right now.

**Comment by webhostinggeek** [comment]
Any update? Still only 'postal run' in screen is running but not postal start or postal stop and start :(

**Comment by webhostinggeek** [comment]
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.111] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.114] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : An error occurred while accepting a new client.
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : Errno::ENOTCONN: Transport endpoint is not connected - getpeername(2)
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:103:in `remote_address'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:103:in `block (2 levels) in run_event_loop'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `select'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `block in run_event_loop'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `loop'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `run_event_loop'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/postal/smtp_server/server.rb:259:in `run'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.115] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
^[[34m[smtp.1:1282]^[[0m [2017-07-30T23:15:45.116] ERROR -- : /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'

**Comment by cinco** [comment]
I have the same problem:

```
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : An error occurred while accepting a new client.                                                                                                                                                                                                           
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : Errno::ENOTCONN: Transport endpoint is not connected - getpeername(2)                                                                                                                                                                                     
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:104:in `remote_address'                                                                                                                                                                                      
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:104:in `block (2 levels) in run_event_loop'                                                                                                                                                                  
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:87:in `select'                                                                                                                                                                                               
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:87:in `block in run_event_loop'                                                                                                                                                                              
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:85:in `loop'                                                                                                                                                                                                 
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:85:in `run_event_loop'                                                                                                                                                                                       
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/postal/smtp_server/server.rb:260:in `run'                                                                                                                                                                                                 
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'                                                                                                                                                                            
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'                                                                                                                                                          
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'                                                                                                                                                                      
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'                                                                                                                                                                   
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'                                                                                                                                           
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'                                                                                                                                                                                             
[smtp.1:70] [2020-12-01T20:21:42.238] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'                                                                                                                                                    
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'                                                                                                                                                                    
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'                                                                                                                                                        
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'                                                                                                                                      
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'                                                                                                                                                               
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'                                                                                                                                                 
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'                                                                                                                                                   
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'                                                                                                                                                          
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'                                                                                                                                                        
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'                                                                                                                                        
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'                                                                                                                                                                 
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'                                                                                                                                                                   
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'                                                                                                                                                                                                
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /opt/postal/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'                                                                                                                                                                                    
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'                                                                                                                                                                                                
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'                                                                                                                                                                                         
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'                                                                                                                                                                                                 
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run' 
[smtp.1:70] [2020-12-01T20:21:42.239] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start' 
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/bundle/bin/bundle:23:in `load'
[smtp.1:70] [2020-12-01T20:21:42.240] ERROR -- : /usr/local/bundle/bin/bundle:23:in `<main>'
```
