### ISSUE TITLE
Wrong handle messages by Yahoo

### ISSUE THREAD

**Issue by igerzog** [postalhq/postal#291]
Messages sent to Yahoo mail are not handled properly. Users can not see the ordinary message but only two files in attachment that actually are plain and html versions of the message.

**Comment by mattmartincouk** [comment]
Does the message have both plain and HTML versions or just the latter?

**Comment by igerzog** [comment]
Both parts.
![screen shot 2017-08-03 at 21 22 31](https://user-images.githubusercontent.com/18285761/28937026-2db5923c-7892-11e7-986f-3885600c2ff8.png)

**Comment by willpower232** [comment]
I can't replicate this, are you able to provide a copy of the message you are sending?

**Comment by igerzog** [comment]
I have prepared three files (text version, html and raw) and packed them to archive. How can I send it to you?

**Comment by willpower232** [comment]
Can you post them here? If you drag and drop it onto the comment box, it should upload

**Comment by igerzog** [comment]
[postal-yahoo.tar.gz](https://github.com/atech/postal/files/1203003/postal-yahoo.tar.gz)

**Comment by willpower232** [comment]
Still not able to replicate it, do you have issues with other email platforms or is it just yahoo?

**Comment by igerzog** [comment]
Only with Yahoo. Can this problem depend on mail servers chain? But as a matter of fact postal is the last one there.

**Comment by willpower232** [comment]
are you not sending the messages directly to postal via its API?

**Comment by igerzog** [comment]
I send them through another local server and use postal as a gateway.

**Comment by willpower232** [comment]
Does that server use the API or send through SMTP somehow? I'm not really familiar with that setup.

**Comment by igerzog** [comment]
Well the chain looks like this:
- I send the message from mail client to the first mail server
- The first mail server recognises sender email and password and then relay this message to my postal server
- The first mail server connects to postal ip on port 25 and uses predefined credentials for authentication
- My postal server handles this message, signs it with DKIM and then relays to recipient

Everything works fine except Yahoo. The same message sent to Gmail or any other mail provider was shown as it was expected to be.

**Comment by willpower232** [comment]
I would question the purpose of the first mail server, is your code not able to send to postal directly? It may be that the message is subtly changed somehow on its way through and it would be difficult to support this configuration.

**Comment by igerzog** [comment]
It handles user database and several other options. Well if Yahoo is the only server that can't render my messages I would not better send to it through postal at all. Let us save some time for more useful issues.

**Comment by mattmartincouk** [comment]
We use a similar setup and don't see any issue with Yahoo.

What mail server is sat in the middle?

**Comment by igerzog** [comment]
It is Axigen.
