### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Burn3rs** [postalhq/postal#300]
Both auto installer and manual methods fail. 

root@ubuntu:/opt/postal/app# postal initialize
Initializing database
Could not find nokogiri-1.7.2 in any of the sources
Run `bundle install` to install missing gems.

I did
# gem install nokogiri -v '1.7.2'
# bundle install

Nothing fixed the issue.

Using Digital Ocean VPS,

**Comment by gthb1** [comment]
#1 Reinstall the server with Ubuntu 16.04 LTS 64bit.
#2 Login as root and run: apt-get update && apt-get dist-upgrade && rm -f /etc/motd.tail && apt 
autoremove && reboot
#3 After proper restart, login again as root and run the quickinstall and continue with instructions as found here: https://github.com/atech/postal/wiki/Quick-Install

**Comment by catphish** [comment]
This is very odd indeed. What happens when you run bundle install? Does it install the gems?

**Comment by alancpazetto** [comment]
Hi!
I got same error when I was using a Ubuntu 512MB machine
Upgrade to 1GB works to me, however the docs recommends at least 8GB machine:

> The following prerequisites are required to run Postal. We recommend running Postal on an Ubuntu 16.04 server with at least 8GB of memory and enough disk space to store your repositories.
