### ISSUE TITLE
Raw message retention size

### ISSUE THREAD

**Issue by gthb1** [postalhq/postal#311]
Suggesting to use KB or MB for the 'Raw message retention size'.

**Comment by willpower232** [comment]
The "Advanced Settings" tab has a "Raw Message Retention Size" field which appears to correlate to "Volume of raw message data that will be stored" on the "Retention" tab.

The field says bytes under it but the volume is in gigabytes.

I would suggest that the bytes be changed to megabytes for the whole thing to make sense. Also it seems that the HTML meta title of the Retention tab is "Message Rentention" so make that two typos on that page.

As the field relates to storing all messages on that particular server, is KB too granular?

**Comment by gthb1** [comment]
Oh, good to know (it is in GB) ;)
Also support MB, it is easy to understand, both ways small & large (yes, KB might be less suitable).

PS: There is a atech/postal and a fork, is there any difference in the resulting code (to install)?

**Comment by willpower232** [comment]
The input field is already in MB so the only changes needed are the typos "bytes" and "rentention".

There will be differences for each fork. Probably better staying off on atech/postal unless you need something from somewhere else.

**Comment by gthb1** [comment]
Ah, good to know, thx!

**Comment by ilyacherevkov** [comment]
I have "Raw message retention size" configured @ 2048, but "Storage used" is already 10GB. Is it ok?

**Comment by ilyacherevkov** [comment]
looks like retention period has more priority and retention size works only to strip data outside retention perido

**Comment by willpower232** [comment]
Interesting, could you open a new issue about this?

**Comment by gthb1** [comment]
In case it is not resolved, perhaps there is some mixup?

Above it says "The field says bytes under it but the volume is in gigabytes" but also "The input field is already in MB"
so which is it? Because if in GB, it would explain @ilyacherevkov's issue
