### ISSUE TITLE
version info in master

### ISSUE THREAD

**Issue by gthb1** [postalhq/postal#318]
Suggesting to put version info as gained from command
postal version
into master, perhaps in separate file called 'version'?

**Comment by willpower232** [comment]
Alas there isn't a version just yet AFAIK https://github.com/atech/postal/milestone/1

**Comment by gthb1** [comment]
Oh, sorry, just went by output:
postal version
1.0.0-f1bee5644b-stable

**Comment by willpower232** [comment]
I get `1.0.0-dev` haha
