### ISSUE TITLE
ip pool

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#323]
Hello

i have added ip pool but how can i check that whether it is working all the ip's or not?

i think it's working only default server ip and i have many ip address so i want to rotate that ip for better inbox deliverability. Please tell me how i can check that ip is working or not?
thanks

**Comment by mattmartincouk** [comment]
You'd have to set sending email and look at the headers.

I don't believe there is another way but it is safe to say, if a few work, they generally all will otherwise it'll be a system issue than software.

**Comment by catphish** [comment]
Out of interest, what leads you to the impression that using multiple IPs will increase the deliverability of your messages? I believe the only way to know for sure is simply to send a batch of emails to yourself and look at the headers of the received emails. It definitely should work if the mail server is configured to use the pool.

**Comment by longhorninmd** [comment]
Because ISPs will limit simultaneous sender connections or messages allowed per connection by IP address.  Therefore, if you want any delivery scale, you need to be sending via multiple IPs.  Waiting for retry periods is way too inefficient.

**Comment by sandeep28saxena** [comment]
Hey, I checked and postal is using the primary IP address (my eth0) to send the emails.  I have multiple IP addresses on server as alias (eth0:1, eth0:2, eth0:3....) and as said above I want postal to rotate the IPs for a particular domain. Is this function available in Postal?  For example in pmta I can assign the IPs to a virtual MTA and pmta keep on sending the emails from all assigned IPs.  This would be a great feature in Postal if its not there.

**Comment by catphish** [comment]
@sandeep28saxena https://github.com/atech/postal/wiki/Configuring-IP-Pools

**Comment by sandeep28saxena** [comment]
Hey Guys, I created an IP pool and then assigned it to an organization.  Checked the settings of the mail server in this org and same pool is assigned to the server.  But when I send emails from this mail server it is going from the other IPs on the server which are not part of the pool.   Any clues what can be wrong ?

**Comment by sandeep28saxena** [comment]
Hey Guys, Is any one facing similar issue ? Any clues what can be wrong. I checked everything as far as I can and did not see anything missing.

**Comment by influenist** [comment]
Mails are totally not send by the Pool which are configured. As already reported above!

It doesn't matter if you setup rules or assign one IP / pool to the organisation. Mails are routed by default via the MAIN IP.

**Comment by iammattmartin** [comment]
This must be down to user configuration.

We have multiple pools, with multiple IPs and they are working as expected and mail from the pool only uses the IP(s) it is allowed to. No mail goes out from our main server IP at all.

**Comment by influenist** [comment]
1) IP is added and ping-able
2) Pool config line has been updated to true
3) Postal has been restarted
4) 2 Pools have been added: 
Pool 0 with Server IP and IPs from that subnet
Pool 1 with IPs from different subnet
5) Organisation has assigned non server - pool with different subnet
6) Rule has beed added on Organisation level > Server > Settings
7) Receiving from * to * and the IP pool Pool0.

Despite, mails are being send via Main IP

**Comment by sgregori** [comment]
Any news about this ?

I configured 3 local ips that each are routed per different public ip addresses, tested with links:
```
links -bind-address 10.0.5.2 www.cualesmiip.com
links -bind-address 10.0.5.3 www.cualesmiip.com
links -bind-address 10.0.5.4 www.cualesmiip.com
```
But when sending a test message, is always routed by "main IP".

Thanks.

**Comment by sgregori** [comment]
Excuse me, is resolved yet ?

Thanks.

**Comment by iammattmartin** [comment]
There isn't a wider issue but instead of hijacking another post it is worth opening your own so any specifics about **your** environment can be obtained.

**Comment by sgregori** [comment]
No problem, thank you for the information.

**Comment by isnuryusuf** [comment]
hello, 

try to add dns of your IP Pool or you can use /etc/hosts
for example:

```
xx.zz.yy.97	ip1-pool.example.com
xx.zz.yy.98	ip2-pool.example.com
xx.zz.yy.99	ip3-pool.example.com
xx.zz.yy.100	ip4-pool.example.com
```

also you can test to create IP Rules, like example

Any message sent from: support@example.com
Will be sent using: IP-Pool1

its work for me, previously on different environment i don't have this issue but when i installing on different environment i facing this issue

**Comment by andresagui** [comment]
Hello guys. Any one can help me with this. I dont know how to get an ip address for an IP pool. I need it for Postal. Everything is set up with my real IP... but i want to use the pool Ips. How can i do, make or cook that?   Thank you very much!!!

**Comment by willpower232** [comment]
@andresagui you will need to get more IP addresses from your server provider which typically requires extra configuration on the server as well. Once you have done that, you will be able to enable the IP Pools feature and set it up as you desire. Please open a new issue if you have more questions rather than commenting on closed issues.

**Comment by Riyad264** [comment]
You just can try this article simply: **[How to set up IP Pool for the Postal SMTP server? (Latest Updated Guide)](https://inboxhujur.com/how-to-set-up-ip-pool-for-the-postal-smtp-server-latest-updated-guide/)**

**Comment by sgregori** [comment]
> You just can try this article simply: **[How to set up IP Pool for the Postal SMTP server? (Latest Updated Guide)](https://inboxhujur.com/how-to-set-up-ip-pool-for-the-postal-smtp-server-latest-updated-guide/)**

Nice, but 5 years late.
