### ISSUE TITLE
MessageSent events not being sent via webhook

### ISSUE THREAD

**Issue by mackinra** [postalhq/postal#330]
We're noticing that a good portion of delivery (MessageSent) events are not being sent via webhook, with these events being left in the `webhook_requests` table.  The problem has been getting worse every day.  I've added more detail in my comments in #265.

**Comment by mackinra** [comment]
This continues to happen... only about 25% of MessageSent events now are being sent to the webhook.

**Comment by mackinra** [comment]
Now it's about 15% of these webhook events being delivered.  Is anyone else experiencing this problem?

**Comment by mackinra** [comment]
@adamcooke This problem continues to spiral.  Now, Postal is only delivering about 10% of the MessageSent events to our webhook... piling up the unsent ones in the `webhook_requests` table.  Any idea on how to fix this?  Thanks.

**Comment by mackinra** [comment]
Now we're noticing a problem with 1000's of emails backing up in the Queue, hours old, in a Pending state.  Perhaps related to the above problem.  Is anyone at atech available to look at this?  @catphish ?

**Comment by mackinra** [comment]
Here is my Postal's status (below).  Probably unrelated, but should I be bumping up the number of workers?  I'm pushing about 60K emails/day right now.

```
Procodile Version   1.0.17
Application Root    /opt/postal/app
Supervisor PID      2347
Started             2017-08-19 23:18:48 -0700

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      19/08/2017   pid:2353     respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      19/08/2017   pid:2355     respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      19/08/2017   pid:2357     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      19/08/2017   pid:2359     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      19/08/2017   pid:2362     respawns:0      port:-        tag:-```

**Comment by willpower232** [comment]
>  Probably unrelated, but should I be bumping up the number of workers?

Almost definitely related. If you are queuing more messages than one worker process can handle in a timely manner (i.e. you see lots of pending) then you should increase the worker count in `postal.yml` like so https://github.com/atech/postal/issues/173#issuecomment-302656698

**Comment by mackinra** [comment]
Restarting with 10 workers did seem to resolve the Pending email issue, but it hasn't resolved the main issue I reported here - the MessageSebt events not being delivered via webhook.  

A couple odd things about the new Pending email issue: we've been sending about 60k emails per day for weeks now, with just the 1 worker, and hadn't noticed any issues like this.  Also, when restarting Postal, it took considerable time for it to shutdown.  I ended up having to send kill signals to the procodile and worker processes.  I've had similar issues with restarts before.  Could these improper shutdowns have ramifications (perhaps helping to explain the MessageSent issue)?

**Comment by mackinra** [comment]
To further illustrate how the pending email problem seemed to come out of nowhere, it appears something has been consuming unusual amounts of CPU in the past couple days.  Here is the 1-min load avg over the past month (on our dedicated 8-vcpu host):
<img width="786" alt="1-min load avg past month" src="https://user-images.githubusercontent.com/1144286/30225954-2d9609cc-9489-11e7-8d67-25a4120eb903.png">

**Comment by mackinra** [comment]
Here's the corresponding avg CPU graph.  I believe that inflection point around Aug 19 where the pattern changes, was the last time I restarted Postal (no config changes then, I believe) before last night (when I added more workers).  This all seems like a ton of CPU to be in use, for a SMTP application.  Anyone know how I can debug this to pinpoint where the hotspots in the code are?

Prior to Aug 19 or so, we had been warming up Postal gradually.  Since then, the volume of emails has been stable (meanwhile those unprocessed `MessageSent` events keep piling up in `webhook_requests`, with 0 `attempts` -- now has > 1M rows).

<img width="795" alt="screen shot 2017-09-08 at 11 39 57 am" src="https://user-images.githubusercontent.com/1144286/30226327-797f296c-948a-11e7-9918-3ff10b703b5f.png">

**Comment by mackinra** [comment]
Interestingly, I've noticed that more `MessageSent` events are being delivered after bumping the number of workers from 1 to (now) 8... but it's still no where near 100%, as it was originally... it's now around 42%.  Better than 7% which it had gotten down to, but still a far cry from where it should be.

**Comment by mackinra** [comment]
So I'd love to fix this myself, and contribute back... but I've been trying to decipher the source and have struggled to identify where in the source that `webhook_requests` records are getting inserted with an `attempts` value of 0.  My ruby knowledge is minimal (more of a Java/ObjC developer).  I would've thought it would be in the `WebhookRequest` class, but I seem to be missing it.  The `deliver` method appears to only insert records with an `attempts` value greater than 0.  Any hints on where I should be looking would be greatly appreciated @adamcooke @catphish?

**Comment by alexroosenstein** [comment]
I've actually 'fixed' this by changing this line:
https://github.com/atech/postal/blob/2f0155747c5c058afb83856ce5c3c8d5f8cad341/app/models/webhook_request.rb#L46

To:
`where("retry_after < ? OR (retry_after IS NULL AND created_at<SUBTIME(NOW(), '0:30:0.000000'))", Time.now).limit(100).each(&:queue)`

I added the `limit(100)` as we've ran into a backlog of roughly 900.000 webhook requests and I didn't want to overload anything. I added the `created_at `check so it would only requeue webhook requests that are older than 30 minutes (and thus were never actually queued).
This is not a permanent/ideal fix, but it did temporarily solve our problem with the webhook requests.

**Comment by shopglobal** [comment]
That works

**Comment by mackinra** [comment]
@alexroosenstein Thanks so much for the suggestion!  It seems to be doing the trick.  I had pondered that `requeue_all` method a bit, but was primarily stuck on trying to understand the underlying cause of the missed events.  Perhaps someone else can enlighten us.

**Comment by mackinra** [comment]
@alexroosenstein You should consider contributing that fix back to the repo.  Even if it doesn't address the underlying issue of why some `MessageSent` events aren't even being attempted, I think it makes sense for that `requeue_all` to be picking those records up too.

**Comment by mackinra** [comment]
@alexroosenstein One issue I just noticed with your SQL is that it's assuming that `NOW()` will be in the same timezone as the one used in `created_at`.  As it is, my Postal server is apparently using UTC times in that column, while `NOW()` returns the time in my timezone (PDT)... therefore it'll take about 6.5 hours before it's picked up.

**Comment by mackinra** [comment]
...I've changed the line to this, and it seems to do the trick.
```
where("retry_after < ? OR (retry_after IS NULL AND created_at<SUBTIME(?, '0:30:0.000000'))", Time.now, Time.now).limit(100).each(&:queue)
```

**Comment by alexroosenstein** [comment]
I honestly did not (could not?) test that part properly, as I'm still processing webhook requests from a week ago.. Thanks for the updated code, I'll give that a go as well.

**Comment by mackinra** [comment]
For what it's worth, I had over a month of webhook backlog (1M+) myself... I opted to bump your limit clause to 1000.  It just finished processing the backlog after about 24 hours, with minimal impact to ongoing email flow.  After it caught up, I've reverted the limit to 100, as I suspect that'll be enough in the steady state.

**Comment by catphish** [comment]
If you want to do date comparisons in SQL, use `UTC_TIMESTAMP()` instead of `NOW()`, as the name suggests, it will use the UTC timestamp, which is how Rails and Postal store database timestamps.

**Comment by mackinra** [comment]
@catphish That was my assumption, that `Time.now` must be defaulting to UTC.

**Comment by catphish** [comment]
In the case of using `?` and `Time.now` Rails knows to convert the timestamp to UTC before putting it in the query, so this works fine too.
