### ISSUE TITLE
Email inbox on postal

### ISSUE THREAD

**Issue by agnibha** [postalhq/postal#333]
I've setup postal on the domain mail.xsend2.email. I have the domain whitelisted and all configurations are in place.

May I know if I can have a permanent or even a forwarding inbox for this domain?

**Comment by mattmartincouk** [comment]
Postal isn't an inbox or forwarder in that sense.

It is so you can send emails from software/applications to others; allowing you to track delivery, bounces, opens and clicks. The only real inbound addresses you have are traditionally from people replying to those messages, or bounces.

**Comment by agnibha** [comment]
What my major use case is to track SPAMs. I have postmaster tools and feedback loops for GMail and Yahoo activated. I want to have an email forwarder or some kind of webhook system to track these spams through an inbox. In fact, I have bought an inbox. But, it would be great if there was an inbox watcher of sorts to close the spam loop.

**Comment by mackinra** [comment]
@agnibha Look under the Routing tab.  You can forward incoming spam report emails (that are presumably being sent to something in your domain, like abuse@mail.xsend2.email) to an HTTP endpoint (akin to webhooks), another SMTP server or address.  I have this all set up and works great.  If my ruby was better, I'd incorporate it directly into Postal. :)  As such, I route incoming email to abuse@[mydomain] to an HTTP endpoint, using the Raw format (so I can see and parse the entire ARF-formatted email). 

Note: you can route incoming email to any address within your email domain, using the Routing options.

**Comment by XenyFord** [comment]
> @agnibha Look under the Routing tab. You can forward incoming spam report emails (that are presumably being sent to something in your domain, like [abuse@mail.xsend2.email](mailto:abuse@mail.xsend2.email)) to an HTTP endpoint (akin to webhooks), another SMTP server or address. I have this all set up and works great. If my ruby was better, I'd incorporate it directly into Postal. :) As such, I route incoming email to abuse@[mydomain] to an HTTP endpoint, using the Raw format (so I can see and parse the entire ARF-formatted email).
> 
> Note: you can route incoming email to any address within your email domain, using the Routing options.

Hi Sir,
If you don't mind, could you please let me know the steps on how I can forward the bounce message to my custom email, which will be [bounce@mydomain.com](mailto:bounce@mydomain.com), rather than [xysh@psrp.mydomain.com](mailto:xysh@psrp.mydomain.com)? Thank you in advance for your quick response!
