### ISSUE TITLE
can't initialize postal assets

### ISSUE THREAD

**Issue by joaoreis81** [postalhq/postal#338]
while running "postal initialize", I'm getting this:

Initializing database
-- create_table("additional_route_endpoints", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0073s
-- create_table("address_endpoints", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0042s
-- create_table("authie_sessions", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0111s
-- create_table("credentials", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0055s
-- create_table("domains", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0081s
-- create_table("http_endpoints", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0051s
-- create_table("ip_addresses", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0051s
-- create_table("ip_pool_rules", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0053s
-- create_table("ip_pools", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0060s
-- create_table("organization_ip_pools", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0045s
-- create_table("organization_users", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0045s
-- create_table("organizations", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0068s
-- create_table("queued_messages", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0082s
-- create_table("routes", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0060s
-- create_table("servers", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0118s
-- create_table("smtp_endpoints", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0053s
-- create_table("statistics", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0053s
-- create_table("track_certificates", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0232s
-- create_table("track_domains", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0048s
-- create_table("user_invites", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0054s
-- create_table("users", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0071s
-- create_table("webhook_events", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0050s
-- create_table("webhook_requests", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0045s
-- create_table("webhooks", {:force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"})
   -> 0.0052s
-- initialize_schema_migrations_table()
   -> 0.0047s
Compiling Assets
rake aborted!
Sprockets::FileNotFound: couldn't find file 'jquery' with type 'application/javascript'
Checked in these paths: 
  /opt/postal/app/app/assets/config
  /opt/postal/app/app/assets/fonts
  /opt/postal/app/app/assets/images
  /opt/postal/app/app/assets/javascripts
  /opt/postal/app/app/assets/stylesheets
  /opt/postal/app/vendor/assets/javascripts
  /opt/postal/app/vendor/assets/stylesheets
  /opt/postal/vendor/bundle/ruby/2.3.0/gems/turbolinks-source-5.0.0/lib/assets/javascripts
/opt/postal/app/app/assets/javascripts/application/application.coffee:1
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:399:in `resolve'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/bin/bundle:23:in `load'
/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

Thanks

**Comment by joaoreis81** [comment]
On an older version this didn't happened.

**Comment by willpower232** [comment]
I'm confused, why are you running `postal initialize`?

**Comment by joaoreis81** [comment]
the error occurs in a fresh installation in centos 7.

**Comment by willpower232** [comment]
Ah well at the minute Postal is only supported for Ubuntu 16.04. Please study https://github.com/atech/postal/wiki/Quick-Install for more details.

You might be able to get it working but you'll have to change the setup script to use yum etc and I don't think we'll be able to support you much.

**Comment by joaoreis81** [comment]
I have postal running smoothly on centos 7. I just had to install an older version, and then upgrade to the latest - it works. It seems to be more a ruby environment issue than postal problem itself. It would be nice to helping contributing with quick-install for centos 7 when I found out why this happened.

**Comment by willpower232** [comment]
It might be that some of the ruby packages are older in the default Centos repository or something along those lines.

I wouldn't be surprised if the age of packages would be an issue for your Centos experience, if you're able to figure out an install script, it may be that you can include an extra repository to match the Ubuntu versions of things.

Good luck!

**Comment by giezi** [comment]
Hi there, 

I've also the same issue on Ubuntu 16.04 within "postal upgrade":

> /opt/postal/app# postal upgrade
> Compiling Assets
> rake aborted!
> Sprockets::FileNotFound: couldn't find file 'jquery' with type 'application/javascript'
> Checked in these paths: 
>   /opt/postal/app/app/assets/config
>   /opt/postal/app/app/assets/fonts
>   /opt/postal/app/app/assets/images
>   /opt/postal/app/app/assets/javascripts
>   /opt/postal/app/app/assets/stylesheets
>   /opt/postal/app/vendor/assets/javascripts
>   /opt/postal/app/vendor/assets/stylesheets
>   /opt/postal/vendor/bundle/ruby/2.3.0/gems/jquery-ui-rails-4.2.1/app/assets/images
>   /opt/postal/vendor/bundle/ruby/2.3.0/gems/jquery-ui-rails-4.2.1/app/assets/javascripts
>   /opt/postal/vendor/bundle/ruby/2.3.0/gems/jquery-ui-rails-4.2.1/app/assets/stylesheets
>   /opt/postal/vendor/bundle/ruby/2.3.0/gems/turbolinks-source-5.0.3/lib/assets/javascripts
>   /opt/postal/vendor/bundle/ruby/2.3.0/gems/rails-ujs-0.1.0/dist
> /opt/postal/app/app/assets/javascripts/application/application.coffee:1
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:399:in `resolve'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
> /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/cli/exec.rb:75:in `load'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/cli/exec.rb:75:in `kernel_load'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/cli/exec.rb:28:in `run'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/cli.rb:424:in `exec'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/cli.rb:27:in `dispatch'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/cli.rb:18:in `start'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/exe/bundle:30:in `block in <top (required)>'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
> /var/lib/gems/2.3.0/gems/bundler-1.16.0.pre.2/exe/bundle:22:in `<top (required)>'
> /usr/local/bin/bundle:22:in `load'
> /usr/local/bin/bundle:22:in `<main>'
> Tasks: TOP => assets:precompile
> (See full trace by running task with --trace)
> 

Many thanks for any help.

Best regards
Reto

**Comment by willpower232** [comment]
Do you know when you last successfully updated Postal or when you installed it if you haven't ever updated?

**Comment by giezi** [comment]
Hi @willpower232 

The issue occured after a postal upgrade.
Before it never happened (I've done a few updates in the past).

Best regards
Reto

**Comment by willpower232** [comment]
Without knowing roughly when you updated before yesterday it will be difficult to replicate. Probably better someone who knows ruby better hop in at this point.

**Comment by cmmata** [comment]
I had the same problem. At the moment I solved it by modifying Gemfile:
```
-group :development, :assets do
-  gem 'sass-rails', '~> 5.0'
-  gem 'uglifier', '>= 1.3.0'
-  gem 'coffee-rails', '~> 4.2'
-  gem 'jquery-rails'
-end
+gem 'coffee-rails', '~> 4.2'
+gem 'jquery-rails'
+gem 'uglifier', '>= 1.3.0'
+gem 'sass-rails', '~> 5.0'
```
With that change, I could upgrade postal to the last development version (which I need because of  #268).

**Comment by willpower232** [comment]
@afanjul as above, you need to modify the gemfile to remove the specific group markers so that the four gems are always installed then you can re-run `postal upgrade`

**Comment by afanjul** [comment]
OK! it sounds a bit akward (to remove the compiling group) but **it works like a charm**!!! So based that I'm o a perfectly supported Ubuntu 16.04, with a postal server that was running. I think **this should be considered as a bug, and correct it,** isn't it? 

I don't know ruby so I can't figure out what is the reason behind this...   sorry

**Comment by willpower232** [comment]
I'm not show the environment is toggled but it looks like the production environment should have precompiled assets so doesn't need the extra gems. It might be that a more recent commit accidentally set production mode all the time so upgraders have a bad time
