### ISSUE TITLE
queued messages

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#345]
Hey

why i can see some emails are on queued...and Outgoing messages 0? why ?
already set worker 10 and postal restart but still messages are in queue.. please help me

**Comment by sahilsunesara** [comment]
Hello

Still i have been waiting for the above msg reply

**Comment by willpower232** [comment]
Can you send us the output of `postal status` please

**Comment by sahilsunesara** [comment]
root@ns1049:~# postal status
Procodile Version   1.0.17
Application Root    /opt/postal/app
Supervisor PID      3557
Started             2017-09-21 12:02:29 +0200

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      12:02        pid:3969     respawns:2      po                                                                                        rt:-        tag:-

|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.3           Running      12:02        pid:3939     respawns:0      po                                                                                        rt:-        tag:-

|| worker
|| Quantity            10
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.21        Running      12:02        pid:3901     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.22        Running      12:02        pid:3903     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.23        Running      12:02        pid:3905     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.24        Running      12:02        pid:3907     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.25        Running      12:02        pid:3910     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.26        Running      12:02        pid:3912     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.27        Running      12:02        pid:3916     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.28        Running      12:02        pid:3919     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.29        Running      12:02        pid:3922     respawns:0      po                                                                                        rt:-        tag:-
|| => worker.30        Running      12:02        pid:3925     respawns:0      po                                                                                        rt:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.3           Running      12:02        pid:3945     respawns:0      po                                                                                        rt:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      12:02        pid:3971     respawns:2      po                                                                                        rt:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.3       Running      12:02        pid:3944     respawns:0      po                                                                                        rt:-        tag:-
