### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#346]
When i start using postal i after some email sent i got 504 Gateway Timeout error and nothing come up... then after i have to hard restart and then start postal...what will be the reason for this?

**Comment by willpower232** [comment]
You'll have to examine your logs and watch your memory usage to see what is happening

**Comment by mohan-nishit** [comment]
@sahilsunesara I encountered this issue running Postal on a rather small DO droplet ($10). The 2 ways I could get it to work were:

1. Get a bigger server (4GB RAM seems to work fine)
2. Configure swap space on your server to avoid memory issues.

**Comment by willpower232** [comment]
More RAM will solve many problems but without studying the log files to understand what caused the issue, it may not be the final answer.

Also please note that enabling swap on SSD based servers can cause issues with reliability and is generally not recommended, please see https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by sahilsunesara** [comment]
1...I have 4 GB RAM but still same problem...
2... configure swap space ?

**Comment by igerzog** [comment]
> You'll have to examine your logs

Otherwise it will be difficult to determine the reason.

**Comment by sahilsunesara** [comment]
which log fine i need to check?

**Comment by shopglobal** [comment]
Good point
How to enable logs?

Seem disabled by default

**Comment by igerzog** [comment]
All the log files are located here: `/opt/postal/logs/`

**Comment by shopglobal** [comment]
In default install logs created
But disabled

Thank you for all your commits recently.
Can you or a community member point me in the right direction as to where
to enable/disable logs?

My first instinct is to check postal.yml

**Comment by willpower232** [comment]
I do not believe the logs need to be enabled.

If there are no logs and you cannot get postal started to create the logs, you should check the system log files.
