### ISSUE TITLE
Export a list with "Hard Fail" addresses - how to?

### ISSUE THREAD

**Issue by Razva** [postalhq/postal#352]
Hello,
Is there any way to export/extract a list with all addresses that returned a Hard Fail? If yes, some guidance would be highly appreciated.
Thank you

**Comment by willpower232** [comment]
At the minute I believe the only official way is for Webhooks to report message status back to your application but obviously that doesn't help you for emails you have already sent.

It might be possible to use `postal console` but I don't think much of the console is documented.

You could search the database directly as it is a regular MySQL database but again, not documented.

**Comment by Razva** [comment]
Isn't this information stored somewhere in SQL...maybe...?

**Comment by catphish** [comment]
The information is definitely in MySQL. You could create a query to extract all messages with a hard failed status, and get their destination addresses. There's no feature to do this in the UI but you can definitely do so with a SQL query.

**Comment by mohan-nishit** [comment]
To add to what @catphish said, each postal server has its own database (for eg. postal-server-1). You could execute a `SHOW DATABASES;` from the MySQL terminal to get the database for your postal server. Execute a Use statement for that database, followed by `select distinct rcpt_to from messages where status="HardFail";` to get the exact list, if you like the MySQL terminal.
