### ISSUE TITLE
postal not run - error

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#359]
when i start postal it show's me

 We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

**Comment by willpower232** [comment]
You will have to check the files in `/opt/postal/log` to find out what the issue is.

**Comment by sahilsunesara** [comment]
upgrade postal and it's resolve

Thank you so much @willpower232 for your support

**Comment by sahilsunesara** [comment]
hi
i got this error while installing postal 

Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

How to resolve this?

**Comment by mattmartincouk** [comment]
I'd recommend not duplicating tasks/questions (#362)
