### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#360]
Hello

I have set DNS perfectly as per given documentation but if i check spam score from mail- tester.com i got very less score.. it show's -4 for below reason

Your SPF record is unavailable.

More information about this error:

psrp.mydomainname.online: Sender is not authorized by default to use 'n2jxnq@psrp.mydomainname.online' in 'mfrom' identity, however domain is not currently prepared for false failures (mechanism '~all' matched)
The Name Server handling the domain name psrp.mydomainname.online is rp.mail.mydomainname.online.

Need guidance? View guides for each host.

Verification details:

dig +short SPF psrp.mydomainname.online :
rp.mail.mydomainname.online.
dig +short SPF @rp.mail.mydomainname.online. psrp.mydomainname.online :
;; connection timed out; no servers could be reached
spfquery --scope mfrom --id n2jxnq@psrp.mydomainname.online --ip 81.xx.xxx.xxx--helo-id mail.mydomainname.online :
softfail
psrp.mydomainname.online: Sender is not authorized by default to use 'n2jxnq@psrp.mydomainname.online' in 'mfrom' identity, however domain is not currently prepared for false failures (mechanism '~all' matched)
psrp.mydomainname.online: Sender is not authorized by default to use 'n2jxnq@psrp.mydomainname.online' in 'mfrom' identity, however domain is not currently prepared for false failures (mechanism '~all' matched)
Received-SPF: softfail (psrp.mydomainname.online: Sender is not authorized by default to use 'n2jxnq@psrp.mydomainname.online' in 'mfrom' identity, however domain is not currently prepared for false failures (mechanism '~all' matched)) receiver=ns303428.ip-94-23-206.eu; identity=mailfrom; envelope-from="n2jxnq@psrp.mydomainname.online"; helo=mail.mydomainname.online; client-ip=81.xx.xx.xxx

Could you please help me in this matter

**Comment by willpower232** [comment]
On the domains tab in Postal, does it say that your domain has been set up correctly? You can open it up and click on the button to check again.

**Comment by sahilsunesara** [comment]
it's sbow perfectly fine without any issue

**Comment by willpower232** [comment]
Have you created all 3/4 Return Path records for your main postal domain as per https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration?

**Comment by sahilsunesara** [comment]
yes i did the same things.. if you can give me your email id then i will PM you with postal details as well as domain dns record

**Comment by palash76** [comment]
I am unable to verify a domain inside an organisation.

- When I tried the email verification option, it was displaying 4 protected email ids, none of which received the verification option.

- When I tried the DNS verification, I added the TXT record as was expected, but the domain failed to verify even after 3 hours. 

Can anyone suggest a solution please?

**Comment by willpower232** [comment]
> When I tried the email verification option...

This doesn't sound like Postal, are you sure you created this issue in the right place?

**Comment by palash76** [comment]
Yes Will, this is with Postal. :-) 
Can you give me a link to any help file with which I can check on the DNS verification issue? 
New user emails are getting delivered, but DNS verification emails are not sent.

**Comment by willpower232** [comment]
can you send us a screenshot of the verification screen?

**Comment by palash76** [comment]
This is the screenshot of the DNS verification screen https://tppr.me/BhuMn
and
This is the screenshot of the email verification process https://tppr.me/cCs8w

**Comment by sahilsunesara** [comment]
@willpower232 what about my issue ?

**Comment by willpower232** [comment]
@palash76 we create all our users using `postal make-user` as per https://github.com/atech/postal/wiki/Installation#create-your-initial-admin-user so they don't need verifying and haven't seen that screen before! Maybe make sure your `postal.yml` file is set up with an SMTP server to email through?

@sahilsunesara sorry, please email will@screwy.eu

**Comment by palash76** [comment]
@willpower232 I am surprised why you keep saying you have never seen this screen. :-) . To clarify further, I am creating a new user for a new organization inside postal. While creating a new user is successful, and a validation email is also sent and delivered, I get stuck in the domain verification for this new user. 

If you have a help file on DNS verification, I will be grateful.

**Comment by willpower232** [comment]
I have just run some tests using our development Postal and the verification works both ways for me.

I am not sure why you haven't received the email verification messages, if you have configured Postal to send emails via itself, maybe you could see what happened to the messages in there?

The DNS requires you to make a TXT record at the root of the domain with the value from your screen. You can use whatsmydns.net to make sure the record has been set up correctly and is resolving around the world, you should see something like this:

![image](https://user-images.githubusercontent.com/1619102/30781128-997e0db2-a111-11e7-8333-bdcbec823a13.png)
