### ISSUE TITLE
Message delivered - error

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#364]
Hello when i am trying to check sending email using postal test-app-smtp youraddress@mydomain.com i got this error 

Message was not delivered successfully to SMTP server.
Error: Timeout::Error (execution expired)

what will be the reason any idea?

**Comment by willpower232** [comment]
Have you set the smtp server options in `postal.yml`?

**Comment by sahilsunesara** [comment]
yes, did it sameway always as per given link..but still, message are pending status and if i run command from SSH it show's me Message was not delivered successfully to SMTP server.
Error: Timeout::Error (execution expired)

**Comment by willpower232** [comment]
Either the settings are incorrect or you have an issue in your postal still.

**Comment by sahilsunesara** [comment]
if i run comman then sometime message go n show successfully n sometimes show above given error... don't know whats wrong with it
