### ISSUE TITLE
Hard Fail -  error

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#367]
Hello

Why i am not able to send gmail addresses and it show's hard fail 

it show's Permanent SMTP delivery error when sending to gmail-smtp-in.l.google.com (108.177.xx.xx)
550-5.7.1 [81.xx.xx.xx 19] Our system has detected that this message is 550-5.7.1 likely suspicious due to the very low reputation of the sending 550-5.7.1 domain. To best protect our users from spam, the message has been 550-5.7.1 blocked. Please visit 550 5.7.1 https://support.google.com/mail/answer/188131 for more information. l5si8427546wrg.365 - gsmtp
Time: 1.57s
Support Ref: JUNHW74F

**Comment by bslavin** [comment]
This is not an error with Postal, this is because you have been delivering spammy messages from this server to Gmail. Is Postal installed on a dedicated IP and have you been reviewing the messages that are being sent from your system? 

Google is notoriously difficult to deliver email to especially if your IP has been tarnished.

**Comment by sahilsunesara** [comment]
yes postal is installed on dedicated IP

**Comment by willpower232** [comment]
If you're sending spammy messages theres not a lot you can do.

If you aren't sure then you could try using https://www.mail-tester.com/ to see what specifically about the messages could be considered bad.

**Comment by sahilsunesara** [comment]
in mail-tester it show's 8.9 but i can't send email to gmail only... it show's above msg hard fail

**Comment by willpower232** [comment]
Theres not a lot you can do in that case other than get a new IP or domain name and try again but if you're sending spammy messages then this will just keep happening.

**Comment by Manishjodhani** [comment]
If we want to remove this features  from postal then what we will do..??]

**Comment by brinnington** [comment]
Based on my experience, this is an issue with IPv6. Disable IPv6 and get Postal to re-send the email using IPv4 and the email will arrive in the Gmail account.

Additionally, I have 2 other MTAs, not Postal, send the same email (with the same message content) and they have arrived in the same Gmail account. Looking at their email headers, they use IPv4.
