### ISSUE TITLE
Feature Request: message expires/ttl

### ISSUE THREAD

**Issue by wankdanker** [postalhq/postal#373]
First, thank you for such a great project. And, if this feature already exists by way of email headers or something I may have missed, please let me know.

When submitting an email via the REST API, it would be nice to indicate that if an email can not be delivered by a certain date or otherwise within some time frame to just give up on delivery attempts. There is an expires email header (https://tools.ietf.org/html/rfc4021#section-2.1.50), but I am unsure of its officially intended use.

The specific use-case I'm considering is for time-sensitive promotional material. If I send a message on Wednesday for a promotion that ends on Thursday and the message is not delivered by Thursday, I wouldn't want the recipient to receive the message at all. If they receive it on Friday they would be annoyed that they can not get the promotion.

Another might be password reset emails. If an application's password reset feature expires the password reset token within a certain time frame and the message is not delivered in that time frame, then it would be great to not deliver a non-functional message.

I would expect that such a feature would also create webhook events so that the application may be able to respond to the situation appropriately.

**Comment by willpower232** [comment]
Typically Postal is able to send messages straight away or after a short delay. Unless you are submitting billions of messages to an under resourced or badly configured server of course.

That does sound like a great feature, however without support from all email clients, servers, and providers, it wouldn't be possible to deploy it with great accuracy or reliability.

**Comment by wankdanker** [comment]
I'm not faulting Postal for not sending the messages out in time, it was definitely trying. The issue was our standing with the remote mail server; they were not accepting our mail. This feature would just allow us to tell Postal: if you can't deliver this by a certain time for whatever reason, just give up.

**Comment by willpower232** [comment]
Ah I see, it might be worth using something like https://www.mail-tester.com/ to verify how good your messages are.
