### ISSUE TITLE
Don't rewrite bounce address

### ISSUE THREAD

**Issue by WilliamDEdwards** [postalhq/postal#382]
Hi,

I have a customer who wants to use Postal but his bounce address is rewritten by Postal to a random ID at the Postal server. However, he doesn't want the bounce address to be rewritten in any way and simply have bounces returned to the system he's using to send the emails (using SMTP) because that system handles the bounces (AcyMailing).

How do I disable this?

**Comment by WilliamDEdwards** [comment]
In other words: I want to leave the Return-path header out.

**Comment by WilliamDEdwards** [comment]
Already did it.

**Comment by WilliamDEdwards** [comment]
Not quite fixed yet. The bounce address is now the From address instead of the bounce address specified in AcyMailing. Can somebody help me out?

**Comment by willpower232** [comment]
Please see https://github.com/atech/postal/issues/245, unfortunately this is somewhere in the to-do list as far as I can tell.

**Comment by willpower232** [comment]
closing in favour of #255

**Comment by ugurtam** [comment]
> Not quite fixed yet. The bounce address is now the From address instead of the bounce address specified in AcyMailing. Can somebody help me out?

That's exactly what I want. In my case return path should be the "from address". How can I do this ? Very important for me!

**Comment by CarlosFongo** [comment]
> > Not quite fixed yet. The bounce address is now the From address instead of the bounce address specified in AcyMailing. Can somebody help me out?
> 
> That's exactly what I want. In my case return path should be the "from address". How can I do this ? Very important for me!

Hi, did you find a solution?

**Comment by ugurtam** [comment]
Maybe @adamcooke can help about this feature
