### ISSUE TITLE
After full install returns ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by PtkFerraro** [postalhq/postal#389]
Just did the normal installation (not the fast one), everything went OK.

But when I try to access my domain, chrome throws 'ERR_TOO_MANY_REDIRECTS', even when I try the https address...

what could be?

cheers

**Comment by willpower232** [comment]
Do you get the error in other browsers? If you don't, have a look at this https://www.drivereasy.com/knowledge/how-to-fix-err-too-many-redirects-error/

If you do get the error in other browsers, you should review your nginx configuration to see if you accidentally have conflicting redirects.

If you can access the raw IP address for your Postal then you could also have a look at how the domain name you are using has been set up in case its conflicting with a redirect from somewhere else.

**Comment by PtkFerraro** [comment]
Will,

All browsers have the same problem and I can't access direct by ip...

**Comment by willpower232** [comment]
Would you mind sharing your nginx configuration for the site?

**Comment by PtkFerraro** [comment]
Not at all... it´s just a testing server...

`server {
    listen [::]:80;
    listen 0.0.0.0:80;
    server_name mail.ptk-postal.info;
    return 301 https://$host$request_uri;
}

server {
    listen [::]:443 ssl;
    listen 0.0.0.0:443 ssl;
    root /opt/postal/app/public;
    server_name mail.ptk-postal.info;
    ssl_certificate      ssl/postal.cert;
    ssl_certificate_key  ssl/postal.key;

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }
}`

**Comment by willpower232** [comment]
I see that you have Cloudflare set up for mail.ptk-postal.info. Are you able to stop using (or temporarily disable) Cloudflare to see if this restores your access?

**Comment by pablomelo** [comment]
@PtkFerraro,

I had the same issue, using Cloudflare. 

My guess is that on Cloudflare, the `SSL` option inside the `Crypto`  setup as `Flexible` will make the traffic always hit on port 80, which will trigger the redirect. 

If you are using a CDN like Cloudflare, I suggest moving the `listen :80` to the other `server` block and set it up at the CDN level to force all traffic through https.

Or (with Cloudflare) you can set the SSL as "Full". Which will hit the port 443, but it might not hit the port 80.
