### ISSUE TITLE
digitealocean setup

### ISSUE THREAD

**Issue by masihfathi** [postalhq/postal#392]
Hi again, for testing postal, I create a  vps in digitalocean, right now, in setup DNS, what should I do? 
as default can use, ns1.digitealcocean.com as a nameserver.
should I install BIND and point like this: ns1.mydomain.com and ns2.mydmain.com and point to these name server in my domain registration?

**Comment by willpower232** [comment]
Where you operate your DNS from is up to you. If you want to host your own nameservers, I would recommend not installing BIND on the same server as Postal to avoid awkward logistics later.

**Comment by masihfathi** [comment]
What is your suggestion  for domain settings on a dedicated server?

**Comment by willpower232** [comment]
Presumably you already have the DNS set up somewhere so unless you want to move it, why not leave it where it is?

If you want to move it, DigitalOceans DNS service is very good. There are of course many options. It really doesn't matter as per my earlier response.

All you need to be able to do is create the records mentioned in the Wiki.

**Comment by masihfathi** [comment]
I know my question may be outside of postal
But I am grateful for your guidance. I could set it up with digitealocean,
Now consider this scenario. I have a dedicated server with 8 IPs. My domain registrar doesn't dns server feature. 
It came to my mind. Virtualize this server. and host one of the machines along with a domain as dns server. Is it a good way?

**Comment by willpower232** [comment]
If you can't make DNS records with your domain registrar then Cloudflare and Digitalocean are both good options. Personally I would use a provider rather than host myself but as long as you can make the records Postal needs, it doesn't really matter.

**Comment by Mr-Binary** [comment]
@masihfathi  also consider using Route 53
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/Welcome.html
In that page you also have extensive information about all the basics about how DNS works.

Managing your own DNS server is not too hard (easier than managing your own SMTP server) but doing it properly is certainly not trivial and the risks in case of miss-configuration or being hacked are potentially fatal. As there are so many good services and many decent free services I would try to find a good provider.

In my opinion, the only use case where it could be worth to manage your own, would be to shorten the response times for a really busy mail server.

Anyway, can´t believe your registrar would not provide you with basic DNS, maybe it´s time for a new registrar...

**Comment by NikhilSaini38** [comment]
I am hosting postal on Digital ocean server, the email transaction is not working. Queued email show soft fail with reason mx.postal.<mydomain>.<mytld>. for record mydomain and tld are hidden for privacy.

**Comment by navinp** [comment]
Hello,

When you do **postal status** what does it give?

**Comment by NikhilSaini38** [comment]
hey navin this is from command ```postal status```
```Procodile Version   1.0.19
Application Root    /opt/postal/app
Supervisor PID      23662
Started             2018-07-21 09:30:11 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      09:30        pid:23668    respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      09:30        pid:23670    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      09:30        pid:23672    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      09:30        pid:23674    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      09:30        pid:23676    respawns:0      port:-        tag:-
```

**Comment by NikhilSaini38** [comment]
@navinp i have posted the output, are you able to guess what might be the problem?

**Comment by willpower232** [comment]
Based on other issues it is likely that Digital Ocean is blocking the SMTP, have you contacted them to unlock it for your account?

**Comment by navinp** [comment]
Not sure about that, but it’s good to contact support and ask if the ports are blocked.

I am also DO customer and nothing is/was blocked

**Comment by NikhilSaini38** [comment]
Lets see, i'll check my ufw too
