### ISSUE TITLE
Could not find acme-client-0.5.5 in any of the sources

### ISSUE THREAD

**Issue by amanjuman** [postalhq/postal#394]
After executing .sh file. I try to run `postal make-user` command but getting an error as below.
```
root@mail:~# postal make-user
Could not find acme-client-0.5.5 in any of the sources
Run `bundle install` to install missing gems.
```
I'm using Ubuntu 16.04 x64 on Digital Ocean. Any way to fix?

**Comment by willpower232** [comment]
Are you able to try `postal upgrade` or a fresh reinstall?

**Comment by amanjuman** [comment]
```
root@mail:~# postal upgrade
Migrating database
Could not find acme-client-0.5.5 in any of the sources
Run `bundle install` to install missing gems.
root@mail:~# ./ubuntu1604.sh
root@mail:~# postal make-user
Could not find acme-client-0.5.5 in any of the sources
Run `bundle install` to install missing gems.
root@mail:~# postal upgrade
Migrating database
Could not find acme-client-0.5.5 in any of the sources
Run `bundle install` to install missing gems.
```
Same issue

**Comment by willpower232** [comment]
I've just done a clean install and it seems to be working. Are you able to destroy and recreate your server?

**Comment by amanjuman** [comment]
Tried again, New issue.
`Fetching gem metadata from https://rubygems.org/...........
Fetching rake 11.3.0
Installing rake 11.3.0
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.9.2
Installing faraday 0.9.2
Fetching acme-client 0.5.5
Installing acme-client 0.5.5
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 0.8.1
Installing i18n 0.8.1
Fetching minitest 5.10.1
Installing minitest 5.10.1
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.3
Installing tzinfo 1.2.3
Fetching activesupport 5.0.2
Installing activesupport 5.0.2
Fetching builder 3.2.3
Installing builder 3.2.3
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching mini_portile2 2.1.0
Installing mini_portile2 2.1.0
Fetching nokogiri 1.7.2
Installing nokogiri 1.7.2 with native extensions
/usr/bin/postal: line 19: 11432 Killed                  sudo -u postal bundle install --path=/opt/postal/vendor/bundle --jobs=2 --clean --without=development assets
root@mail:~# postal make-user
Could not find nokogiri-1.7.2 in any of the sources
Run `bundle install` to install missing gems.
root@mail:~# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application
for all non-root users on this machine.
Could not locate Gemfile
root@mail:~#
`

**Comment by amanjuman** [comment]
I think script need modification.
```
root@mail:~# postal make-user
Could not find nokogiri-1.7.2 in any of the sources
Run `bundle install` to install missing gems.
root@mail:~# gem list nokogiri --remote

*** REMOTE GEMS ***

backupify-rsolr-nokogiri (0.12.1.1)
epp-nokogiri (1.1.0)
glebm-nokogiri (1.4.2.1)
jwagener-nokogiri (1.4.1)
nokogiri (1.8.1 ruby java x64-mingw32 x86-mingw32, 1.6.1 x86-mswin32-60, 1.4.4.1 x86-mswin32)
nokogiri-cache (1.0.0)
nokogiri-diff (0.2.0)
nokogiri-fitzsimmons (1.5.5.3 ruby java)
nokogiri-happymapper (0.6.0)
nokogiri-happymapper-deiga (0.5.10)
nokogiri-maglev- (1.5.5.20120817130721)
nokogiri-maven (1.5.0 java)
nokogiri-plist (0.5.0)
nokogiri-pretty (0.1.0)
nokogiri-streaming-reader (1.2)
nokogiri-styles (0.1.2)
nokogiri-tools (1.0.0)
nokogiri-xml-range (0.1.0)
nokogiri-xmlsec (0.0.4)
nokogiri-xmlsec-me-harder (0.9.2)
nokogiri-xmlsec1 (0.0.11)
nokogiri_bang_finders (1.1.0)
nokogiri_helper (0.0.1)
nokogiri_html_helpers (0.1.4)
nokogiri_truncate_html (0.0.5)
rack-nokogiri (0.1.0)
ratom-nokogiri (0.10.6)
revo-nokogiri (1.4.1 java)
rsolr-nokogiri (0.0.0)
rss-nokogiri (0.0.1.1)
rubyjedi-nokogiri_java (1.4.0.20100513161003 java)
sax-machine-nokogiri-1.4.4-safe (0.0.15)
schematron-nokogiri (0.0.3)
spp_nokogiri_ext (0.0.5)
superfeedr-nokogiri (1.4.0.20091116183308)
tag_remover_nokogiri (0.0.2)
tenderlove-nokogiri (0.0.0.20081001111445, 0.0.0 x86-mswin32-60)
unobtainium-nokogiri (0.1.2)
vulnerable-nokogiri (0.0.1)
watir-nokogiri (1.0.0)
root@mail:~#

```

**Comment by willpower232** [comment]
In your example you received this:
> /usr/bin/postal: line 19: 11432 Killed                  sudo -u postal bundle install --path=/opt/postal/vendor/bundle --jobs=2 --clean --without=development assets

I have only received this message when using a server that doesn't have enough memory. Try deleting your server and getting at least the next size up with more memory.

**Comment by taewookim** [comment]
> I have only received this message when using a server that doesn't have enough memory. Try deleting your server and getting at least the next size up with more memory.

I read the wiki and it says min 8 gig of memory. WHy so much?

**Comment by willpower232** [comment]
The default installation has a MySQL service running on the same server which means that there is a significant risk of running out of memory, especially if you want to use every feature of Postal.

If you're able to install Postal more manually and reference MySQL installed and configured elsewhere then you may be able to have less memory available directly for your actual Postal server.
