### ISSUE TITLE
Click tracking domain SSL certificate verification fails

### ISSUE THREAD

**Issue by farhadhf** [postalhq/postal#396]
Having postal installed on `postalserver.com` I've added two mail servers:

* `postalserver.com` (for sending emails related to postal itself)
* `example.com` (for sending emails related to our production application)

I've also enabled fast_server and click tracking on `postalserver.com` successfully (through `click.postalserver.com`).

I'm trying to do the same thing with `click.example.com` on the `example.com` mail server, but the SSL setup does not complete (CNAME record verification has completed successfully).

letsencrypt.log:

```
[4882] [2017-10-30T07:17:12.025] INFO -- : Successfully registered private key with address farhad@example.com
[4882] [2017-10-30T07:17:12.243] INFO -- : Terms have been accepted
[worker.1:4529] [2017-10-30T07:30:00.809] INFO -- : Attempting verification of click.postalserver.com
[worker.1:4529] [2017-10-30T07:30:02.812] INFO -- : Getting certificate for click.postalserver.com
[worker.1:4529] [2017-10-30T07:30:04.038] INFO -- : Certificate issued (expires on 2018-01-28 06:30:03 UTC, will renew after 2018-01-04 06:30:03 UTC)
[worker.1:14573] [2017-10-30T08:15:01.090] INFO -- : Attempting verification of click.example.com
[worker.1:14573] [2017-10-30T08:15:03.623] INFO -- : Status was not valid (was: invalid)
[worker.1:16137] [2017-10-30T11:15:00.696] INFO -- : Attempting verification of click.example.com
[worker.1:16137] [2017-10-30T11:15:02.876] INFO -- : Status was not valid (was: invalid)
[22224] [2017-10-30T11:26:52.343] INFO -- : Attempting verification of click.example.com
[22224] [2017-10-30T11:26:54.323] INFO -- : Status was not valid (was: invalid)
```

I also tried running the console commands (`postal console`) mentioned in #93 to see if I can get more information on the error, but `cert.get` just returns `false`.

```
root@postalserver:/opt/postal/log# postal console
Loading production environment (Rails 5.0.2)
irb(main):001:0> cert = TrackCertificate.find_by(:domain => "click.example.com")
=> #<TrackCertificate id: 3, domain: "click.example.com", certificate: nil, intermediaries: nil, key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAt+...", expires_at: nil, renew_after: "2017-10-31 11:15:02", verification_path: ".well-known/acme-challenge/GrMZZOuGyWh7sEW4Iga9zBI...", verification_string: "GrMZZOuGyWh7sEW4Iga9zBI7UsF8EMrMugCsdHuTlaw.dc-ayF...", created_at: "2017-10-30 11:06:39", updated_at: "2017-10-30 11:26:52">
irb(main):002:0> cert.active?
=> false
irb(main):003:0> cert.get
=> false
```

**Comment by farhadhf** [comment]
Seems like Postal is generating a certificate, but for the wrong domain? It should be generating the certificate for click.example.com but Chrome's error is NET::ERR_CERT_COMMON_NAME_INVALID.

![screen shot 2017-10-30 at 5 22 39 pm](https://user-images.githubusercontent.com/1378901/32174584-87a8402e-bd97-11e7-9f18-ccfc7a3cc107.png)

**Comment by hadifarnoud** [comment]
any update on this? have the same issue

**Comment by farhadhf** [comment]
Not really, I never managed to get it working unfortunately.

**Comment by willpower232** [comment]
It sounds like you have put the same IP address in your DNS records for click tracking and the Postal interface itself.

Click tracking requires a separate IP address as per https://github.com/atech/postal/wiki/Click-&-Open-Tracking
