### ISSUE TITLE
User and Organization accounting ( limit max total emails sent per month/year)

### ISSUE THREAD

**Issue by extremeshok** [postalhq/postal#400]
Did some searching and have not found anything. 

Been testing postal, it seems the only limit is emails per hour. 

Is there anyway to assign a maximum allowed number of emails a user/organization is allowed to send per a month ?

Or to implement an accounting system with some conditionals, ie disable account or set to debug when send emails are over X per X days

ie.
somecompany can send a max of 100 000 emails per a month

another user can send 10 000 emails per a year.

**Comment by willpower232** [comment]
This is not currently part of Postals features but you could implement this in your app. There is a wider issue in needing more statistics as well.

The limit applied by Postal simply holds other emails so its not much of a block anyway.

**Comment by Mr-Binary** [comment]
I also believe alternative ways of usage accounting would be very helpful.
