### ISSUE TITLE
Outbound mail for to different Mail server with postal but Authentication Error:550 exist

### ISSUE THREAD

**Issue by rc111** [postalhq/postal#403]
I want to send mails beween to mail  servers by the help of postal mail server . In this connect the postal and any other mail server. postal is send the mail to the other mail server as an client . HERE is the scenario: 
1. mail client send the mail  to the recipient in between the sender and receiver two mail server is exist .
a) postal mail server
b) any other mail server
2. postal accept mail from the sender and send it to the second mail server, now the postal mail server is  worked as an client of the second mail server.
3.second mail server is accept or receive the mail from the postal mail server, and send to the real receiver.
4. receiver accept the mail and read it the information.
This is my  work scenario.

Error:
but in between the two mail server the postal mail  server always send the Error , "550 Authentication required" , the postal mail server hold the my mail every time and suspense the mail id .   
      
Here is any solution  for this that i can connect the any  mail server  to each  other and send the mail to the any receiver without any connection down and Authentication.

**Comment by willpower232** [comment]
Please include a description of your problem and how you are trying to use Postal.

**Comment by rc111** [comment]
I'm using the postal in my own network with default configuration. 
when i'm send the mail by single postal mail server then the mail delivered to the receiver properly . 
means 

my mail  ----> postal mail server --> receiver  (delivered properly).

This is an default behavior.but my working is, 

my mail --> postal mail server --> other mail server --> receiver (delivered properly).


BUT in both mail server 550: Authentication Error Exist , and postal says for "Hard Fail " and suspense my mail ip.

**Comment by rc111** [comment]
I'm using the other mail server as an smtp_relay of the postal mail server. 

smtp_relays:
  - 
    hostname: vps.highfashion.biz
    port: 25
    username: vps
    password: jhgt6&((^%GGFRYEuje55
  #  from_address: info@rccess.org
    ssl_mode: Auto

**Comment by rc111** [comment]
Is it any way that postal not using the authentication between the mail servers.

**Comment by willpower232** [comment]
Have a look at https://github.com/atech/postal/issues/48

> [authentication on SMTP relays] isn't supported. You should configure your relay to allow connections from the IP of your Postal server.

**Comment by rc111** [comment]
#48 says that  i also configure the relay in the other mail server, if i understand write , but how to configure the relaying in postal

**Comment by rc111** [comment]
Is it any smtp forward feature available for the postal
