### ISSUE TITLE
procodile.log disk usage

### ISSUE THREAD

**Issue by mackinra** [postalhq/postal#407]
I just noticed that there's a procodile.log being written to /tmp/postal, and it appears that's it's never being purged or rotated.  And after growing for 3+ months, it's using up most of the disk space on our postal server. 

What was the intent of this log, and how it would be managed over time?

**Comment by willpower232** [comment]
It looks like it records how the processes work and any errors they encounter. Ours is only 76K so I guess it gets reset on server reboot or something.

Procodile is a separate repo here https://github.com/adamcooke/procodile so it might be worth asking this question there.

If you don't restart your server (namely for kernel updates) that may clear the log then I wonder if @adamcooke would be able to suggest an appropriate `logrotate` configuration for this.

I don't think the file is critical so if restarting the server is not possible or sufficient to empty the file, I'd suggest running `postal stop`, deleting the file, and then running `postal start` at a time convenient to you.

**Comment by mackinra** [comment]
Thanks for the info.  By the way, I have restarted Postal several times over the past few months, and coincidentally the procodile process always seems to refuse being shutdown and I’ve had to resort to killing it.  Is that a known issue?

**Comment by willpower232** [comment]
We've never experienced it. I just schedule late night shutdowns with the OS and Postal has no issues.

When you say the procodile process keeps running, do you mean its still there after a `postal stop`? Or does the `postal stop` never complete?

**Comment by willpower232** [comment]
Back on your initial problem, it might be worth reviewing the contents of the log file yourself, it may be there are some issues in your setup.

Are you running the queue and MySQL server on the same server as Postal?

**Comment by mackinra** [comment]
`postal stop` is not completing.  It reports that the it's stopped the worker processes, for example, but I can see in another shell that they're still running.  I usually have to resort to manually killing them.  It wasn't always like this.  `postal stop` used to function properly.  Here is the output I see (and it stays like this indefinitely until I intervene):

```Stopped web.1 (PID: 31082)
Stopped worker.1 (PID: 31084)
Stopped worker.2 (PID: 31086)
Stopped worker.3 (PID: 31088)
Stopped worker.4 (PID: 31091)
Stopped cron.1 (PID: 31096)
Stopped smtp.1 (PID: 31098)
Stopped requeuer.1 (PID: 31102)
Supervisor will be stopped when processes are stopped.
Waiting for supervisor to stop...```

**Comment by mackinra** [comment]
And yes, everything is running on the same host.

**Comment by mackinra** [comment]
So I had a look at the procodile.log and did notice a large number of warnings.  I seeing the same pattern repeated thousands of times:

```ESC[33m15:42:25 smtp.1          | ESC[0mESC[33m=> ESC[0mWARNING: Could not parse (and so ignoring) 'by mail1.foobarinc.com (Postfix) with ESMTP id 26BB781570
ESC[33m15:42:25 smtp.1          | ESC[0mESC[33m=> ESC[0m        for <dpsmith@redacted.com>; Tue, 21 Nov 2017 15:42:23 -0800 (PST)
ESC[33m15:42:25 smtp.1          | ESC[0mESC[33m=> ESC[0m        by worker2 (Postfix) with ESMTP id 24B878180D
ESC[33m15:42:25 smtp.1          | ESC[0mESC[33m=> ESC[0m        for <dpsmith@redacted.com>; Tue, 21 Nov 2017 15:42:23 -0800 (PST)'
ESC[36m15:42:25 worker.3        | ESC[0mESC[36m=> ESC[0mWARNING: Could not parse (and so ignoring) 'by mail1.foobarinc.com (Postfix) with ESMTP id 26BB781570
ESC[36m15:42:25 worker.3        | ESC[0mESC[36m=> ESC[0m        for <dpsmith@redacted.com>; Tue, 21 Nov 2017 15:42:23 -0800 (PST)
ESC[36m15:42:25 worker.3        | ESC[0mESC[36m=> ESC[0m        by worker2 (Postfix) with ESMTP id 24B878180D
ESC[36m15:42:25 worker.3        | ESC[0mESC[36m=> ESC[0m        for <dpsmith@redacted.com>; Tue, 21 Nov 2017 15:42:23 -0800 (PST)'
```

`mail1@foobarinc.com` represents the Postfix server of ours that relays mail into Postal.  Each batch of these lines has a different arbitrary email recipient.  I'm thinking this has something to do with that patch I did for stripping Received headers.

**Comment by willpower232** [comment]
Did you mean https://github.com/atech/postal/pull/282?

Since that pull request is part of the main code now, you could try a `postal auto-upgrade` to reset your code to what is current.

**Comment by mackinra** [comment]
I updated my copy of client.rb, to handle the continuation lines of Received headers and those warnings have gone away.  

Now just need to figure out why procodile isn't gracefully stopping.  Another clue seems to be that of the 4 worker processes I start Postal with, the last one (`worker.4`) seems to be refusing to stop.  If I intervene with a `kill -SIGQUIT` on the worker process, the `postal stop` seems to then complete it's job.  Looks like @adamcooke wrote procodile.  Perhaps he might know what's going on there.
