### ISSUE TITLE
Hide Source host via API

### ISSUE THREAD

**Issue by danielsmay** [postalhq/postal#457]
Is it possible to hide the Source Host of a message sent via the API?

This issue here discusses it for SMTP https://github.com/atech/postal/issues/86

**Comment by danielsmay** [comment]
It should be as easy as adding a setting in the config and removing this, yes?
https://github.com/atech/postal/blob/master/app/models/outgoing_message_prototype.rb#L182

**Comment by willpower232** [comment]
Yes, arguably it could use the same setting since there probably isn't a case where you want to hide one and show the other but I'd wait for comment from atech on that front.
