### ISSUE TITLE
Multiple SPF Records on a single instance? 

### ISSUE THREAD

**Issue by danielsmay** [postalhq/postal#458]
This comment says that the typical user of Postal has many domains on it with each SPF record pointing to the single installation of postal.
https://github.com/atech/postal/issues/409#issuecomment-345643445

Is it possible to have an SPF record for each domain (or even just multiple SPF records) through a single postal installation? Furthermore, would it be possible to do something similar for return_path, and tracking domains?

**Comment by willpower232** [comment]
I'm not sure you have understood the process.

The domain you run Postal from should have a record called something like spf.postal.yourcompany.com which points to the IP address of the server. Then every domain you want to send email from includes spf.postal.yourcompany.com in their SPF record.

What are you trying to accomplish?

**Comment by danielsmay** [comment]
Yes, that's as I understand it.

I'm wanting to send mail from a central postal installation from multiple domains that have no reference to the central postal installation in the message itself.

**Comment by influenist** [comment]
Thats why you verify the IP / postal installation by adding a SPF record to the domains in question.

So you have domains:
domain-a.com
domain-b.net
domain-c.org

Your postal domain is:
postal.domain-f.biz

Default the SPF domain for your postal installation / domain has been setup as:
spf.postal.domain-f.biz

(Please also look at the DNS intruction for your postal domain at  https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration)

To verify your domains with SPF, you want to add TXT records to the DNS zones of your domain. So for domain-a.com you add the following:
domain-a.com TXT "v=spf1 a mx include:spf.postal.domain-f.biz ~all"

**Comment by willpower232** [comment]
@danielsmay there is nothing stopping you from creating your own differently named records in each domain you manage in Postal, it may be confusing for other Postal users who aren't expecting it and I'm not sure if Postal will include the SPF header if it knows the SPF record is "missing".

Also as messages will include a sending IP header, you aren't really concealing much from people.
