### ISSUE TITLE
Google does not allow access to port 25 from a Google instance.

### ISSUE THREAD

**Issue by sophatvathana** [postalhq/postal#461]
Google does not allow access to port 25 from a Google instance.(https://cloud.google.com/compute/docs/tutorials/sending-mail/).
So how could I use the different port like 2525? Thanks

**Comment by willpower232** [comment]
You can specify the SMTP server port by adding a config value to your `postal.yml` (see default here: https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L67)

Alternatively, you can keep 25 open and use 2525 as well by using iptables like this https://github.com/atech/postal/issues/306#issuecomment-321571866
