### ISSUE TITLE
Messages are not sending

### ISSUE THREAD

**Issue by vscool19** [postalhq/postal#462]
Hi @willpower232 
one of my tester is try to send messages via api and smtp but both are going into pending status and not getting change since 24 hours. 
There are no messages in queue other than that.
On same instance I am trying to send message with other server and it goes fine and get sent. 
dint get what is happening.

**Comment by willpower232** [comment]
Can you run `postal status` to see what is happening? Are you using IP Pools?

**Comment by vscool19** [comment]
Yes i am using IP Pools.

**Comment by vscool19** [comment]
@willpower232  I tried with postal status and find that all workers are running fine.

**Comment by willpower232** [comment]
Did `postal status` mention anything that wasn't running?

**Comment by vscool19** [comment]
![screenshot from 2018-01-17 17-26-23](https://user-images.githubusercontent.com/11226836/35041690-a3dc7998-fbab-11e7-8e93-90673657d924.png)
![screenshot from 2018-01-17 17-26-48](https://user-images.githubusercontent.com/11226836/35041702-ac8725ac-fbab-11e7-9d1e-f4a30fa9a16e.png)

No all are running fine as shown in above images

**Comment by vscool19** [comment]
@willpower232 I dint get why it is picking for one server and not picking for another server.

**Comment by willpower232** [comment]
Have you tried restarting Postal?

**Comment by vscool19** [comment]
yes I tried 2-3 times

**Comment by willpower232** [comment]
Either something isn't quite right in your settings or you need to restart the whole server for some reason. If you can arrange for a restart, that will tell you what the problem is.

**Comment by vscool19** [comment]
I can restart the server but the thing is in same instance mails are getting sent through one mail server and not getting sent through another mail server. 
I have checked mail server configuration for both mail server and find nothing wrong in that.
@willpower232  can you tell me that. when unqueue_message_job picking queue messages ?

**Comment by willpower232** [comment]
I'm afraid we don't use IP Pools so haven't really got any familiarity with what could be going wrong having checked everything else.

**Comment by vscool19** [comment]
As per my knowledge, IP Pool will come into picture when even one delivery attempt has made by application. But here no delivery attempts was made by application and messages are still in pending.

**Comment by vscool19** [comment]
Changed the IP Pool to other and it works. Dint get why it was not working with that IP Pool?

**Comment by willpower232** [comment]
That would imply that the settings for the not working IP Pool are wrong. If you run `ip a` on the server you can verify that the IP address is available on the server but I don't know what else could be wrong off the top of my head.

**Comment by vscool19** [comment]
Okay I will check that. Thanks for the support.

**Comment by vscool19** [comment]
@willpower232  same pending problem happen again. Some email got stuck in pending state since 1 - 2 days. No worker has attempt that mails yet. Don't know what is the actual reason.

![postal-1](https://user-images.githubusercontent.com/11226836/44458154-eff96d00-a622-11e8-97cd-7ca0a6de9a85.png)

![screenshot from 2018-08-22 15-46-39](https://user-images.githubusercontent.com/11226836/44458159-f7b91180-a622-11e8-81ac-6fbaa5d03428.png)

Having 6 workers and all are running fine as you can see in above screenshots. 
Whatever IPs assign to that mail server are available there as i have checked through **ip a**

**Comment by willpower232** [comment]
If they're getting stuck, you could try setting up Sentry and reporting any exceptions

https://github.com/atech/postal/issues/597#issuecomment-396082284

**Comment by vscool19** [comment]
Okay thanks I will check

**Comment by Williamisbest** [comment]
My requeuer and worker are not running it is written there failed, what should I do? Please anyone help me..

**Comment by virendrasinght** [comment]
@Williamisbest  check worker log once in application or do postal stop and postal start

**Comment by willpower232** [comment]
@Williamisbest please open a new issue rather than commenting on a long closed one. That said, have a look at #1339 which may be relevant to you.

**Comment by acbsalman** [comment]
Hello,
After successfully install postal, then i saw postal status UP
but when try to send mail from smtper.net or any app its just loading loading then showing no response from mail server.
And also i try to send mail from postal panel but its just loading loading.
Please how to fix it.

Thanks
