### ISSUE TITLE
Gmail spam problem

### ISSUE THREAD

**Issue by Ishma59** [postalhq/postal#464]
everything is set and i'm able to send mail from my postal server......thanks to the community for the help
the only problem i'm having is when i send mail to mails such as yahoo from postal they are okay but when i send to gmail they are flaged as spam emails.....i just cant understand any help please

**Comment by daseinhorn** [comment]
Gmail has very restrictive SPAM "filters" and rules. For example, when using a not known IP to send E-Mails, they are often flagged as SPAM. Also, there is pretty restrictive rate limiting for unknown IP. 
The second reason could be that maybe the IP you are using is on a blacklist because a previous owner sent SPAM with it and got reported.

**Comment by Ishma59** [comment]
but the main problem is that when i use the postal interface to send mail  l to @gmail.com it is flagged as spam but when i configure thunderbird to send mail through my postal server its not flagged as spam by gmail......

**Comment by Ishma59** [comment]
and the problem with the thunderbird -- postal server connection  is connection keeps timing out

**Comment by willpower232** [comment]
Try sending one of your emails to https://www.mail-tester.com/ and see what they say.

**Comment by Ishma59** [comment]
Click here to view your message
-1.6
SpamAssassin thinks you can improve
-4
You're not fully authenticated
Your message could be improved
-0.5
You're listed in 1 blacklist

**Comment by willpower232** [comment]
The black list definitely will be a contributor but "you're not fully authenticated" implies there might be a problem with your DKIM and/or SPF records as well.

**Comment by masihfathi** [comment]
An Experimental Case in Gmail
Start with low send and gradually increase. After almost a month, your email will be inbox,
Sending with new IPs, take about a month to be inbox and you should wait.
Of course, I suggest register your IPs  and domains in 
https://postmaster.google.com/
