### ISSUE TITLE
Mail route between two Postal domains are not being logged.

### ISSUE THREAD

**Issue by influenist** [postalhq/postal#467]
Hi,

I notice mails between two domains using Postal are not being logged as incomming messages. Case:
domainA.com EXIM Smarthost SMTP > Postal domainA.com SMTP > SMTP Endpoint (EXIM) domainB.com

On domainA.com the mail is being logged as outgoing message. But it is not logged on the incoming messages side of domainB.com. Wishful situation:

domainA.com EXIM Smarthost SMTP > Postal domainA.com SMTP > internal route > Postal domainB.com MX > SMTP Endpoint (EXIM) domainB.com

Any idea's on this matter?

**Comment by influenist** [comment]
Hi Will. The Exim servers are hosted externally on public IPs.

**Comment by willpower232** [comment]
So are domainA and domainB in the same installation of Postal but emails from domainA to domainB don't appear on the domainB messages page?

**Comment by influenist** [comment]
Hi @willpower232, this is correct. The outbound messages are being logged at domainA. Hence they do not appear on inbound messages log at domainB. 
domainA has external EXIM server. The EXIM server of domain B is not the same as domainA.

192.168.10.1 - EXIM domanA > 192.168.20.1 inbound logged for DomainA by Postal / outbound not logged for domainB by Postal > 192.168.30.1 - EXIM domainB successful accepted the message from Postal.

**Comment by willpower232** [comment]
So the message arrives successfully but doesn't appear in the outgoing messages tab in Postal for both domainA and domainB?

Can you look directly in the databases with a program like HeidiSQL to find the message?

**Comment by willpower232** [comment]
Each mailserver in Postal is its own database. If you have many, you can look in the main postal database which should tell you which database corresponds to which mailserver.
