### ISSUE TITLE
Remove Held messages, not release or re-add them to queue 

### ISSUE THREAD

**Issue by influenist** [postalhq/postal#469]
Hi, 
As disucesed in https://github.com/atech/postal/issues/239 https://github.com/atech/postal/issues/257 https://github.com/atech/postal/issues/256 

There are options to reapply the held messages to the queue. But how to remove them? Or better from a particular sender if there was a smtp flood? I now have a held queue of 10000 mails to non existing user due to incorrect smtp client connection which flooded the root user mails. In exim I would do smth like this:

exiqgrep -i -f root@localhost | xargs exim -Mrm

**Comment by teoxrr** [comment]
Hello, we've about 1000 messages held, nevere cleaned by the system.
How can we delete all at once?

"You can leave the messages in the system and they will be filtered out by the passage of time."
Seems not true
