### ISSUE TITLE
Postal OutBound Relay Not Working

### ISSUE THREAD

**Issue by brainiers** [postalhq/postal#470]
Hello We arrying to relay outbound emails from Postal to another server. The main reason is that with postal we cannot manage the VMTAs like we can with PowerMTA.  We have tried the code below:

smtp_relays:
  -
    hostname: othersmtp.yourdomain.com
    port: 25
    ssl_mode: Auto

We have tried to configure 10 SMTP relays but none is working. We have disabled username and password. The SMTP for POstal Emails is working perfectly.

HOw can we achieve this?

**Comment by Power-MTA** [comment]
🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1
