### ISSUE TITLE
"tlsv1 alert decode error" when sending to ping@tools.mxtoolbox.com

### ISSUE THREAD

**Issue by dsnopek** [postalhq/postal#479]
I've been trying to use the Email Deliverability testing tool at https://mxtoolbox.com/deliverability but when I try to send to ping@tools.mxtoolbox.com from Postal I get this error:

```
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert decode error
```

I tried setting more SSL versions in postal.yml like:

```
smtp_server:
  tls_enabled: true
  ssl_version:  [TLSv1, TLSv1_1, TLSv1_2, SSLv23]
```

That didn't help.

Googling around made reference to some SNI issues for that error, ie. not sending the hostname when doing TLS, but I'm not sure that really applies here. That said, I searched and found this issue https://github.com/atech/postal/pull/336 which seems like it might have been a change to send the hostname rather than IP, which seems like it would have maybe fixed this potential SNI issue?

Any ideas? Or is this just a problem with the mailservers on mxtoolbox.com? (The other tools there have been very helpful to me over the years - I'm not sure I've used this one before...)

**Comment by igerzog** [comment]
If I am not mistaken regarding to #387 you should use only one of these values: `TLSv1, TLSv1_1, TLSv1_2, SSLv3 or SSLv23`, and not a list of them. Try to set parameters in `smtp_server:` section like these:

`tls_enabled: true`
`ssl_version: TLSv1`
`tls_ciphers: TLSv1:!aNULL:!eNULL!SHA`

**Comment by dsnopek** [comment]
Does setting a single ssl_version limit what get's used? I'd like to support all versions if possible..

Anyway, I'll give those settings a try!

**Comment by dsnopek** [comment]
I tried those settings. No effect, got the same error :-/

**Comment by dsnopek** [comment]
@igerzog Are you able to send to ping@tools.mxtoolbox.com from your Postal instance?

**Comment by igerzog** [comment]
> @igerzog Are you able to send to ping@tools.mxtoolbox.com from your Postal instance?

Hm, I have got the same error while trying to send a message to `ping@tools.mxtoolbox.com`.
In my opinion there is a problem more like at `tools.mxtoolbox.com` but not at postal instance.

**Comment by willpower232** [comment]
> In my opinion there is a problem more like at `tools.mxtoolbox.com` but not at postal instance.

Yes this sounds like the problem here, mxtoolbox is the only system I've seen problems sending messages to. It might be worth @dsnopek contacting them to investigate.

In the meantime, https://www.mail-tester.com should be a suitable alternative.

**Comment by dsnopek** [comment]
Ok, I sent a message to the mxtoolbox folks! We'll see if they get back. :-) If it's just their tester that has issues and this isn't a problem with any real mail servers, that'd be great. That's what I'm really worried about here, that this is indicative of problem that could be encountered in the wild when sending real mail.

> In the meantime, https://www.mail-tester.com should be a suitable alternative.

Thanks for the suggestion!

**Comment by dsnopek** [comment]
I got this response from mxtoolbox:

> Good morning...The error that you are experiencing is due to the version of TLS that your ESP is using.
>
> It looks like they use TLSv1.  Are they able to send with TLSv1.2 or with just simple SMTP without TLS?
>
> We have not received any complaints until now, so testing the version of TLS would help in isolating your issue with the Email Deliverability tests.

I tried setting:

```
smtp_server:
  ssl_version: TLSv1_2
```

... restarting Postal and sending again. That didn't help :-(

I'm not super sure on the syntax for the `tls_ciphers` key so I didn't try changing that

**Comment by dsnopek** [comment]
Reading about Ruby's support for TLS 1.2 [here](https://stackoverflow.com/questions/11059059/is-it-possible-to-enable-tls-v1-2-in-ruby-if-so-how) leads me to believe that setting `ssl_version` sets a minimum version, and that so long as openssl on your system supports TLS 1.2, it'll use TLS 1.2 if the peer supports it.

I tested if my system's openssl supports TLS 1.2 by per [this article](https://serverfault.com/questions/638691/how-can-i-verify-if-tls-1-2-is-supported-on-a-remote-web-server-from-the-rhel-ce) and it appears that it does!

So... I'm not convinced by the theory that Postal is not using TLS 1.2.

**Comment by willpower232** [comment]
Curious indeed. Again, we've had no issues like this elsewhere.

You can use openssl from a command line like this to get some more information about your Postals TLS-ability
`openssl s_client -connect postal.yourserver.com:25 -starttls smtp`

I've highlighted some bits which are probably related.

![image](https://user-images.githubusercontent.com/1619102/35649843-2bebd9b0-06d2-11e8-9ba3-35f8b3ae2d4e.png)

I'd be surprised if any Postal server didn't support TLS 1.2 but whether thats getting through to the connection is a bit beyond me I am afraid...

**Comment by dsnopek** [comment]
I get a similar result with `openssl` connecting to my Postal server via SMTP - it says `Protocol  : TLSv1.2` as well.

Thanks, Everyone, for your help! Until I see another server give this error, I'm just going to write it off as a problem with mxtoolbox.

**Comment by tankerkiller125** [comment]
@willpower232 I ran that command and I'm getting TLSv1.2 as the protocol, but I'm completely missing the part after "New," (it just says none) and missing the Cipher. I'm using my custom certs and I have the config as such:

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencypt/live/domain.com/fullchain.pem
  tls_private_key_path: /etc/letsencypt/live/domain.com/privkey.pem
  ssl_version: TLSv1  
  tls_ciphers: TLSv1 
```

Any suggestions?
