### ISSUE TITLE
Regular expressions in the routing address

### ISSUE THREAD

**Issue by sperlic** [postalhq/postal#480]
Hi guys,

We have a situation where **domen.tld** is used for regular email messages and for transaction messages across the route **notifications-{INSTANCE_ID}@domain.tld**[1]. Is it possible to use a regular expression in the ruting address to route only the addresses that contain **notifications -.*@domain.tld**? Wildcard address ***@domain.tld** makes us a redirection loop when the transaction message is sent to regular user **user@domain.tld** back through the Postal.

[1] The server that performs the separation and routing (via Postfix) for the **domain.tld** is located on another machine in relation to Postal which currently has a wildcard route.

Let me know if you need more informations about this scenario. 

Thank you for the great product!

**Comment by willpower232** [comment]
I don't believe such a thing is currently possible, there is only the wildcard redirect *@domain.tld.

We don't really use routes so not sure exactly what changes are needed but I don't believe it would be complicated to add.

If you add that feature yourself, do send a pull request.

**Comment by Csardelacal** [comment]
I know this is a bit older thread. 

But I found out that this is actually possible in vanilla Postal and made a [blog post ](https://tumblr.magic3w.com/post/190439136743/postal-is-awesome-for-incoming-emails-wildcards) about it)

You may not be able to use `notifications-*@domain` but you can create a route for `notifications@domain` and then send emails to `notifications+id@domain` and it will work just fine. 

Postal respects the fact that the + symbol in email addresses is akin to the # character for URL fragments.
