### ISSUE TITLE
Sending domain without verifying

### ISSUE THREAD

**Issue by masihfathi** [postalhq/postal#484]
Hi,
Is it possible to send via any domain? like many ESP, you can send email without verify domain (but with a higher risk of spamming),
For example i verify example.com but want able send via example..@gmail.com

**Comment by willpower232** [comment]
If you are wanting to send via a gmail account you already own, you can probably just use the SMTP settings from them without involving Postal at all.

Alternatively, are the instructions in https://github.com/atech/postal/issues/277 not relevant for you?

**Comment by masihfathi** [comment]
I did not mean Gmail. In system like mailchimp, sendgrid ... Domain DNS verification is optional.
[ #277 
](https://github.com/atech/postal/issues/277)
In "SEND AS ANY ", The main domain must be verified and can send via any subdomain.

**Comment by masihfathi** [comment]
Got it,
We should register all domain in postal,  but when we active "SEND AS ANY", it's not necessary to verifying  DNS.
One of the nice features of post design
An interesting point in postal was Database architecture, None of the tables are not related, I easily change database with frontend script and register new domain ...
