### ISSUE TITLE
email failing to send to certain email addresses

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#489]
Hello 

we believe we have all of our DNS records setup based on the settings within Postal Mail under Domains. 
I'm trying to send emails to certain addresses which are failing. 

We first get a soft fail and then when we try and send it again, we get a hard fail.

Does anyone have any ideas why some emails fail to send.

Here is the error message we get.

450 4.1.8 <framzy@psrp.mailtest.justin.ca>: Sender address rejected: Domain not found
Time: 0.11s
Support Ref: JK0OQO8M

**Comment by djmuttart** [comment]
Hello, I checked my SPF record in Postal and my DNS and I have TXT record set as 

mailtest.justin.ca- v=spf1 a mx include:spf.mailtest.justin.ca ~all

when I run tests on https://www.mail-tester.com it says, You do not have a SPF record, please add the following one to your domain psrp.mailtest.justin.ca:

v=spf1 a mx ip4:192.167.125.134 ~all

Would this be causing the issue why some of my email addresses are not receiving my emails

**Comment by willpower232** [comment]
`Domain not found` means that the subdomain doesn't exist in a CNAME or A record form.

`psrp` suggests that the return path for the domain name you have set up is not present. Have a look here and note you will need several different types of record for your return path domain:
https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration

The Domains tab in your Postal should tell you if the return path is correct and ready.

**Comment by djmuttart** [comment]
willpower232.

Thank you for the response. When I set up Postal Mail I followed the instructions under the Domains tab to setup my DNS records. I didn't use the Domains & DNS - Configuration documentation as I didn't know it existed. 

Having said that, the information under the Domains Tab (which all show good for me) don't match what the records show in the Domains & DNS - Configuration documentation. Fox example, no where in the Domains & DNS - Configuration documentation does it show to setup a CNAME record, but under Domains Tab it says it there. Also, in the Domains & DNS - Configuration documentation, it says to create rp.mail.yourdomain.com.      IN    A     192.168.1.3 this is not specified under the Domains Tab.

I guess my question to you is, do I create the exact number of DNS records identified in the Domains & DNS - Configuration documentation exactly as they are listed? This would mean I would have 11 entries?

Also do I need to add the  IPv6 address stuff?

I currently only have 4 DNS records which I created based on the instructions on the Domains Tab

**Comment by djmuttart** [comment]
I ran the test again from mail-tester.com and here is what it showed for an issue. Under my Domain Tab, everything is green. I can send emails to some addresses and not others. I did run the test like you indicated above.

We check if the server you are sending from is authenticated
-1
[SPF] psrp.mailtest.justin.ca does not allow your server 192.167.125.134 to use vfyewr@psrp.mailtest.justin.ca
Sender Policy Framework (SPF) is an email validation system designed to prevent email spam by detecting email spoofing, a common vulnerability, by verifying sender IP addresses.
You do not have a SPF record, please add the following one to your domain psrp.mailtest.justin.ca:

v=spf1 a mx ip4:192.167.125.134 ~all
The Name Server handling the domain name psrp.mailtest.justin.ca is rp.mailtest.justin.ca.

Need guidance? View guides for each host.



Verification details:

dig +short TXT psrp.mailtest.justin.ca :
rp.mailtest.justin.ca.
dig +short TXT @rp.mailtest.justin.ca. psrp.mailtest.justin.ca :
spfquery --scope mfrom --id vfyewr@psrp.mailtest.justin.ca --ip 192.167.125.134 --helo-id mailtest.justin.ca :
none
psrp.mailtest.justin.ca: No applicable sender policy available
psrp.mailtest.justin.ca: No applicable sender policy available
Received-SPF: none (psrp.mailtest.justin.ca: No applicable sender policy available) receiver=ns303428.ip-94-23-206.eu; identity=mailfrom; envelope-from="vfyewr@psrp.mailtest.justin.ca"; helo=mailtest.justin.ca; client-ip=192.167.125.134

**Comment by willpower232** [comment]
Postal requires a number of records to function appropriately and these are set in `postal.yml`.

You may have set them but not actually created them? https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L84-L91

**Comment by djmuttart** [comment]
@willpower232

I will check my settings in postal.yml

Since everything is green under my Domains Tab, does this mean I likely have my DNS setup properly?

Are you suggesting I have some thing not configured properly in my postal.yml file based on the issue identify by mail-tester.com?

I feel like I'm just missing something very simple. I will post my DNS settings in postal.yml tomorrow when I can log into my server. 

Thanks for your replies.

**Comment by hivetechag** [comment]
@djmuttart I have the same issue, did you manage to fix it?
