### ISSUE TITLE
Remove Queued messages. 

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#494]
I have several emails which are listed under the link which says queued messages. Most of these are Hard Failed. 

How can i manually remove these. I know you can truncate the database table for the suppression list. Is there a way for the queued ones? 

Thanks.

**Comment by willpower232** [comment]
If they have hard failed they are already out of the queue surely?

**Comment by tchwpkgorg** [comment]
I also have a message in the queue which stays there for a couple of days already.

When I click on message details, it says:

```
Message is currently being processed.
No delivery attempts yet.
```

The recipient is not on suppression list.

**Comment by joltcan** [comment]
Do you use IP pools? When I disable those it started to worked again (I remove the old messages from the database and created new ones).
