### ISSUE TITLE
Slow down send rate

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#495]
Hello 

When i send my emails from postal it goes through our Baracuda system. When trying to send about 700 emails using 2 workers, Baracuda fails to let them go through and i get a 421 error saying to many messages in one session 

Baracuda has suggested we slow down our send rate from postal.   

Is this possible within postal. Can I drop the workers down to 1 to slow down the messages per session?

**Comment by willpower232** [comment]
Similar to https://github.com/atech/postal/issues/488, there aren't many options for slowing down messages other than queuing them in your own application.

Is your Baracuda set up as an SMTP relay?
