### ISSUE TITLE
Pending Mails

### ISSUE THREAD

**Issue by Manishjodhani** [postalhq/postal#498]
Is there any process by which we can resend the pending mails??

**Comment by willpower232** [comment]
Do you mean messages which have not been sent yet? If they aren't being sent at all, you may be interested in https://github.com/atech/postal/issues/287 otherwise if the message has been attempted to send, you should see a redeliver button on each message when you go into it.

**Comment by Manishjodhani** [comment]
i have check this #287 and my default value is NULL in the tables.
@willpower232 Call you tell how many worker should i use,if my server had 32GB RAM..?

**Comment by Manishjodhani** [comment]
@willpower232  can you tell me???

**Comment by willpower232** [comment]
Please read https://github.com/atech/postal/issues/290 with regards to increasing the number of workers on your system

**Comment by Manishjodhani** [comment]
I have check this #287 and my default value is NULL in the table.
you can check in the screenshot.

https://prnt.sc/ih9azj

Please check this and reply soon.

**Comment by willpower232** [comment]
Your default value may be null but the actual value currently used by some of the rows might not be null.

**Comment by Manishjodhani** [comment]
I can't understand what you are trying to say?
