### ISSUE TITLE
Sender don't recieve hard fail messages 

### ISSUE THREAD

**Issue by saire-lancelot** [postalhq/postal#502]
Is there any way, that bounce messages and hard fail notifications get back to the original sender?

**Comment by willpower232** [comment]
Please read https://github.com/atech/postal/wiki/Auto-Responders-&-Bounces but note your return path is probably psrp.yourdomain.com and they can only be sent via HTTP webhook endpoints

**Comment by saire-lancelot** [comment]
Ok thanks for your answer. Is #255 still open? In my opinion an smtp endpoint should work also.

**Comment by willpower232** [comment]
It looks to still be open but whether it will receive any work, I'm not sure.

**Comment by influenist** [comment]
In my opinion hardfails should be returned / notify to the sender, like any other platform would do.
