### ISSUE TITLE
users password digest

### ISSUE THREAD

**Issue by joaoreis81** [postalhq/postal#503]
How can I update a user password? the password_digest field, can I do it in a sql query?

Thanks in advance.

**Comment by willpower232** [comment]
The safest way would be to log in as the user to get to the settings and/or make use of the password reset feature.

**Comment by catphish** [comment]
I'm not sure exactly how you would manually create the necessary password digest. The safest way to do this (assuming you can't use the GUI) would be using the Rails console.
