### ISSUE TITLE
Certificate for some tracking domains weren't created automatically

### ISSUE THREAD

**Issue by pablomelo** [postalhq/postal#515]
After some head banging, I saw that the `log/lets_encrypt.log` showed the certificate for only a few tracking domains. I'm not sure the reason, but as a tip for other people who might have the same problem, I'm posting the solution here.

1. Open the console
`postal console`

2. Query for all the domains with empty certificates and run the `get` on each.
`irb(main):001:0> TrackCertificate.where(certificate: nil).map(&:get)`

3. Done.

**Comment by willpower232** [comment]
Thanks for the information, out of curiousity, how many tracking domains do you have?

**Comment by pablomelo** [comment]
@willpower232: 
12, for now - 3 TLDs X 4 "mail servers".

**Comment by willpower232** [comment]
I presume you registered with lets encrypt during the set up process and before adding the tracking domains.

Are you able to add another domain and watch the logs to see if Postal even makes an attempt?
