### ISSUE TITLE
can't receive email

### ISSUE THREAD

**Issue by hrmshandy** [postalhq/postal#516]
Hello,

I have a problem that is always bounced when receiving email.

Looking for your help. Thanks

![image](https://user-images.githubusercontent.com/8230690/36967667-ec7a2234-2092-11e8-8627-cbad51dba553.png)

![image](https://user-images.githubusercontent.com/8230690/36967084-55e5e6d8-2091-11e8-86ac-17bcc562db06.png)

![image](https://user-images.githubusercontent.com/8230690/36967695-01ad8e7a-2093-11e8-9eb0-8b156edb7c69.png)

**Comment by willpower232** [comment]
Looking at your DNS, it seems that you have the MX records for your main domain `quiq.biz` pointed to your Postal server which is leading to this confusion.

Postal can handle incoming mail but it is not intended as a traditional email server.

You can create a return path route to handle these messages, have a look at https://github.com/atech/postal/wiki/Auto-Responders-&-Bounces

**Comment by hrmshandy** [comment]
@willpower232 

I have created the return path route, but still fail
![image](https://user-images.githubusercontent.com/8230690/36970821-6f54ad38-209c-11e8-9862-8e704cfef5c3.png)
![image](https://user-images.githubusercontent.com/8230690/36971500-95494e70-209e-11e8-97ce-9f059d325ef5.png)

is the url http endpoint correct?

sorry, I'm just confused, the documentation is less clear to me

**Comment by willpower232** [comment]
A HTTP endpoint implies that you have an application capable of receiving this information on a separate URL or server. Please have a look at https://github.com/atech/postal/wiki/HTTP-Payloads

**Comment by hrmshandy** [comment]
ok, I understand now.

Thanks @willpower232

**Comment by ilearnbydoing** [comment]
Hi, @willpower232  I want to understand the incoming message feature of Postal.
suppose I have a sender domain name domainname.tld
now I wish to received email for user@domainname.tld though I have setup MX record which points to postal IP.

I also have created a route like user@domainname.tld and setup to hold it.

Now when I try to send a test email to user@domainname.tld from my gmail id and it is not receiving any email and also gmail getting fail to deliver the message to such recipient.

Whereas sending via the Postal inbuilt incoming message stimulate feature I able to receive the mail.  

So I want a clarity of how does incoming works?

thanks

**Comment by willpower232** [comment]
You should examine the SMTP server logs in /opt/postal/log to see if Postal had any problem.

If you can't figure it out, please open a new issue with the gmail error message and whatever log entries are useful.

**Comment by RahulVerma989** [comment]
> /opt/postal/log

Hi @willpower232 I am also facing the same issue and in my case there is no /opt/postal/log folder as well. @ilearnbydoing did you find any solution for this issue?

<img width="247" alt="Screenshot 2024-03-09 at 2 51 26 PM" src="https://github.com/postalserver/postal/assets/48805821/53e88dd0-95e8-4ead-aab9-07dead9afc5e">

**Comment by willpower232** [comment]
@RahulVerma989 this information is now very redundant and incorrect now that Postal is managed by docker and has a completely different logging process.

I think there are a few more recent discussions worth looking at but I can't find them right now however basically `postal logs smtp` for example would give you the logs from the SMTP server.
