### ISSUE TITLE
SMTP connection issue

### ISSUE THREAD

**Issue by khalidelmerrah** [postalhq/postal#519]
Hello postal team,
i'm trying to connect to postal smtp from a desktop application using the credentials created on the postal dashboard. but it won't connect.

> please log into say smtp account and check pop settings. Error occured = Unable to connect to remote server 

i'm stuck here i don't know what to do next and what to fix ..

**Comment by willpower232** [comment]
Postal has no POP (or IMAP) functionality. It is only a sender of emails.

Typically it is used to allow a website to send emails that can't already send emails through the platform it is hosted on.
