### ISSUE TITLE
Is it possible to start only SMTP and API?

### ISSUE THREAD

**Issue by vgladimir** [postalhq/postal#522]
I want to start only SMTP and API on One server and the Workers for sending emails on the another server. Is it possible to separate these processes?

**Comment by willpower232** [comment]
I do not believe this is possible but as Postal is clusterable, there would be nothing stopping you from running multiple servers if you shared a database and rabbitmq instance between them.

**Comment by vgladimir** [comment]
The server with workers are heavy and requires a lot of resources. Is it possible to start server without workers?

**Comment by willpower232** [comment]
Resources shouldn't be an issue if it is installed appropriately. Postal requires at least a couple of gigabytes of memory to run and should be on a server that isn't doing anything else.

**Comment by vgladimir** [comment]
If you send 1000 mails in minutes I think it will require a lot resources. And in this case it will be great to have light server on front and separate workers servers.
