### ISSUE TITLE
Getting "Message was not delivered successfully to SMTP server."

### ISSUE THREAD

**Issue by ankitsamarthya** [postalhq/postal#523]
Hi,

I have setup postal on my aws account. Web interface works fine. I am able to send email from it. But when I try `postal test-app-smtp some@email.com` or trying to invite a user its giving the following error.

Message was not delivered successfully to SMTP server.
Error: Errno::ECONNREFUSED (Connection refused - connect(2) for "127.0.0.1" port 2525)

  SMTP Host: 127.0.0.1
  SMTP Port: 2525
  SMTP Username: (system generated username)
  SMTP Password: (system generated password)

Please help.

**Comment by vgladimir** [comment]
Change port to 25. I don't know why, but SMTP don't turn on 2525 port.

**Comment by willpower232** [comment]
Port 2525 was part of the previous original configuration but Postal is capable of running on 25 now and does so by default. You can run on 2525 as well with some help from iptables.

If you see a reference to 2525, there is an issue open somewhere for updating the wiki.

**Comment by ankitsamarthya** [comment]
Changing port to 25 in postal.yml worked.
