### ISSUE TITLE
Can't connect to Postal after updating SSL Certificate

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#524]
Hello, 

I have a separate application which connects to Postal via API. We recently update the SSL certs on the Postal Server and since then, we are unable to connect our application to Postal. There doesn't seem to be any glaring issue showing up in Postal or even on our application side. It shows are key is active and Used 3 days ago, exactly the time when we updated the Postal SSL Certificate.

Anyone ever run into this problem? 

Thank you

**Comment by willpower232** [comment]
You'll have to use logging in your application to see what the problem is.

You could also try using https://ssllabs.com to make sure the server certificate is working properly.
