### ISSUE TITLE
Webhook Retry

### ISSUE THREAD

**Issue by TioLuiso** [postalhq/postal#527]
Hello

We are integrating our application with postal. And were interested specifically in using webhooks to be notified about bounces.

I was wondering what would happen if the application that hosts the webhook is down... What would postal do with the notification? Retry it? drop it?

Have looked for it in the documentation or in other issues, but haven't found it.

**Comment by willpower232** [comment]
A cursory look at the code suggests it is retried over the course of a set amount of minutes

https://github.com/atech/postal/blob/master/app/models/webhook_request.rb#L22
