### ISSUE TITLE
Failed to scan virus. 

### ISSUE THREAD

**Issue by wackoen** [postalhq/postal#528]
I already telnet scan virus. Clamav scan work fine.
I enable postal clamav. Postal seem to run find because not error produce.
The problem when test sending virus, all virus can still send to my email. Postal seem not blocking this virus.
FYI, I test send virus using this site.
http://www.aleph-tec.com/eicar/index.php
How do I check whether the scanning occur or not.

Hope to get help on this thank you.

**Comment by willpower232** [comment]
Have you definitely switched to pure clamav as per https://github.com/atech/postal/issues/507?

**Comment by wackoen** [comment]
Yes I do.. I compile from source..

**Comment by willpower232** [comment]
Is the clamav service running?
