### ISSUE TITLE
Register new key with letsencrypt

### ISSUE THREAD

**Issue by nenominal** [postalhq/postal#529]
Hi,

I've registred to postal Letsencrypt with postal register-lets-encrypt and I only got the folloing in the logs:

[4066] [2018-03-14T12:44:09.143] INFO -- : Successfully registered private key with address xxx@xxxx
[4066] [2018-03-14T12:44:09.404] INFO -- : Terms have been accepted

It's been more than 1 day and there is no logging on the subject

Is there a way to re-register or regenerate the keys and register again?

**Comment by willpower232** [comment]
You have probably registered okay but maybe Postal is struggling picking up a new domain.

Have you tried adding a new (or re-adding an existing) tracking domain?

**Comment by willpower232** [comment]
See also https://github.com/atech/postal/issues/515

**Comment by nenominal** [comment]
Hi,

I've added another domain till yesterday but with any luck for all of them. Currently I have 3 domains with tracking status _"SSL setup in progress"_ 

As for you #515 

> irb(main):002:0> TrackCertificate.where(certificate: nil).map(&:get)
> => [false, false, false]

As the documentation regarding letsencrypt it's kinda scarce, could you please point me to the correct way of registering domains using the plugin?

Is there a way to cancel the current registration and do it again? Or maybe regenerate the keys again?

Or any other solution whatsoever by all means.

**Comment by nenominal** [comment]
I've run the job **RenewTrackCertificatesJob** using postal console and I got:

> 
> [18935] [2018-03-15T14:36:11.843] INFO -- : Attempting verification of click.postal.x.x
> [18935] [2018-03-15T14:36:24.159] INFO -- : Status was not valid (was: invalid)
> [18935] [2018-03-15T14:36:24.514] INFO -- : Attempting verification of click.postal.x.x
> [18935] [2018-03-15T14:36:36.825] INFO -- : Status was not valid (was: invalid)
> [18935] [2018-03-15T14:36:37.171] INFO -- : Attempting verification of click.y.y
> [18935] [2018-03-15T14:36:49.379] INFO -- : Status was not valid (was: invalid)
> [18935] [2018-03-15T14:42:01.369] INFO -- : Attempting verification of click.postal.z.z
> [18935] [2018-03-15T14:42:13.714] INFO -- : Status was not valid (was: invalid)
> [18935] [2018-03-15T14:42:14.107] INFO -- : Attempting verification of click.x.x
> [18935] [2018-03-15T14:42:26.459] INFO -- : Status was not valid (was: invalid)
>

**Comment by willpower232** [comment]
Are all of the domains you're using pointing at your postal server? If you try to access them you should just see "Hello."

**Comment by arendvw** [comment]
I've encountered the same problems. The root cause was that letsencrypt was looking for the ipv6 address, which was not well bound.

fast_server:
  enabled: true
  bind_address:
    - 6.7.8.9
    - "xxx:yyyy:zzz:ffff::2"

After checking that all ipv6 issues were resolved:

Running the command on the console: (`postal console`)
> TrackCertificate.where(certificate: nil).map(&:get)

Fixed the problem for me.

**Comment by nenominal** [comment]
@willpower232 : Yes, all domains are pointing to postal service, I get a Hello for every one of them.
@arendvw : I'm using only IPV4, the DNS is configured to IPV4 only. Does IPV6 is mandatory to DNS as well or I just need to configure an IPV6 IP on postal server?

**Comment by arendvw** [comment]
No, it's not mandatory. But if you add it, make sure it's working, ortherwise, make sure you don't have an AAAA record for the tracking domain

**Comment by nenominal** [comment]
The configuration for both DNS and fast_server is with an IPv4 IP. I've added another domain since I open the issue and none of them got the SSL till now.

**Comment by willpower232** [comment]
According to the library documentation, it should be possible to get the error message out of Lets Encrypt.

After this line:
https://github.com/atech/postal/blob/3ba0a72779c984e1539423cc71214408779f6f03/app/models/track_certificate.rb#L57

Add this line and restart Postal:
```ruby
 logger.info "Response from Lets Encrypt; Error Type: #{challenge.http01.error.type}. Error Detail: #{challenge.http01.error.detail}. )"
```

I can't test it right now but according to [this](https://github.com/unixcharles/acme-client) something like that should work.

Hopefully you should get some more detailed information in your logs about what the problem is.

**Comment by arendvw** [comment]
It's how I debugged this:
By changing line 57 of `app/models/track_certificate.rb`
to:
`logger.info "Status was not valid (was: #{challenge.verify_status}) #{self.domain} #{challenge.error}"`

This wil report errors to the `lets_encrypt.log` file

**Comment by nenominal** [comment]
Ok, I've enabled logging but I also did an update and reconfigure a bit the firewall, so, I'm not pretty sure which one solved my issue but all the SSL certs have been issued :-)

```
# Logfile created on 2018-04-03 19:45:00 +0300 by logger.rb/56438
^[[34m[worker.1:10233]^[[0m [2018-04-03T19:45:00.794] INFO -- : Attempting verification of click.postal.xx.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T19:45:02.844] INFO -- : Getting certificate for click.postal.xx.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T19:45:03.693] INFO -- : Certificate issued (expires on 2018-07-02 15:45:03 UTC, will renew after 2018-06-07 15:45:03 UTC)
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:01.086] INFO -- : Attempting verification of click.postal.yy.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:03.369] INFO -- : Getting certificate for click.postal.yy.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:04.572] INFO -- : Certificate issued (expires on 2018-07-02 16:00:03 UTC, will renew after 2018-06-04 16:00:03 UTC)
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:05.450] INFO -- : Attempting verification of click.postal.zz.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:07.649] INFO -- : Getting certificate for click.postal.zz.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:08.379] INFO -- : Certificate issued (expires on 2018-07-02 16:00:07 UTC, will renew after 2018-06-02 16:00:07 UTC)
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:08.750] INFO -- : Attempting verification of click.postal.vv.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:10.869] INFO -- : Getting certificate for click.postal.vv.ro
^[[34m[worker.1:10233]^[[0m [2018-04-03T20:00:12.044] INFO -- : Certificate issued (expires on 2018-07-02 16:00:11 UTC, will renew after 2018-06-11 16:00:11 UTC)
```
