### ISSUE TITLE
Spam checks, is it working?

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#532]
I'm seeing this message:

This message doesn't have any spam checks.
This likely means we haven't scanned this message to determine its likelyhood of being spam. It may take a few seconds to appear after a new message is received.

Does it mean, that the spam checks are not working?

**Comment by saire-lancelot** [comment]
Check /var/log/mail.log. There you can see, if spamd is checkig the mails.

**Comment by saire-lancelot** [comment]
Is spamassassin installed and runnig and the  postal configuration correct?:

`systemctl status spamassassin.service
`
 
check /opt/postal/config/postal.yml:
```
spamd:
enabled: true
host: 127.0.0.1
port: 783
```

**Comment by navinp** [comment]
Spamassassin installed.

After that looked into the file /postal.yml

But it didn't have anything about spamd, so I added it.

After that restarted the postal using **postal restart**

I send a test mail and got this error:

```
March 22, 2018 00:00
ERROR
An internal error occurred while sending this message. This message will be retried automatically. This this persists, contact support for assistance.

NoMethodError: undefined method `enabled?' for nil:NilClass

Support Ref: J-WI9NLW2XDE
```

**Comment by navinp** [comment]
Hello,

I removed the spamd-part from the /postal.yml file, restarted using **postal restart** and now I see the spam checks are indeed working.

I don't know what is a good practice, but I have put the Outbound spam threshold to 5.0

**Comment by saire-lancelot** [comment]
Best Case is to test it with a real spam mail. I use 3.0

**Comment by navinp** [comment]
I think this happened after the server was rebooted :/ 

root@domain:~# systemctl status spamassassin.service
● spamassassin.service - Perl-based spam filter using text analysis
   Loaded: loaded (/lib/systemd/system/spamassassin.service; disabled; vendor pr
   Active: **inactive** (dead)

**Comment by saire-lancelot** [comment]
Can you manually start the service? If you want to start the service after each reboot, this will do the job:
`systemctl enable spamassassin.service`

**Comment by navinp** [comment]
I have this Postal installed on a fresh new box, Spam checks are not working... I have Spamassassin enabled though and active (running).

It's just not scanning the emails :/

Is it something I missed on this fresh new box?

**Comment by willpower232** [comment]
When you say its not scanning the emails, what exactly are you seeing?

**Comment by willpower232** [comment]
Are you referring to a message that you have sent from Postal or one that has been received by Postal?

By default, messages sent from Postal are not checked for spam because its intended they are sourced from yourself and not likely to be spam at all.
