### ISSUE TITLE
can't send emails [soft fail] 

### ISSUE THREAD

**Issue by khalidelmerrah** [postalhq/postal#541]
hello team
i can't send emails even that port 25 is open, and the routing settings are set the smtp credentials are set and i set them up on `postal.yml` i'm running out of ideas what to do to fix this ? where can i find log to understand the situation .. all i get is this 

![image](https://user-images.githubusercontent.com/24738104/37875779-a46bf68a-303b-11e8-8e83-b51b3a5a85ad.png)

**Comment by khalidelmerrah** [comment]
i just bought a digital ocean vps and checked that port 25 is open. what else could be wrong ?

**Comment by willpower232** [comment]
Might be worth restarting the server to make sure everything is running smoothly. Do you have any issues emailing other domains?

**Comment by khalidelmerrah** [comment]
i restarted the server and got a new problem, it use to say it's soft fail, now it won't even try, just stay on pending,
this is the changes i made to postal.yml and postal.defaults.yml are they correct ? 

on the postal.yml file
`smtp:
  host: postal.nasdaily.us
  port: 25
  username: nasdaily/nasdailyserver #got this from the smtp credentials that was generated
  password: hJ0seph2zKCOxTNSUlrQ**** # password dones't contain stars it's just to hide it
  from_name: NasDaily
  from_address: mailling@nasdaily.us`

same thing on the postal.defaults.yml file
`smtp:
  host: postal.nasdaily.us
  port: 25
  username: nasdaily/nasdailyserver
  password: hJ0seph2zKCOxTNSUlrQ***
  from_name: NasDaily
  from_address: mailing@nasdaily.us`

should it be like this or what ?

**Comment by willpower232** [comment]
The credentials in postal.yml are only for when Postal wants to send emails (e,g. password reset). You should not change postal.defaults.yml as it can be overwritten by future updates.

Make sure that all of Postal is running with `postal status`.

**Comment by khalidelmerrah** [comment]
hey will,

the postal status shows everything running 
 => web.1            Running
 => worker.2        Running
=> cron.2           Running
 => smtp.1           Running
 => requeuer.2       Running

but i still can't send a test email it pop a message says : message was queued successfully.

**Comment by willpower232** [comment]
If the message was queued successfully, does the UI tell you what happened to the message?

**Comment by khalidelmerrah** [comment]
it just keeps pending for few seconds, then make it soft fail.. i just found out that the fu*** digital ocean doesn't allow sending emails and they are blocking outgoing requests through port 25.. can you refer a good vps company .. 
thanks Will

**Comment by willpower232** [comment]
It appears Digital Ocean block SMTP on new accounts unless you open a ticket with them and explain your need for it.

I'd say most reputable VPS companies would have some kind of SMTP policy so you'd have to double check with them what was available. We use AWS but we had to contact them to arrange Reverse DNS.

**Comment by khalidelmerrah** [comment]
i tried AWS but they didn't accept to get my account out of the sandbox, i will be using postal for promotional emails and transnational emails and will send them to only who subscribed through our website ..  i requested a 1000 emails a day increase but they just didn't accept it .. what you think i did wrong ?

**Comment by aliyenidede** [comment]
"v=spf1 ip4:XX.XX.XX.XX ip6:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX ~all"

try to use spf like this

**Comment by Gopi9655** [comment]
> "v=spf1 ip4:XX.XX.XX.XX ip6:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX ~all"
> 
> try to use spf like this

and the host name please
