### ISSUE TITLE
fail to send emails to paypal

### ISSUE THREAD

**Issue by theraw** [postalhq/postal#543]
Hello, 
i just tried to contact paypal.com and all emails are failing before i was thinking paypal was not accepting my emails and i was blaming them for this. but i was seeing logs and
![image](https://user-images.githubusercontent.com/32969774/37877403-196beb7e-305b-11e8-97d6-faab1066a234.png)

![image](https://user-images.githubusercontent.com/32969774/37877405-231a030e-305b-11e8-8895-f128946e3bcb.png)
`Domain of sender address <n64jyz@psrp.dopehosting.net> does not exist`

Is something wrong with my setup or is something wrong with postal? can someone help please?

I can say that i'm able to receive emails from them with no problems just i cannot send emails to them..

**Comment by theraw** [comment]
i also tried to send it from api same problem..

**Comment by willpower232** [comment]
I can't see anything out of place with your set up.

You could try these steps and changing the sender header to raw@dopehosting.net to see if it makes a difference: https://github.com/atech/postal/issues/277#issuecomment-316034829

**Comment by theraw** [comment]
![image](https://user-images.githubusercontent.com/32969774/37877585-adef7fc0-305d-11e8-96c3-f27e959e2abd.png)

![image](https://user-images.githubusercontent.com/32969774/37877607-01f73ba8-305e-11e8-92d1-942d00721e1a.png)

![image](https://user-images.githubusercontent.com/32969774/37877608-0e0b0438-305e-11e8-9119-0f648c1268dd.png)

maybe i should try to restart postal once or i'm doing it wrong?

**Comment by willpower232** [comment]
Its clearly changed because the sender address changed but Postal has still added psrp to it so that hasn't really changed the situation.

For whatever reason, Paypals email server is unable to verify the Postal server exists so rejects the email. If might be worth testing other systems if possible with your current set up to see if you get similar rejections.

If you have a contact at Paypal, you might be able to find out more about the verification process. I can see that you're using an xyz domain so maybe they're a bit confused at Paypals end.

**Comment by theraw** [comment]
i have alot of time using Postal i never got rejected with this reason, Paypal is first one, However sometimes when i do changes to postal it takes some time to update so i will try again later.. If this doesn't change i will try to explain this to them may they will explain more why verification fails..

i have try to contact them from another mail server and gmail directly everything was ok so i think is all about sender verification.

and yes my Postal setup/DNS is created with a different domain which is used just for mail purpose. and other domains has been just added to "Domains".

**Comment by theraw** [comment]
![image](https://user-images.githubusercontent.com/32969774/37879529-a84416a4-307a-11e8-8d52-e8d2dfa9fe7e.png)
tried alot but cannot set right `sender`

**Comment by willpower232** [comment]
Unless you can get some technical information from Paypal, or someone from atech chips in, I don't think theres much we can do for now.

**Comment by theraw** [comment]
if i edit a file from Postal `app/` files what should i do for it to take effect, Or just restart Postal?

I mean isn't possible to set `mailfrom` header manually on Postal code? even if it will be changed again by Postal after i do it isn't problem as i will not contact paypal every day i need it just for some minutes. I've try to use my gmail acc to contact them but they ignore them and say to contact from the email which i have on my account which is raw@d...

I'm talking with them on twitter.com as of now but i think they from twitter don't have too much informations as are not helping too much.

**Comment by willpower232** [comment]
If you're modified the ruby files, you will have to restart postal for the changes to take affect.

**Comment by theraw** [comment]
okay thanks i will do some tests by myself and let you know. however you can close this if you're not interested in hearing more about this.

Thank you for trying to help and i'm sorry for disturbing you!

**Comment by theraw** [comment]
Tried. No luck..

**Comment by theraw** [comment]
[this part did the magic](https://github.com/atech/postal/blob/master/lib/postal/smtp_sender.rb#L115-L122)

![image](https://user-images.githubusercontent.com/32969774/38286477-e128ddae-37c5-11e8-9f70-c82261955ad6.png)

**Comment by willpower232** [comment]
Have you tried lowercase `s` on your sender header (presuming you're still using the above code?)

**Comment by theraw** [comment]
you mean setting Sender with lowercase 'sender' ?
yes. sender, Sender SENDER mail_from MAIL_FROM Mail_From etc. i have try alot..

however as much as i can understand this piece of code doesn't even tries to "catch" headers or mail_from it will just set domain return path for "smtp.mailfrom" 
```
        if message.bounce == 1
          mail_from = ""
        elsif message.domain.return_path_status == 'OK'
          mail_from = "#{message.server.token}@#{message.domain.return_path_domain}"
        else
          mail_from = "#{message.server.token}@#{Postal.config.dns.return_path}"
        end
```
maybe i'm wrong because i don't understand very well this lang..

some days ago i also tried https://github.com/atech/postal-php
problem was the same! cannot set right sender
