### ISSUE TITLE
1 in 500 emails fail. 

### ISSUE THREAD

**Issue by PureMSP** [postalhq/postal#556]
Hi.
One in maybe 500 emails (from the same server) randomly fail. This is in the logs. Any idea what it means?
```
[smtp.1:24380] [2018-04-02T19:06:43.431] DEBUG -- : [QZXWRG]    Connection opened from xx.xx.xx.xx
[smtp.1:24380] [2018-04-02T19:06:43.431] DEBUG -- : [QZXWRG]    Client identified as xx.xx.xx.xx
[smtp.1:24380] [2018-04-02T19:06:43.431] DEBUG -- : [QZXWRG] => 502 Invalid/unsupported command
[smtp.1:24380] [2018-04-02T19:06:43.432] DEBUG -- : [QZXWRG] => 502 Invalid/unsupported command
[smtp.1:24380] [2018-04-02T19:06:43.432] DEBUG -- : [QZXWRG] => 502 Invalid/unsupported command
[smtp.1:24380] [2018-04-02T19:06:43.432] ERROR -- : [QZXWRG] An error occurred while processing data from a client.
[smtp.1:24380] [2018-04-02T19:06:43.432] ERROR -- : [QZXWRG] Errno::EPIPE: Broken pipe
```

**Comment by willpower232** [comment]
Are you able to see what server you are sending to when that failure occurs?

**Comment by PureMSP** [comment]
It's inbound to the POSTAL server.
The logs are from the SMTP SERVER log.

**Comment by willpower232** [comment]
You could add a line after the error to see what the unsupported command is:
https://github.com/atech/postal/blob/ce68d9eacdd4b9351d7601da7bc0397b48a67247/lib/postal/smtp_server/client.rb#L82

Something like:
```ruby
log "Invalid/unsupported command was: #{data}"
```

**Comment by PureMSP** [comment]
I’ve added the line, and will see what it shows.
Thanks! 😊

**Comment by PureMSP** [comment]
Just a question, is the SMTP service allowing more than 1 connection at a time?

**Comment by adamcooke** [comment]
It's quite common for invalid commands to be thrown at SMTP servers. @willpower232's suggestion to log the invalid command will hopefully help you see what's the actual command is.

**Comment by catphish** [comment]
> Just a question, is the SMTP service allowing more than 1 connection at a time?

Yes, it allows many independent connections.
