### ISSUE TITLE
Sending to postal via SMTP or API is slow

### ISSUE THREAD

**Issue by russjfreeman** [postalhq/postal#558]
New linux box (fairly powerful), new install of postal.

API takes, on average 1.5s to send an email. SMTP is very similar. It's painfully slow, too slow for production use :-(

Is there some tweak somewhere I need to do to speed this up?

(newbie to linux and postal)

**Comment by willpower232** [comment]
How much memory does your server have? Have you configured more than two workers?

**Comment by russjfreeman** [comment]
The server is a quad core with 12GB ram and 1GB network.

There are 10 workers.

**Comment by willpower232** [comment]
That should be sufficient. Is the server doing things other than Postal-related things? Do you get any other network issues when updating or transferring files?

**Comment by russjfreeman** [comment]
FYI: av and spam is disabled too too.

It's the only thing installed on there and it's all it does.

No other issues at all. Hosting company and our experience has confirmed that.

We're going to try postfix, mainly as a test, but we really like postal.

**Comment by adamcooke** [comment]
Sounds like a database performance issue. We'd recommend tuning your MySQL database to extract maximum throughput. This certainly isn't normal behaviour and sends through the API on our installation are very quick.

**Comment by russjfreeman** [comment]
@adamcooke I'll take a look.

**Comment by russjfreeman** [comment]
The DB and rabbit is default, as per default installation.
