### ISSUE TITLE
offer donation search Debian 8 installation guide

### ISSUE THREAD

**Issue by JoergKaufmann** [postalhq/postal#563]
I'm not in Linux. I am looking for a complete beginner 8 minimal installation guide for beginners, I offer a small bitcoin donation.
Installation instructions from the beginning

**Comment by arendvw** [comment]
I've recently installed on debian 9 if this is a possiblity for you, this was rather painless. 

It's main difference is that the prerequisites are different from the normal installation guide prerequisites:
https://github.com/atech/postal/wiki/Prerequisites

This whole page can be replaced by:
```
sudo apt remove exim4 exim4-base exim4-config exim4-daemon-light
sudo apt install mariadb-server libmariadbclient-dev rabbitmq-server nodejs ruby mysql-server git rabbitmq-server nodejs ruby mysql-server git libcap2-bin ruby2.3 nginx
```

**Comment by JoergKaufmann** [comment]
on my server I can install a maximum of Debian 8. Also no Ubuntu. Thank you I will test your instructions

**Comment by arendvw** [comment]
Probably these instructions will not work for debian 8.

Possibly you can install debian 8, [upgrade to debian 9](https://linuxconfig.org/how-to-upgrade-debian-8-jessie-to-debian-9-stretch) and then install these packages?

**Comment by JoergKaufmann** [comment]
I did an update from debian 8 to 9. your commands entered. and then I wanted to continue with the normal installation.mysql -u root -p -h 127.0.0.1 there is an error: Command not forund
--
Sicher gesendet mit Tutanota. Hol dir jetzt deine verschlüsselte Mailbox!
https://tutanota.com <https://tutanota.com>

11. Apr 2018 09:42 von notifications@github.com <mailto:notifications@github.com>:

**Comment by JoergKaufmann** [comment]
mysql_secure_server  
command not found

and this command  mysql -u root -p -h 127.0.0.1
a password is requested, but which one do I enter? my root password is not working!

**Comment by willpower232** [comment]
You need to `apt install mysql-client` to be able to connect to mysql from the command line.

The secure command is `mysql_secure_installation` which should already be available to you if the server is installed.

**Comment by JoergKaufmann** [comment]
root@debian:~# mysql_secure_server
-bash: mysql_secure_server: command not found
 
and 

I always get an error though it is the password
root@debian:~# mysql -u root -p -h 127.0.0.1
Enter password:
ERROR 1698 (28000): Access denied for user 'root'@'localhost'

**Comment by willpower232** [comment]
mysql_secure_server IS NOT the command. Use `mysql_secure_installation` instead.

Try `mysql -u root` or `mysql -u root -p`

**Comment by JoergKaufmann** [comment]
Hello willpower232

Can you help me please? I also tried the mysql_secure_installation, nothing works. Could you give me an installation description for debian 8 minimal? Would that pay too! Although I have updated the server on Debian 9, but maybe something goes wrong. because my hoster only offers Debian 8.

**Comment by oasis1234** [comment]
Have a look to https://github.com/atech/postal/issues/614

**Comment by gavintfn** [comment]
check your /etc/hosts file... make sure you have the line:
127.0.0.1 localhost

if thats not it...

 sudo /etc/init.d/mysql stop
 sudo /usr/sbin/mysqld --skip-grant-tables --skip-networking &
mysql -u root
CREATE USER 'root'@'%' IDENTIFIED BY 'somepassword';
GRANT ALL PRIVILEGES on *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
exit
sudo /etc/init.d/mysql stop
sudo /etc/init.d/mysql start
