### ISSUE TITLE
250 error - Giveup

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#570]
if i am sending email i got the below error

Expected response code 250 but got code "530", with message "530 From/Sender name is not valid " Log data: ++ Starting Swift_SmtpTransport << 220 mail.mydomainname.in ESMTP Postal/VJ9FDP >> EHLO apps.mydomainname.in << 250-My capabilities are 250 AUTH CRAM-MD5 PLAIN LOGIN >> AUTH CRAM-MD5 << 334 PGRmYjVmNDgyMWE5ZDU4ZjAxZjdmQG1haWwubWFpbGxlYWRlcnMuaW4+ >> bWFpbGxlYWRlci9tYWlsbGVhZGVyIDY5NmU5NDJkMDlkY2Q5ODIyZjkzMjg4ZTZmOWYxNjU5 << 235 Granted for maille/maille ++ Swift_SmtpTransport started >> MAIL FROM:<info@mydomainname.in> << 250 OK >> RCPT TO:<myemailid@gmail.com> << 250 OK >> DATA << 354 Go ahead >> . << 530 From/Sender name is not valid !! Expected response code 250 but got code "530", with message "530 From/Sender name is not valid " (code: 530)

**Comment by willpower232** [comment]
'From/Sender name is not valid' implies that your domain may not be verified for the credential used so you should also check that `mydomainname.in` is part of your `mailleader/mailleader` server.

P.S. you should remove the base64 strings above and change your credential as the credential is in there.

**Comment by sahilsunesara** [comment]
base64 strings from which credential ? you mean from postal? if yes there where?

**Comment by willpower232** [comment]
The opening comment of your issue contains base64 strings in your error which evaluate to the credential you're using for your Postal. For security, you should change that credential and remove the strings from the error.

**Comment by sahilsunesara** [comment]
my domain is verified but i got 250 error. 

For more information: from where i am sending email that system work properly with other SMTP but if i use poster SMTP i got 250 error and showing give up

What will be the solution?

**Comment by willpower232** [comment]
250 isn't an error code, can you send a screenshot of what you are seeing?

**Comment by sahilsunesara** [comment]
i already send complete error msg..please check above msg

i got same error msg

**Comment by willpower232** [comment]
Then make sure that the domain is in the same organisation that has the credential.

**Comment by sahilsunesara** [comment]
Yes, it's a same domain organisation.

**Comment by willpower232** [comment]
Then the only other thing that might be wrong is if you have entered the wrong password. If you've definitely entered the right details then you've missed something somewhere that we've already covered.
