### ISSUE TITLE
Is there any clear way to have multiple app servers?

### ISSUE THREAD

**Issue by reshadman** [postalhq/postal#573]
Thanks for your great clean work here. Is it possible to scale the app servers with a single database server? here is the scenario:

 - Multiple app servers each of the have multiple IP addresses attached to them (their own IP Pool).
 - Single MySQL database
 - Single RabbitMQ 
 - Putting a loadbalancer in front of the web interface (for open and click tracking)
 - Putting a loadbalancer in front of the SMTP server or routing in the client application itself.

**Comment by masihfathi** [comment]
See this topic:
[https://github.com/atech/postal/issues/41](url)
But if you just need multiple ips, you can use IP Pools

**Comment by willpower232** [comment]
This is also confirmed by https://github.com/atech/postal/issues/334#issuecomment-326765678

If each IP Pool was actually one server, it would be good to confirm that Postal can handle such a "physical" separation and each server only send emails it was supposed to.

**Comment by rakshith-ravi** [comment]
@catphish Do we have any update on this?

Let's say I have a common MySQL and RabbitMQ server, and connect multiple postal instances to the same server, would that be enough? Or is there anything else that I need to add to the setup to retain the same data across both servers?

**Comment by catphish** [comment]
This should work fine. There is no documented installation process, but if you install Postal on 2 servers and point them to a common MySQL an Rabbit server, it should work fine.

* You can either loadbalance SMTP, or just send emails to one server in the cluster and and they will all send.
* Servers should be able to share an IP pool, as long as the each have at least one IP from that pool.

**Comment by rafaelsisweb** [comment]
> This is also confirmed by [#334 (comment)](https://github.com/atech/postal/issues/334#issuecomment-326765678)
> 
> If each IP Pool was actually one server, it would be good to confirm that Postal can handle such a "physical" separation and each server only send emails it was supposed to.

Any additional information about that? Using IP Pools with smtp server running on distributed servers.
If it works, how to setup additional smtp servers?
