### ISSUE TITLE
Mail worked on first attempt then stopped working.

### ISSUE THREAD

**Issue by danteissaias** [postalhq/postal#576]
When sending a message... I receive this error:

```
temporary SMTP delivery error when sending to ===========(xx.xxx.xx)

451 4.7.1 Try again later

Time: 0.09s

Support Ref: WJWUQLDI
```
Any known fixes?

**Comment by arendvw** [comment]
This is probably [greylisting](https://en.wikipedia.org/wiki/Greylisting).
Just wait a bit, and it will be delivered. 

Also "Stopped working" is a horrible, horrible problem description. You'll yield better results with placing an issue if you actually describe the issue, such as Soft fail error on mail delivery.
