### ISSUE TITLE
Email Spamming

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#577]
Hi

Why my all email goes to spam?
I have test email using mail-tester site and i got 8.5 score but still my email goes to spam only
Why? what will be the reason ?

Thanks

**Comment by willpower232** [comment]
It will probably be that whoever you're sending email to doesn't completely trust your Postal server yet.

Can you share the details of your mail-tester score?

**Comment by sahilsunesara** [comment]
https://www.mail-tester.com/web-6cue1

**Comment by Mayeu** [comment]
Your IP seems to be in a blacklist, almost no chance to be clear out from spam:
```
-1.644 | RCVD_IN_BRBL_LASTEXT | Your sending server IP is listed in the Barracuda blacklist142.44.161.65 listed in bb.barracudacentral.org
```

You have to check with the list how to delist yourself.

**Comment by sahilsunesara** [comment]
i haven't send more then 100 email till yet n it's show black list... surprised

Given bb.barracudacentral.org website is not working

**Comment by longhorninmd** [comment]
You have to warm up your IP which is sending a small amount of messages at first and then progressively increasing this total.  It could take several weeks before remote mail systems start trusting mail from your Postal server.  For example, Gmail will usually block postal traffic the first few days you try sending to it.
