### ISSUE TITLE
I can't receive emails

### ISSUE THREAD

**Issue by emresaracoglu** [postalhq/postal#579]
Hello

I can send e-mail but I can not receive emails. 

1.
![](https://user-images.githubusercontent.com/297968/39529851-5265d2f8-4e30-11e8-8fea-ad60300c46d3.png)
2.
![screenshot-2018-5-l](https://user-images.githubusercontent.com/297968/39529994-a4ee750c-4e30-11e8-800c-016dc0e7fc6d.png)
3.
![screenshot-2018-5-2 edit -](https://user-images.githubusercontent.com/297968/39530066-ce166c32-4e30-11e8-8d1f-92ace9926701.png)

Where can the problem be?
Thank you.

**Comment by willpower232** [comment]
I'm confused about your set up, are you trying to forward emails from Postal into itself?

**Comment by emresaracoglu** [comment]
Hi @willpower232 ,

No, I thought it was true.

postal.domainONE.com
bilgilendirme@domainTWO.com

**Comment by emresaracoglu** [comment]
Hi @willpower232 ,

No, I thought it was true. How should the correct?

**Comment by willpower232** [comment]
> No, I thought it was true.

I'm not sure what you mean?

**Comment by emresaracoglu** [comment]
I can send e-mails but I can't receiving e-mails. I have asked you the reason for this and for this I added screenshots. Do you have an idea on this?

**Comment by willpower232** [comment]
I'm still confused about how you have things set up but I would direct you to the log files in /opt/postal/log particularly the smtp_server.log.

If the server is receiving emails but Postal is not working with them properly, there should be log entries.

If there are no relevant log entries then it may be your DNS records are correct.
