### ISSUE TITLE
"Universal" unsubscribe link

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#580]
Hello,

With the whole gdpr thing coming our way, I was thinking if there was a way to add an unsubscribe link to all outgoing emails. 

I have customers and I can't rely on my customers that they will take care of this. 

Is there a way already for this? Or are there plans for this?

**Comment by willpower232** [comment]
Postal does not maintain any lists of contacts, that should be handled by your application or software that uses Postal.

If you wanted to add this functionality to Postal, you would have to fork it and add a completely separate blocklist which doesn't get automatically cleaned.

As for other aspects of GDPR, you can already control how long emails are kept by Postal so you can set this for a very short time if you deem it necessary.

**Comment by navinp** [comment]
I suppose if there were an option like this, unsubscribers would be added to the suppression list along with the details

**Comment by willpower232** [comment]
The suppression list is automatically cleared after a certain amount of time so you would have to implement a completely separate list that was permanent.

You would probably find a much more effective solution by building this into whatever uses Postal.
