### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by hadifarnoud** [postalhq/postal#587]
setting up Postal is very confusing. there are several 'domains' setup. I did not understand what is for what. 

I have the same issue. this is kinda confusing for me. so, let me explain how I understood it:

I install Postal on a domain, that would be my primary SMTP domain for use in apps. in this case the server domain is `mail.kamva-files.com` whilst postal is accessible from `postal.kamva-files.com`
[this is my config file ](https://gist.github.com/hadifarnoud/0aa07100b5f2f4c51503390a31e75501)

there are a few places you can add domains. there is one in `Organization -> Domains` and one in `Mail Server -> Domains`

1. I want to use this server in `camva.ir` app. where should I add `camva.ir` as domain?
2. What is the difference between Mail Server domains and Organization domains?

**Comment by hadifarnoud** [comment]
for example, there is no mention of `mx.mail.yourdomain.com` in DNS config documentation. what should that be?

**Comment by hadifarnoud** [comment]
I'm still not sure what is the difference of `Mail Server` domain and what should be added in  `dns` section of config yml file.

should I add that domain in Mail Server? 
I still get the following error when doing `postal test-app-smtp hadi@camva.ir` (I added camva.ir in org domains and set DNS as instructed)

Message was not delivered successfully to SMTP server.
```
Error: Errno::ECONNREFUSED (Connection refused - connect(2) for "127.0.0.1" port 2525)

  SMTP Host: 127.0.0.1
  SMTP Port: 2525
  SMTP Username: ======
  SMTP Password: ======
```

**Comment by willpower232** [comment]
The `dns:` section should contain a list of records which all point to the main servers IP address (see https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration) and then those any domain that uses your Postal server will use some or all of those records.

Once you have added `camva.ir` as a domain in your Postal server, you will need to make a credential for it and use that in the `smtp:` section you have above.

Unless you have any iptables or port forwarding involved, the port you have used under `smtp:` should be the same as the one listed under `smtp_server:`

**Comment by gitaayush** [comment]
I am Still confused on Organizations -> Domains and Mail server -> Domains
