### ISSUE TITLE
Monitoring email traffic

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#591]
Hi,

I don't think it has this feature, but to those here, that has a number of organizations or planning to add more:

How do you view your overall **email traffic** that is being sent via your Postal? 

At the moment I have no other way than to browse through the organizations manually, to see if they are active or not and how many emails they had sent/received and if they any problems at all etc.

Any suggestions or ideas are welcome.

**Comment by willpower232** [comment]
Monitoring MySQL activity is a way of seeing how the overall system is performing, if you notice a large spike then a lot of messages are being sent at that time.

Also related https://github.com/atech/postal/issues/545 and https://github.com/atech/postal/issues/453

**Comment by alonle** [comment]
I recommend using redash https://redash.io/
It will help you do some Mysql queries on the data and see it as a dashboard.
For example, to see all emails sent today by status:
`select status as Status, count(status) as number
FROM messages
WHERE TIMESTAMP > UNIX_TIMESTAMP(CURDATE())
group by status;`
At least until postal will have a reporting feature

**Comment by navinp** [comment]
Thanks very much, will look into it.

**Comment by navinp** [comment]
@alonle Maybe via ssh do a query to see recent active accounts? I wonder if there are any options via ssh to figure out which customer is causing the spike.

**Comment by willpower232** [comment]
Your only real option is to check the database, that is all Postal could do anyway.

If you need to establish an SSH connection to connect to the MySQL instance, you might want to have a look at this https://discuss.redash.io/t/connect-to-mysql-postgres-over-ssh-tunnel/57
