### ISSUE TITLE
Not Sending Emails with Medium Attachment Size

### ISSUE THREAD

**Issue by marcotuna** [postalhq/postal#594]
Hello, I am trying to send an email with two attachments, one with 400 kb and the other with 8.7 MB.
The server is not sending the email because is throwing an error: "Mysql2::Error: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size us                          ing innodb_log_file_size."
As far as the error says it's because the size and I can or might fix it by increasing innodb_log_file_size. What if I do not want to log it at all? Is there any way I can disable logging?

![ss 2018-05-30 at 12 14 52](https://user-images.githubusercontent.com/6924105/40717272-9fe039a4-6403-11e8-922c-188340e2e3ba.png)

**Comment by willpower232** [comment]
Can you tell us the current value of `innodb_log_file_size`?

If you aren't sure where to look, you can run this query `SHOW VARIABLES LIKE 'innodb_log_file_size'`

**Comment by marcotuna** [comment]
Hi, here it is:
`MariaDB [(none)]> SHOW VARIABLES LIKE 'innodb_log_file_size';
+----------------------+----------+
| Variable_name        | Value    |
+----------------------+----------+
| innodb_log_file_size | 50331648 |
+----------------------+----------+
1 row in set (0.00 sec)
`

**Comment by willpower232** [comment]
The log file in question is a core part of how MySQL operates so you'll have to at least double the value.

You will need to stop your database server cleanly and update the configuration. It would also be worth stopping Postal during this process.

Have a read of this https://dev.mysql.com/doc/refman/5.6/en/innodb-data-log-reconfiguration.html, be careful and good luck!

**Comment by marcotuna** [comment]
Thanks, it worked. I increased from 50 MB to 256 MB. Now I can send the email.
Do you have any recommended hardware configuration for a postal server?

**Comment by willpower232** [comment]
Not specifically, the most important component is memory. 8GB is recommended but you may be able to get by with less.

When it comes to performance, configuration is everything. Have a read of https://github.com/atech/postal/issues/324 and https://github.com/atech/postal/issues/290

**Comment by marcotuna** [comment]
When I try to visualize the email through the Postal Web Panel (Plain Text, HTML and Attachments) it responds with 502 Gateway Error but if I force page refresh it loads correctly. Can't I just disable the email body not to be stored?

**Comment by marcotuna** [comment]
I upgraded from 2 GB to 4 GB. I only use to send a few emails, is not for bulk email sending. I use it as a relay, I don't need it to store messages.
The thing is, if I navigate to Plain Text, HTML and Attachments from a smaller email I don't see any relevant RAM increase/decrease, however, if I do the same thing on a bigger email (~10 MB) I see those issues.
Restarting the service: "systemctl restart postal" brings back the memory

**Comment by willpower232** [comment]
If you're literally only needing a relay, there are other software packages available that will do this task better, e.g. Postfix.

Postals primary purpose is sending emails it receives from applications over an API.

**Comment by influenist** [comment]
It seems I'm running into the same issue. A have tons of mails which do not even attempt to been delivered... 

Used the install for Ubuntu. Where can I find info on logging? It's a nice project yet misses some logical build. Like log paths, configuration paths etc. Its like a black box which sends en receives mails.

**Comment by influenist** [comment]
<img width="151" alt="screen shot 2018-07-12 at 16 07 42" src="https://user-images.githubusercontent.com/22964559/42639118-8e93812a-85ef-11e8-8498-b9d64f592841.png">

**Comment by willpower232** [comment]
@influenist please have a look at `postal status` and the files in `/opt/postal/log` to see what the problem might be. If you are unable to figure it out, please open a new issue with any relevant information from those places.

**Comment by nisanth074** [comment]
I hit this issue today. I've leaving a comment here in case it helps other Postal users.

I increased the value of `innodb_log_file_size` to `512 MB` in `/etc/mysql/my.cnf` and restarted MySQL
```
systemctl restart mysql
```
so Postal can store and deliver larger emails.

From my web searches, it seems like the only con of increasing the value of `innodb_log_file_size` is that MySQL / MariaDB will require more time to recover in case of a server crash. This is okay for us.
