### ISSUE TITLE
Open tracking not happening

### ISSUE THREAD

**Issue by vscool19** [postalhq/postal#596]
I have already read about Open & Click tracking in Wiki. I have setup a tracking domain and enabled a open tracking option so that it should add 1px image in email body as mentioned. But after sending a mail, when I checked there is no open count and no pixel image present in email body. I have also setup a fast server. 
Can you help me.. if something I missed?

**Comment by willpower232** [comment]
If you visit the click tracking address in your browser, you should see a white screen with the word hello to confirm that is activated properly.

Also did you send a HTML email?

**Comment by vscool19** [comment]
@willpower232 yes I am sending HTML email. I only want open tracking not a click tracking.

**Comment by willpower232** [comment]
They use the same bits of Postal, you won't be able to separate them but you can disable click tracking for individual links or individual emails as per the wiki page.

**Comment by vscool19** [comment]
@willpower232 I dint get you properly. but If I am disabling the click tracking, my open tracking also not working. It is necessary that both should be enabled.

**Comment by willpower232** [comment]
Yes thats correct

**Comment by vscool19** [comment]
@willpower232  then why they provide separate enable/disable option for open & click tracking. How open tracking is dependent to click tracking because open tracking works on pixel image setting and click tracking on tracking url.
