### ISSUE TITLE
Is there any way to delete organization?

### ISSUE THREAD

**Issue by ilearnbydoing** [postalhq/postal#598]
Hi,
I cant see any option which allows to delete organization to be deleted, is there any way to delete created organization?
thanks

**Comment by navinp** [comment]
Log in, go to the organization, check the navigation, it says Mail Servers, Domains ...etc ... **Delete Organization**

**Comment by willpower232** [comment]
You can only delete an organisation if you are the owner of it (i.e. you/your user created it).

I don't believe theres an option to change the owner at this time.
