### ISSUE TITLE
Deleting Held Messages

### ISSUE THREAD

**Issue by gacott** [postalhq/postal#599]
Saw a couple of posts that mentioned forcing held messages back into the queue but was not clear on how to delete all held messages.

**Comment by willpower232** [comment]
A held message has two buttons, release and cancel.

Release will queue it normally as if it was never held and cancel will clear the hold but not add it to the queue.

Unfortunately, there isn't a cancel or release all function.

**Comment by gacott** [comment]
Thanks, @willpower232. Is there a way cancel all help messaged by cli then? I have 10s of thousands I need to clear out of there.

**Comment by willpower232** [comment]
Unfortunately there isn't an official way of doing so.

Having a look at https://github.com/atech/postal/blob/master/app/jobs/expire_held_messages_job.rb, if you wanted to clear a whole load of messages, you could change the `hold_expiry` values in the messages table to a lower one so the system does it itself.

**Comment by gacott** [comment]
Thanks, so if I just leave them alone will they clear themselves then? Without sending?

**Comment by willpower232** [comment]
That should be the case, yes.

**Comment by avdhoot** [comment]
Will change in  `hold_expiry` will resend the message or delete it.  I will want to delete messages which are in a held state.  @willpower232

**Comment by willpower232** [comment]
it will do neither of those things, it will only stop marking the message as held.

if the postal server has the retention settings enabled, as it is by default, then the messages will eventually be purged by Postal which might be worth waiting for if there are many that you want gone.

**Comment by ruchit47** [comment]
I was frequently running into this issue. I could delete the old/held messages with following commands in  "postal console"
```
server = Organization.find_by_permalink('YOURORG').servers.find_by_permalink('YOURORGPERMALINK')
server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.delete() }
```
