### ISSUE TITLE
Postal API - IP Pools

### ISSUE THREAD

**Issue by saschaarthur** [postalhq/postal#601]
Hey,

Looks like the postal send API (https://atech.github.io/postal-api/controllers/send/message.html) is not considering the IP-Pools and using always the same ip, could this be?

**Comment by willpower232** [comment]
If you send a message from inside Postal, does it go via the IP Pool?

**Comment by saschaarthur** [comment]
yes it does

2018-06-06 14:05 GMT+02:00 Will Power <notifications@github.com>:

**Comment by gacott** [comment]
I'm having an issue like this as well. Originally I had one IP pool assigned. Removed that and assigned a new IP pool. It's still using the original IP pool.

**Comment by saschaarthur** [comment]
why just closed? is it solved?

**Comment by willpower232** [comment]
I can't replicate this and no one else has reported it
