### ISSUE TITLE
clodflare + docker + nginx

### ISSUE THREAD

**Issue by akudelka** [postalhq/postal#604]
Hi! we have a problems with recieving mail.
http://joxi.ru/1A5KV9etnD91Ym
outgoing messages work fine, but recieve doesn't.

We use cloudflare like dns hosting
and running postal in docker container
`web:
  host: mail.rocketdata.wiki
  protocol: http

fast_server:
  
  enabled: false
  bind_address:

general:
 
  use_ip_pools: false

logging:
  stdout: false
  max_log_file_size: 20
  max_log_files: 10

main_db:
 
  host: mysql
  username: root
  password: changeme
  database: postal

message_db:
  
  host: mysql
  username: root
  password: changeme
  prefix: postal

rabbitmq:
  
  host: rabbitmq
  username: postal
  password: changeme
  vhost: /postal

dns:
  
  mx_records:
    - mx.mail.rocketdata.wiki
  smtp_server_hostname: mail.rocketdata.wiki
  spf_include: spf.mail.rocketdata.wiki
  return_path: rp.mail.rocketdata.wiki
  route_domain: routes.mail.rocketdata.wiki
  track_domain: track.mail.rocketdata.wiki
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

smtp_server:
  proxy_protocol: false
  log_connect: true
  evented: true
  ports:
    - 25

smtp_relays:
  -
    hostname:
    port: 25
    ssl_mode: Auto

smtp:
  host: 127.0.0.1
  port: 25
  username:
  password:
  from_name: Postal
  from_address: postal@rocketdata.wiki

rails:
 
  secret_key: ************************
web_server:
  bind_address: 0.0.0.0
`

**Comment by akudelka** [comment]
Reporting-MTA: dns; mxback17j.mail.yandex.net
X-Yandex-Queue-ID: 46805813D4
X-Yandex-Sender: rfc822; a@rocketdata.io
Arrival-Date: Fri, 22 Jun 2018 10:01:51 +0300 (MSK)

Final-Recipient: rfc822; test@rocketdata.wiki
Original-Recipient: rfc822;test@rocketdata.wiki
Action: failed
Status: 5.1.1
Remote-MTA: dns; 127.0.0.1
Diagnostic-Code: smtp; 554 5.1.1 Unknown user; BN0fonOJ 166070236259288914 740

**Comment by akudelka** [comment]
postal test-app-smtp test@rocketdata.wiki  
Message has been sent successfully.

**Comment by akudelka** [comment]
https://www.mail-tester.com/web-bg7x8

**Comment by willpower232** [comment]
Can you show us the output of `postal status` and `netstat -lnp`?

**Comment by akudelka** [comment]
postal status
`/opt/postal/bin/postal status                            
Procodile Version   1.0.19
Application Root    /opt/postal
Supervisor PID      36
Started             2018-06-22 08:40:50 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      08:40        pid:40       respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      08:40        pid:42       respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      08:40        pid:44       respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      08:40        pid:46       respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      08:40        pid:49       respawns:0      port:-        tag:-`

**Comment by akudelka** [comment]
`netstat -lnp
(No info could be read for "-p": geteuid()=1001 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::8052                 :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::8023                 :::*                    LISTEN      -               
tcp6       0      0 :::15672                :::*                    LISTEN      -               
tcp6       0      0 :::25                   :::*                    LISTEN      -               
tcp6       0      0 :::9050                 :::*                    LISTEN      -               
tcp6       0      0 :::8090                 :::*                    LISTEN      -               
tcp6       0      0 :::8123                 :::*                    LISTEN      -               
tcp6       0      0 :::9051                 :::*                    LISTEN      -               
tcp6       0      0 :::4444                 :::*                    LISTEN      -               
tcp6       0      0 :::2525                 :::*                    LISTEN      -               
tcp6       0      0 :::5566                 :::*                    LISTEN      -               
tcp6       0      0 :::9150                 :::*                    LISTEN      -               
tcp6       0      0 :::9151                 :::*                    LISTEN      -               
tcp6       0      0 :::18050                :::*                    LISTEN      -               
tcp6       0      0 :::8066                 :::*                    LISTEN      -               
tcp6       0      0 :::5442                 :::*                    LISTEN      -               
tcp6       0      0 :::9090                 :::*                    LISTEN      -               
tcp6       0      0 :::3331                 :::*                    LISTEN      -               
tcp6       0      0 :::8036                 :::*                    LISTEN      -               
tcp6       0      0 :::3333                 :::*                    LISTEN      -               
tcp6       0      0 :::9093                 :::*                    LISTEN      -               
tcp6       0      0 :::5672                 :::*                    LISTEN      -               
tcp6       0      0 :::5000                 :::*                    LISTEN      -               
tcp6       0      0 :::2377                 :::*                    LISTEN      -               
tcp6       0      0 :::2090                 :::*                    LISTEN      -               
tcp6       0      0 :::7946                 :::*                    LISTEN      -               
tcp6       0      0 :::6380                 :::*                    LISTEN      -               
tcp6       0      0 :::9100                 :::*                    LISTEN      -               
tcp6       0      0 :::2190                 :::*                    LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::6800                 :::*                    LISTEN      -               
tcp6       0      0 :::82                   :::*                    LISTEN      -               
tcp6       0      0 :::8050                 :::*                    LISTEN      -               
tcp6       0      0 :::3090                 :::*                    LISTEN      -               
tcp6       0      0 :::27027                :::*                    LISTEN      -               
udp        0      0 0.0.0.0:4789            0.0.0.0:*                           -               
udp6       0      0 :::7946                 :::*                                -               
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     223280336 -                   /run/user/0/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     24903    -                   /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     25012    -                   /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     24897    -                   /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     25009    -                   /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     25010    -                   /var/run/docker.sock
unix  2      [ ACC ]     STREAM     LISTENING     25011    -                   /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     24904    -                   /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     25013    -                   /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     24905    -                   /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     25014    -                   /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     24920    -                   /run/systemd/fsck.progress
unix  2      [ ACC ]     STREAM     LISTENING     24931    -                   /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     23690    -                   /var/run/docker/libcontainerd/docker-containerd.sock
unix  2      [ ACC ]     STREAM     LISTENING     17046    -                   /run/docker/libnetwork/123da87034270e4c635af9db4b2cdfaaae8fbd0205702af6dbd8188d8527fb73.sock
unix  2      [ ACC ]     STREAM     LISTENING     16946    -                   @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     35942    -                   /var/run/docker/swarm/control.sock
`

**Comment by willpower232** [comment]
Looks like everythings running properly so its probably firewall or DNS record related.

**Comment by akudelka** [comment]
thi is a problem: 
mx_records:
- mx.mail.rocketdata.wiki

need to be:
mx_records:
 - mail.rocketdata.wiki

**Comment by akudelka** [comment]
another problem:
not sending email from mail.yandex but work fine with gmail

**Comment by akudelka** [comment]
http://joxi.ru/D2PzvBRtpkdL8r

i dont understand what happening. I think all my dns config is ok, but from yandex recieve do not work

**Comment by akudelka** [comment]
550-5.7.1 [195.2.252.217] The IP you're using to send mail is not authorized to 550-5.7.1 send email directly to our servers. Please use the SMTP relay at your 550-5.7.1 service provider instead. Learn more at 550 5.7.1 https://support.google.com/mail/?p=NotAuthorizedError a63-v6si2991739lfe.256 - gsmtp

Time: 0.54s

Support Ref: AAEVYILN

problem: i can receive mail from google but has error from yandex
i can send message to yandex but has error when send message to google


I need help))))

**Comment by willpower232** [comment]
Your IP address is still listed on blacklists, you will most likely need to resolve this.

![image](https://user-images.githubusercontent.com/1619102/42209857-a5cff4a8-7ea7-11e8-8187-d5f56e1854d4.png)
