### ISSUE TITLE
postal is slow accepting relayed emails

### ISSUE THREAD

**Issue by javiervegas** [postalhq/postal#606]
I have postal running on a 4 CPU, 8 Gb Ram server configured with "unlimited" sent email rate. The server receives emails relayed via SMTP from another server running postfix, and then postal sends them to the final destinations. The problem I am seeing is that postal is slow receiving emails from postfix, so the emails end up queued for a long time in the postfix queue before being accepted into postal, while the postal queue is pretty much empty because postal sends emails at the same rate it accepts them. The rate I am seeing is about 360emails/minute, which means it takes about 3 hours to send 60K emails. The postal queue typically has also round 300 emails. I have verified that the relaying server running postfix is not bounded by cpu, memory, disk or network, so the bottleneck seems to be the rate at which postal is accepting the mail to be sent. Is there any way I can speed that up? Looking through the configuration parameters, I found parameters that could help sending emails, but I didn't find anything that seems relevant to accepting relayed email.

Thanks!

**Comment by javiervegas** [comment]
In case it makes any difference, I forgot to mention that postal is using 5 IPs, postal receives relayed emails on the 5 IPs, and each email is delivered from the same IP it is received

**Comment by willpower232** [comment]
Have a look at https://github.com/atech/postal/issues/290 and https://github.com/atech/postal/issues/324
