### ISSUE TITLE
would it be possible to disable domain checking?

### ISSUE THREAD

**Issue by rafaelmarrichi** [postalhq/postal#607]
(google translate)
Hello, I recently started using atech / postal as an email server for mautic.
I'm going through a difficulty where the postcard gives Hard Fail or soft fail to domains of some clients where I need to be sent the email.
Would you have any option to unseat this domain check and fire the shot anyway?

**Comment by willpower232** [comment]
If Postal is marking the messages as Soft Fail or Hard Fail then it is highly unlikely that the message will be delivered to the recipient. You should be able to see why it failed in the UI.

**Comment by rafaelmarrichi** [comment]
There would be the error message giving on the postcard. The domain to which I sent the email was aurock.com.br

550 - Verification failed for <jlrwlm@psrp.tw3digital.com.br> 550 - The mail server could not deliver the email to jlrwlm@psrp.tw3digital.com.br. The account or domain may not exist, they may be blacklisted, or you may lose the appropriate DNS entries. 550 sender verification failed

Time: 30.58s

Support Ref: AUMMHDIK

**Comment by willpower232** [comment]
Looking at your DNS records, it appears you haven't set up mx.mkttw3.com.br to point at a server.
