### ISSUE TITLE
Same IP in Multiple IP pool

### ISSUE THREAD

**Issue by rsgehlot** [postalhq/postal#610]
Hey there,

Do we have any possibility to add one Ip into multiple Pools? This is required to test some IP warm-up theory. 

Regards,
Rahul

**Comment by willpower232** [comment]
I don't believe there is anything stopping you from doing this but I might be wrong.

**Comment by rsgehlot** [comment]
It gives an error, "ipv4 already has been taken"

![image](https://user-images.githubusercontent.com/20169861/42266722-d86cba70-7f94-11e8-90df-e27f17983dd9.png)

**Comment by willpower232** [comment]
Well that makes me wrong then.

**Comment by rsgehlot** [comment]
Hope, we can see possibilities of enabling this.
