### ISSUE TITLE
Multiple IP pools in single server to be used together

### ISSUE THREAD

**Issue by rsgehlot** [postalhq/postal#611]
I know we can assign multiple IP pools to a server. However, would like to know if we have the option to use both the pools together to share email volume.

**Comment by willpower232** [comment]
If you've assigned multiple IP pools to one server then I would believe that it is already sharing the volume.

**Comment by rsgehlot** [comment]
I don't think so, If multiple pools are assigned, it gives the option for the user to choose one at a time.

![image](https://user-images.githubusercontent.com/20169861/42267070-affad530-7f95-11e8-9c44-ad96235ab0de.png)

**Comment by rsgehlot** [comment]
In server setting, only one pool can be selected at once

**Comment by willpower232** [comment]
Oh I thought you said you had already done it in the server. I guess it can't be done then.
