### ISSUE TITLE
Email sending speed per minute configuration

### ISSUE THREAD

**Issue by rsgehlot** [postalhq/postal#612]
Hi -
Can we setup hourly limit to per minute?

Regards,
Rahul

**Comment by willpower232** [comment]
This is not currently a feature

**Comment by rsgehlot** [comment]
Can this be considered for upcoming releases?
It would really help Email admin to prevent IP reputations.

**Comment by saporus** [comment]
Hi,

If you are using Mailwizz Email Marketing App. This could be done efficiently.

Regards.
