### ISSUE TITLE
Error No SPF record exists for this domain

### ISSUE THREAD

**Issue by mypostal** [postalhq/postal#617]
Installed postal in amazon EC2 instance. Getting No SPF record exists for this domain when i try to register the Domain through postal UI.

Attached the postal.yml file and my records in DNS are as below

Type	Name	Value	TTL	Actions
A	@	xxxxxx	1 Hour	Edit
A	postal	xxxxxx	1 Hour	Edit
A	rp.postal	xxxxxx	1 Hour	Edit
A	track.postal	xxxxxx	1 Hour	Edit
CNAME	psrp	rp.postal.xxxxxx.com	1 Hour	Edit
CNAME	psrp.postal	rp.postal.xxxxxx.com	1 Hour	Edit
CNAME	www	@	1 Hour	Edit
MX	@	postal.xxxxxx.com (Priority: 10)	1 Hour	Edit
MX	routes.postal	postal.xxxxxx.com (Priority: 10)	1 Hour	Edit
MX	rp.postal	postal.xxxxxx.com (Priority: 10)	1 Hour	Edit
TXT	@	v=spf1 a mx include:spf.postal.xxxxxx.com ~all	1 Hour	Edit
TXT	postal	v=spf1 a mx include:spf.postal.xxxxxx.com ~all	1 Hour	Edit
TXT	postal-gj77yz._domainkey	v=DKIM1; t=s; h=sha256; p=;	1 Hour	Edit
TXT	postal-h6xsid._domainkey.mymail	v=DKIM1; t=s; h=sha256; p=;	1 Hour	Edit
TXT	rp.postal	v=spf1 a mx include:spf.postal.xxxxxx.com -all	1 Hour	Edit
TXT	spf.postal	v=spf1 ip4:xxxxxx ~all	1 Hour	Edit
CNAME	psrp.mail	rp.postal.xxxxxx.com	1 Hour

[postal.txt](https://github.com/atech/postal/files/2196237/postal.txt)

**Comment by mypostal** [comment]
May i know what i am missing. I added the A records cname and MX records still no luck..

**Comment by mypostal** [comment]
I believe the records are published. 
Below is the the output that i got when i ran 
**DIG TXT manibhasuri.com**
 <<>> DiG 9.10.3-P4-Ubuntu <<>> txt manibhasuri.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34165
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;manibhasuri.com.               IN      TXT

;; ANSWER SECTION:
manibhasuri.com.        13      IN      TXT     "v=spf1 mx a include:spf.postal.                                                                             manibhasuri.com ~all"

;; Query time: 0 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Tue Jul 17 00:29:06 UTC 2018
;; MSG SIZE  rcvd: 108




also ran ### **dig txt postal.manibhasuri.com** below is the output

ubuntu@ip-172-31-92-140:~$ ### **dig txt postal.manibhasuri.com**

; <<>> DiG 9.10.3-P4-Ubuntu <<>> txt postal.manibhasuri.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33466
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;postal.manibhasuri.com.                IN      TXT

;; ANSWER SECTION:
postal.manibhasuri.com. 60      IN      TXT     "v=spf1 mx a include:spf.postal.manibhasuri.com ~all"

;; Query time: 13 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Tue Jul 17 00:30:30 UTC 2018
;; MSG SIZE  rcvd: 115

**Comment by willpower232** [comment]
Are you trying to add `manibhasuri.com` to the UI?

Also it looks like the TXT record for `spf.postal.manibhasuri.com` doesn't exist. I'm not sure if thats whats causing the issue but it needs to be created/published.

**Comment by mypostal** [comment]
postal.manibhasuri.com is the UI of the postal and manibhasuri,com is the domain  so i have added A records for both of the domains.
Also added TXT record but no luck 
spf.postal  v=spf1 ip4:52.4.159.183 ~all

**Comment by navinp** [comment]
Hello,

Did you try by also adding ip6 and using ~instead of - (tilde instead of dash)

**Comment by willpower232** [comment]
The check will be for `spf.postal.manibhasuri.com` so it should be working.

Can you send us the screenshot of the checks page from the Postal UI where it isn't working?

**Comment by navinp** [comment]
https://toolbox.googleapps.com/apps/dig/#TXT/

**Comment by willpower232** [comment]
@mypostal Can you send us the screenshot of the checks page from the Postal UI where it isn't working?

**Comment by mypostal** [comment]
<img width="725" alt="error" src="https://user-images.githubusercontent.com/41273519/42826562-b8607208-89b2-11e8-99f3-4d571f46821b.PNG">
<img width="504" alt="error1" src="https://user-images.githubusercontent.com/41273519/42826563-b8755024-89b2-11e8-8bc4-354a3ee4a8c4.PNG">

**Comment by willpower232** [comment]
Based on the error message under DKIM, it looks like you're trying to add `manibhasuri` and not `manibhasuri.com`

**Comment by mypostal** [comment]
Thank you.. It worked after I changed to manibhasuri.com

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
