### ISSUE TITLE
DKIM Records could be same ??

### ISSUE THREAD

**Issue by Manishjodhani** [postalhq/postal#619]
Hi,

I'm using two different server and i want to install postal in both server.

And i want to know that it is possible to have same dkim records in both server withe same identifier?

I have changed the signing.key and put the same key in both server but there is problem in generated host name see in screenshots 

![image](https://user-images.githubusercontent.com/28861157/43032846-9263583a-8cdd-11e8-83b6-b9331232a244.png)

How would i generate the same host name for the all domain with postal.?

Thanks in Advance

**Comment by willpower232** [comment]
Why would you want the same records for both Postal servers? If you are trying to share the workload between two servers, you should share the exact same code along with database and queue.

**Comment by Manishjodhani** [comment]
Let me explain you If we create a new mail server in postal and then add domain it will create random host name like postal-xyz123.domainkey

But i need to use common host name like  postal-example.domainkey for all other domain we add in the postal.

For example :

Suppose we create mail server and add domain abc.com and records generated 
and there should be show this line "You need to add a new TXT record with the name **postal-example._domainkey** with the following content." 

And this should be same in all other mail server we create in postal.

**Comment by willpower232** [comment]
> But i need to use common host name like postal-example.domainkey for all other domain we add in the postal.

Do you have a limit on the records you can create or something?

In the domains table in the main database, you can see a field called `dkim_identifier_string` so you might be able to modify them to be the same there but I wouldn't be entirely sure of the outcome.

**Comment by Manishjodhani** [comment]
Hi,

I checked it.But the value is coming from this random_string in the dkim_identifier_string

https://github.com/atech/postal/blob/b396920d4761001c0cb87fc4695878d2ea18a801/app/models/domain.rb

So, can you check and tell me that from where the value is generating in the random_string.

**Comment by willpower232** [comment]
It uses a random string because they should be separate records. The random string is only generated when the database row is created.

If you want to use the same values, you will have to edit the database to copy the values from one installation of Postal to the other.
