### ISSUE TITLE
Slow Email Delivery

### ISSUE THREAD

**Issue by vscool19** [postalhq/postal#624]
@willpower232 @adamcooke  Using Postal since long time. Having configuration 8gb RAM and 4 CPU. Now after getting mail in pending state, it is taking around 3-4 minutes to process and sometime more. Earlier 6 workers are running and just now i have increased quantity and threads to 8.
Even that change, no change happened. still is going very slow.

**Comment by willpower232** [comment]
Are you using MySQL hosted on the same server? Are you running low on available memory whilst everything is running?

**Comment by vscool19** [comment]
@willpower232  Yes mysql hosted on same server and not running low on available memory. My worker configuration is quantity-8 and threads - 16. Main_db pool size is 20. Don't know why it is taking so much time to process a single mail.

**Comment by vscool19** [comment]
@willpower232 having around 100k  emails in queued message table. that can be the problem of slow sending rate?

**Comment by vscool19** [comment]
@willpower232 I have increased RAM to 16 GB and changes mysql settings with max_allowed_packet = 256M, innodb_flush_log_at_trx_commit = 2.
Now watching for imporvement.

**Comment by vscool19** [comment]
@willpower232  I have assigned 8 workers yesterday and that time all were running fine but now when i see the status out of 8, 4 workers are getting failed. 
what could be the reason of this?

**Comment by willpower232** [comment]
You'll have to look in the logs folders to see what is happening. You can also run the commands from `postal status` manually to get real time output.

**Comment by vscool19** [comment]
@willpower232 when I am doing postal status or postal stop it says 
Error: Procodile supervisor isn't running
But my application is running fine. Don't know how it is running?

**Comment by willpower232** [comment]
That is a bit odd, might be worth restarting the server as a whole to see if that brings you back in control.

**Comment by vscool19** [comment]
@willpower232 Yes sure. Thanks for your support
