### ISSUE TITLE
Issues configuring message limit

### ISSUE THREAD

**Issue by prasadasokan** [postalhq/postal#630]
We are using the latest postal version and adding the following isn't still helping us increase the message size limit to 25MB.

smtp_server:
max_message_size: 25

We are seeing the following error.

552 Message too large (maximum size 14MB)

I have restarted postal after making the change and it still isn't working.

**Comment by willpower232** [comment]
Can you share your `postal.yml`, redacted as much as you need?

**Comment by prasadasokan** [comment]
`web:
  # The host that the management interface will be available on
  host: mail.example.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: password
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: password
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: password
  vhost: /postal

smtp_server:
  max_message_size: 25
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mail.example.com
  smtp_server_hostname: mail.example.com
  spf_include: spf.mail.example.com
  return_path: rp.mail.example.com
  route_domain: routes.mail.example.com
  track_domain: track.mail.example.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: info@example.com

workers:
  quantity: 10
rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: {{secret_key}}`

**Comment by prasadasokan** [comment]
> web:
  # The host that the management interface will be available on
  host: mail.example.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: password
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: password
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: password
  vhost: /postal

smtp_server:
  max_message_size: 25
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mail.example.com
  smtp_server_hostname: mail.example.com
  spf_include: spf.mail.example.com
  return_path: rp.mail.example.com
  route_domain: routes.mail.example.com
  track_domain: track.mail.example.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: info@example.com

workers:
  quantity: 10
rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: {{secret_key}}

**Comment by prasadasokan** [comment]
[postal.txt](https://github.com/atech/postal/files/2279902/postal.txt)

**Comment by willpower232** [comment]
Is that definitely `/opt/postal/config/postal.yml`?

Also you could try putting newlines before `dns:` and `rails:` for consistency.

**Comment by prasadasokan** [comment]
Yes, that is the default postal.yml on which, I ended up changing the credentials etc, replaced it with dummy values and pasted it here. The only change apart from those credentials etc is the section to add the message size.

smtp_server:
  max_message_size: 25

Added new lines before dns: and rails: and restarted postal to ensure the yml is consistent.

**Comment by willpower232** [comment]
I mean `/opt/postal/config/postal.yml` instead of `/opt/postal/app/config/postal.example.yml` or something else in the `app` folder.

Have you tried restarting the whole server? There might be an issue when you're restarting that isn't letting the processes update.

**Comment by prasadasokan** [comment]
Yes, I did try restarting the server and nothing helps. How do we overcome this?

**Comment by willpower232** [comment]
I'm assuming you're on the latest Postal, you can check with `postal auto-upgrade`.

If you're running the latest Postal and you've definitely edited `/opt/postal/config/postal.yml` and Postal has definitely been restarted, the setting should apply.

**Comment by prasadasokan** [comment]
I did attempt the postal auto-upgrade and it did some git pull, and then restarted postal. Still the same issue. 

Attaching the upgrade logs. If the upgrade is run again, it is doing the same process again. I'm not sure how to prove you that I have restarted postal, and the config file provided is the one available on the server, and still the issue remains. 
[output.txt](https://github.com/atech/postal/files/2287486/output.txt)

**Comment by arashm** [comment]
I have the same problem. Changing the `max_message_size` doesn't actually work and I still get 14mb limit error.
I'm not sure how the `auto-upgrade` works but since https://postal.atech.media/packages/ hasn't been updated since 1st November 2017, neither on stable nor beta branch, I'm not sure if the update actually contains the latest code.

**Comment by willpower232** [comment]
That is a great spot @arashm and I've verified that is exactly the case with our development server.

@catphish are you able to make an up to date build?

In the meantime, you could make the changes to the ruby file and database yourself to enable you to keep using Postal.

**Comment by prasadasokan** [comment]
@willpower232 What does this mean with regards to the issue am facing? Any workaround or solution for us to go live with an increased message limit?

**Comment by willpower232** [comment]
> In the meantime, you could make the changes to the ruby file and database yourself to enable you to keep using Postal.

Updating the code is only one line of code to change but you will also need to change the type of database field to guarantee it can store your attachments.

**Comment by prasadasokan** [comment]
@willpower232 Can you help us with that change? I'm not sure where and what to change.

**Comment by willpower232** [comment]
You would have to make the changes from the pull request where you originally commented (https://github.com/atech/postal/pull/383).

If you make the changes outlined in the "Files Changed" tab and then restart Postal, you should find your message limit increased.

**Comment by prasadasokan** [comment]
@willpower232 We are able to resolve this issue now. Future upgrades will override this issue?

**Comment by willpower232** [comment]
Hopefully, the next update should include the changes but that relies on a new build being made.

If you run the update command and it resets your code, your current code copy should be automatically backed up in a new folder for you to restore from.

**Comment by navinp** [comment]
I hope it will include fbl

**Comment by arashm** [comment]
Is there any way I could help so the release happens faster? Is there any roadmap? Left issue or something?

**Comment by willpower232** [comment]
I believe it is a process internal to atech so requires their attention primarily

**Comment by vishnus** [comment]
@willpower232 just spotted this issue, few mails failed due to attachment size issue and can see that the code is not updated as mentioned in the pull request which is merged: https://github.com/atech/postal/pull/383 . We just did an auto-upgrade and can see that the smtp_server/client.rb file is not updated to match the change. @adamcooke and @catphish will this be updated in upcoming release?
