### ISSUE TITLE
Postal devs

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#631]
Hello,

Are there members in this group who are for hire?

I need a few enhancements on my Postal install, if anyone here is for hire, please leave a comment.

**Comment by hmnhf** [comment]
@navinp 

Hi, I'm the head of backend engineering at [Taskulu](https://taskulu.com), where we've used Ruby on Rails for developing the product and are also using Postal for sending our emails and have done a bit of customization on it.

Please feel free to contact me at: homon.hf@gmail.com
