### ISSUE TITLE
Enormous queue

### ISSUE THREAD

**Issue by influenist** [postalhq/postal#632]
Hi,

I have an enormous outgoing queue filled with bounce massage upon a bounce message.

Alos my log is empty despite checking both
/opt/postal/app/log
/opt/postal/log

So my questions are:

- How to actively tail the SMTP server via shell?
- How to purge specific from / to addresses from the message queue via shell?
- How to check the SMTP servers PID?

**Comment by influenist** [comment]
<img width="133" alt="screen shot 2018-08-10 at 20 26 26" src="https://user-images.githubusercontent.com/22964559/43974755-c8676cc4-9cdb-11e8-8774-faa50340a584.png">

**Comment by willpower232** [comment]
Can you share screenshots of why the messages failed?
