### ISSUE TITLE
Missing Date Header - Spam Assassin warning

### ISSUE THREAD

**Issue by prasadasokan** [postalhq/postal#638]
Emails sent to outlook.com are always landing in junk and hence used tools like mail-tester.com to check the score of the email. It's showing that a date header is missing.

https://wiki.apache.org/spamassassin/Rules/MISSING_DATE

Is there a way to add this header part of the outbound email?

**Comment by willpower232** [comment]
Thats very odd, the date header should be present by default.

How did you send an email from Postal to mail-tester.com?

**Comment by prasadasokan** [comment]
@willpower232  Looks like it is an issue with ansible. Emails sent through other email client is containing the date header. Sorry for the inconvenience.

**Comment by willpower232** [comment]
Can you share how you are sending messages with ansible and JavaMail? I would suspect the problem is with how Postal receives the messages.

**Comment by prasadasokan** [comment]
@willpower232 Using SMTP without TLS.

**Comment by willpower232** [comment]
I meant can you show the code or ansible playbook you use to send the messages?

**Comment by prasadasokan** [comment]
@willpower232 

[ansible.txt](https://github.com/atech/postal/files/2327520/ansible.txt)
[java.txt](https://github.com/atech/postal/files/2327521/java.txt)
With ansible, I understand we can use header and add date in RFC 2822 standard, but tried doing that and it isn't working as expected.
Add this to the yml.  

`headers: Date={{lookup('pipe', "date +'%a, %d %b %H:%M:%S %z'")}}`

**Comment by willpower232** [comment]
With ansible, the indenting is important so it would have to be something like

```yml
  ...
  tasks:
  - mail:
      ...
      headers:
      - Date={{lookup('pipe', "date +'%a, %d %b %H:%M:%S %z'")}}
```

I'm not sure where Java fits into your setup but I couldn't confirm whether a date header is set in that either.

I don't think Postal "re packages" the message so if it doesn't have a date header at its source, thats probably the problem.

**Comment by willpower232** [comment]
Mail tester will tell you what is keeping you from a perfect 10 score.

Have you also checked blacklists? https://mxtoolbox.com/blacklists.aspx

Other than that, Outlook is quite strict on spam so if there have been spam problems in the past, it might take a while for them to update.

**Comment by prasadasokan** [comment]
@willpower232 I tried sending an test email from the web dashboard to see if the date header is fine when sent this way. And the mail still ended up in the junk folder and the analyse header from Microsoft was showing invalid date. Not sure if that is the reason for mail ending up in junk though. But every other bulk sender, spam checks were negative. Mail tester gives a thumbs up except the date format. Please refer screenshot. Is there a workaround for the same? We are still not able to move Postal to production environment due to this.
![screenshot 2018-10-25 at 4 31 58 pm](https://user-images.githubusercontent.com/33906877/47496383-475ec800-d874-11e8-8a57-2e487ba50a9f.png)

**Comment by willpower232** [comment]
Which web dashboard did you use? I used Postals own UI and had this result:

![image](https://user-images.githubusercontent.com/1619102/47497830-3ea9ca00-d853-11e8-843f-0ce2f06b431d.png)

Do you have anything filtering your incoming messages that might be garbling them?

**Comment by prasadasokan** [comment]
@willpower232 I used the Postals own UI too. Is it something to do with the downloaded version? I remember another issue being related to the download URL pointing to some dev server earlier. 

No filters. Sending it to mail tester, outlook.com and seeing same result.

**Comment by willpower232** [comment]
Your screenshot implies your email was sent from outlook rather than from Postal which is confusing. Have you made any changes to your server code?

**Comment by prasadasokan** [comment]
@willpower232 No changes made except for the change in message limit as discussed in https://github.com/atech/postal/issues/630
I sent using the web ui to my personal outlook.com ID and pasted that source into the header. Hwew is the actual information from submitting host. (Scrubbed IP's and hostname)


BY2NAM05HT213.eop-nam05.prod.protection.outlook.com (2603:1096:203:3e::27); BY2NAM05FT031.eop-nam05.prod.protection.outlook.com (10.152.100.51); smtp.example.com(x.x.x.x); web-ui (host.example.com) [x.x.x.x])

**Comment by prasadasokan** [comment]
@willpower232 Any clue on why the date issue is seen in our installation alone even without any change in the code?

**Comment by willpower232** [comment]
I think something outside of Postal is messing with your emails so without you having someone you trust locally to know and examine everything in your email flow, theres not a lot that can be done here.

**Comment by prasadasokan** [comment]
@willpower232 There are no external filters/firewall through which these traffic are flowing. Initially, we doubted our ansible playbooks. But even the UI having the same error is what is little confusing. Will you be able to tell me what to look for or I can upload a dump for you to take a look on to the code that is available in our installations. Will you be able to help?

**Comment by prasadasokan** [comment]
@willpower232 Can you send a test email to prasadasokan@outlook.com from your web based UI to see if it is landing on the inbox? This way, at least we will be able to confirm that the reason for emails landing on the junk folder is due to the invalid date issue. And if this is successful, I shall try building a new server to see if that helps.

**Comment by prasadasokan** [comment]
@willpower232 Can this be a cause for the invalid date issue to occur in our case?

https://stackoverflow.com/questions/4301464/what-is-causing-this-invalid-date-error

I can see that the below file is using strptime on line no 383 of the below file. 

vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/values/time_zone.rb


`parts_to_time(DateTime._strptime(str, format), now)`

**Comment by prasadasokan** [comment]
@willpower232 And I see three files having reference to "invalid date" in the postal directory.
vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/parsers/date_time_parser.rb
vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/fields/date_field.rb
vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/string/conversions.rb

Any clue if the encoding format, or something like that causing the invalid date issue?
