### ISSUE TITLE
Domain of sender address does not exist Error ?

### ISSUE THREAD

**Issue by Manishjodhani** [postalhq/postal#641]
Hi,
Some of my mails were hard fails due to this reason.
Please have a look in screenshots.
![screenshot_30](https://user-images.githubusercontent.com/28861157/44458150-ed971300-a622-11e8-8b56-84b69b71704c.png)
And we are using support@ourdomain.org this sender mail id is valid.

**Comment by willpower232** [comment]
If you've been given an invalid email address, I don't think theres anything you can do.

In your screenshot it sounds like they haven't set up the return path for their own email system.

**Comment by catphish** [comment]
I believe this is the recipient checking the existence of the envelope from domain. It may be resolved if you add an MX record and/or an A record to that rp.cloud.xxxxxxxxxxx domain name pointing to your mail server. If that is a CNAME, then those records would be added at the final domain to which the CNAME points.

**Comment by Manishjodhani** [comment]
Thanks @willpower232 for reply.
I check the records and yes,they don't have pass the return path.
and i will correct it.
But can you tell what is actual use return path in this. If you don't mind.
It will help me to understands this.

**Comment by willpower232** [comment]
If you were expecting that bounce message to go to your Postal, you should be able to see the record you need to create in the Domains page.

**Comment by catphish** [comment]
The return path is the address in your screenshot above, beginning pks66q. This domain name should have MX records pointing back to postal so that bounces work correctly.
