### ISSUE TITLE
Mailwizz and Postal

### ISSUE THREAD

**Issue by yeah-nothing** [postalhq/postal#655]
I'm trying to use Mailwizz with Postal. I set up Postal on Ditigal Ocean using the quick install. Mailwizz is an email marketing application. Mailwizz is installed on Ditigal Ocean as well but on separate VPS. I have a domain "email-marketing.trade" assigned to my Mailwizz install. For my Postal install I created a floating IP address. I edited the dns section of my "/opt/postal/config/postal.yml" and added the floating IP address. Then I re-started my Postal server. I added the Mailwizz domain "email-marketing.trade" to my Postal configuration. (When I created an organization) I added the records that Postal said to add to my doamin (email-marketing.trade). My goal is to use Mailwizz as my campaign manager and Postal to do the actual mailing. Mailwizz manages my lists, newsletters and campaigns. Mailwizz supports several popular MTAs. Mailgun, Sendgrid, etc... In the admin panel of Mailwizz I'm able able to add a custom SMTP configuration. I had Postal generate some SMTP credentials. I then tried to use these credentials with Mailwizz and I get the following error. 

Connection could not be established with host postal.206.189.250.128 [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]
Log data:
++ Starting Swift_SmtpTransport
!! Connection could not be established with host postal.206.189.250.128 [php_network_getaddresses: getaddrinfo failed: Name or service not known #0] (code: 0)

Does my Postal install need a FQDN in order to function properly? What am I missing with the Postal configuration? Mailwizz has three options for SMTP authentication TLS, SSL and STARTLS. Postal doesn't support this option or does it? The SSL sertificate on my Postal installation is self-signed. I don't know if that makes a difference.

AND MY FINAL QUESTION....Can you recommend any list management/marketing apps that might play well with Postal? Say like Mailman or PHPMailer. Do the list management apps need to be installed on the same server running Postal? Any tutorials on setting this up?

Thank You

**Comment by visomymail** [comment]
my friend, did you understand your problem? I'm trying to do the same as you, glad to any advice

**Comment by willpower232** [comment]
postal.206.189.250.128 doesn't sound like a real domain name. Either use a real domain name or an IP address.

On the credentials page of your Postal setup there should be a link at the top which says "Read more about sending outgoing e-mails" which takes you to a page explaining what SMTP details you will need.

Postal should work with any system that supports sending messages via SMTP.
