### ISSUE TITLE
Error: Net::SMTPAuthenticationError (503 5.5.1 Error: authentication not enabled )

### ISSUE THREAD

**Issue by neidiom** [postalhq/postal#685]
I have configured SMTP in `/opt/postal/config/postal.yml` to send tolocalhost on port 25 using a username and password  created from postal web admin interface. When I try to send email with `postal test-app-smtp me@examle.com` I get following error `Error: Net::SMTPAuthenticationError (503 5.5.1 Error: authentication not enabled )`. Can you point me to the right direction?

**Comment by neidiom** [comment]
@willpower232 any idea why smtp is not running on port 2525? No other services are running such as postfix.

**Comment by willpower232** [comment]
We run Postal primarily on port 25 and use iptables to allow access from 2525 to get around various blocks.

Have a look at https://github.com/atech/postal/issues/565

Have you tried using `netstat -lnp` to see which ports are being used on the server?
