### ISSUE TITLE
Postal tuning for sending out a massive email campaign (> 1 million)

### ISSUE THREAD

**Issue by vishnus** [postalhq/postal#697]
Hi there,

We've been using Postal in production for last one year and we couldnt be happier with the performance. We recently built a list campaign manager inhouse in Golang, it can push over 10k emails in matter of seconds to the SMTP. But postal seems to throw timeout / connection pool error (ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds) maybe 2-3 times in a second. We think our config may not be right. We have 36 core, 68GB server where postal is running. Load is always less than 3. Currently the config looks like this:

workers:
  quantity: 60
  threads: 80
main_db:
  host: 127.0.0.1
  username: postal
  database: postal
  pool_size: 150

Mysql DB has max_connections set to 5000. Is this configuration ok?  How can we use the system specs to the fullest? More than 50 workers its not spawning when we gave. The thread count and pool_size what is the relation we couldnt really understand. Can someone shed some light on this?

**Comment by willpower232** [comment]
It might be that your `max_connections` is being reached, based on https://github.com/atech/postal/issues/324#issuecomment-323538575 and your email volume, its likely that number needs to be much higher.

You should be able to use some database tools to monitor the number of active connections and see how quickly you use up the connections.

**Comment by rafaelsisweb** [comment]
60 workers with a pool_size of 150 connections = 9000 connections . 
That is the right interpretation of this scenario?

**Comment by vishnus** [comment]
@rafaelsisweb  same question even I have.. what would be the right max_connection required in Mysql config?

**Comment by willpower232** [comment]
I would suggest 9000 at minimum as calculated, maybe 10000 to give you more room.

You'd have to continue monitoring to see if this resolved your problem and increase further if necessary. If it doesn't have any effect or reduction in your issues at all, we'll have to consider something else.

**Comment by vishnus** [comment]
Thanks @willpower232 . 

I've tweaked some config and its currently:

System: 36core, 68gb RAM

Mysql:

```
innodb_buffer_pool_size	= 2048M
innodb_flush_log_at_trx_commit = 2
max_connections		= 8000
wait_timeout		= 31536000
max_allowed_packet	= 256M
```

Postal:
```
workers:
  quantity: 50
  threads: 80

main_db:
  pool_size: 150

message_db:
  pool_size: 50
```

We are sending a bulk campaign only next week now, so can tell then if this works. Normal emails are  going fine, ~100k a day happens seamlessly. We will know when we actually send out campaign email in bulk if this works. 
Any other thoughts on scaling, please feel free to post it here.. thanks

**Comment by willpower232** [comment]
Interesting, it might be that your next step is an additional server and to make a cluster out of your setup if you're starting to max out resources.

**Comment by vishnus** [comment]
I hope to see the resources maxed out :) 

On a different topic, if we set up another SMTP server, (not postal, just a simple golang email relay server), would it be possible to use that server also?

**Comment by vishnus** [comment]
So went sent another set of emails. Upto 300k it was sent in an hour. Exactly after 58minutes, sending stopped completely. But emails were queuing up. Then in worker.log we could see this error:

`ActiveRecord::StatementInvalid: Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: UPDATE `queued_messages` SET `queued_messages`.`locked_by` = NULL, `queued_messages`.`locked_at` = NULL WHERE `queued_messages`.`id` = xxxxx
`

Any thoughts? Theres over 20k emails in queue which needs to be sent before resuming the rest of the emails..

**Comment by vishnus** [comment]
Ok I manually cleared the locks following #645 

Any reason why all of a sudden this would have happened? Load and RAM was fine. I'll rerun now and will increase mysql connections a bit more and see..

**Comment by willpower232** [comment]
That error message implies that you are now so aggressively using the database that all the updates involved can't complete properly. You can increase the wait timeout as suggested here: https://dba.stackexchange.com/questions/100984/mysql-lock-wait-timeout-exceeded-try-restarting-transaction

As time goes on and your mail volume grows, you may need to consider dividing your workload between multiple servers so you don't completely swamp out your server and it becomes unusable.

**Comment by vishnus** [comment]
@rbustos yes, we're running in one server. 400/min is very less. Just with 4 core, 16gb, we were able to send at 1500 emails/min. Is your email triggering application slow?

**Comment by rbustos** [comment]
Actually I sent all emails previously to a postfix queue and then it talk directly to postal (smtp.1). So with this I tried to avoid any bottleneck between them.

**Comment by vishnus** [comment]
@willpower232 I think we've cracked the specs and config! We sent out over 1.1 million emails in less than 3 hours (all delivered except for 2-3k bounced). We got a speed of over 6400 emails per minute, ie around 105 emails per second. We had zero timeouts, not even single email was lost in transit. We used the same hardware and the following config:

Mysql:
`
innodb_buffer_pool_size	= 3048M
max_connections		= 9000
connect_timeout		= 6
wait_timeout		= 31536000
max_allowed_packet	= 256M
`
Postal config:
`
workers:
  quantity: 50
  threads: 60

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: xxxx
  password: xxxxxx
  database: postal
  pool_size: 150
`
Hope this thread helps someone who is looking to scale their postal set up :)

**Comment by willpower232** [comment]
Good to know some numbers.

Not refreshing the UI might have helped but you'd hope that the UI wouldn't block the workers from working. It might be easier to monitor the server from the cli, watching htop or any server manager so you can see when its quietened down again.

**Comment by vishnus** [comment]
In case anyone interested, we've open-sourced the mailing list manager used for sending over a million emails in a couple of hours: https://listmonk.app - we use Postal SMTP.

**Comment by rafaelsisweb** [comment]
Hi @vishnus ,

Can you share details of your postal setup?
Or even improve project doc with tips to handle this workload?

**Comment by vishnus** [comment]
> @willpower232 I think we've cracked the specs and config! We sent out over 1.1 million emails in less than 3 hours (all delivered except for 2-3k bounced). We got a speed of over 6400 emails per minute, ie around 105 emails per second. We had zero timeouts, not even single email was lost in transit. We used the same hardware and the following config:
> 
> Mysql:
> 
> ```
> innodb_buffer_pool_size	= 3048M
> max_connections		= 9000
> connect_timeout		= 6
> wait_timeout		= 31536000
> max_allowed_packet	= 256M
> ```
> 
> Postal config:
> 
> ```
> workers:
>   quantity: 50
>   threads: 60
> 
> main_db:
>   host: 127.0.0.1
>   username: xxxx
>   password: xxxxxx
>   database: postal
>   pool_size: 150
> ```
> 
> Hope this thread helps someone who is looking to scale their postal set up :)
> 
> Apart from these minor tweaks, the only difference from last times was that we did not constantly refresh the postal web. Probably that might have reduced some select queries unnecessarily hitting the db?

@rafaelsisweb you can check this config

**Comment by sergeymavrin** [comment]
@vishnus Does Your mailing list have different ISPs or it is one domain, one ISP?
