### ISSUE TITLE
How to delete an admin user

### ISSUE THREAD

**Issue by zeeshanjamal16** [postalhq/postal#698]
I had created 3 admin users with the command `postal make-user`. Now I want to remove one of them but could not find a suitable command for that. Is there any way to remove admin user?

**Comment by willpower232** [comment]
I don't believe there is a UI for the admin users at this time, you will have to manually make changes in the users table in the database.

**Comment by zeeshanjamal16** [comment]
@willpower232 Can you please inform in which tables these entries are saved. I would like to make a bash script for this so that it can be directly deleted from command line.

**Comment by willpower232** [comment]
As far as I can tell, the user entries are only in the main Postal database in a table called users.

I'm not sure if there are any relations that require the user record to exist so to be safe you could put `[disabled]` on their email address and blank out the password so the account exists but cannot be used.

Definitely take backups before you proceed though.
