### ISSUE TITLE
how to send emails as part of a thread vs new thread?

### ISSUE THREAD

**Issue by rileylnapier** [postalhq/postal#701]
hi all, i'm using postal through my work and we want to make sure that when we send certain emails, that they get delivered as "replies" in a thread vs brand new emails.

doing some testing, i see that if the subject lines match... then the email will fall into a reply and will collapse under the main email (this is gmail/inbox). i will be doing some testing on yahoo/oulook after submitting this issue.

i do see that when sending an email, i get a messageId in the response data.  can I use this message id to force a reply to a thread?  

or is it possible that every email client treats emails differently?

thanks for any help!!!!

**Comment by rileylnapier** [comment]
is it as simple as just making the subject "Re: ${oldSubject}"

**Comment by willpower232** [comment]
> or is it possible that every email client treats emails differently?

Thats exactly it.

This isn't really a Postal issue, no one can guarantee that emails received will be threaded.
