### ISSUE TITLE
Correct return_path configuration when using postal only as SMTP-server

### ISSUE THREAD

**Issue by olegblecher** [postalhq/postal#702]
Hi everyone,

I've been using Postal now for a while and I'm really enjoying it.

Support my company's domain name is "company.org". _company.org_ is using Google's email service (that's where the mailboxes are, Postal is only sending all sorts of automated emails). I've tried setting `return_path` to _company.org_, but that generates a `550 Invalid server token` whenever I try to email *@company.org. I can email all other addresses, and I have zero issues when sending emails via the API.

What would be the correct way to configure Postal? I would like to have _company.org_ as a return path, and right now I am simply just using _rp.company.org_ as a return path with an MX-post that looks real, but doesn't deliver anything anywhere.

I have no routes configured. 

Here's my config file:

```
dns:  # Specifies the DNS record that you have configured. Refer to the documentation at  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further  # information about these.  
mx_records: 
   - company.org  
smtp_server_hostname: postal.company.org 
spf_include: spf.postal.company.org  
return_path: rp.company.org
route_domain: routes.postal.company.org
track_domain: track.postal.company.org
```

Thanks!

**Comment by willpower232** [comment]
All of the DNS records need to point back to your Postal server otherwise it will not receive bounce backs and there may also be some message verification issues with people receiving the messages.

**Comment by olegblecher** [comment]
Got it! So basically, using a @postal.company.org-addresses will solve the issue.

**Comment by willpower232** [comment]
I mean the MX and Return Path need to point back to your Postal server, using different email addresses is not likely to change the situation.
