### ISSUE TITLE
This message was a bounce but we couldn't link it with any outgoing message and there was no route for it.

### ISSUE THREAD

**Issue by realseoexpert** [postalhq/postal#706]
I have two systems doing the same thing for bounces: "This message was a bounce but we couldn't link it with any outgoing message and there was no route for it." So it's not managing to associate them with an outgoing email it looks like. Any suggestions? All dns looks to be set up correctly.

**Comment by realseoexpert** [comment]
Thanks, I have two postal systems installed, both showing this same error. They were installed for different customers. We are using mailing software (have tried mailwizz, mumara and mautic. I have a test email list that includes an email I know to be set up to return as a bounce (for testing bounces). So I am not sure if it's just because I have set something wrong or not, but we had this issue in the past as well, with bounces not being handled well specifically.

The message is being sent to bounce-test@service.socketlabs.com and coming back into the system as from 3e8.10.thd8dh=psrp.mydomain.com@tracking.socketlabs.com and being delivered to the return path. which is  thd8dh@psrp.mydomain.com.

When it comes back into my system it displays an unknown route and in the bounce detail states "This message was a bounce but we couldn't link it with any outgoing message and there was no route for it.".

**Comment by willpower232** [comment]
When you say you have two installed, are they sharing a database and queue?

**Comment by realseoexpert** [comment]
No, totally different systems, the only reason I mentioned "two" was to indicate that at least for me, the same behavior is being displayed in multiple instances.

**Comment by realseoexpert** [comment]
Any ideas? This is a major issue for us. Is nobody else seeing this?

**Comment by realseoexpert** [comment]
Hey @willpower232 , I don't think you are reading my responses fully. The two systems are NOT connected, they have nothing to do with one another, the only reason I mentioned both was to show a reproduced issue, ie I have installed this twice now and have the same issue on both systems.

I am NOT trying to get the two systems to work together. I, however, AM trying to get bounces to work correctly, on just ONE system, NOT a combined system. I am looking for solutions related to that. Thanks.

**Comment by willpower232** [comment]
If they have nothing to do with each other, you should make sure that the configuration is also completely different. Particularly the DNS records for `return_path`.

It sounds like they are receiving each others message bounce backs so its likely they are connected in some way.

**Comment by realseoexpert** [comment]
@willpower232 again, EVERYTHING is different on these, domains, dns, rpath, everything. They are NOT connected in ANYWAY. The bounce back issue is on a SINGULAR machine.

**Comment by willpower232** [comment]
Your initial message said you had two systems with the same problem hence the apparent confusion.

You may be interested in https://github.com/atech/postal/issues/154

**Comment by realseoexpert** [comment]
Thank you, I TRULY appreciate your time.

**Comment by realseoexpert** [comment]
> Were you able to solve the issue @realseoexpert ?

@Randall-Coding no, I have not. Do you have a solution? I am using Cloudflare and somebody suggested that could be an issue, but we aren't using their cache so I'm not clear why it would be.
