### ISSUE TITLE
Query regarding postal

### ISSUE THREAD

**Issue by tushar1135** [postalhq/postal#710]
Hi,
Please can anybody describe the main use of postal. It is ok if post some helpful links.
I have a requirements like:
1. Create separate links for separate organizations with a single installation.
ex: example.com/org1, example.com/org2 etc.
2.  Organizations admin can see the domains under it & Other users can see there own accounts.
3. Can we create users by sending invitation?
4. Can we create email ids for my domain?

**Comment by willpower232** [comment]
1. Organizations are separate entities yes.

2. An administrator can see all things, an organization user can only see servers in that organization.

3. I believe this is possible, yes.

4. I'd hazard a guess that you want a system that provides and uses email addresses? Postal is not like that at all, there are no mailboxes to speak of. Postal mainly sends emails generated by other systems.

**Comment by tushar1135** [comment]
Thanks for your quick reply. It's very clear now.
Please can you help me on point 3. 
That is creating multiple users for different organizations. 
First of all we need to create new users using command prompt or by sending invitation.
I am trying to send invitation but it was not working. It is processing for long time.

**Comment by willpower232** [comment]
If you want to create a system-wide admin that can see all organizations, then you need to use the command line.

Users that can only access one organization have to be made in the user interface.

Have you configured the ability for Postal to send emails to itself in `postal.yml`?

**Comment by tushar1135** [comment]
I have created system-wide admin and it works fine. But For individual organization its not working. I am able to send test emails from multiple domains, I have set up for different organizations.

Yes i need your help on postal.yml file.

web:
  # The host that the management interface will be available on
  #host: postal.mazeweb.com
  host: 147.135.203.103
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: passwd_1
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: passwd_1
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: passwd_1
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.mailconic.com
  smtp_server_hostname: postal.mailconic.com
  spf_include: spf.postal.mailconic.com
  return_path: rp.postal.mailconic.com
  route_domain: routes.postal.mailconic.com
  track_domain: track.postal.mailconic.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal.mailconic.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 4e9d6718c0c6e6d5ffe791ca1d6b70c97ff52747e25342d27130a2217d22b40292072bd5bacb79132e0b7d1f902589fd1362c4aa7ae89e70bd162ff4ad2f168b9cb418bd05e42a0fadad92f0cd42faad79fc29d836d77e817bdf1146098f8744aeeb4d27274864f1040f9a8e62f7a7b78962054b351f22ad1675a066615ed92e

**Comment by willpower232** [comment]
The `smtp:` section is where you need to look.

You have currently specified `from_address: postal.mailconic.com` but this needs to be an email address such as `from_address: postal@mailconic.com`. You should then add `mailconic.com` to your Postal server, create an SMTP api key and update the username and password appropriately.

**Comment by tushar1135** [comment]
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 25
  username: mcon/mcon # Complete when Postal is running and you can
  password: gxYxQnAXjEYeY4YJmmaneshe # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@mailconic.com

Still not able to sending invitation. 

We can send invitation to any email id or like exa1@mailconic.com or exa2@mailconic.com
For different domain do we need multiple SMTP setup?

**Comment by tushar1135** [comment]
postal test-app-smtp tusharm@drupway.com

o/p
Message was not delivered successfully to SMTP server.
Error: ArgumentError (An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.)

  SMTP Host: 127.0.0.1
  SMTP Port: 25
  SMTP Username: mcon/mcon
  SMTP Password: gxYxQnAXjEYeY4YJmmaneshe

**Comment by willpower232** [comment]
Firstly, you should **delete the credential right now** because you have posted it here.

These details are only for Postal sending its own emails. Once its working, you should be able to invite any email address.

Did you have a `from_address` set when you tried `postal test-app-smtp`?

**Comment by tushar1135** [comment]
Thanks for your suggestion. I have deleted the credential and now I am able to send the test emails.
But Unable to send the invitation to user. Still processing......for long time.
![capture](https://user-images.githubusercontent.com/45814724/50021543-720d0780-ffff-11e8-9489-4ce617c4fb28.PNG)

One more query?
How to set up "SMTP" for multiple domain?
Thanks for all your help.

**Comment by willpower232** [comment]
Ah thats interesting. It might be worth using the developer tools in your browser to see if there is a different error hidden in there.

It looks like the SMTP is working for your Postal already so whichever SMTP credentials you make should all use the URL of your Postal server, regardless of which domain they are for.
