### ISSUE TITLE
Removing Email Queues on Database

### ISSUE THREAD

**Issue by joeneldeasis** [postalhq/postal#714]
Is there any way to remove the queued messages on the database? As far as I know I've set the `status` to `HardFail` on table `messages` and then restart the postal services but it does not reflect the number of removed queued messages on the dashboard.

**Comment by willpower232** [comment]
Queued messages are also in the `queued_messages` table which I believe is the table actually responsible for that count

(Maybe related https://github.com/atech/postal/issues/521)

**Comment by joeneldeasis** [comment]
Hi can you guide me how to set it all the emails to `HardFail` so it will not be processed anymore? Or I can just delete the emails in the `raw` tasbles of each `postal-server-*` database? Thanks

**Comment by willpower232** [comment]
The raw tables are the actual content of the message, deleting them will not change anything apart from you storing the content of the messages.

If you find the messages you want to stop in the `messages` table in each database, you can change the `status` field there.

If you want to remove messages from the queue, you will have to remove them from the `queued_messages` table and also remove them from RabbitMQ if they have already been put there but I am not sure how to do that last part.
