### ISSUE TITLE
Changing Domain Name From Example.Com 

### ISSUE THREAD

**Issue by jackrobson** [postalhq/postal#715]
Hello Postal enthusiast,

I really like the look of your app. It's capabilities are far beyond that of other open-source projects I've seen, and it's documentation and support look great! 👍 

However, I'm perplexed by one somewhat simple step in the setup. How do I tell the system what my domain name is? Everything appears to go good, and I'm able to send mail but not receive it.

I think this is because the system thinks I'm using example.com not toastedham.info which is a test domain I have for my mail.

I think this issue is better explained in a story format:

I completed the first 5 steps of the https://github.com/atech/postal/wiki/Quick-Install page on a fresh Ubuntu 16.04.5 x64 hosted by DigitalOcean.

I then setup  organization, mail server.a domain, routing and credentials.

Using this, I was able to send an email using the SMTP.

However, I am unable to receive mail because it ends up trying to get delivered to ifiqta@rp.postal.example.com not ifiqta@rp.postal.toastedham.info.

https://imgur.com/a/ERxxEfh

Also, if I try to register SSL using postal register-lets-encrypt notmy@email.com it comes back as using example.com as seen on the bottom of this screenshot:

https://imgur.com/a/fkPe0Jr

I also noticed that DNS verification fails. I assume because it's checking against records using example.com not toastedham.info. See this for an image of what I see on this screen:

https://imgur.com/a/E2A6wUL

Super excited to begin using this app. Any help getting over this final hurdle is greatly appreciated.

Kind regards, Jack.

Steps to reproduce the SSL error (the quickest issue to reproduce IMO):
1.  Deploy Ubuntu 16.04.5 x64 doplet on DigitalOcean. 
2. First 5 steps of the https://github.com/atech/postal/wiki/Quick-Install
3. inside /opt/postal/config/postal.yml I replace all instances of example.com with toastedham.info
4. postal register-lets-encrypt notmy@email.com
5. Check certificate https://www.sslshopper.com/ssl-checker.html

**Comment by jackrobson** [comment]
I needed to have the application reload using  "postal restart", after changing /opt/postal/config/postal.yml.

Shows how green I am that this took me nearly a couple days of dev time to come to this conclusion that lead me to finding my answer. :)

Great app. Thanks for your amazing repo.

**Comment by jackrobson** [comment]
It seems that the previous does not fix the SSL certificate issue.

My new droplet experiences the same issue.

https://www.sslshopper.com/ssl-checker.html#hostname=https://wpsupportuk.me/

Steps to reproduce:

1. Deploy Ubuntu 16.04.5 x64 doplet on DigitalOcean.
2. First 5 steps of the https://github.com/atech/postal/wiki/Quick-Install
inside /opt/postal/config/postal.yml I replace all instances of example.com with mynewdomain.com
3. postal restart
4. postal register-lets-encrypt notmy@email.com
5. Check certificate https://www.sslshopper.com/ssl-checker.html

How do I uninstall the current certificate and change the domain name so the next certificate is correct?

**Comment by willpower232** [comment]
The lets encrypt integration is for the click tracking service. If you want to put your UI behind SSL, you'll need to update the nginx configuration with valid SSL certificates you obtained yourself.

For some reason I forget, I have an admittedly probably incomplete gist about it https://gist.github.com/willpower232/40719db4b42748822d4ea3c3f8c6961c
