### ISSUE TITLE
How to delete attachment.

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#719]
Hello 

How to delete attachment after message is  delivered in Postal.
![screenshot_24](https://user-images.githubusercontent.com/46315368/50721648-e3187a00-10e8-11e9-9a70-47dcf62a8794.png)

![screenshot_43](https://user-images.githubusercontent.com/46315368/50721623-9fbe0b80-10e8-11e9-9798-fcddccd63294.png)

**Comment by willpower232** [comment]
The settings tab of that particular server will show you how long it will automatically retain information about the message and then you can predict when the attachments and other information will be automatically removed.

Are you looking to remove specific attachments only?

**Comment by zeba121** [comment]
yes
