### ISSUE TITLE
fastserver: error fetching interface information

### ISSUE THREAD

**Issue by wh4u** [postalhq/postal#733]
OS: Ubuntu 17.10
At my dedicated server i have my main physical Ethernet card.
An ip address is assigned properly and postal is installed successfully.

I have also ordered an extra vlan of 8 ip addresses for postal's ip-pool
One of them will be used on fastserver.
Fastserver is enabled on postal.yml with proper configuration.

Those 8 ip's are added on my OS as ip alias on the /etc/systemd/network/50-default.network file.

On postal status the fast.4 status is Failed.
Ipconfig -a : fastserver: error fetching interface information: Device not found

Postal mailserver needs the dedicated ip for the fastserver to be on a physical Ethernet card?

**Comment by willpower232** [comment]
If the server is able to be aware of the IP addresses, that should be enough for Postals click tracking.

Are you able to see all the IP addresses you're expecting with `ip a`?

I'd also point out that 17.10 is now EOL and for web-facing a server OS, you should use an LTS version, either 16.04 or 18.04.

**Comment by wh4u** [comment]
This is my ifconfig status.
all extra ip's all publicly available and working.
a also did a do-release-upgrade successfully.

Maybe postal is checking for eth based names for network cards?
i see that my physical card is named enp1s0

ifconfig -a
enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet xx.xx.xx.xx  netmask 255.255.255.0  broadcast xx.xx.xx.xx
        inet6 xx.xx.xx.xx::  prefixlen 64  scopeid 0x0<global>
        inet6 xx.xx.xx.xx  prefixlen 64  scopeid 0x20<link>
        ether xx.xx.xx.xx  txqueuelen 1000  (Ethernet)
        RX packets 3447  bytes 377943 (377.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1950  bytes 220594 (220.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xde200000-de27ffff

enp2s0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether xx.xx.xx.xx  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xde100000-de17ffff

fastserver: error fetching interface information: Device not found

**Comment by willpower232** [comment]
I know Postal doesn't use device names to reference the IP addresses.

Have you definitely set the fastserver `bind_address` value to use one of the inet or inet6 values shown under "enp1s0"?

**Comment by wh4u** [comment]
Yes ip address is set correctly

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: xx.xx.xx.13 (extra ip on /etc/systemd/network/50-default.network file)***
  port: 80
  ssl_port: 443
  proxy_protocol: false
  default_private_key_path: /etc/letsencrypt/live/mailer.sendnewsletter.today/privkey.pem
  default_tls_certificate_path: /etc/letsencrypt/live/mailer.sendnewsletter.today/fullchain.pem
---
***
[Address]
Address=xx.xx.xx.13/32
Label=fastserver

**Comment by willpower232** [comment]
And does that `.13` ip address appear if you do `ifconfig -a`?

**Comment by wh4u** [comment]
Response : 
enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet xx.xx.xx.215  netmask 255.255.255.0  broadcast xx.xx.xx.255
        RX packets 18557586  bytes 11587142563 (11.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13170488  bytes 11334678646 (11.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xde200000-de27ffff

enp2s0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xde100000-de17ffff

fastserver: error fetching interface information: Device not found

**Comment by willpower232** [comment]
So your computer is only seeing a `.215` address and there isn't a `.13` to bind to?
