### ISSUE TITLE
How does one use OWN SSL in place across whole Postal?

### ISSUE THREAD

**Issue by uhlhosting** [postalhq/postal#736]
Hello I have added in my config ssl settings for tracking server, alto service is keep failing, here are some outputs bellow.

I have since updated the SSL ownership from root to postal.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/6324047/52119941-24824380-261b-11e9-8b40-367b62bf519b.png">

Now I am not sure from the saying to where the new KEY and cert are placed. I put mine in place manually.

Here is the home directory structure:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/6324047/52119923-12080a00-261b-11e9-8ace-685bf05809a6.png">

whereas again very confused hence the config I used is in ~/config , while making some research there is another config file in app/config now I am not sure what is valid, just why aren't those symlinked, should I do it manually a symlink?

Note: I am open to pay someone to help us faster solve some Postal issues we meet on deployment, PM for more info or drop me a line cosmin at uhlhost . net

**Comment by willpower232** [comment]
The fast server generates its own SSL certificates for click tracking using Lets Encrypt. This is because click tracking can use a custom domain configured in the interface and there is no ability to supply your own certificate here.

If you're talking about a certificate to access the UI of Postal, you should do this using nginx.

`~/config` is your actual config, `app/config` is for the files from the main code that provide default values to Postal. You should only change things in `~/config`.

**Comment by uhlhosting** [comment]
@willpower232 how does one adds ls ssl to localhost also lets encrypt? we already have own ssl in nginx that works fine. So should i be worried if i made changes in /opt/postal and in app/config besides ~/config . initially was using only this one, then had some issues and the online guides a time mentioned editing these files. is there some way to get some paid professional support for some fine tuning and improvements?

**Comment by willpower232** [comment]
if your nginx is happy then you are able to access the Postal UI over HTTPS? You don't need to worry about the click tracking certificates, they should handle themselves unless theres a problem.

Your changes in app/config should be fine for now but I would add them to your ~/config before you next try to update Postal.

I think there was a request in another issue about paid support and I believe atech themselves may offer it too but you'd have to have a look in other issues.

**Comment by uhlhosting** [comment]
Yes nginx works fine over https. 
So you say i should try atech?

**Comment by willpower232** [comment]
> I think there was a request in another issue about paid support and I believe atech themselves may offer it too but you'd have to have a look in other issues.

**Comment by uhlhosting** [comment]
> I think there was a request in another issue about paid support and I believe atech themselves may offer it too but you'd have to have a look in other issues.

it seems from their official side they do not, this is at the hands of community.
