### ISSUE TITLE
setting up mailgrid or mailjet type service

### ISSUE THREAD

**Issue by dataent** [postalhq/postal#740]
We have a saas that as a small feature is going to be a mailgrid type service. We have made a marketing app such as mailchimp or mailjet which creates dkim for each customer and that is fine. However how do we transfer that verification through to the end receiver or our clients customer? We cant manually add  all of the domains to postal. Does anyone have a solution to this problem.

**Comment by willpower232** [comment]
If you have the ability to send emails and make DKIM records, why do you need Postal?

If you can't send emails without Postal, why would you make your own DKIM? You could let Postal do the work of handling the DKIM and just worry about passing your messages to Postal.

At the minute, there isn't an API for adding or managing domains so if you want to avoid using the Postal interface, you would have to make something to do so yourself.
