### ISSUE TITLE
How to configure Postal to mark the message as "Softfail" after "Maximum number of delivery attempts (18) has been reached

### ISSUE THREAD

**Issue by saporus** [postalhq/postal#741]
If you are someone like me using Webhook to process bounces for your email marketing application like (Mailwizz), if Postal return "Hardfail" status to your Email Marketing App, your EMA will mark it also as "Hardfail" and it would be added to global blacklist automatically just the way Mailwizz Email Marketing App works.

So, In a case that "SoftFail" error continue to appear during Maximum Final retry attempt and postal marks it as Hardfail.

An error such as `421 4.7.0 [TSS04] Messages from XXX.XXX.XXX.XXX temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html` should be marked as "SoftFail" at the Final retry attempt as this kind of issue is temporary but postal currently mark it as "HardFail" and because of this, if you are using webhook to process your bounces, the return code to your app would be "HardFail". EMA like Mailwizz will add such address to global blacklist because the app believes that such email address does not exist base on the status code the app received from the MTA.

**Solution**

Change the `HardFail` at line https://github.com/atech/postal/blob/a7e3e9de79fdd0d9cf7d811d370e854dd5307da9/app/jobs/unqueue_message_job.rb#L68 to `SoftFail` and then restart your postal `postal restart` for changes to take effect

Thanks

#399

**Comment by willpower232** [comment]
FWIW if you're seeing that error message, its likely Yahoo is upset with your servers email sending (either because of you or a past user of the IP address) so recording SoftFails and continuing to deliver emails to Yahoo is unlikely to resolve the situation.

**Comment by saporus** [comment]
Yes, but it shouldn't be marked as "Hardfail" neither, the email marketing app should be the one to do that and not the MTA. Other MTA doesn't do such as far as I know.

My email marketing app has option of blacklisting email address of subscriber if it reaches maximum "softfail" configured in the app.

If a "softfail" occurs and it reach the maximum retry time in postal, there are chances of re-sending the campaign and later get sent.

BTW, apart from such error above, I have came across so many other errors **e.g** whereby the "resolv.conf" is the problem and we were getting "could not resolve host xxx.com" within the postal app and postal continues to retry and eventually got to the maximum retry time with "hardfail" status, the webhook was triggered and my EMA marked such subscribers as "hard" and also blacklist it thinking the subscribers wasn't valid before we could even investigate and resolve.

We had to start tracing and removing over 700k of email addresses from the EMA blacklist.

Thank you!

**Comment by willpower232** [comment]
You'll see in the error message you got that Yahoo said the error code was 421.

This is apparently a vague error but is usually a hard fail so that would be why Postal considered it as such.

**Comment by saporus** [comment]
421 4.7.0 isn't a hard fail but temporary error and postal never consider such as hard fail until it reaches the maximum retry time

544 is the hard fail. for example 

> "554 delivery error: dd Sorry, your message to xxxx@yahoo.com cannot be delivered. This mailbox is disabled (554.30). - mta4015.mail.ne1.yahoo.com"

Thanks

**Comment by willpower232** [comment]
Sorry I meant to say that usually after 18 softfails in a row, it would be a hard fail.

Otherwise Postal could continue trying to send it for some time which would delay other messages trying to get through the system.

You'll see that Postal even waits longer and longer between each attempt to reduce the likelyhood of a hardfail https://github.com/atech/postal/blob/master/lib/postal/smtp_sender.rb#L158-L168
