### ISSUE TITLE
Feature Request: Two factor authentication

### ISSUE THREAD

**Issue by martijnhartlief** [postalhq/postal#752]
Is it possible to implement and optionally require 2FA for users?

**Comment by willpower232** [comment]
Its definitely possible but it will rely on someone who knows rails well enough to put in the work for it.

I'd definitely like to see it included but its a bit over my head at the minute.

**Comment by c-nv-s** [comment]
> Is it possible to implement and optionally require 2FA for users?

This would definitely be amazing

**Comment by RyankePars** [comment]
> Is it possible to implement and optionally require 2FA for users?

That would be great!
