### ISSUE TITLE
No access via HTTPS protocol click tracking domaine.

### ISSUE THREAD

**Issue by ITfrance** [postalhq/postal#788]
Hello.
Does not work SSL on fast server.
Domaine: track.fafpro.fr
Additional information about settings: https://gist.github.com/ITfrance/75493012b7dd7a8c807120a0de85d479

**Comment by willpower232** [comment]
I'm not sure why `fast_server` has that config option since it should use Lets Encrypt to get all the certificates it needs.

Have you followed the steps in the wiki? https://github.com/atech/postal/wiki/Click-&-Open-Tracking#setup-lets-encrypt

**Comment by ITfrance** [comment]
Thanks for the answer.

Yes, I used this command `postal register-lets-encrypt`
Domain works if no SSL. I can see "Hello"
I've been trying to solve for a week. I read all the solutions here. Which way to look about `fast_server`?

**Comment by willpower232** [comment]
In theory the only settings you need for the `fast_server` are `enabled` and `bind_address` so I'd start by reducing down to just those two to avoid further confusion.

Can you also check the `lets_encrypt.log` log file in the Postal logs folder? It might be having an issue generating the certificates.

**Comment by ITfrance** [comment]
Looks like I haven't found a solution.

Another question: Is it possible to reinstall the postal and keep the old domain configuration?

**Comment by willpower232** [comment]
Do you mean the databases? You'd have to backup and restore them most likely.
