### ISSUE TITLE
Functional Installation Guide for Postal Mail Server

### ISSUE THREAD

**Issue by Hadeoluwah** [postalhq/postal#789]
Please how can I get the WORKING guide for the installation of Postal Mail Server?

I have tried all manner including the one you gave in May 2017 but none of them is working.

Could you please assist me with this quickly?

**Comment by tchwpkgorg** [comment]
https://github.com/atech/postal/wiki/Quick-Install worked for me quite well?

**Comment by Hadeoluwah** [comment]
Thanks tchwpkgorg

**Comment by willpower232** [comment]
If you are still encountering issues, please actually tell us what isn't working so we can see where things have gone wrong.

**Comment by Hadeoluwah** [comment]
The issue I am experiencing now is 502 Bad Gateway
nginx/1.10.3 (Ubuntu).

When I edited the postal.yml, the changes were not displaying on the DNS session of the installation when I clicked on domain and try to very the domain.

Instead of reflecting postal.mydomainame.com it was showing postal.example.com which was what I corrected it from for SPF, DKIM and others

So when I tried to restart the VPS thinking it will resolve the issue I can't access the postal installation again and the error on the page is 502 Bad Gateway
nginx/1.10.3 (Ubuntu)

I will appreciate your assistance if you can help me

**Comment by willpower232** [comment]
Please check `postal status` and see which services have failed. You may also find more information in `/opt/postal/logs`

**Comment by Hadeoluwah** [comment]
Postal status show that Error: Procodile supervisor isn't running

How can I fix this please?

**Comment by willpower232** [comment]
Have a look at `/tmp/postal/procodile.log` which is where the log file is apparently

**Comment by Hadeoluwah** [comment]
It returned error of no such file directory....

Waiting for your response boss

**Comment by willpower232** [comment]
If that file isn't present then it may never have started properly so you could have a look at the system logs, see if theres anything there. 

Alternatively, you could try running Postal directly `sudo -u postal postal start`

**Comment by Hadeoluwah** [comment]
This is what I got when I run that command;

`/root` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
Started Procodile supervisor with PID 13516

**Comment by Hadeoluwah** [comment]
This is what the server is displaying now "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

You guide seems to be working, I am expecting your response to get this sorted out again.

Thanks a million in advance

**Comment by Hadeoluwah** [comment]
This is the content of rails.log checked here /opt/postal/app/log 

# Logfile created on 2019-03-14 13:55:58 +0000 by logger.rb/61378

**Comment by Dr-Nio** [comment]
This command work for me sudo -u postal postal start
