### ISSUE TITLE
sending newsletters

### ISSUE THREAD

**Issue by ehsanhajian** [postalhq/postal#790]
I want to use postal to send newsletters to 100K subs. I couldn’t find this feature in your document and please let me know how to import my addresses and send the newsletters. Please let me know how to bulk import my addresses and specific settings on postal.

**Comment by ITfrance** [comment]
With one Postal it is impossible: https://github.com/atech/postal/wiki/FAQs#can-you-add-mailing-list-feature
You have to use something together with Postal: for example Mautic.
