### ISSUE TITLE
How To Delete Users Use Storage

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#795]
Hello Postal Team

I have created a postal  on Vps server and there total storage is 80GB I have used only 17 GB but they  show the 100 % use of the server and server is not working. Could you suggest me ,what is the reason?
And how I can delete user use storage.

Here is the Attachments of my VPS server

Thank You

![Screenshot_44](https://user-images.githubusercontent.com/46315368/56421740-a3eded80-62c1-11e9-9af3-5631e796cb44.png)
![Screenshot_45](https://user-images.githubusercontent.com/46315368/56421742-a4868400-62c1-11e9-943a-b8aefb007af9.png)

**Comment by rbustos** [comment]
Hi Zeba,
 I suggest you to dig under your configuration:

**Go to :** Postal -> Organization -> Settings > Advanced Settings

**Check :** RAW MESSAGE RETENTION SIZE (Local Filesystem)

If your are using a local database then:
**Check**
RAW MESSAGE RETENTION DAYS (Database, it store in local filesystem) 
MESSAGE RETENTION DAYS (Database, it store in local filesystem)

Hope it helps.
-rbustos

**Comment by zeba121** [comment]
Thank You so much Mr.-rbustos
