### ISSUE TITLE
webhooks not always processed?

### ISSUE THREAD

**Issue by tchwpkgorg** [postalhq/postal#796]
Just spotted this in /opt/postal/log/smtp_sender.log - an event which should generate two webhooks (I have a webhook configured for MessageDeliveryFailed and MessageBounced). However, it didn't trigger a webhook.

Any ideas why?

```
[worker.1:958] [2019-04-21T22:55:30.871] INFO -- : [PPIRRUWH] Connected to 2a00:1450:400c:c00::1a:25 (aspmx.l.google.com)
[worker.1:958] [2019-04-21T22:55:30.871] INFO -- : [PPIRRUWH] Sending message 1::24017 to some-dead-address@gmail.com
[worker.1:958] [2019-04-21T22:55:30.910] INFO -- : [PPIRRUWH] Net::SMTPFatalError: 550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/?p=NoSuchUser f199si8487887wmf.58 - gsmtp

[worker.1:958] [2019-04-21T22:55:30.966] INFO -- : [PPIRRUWH] Sending message 1::24044 to another-dead-address@gmail.com
[worker.1:958] [2019-04-21T22:55:30.999] INFO -- : [PPIRRUWH] Net::SMTPFatalError: 550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/?p=NoSuchUser f199si8487887wmf.58 - gsmtp

[worker.1:958] [2019-04-21T22:55:31.044] INFO -- : [PPIRRUWH] Finishing up

```

**Comment by willpower232** [comment]
I think a message only bounces if Postal receives a bounce email from the mail server it is sending to.

How does it look in the Postal UI?

**Comment by tchwpkgorg** [comment]
I think it's a bug.

Please see both messages were sent in one connection (worker.1:958 / PPIRRUWH).

When I've used "Redeliver message" (and thus, a single connection for a message), they sent a webhook as expected.

**Comment by rbustos** [comment]
Did you check if that email is under Suppressions list?

**Comment by tchwpkgorg** [comment]
If the email was under suppression list, Postal would not attempt to deliver to gmail.

Postal did attempt to deliver to gmail, which failed (550-5.1.1 The email account that you tried to reach does not exist), and yet - Postal did not trigger a webhook it had configured. This was going for several days.

@rbustos please note that Postal's bounce handling and automatic adding to suppression list is not really functional, as explained here: https://github.com/atech/postal/issues/786
