### ISSUE TITLE
Can I delete queue mails .. ??

### ISSUE THREAD

**Issue by sdp-inderpalsingh** [postalhq/postal#797]
Hi Team,

I have bulk mails on my server,around 30K . I want to delete queue mails. Please tell me procedure what to do now.

**Comment by rbustos** [comment]
Removing Email Queues on Database #714

**Comment by Ashishlead2** [comment]
Hi, I am facing the same problem. Can you please help me to clear queue. Also I am not aware how to access database for it. mysql -uroot not working here
