### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by pradiptac** [postalhq/postal#799]
When I am testing the mail server getting error like

Connected to smtp://postal.altisinfonet.in:25/?starttls=always
<< 220 postal.altisinfonet.in ESMTP Postal/MB6FOX
>> EHLO [172.31.32.8]
<< 250-My capabilities are
<< 250-STARTTLS
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> STARTTLS
<< 220 Ready to start TLS
ERROR: An error occurred while attempting to establish an SSL or TLS connection.
The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.
See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. 

My postal.yml contains

smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.altisinfonet.in/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.altisinfonet.in/privkey.pem
  tls_ciphers: TLSv1_1
  ssl_version: TLSv1_1
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14
smtp:
  host: postal.altisinfonet.in

Also I already executed
chown -R postal:postal /etc/letsencrypt/live/postal.altisinfonet.in
chown -R postal:postal /etc/letsencrypt/archive
chown -R postal:postal /etc/letsencrypt

My website is getting the certificate properly but SMTP not. What can be the issue?

**Comment by shinebayar-g** [comment]
I tried to do the same. Just putting cert paths like this
```
tls_certificate_path: /etc/letsencrypt/live/postal.altisinfonet.in/fullchain.pem
tls_private_key_path: /etc/letsencrypt/live/postal.altisinfonet.in/privkey.pem
```

I've 2 suggestions
1. I think when certbot renews license, postal didn't pick it up. Try to restart postal and check it again.
2. If first suggestion didn't work, your Let's Encrypt license could be validated through TLS-SNI validation. I received email about it has reached end of life support and deprecated. If that's the case try to recreate new license with http01 or other validation method.

Let us know what was the case for you.

**Comment by pradiptac** [comment]
1. I have restarted postal several times.No result.
2. It is a brand new postal server.Just yesterday I have created the certificate.The same certificates are working successfully for web.
Any other suggestions?

**Comment by shinebayar-g** [comment]
Make sure postal user has access to those files.

**Comment by willpower232** [comment]
Under `smtp_server` you should only need to configure `tls_enabled` and the two paths. The other defaults should be sufficient.

You can also have a look at https://github.com/atech/postal/issues/479#issuecomment-362085834 for testing the SSL output of your Postal server.

**Comment by pradiptac** [comment]
> 
> 
> Under `smtp_server` you should only need to configure `tls_enabled` and the two paths. The other defaults should be sufficient.
> 
> You can also have a look at [#479 (comment)](https://github.com/atech/postal/issues/479#issuecomment-362085834) for testing the SSL output of your Postal server.

**Comment by pradiptac** [comment]
My postal.yml 

smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.altisinfonet.in/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.altisinfonet.in/privkey.pem
  tls_ciphers: TLSv1_1
  ssl_version: TLSv1_1
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14

result of  "openssl s_client -connect postal.altisinfonet.in:25 -starttls smtp"
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 142 bytes and written 209 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1556375258
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
 What should I check? My postal web ssl status is ok

**Comment by willpower232** [comment]
If the certificate files exist at that location and are accessible by the postal system user, have you restarted Postal since applying the configuration?

**Comment by pradiptac** [comment]
I have restarted several time but not solved.How to check those files are accessible by the postal system user or not?

**Comment by shinebayar-g** [comment]
> Make sure postal user has access to those files. Login as postal user and try to view certificate files.

this

**Comment by willpower232** [comment]
The terminal command `sudo -iu postal` will put you into the postal user.

**Comment by pradiptac** [comment]
After running the above command I can run nano and see the content of both the certificates
