### ISSUE TITLE
enable IP Pool message in Queue always pending status

### ISSUE THREAD

**Issue by yourihua** [postalhq/postal#801]

**Comment by yourihua** [comment]
enable IP Pool message in Queue  always pending status, How should I solve it?

**Comment by yourihua** [comment]
![image](https://user-images.githubusercontent.com/42401769/56864160-ba96f180-69f1-11e9-88ab-20a333b2c7d9.png)

**Comment by yourihua** [comment]
if i delete all ip from table ip_addresses, and remore all message from queue. and go on sent email, it looks normal again.

**Comment by ankitsamarthya** [comment]
Hi @yourihua,
Did you solve this issue? I am also getting the same issue with IP pools. See #804

**Comment by joltcan** [comment]
Same here. When I disabled the pool it worked. I have a theory that the IP pool IP's has to be bound to your host for them to work, but I haven't had time to test it yet.

**Comment by joltcan** [comment]
Indeed, I had time, so I tested it. If the IPs are bound to the server, then the IP pool seems to work. I have internal IP's NATed to external, so I had to use the internal IP's in the pool, and they had to be available on the server network interface.
