### ISSUE TITLE
Postal Credentials - SMTP Validation Error on Mailwizz

### ISSUE THREAD

**Issue by lovelyns** [postalhq/postal#806]
I keep getting error whenever I try to connect to Mailwizz with Postal SMTP credentials. I am able to send test messages perfect but SMTP is not working. Could you please help? @willpower232  @catphish 
![PhotoGrid_1557035420154](https://user-images.githubusercontent.com/50284956/57189133-75e3ec80-6f02-11e9-90fa-b0eba1e77bf0.jpg)

**Comment by willpower232** [comment]
Make sure your server provider is allowing you to connect on presumably port 25 and that you have no firewall in the way.

**Comment by lovelyns** [comment]
The server provider where postal is hosted had earlier confirmed to me when I contacted them that they did not block any port on my server.

Is it possible that the server provider where Mailwizz is hosted block the port 25?

Again I am yet to get Certbot SSL certificate, could that be the reason?

**Comment by lovelyns** [comment]
In addition ufw is disabled already

**Comment by willpower232** [comment]
> Is it possible that the server provider where Mailwizz is hosted block the port 25?

Yes this is possible, definitely worth confirming before proceeding.

> Again I am yet to get Certbot SSL certificate, could that also be the reason?

The error you're getting is a timeout which implies Mailwizz is unable to even begin talking to Postal so it hasn't got to the SSL stage yet. This should be resolved before you're using it properly but isn't the issue right now.

**Comment by lovelyns** [comment]
Thanks for your response @willpower232

I have been able to connect using the IP address and not the server domain which I was using before. i think the connection problem is because the server domain is listed on Spamhaus.
======================
This last one please, the newsletter I sent out went to about 3000 emails but close to 24hours since I have sent it I observed that just 50 has been sent out while others are still on Soft Fail.

I have increased workers to 10 and all records of the domain I am using to send are verified 

What do you think I can do to help my delivery rate?

**Comment by catphish** [comment]
> the server domain is listed on Spamhaus

You're not going to get very far if your domain / server / network has previously been used to send spam. I'd address this first.

**Comment by lovelyns** [comment]
@catphish do you mean this is the reason for very low sent emails? If yes, would you suggest that I get additional IP?

Note also that the verified domain that I am using to send newsletter is different from the server domain where postal is hosted.

**Comment by catphish** [comment]
> would you suggest that I get additional IP?

Having your server's domain on any blacklist suggests an underlying problem that needs to be addresses before sending any more email. I can't really be more specific, but you need to find out why it was blacklisted and address the root cause.

**Comment by lovelyns** [comment]
this is my server domain **postal.mydomain.com** where postal is hosted =>it is not on blacklist

but **mydomain.com** the main domain hosted elsewhere is on blacklist

Any problem with that @catphish ?

**Comment by lovelyns** [comment]
Hello @catphish

This is the error message I am getting on most of the Soft Fail messages though the IP is relatively new;

421 4.7.0 [TSS04] Messages from 209.160.21.198 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html

Time: 0.12s

Support Ref: BXQQSZWH

**Comment by willpower232** [comment]
Until you can remove yourself from whatever blacklists you're on, you will probably see plenty of errors like that.

https://mxtoolbox.com/ will help you see which blacklists you are on and you can work with the blacklists to get yourself cleared.

**Comment by lovelyns** [comment]
Thanks a lot @willpower232

My IP is already free from blacklist.

My concern is this @catphish comment below......emphasis on previously
> You're not going to get very far if your domain / server / network has previously been used to send spam.
