### ISSUE TITLE
Import Data in Postal

### ISSUE THREAD

**Issue by hamed69r** [postalhq/postal#811]
Hi
I used Zoho mail server and i want to migrate to Postal mail server.
I installed Postal and i export all of my data from Zoho mail server.
Anyone know, how can i import my data in Postal mail server ?

**Comment by tchwpkgorg** [comment]
Postal is just a SMTP server with some added functionality (DKIM signing, GUI etc.).

There isn't really nothing to migrate (SMTP credentials maybe? please elaborate on what you want to do).
