### ISSUE TITLE
does postal try IPv4 if IPv6 fails?

### ISSUE THREAD

**Issue by tchwpkgorg** [postalhq/postal#813]
I have a recipient with an MX which has both IPv4 and IPv6 addresses.

Unfortunately their IPv6 address does not work; IPv4 does work. This results in Postal being unable to send mail there - first, there are 18 soft fails for all mail sent to @wsys.inf.br addresses; eventually, this turns into a hard fail with "too many soft fails" reason.

This means that unfortunately Postal will try IPv6, but will not fall back to IPv4 if it's unable to connect on a network level (timeout, connection refused; obviously it shouldn't try to fall back to a different protocol if there are SMTP session errors).

I think there are a lot of broken IPv6 setups out there and postal should be able to handle such cases (most MTA software do).

Below, DNS resolving and probes with telnet to port 25:

```
# host -t MX wsys.inf.br 
wsys.inf.br mail is handled by 5 mx-vip-01-farm64.kinghost.net.
wsys.inf.br mail is handled by 5 mx-vip-02-farm64.kinghost.net.

# host mx-vip-01-farm64.kinghost.net.
mx-vip-01-farm64.kinghost.net has address 177.185.200.35
mx-vip-01-farm64.kinghost.net has IPv6 address 2804:10:4064::200:35

# host mx-vip-02-farm64.kinghost.net
mx-vip-02-farm64.kinghost.net has address 177.185.200.36
mx-vip-02-farm64.kinghost.net has IPv6 address 2804:10:4064::200:36

# telnet 2804:10:4064::200:35 25
Trying 2804:10:4064::200:35...
telnet: Unable to connect to remote host: Connection timed out

# telnet 2804:10:4064::200:36 26
Trying 2804:10:4064::200:35...
telnet: Unable to connect to remote host: Connection timed out
```

IPv4 works correctly:

```
# telnet 177.185.200.35 25
Trying 177.185.200.35...
Connected to 177.185.200.35.
Escape character is '^]'.
220-mx-node-05-farm64.kinghost.net ESMTP
```

**Comment by willpower232** [comment]
I believe that Postal won't be able to distinguish between ipv4 and ipv6 from an error point of view.

If a large amount of your recipients are affected you can disable or remove ipv6 from your entire server depending on your provider, see https://github.com/atech/postal/issues/435

Alternatively, you could discuss the matter with your recipient to see what they can do.

**Comment by tchwpkgorg** [comment]
Above suggested workaround, I'd suggest fixing the issue in Postal (i.e. by randomizing the IPs returned by DNS) :)

**Comment by tchwpkgorg** [comment]
Note there is a standard algorithm to deal with the case of several IP addresses (IPv4 or IPv6) when some are unresponsive; in RFC 8305 https://www.rfc-editor.org/info/rfc8305

**Comment by willpower232** [comment]
Good to know, I'm not sure how implementable that is, one for @catphish for an official perspective

**Comment by catphish** [comment]
> you can disable or remove ipv6 from your entire server depending on your provider, see #435

Don't do this :slightly_frowning_face:  We're supposed to be encouraging IPv6 deployment!

Like most software, Postal is designed to try IPv6 first, then fall back to IPv4. It should do this for each MX server in turn. Are you able to get an extract from the SMTP sender log when this fails? It should show an error for each IP it tries and fails to connect to.

Relevant code is here: https://github.com/atech/postal/blob/ed7889a40e1d777f1d80821043562ab18b04766e/lib/postal/smtp_sender.rb#L33
