### ISSUE TITLE
Sending Message is so slow.

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#818]
Hello Team,

I have sending email using postal before 4-5 days but they still in  queue or held. so may i know the reason of this issue. and message rate is showing  0.00 messages/minutes.

Seen the below attachment.
![Screenshot_15](https://user-images.githubusercontent.com/46315368/58325288-dd78c200-7e46-11e9-910c-899ab1939a49.png)

Thanks In Advance
Zeba Parveen

**Comment by willpower232** [comment]
Can you use `postal status` on the command line to make sure that everything is running okay?

**Comment by zeba121** [comment]
yes, can run this command please see this

root@ns101022:~# postal status
Procodile Version   1.0.22
Application Root    /opt/postal/app
Supervisor PID      4057
Started             2019-05-24 07:33:01 -0400

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      07:33        pid:4063     respawns:0
   port:-        tag:-

|| worker
|| Quantity            8
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      07:52        pid:4875     respawns:0
   port:-        tag:-
|| => worker.2         Running      07:52        pid:4877     respawns:0
   port:-        tag:-
|| => worker.3         Running      07:52        pid:4879     respawns:0
   port:-        tag:-
|| => worker.4         Running      07:52        pid:4881     respawns:0
   port:-        tag:-
|| => worker.5         Running      07:52        pid:4883     respawns:0
   port:-        tag:-
|| => worker.6         Running      07:52        pid:4885     respawns:0
   port:-        tag:-
|| => worker.7         Running      07:52        pid:4887     respawns:0
   port:-        tag:-
|| => worker.8         Running      07:52        pid:4891     respawns:0
   port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      07:33        pid:4089     respawns:0
   port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      07:33        pid:4092     respawns:0
   port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      07:52        pid:4864     respawns:0
   port:-        tag:-
root@ns101022:~#

Thanks & Regards
Zeba Parveen

**Comment by tchwpkgorg** [comment]
Can you check the held messages, click on a couple of them? They should see a reason why they are delayed.

**Comment by tchwpkgorg** [comment]
24% bounce rate?! Something's definitely not right with your setup.

**Comment by zeba121** [comment]
see this held message error:-

**Comment by zeba121** [comment]
24% bounce rate?! Something's definitely not right with your setup.

how can i solve this?




<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by willpower232** [comment]
This sounds a little like #287

**Comment by zeba121** [comment]
Hello Team

Can You Help me How to Secure my postal with using SSL TLS.

Thanks In Advance
Regards
Zeba Parveen

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by willpower232** [comment]
Do you mean using HTTPS on the UI? You'll need to update your nginx configuration with a valid certificate.

If you meant securing your SMTP, you'll have to update the Postal config file with a valid certificate in the `smtp_server` section.

**Comment by zeba121** [comment]
Hello Team,

We have already configure in both files but it is not proper working
properly.
when we login with hostname so it is showing a https secure, But when we
login with ip address it is showing https not secure.

Please Reply me As Soon as possible.

Please seen the below error:-

Error: OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0
state=SSLv2/v3 read server hello A)


Thanks & Regards
  Zeba Parveen

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by willpower232** [comment]
> when we login with ip address it is showing https not secure

Your SSL certificate will only be valid for the hostname. It would be better to only use the hostname for logging in.

**Comment by zeba121** [comment]
Ok Thank You for replaying me.

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zeba121** [comment]
Hello Team,

how can i add my secondary storage in my server without affecting to postal
server.

Please seen the below statements:-
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           780M  8.7M  771M   2% /run
/dev/sda1        78G   78G     0 100% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sdb1        99G   60M   94G   1% /mnt/disk
tmpfs           780M     0  780M   0% /run/user/0


Thanks


<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zeba121** [comment]
Hello Team,

we have add a additional hard disk  in our vps server.

But how can i redirect hard disk sda1 from sdb1.

We want to if our 1st hard disk (sd1) storage is full then our server is
automatically redirect from 2nd hard disk (sdb1).

Please answer me as soon as possile.

Thanks & regards
Zeba Parveen

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=0e74b438-8226-41cd-9622-be5b5c512418>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by willpower232** [comment]
> how can i add my secondary storage in my server without affecting to postal server.

Postal won't have any bearing on how you manage storage on your server.

> We want to if our 1st hard disk (sd1) storage is full then our server is automatically redirect from 2nd hard disk (sdb1).

This is not possible as far as I know.

You will have to identify what is using up all the hard drive space and manage that better.

You should also consult a more local linux administrator as managing your server is beyond the scope of relevant support here.
