### ISSUE TITLE
SPF Record for Added Domain Can't Be Verified.......How to Remove example.com

### ISSUE THREAD

**Issue by lovelyns** [postalhq/postal#820]
I newly installed Postal but instead of the domain to be verified what it is displaying is example.com

See the screenshot here https://ibb.co/r6LhFxv

Please how can I change it to the domain I want to verify

**Comment by willpower232** [comment]
This is probably because you haven't changed it in the `postal.yml` config file. If you update this file and restart Postal, that should clear it.

**Comment by lovelyns** [comment]
Thanks @willpower232
