### ISSUE TITLE
Override target server for some mail

### ISSUE THREAD

**Issue by msiegenthaler** [postalhq/postal#828]
One of our mail recipients has a special "secure" mail server (SMTP with forced TLS) that they want us to use instead of their normal mail server (as advertised by MX). They use this special mail server to ensure that sensitive messages never get relayed outside of the sender/receiver.

Is there a way to override the target server per domain inside postal? At the moment we are doing it with a postfix with an entry in /etc/postfix/transport (`$DOMAIN  smtp:$HOST:$PORT`), but we'd like to get rid of postfix and only use postal.

**Comment by willpower232** [comment]
This is a bit advanced for Postals functionality but I believe it does support outbound relays so you could maintain your use of Postfix but relay Postals messages through it.

Have a look at adding some config to your Postal.yml like this:

https://github.com/atech/postal/blob/1adedc6343044fedee76aaf928efccd45d32e15f/config/postal.defaults.yml#L66-L70

Have a look at https://github.com/atech/postal/issues/48#issuecomment-298029954 for more details
