### ISSUE TITLE
How To Use IPv6 in Postal ???

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#836]
Hello Team,

I am trying to connect sending emails while using IPv6 but it cannot send mail using IPv6.
It continuously sending mail to my host IP and I am also bind the IPv6 in the network file but it cannot use IPv6 if i am trying to sending mails so it shows the mails in pending .
And i want to send Emails using IPv6 .
Is there possible or not?? 

thanks in advance

**Comment by willpower232** [comment]
It should be possible if your server has a working IPv6 connection to the internet and the receiving servers are also IPv6 enabled. Can you share screenshots of what you're seeing?

**Comment by timraybould** [comment]
@zeba121 Is your server on Digital Ocean? https://ideas.digitalocean.com/ideas/DO-I-1366

**Comment by zeba121** [comment]
Hello @willpower232 

Sorry For the late reply.

Please check the following link:-
https://pastebin.com/usa3h5XF

Thank You

**Comment by zeba121** [comment]
Hello @timraybould 

My server is not on a Digital Ocean.

**Comment by zeba121** [comment]
Hello @willpower232 

ipv6 is pinging but when i am sending a mail through postal but they landing in pending or not sent.

please see this:-
root@vpsXXXXX:~# ping6 -c5 XXXX:XX00:XXX:X000::XXX
PING XXXX:XX00:XXX:X000::XXX(XXXX:XX00:XXX:X000::XXX) 56 data bytes
64 bytes from XXXX:XX00:XXX:X000::XXX: icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from XXXX:XX00:XXX:X000::XXX: icmp_seq=2 ttl=64 time=0.055 ms
64 bytes from XXXX:XX00:XXX:X000::XXX: icmp_seq=3 ttl=64 time=0.057 ms
64 bytes from XXXX:XX00:XXX:X000::XXX: icmp_seq=4 ttl=64 time=0.064 ms
64 bytes from XXXX:XX00:XXX:X000::XXX: icmp_seq=5 ttl=64 time=0.075 ms

--- 2607:5300:201:3000::391 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 3997ms
rtt min/avg/max/mdev = 0.055/0.064/0.075/0.010 ms

Please response me as soon as possible.

**Comment by willpower232** [comment]
If your messages are still pending, have you checked `postal status` to guarantee that everything is running as it should? If you were experiencing network problems, the messages would have failed rather than still being pending.

**Comment by zeba121** [comment]
Hello @willpower232 

See my postal status:-

root@vps121528:~# postal status
Procodile Version   1.0.23
Application Root    /opt/postal/app
Supervisor PID      24737
Started             2019-07-15 05:35:45 -0400

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      05:35        pid:24743    respawns:0      port:-        tag:-

|| worker
|| Quantity            4
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      05:35        pid:24745    respawns:0      port:-        tag:-
|| => worker.2         Running      05:35        pid:24747    respawns:0      port:-        tag:-
|| => worker.3         Running      05:35        pid:24750    respawns:0      port:-        tag:-
|| => worker.4         Running      05:35        pid:24753    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      05:35        pid:24756    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      05:35        pid:24758    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      05:35        pid:24762    respawns:0      port:-        tag:-

**Comment by willpower232** [comment]
Looks like everything is running fine so its possible you were previously having some problems and the messages got locked by another process which isn't around any more, have a look at https://github.com/atech/postal/issues/287#issuecomment-367293435

**Comment by zeba121** [comment]
Hello @willpower232 

when we assigned ipv6 address then emails are pending in a mail queue.
But we assigned Ipv4 address emails are sent properly.

![image](https://user-images.githubusercontent.com/46315368/61442729-cbf2f880-a965-11e9-969b-d1cd1451ecf7.png)

**Comment by zeba121** [comment]
hello @willpower232 

its done thanks for help.

**Comment by willpower232** [comment]
It might be worth googling that particular message, I know a couple of others have had similar messages (#468 and #847)
