### ISSUE TITLE
Disabling DKIM signing

### ISSUE THREAD

**Issue by ahmedaldabbagh** [postalhq/postal#846]
Hi all,

I am aware that a DKIM record should be used to improve deliverability. However, some of our customers who want mails dispatched on their behalf have have not set the DKIM nor Return Path records. Only the SPF records are used correctly.
Of course we have advised our customers to set these records (DKIM and Return Path) to ensure delivery. But our recommendations have not been fully considered.

Sending out messages with a DKIM signature using the private key would make the server on the receiving end check for a public key.

My question in 2 parts:

1. Is it possible to disable signing messages with the DKIM key? 

2. Or Is there no need to disable it when sending a message with a DKIM signature (using the private key) and having no public key in the DNS record?

Thank you for the input in advance!

**Comment by willpower232** [comment]
I doubt there would be much interest in providing a feature to turn off DKIM signing as it is an important feature for email as a whole but, as per #339 and #559, the actual necessity for valid, working DKIM seems to be varied but obviously it is always better to include it where you can.

The Postal provided DKIM and Return Path records shouldn't conflict with an organisations main DNS records (or shouldn't do) so if your customer is refusing to add the extra records and complains about deliverability, they have only themselves to blame unless you have access to their DNS to add the records yourself.

**Comment by ahmedaldabbagh** [comment]
thanks for the input @willpower232 .
totally agree with your view regarding the DNS records.

**Comment by marcoxyz123** [comment]
Hi all 
It is important that especialy if I would use a relay server.
In case of outgoing milter processing it is also neccesary that the fields for signing are editable (date:from:to:message-id:subject:mime-version:content-type:content-transfer-encoding;).

Fore example if I rewrite the Subject after send to the relay Server the DKIM fails.

Best regards,
Marco

**Comment by ssdrosos** [comment]
Hi @willpower232 ,

We are also in a place where we need to have the DKIM signing off. We have setup postal to forward any emails it receives to an SMTP relay that takes care of the email deliverability.

Ideally, we need the following option to be available:

```
dns:
  dkim:
    # Set this to false to disable DKIM signing
    enable: false
```

Is this something that we could put back on the map?
