### ISSUE TITLE
Accidentally deleted the postal.yml file - need rails secret_key

### ISSUE THREAD

**Issue by gtmadev** [postalhq/postal#847]
Using the up arrow key and editing the wrong command, I accidentally deleted the postal.yml file. I should.. but I don't have a backup of it. Lesson learned...

I have pretty much all of the values needed to recreate it. But.. I am wondering where I can find the rails: secret key. I think that gets created upon initialization. Is it in a table in the database? Some conf file in rails?

**Comment by gtmadev** [comment]
It seems as if I can just run `postal initialize-config` again and then just fill in the same settings I used before. I was looking at some of the source code, and it doesn't look like it uses the secret as an encryption key or anything. Maybe it's just an internal validation key??

Anyway... I am about to trigger a restart (with the new postal.yml)... with fingers crossed.

**Comment by gtmadev** [comment]
kay... seemed like everything was okay, but not... I am getting this when running `postal run`

`EAFNOSUPPORT: Address family not supported by protocol - socket(2) for "::" port 25`

I didn't change anything else on the server. Only the config file got deleted. I have no idea what this is all about. I am reading other threads making mention of this being some kind of ipv6 issue. But why didn't this show itself before?

**Comment by gtmadev** [comment]
Okay.. looks like this is resolved. I followed the idea in the following comment...

https://github.com/atech/postal/issues/435#issuecomment-354847432

Not sure why I had to do this. The server does have ipv6 enabled. But for some reason, the smtp server can't bind on it. So, my workaround was to force it on ipv4 0.0.0.0 (per the comment above).

I guess I just need to remember to make that edit again if I upgrade or pull from the repo.

**Comment by willpower232** [comment]
As you surmised, the `secret_key` is part of Rails not the application so if it gets changed, I think the worse that might happen would be users being logged off.

Interesting error about no support for IPv6, it might have been a pending server/daemon restart or something if it was working properly before or perhaps there was already something else trying to use that port.

Do you still experience that error after restarting the server?

**Comment by gtmadev** [comment]
Some things I did try...

1. I changed ports. 
2. I tried adding a host with a port (for smtp_server).
3. I tried host: 0.0.0.0 and also 127.0.0.1, and just localhost.
4. I tried without any smtp_server entry in the yml file (defaults)
5. I tried removing the ip6 entries in the hosts file

Ultimately, from what I have read on other Ruby forums, it's an issue with ipv6 on my server. Previously, the postal server did fine on restarts of the app. I don't recall the last time the server was rebooted though. After I had the ipv6 issues, I applied all ubuntu updates to see if that would clear things up. But after applying and a reboot, the postal server gave the same error on `postal run`.

At that point, I decided to just opt for the small code mod I referenced in my previous comment. I was pretty sure that would work, and it did.

FYI.. this is a Digital Ocean instance running the latest Ubuntu. I believe private network is also enabled, but I don't think it's being used at this point. I run most of my instances with another provider. And now that the ip has pretty good reputation, I don't want to move it. It's been running stable for quite some time now. I may, at some point, perform a "reinstall" on the DO instance, but that will require a window of downtime while I rebuild postal and restore data from a backup. I don't know that I want to do something like that right now though.

So, for now, I will just implement the way I have it and I have made a note in my app notes folder about the code change - which will be required on upgrades.

**Comment by gtmadev** [comment]
Okay... I just now saw this... I bet this is the issue with DO.

https://github.com/atech/postal/issues/836

**Comment by willpower232** [comment]
Thanks for your thoroughness. Personally (and I think in other issues here), people have had issues with DO and IPv6 and not experienced them on other providers servers so best to keep yourself as stable as possible for now until some official conclusion can be found.

Fortunately in this case, updates are few and far between, you should be able to continue as you are for a while yet.
