### ISSUE TITLE
fast_server log location

### ISSUE THREAD

**Issue by epipheus** [postalhq/postal#854]
I don't see logs for the fast server. As best as I can ascertain, it should be /opt/postal/log/puma.fast.log. 

I don't have any logs for it.  I've even touched the above file.  No love. 

What am I missing?

**Comment by DTS-Mike** [comment]
What are you looking for in a log?  I have found process related to fast server in the puma.log

**Comment by epipheus** [comment]
I'm looking for any hint why fast_server is failing.  my puma.log doesn't really have anything useful in it.

**Comment by pjv** [comment]
in `/opt/postal/log/`,  doing `cat * |grep -i fast` gives me crickets. Fast server fails with no trace for debugging.

**Comment by willpower232** [comment]
Please see https://github.com/atech/postal/issues/851#issuecomment-513218504
