### ISSUE TITLE
502 Bad Gateway nginx/1.10.3 (Ubuntu) - server does not start

### ISSUE THREAD

**Issue by visomymail** [postalhq/postal#858]
after installation, after reboot the server does not start
look errors in tail -f /var/log/nginx/error.log
I see some connection attempts
`2019/07/28 07:54:36 [error] 695#695: *322 connect() failed (111: Connection refused) while connecting to upstream, client: 46.229.168.130, server: postal.yourdomain.com, request: "GET /j08t/86365.php?112738.html HTTP/1.1", upstream: "http://127.0.0.1:5000/j08t/86365.php?112738.html", host: "vremonte.kiev.ua"
2019/07/28 07:54:39 [error] 695#695: *325 connect() failed (111: Connection refused) while connecting to upstream, client: 46.229.168.140, server: postal.yourdomain.com, request: "GET /U5iDg2P/29879.php?85889.html HTTP/1.1", upstream: "http://127.0.0.1:5000/U5iDg2P/29879.php?85889.html", host: "vremonte.kiev.ua"
`

I see that someone is trying to send something, but the server and the domain is new, this can not be.

**Comment by visomymail** [comment]
error above after installation https://github.com/atech/postal/wiki/Quick-Install

I tried to put everything separately, now everything has started, but I can not access the admin area, display the page Welcome to nginx!

**Comment by willpower232** [comment]
`postal status` will confirm that each part of Postal is running appropriately.

You will have to make Postal start with the server at boot (some tips are [in the wiki](https://github.com/atech/postal/wiki/Starting-on-boot)). This is not part of the install process.

If Postal is running but you can't get to it via nginx, your install process may not have updated the nginx configuration. You should find that the `/etc/nginx/sites-enabled/default` file resembles the [one in this repo](https://github.com/atech/postal/blob/master/resource/nginx.cfg).
