### ISSUE TITLE
How to using organization domain ?

### ISSUE THREAD

**Issue by losingle** [postalhq/postal#860]
How do I use the organization domain to send mail?
What should best practices look like?

**Comment by willpower232** [comment]
Admittedly there isn't really a user guide haha.

Basically, you'll need to add the domains you want to send from in the UI. The domain pages have instructions about what DNS records you'll need (as long as you have set up the domain names correctly and entered them in `postal.yml`).

Once the domains are added and verified, then you can create credentials to allow you to use Postals API or SMTP to send the messages from your application.

As for best practices, you'll get the best experience if SPF, DKIM, and Return Path are all set up for the domains you add. Postal should be able to send any valid email message you give it.

**Comment by losingle** [comment]
I thought only Chinese people would laugh at the haha 😊
What is the difference between the DNS configuration in postal.yml and organization domain ?
Actually, I'm at a loss

**Comment by willpower232** [comment]
`postal.yml` is how the entire Postal application is set up. You need to tell Postal the domain names that refer to the server, what ports and certificate to use amongst other bits of information.

The organizations are for you configuring and grouping other applications that use Postal to send their emails.

**Comment by losingle** [comment]
Another thing I don't understand is the IP pools
What is the relationship between IP pools and mail services?
I actually configured the IP pools with the domain name and IP address,
But I still need to configure the mail service,
This is a little hard to understand from a product perspective

**Comment by willpower232** [comment]
IP Pools are for when you have multiple IP addresses and want to specifically send certain organizations mail using those specific IP addresses.

You mentioned in a previous issue that you weren't able to have multiple IP addresses on your server so you probably won't need to make use of the feature.

Without IP Pools, Postal will send from any IP address available on the system which isn't a problem if you only have the one!
