### ISSUE TITLE
Attempting to resend messages held due to sending rate limit - console crashes.

### ISSUE THREAD

**Issue by CodeCompilerArizona** [postalhq/postal#862]
Using the following code via **postal console**
`server = Organization.find_by_permalink('saveoncbd-gq').servers.find_by_permalink('saveoncbd-gq')
server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }`

Results in the following
`root@localhost:~# postal console
Loading production environment (Rails 5.2.2.1)
irb(main):001:0> server = Organization.find_by_permalink('saveoncbd-gq').servers.find_by_permalink('saveoncbd-gq')
=> #<Server id: 1, organization_id: 1, uuid: "1b83b401-3ba3-4d4a-8fa3-34620f791a9b", name: "saveoncbd.gq", mode: "Live", ip_pool_id: nil, created_at: "2019-07-28 21:02:15", updated_at: "2019-08-04 22:43:52", permalink: "saveoncbd-gq", send_limit: 108, deleted_at: nil, message_retention_days: 60, raw_message_retention_days: 30, raw_message_retention_size: 2048, allow_sender: true, token: "zyqesk", send_limit_approaching_at: nil, send_limit_approaching_notified_at: nil, send_limit_exceeded_at: "2019-08-04 16:26:52", send_limit_exceeded_notified_at: nil, spam_threshold: #<BigDecimal:6e916b8,'0.5E1',9(18)>, spam_failure_threshold: #<BigDecimal:6e915c8,'0.5E2',9(18)>, postmaster_address: nil, suspended_at: nil, outbound_spam_threshold: nil, domains_not_to_click_track: nil, suspension_reason: nil, log_smtp_data: false>
irb(main):002:0> server.message_db.messages(:where => {:held => 1, :scope => 'outgoing'}).each { |m| m.add_to_message_queue(:manual => true) }
  MessageDB Query (1.14s)   SELECT * FROM `postal-server-1`.`messages` WHERE `held` = '1' AND `scope` = 'outgoing'
/usr/bin/postal: line 19: 29303 Killed                  sudo -u postal bundle exec rails console
`

I have no idea why its popping "Killed" ect. Why wont this run? I've had this EXACT command load and work functionally on other postal installations.

**Comment by willpower232** [comment]
Do you know how many messages you are trying to resend? It might be that you're using too much memory and your OS is killing the process to save it.

**Comment by catphish** [comment]
"Killed" means the machine ran out of memory and the OS killed it. This happened because it tried to load too many messages into memory at once. It should be possible to limit the number of messages loaded at once, or iterate over them, loading one (or a batch) at a time. I don't have the command to hand but you might try adding a `limit` to the query like this:
...`.messages(:limit => 1000, :where`...
