### ISSUE TITLE
Gsuite/iCloud Sending

### ISSUE THREAD

**Issue by danthegoodman1** [postalhq/postal#865]
Somewhat related to #856 , I am having trouble sending messages to other mail services, getting errors like:
![image](https://user-images.githubusercontent.com/17806508/62635017-dec57100-b904-11e9-8792-0afb0a96c451.png)
for both gsuite and icloud (different mx domains for icloud appear)

When sending to something like mail-tester.com it sends instantly, what could be the issue?

**Comment by willpower232** [comment]
Are you seeing the same "no smtp servers" error for icloud?

It suggests those providers are blocking your IP address rather than silently dropping your mail like #827 

Have you checked block lists with mxtoolbox.com?

**Comment by danthegoodman1** [comment]
@willpower232 The domain nor the IP is in the blocklist. I am using DigitalOcean for reference. I wonder would using an smtp relay work? If so where is there more extensive documentation that the postal.defaults.yml file? Thanks.

**Comment by willpower232** [comment]
Interesting, IIRC I think we've been caught by the same block list which apparently isn't mainstream enough to appear on mxtoolbox.

They've given you a link to visit so you might be able to appeal and get yourself off that particular list.

Regarding google, have you got reverse DNS set up and all the other records in place?

**Comment by danthegoodman1** [comment]
@willpower232 I've appealed to their blocklist, hope to hear from them soon. As for GSuite I've got reverse DNS setup and stuff like mail-tester.com gave me a perfect 10/10 score for some test emails (everything above 9/10). If you'd like to see the records I'd be willing to share them more privately. I've set everything up accord to the "Add Domain" menu in the control panel. I've added nothing so far for ipv6 though.

**Comment by willpower232** [comment]
Hope it works out, alas if Google is outright blocking you, you might have to try an alternate server provider or another country/region within your current provider to see if that improves it.

**Comment by catphish** [comment]
This is sometimes caused by trying to send from a server that has IPv6 connectivity, but a service provider that blocks SMTP on IPv6. It should fall back to IPv4, but worth checking.

**Comment by nmanley** [comment]
Here is a tool I frequently use.

https://www.talosintelligence.com/reputation_center
