### ISSUE TITLE
click & open tracking for sent e-mails from free yahoo/hotmail mailboxes through SMTP relay

### ISSUE THREAD

**Issue by wokawoka** [postalhq/postal#870]
I'm looking to install postal soon in order to use it for the messages of my own domains. Great project!

I was also wondering if by chance it was possible to set up and use postal as SMTP relay in order to track click & open for messages sent from free e-mail providers such as yahoo or hotmail in a similar way as [bananatag](http://bananatag.com/hub/new-email-tracking-with-smtp-relay-from-bananatag/) or [saleshandy](https://help.saleshandy.com/article/98-how-do-i-connect-my-email-account-via-smtp-method) would allow me to do. 
In the case of these two freemium services the tracking is possible but the need to pass them my mailbox credentials in order to let them authenticate and relay to yahoo/hotmail SMTP server with my account feels an extremely high price to pay to me, and for this privacy reasons I was looking for a self-hosted solution.

I tried to go through the postal documentation and search on the past issues here on github and it looks like that the webserver that listens to the connections for the tracking is by default on the same domain of the e-mail boxes (which is something that would not work with a free yahoo or hotmail address) and that SMTP relay with autenthication is not supported (at least until some time ago).

Could you guys confirm that what I would like to achieve is not possible?
Thank you again and keep up with the great work

**Comment by willpower232** [comment]
Those services appear to allow you to send messages through their services via your usual email provider to apply their functionality.

Postal provides email sending and receiving services to other applications. With some customisations, you may be able create the setup you want however you would have to make some changes to how Postal functions to allow you to use the domains you can't add normally to Postal (like yahoo.com) and authenticate against their SMTP servers.

Theres no guarantee that any of this would work and it would make updating Postal difficult so if this functionality is what you need, you may be better off getting your own domain name to send emails from so you can use Postals tracking in the more standard ways.

**Comment by wokawoka** [comment]
Thank you for replying.

Yes, there are no problems for me in using postal with my own domains, I just wanted to try using it to also track (while keeping my data completely private) the e-mail that I send from some free personal e-mail boxes that I'm still using.

I'll try to experiment and see if I can dig a little bit through the code with a friend to see if customizing it for that purpose is doable.
