### ISSUE TITLE
Read tracking use real IP

### ISSUE THREAD

**Issue by criskolkman** [postalhq/postal#875]
Hello,

I have Postal and everything is working fine.
Only thing I would like to see is the users real IP address instead of my firewall's IP address (yes I have setup Postal behind a firewall).

**Message Viewed**

**Opened from 192.168.200.250 (Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy))**
Note that the **Opened from** shows the internal IP address for my firewall (Sophos UTM).

This means that Postal should check the **X-FORWARDED-FOR** header to get the real IP address.
Is there any way to achieve this?

**Comment by willpower232** [comment]
I'd definitely call this a bug however I'm not sure precisely how or where to fix it so definitely a question for a ruby developer or atech themselves

**Comment by dragoangel** [comment]
@lucaspiller thanks for fix, tested it - it works.
But actually X-Forwarded-For can't be trusted from everyone and can contain multiply IPs (Lucas fix check first IP from all) or have another name, e.g.: X-Real-IP, CF-Connecting-IP, etc. To be really correct this part need to be configurable thou the UI and has:
trusted IPs from which try to get real IP
real IP header to check
recursive check for trusted ip.

For Postal UI Nginx can be easily configured by display valid IPs:
real_ip_header X-Forwarded-For;
set_real_ip_from 192.168.1.1;
