### ISSUE TITLE
error during postal initilize

### ISSUE THREAD

**Issue by harshweo** [postalhq/postal#877]
root@mail:~# postal initialize
Initializing database
rake aborted!
ActiveRecord::ProtectedEnvironmentError: You are attempting to run a destructive action against your 'production' database.
If you are sure you want to continue, run the same command with the environment variable:
DISABLE_DATABASE_ENVIRONMENT_CHECK=1
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:61:in `check_protected_environments!'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <top (required)>'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)

**Comment by willpower232** [comment]
Is this the first time you have run `postal initialize`? Have you only just installed?

**Comment by harshweo** [comment]
yes @willpower232 this is first time when i run postal initialize and got error.

**Comment by willpower232** [comment]
I vaguely remember bumping into this recently, if you're happy to bypass it for your first run you can go `DISABLE_DATABASE_ENVIRONMENT_CHECK=1 postal initialize`

**Comment by peeterma** [comment]
Problem still exists and using "DISABLE_DATABASE_ENVIRONMENT_CHECK=1 postal initialize" does not help.

**Comment by willpower232** [comment]
@peeterma please open  a new issue with some more details about the problems you're experiencing rather than commenting on old ones

**Comment by isiddiquebd** [comment]
error during postal initialize
![image](https://user-images.githubusercontent.com/61184355/114227219-8165ab00-9996-11eb-9521-44d69edbf634.png)
![image](https://user-images.githubusercontent.com/61184355/114227243-8a567c80-9996-11eb-809c-b2a23dba55c9.png)

**Comment by willpower232** [comment]
@isiddiquebd please open a new issue instead of commenting on closed ones

> access denied for user postal@localhost

It sounds like your MySQL server isn't running or you have the wrong details in your configuration file.

**Comment by simarmannsingh** [comment]
If anyone else also followed the official documentation of `postal` and is facing this issue, here's how to solve it.
Old version of postal used to find a DB named as `postal` while the new version of postal doesn't find, rather creates a new database during the initialize step.
However, the documentation is still outdated.

So, to fix it, simply check the container ID of the docker pod running the mariaDB,
```sh
docker ps
...

CONTAINER ID   IMAGE          COMMAND                  CREATED       STATUS       PORTS                                                                      NAMES
<MARIADB_CONTAINER_ID>   mariadb        "docker-entrypoint.s…"   3 hours ago   Up 3 hours   127.0.0.1:3306->3306/tcp                                                   postal-mariadb
```

Then, simply log in to the mariadb using following cmd
```sh

docker exec -it <MARIADB_CONTAINER_ID> mariadb --user root -p<MARIADB_PASWORD>
```

Once inside, drop the database using
```sh
DROP DATABASE postal;
```
Finally exit from there, and re-run the `postal initialize`.
Also, if it works for you, like this so that other's also know it work for everyone.
