### ISSUE TITLE
message held

### ISSUE THREAD

**Issue by davidlou123** [postalhq/postal#879]
when i try to send email if from and to are in the same domain(domain is in the approved list), message go to held messages, is it correct?

**Comment by willpower232** [comment]
If you look at the messages in the Postal interface, you will see why the message has been held.

**Comment by davidlou123** [comment]
the error, i got is the emails is on the suppression list. i checked, the problem is Zoho clients cant receive emails, and i dont now why?

**Comment by willpower232** [comment]
If the email addresses are already on the suppression list, you will have to look at an older message to see the error message it received that caused it to be on the suppression list.
