### ISSUE TITLE
'Sent status' in message details web service

### ISSUE THREAD

**Issue by doctore** [postalhq/postal#882]
Hi

I'm using Postal as external mail server, using the provided API to send emails and receive 'feedback' about what happened with every one. However using the web service:

   `/api/v1/messages/message`  (with `id` as parameter)

I always receive the same `status: success` independently if the email was or not really sent.
If I want to know it, I have to use the web service:

   `/api/v1/messages/deliveries`  (with `id` as parameter)

and iterate through `data` array searching something like `status: Sent`

Is there a more easy way to know it? Why does the first web service not provided it in a new property: `sentStatus` or something like that?

Best regards

**Comment by willpower232** [comment]
Confusingly, the [moonrope](https://github.com/adamcooke/moonrope) library includes the status of the request as one of the return values so you'll see the same entry is `success` in both endpoints and unrelated to the email messages themselves.

I think the status should be already available for the message endpoint but I'm not familiar enough with it to know how to send it in the API response.

**Comment by doctore** [comment]
Hi

No, the following response is a typical one of an email not really sent (due to a failure) by Postal:

`{
    "status": "success",
    "time": 0.0,
    "flags": {},
    "data": {
        "id": 200,
        "token": "WRXjbRnhCmSJ"
    }
}`

I mean using the web service:

   `/api/v1/messages/message` (with `id` as parameter)

Using the other one, you will receive an array in the `data` property with a "useful `status` containing values like: `SoftFail`, `HardFail` or `Sent`. As far as I know, that is the only way you can check if an email was really sent or not.

Although `POST` is not the standard way to receive information, probably it has more sense that the web service that provides the details of a messages includes information about the current status of the "sending operation".

Best regards

**Comment by willpower232** [comment]
What I am saying is that `data` is the result of the API code and the rest of the information is coming from Moonrope processing that result.

As you say and can see from the below, the outermost `status` is always present and always `"success"` regardless of the `data` values.

![image](https://user-images.githubusercontent.com/1619102/65691135-3b711c80-e068-11e9-9369-4c6b5dda2047.png)

![image](https://user-images.githubusercontent.com/1619102/65691209-5d6a9f00-e068-11e9-860a-3760b5c681c2.png)

Having read [the documentation](https://atech.github.io/postal-api/controllers/messages/message.html) and [api/structures/message_api_structure.rb](https://github.com/atech/postal/blob/master/api/structures/message_api_structure.rb), it seems you can already request the extra information like so

![image](https://user-images.githubusercontent.com/1619102/65692661-d10dab80-e06a-11e9-8164-53700be8e1ff.png)

HTH
