### ISSUE TITLE
smtp not working by php code

### ISSUE THREAD

**Issue by harshweo** [postalhq/postal#883]
Hello all;
My postal server is working good ,graphically  i can sent mail to every where.but when i use SMTP by php code it could not work.
it generate error:
2019-09-25 12:06:23 Connection: opening to ssl://mail.webexpertsonline.co:25, timeout=300, options=array ( ) 2019-09-25 12:06:23 Connection failed. Error #2: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23

Failure sending mail.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 157.245.96.95:2525

**Comment by willpower232** [comment]
Are you able to share your code?

Also if you're writing custom PHP code, you could make use of the [postal-php](https://github.com/atech/postal-php) library to avoid having to use SMTP.

**Comment by harshweo** [comment]
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require 'PHPMailer/PHPMailerAutoload.php';

$email='admin@gmail.com';
$subject = "Test Weo SMTP ";
$mailContent = 'Hi admin,' .
'<br>YOu recieve this email as you we are testing weo SMTP server.'.
'<br>' .
'<br><br>&copy; ' . date('Y') . ' P2H5. all rights reserved.';

$mail = new PHPMailer;
$to= 'user@domainname.com';
$from = 'info@domainname';
$reply = 'info@domainname';
$mail->SMTPDebug = 2;                               // Enable verbose debug output
$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'hostname';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'username';                 // SMTP username
$mail->Password = 'password';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 2525;                                    // TCP port to connect to
$mail->setFrom($from, 'weo');
$mail->addAddress($to);               // Name is optional
$mail->addReplyTo($reply, 'weo');
$mail->isHTML(true);                                  // Set email format to HTML
$mail->Subject = $subject;
$mail->Body = $mailContent;
//$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if (!$mail->send()) {
echo 'Message could not be sent.';
echo 'Mailer Error: ' . $mail->ErrorInfo;
exit;
} else {
echo 'Message has been sent';
}

**Comment by harshweo** [comment]
is any problem with self generated ssl?

**Comment by willpower232** [comment]
Its interesting that the error talks about the port that you didn't give it but maybe thats a PHPMailer thing.

Yes, you should have fully valid certificates for your SMTP server. If you have secured the UI through some, you should be able to reuse them for the SMTP server.

**Comment by yuvrajWeo** [comment]
working for me after installtion SSL
