### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by yuvrajWeo** [postalhq/postal#887]
Hi ,
After restart my server my postal server stop working but my nginx is working.
Here is the screen shots:

http://prntscr.com/phsrmk
http://prntscr.com/phsrxr
http://prntscr.com/phss93

**Comment by willpower232** [comment]
What happens if you just run `postal start`?

Did you configure your Postal to start on boot? https://github.com/atech/postal/wiki/Starting-on-boot

Have you modified the defaults file instead of the separate configuration file?

**Comment by yuvrajWeo** [comment]
When i just run postal start  
http://prntscr.com/phu1zm
yes i configured  Postal to start on boot.
yes i have two configuration files
/opt/postal/app/config/postal.defaults.yml (i have done changes likes on SMtp: ssl path )
/opt/postal/config/postal.yml

**Comment by yuvrajWeo** [comment]
http://prntscr.com/phud4g

**Comment by willpower232** [comment]
You should not make changes to `/opt/postal/app/config/postal.defaults.yml` as can be overwritten by updates to Postal.

Are you able to put all your changes in `/opt/postal/config/postal.yml` and if its still not working, share that file here (redacting the passwords)?

**Comment by yuvrajWeo** [comment]
web:
  # The host that the management interface will be available on
  host: mail.webexpertsonline.co
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: password
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: password
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: password
  vhost: /postal
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mail.webexpertsonline.co
  smtp_server_hostname: mail.webexpertsonline.co
  spf_include: spf.mail.webexpertsonline.co
  return_path: rp.mail.webexpertsonline.co
  route_domain: routes.webexpertsonline.co
  track_domain: track.mail.webexpertsonline.co

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 157.245.96.95
  port: 25
 username: weo-infotech
  password: smtp password
  from_name: Postal
  from_address: info@mail.webexpertsonline.co
Rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: d748e89caa2d2a49a9e4223349cd0cdd9db333b590a3138fd6cff64deac25baa51ba682565bfa9c4f7e145797a3b5f0f5d67394ec7b0364f19a8e1f452cef8e474cf935a7bcbc43f9b5502fef$

@willpower232

**Comment by yuvrajWeo** [comment]
hi @willpower232  please find the attachment of file please tell me where i have to give ssl path in the file . i have revert all the changes of /opt/postal/app/config/postal.defaults.yml to default

[optpostalconfigpostal.yml.txt](https://github.com/atech/postal/files/3717076/optpostalconfigpostal.yml.txt)

**Comment by yuvrajWeo** [comment]
after the restart postal 
http://prntscr.com/phvnne

**Comment by willpower232** [comment]
Glad you figured out the rest of it, what error message are you seeing now?

**Comment by yuvrajWeo** [comment]
error on phpcode :
2019-10-11 11:43:56 Connection: opening to mail.webexpertsonline.co:25, timeout=300, options=array()
2019-10-11 11:43:56 Connection: opened
2019-10-11 11:43:56 SERVER -> CLIENT: 220 mail.webexpertsonline.co ESMTP Postal/LZNFRJ
2019-10-11 11:43:56 CLIENT -> SERVER: EHLO www.p2h5.com
2019-10-11 11:43:57 SERVER -> CLIENT: 250-My capabilities are250 AUTH CRAM-MD5 PLAIN LOGIN
2019-10-11 11:43:57 CLIENT -> SERVER: AUTH CRAM-MD5
2019-10-11 11:43:57 SERVER -> CLIENT: 334 PGNhN2VkNGI2MzZhZWI1MWRiYzZiQG1haWwud2ViZXhwZXJ0c29ubGluZS5jbz4=
2019-10-11 11:43:57 CLIENT -> SERVER: <credentials hidden>
2019-10-11 11:43:57 SERVER -> CLIENT: 535 Denied
2019-10-11 11:43:57 SMTP ERROR: Username command failed: 535 Denied
SMTP Error: Could not authenticate.
2019-10-11 11:43:57 CLIENT -> SERVER: QUIT
2019-10-11 11:43:57 SERVER -> CLIENT: 221 Closing Connection
2019-10-11 11:43:57 Connection: closed
SMTP Error: Could not authenticate.
Message could not be sent. Mailer Error: SMTP Error: Could not authenticate.

**Comment by yuvrajWeo** [comment]
if i bypass tls security it will working fine with smtp or api key.

can you please suggest me to use ssl path in configuration file or tls cipher .

**Comment by willpower232** [comment]
Do those two certificate files exist? Are they readable by the Postal user?

I assume you took out the password from your SMTP transcript?

It doesn't actually say you had a problem with the certificate so perhaps there was a problem with the username. Did you definitely use `org/server` format?

#414
