### ISSUE TITLE
Fast Server SSL certificate issue

### ISSUE THREAD

**Issue by marc-pages-onclick** [postalhq/postal#892]
The generated certificate for tracking URL is self signed so an error message is shown to the users.

Tracking domains:
`track.example.com`

The admin panel shows:
- CNAME configured correctly
- SSL enabled

But when I try to reach the tracking URLs, on https an error is given:

`curl http://track.postal.site.com`
Response: `Hello.`

`curl https://track.postal.site.com`
Response: `(60) SSL certificate problem: self signed certificate`

`curl http://track.example.com`
Response: `Hello.`

`curl https://track.example.com`
Response: `(60) SSL certificate problem: self signed certificate`

DNS:

`CNAME track.example.com -> track.postal.site.com`

What I'm doing wrong? It looks like it's generating self-signed certificate instead of Let's Encrypt.

Thanks.

**Comment by marc-pages-onclick** [comment]
Hi,

I think I've already did that.

**/opt/postal/log/lets_encrypt.log output:**
`[5397] [2019-10-16T11:38:29.175] INFO -- : Successfully registered private key with address email@example.com

^[[34m[worker.1:5030]^[[0m [2019-10-16T13:30:01.679] INFO -- : Attempting verification of track.example.com

^[[34m[worker.1:5030]^[[0m [2019-10-16T13:30:03.606] INFO -- : Getting certificate for track.example.com

^[[34m[worker.1:5030]^[[0m [2019-10-16T13:30:12.317] INFO -- : Certificate issued (expires on 2020-01-14 12:30:08 UTC, will renew after 2019-12-23 12:30:08 UTC)`

Thanks.

**Comment by willpower232** [comment]
Interesting. It might be worth restarting Postal/your server to see if that applies the certificate.

**Comment by marc-pages-onclick** [comment]
Yes, after restart it worked 😅. All tracking features are working fine now.

If you need more information:
Digitalocean
Ubuntu 16.04.6 (LTS) x64
Fresh installation following Quick Install guide

Thanks.
