### ISSUE TITLE
Fresh Install - Invite new user and it just spins

### ISSUE THREAD

**Issue by compwiz21** [postalhq/postal#894]
On a fresh install, once i verified my domain, i go to invite users and it just spins.  Any ideas? The email never gets sent out. In the configuration, i'm using the newly created mail server to send out mail.

**Comment by DTS-Mike** [comment]
Look at your postal.yml file and make sure your smtp domain is the same as the domain your using.

**Comment by willpower232** [comment]
You should look in the `/opt/postal/log` files to see what the problem is.
