### ISSUE TITLE
Postal randomly stops responding 

### ISSUE THREAD

**Issue by DTS-Mike** [postalhq/postal#895]
So I have this issue of postal stop responding and I don’t see anything alarming in any logs. 

Environment -
- lower volume today with only 100 messages sent
- in AWS for VM (postal) and using RDS for MySQL 

They Symptoms:
-The web interface says 502 bad gateway
- smtp connection won’t connect. 

Things tried:
-postal status always says running
-running post restart does not fix. It does not appear to actually stop the original jobs. Every once in a while it will start a 2nd worker job. 
- I have to reboot the server for the issue to fix. 

I have looked in worker, rails, smtp, and messagerequer logs with no luck as to why. The only thing I think is Cole to timing is when postal will add a new smtp log file and changes the name to .log.0.  Where should I start to look at?

Thoughts or suggestions?  Some times it goes a week while other times it happened twice today.

**Comment by willpower232** [comment]
When you say `2nd worker job` do you mean process or something different?

Are you using up all your available memory?

Have you had a look in syslog for anything else happening around that time?
