### ISSUE TITLE
adding to suppression list customisation

### ISSUE THREAD

**Issue by pixelpaulaus** [postalhq/postal#900]
i am very interested in using postal. But from what i have read... if an email gets hard bounced, it will only add to the suppression list if it was bounced 2 times within 24hrs.
Is there any configuration that can be set to change this to something like 60 days? And the email will remain on the list for a custom amount of days? Or maybe a gradual increase in the time on the list when the address was previously on the list an X amount of times.

**Comment by willpower232** [comment]
I do not believe that level of configuration is currently available. You might be able to reduce the amount of time email addresses are on the suppression list with a small code change but #815 could be a problem for the list being cleared.

An email message should only be hard-failed after it has been repeatedly retried over an increasing period of time so the recipient is definitely incorrect/broken in some way or another, any additional delay beyond the current coding would likely only delay the inevitable suppression but also could be interpreted badly by the receiving mail server causing you more trouble.

Postal is designed for transactional email (as opposed to marketing email) so you should have the opportunity to internally detect and warn you of failing email messages. This can be done by your software receiving webhooks from the Postal server.

That said, the code is all here if you want to investigate and add the feature yourself.
