### ISSUE TITLE
Suppression list not cleared

### ISSUE THREAD

**Issue by criskolkman** [postalhq/postal#904]
Hello,

On the **Suppression List** page there is a note that the list is being cleared every 30 days, but this does not seem to be happening:

![image](https://user-images.githubusercontent.com/17678609/67933803-d8bef380-fbc6-11e9-9534-64b88175e20a.png)

![image](https://user-images.githubusercontent.com/17678609/67934120-7fa38f80-fbc7-11e9-9f10-dea6995fb0d3.png)

**Comment by willpower232** [comment]
Duplicate of #815

**Comment by zeba121** [comment]
You can change on this file.
![image](https://user-images.githubusercontent.com/46315368/68273031-5c775500-008b-11ea-82c6-43188f18f4f8.png)


and you can also delete suppression mail manually.
got the 
#mysql
>use postal
>use postal-server-1
>TRUNCATE TABLE suppressions;

**Comment by willpower232** [comment]
resolved by the merging of #867
