### ISSUE TITLE
question about transport rules limit

### ISSUE THREAD

**Issue by liorme776** [postalhq/postal#911]
i want to use postal to make alias based forwarding

say i have a mailbox called x@x.com

and i also have a lot of other domains, such as y.com and d.com and so on
i want to point those domains to this postal server, and from there i want to redirect them onward.

for example i have 1@d.com, i want to make a rule that if an email comes for 1@d.com, it'll be forwarded to 1@ddd.com based on specific body
can postal do that? and also, what's the limit, the number of such rules? today i use office 365 and the limit is 300 rules and it's not enough
thank you

**Comment by willpower232** [comment]
I don't believe Postal will have a limit on the routes, as long as your server can handle the traffic, it should be fine.

**Comment by liorme776** [comment]
i see. so there is no known hard limit? a "cap" of some sort?

**Comment by willpower232** [comment]
the only cap would be what your server can handle, presumably there is some point in the thousands where you might start to struggle
