### ISSUE TITLE
SSL not being created to click & tracking system

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#914]
When I add one subdomain to "click & tracking system", the status "SSL setup in progress" never change.

On lets encrypt log side I only see this:
```bash
[6290] [2019-11-09T15:57:03.282] INFO -- : Attempting verification of click.notifications.xxxxx.com
[6290] [2019-11-09T15:57:05.446] INFO -- : Status was not valid (was: invalid)
```
I have all ports opened. I can generate SSL certs from LE manually normally. Even with firewall with no rules and all policies set to ACCEPT.

I tried to run 
```python
 TrackCertificate.where(certificate: nil).map(&:get)
```

and 

```python
irb(main):002:0> RenewTrackCertificatesJob.perform
```

and they get same problem (status invalid).

When I run "RenewTrackCertificates" in the first time I get this log:

```bash
=> [#<TrackCertificate id: 12, domain: "click.notifications.xxxxxx.com", certificate: nil, intermediaries: nil, key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA70...", expires_at: nil, renew_after: "2019-11-10 15:53:51", verification_path: ".well-known/acme-challenge/PRMHGnkwb2sTQY8iV8VERQ3...", verification_string: "PRMHGnkwb2sTQY8iV8VERQ3daF6xGtiun__P03bnWQI.ZH5yQ4...", created_at: "2019-11-09 15:46:06", updated_at: "2019-11-09 15:53:51">]
```

But in second time and the following I get only

```bash
=> []
```

With "TrackCertificate" command I get:

```bash
=> [false]
```

I did all steps required in https://github.com/atech/postal/wiki/Click-&-Open-Tracking 

I use a dedicated IP to click & tracking system and there are no rules to block anything on that IP.

How can I get more details about what is happening?

I installed Postal from "quick guide" that provice a shell script. It is a very fresh installation on Ubuntu 16.04.6 LTS.

**Comment by willpower232** [comment]
Did you definitely run `postal register-lets-encrypt youremail@example.com` without any problems?

**Comment by franciscopaniskaseker** [comment]
> Did you definitely run `postal register-lets-encrypt youremail@example.com` without any problems?

There is only this message when I execute this command:

```bash
Done
```

I think this problem is due to #915 , fast server is not running.
