### ISSUE TITLE
Click & tracking service getting 404 error

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#915]
Can be relationated with #914 

When we create one click & tracking subdomain, with or without SSL configuration, all URLs get 404 error.

One example of error log:

```bash
172.94.15.30 - - [05/Nov/2019:21:48:04 +0000] "GET /404 HTTP/1.0" 404 1564 0.2122
```

When I access 

https://click.notifications.xxxxxxx.com/ctqu6f/H0zoVR7I

Clearly HTTP server not find the file, so I interpret that are some misconfiguration about how to interpret the URL or something is broking at "cick & tracking" service.

I uses "quick install guide" that execute a shell script. And I double checked every configuration reading full install guide from documentation.

- I am using Ubuntu 16.04
- I am using latest Postal version (confirmed when I do postal auto-upgrade command).
- All configurations asked to do in https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration are done.

Is there a way to set some debug mode to troubleshoot this?

**Comment by franciscopaniskaseker** [comment]
track.subdomain.domain.com point to dedicated IP on postal server configured postal.yml. And all click & tracking subdomains are cname to track.subdomain.domain.com, and I checked the dns lookups and they get same IP address on server.

**Comment by willpower232** [comment]
If you access http://click.notifications.xxxxxxx.com then you should see a `Hello.` from the fast server. If you don't see that then you could use `netstat -lnp` on the server and `postal status` to be sure that the fast server is running and is listening on ports 80 and 443 on the IP address that matches what you think it should be.

**Comment by franciscopaniskaseker** [comment]
> If you access http://click.notifications.xxxxxxx.com then you should see a `Hello.` from the fast server. If you don't see that then you could use `netstat -lnp` on the server and `postal status` to be sure that the fast server is running and is listening on ports 80 and 443 on the IP address that matches what you think it should be.

Fast server is not running. I configured zabbix server with postal template today and I saw that. Then you sent this message then. I will try to fix that.

**Comment by franciscopaniskaseker** [comment]
There are no logs about fast_server when I restart postal service. If the fast_server IP is configured on IP Pool (even without use), it can block fast_server to start?

I will try to check that.

**Comment by franciscopaniskaseker** [comment]
I tried with IP added on IP pool and without on IP pool (postal web interface) and in both cases did not work. I read the postal fast_server ruby code about bind this IP and I not found any kind of test if the IP is or not is added on IP pool.

> https://github.com/atech/postal/blob/master/lib/postal/fast_server/server.rb


There are no logs in "/opt/postal/logs" about fast_server or relationated about.

**Comment by franciscopaniskaseker** [comment]
I tried to declare all possible vars on fast_server config on postal.yml, but no success to get some log.

```bash
fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: x.y.z.w
  port: 80
  ssl_port: 443
  proxy_protocol: false
  default_private_key_path: /opt/postal/config/fast_server.key
  default_tls_certificate_path: /opt/postal/config/fast_server.cert
```

And cert permissions are ok:

```bash
-rw-r--r-- 1 postal postal 1931 Nov  6 17:44 fast_server.cert
-rw-r--r-- 1 postal postal 1704 Nov  6 17:44 fast_server.key
```

If I did not see any error about bind IP address fail in https://github.com/atech/postal/blob/master/lib/postal/fast_server/server.rb , I think the server is not be executed for someone.

Befora I try do some debug on code, I left

```bash
  bind_address:
```
empty and tried restart the server. Finally I get a file called "fast_server.log" with some messages:

```bash
^[[34m[fast.1:8789]^[[0m [2019-11-12T16:11:19.779] INFO -- : Cannot start fast server because no bind address has been specified
```

Then I configured the IP again and the log file is not updated anymore.

The IP is working and is dedicated to this feature. I can ping and access ssh from this IP, so it is working (only to help understand the scenario, because I know the application not test this).

**Comment by franciscopaniskaseker** [comment]
> Then I configured the IP again and the log file is not updated anymore.

I saw in

https://github.com/atech/postal/blob/634d3af59d392e84bdcd2b843b427f3a79d3ff4c/lib/postal/fast_server/server.rb#L20

If bind fail, there are no logs about bind fail.

**Comment by willpower232** [comment]
in this situation, I would use `postal status` to see what the command to run the fast_server is and then run that command myself to see what the output from it is

**Comment by franciscopaniskaseker** [comment]
postal status result

```bash
 * fast.1 is not running (Failed)
```

```bash
|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.1           Failed       16:12        pid:9066     respawns:5      port:-        tag:-
```

**Comment by willpower232** [comment]
If you haven't already, run `bundle exec rake postal:fast_server` to see what the problem might be

**Comment by franciscopaniskaseker** [comment]
I did:

```bash
postal@s54797:~/app/bin$ bundle exec rake postal:fast_server
(in /opt/postal/app)
rake aborted!
Errno::EADDRINUSE: Address already in use - bind(2) for "x.y.z.w" port 80
/opt/postal/app/lib/postal/fast_server/server.rb:21:in `initialize'
/opt/postal/app/lib/postal/fast_server/server.rb:21:in `new'
/opt/postal/app/lib/postal/fast_server/server.rb:21:in `block in run'
/opt/postal/app/lib/postal/fast_server/server.rb:20:in `each'
/opt/postal/app/lib/postal/fast_server/server.rb:20:in `each_with_object'
/opt/postal/app/lib/postal/fast_server/server.rb:20:in `run'
/opt/postal/app/lib/tasks/postal.rake:33:in `block (2 levels) in <top (required)>'
rake:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.3.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => postal:fast_server
(See full trace by running task with --trace)
```

Then I verified the nginx default configuration of postal service and I saw default config files listening 0.0.0.0 on 80 port. Then I changed to IP:80 (nginx /etc/nginx/sites-enabled/default file) and started Postal service. Now it works.

```bash
|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.1           Running      00:39        pid:16770    respawns:0      port:-        tag:-
```

So I recommend update the manual guide to show this information and change the quick install script to avoid "0.0.0.0" configuration, because it will block fast server to start if 0.0.0.0 is used in nginx.

Thank you for all help.

**Comment by willpower232** [comment]
Glad you got it sorted.

Using a different IP address can't really be automated without a lot of work to detect IP addresses on the system and replacing them in the files. Also some server configurations will be different so blindly replacing IP addresses in files wouldn't be good for everyone.

Admittedly it is easily missed, I seem to remember doing the same initially, but it is in the documentation already https://github.com/postalhq/postal/wiki/Click-&-Open-Tracking#enable-the-fast-server
