### ISSUE TITLE
How Can I Stop Postal Login Redirection On Additional IPs

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#919]
Hello Postal Team,

I want to stop postal login redirection on additional ips.

I want to postal login on main static ip but when we add additional ips on server or add on ip pool. 
Then they additional ips are redirect on postal login.

Nobody see my postal login with any ips.

So please help me on this how can i stop this.

Thank You
Zeba Parveen

**Comment by willpower232** [comment]
Its likely that your nginx configuration is set to listen on the default IP addresses: https://github.com/atech/postal/blob/2d9a18f658a0b561381851eaf94ad9d0f9f8c73a/resource/nginx.cfg#L3

You should change this IP address to match the one you wish. If you are unsure, you can use the `ip a` command to see which IP addresses your server can see.

**Comment by zeba121** [comment]
Hello @willpower232 ,

I have configured in postal/resource/nginx.cfg file but it's still.
please check this  https://pastebin.com/kewqX9t7

and you can also check my server network:-
https://pastebin.com/iV75cPYi

My all additional ips redirect on Postal login.
https://prnt.sc/q1l83y

I don't want to login postal on additional Ips.

Thank You

**Comment by willpower232** [comment]
Have you made the changes to `/etc/nginx/sites-enabled/default` and restarted nginx?

The `nginx.cfg` is a template for the configuration.

**Comment by zeba121** [comment]
Thank You @willpower232  its working additional ips are not redirecting on postal.
Thanks Again for helping me.
