### ISSUE TITLE
Webhooks URL ignores query parameters

### ISSUE THREAD

**Issue by joseltorres** [postalhq/postal#923]
When the webhook url is set to something like `https://example.com/?page=crm&q=crm/postal/callback`, Postal sends webhook only to `https://example.com/`

Seems at some point Postal strips the webhook URL query  #parameters

**Comment by willpower232** [comment]
Thanks for mentioning @joseltorres, have you been able to test the PR or are you from the same company?

**Comment by joseltorres** [comment]
Yes, we are from the same company.  Yes, we tested it, and it's in production right now.
