### ISSUE TITLE
Mysql2::Error (Access denied for user 'postal'@'localhost' to database 'postal-server-25')

### ISSUE THREAD

**Issue by GhaziTriki** [postalhq/postal#925]
The error I get on ubuntu 18, maria db is

```
[34m[web.1:19236][0m [2019-11-27T21:04:35.593] FATAL -- :   
[34m[web.1:19236][0m [2019-11-27T21:04:35.593] FATAL -- : Mysql2::Error (Access denied for user 'postal'@'localhost' to database 'postal-server-25'):
[34m[web.1:19236][0m [2019-11-27T21:04:35.593] FATAL -- :   
[34m[web.1:19236][0m [2019-11-27T21:04:35.593] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'
lib/postal/message_db/database.rb:311:in `block in query'
lib/postal/message_db/mysql.rb:20:in `client'
lib/postal/message_db/database.rb:342:in `with_mysql'
lib/postal/message_db/database.rb:310:in `query'
lib/postal/message_db/provisioner.rb:46:in `drop'
lib/postal/message_db/provisioner.rb:13:in `provision'
app/models/server.rb:86:in `block in <class:Server>'
app/controllers/servers_controller.rb:36:in `create'

```

**Comment by willpower232** [comment]
> Access denied for user 'postal'@'localhost' to database 'postal-server-25'

If it can access the other Postal databases, either postal-server-25 doesn't exist or something has altered the user configuration in the database server.

**Comment by GhaziTriki** [comment]
I discovered that my MariaDB user did not have the permission to create tables and alter them. Is that written somewhere in docs?

**Comment by willpower232** [comment]
The docs recommend granting the `ALL` permission to your Postal user for the Postal databases as detailed here: https://github.com/postalhq/postal/wiki/Installation#preparing-the-database

You will need to use the `root` user to update the permissions.

**Comment by dsaydon90** [comment]
This helped me
```
# connect to the container
docker exec --user root -it <mariadb container> bash

# connect to db
mysql -u root -h localhost -P 3306 -p
```
now enter your db password - in my case I took it from the docker compose
