### ISSUE TITLE
How To Stop Auto Generator DKIM Key Or Hostname 

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#926]
Hello Postal Team,

How Can I stop automatic dkim generator key or hostname.

I need to stop this automatic generator.

So Please help me on my Query.

Best Regards,
----------------------
Zeba

**Comment by willpower232** [comment]
I'm not sure you can or should, Postal should still be signing the emails with it so needs this information.

You may be able to set it to what you want in the database if you already have something you want but I'm not sure how well that would work.

**Comment by zeba121** [comment]
Hello @willpower232 


**I have to try pass dns records on default domain or existing domain in postal.** 

If the sender send  mail with existing domain so the dns records pass on the existing domain.

If the sender send mail without existing domain then the dns records pass with default domain.


check this i have edit in this file 

https://github.com/postalhq/postal/blob/master/lib/postal/smtp_server/client.rb   line no. 394



![image](https://user-images.githubusercontent.com/46315368/70370591-f16da800-18ee-11ea-9634-471ce56eda43.png)


**I have try this but the postal** when the sender send  mail with existing domain so the dns records doesn't pass on the existing domain.

Or when the sender send mail without existing or not existing domain then the dns records pass with default domain.



Thank You

**Comment by willpower232** [comment]
I'm not completely familiar with the process but the DKIM functionality relies on a private key amongst other things.

You can access this private key in your postal database if you connect directly to it with a program such as heidisql.

Can you explain what you're trying to accomplish and why? The DKIM record generated by Postal uses a separate identifier so should not interfere with anything already existing.

**Comment by zeba121** [comment]
Hello @willpower232 


Because i want to send mail without existing or existing domain  but the dns records pass on both of condition same, that's why i want to try this.

**Comment by willpower232** [comment]
Postal has to know at least one domain to allow you to send from it but you can make use of the Sender header to allow you to send from other domains, have a look at https://github.com/postalhq/postal/issues/277#issuecomment-316034829

**Comment by zeba121** [comment]
Hello @willpower232 ,


Whenever we delete the domain, the SPF and other records are not changed, only the dkim key changed. so i want  to fixed the dkim value for every domain.


So that the dkim value is always fixed and whenever I add the domain then all the records become active.

It is Possible.

**Comment by willpower232** [comment]
I think I understand, if you remove the additional domain from your Postal and send using it anyway, which DKIM domain does it use?

**Comment by zeba121** [comment]
No I want send both condition if we have add additional or remove domain in postal.

**Comment by willpower232** [comment]
Then I probably don't understand what you're doing sorry

**Comment by zeba121** [comment]
Whenever we delete the domain, the SPF and other records are not changed, only the dkim key changed. so i want to fixed the dkim value for every domain.

So that the dkim value is always fixed and whenever I add the domain then all the records become active.

If It is Possible.

**Comment by bpareek9694** [comment]
Hi @willpower232,

My issue are same as describe in this case,


I just want that i have one dkim key which are applied all my server domain in the postal.

**Comment by willpower232** [comment]
In theory you can update the database manually so that the DKIM private key is the same for your domains which I believe would make the values match.

**Comment by bpareek9694** [comment]
i already change private key according to #616 
But when i send a mail using postal to my gmail account, the dkim are not finding key
https://prnt.sc/q8s0od

after that i can check dkim status in domain setting in postal...
it's show varified...https://prnt.sc/q8s2m6

and also i generate dkim key using online tools,

**Comment by zeba121** [comment]
Hello @willpower232

My second issue one dkim key which are applied all my server domain in the postal has resolved by the help of you or @bpareek9694 .

But my first issue are not solved can you please help me on this.
 
Let me explain you my issue:

I have made some changes in this file which can send  mail from any domain

 /opt/postal/lib/postal/smtp_server/client.rb

authenticated_domain = nil
        if @credential
          authenticated_domain = @credential.server.find_authenticated_domain_from_headers(@headers)
          if authenticated_domain.nil?
            transaction_reset
            @state = :welcomed
            return '530 From/Sender name is not valid'
          end
        end


**if i have removed this** **.find_authenticated_domain_from_headers(@headers)**

**from  this ** **@credential.server.find_authenticated_domain_from_headers(@headers)**


And it is also working properly with all DNS records pass on the default example.com domain.

But when i add the example2.com domain in the postal or pass the all dns records the mails are sent  with all dns records pass on the default example.com domain.

That's why When I  don't add domain, then without checking domain, go to Example.com and when I add another, then go to Example2.com.

So how can i do this.
