### ISSUE TITLE
CheckAllDNSJob doesn't run

### ISSUE THREAD

**Issue by alnalda** [postalhq/postal#928]
Hi, 
i was trying to use the defined function CheckAllDNSJob.

Should be straight forward by calling it from the Postal Console as _CheckAllDNSJob.perform_ but it didn't return any result but empty object and seems like doesn't work.

I have multiple records matching the function requirements so it's not an issue with the data: 
- not(:dns_checked_at => nil)
- ("dns_checked_at <= ?", 1.hour.ago)

I could run directly the code successfully but **can anybody confirm that the CheckAllDNSJob job is working fine and it's an issue on my side?**

**Comment by willpower232** [comment]
In theory, the job runs as part of the cron: https://github.com/postalhq/postal/blob/7cfbda4426e2a5b7eccc6f888d80abfdebf2f0cb/config/cron.rb#L18

Are you seeing that DNS is not correct in the UI if you wait an hour or so for a known-"broken" domain?

**Comment by alnalda** [comment]
I checked that the cron is doing the job correctly but in the "Verification at" is not updated.
![imagen](https://user-images.githubusercontent.com/10944246/70900881-0090dc00-1ffa-11ea-93e2-e1d416f1967c.png)
![imagen](https://user-images.githubusercontent.com/10944246/70900957-26b67c00-1ffa-11ea-9c42-31a46ae38547.png)

This check is bringing me to this other point. https://github.com/postalhq/postal/issues/868#issuecomment-566006383

**Comment by willpower232** [comment]
I believe that the verified at timestamp would be for when the domain was initially verified to be on your Postal server. If you are using it as a regular user, not administrator, then you would have to create a verification DNS record.

It would seem your problem is related to the type of record as discussed in #868
