### ISSUE TITLE
550 5.7.1 Relaying denied

### ISSUE THREAD

**Issue by renagaev** [postalhq/postal#929]
I see 550 5.7.1 Relaying denied in gmail when I try to send email to Postal. 
Postal says that all DNS records are correct. 
My postal.yml:

```web:
  host: mail.mydomain.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  enabled: false
  bind_address:

general:
  use_ip_pools: false

main_db:
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  mx_records:
    - mail.mydomain.com
  smtp_server_hostname: mail.mydomain.com
  spf_include: mail.mydomain.com
  return_path: rp.mail.mydomain.com
  route_domain: routes.mail.mydomain.com
  track_domain: track.mail.mydomain.com

smtp:
  host: 127.0.0.1
  port: 2525
  username: admin
  password: admin
  from_name: Postal
  from_address: postal@yourdomain.com```

**Comment by willpower232** [comment]
Can you share a screenshot of the error message please?

**Comment by renagaev** [comment]
@willpower232 
![IMG_20191206_144908](https://user-images.githubusercontent.com/28779174/70321171-b8bec780-1837-11ea-94eb-22558cbe7113.jpg)
Message says that server configured incorrectly

**Comment by willpower232** [comment]
Postal is not a traditional email-account style server so I'm not sure your setup is quite right.

Can you tell us how you have set up the relaying?

**Comment by renagaev** [comment]
@willpower232 I don't setup any related to relaying. I installed postal and created dns records. I can send email through web interface

**Comment by willpower232** [comment]
The error message implies there is some relaying happening at some point. Postal does not output that error message as far as I can tell.

Are you able to log in to Postal and see what the message says?

**Comment by renagaev** [comment]
@willpower232 Sorry. I made a mistake. My domain had MX record pointed to mailgun with the same priority as postal record. Thank you for your help.
