### ISSUE TITLE
Stop Auto Generator DKIM Key Or Hostname

### ISSUE THREAD

**Issue by bpareek9694** [postalhq/postal#930]
Hi Team,

I have to try pass dns records on default domain or existing domain in postal.

If the sender send mail with existing domain so the dns records pass on the existing domain.

If the sender send mail without existing domain then the dns records pass with default domain.

check this i have edit in this file

https://github.com/postalhq/postal/blob/master/lib/postal/smtp_server/client.rb line no. 394

![image](https://user-images.githubusercontent.com/53152540/70410733-0d4f8600-1a76-11ea-9db9-642898307140.png)

I have try this but when the sender send mail with existing domain so the dns records doesn't pass on the existing domain.

Or when the sender send mail without existing or not existing domain then the dns records pass with default domain.

Thank You

**Comment by willpower232** [comment]
see #926 926
