### ISSUE TITLE
Does it replace a regular email server?

### ISSUE THREAD

**Issue by DjezusKryst** [postalhq/postal#932]
Hello,

It's not really an issue but I think I've mistaken some information when I installed Postal, I thought that it could replace a full email server with dovecot and postfix but it doesn't seems to be the case. Am I right? Do I still need a regular email server in the first place?

Regards,

**Comment by willpower232** [comment]
Hopefully you saw https://github.com/postalhq/postal/wiki/Features and some other issues where Postal is discussed. Its mainly designed as a tool to use with another software solution, either bespoke or off-the-shelf, to allow the software to send emails and monitor their deliverability.
