### ISSUE TITLE
Pass defaults dkim key in case of other domain used in from address

### ISSUE THREAD

**Issue by bpareek9694** [postalhq/postal#933]
Hello Community,

I've installed postal in Ubuntu 16.04. its working properly.

I am doing some changes
i am using postal smtp in different mail clients (Mail sending application)
concern is that one of my application use multiple domains and domains are dynamic. the important point is that i can't add dns entries in all domains
i want to that, my default domain **domain-default.com** i.e if i added **domain1.com** mail should be go through **domain1.com** and if a added **domain2.com** mails should be go through **domain2.com** , in both case i used same from address **info@domain1.com** and **info@domain2.com** respectively, in case of my mail sending application used domain3.com which don't have dns entries, mails should automatically passed with **_[info@domain3.com via domain-default.com]_** with passed **dkim** and spf with domain  : **domain-default.com**. 

current scenario in postal that if default dkim passed, all mails will go with default domain only. yet we added any domain too. all emails dkim pass with default domain only

**Comment by willpower232** [comment]
Thanks for explaining your needs a bit more from #926.

Postal wasn't designed to work from a mail client which might explain some of your problems.

We actually have experienced a similar issue where dynamic domains were required without being able to officially add the extra records but we eventually concluded it was not possible and are sending from domains we can add the records to.

In your current state, the recipients for the domains that don't have SPF and DKIM configured may or may not receive the email, it depends entirely on how stringent their anti-spam filters are.

**Comment by bpareek9694** [comment]
Thanks for your advise

We've done it with modify the code and tested successfully 

thanks
