### ISSUE TITLE
Bulk mail

### ISSUE THREAD

**Issue by antonkallenberg** [postalhq/postal#934]
We are considering using Postal for one of our services. The service is sending a lot of e-mails, sometimes more than 100k at once. 

I can't find any API for sending the same message to multiple recipients, so if we where to send 100k message we need to do 100k request to Postal and we will get 100k webhooks back? Is there some kind of SMTP-api or something which could handle bulking? 

Is this something you find possible for Postal to handle or would you recommend us to use something else?

**Comment by willpower232** [comment]
https://github.com/postalhq/postal/wiki/FAQs

In your scenario, bulk sending should be handled by your application with 100k requests to Postal as you described.

Postal can handle multiple email addresses on a single email (i.e. CC/BCC) but I presume that wouldn't be suitable or appropriate for your needs.

**Comment by antonkallenberg** [comment]
Thank you for your reply! 

I understand, no problem for our application to batch/bulk. But there will be a lot of requests for Postal to handle. Will postal have a hard time dealing will all of these requests or is it designed to handle many simultaneous requests and handling all of those webhooks... 

Yes we could add multiple addresses to the same message but there are a limit of 50 addresses per request (?). Adding multiple recipients to the same message will also be problematic since Postal doesn't support "recipient variables". If there are something differing between the messages (e.g recipient name) we need to make a new request?

I'm not complaining, just trying to figure out our options.

Thanks,
Anton

**Comment by willpower232** [comment]
No problem at all, Postal should be able to handle the requests but it would be worth making sure you have a well-specced server and Postal configured to take advantage of it.

There are a few issues discussing this topic, #697 and #324 would be a good place to start in this regard.

**Comment by antonkallenberg** [comment]
Thank you for your input! Would you recommend us to use SMTP or the built in HTTP API?

**Comment by willpower232** [comment]
If you want to make use of webhooks, I believe you have to make use of the HTTP API in order to match individual messages you have sent with the received webhook as the output from using the HTTP API will be required for this.

**Comment by antonkallenberg** [comment]
Okay! If using SMTP, we were thinking of using the message-id header (with our own custom ID) to map the message in incoming webhook but that might be a bad idea? :)

**Comment by willpower232** [comment]
I'm not sure that the information returned by the webhooks would include your message ID. If you're hoping to use webhooks, making use of the HTTP API would be a more complete solution.
