### ISSUE TITLE
How To Get Proper Bounce In My Application With Using Postal Server

### ISSUE THREAD

**Issue by zeba121** [postalhq/postal#935]
Hello Postal Team,

I want to get bounce in my email marketing application with using postal server.

I have also configured this but i did not get proper bounce in my application sent mail show the bounce in my application.

So can I fixed this issue.

Looking for your help. 

Thank You
Zeba121

**Comment by willpower232** [comment]
Can you tell us what you have set up so far specifically in Postal and your email marketing application?

**Comment by zeba121** [comment]
@willpower232 

I have add IMAP set up in my application for bounce tracking.

Please seen my application settings:- 
![image](https://user-images.githubusercontent.com/46315368/70882836-fc16f400-1ff6-11ea-8753-71586226cffd.png)


I have added the return path address in the postal

This my postal settings:- 
![image](https://user-images.githubusercontent.com/46315368/70882972-7b0c2c80-1ff7-11ea-80de-9c26b313439f.png)


Then I have received bounce mails  but not proper because sent mails are also show in bounce status and many hard fails or soft fails mails are not show in bounce status  my application.

It's Working but not proper.

**Comment by willpower232** [comment]
I think it might be worth sending an email to a known email you have to see what headers you actually receive. Its likely that Postal is changing the bounce address to one of its own.

**Comment by zeba121** [comment]
Hello @willpower232 

Sorry for late reply.

mails are sent but the bounce status show Over Quota or email address doesn't exist.

Sent mails are also show in the bounce status see in my Application Or Postal.

![image](https://user-images.githubusercontent.com/46315368/71171915-eae31700-2284-11ea-9cc2-ec9e09d824c0.png)

![image](https://user-images.githubusercontent.com/46315368/71172243-b6238f80-2285-11ea-9f3c-50d3e7eedb6e.png)

**Comment by willpower232** [comment]
So your application is receiving the bounces and Postal isn't?

This would imply that the return path address in your emails is being configured by your email application which has access to the bounce messages themselves.

It is possible to allow Postal to receive and process the bounce messages but it might not be quite right for you, have a look at https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces

**Comment by zeba121** [comment]
Hello @willpower232 

How can i configure this auto-responder-&-bounce.

**Comment by willpower232** [comment]
You should have a look at https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces and have a look at setting up routes in your Postal server.
