### ISSUE TITLE
Cannot send email from SMTP relay using external application

### ISSUE THREAD

**Issue by ehtesham000** [postalhq/postal#936]
Socket Error # 10054
Connection reset by peer.Disconnected.

This is the error form my mailing application.
I guess something is blocking 

result after testing 
telnet postal.yourserver.com 25

Trying 1.1.1.1...
Connected to mail.yourdomain.com.
Escape character is '^]'.
220 yourdomain.com ESMTP Postal/BGXGVJ

**Comment by willpower232** [comment]
Where are you seeing that error message?

**Comment by ehtesham000** [comment]
I dont know.. i have installed using the documentation as it was mention 

Secondly some mailing application is sending the emails but those logs like the logs details shows after every  outgoing emails in postal dashboard is not coming like send 5 test emails using postal web interfaces it is showing that but the emails which are going through mailing application is not showing

**Comment by ehtesham000** [comment]
Is there someone who can help me to setul postal correcrly

**Comment by willpower232** [comment]
Are you able to use `postal status` and `netstat -lnp` on your server and share the output here?

**Comment by ehtesham000** [comment]
root@mail:~# postal status
Procodile Version   1.0.26
Application Root    /opt/postal/app
Supervisor PID      23571
Started             2019-12-15 15:14:44 +0000

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      15:14        pid:23577    respawns:0      port:-        tag:-

|| worker
|| Quantity            1
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      15:14        pid:23579    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      15:14        pid:23581    respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      15:14        pid:23584    respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      15:14        pid:23587    respawns:0      port:-        tag:-

**Comment by ehtesham000** [comment]
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      11193/nginx -g daem
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      11400/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1676/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      11193/nginx -g daem
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      23577/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      11321/beam
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      12221/mysqld
tcp6       0      0 :::80                   :::*                    LISTEN      11193/nginx -g daem
tcp6       0      0 :::4369                 :::*                    LISTEN      11400/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      1676/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      23584/[postal] smtp
tcp6       0      0 :::443                  :::*                    LISTEN      11193/nginx -g daem
tcp6       0      0 :::5672                 :::*                    LISTEN      11321/beam
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     8753     1/init              /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     8517     1/init              /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     8530     1/init              /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     8752     1/init              /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     8902     1/init              /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     38640    23571/app)          /tmp/postal/pids/procodile.sock
unix  2      [ ACC ]     STREAM     LISTENING     13138    1/init              /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     13139    1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     13140    1/init              /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     13141    1/init              /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     14304    1457/iscsid         @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     13134    1/init              /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     31978    12221/mysqld        /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     13135    1/init              /var/lib/lxd/unix.socket

**Comment by ehtesham000** [comment]
please someone reply to this @willpower232

**Comment by willpower232** [comment]
It looks like everything is running fine. I presume your application is trying to use an SMTP connection? Did you set up a certificate for it?

**Comment by ehtesham000** [comment]
No i haven't and the certificate thing is not getting install. I was using certbot for that

**Comment by ehtesham000** [comment]
Error: Errno::ECONNREFUSED (Connection refused - connect(2) for "64.225.12.163" port 2525)

  SMTP Host: 64.225.12.163
  SMTP Port: 2525
  SMTP Username: subscriptionrenew/email-server
  SMTP Password: password

@willpower232 

This error generate when trying to execute postal test-app-smtp command

**Comment by ehtesham000** [comment]
I used this https://www.gmass.co/smtp-test to test my smtp with port 25 and security none
i can send the email but the moment i am trying to send from my desktop application i am facing issue

**Comment by ehtesham000** [comment]
[34m[smtp.1:3119][0m [2019-12-17T20:53:20.902] DEBUG -- : [ZUP09V] [34m=> 502 Invalid/unsupported command[0m
[34m[smtp.1:3119][0m [2019-12-17T20:53:20.902] DEBUG -- : [ZUP09V] [34m=> 502 Invalid/unsupported command[0m
[34m[smtp.1:3119][0m [2019-12-17T20:53:20.902] DEBUG -- : [ZUP09V] [34m=> 502 Invalid/unsupported command[0m

SMTP Server log

Help to solve this @willpower232

**Comment by willpower232** [comment]
You probably need to set up the certificate for the SMTP server to use. You can set the following two lines in your main config to point at a valid certificate for your server name:

https://github.com/postalhq/postal/blob/7e5403ace15c252ba49703900ee4d6ae792828ef/config/postal.defaults.yml#L76-L77

And then restart Postal for the change to apply. This should let the SMTP servers talk to each other properly.

**Comment by ehtesham000** [comment]
web:
  # The host that the management interface will be available on
  host: mail.yourbookkeeping.org
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mail.yourbookkeeping.org
  smtp_server_hostname: mail.yourbookkeeping.org
  spf_include: spf.mail.yourbookkeeping.org
  return_path: rp.mail.yourbookkeeping.org
  route_domain: routes.mail.yourbookkeeping.org
  track_domain: track.mail.yourbookkeeping.org
  helo_hostname: mail.yourbookkeeping.org
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

smtp_server:
  port: 25
  tls_enabled: false
  tls_certificate_path: /etc/letsencrypt/live/mail.yourbookkeeping.org/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/mail.yourbookkeeping.org/privkey.pem
  tls_ciphers:
  ssl_version: SSLv23
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14 # size in Megabytes

smtp_relays:
  -
    hostname: mail.yourbookkeeping.org
    port: 25
    ssl_mode: Auto

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 70ab02e590fccabe963178d4b17de5e49d679ddba4e90d2e7410537aa9c075e104ebc1c407ff89599513ef739f1fd12e31e34fd226b81c0be8ae1001c551ba31aadeb316c56923b7381da8d529bc3d3d8d12ef2310a0fc99ccffb8586dfd0ceac4d5f7b68d15bed3641821f42a66ba665d37bfe7f3a0cb8b509dc98e564bb974

**Comment by ehtesham000** [comment]
@willpower232  please check my postal.yml file which is above

**Comment by willpower232** [comment]
You'll notice above the certificates is the entry `tls_enabled` which apparently you have set to false. You will need to set it to true to actually make use of it.

**Comment by ehtesham000** [comment]
Connected to smtp://mail.yourbookkeeping.org:25/?starttls=always
<< 220 mail.yourbookkeeping.org ESMTP Postal/UKFKPC
>> EHLO [172.31.4.197]
<< 250-My capabilities are
<< 250-STARTTLS
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> STARTTLS
<< 220 Ready to start TLS
ERROR: An error occurred while attempting to establish an SSL or TLS connection.
The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.
See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.

Error received while testing smtp

**Comment by ehtesham000** [comment]
<< 220 mail.yourbookkeeping.org ESMTP Postal/B0TWSQ
>> EHLO [172.31.4.197]
<< 250-My capabilities are
<< 250-STARTTLS
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> AUTH CRAM-MD5
<< 334 PDkxYjlhNWY1MzgzYjUzYjZmNzhiQG1haWwueW91cmJvb2trZWVwaW5nLm9yZz4=
>> Ym9va2tlZXBpbmcvc2VydmVyLTEgODlhZTQ5NjQ3YTkzMjNmZTNkNTBlNDRkOTM0MmQzM2Y=
<< 235 Granted for bookkeeping/server-1
>> MAIL FROM:<testmail@yourbookkeeping.org>
<< 250 OK
>> RCPT TO:<prashantkodobagote@gmail.com>
<< 250 OK
>> DATA
<< 354 Go ahead
>> From: testmail@yourbookkeeping.org
>> Date: Mon, 30 Dec 2019 14:41:28 퍍
>> Subject: SMTP test from mail.yourbookkeeping.org
>> Message-Id: <AEC9VDIUG9U4.ZWJJAKCTSK8N@WIN-AUIR3RRGP88>
>> To: prashantkodobagote@gmail.com
>> MIME-Version: 1.0
>> Content-Type: text/Test message
>>
>>
>> .
<< 530 From/Sender name is not valid
ERROR: From/Sender name is not valid


Error when security is none

**Comment by willpower232** [comment]
For your first problem, did you restart Postal after setting `tls_enabled` to true?

Your main problem seems to be that yourbookkeeping.org doesn't seem to be a domain for bookkeeping/server-1

Also you have included the complete credential in base64 in the output here so you should delete that credential from your server.

**Comment by samg8520** [comment]
hi guys i am trying to use postal but facing difficulty.when i restart postal i get
root@postal:~# postal restart
Stopped smtp.8
Restarted web.1
Restarted worker.9 -> worker.10
Restarted cron.9 -> cron.10
Restarted smtp.9
Restarted requeuer.9 -> requeuer.10
root@postal:~#
