### ISSUE TITLE
How to set fast server step by step

### ISSUE THREAD

**Issue by newrose1** [postalhq/postal#937]
i have 1 ip address from postal server  use provider hostkey.com and 1 ip address for tracking in digitalocean how to set fast server.

**Comment by willpower232** [comment]
How have you configured Postal? Do you have one server or multiple? Can you see the IP addresses from the command line of the server(s)?

**Comment by newrose1** [comment]
Postal web server run on hostkey provider and had 1 ip address. but fast server need more 1 ip address.
I already have more server on digital ocean. Can i use ip address from server on digital ocean for set fast server postal?

**Comment by newrose1** [comment]
Postal server 
![aaaa](https://user-images.githubusercontent.com/33556574/70864027-e0710680-1f80-11ea-99db-b2ab8d90ca6c.PNG)

**Comment by willpower232** [comment]
Your servers are with different providers, I do not think you'll be able to use an IP address from one on the other.

I am not sure how feasible it would be to run only the fast server functionality on a separate server, I believe you might have to make some code changes to more than just the Procfile.

**Comment by newrose1** [comment]
If use once provider but i have 1 ip address. I wan't set fast server for tracking. What should i do?

**Comment by willpower232** [comment]
If you change your nginx to use different ports than 80 and 443, you can use the fast server as well as the rest of Postal. You may also have to change the Postal configuration for the extra port number.

This is mentioned briefly in another issue somewhere as it can cause a few problems but should work for the most part.

**Comment by newrose1** [comment]
After i change port 80 and 43 at nginx/sites-enabled/default to 5013 and 5014 it make can't use https and show this picture
![err](https://user-images.githubusercontent.com/33556574/70865689-dce67b00-1f92-11ea-90bf-5e2d8e8d9d52.PNG)

**Comment by newrose1** [comment]
Now i change fast server to port 5011 ssl 5012 and create new cert.
![1](https://user-images.githubusercontent.com/33556574/70867718-f1cf0880-1faa-11ea-8d8d-77d1effd8b0c.PNG)
postal status (fast server running)
![3](https://user-images.githubusercontent.com/33556574/70867753-69049c80-1fab-11ea-9367-42b6c04f5a75.PNG)
netstat
![4](https://user-images.githubusercontent.com/33556574/70867769-abc67480-1fab-11ea-9e9c-838860f208aa.PNG)

What to do next for open tracking?

**Comment by newrose1** [comment]
![5](https://user-images.githubusercontent.com/33556574/70867782-ddd7d680-1fab-11ea-98a9-3c14ea775982.PNG)

**Comment by newrose1** [comment]
fast server.log
![Screenshot from 2019-12-16 10-01-07](https://user-images.githubusercontent.com/33556574/70876131-0501c880-1feb-11ea-81ad-9f1af306255a.png)

**Comment by willpower232** [comment]
The hello message means you have found the click tracking so its working properly.

Did you do the register lets encrypt command?

**Comment by newrose1** [comment]
postal register-lets-encrypt **youremail@example.com** right?

**Comment by newrose1** [comment]
In document  "subdomain like click.yourdomain.com and point it to your Postal server."
It mean I should set A record click.yourdomain.com to xxx.xx.xx.xx
but in Web UI suggest me click.yourdomain.com CNAME to track.domainname.com.
![Screenshot from 2019-12-16 18-10-38](https://user-images.githubusercontent.com/33556574/70903343-4a48e900-2031-11ea-83e2-6b8a74c5ad32.png)
