### ISSUE TITLE
Why mail-testter score 10 but mail send to spam and junk mail?

### ISSUE THREAD

**Issue by newrose1** [postalhq/postal#940]

**Comment by newrose1** [comment]
![Screenshot from 2019-12-17 09-55-55](https://user-images.githubusercontent.com/33556574/70961115-7c9b2a80-20b3-11ea-82d5-489d1199a62f.png)

**Comment by willpower232** [comment]
This can be for several reasons, usually down to the receiving servers strictness. It might be that you haven't been sending emails for very long or they don't trust the server company you are using.

Can you send a screenshot of what Postal has recorded for the message that ended up in spam?

**Comment by newrose1** [comment]
![Screenshot from 2019-12-17 16-50-54](https://user-images.githubusercontent.com/33556574/70984983-fcde8180-20ed-11ea-961f-c51f742e7179.png)
![Screenshot from 2019-12-17 16-50-33](https://user-images.githubusercontent.com/33556574/70984986-ff40db80-20ed-11ea-8a95-01d5d794c930.png)

**Comment by willpower232** [comment]
Have a look at the right hand side of the properties tab, you should see what the receiving server said.

Unfortunately, Hotmail, and other Microsoft receiving systems, are particularly untrustworthy of many email messages. Do you have another email address to try as well?

**Comment by newrose1** [comment]
I've tried other email such as Gmail but it's still send to junk mail same as previous mail. I didn't try mail API like Mailgun yet. Do you have any suggestion for this?

**Comment by willpower232** [comment]
I'm afraid there is not much you can do in this case.

It could be worth trying to send a real email instead of a test one to see if the content of the real email makes them less likely to send your email to their spam folder.

Otherwise you could try setting up a Postal server with another provider to see if you have more luck.
