### ISSUE TITLE
Need help getting STARTTLS with Lets-Encrypt working

### ISSUE THREAD

**Issue by alexander-rieder** [postalhq/postal#942]
Hello everyone,

I already tried setting the permissions of the letsencrypt cert directory with setfacl to allow the postal user to access the lets encrypt certificates...

However that didnt work out and my client still reporting, that the provided ssl cert seems invalid or missing.

Can anyone help me out with this?

Greetings,

Alex

**Comment by zeba121** [comment]
Hello,

I have also facing this issue .

![image](https://user-images.githubusercontent.com/46315368/71061365-d96b1380-218d-11ea-884f-bb16ab6432dc.png)

**Comment by willpower232** [comment]
If you're setting the following two lines in your Postal config to set the SMTP server certificate:

https://github.com/postalhq/postal/blob/7e5403ace15c252ba49703900ee4d6ae792828ef/config/postal.defaults.yml#L76-L77

Then you can put those certificates wherever you like.

In our servers case, I modified the certbot cronjob to copy the whole certificate folder somewhere else with better permissions.

**Comment by alexander-rieder** [comment]
could you share your cronjob and the permissions applied to the new dir?
:)

**Comment by willpower232** [comment]
It looks something like this with some extra monitoring involved. I also point nginx at the same copy of the certificates hence the reload but Postal seems to cope just fine.

`0 */12 * * * root perl -e 'sleep int(rand(3600))' && certbot -q renew && rsync -rqtl /etc/letsencrypt /mycompany/ && chmod 555 -R /mycompany/letsencrypt && service nginx reload`

**Comment by alexander-rieder** [comment]
thank you :)

I went another way now.. I just changed the live and the archive folder permissions and added the postal user to it:

```
 setfacl -R -m u:postal:rX /etc/letsencrypt/live/
 setfacl -R -m u:postal:rX /etc/letsencrypt/archive/
```

**Comment by willpower232** [comment]
fair play, feel free to close this issue if you're all sorted now

**Comment by zeba121** [comment]
Hello @willpower232 

I have configure all these. But i have same problem.

![image](https://user-images.githubusercontent.com/46315368/71435116-9836ae80-270d-11ea-9cd3-8a04b18b6bb1.png)

**Comment by willpower232** [comment]
@zeba121 if restarting your Postal doesn't resolve the problem, you should open a new issue with a copy of your Postal config file.

**Comment by moqmar** [comment]
Just a quick question, does the certificate (when setting them manually) also have to be valid for rp.example.org (or any other names), or just for the main domain? :)

**Comment by willpower232** [comment]
@moqmar thats a great question, ours isn't and we haven't had any issues but if you find any problems, do open a new issue

**Comment by moqmar** [comment]
Hm, thanks. It seems like the target of the MX record of the RP domain (which is the main domain) needs a valid TLS certificate, but the RP domain itself doesn't - at least that's what Amazon SES does (see https://luxsci.com/smtp-tls-checker with the server `eu-west-1.amazonses.com` - the domain has a MX record to `feedback-smtp.eu-west-1.amazonses.com`, and the server at that address seems to have a valid certificate for the very same address).

**Comment by layen67** [comment]
If you want TLS working the client where do you want to connect to your smtp use tls version 1.2 not 1.3 version.
