### ISSUE TITLE
mysql12 step failing on "Install Ruby Dependencies" Instructions

### ISSUE THREAD

**Issue by ilovepancakes95** [postalhq/postal#944]
For the "Install Ruby Dependencies" step of the Full Installation instructions I get the following error. Have followed the exact guide up to that point on a clean install of Ubuntu 16.04 LTS. Any ideas?

https://pastebin.com/L4LqZ7FT

**Comment by willpower232** [comment]
Have a look at https://github.com/postalhq/postal/issues/921#issuecomment-558648734

**Comment by ilovepancakes95** [comment]
`apt-get install libnetcdf-dev libssl-dev libcrypto++-dev libgmp-dev`

That allowed me to finish with the installing ruby dependancies step. Thank you.

**Comment by willpower232** [comment]
Thanks for replying, feel free to close the issue if this is all resolved now.
