### ISSUE TITLE
External ID for every send mail request

### ISSUE THREAD

**Issue by MuratKaragozgil** [postalhq/postal#945]
Hello,

I want to identify every send mail request with external identifier (which generated by me). Because i'm getting responses from postal webhook, but webhook contains id and token which generated by postal server.

Below json is to send email request payload; (externalId is generated by me which i want to send and get same if from webhook).
`{
    "to": [
        "xxxx@gmail.com"
    ],
    "from": "test@gmail.com",
    "subject": "Subject",
    "html_body": "body",
    **"externalId" : "asd123asd123"**
}`

And this one is webhook payload;
`{
  "message": {
    **"externalId": "asd123asd123"**
    "id": 23,
    "token": "pYmTDNwpDiFA",
    "direction": "outgoing",
    "message_id": "55fca21e-5c3a-4b94-8d6a-4fadcd0d9c06@rp.mail.xxx.com",
    "to": "xxxx@gmail.com",
    "from": "test@gmail.com",
    "subject": "Subject",
    "timestamp": 1576672849.376531,
    "spam_status": "NotChecked",
    "tag": null
  },
  "status": "Sent",
  "details": "Message for xxsasxasl@gmail.com accepted by aspmx.l.google.com (2a00:1450:4013:c01::1b)",
  "output": "250 2.0.0 OK  1576672850 i1si1751061edf.185 - gsmtp\n",
  "sent_with_ssl": false,
  "timestamp": 1576672850.4403355,
  "time": 0.51
}`

**Comment by willpower232** [comment]
I feel like this has been discussed in another issue but I can't find it now.

At the minute, presuming you are using the HTTP API, you should store the ID and token Postal returns to you when the message is sent to allow you to do the matching within your system.

**Comment by MuratKaragozgil** [comment]
Yes, i will store ID and token Postal, then i will search on database for every web hook calls. It's a solution but i think not efficient. Custom transactional contexts improvements may be very useful for Postal. 

Thanks you for quick response :)
