### ISSUE TITLE
using thunderbird

### ISSUE THREAD

**Issue by el-rems** [postalhq/postal#946]
hello,

my solution is OK , work fine, 
i want to know how using Thunderbird and the solution.

Thanks

**Comment by willpower232** [comment]
Postal does not have email accounts so you cannot connect to it using POP or IMAP.

You can configure Thunderbird to use Postal SMTP credentials if you like but that would only seem to be half of a traditional email setup as you wouldn't be able to read email Postal had received in Thunderbird.
