### ISSUE TITLE
Email Sending Very Slow 

### ISSUE THREAD

**Issue by vscool19** [postalhq/postal#949]
4 quantity worker and 16 threads are running and all are running without any issue. But after picking queued messages, they are taking so much time to parse and deliver. I have checked logs but didn't find any error. Just find that message parsing taking sometime for some messages. Don't know what happened suddenly, earlier they were delivering fast. @willpower232  Can you please give your thoughts where I am lacking. Due to above problem, many mails didn't have any delivery attempt.
Thank you in advance.

![Screenshot from 2019-12-26 22-51-50](https://user-images.githubusercontent.com/11226836/71484459-869af700-2832-11ea-855b-afb76da26351.png)

**Comment by vscool19** [comment]
@adamcooke can you please help me on this?

**Comment by navinp** [comment]
Increase the number of workers, does it help? Or restarting postal?

Are you using a newsletter tool, and is that having db issues also?

**Comment by vscool19** [comment]
> Increase the number of workers, does it help? Or restarting postal?
> 
> Are you using a newsletter tool, and is that having db issues also?

Increasing workers is also not helping in this and also tried stop and start postal so many times. 
Newsletter tool? I didn't get. What are the DB issues it can have? I am not getting any DB related issue.
My other Postal instance is running fine and I am using smtp relay there.

**Comment by arifuzzaman35** [comment]
Hi vscool19 could you please sent me configuration file ,i can sent test mail but could not connect moutic mail sender platform smtp server error below 


Connection could not be established with host mail.mailsurge.email [Connection refused #111] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host mail.mailsurge.email [Connection refused #111] (code: 0)
++ Starting Swift_SmtpTransport !! Connection could not be established with host mail.mailsurge.email [Connection refused #111] (code: 0)

**Comment by willpower232** [comment]
@vscool19 You say the messages are taking a long time to process, are you able to tell us what speeds you are seeing? 

Also if you have been doing lots of restarts, you may also have messages trapped in the queue table so it might be worth double checking https://github.com/postalhq/postal/issues/287#issuecomment-367293435

@arifuzzaman35 make sure that your Postal server is running with the `postal status` command and then that the SMTP port is open for your server. If that all checks out, feel free to open a new issue with some more information.

**Comment by vscool19** [comment]
@willpower232 7-8 mails are going per minute, this is very slow. I have familiar with message stuck thing in queue. So I have already run  update query to update lock with null. But update thing is not helping me either.
As I checked with logs, message parsing is taking time for some messages.

**Comment by willpower232** [comment]
Odd indeed, can you use `htop` or similar on your computer to see if it is low on resources or anything?
