### ISSUE TITLE
Postal breaks when doing email verification

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#950]
Hello,

After adding a domain/and choosing email as verification mechanism, and clicking DNS setup, the Postal install breaks, it gives a "W're sorry, but something went wrong" page error.

Restarting the server does not fix this problem. 

Any ideas?

**Comment by navinp** [comment]
Okay, it's not just email verification, ANY domain, even verified domains, if you click DNS setup, the application breaks.

You get this page:

**We're sorry, but something went wrong.
If you are the application owner check the logs for more information.**

**Comment by willpower232** [comment]
This sounds like a system error. You will have to have a look in your log files to see what has gone wrong.
