### ISSUE TITLE
CNAME not configured correctly

### ISSUE THREAD

**Issue by juhniorsantos** [postalhq/postal#955]
When I validate the track domain, the message always appears: CNAME not configured correctly, does anyone know how to proceed? I already created the registration according to the documentation

**Comment by willpower232** [comment]
You can use whatsmydns.net to verify that the record is available worldwide and the `dig` command on your server to verify that your server can see the record also.

**Comment by juhniorsantos** [comment]
I performed the test and this propagated.
click.massive.com.br.	30 IN CNAME postal.massive.com.br.
mail.massive.com.br.	30 IN TO 144.217.90.163

but in the application it does not confirm

**Comment by willpower232** [comment]
Looks like its propagated to me. Have you tried the `dig` command on the server you're running Postal on? It might have difficult DNS.

**Comment by juhniorsantos** [comment]
Yes, I tried with the dig on my server and it returns correctly.
When I access the domain I also have the return 'Hello.

**Comment by willpower232** [comment]
Have you restarted your Postal just to be sure its all functioning correctly? Can you send a screenshot of where you're seeing the problem?
