### ISSUE TITLE
can i install postal on aws 

### ISSUE THREAD

**Issue by rajneeshweo** [postalhq/postal#956]
@support 
can i install postal on aws  ,how it work without reverse proxy @willpower232 .

**Comment by willpower232** [comment]
You can use the standard install script on AWS EC2 instances. You will need to use AWS support to request permission to send emails regularly though.

You won't need a load balancer from Amazon or anything. nginx is used as a proxy to handle the certificate for the web UI and that is also mostly set up by the script but you will probably have to arrange your own SSL certificates.

**Comment by rajneeshweo** [comment]
thank you @willpower232

**Comment by willpower232** [comment]
no dramas, feel free to close the issue if you have no further questions
