### ISSUE TITLE
Change 25 to 2525 smtp server port

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#957]
I did not find in documentation what I have to configure, but I found one example config in one issue.

What I did (postal.yml):

```bash
smtp_server:
  port: 2525
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/fast_server.cert
  tls_private_key_path: /opt/postal/config/fast_server.key
  #tls_ciphers: TLSv1_1
  #ssl_version: 
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14
```

But I am having 2 problems:

1. SSL connections can not complete ssl validation.
Can anyone exemplify "ssl_version" configuration? I do not which modules are accepted.

2. I am seeing in outgoing messages of Postal dashboard this error:
```bash
No smtp servers were available for xxxx. Tried xxxx.
Connection refused - connect (2) for "****" port 25.
```
If I changed the port from 25 to 2525 and restarted the server and now my applications can connect using 2525 and the postal is listening 2525 port, why 

I am using default "smtp" cinfiguration:
```bash
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
```

I not understand why Postal is trying to use 25 port.

I am using last postal version with updated Ubuntu 16.04.

**Comment by willpower232** [comment]
1. Have a look at https://github.com/postalhq/postal/pull/387, that should help you change it if you want but you don't need to really.

2. The settings in your postal.yml affect only the smtp server that Postal is running. It allows you to send messages via Postal using SMTP instead of the HTTP API. The standard SMTP port is 25 so it will always attempt to connect to other servers using port 25 to send messages to them.

The smtp section is to allow Postal to send messages via itself or another service which is why you get the opportunity to enter the port again.

When you say no smtp servers are available for xxxx, is xxxx yourself or some other email service?

**Comment by franciscopaniskaseker** [comment]
(3) Is not possible to Postal use, for your self, the 2525 port? My customer need to work using 2525.

(4) About "smtp servers are available for xxxx", xxxx is my own server. The DNS is working and is configured in "mx_records" in postal.yml. The problem is postal is trying to use 25 port. The problems is tagged as "softfail" on web interface.

Here there is another example:
```bash
^[[32m[worker.4:16217]^[[0m [2020-01-05T08:05:47.038] INFO -- : [TK85AO9Q] Cannot connect to 127.0.0.1:25 (localhost) (Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25)

^[[32m[worker.4:16217]^[[0m [2020-01-05T09:24:19.902] INFO -- : [K39QTAXN] -> Hostnames: ["localhost"]
^[[32m[worker.4:16217]^[[0m [2020-01-05T09:24:19.902] INFO -- : [K39QTAXN] -> Errors: ["Connection refused - connect(2) for \"localhost\" port 25"]
```

(4) If 25 port is hardcoded on Postal, will be better to set 25 port again and set port foward?

**Comment by willpower232** [comment]
Did you restart Postal after changing the configuration? Can you use `netstat -lnp` to see what ports your Postal is using?

**Comment by franciscopaniskaseker** [comment]
Yes, I restarted.

``'bash
root@s54797:~# netstat -nlptu | egrep -i postal
tcp        0      0 xxx:443       0.0.0.0:*               LISTEN      1654/[postal] fast.
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      1652/[postal] web.1
tcp        0      0 xxx:80        0.0.0.0:*               LISTEN      1654/[postal] fast.
tcp6       0      0 :::2525                 :::*                    LISTEN      1678/[postal] smtp.
root@s54797:~# 
```

The port 2525 is working. The problem is Postal internally is trying to use 25 port even if I configured 2525 port in portal.yml.

**Comment by willpower232** [comment]
I think I understand now. The emails that you're sending, is the domain of the To address also xxxx?

**Comment by franciscopaniskaseker** [comment]
No, the to address is a complete different domain.

**Comment by willpower232** [comment]
I think it sounds like your Postal server is trying to email itself, your messages are getting to the Postal server but since your server isn't available on port 25, it can't send them.

Are you able to use the test message feature in the UI to send emails to a definitely different domain?

**Comment by sahilsunesara** [comment]
can anyone help me with this?
having issue with No SMTP servers were available for domainname.com. Tried mx.mail.domainname.com

https://paste.pics/826RU

**Comment by willpower232** [comment]
@sahilsunesara as per #993 you appear to be experiencing a big delay in your DNS records actually working, please don't ask for help in unrelated issues

**Comment by arunkp** [comment]
Anybody found the issue?
