### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by Nekiono** [postalhq/postal#958]
Hi,
I've tried to setup a postal server from stable following the installation guide.

[nginx config](https://hasteb.in/awipaxid.nginx)
[postal.yml](https://hasteb.in/fotajuko.yaml)

upon trying to create an org, I get this error: https://i.imgur.com/NvWj5mi.jpg

[logs](https://hasteb.in/ewadukus.txt)

I've setup postal before with the same setup, and there hasn't been a new release since then; am I overseeing something obvious?

**Comment by willpower232** [comment]
You could try using your browser developer tools to see if you're actually sending a CSRF token.

Also can you tell us which Ruby version you are using? There have been other issues where people weren't using Ruby 2.3 and had minor UI problems.

**Comment by Nekiono** [comment]
```
~ # ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux-gnu]
```

I've tested this across Firefox, Chrome, Iridium, and Chrome mobile. How do I check if a CSRF token is sent?

**Comment by Nekiono** [comment]
Cookies set are  
__cfduid, experimentation_subject_id, browser_id, cf_use_ob, user_session, _postal_session

**Comment by willpower232** [comment]
The form data should include an `authenticity token`.

The `cf` cookies suggest you are using cloudflare to proxy the UI, are you able to turn this off?

**Comment by Nekiono** [comment]
I'll test without cf, though if it's incompatible with cf, that'd be quite inconvenient.

**Comment by Nekiono** [comment]
Hey @willpower232, I've managed to get it to work by disabling Cloudflare; could you imagine why this issue would arise?

**Comment by willpower232** [comment]
I'm not super familiar with cloudflare but I know that it can do things to the content that get proxied through it so I'd imagine that some unwanted filtering is happening.

It might be possible for you to contact their support about it as it could be as simple as a setting that needs changing in your control panel.
