### ISSUE TITLE
I have installed Postal ony my VPS :)

### ISSUE THREAD

**Issue by evil4u** [postalhq/postal#959]
I have installed Postal to my VPS server and I am noob at this.

Could some one guide me how I can use this.

Where is the manual for the next steps after I have installed Postal?

**Comment by willpower232** [comment]
There isn't really a manual or any written instructions, once you add an "organization" to your Postal then you should be able to see where to add a "mail server" and then the domains you would like to use.

**Comment by evil4u** [comment]
I have done that, I just need the manual so I know what I'm doing. Postal looks good but there's a lot that I don't know and don't understand so please guide me or at least create a manual.

I have created "orgnization" 
I have created a "mail server" 
I have added "domain" and 
I have a valid "DNS" Records.

SO what's next...

**Comment by willpower232** [comment]
You can generate some credentials and include those in your application to allow it to send email through Postal.
