### ISSUE TITLE
SSL not working, TLS is working

### ISSUE THREAD

**Issue by franciscopaniskaseker** [postalhq/postal#961]
Using Ubuntu 16.04 and Postal updated.

When I test ssl configuration:
```bash
apterix@ax:~$ openssl s_client -showcerts -connect xxxxxxx:2525
```

I get:

```bash
No client certificate CA names sent
```

When I test starttls:

```bash
apterix@ax:~$ openssl s_client -starttls smtp -showcerts -connect xxxxxxx:2525
```

I get the certificate.

**My mx domain:**
mx.xxxxxxx.com

**My smtp hostname:**
xxxxxxx.com

My smtp_server config:

```bash
smtp_server:
  port: 2525
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/fast_server.cert
  tls_private_key_path: /opt/postal/config/fast_server.key
  tls_ciphers:
  ssl_version: SSLv23
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14
```
Certificate and key are readable by postal user and actually is the same ssl of fast server service. And is working.

I read the #387 but no idea yet why I can not get SSL working on smtp server.

I read https://github.com/postalhq/postal/commit/67e37b077075a9ae074632a23b5a8e9a162f70f4 commit and seems it get ssl from somewhere, maybe from smtp_server from postal.yml (I did not read the method, but seems pretty obvious).

Does not matter the ssl_version value, it will not work (I did not found any documentation here, but seems this config is about minimal version that will be accepted).

Summarizing, I want to know how to allow ssl connections to smtp server. Starttls is working.

**Comment by willpower232** [comment]
The certificate for the SMTP server is only exposed via STARTTLS so this behaviour is correct.

Your first command was intended to work for websites, i.e. `openssl s_client -showcerts -connect example.com:443`

**Comment by franciscopaniskaseker** [comment]
So Postal is not compatible with softwares that use SSL through STMP service? Only TLS and STARTTLS? Or maybe only STARTTLS...

**Comment by willpower232** [comment]
I think STARTTLS is the only supported encrypted connection method currently, as you can see from https://github.com/postalhq/postal/blob/master/lib/postal/smtp_server/client.rb

This is sufficient for Postal to receive incoming email securely AFAIK. We have not experienced anyone unable to send email our way.

**Comment by kindlychung** [comment]
And a quick test with telnet:
```

EHLO
250-My capabilities are
250 AUTH CRAM-MD5 PLAIN LOGIN
```

`STARTTLS` is not in the list indeed.

**Comment by willpower232** [comment]
@kindlychung please verify that you have turned it on in the configuration and then open a new discussion if you're still having problems rather than replying to long closed issues.
