### ISSUE TITLE
IP Pools

### ISSUE THREAD

**Issue by sbonello** [postalhq/postal#962]
I need some assistance in setting up I.P pools. The following are a list of questions I have.

1. I attached multiple public ips to the box from an infrastructure point of view and they are working fine. 

In my scenario I need two i.ps eg

mail.mydomain.com     with public  ip.  xxx.xxx.xxx.1
mail.mydomain.com     with public  ip.  xxx.xxx.xxx.2

I have setup reverse ip for both domain.

If ips that I setup in the UI of postal should they be the public or the private ips of the machine. I assume they would be the public ip . Can you kindly confirm.
 
What additional dns and configuration setting should I do for the second ip. as I only have two A records to mail.mydomain.com for each ip address

Assistance is highly appreciated

**Comment by willpower232** [comment]
>If ips that I setup in the UI of postal should they be the public or the private ips of the machine. I assume they would be the public ip . Can you kindly confirm.

You should use the IP addresses that your server can see, if you run the `ip a` command on the terminal you should see them. Its likely that you'll only see the private IPs and the public side will be handled by your provider.

>What additional dns and configuration setting should I do for the second ip. as I only have two A records to mail.mydomain.com for each ip address

You only need to set up DNS for the incoming traffic, if you only intend to access your Postal server on the primary IP, you only need the records for that IP.

IP Pools are mostly configured within the UI, have a read of the following: https://github.com/postalhq/postal/wiki/Configuring-IP-Pools

**Comment by sbonello** [comment]
Thanks managed to set them up.

Small question if a server has two ip addresses. Will both ip addresses be used allowing me the double the output ?

**Comment by willpower232** [comment]
If you don't configure IP Pools I believe Postal will use any available one but its still the same server behind it so it won't be "double the output", just double the number of IP addresses to maintain.

**Comment by ivansalloum** [comment]
Hey! Yes, in Postal’s UI, you should use your public IPs. For each IP, make sure you have proper A/AAAA and PTR records, and update your SPF accordingly.

I recently wrote a full guide on setting up IP pools in Postal, including DNS, server config, and using pools properly. Might help clarify things: [How to Use IP Pools for Better Deliverability in Postal](https://ivansalloum.com/how-to-use-ip-pools-in-postal/)

Hope it helps!
