### ISSUE TITLE
Amazon Cloud Front - image urls

### ISSUE THREAD

**Issue by MuratKaragozgil** [postalhq/postal#964]
Hi,

I'm using click & open tracking on postal mail server but i'm getting image urls from aws cloud front. The domain is  https://d178r3dmgae5qs.cloudfront.net.

But im trying to add tracking domains to postal panel, only mail server domains can be selected.
<img width="1168" alt="Screen Shot 2020-01-08 at 14 30 05" src="https://user-images.githubusercontent.com/8644827/71974844-98619e80-3223-11ea-87c0-468337ac7319.png">

How can i solve this problem ?

Thanks,
Murat

**Comment by willpower232** [comment]
Click tracking rewrites the links that can be clicked in the email so the domain needs to be one pointing at the Postal server.

If your images are hosted from CloudFront, then those URLs should be written into the message before it gets to Postal.
