### ISSUE TITLE
Error 500 at email domain verification

### ISSUE THREAD

**Issue by marcsche73** [postalhq/postal#965]
Hello,

I'm facing an Error 500 when I try to verify a Domain via Email. 

Here's a log excerpt:  

/opt/postal/log/rails.log
`ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.517] INFO -- : Started POST "/org/<some_org>/servers/<some_domain>/domains/<some_id>/verify" for <ip> at 2020-01-09 09:53:41 +0100
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.518] INFO -- : Processing by DomainsController#verify as JSON
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.518] INFO -- :   Parameters: {"utf8"=>"✓", "email_address"=>"<some_email>", "commit"=>"Continue", "org_permalink"=>"<some_domain>", "server_id"=>"<some_domain>", "id"=>"<id>
d711"}
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.531] INFO -- :   Rendering app_mailer/verify_domain.text.erb
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.531] INFO -- :   Rendered app_mailer/verify_domain.text.erb (0.1ms)
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.716] INFO -- : Sent mail to <some_email> (184.5ms)
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.717] INFO -- : Completed 500 Internal Server Error in 199ms (ActiveRecord:
 3.4ms)
34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.718] FATAL -- :
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.718] FATAL -- : OpenSSL::SSL::SSLError (hostname "10.15.0.24" does not mat
ch the server certificate):
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.718] FATAL -- :
ESC[34m[web.1:2007]ESC[0m [2020-01-09T09:53:41.718] FATAL -- : app/controllers/domains_controller.rb:81:in verify`

I already checked the hostname, /etc/hosts and nginx server block but didnt found any faulty configurations. 

Any help is greatly appreciated. Thanks in advance. 

Best regards. 

Marc

**Comment by willpower232** [comment]
> OpenSSL::SSL::SSLError (hostname "10.15.0.24" does not mat ch the server certificate):

Are you accessing the UI using your servers IP address instead of a domain name or subdomain?

**Comment by marcsche73** [comment]
No, I accessed the server by its fqdn via https://server.domain.tld. 

What might be of interest: the server has a dual NIC setup, since we want to use clicktracking.

**Comment by willpower232** [comment]
Unless there are any other errors, are you pointing the nginx server block to only one of the two IPs?

**Comment by marcsche73** [comment]
yes right. the current nginx configuration is as follows:

`
server {
# listen was set to listen privateip:80; before
    listen mail.domain.com:80;

    server_name mail.domain.com;

    return 301 https://$host$request_uri;
}

server {
# listen was set to listen privateip:443; before    
listen mail.domain.com:443 ssl;

    root /opt/postal/app/public;
    server_name mail.domain.com;
    ssl_certificate      /etc/letsencrypt/live/mail.domain.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/mail.domain.com/privkey.pem;

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }
}
`
this are the current listeners, where 10.15.0.24 is the web ui interface and 10.15.0.25 is for the clicktracking configuration. 
`
netstat -tulpn 
tcp        0      0 10.15.0.24:80           0.0.0.0:*               LISTEN      4139/nginx -g daemo
tcp        0      0 10.15.0.25:80           0.0.0.0:*               LISTEN      2009/[postal] fast.
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1428/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1495/sshd
tcp        0      0 10.15.0.24:443          0.0.0.0:*               LISTEN      4139/nginx -g daemo
tcp        0      0 10.15.0.25:443          0.0.0.0:*               LISTEN      2009/[postal] fast.
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      2007/[postal] web.1
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1273/beam.smp
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1701/mysqld
tcp6       0      0 :::4369                 :::*                    LISTEN      1428/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      1495/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      2017/[postal] smtp.
tcp6       0      0 :::5672                 :::*                    LISTEN      1273/beam.smp
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1022/dhclient
`

any ideas? 

thanks for your support.

**Comment by willpower232** [comment]
Having searched for the error message, it looks like its coming from the attempt to email you the verification information.

Presuming you have setup your Postal to use itself for email, have you applied your letsencrypt certificates to the SMTP server config?
