### ISSUE TITLE
Domain Verification by DNS txt entry over CNAME

### ISSUE THREAD

**Issue by ingo-lorenz** [postalhq/postal#966]
Hi,

Can someone explain why a verification of a TXT record (postal-verification xxx...) does not work if the domain has only one CNAME record and the TXT record exists in the target domain?

Many thanks in advance.

Bye

Ingo

**Comment by willpower232** [comment]
see #868

**Comment by ingo-lorenz** [comment]
Yes hole zone, but the record is shown as invalid in postal. 

https://www.whatsmydns.net/ shows the correct value.

**Comment by willpower232** [comment]
I am not sure whether Postal would be able to follow the CNAME of the whole domain to be honest, sounds like it is not.

Do you know enough ruby to investigate what Postal sees or can you share the domain you're using?
