### ISSUE TITLE
Mail sending going in pending after enabling the ip pool

### ISSUE THREAD

**Issue by Rishu032** [postalhq/postal#973]
Hi Team, 

I have install & configure the postal properly. I have tested mail befor enabling the ip pool. It was sending properly. Once I have enabled the ip pool, sending mails are going in pending. 

Can anyone suggest me on this. i'm using the ip's for ip pool from another vps(cloud provider) & my postal server on ovh vps. 

![image](https://user-images.githubusercontent.com/44774765/72679059-945e3800-3ad1-11ea-8027-13eff9c7c688.png)

![image](https://user-images.githubusercontent.com/44774765/72679093-dd15f100-3ad1-11ea-885b-cb662b50a198.png)

**Comment by Rishu032** [comment]
@willpower232 Can you suggest on this?

**Comment by willpower232** [comment]
> i'm using the ip's for ip pool from another vps(cloud provider) & my postal server on ovh vps.

If you run the `ip a` command on your server can you see the IP addresses you've told the pool about?

**Comment by Rishu032** [comment]
Yes, It has been assigned properly. I have the added ip in the interface.

![image](https://user-images.githubusercontent.com/44774765/73119990-f82fa780-3f8e-11ea-8536-5bdbd9752021.png)

**Comment by willpower232** [comment]
Can you share the output of `netstat lnp` please?

**Comment by manjunathraju** [comment]
> Yes, It has been assigned properly. I have the added ip in the interface.
> 
> ![image](https://user-images.githubusercontent.com/44774765/73119990-f82fa780-3f8e-11ea-8536-5bdbd9752021.png)

Hi you have to change the subnet mask also there like: 
158.69.114.246/24 ------------- 158.69.114.246/32
