### ISSUE TITLE
Using redirect modifier on spf records.

### ISSUE THREAD

**Issue by alnalda** [postalhq/postal#976]
Hi, i've added a domain and multiple subdomains to the domains list. 
All of them are configured but to avoid overload all the subdomains SPF are redirected to the main one. 
Example:
MAINDOMAIN.COM (`v=spf1 a mx include:POSTALDOMAIN ~all`)

SUBDOMAIN.MAINDOMAIN.COM (`v=spf1 redirect=MAINDOMAIN.COM`)

With this solution, I'm not able to verify the subdomains and checking the code behind (https://github.com/postalhq/postal/blob/master/app/models/domain/dns_checks.rb#L44) i think it can't get a success as it's looking for `include:POSTALDOMAIN` on the returned records. 

Do you know if there is any possibility to use _redirect_ modifier to verify the spf records?

Thanks for your time ;)

**Comment by willpower232** [comment]
If the domains are verified then you should still be able to make use of the domain regardless of the validity of the SPF record according to Postal.

Unfortunately, it is not currently possible for Postal to validate more complex situations at the minute but as long as you're sure the records are valid elsewhere, you should not have a problem.

mxtoolbox.com has an SPF checker which can detect multiple levels of records which might help you here.
