### ISSUE TITLE
Configuration for SSL & TLS and also HTTPS Connection Documentation

### ISSUE THREAD

**Issue by arifuzzaman35** [postalhq/postal#977]
Hello i need to configuration documentation for advanced configuration like as all incoming & outgoing port with https connection .i will highly request to you plz help me and sent me documentation for proper setup postal if my domain example.com so postal.yml confiration should be what with SSL ,TLS configuration and also https connection 

Thanks

**Comment by arifuzzaman35** [comment]
when i installed certbot and configured ssl certificated then web panel not fully loaded only view text mode please check screen short
https://drive.google.com/file/d/1DB2hPt-Dso8IFtFBzccgnJVnAJopKuRH/view?usp=sharing

**Comment by willpower232** [comment]
It looks like your browser wasn't able to load the assets for the webpage which might be related to SSL but is more likely to be related to the files not being generated properly.

Running the following commands should verify that the assets are built properly:
```
postal bundle /opt/postal/vendor/bundle
postal upgrade
```

**Comment by arifuzzaman35** [comment]
postal bundle /opt/postal/vendor/bundle                     (show messages)
Bundle complete! 41 Gemfile dependencies, 85 gems now installed.
Gems in the groups development and assets were not installed.
Bundled gems are installed into `/opt/postal/vendor/bundle`

root@mail:~# postal upgrade
Migrating database
root@mail:~#
but didi not load full panel 

check link
https://drive.google.com/file/d/1CfBvfEU8n6wErPctWPh4sfNJ-bg2qQ0e/view?usp=sharing

**Comment by willpower232** [comment]
I can see you're getting nginx not found errors, can you share your nginx configuration?
