### ISSUE TITLE
Use with Apache

### ISSUE THREAD

**Issue by siliconCupcake** [postalhq/postal#978]
I have successfully installed postal on my server, but would like to use it with apache instead of nginx since I already have a bunch of other stuff running on apache. Any help on how to do so would be great.

**Comment by iammattmartin** [comment]
Nginx is the expected server but you can just follow the usual guide found at https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html for setting up Apache as a reverse proxy.

Probably a bit outside the scope of any support as custom to you.

**Comment by willpower232** [comment]
Firstly, if you have things running on your server other than Postal and don't have enough RAM for it all, you're likely to run into performance problems. It is recommended to run Postal on a separate server entirely.

For your question, `ProxyPass` as highlighted above may well be sufficient for your needs.
