### ISSUE TITLE
Postal Database

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#980]
When I created the database is created two databases, 

1 Postal
2. Postal-server-1

I don't know how the second one got created? 

Is this done automatically?

**Comment by zeba121** [comment]
when you have created a mail server from the frontend then the Postal create a database for a particular user.
when you have created the second user then the postal create again a new database for the second user.

**Comment by willpower232** [comment]
Each "mail server" in Postal has its own database. This allows for completely separate management of email messages amongst other things.

If you have several additional databases, the database called "postal" should have a table which lists the "mail servers" it knows and you can match each database up that way.
