### ISSUE TITLE
"We're sorry, but something went wrong - If you are the application owner, check the logs for more informations". 

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#981]
While logged into the Postal UI clicking the "queued messages" link results in a "We're sorry, but something went wrong - If you are the application owner, check the logs for more informations". 
 
The error from the rails.log is:
 
INFO -- : Completed 500 Internal Server Error in 117ms (ActiveRecord: 51.2ms)
FATAL -- :   
FATAL -- : ActionView::Template::Error (No message found matching provided query {:id=>90343}):
FATAL -- :     1: %ul.messageList
    2:   - for message in messages
    3:     - if message.is_a?(QueuedMessage)
    4:       - message = message.message
    5:     %li.messageList__message
    6:       = link_to organization_server_message_path(organization, @server, message.id), :class => 'messageList__link' do
    7:         .messageList__details{:class => 'messageList__details--' + message.scope}
FATAL -- :   
FATAL -- : lib/postal/message_db/message.rb:13:in `find_one'
lib/postal/message_db/database.rb:36:in `message'
app/models/concerns/has_message.rb:8:in `message'
app/views/messages/_list.html.haml:4:in `block in _app_views_messages__list_html_haml__4169117333314457771_49077920'
app/views/messages/_list.html.haml:2:in `each'
app/views/messages/_list.html.haml:2:in `_app_views_messages__list_html_haml__4169117333314457771_49077920'
app/views/servers/queue.html.haml:21:in `_app_views_servers_queue_html_haml___1236125962400471721_70122255952860'

**Comment by willpower232** [comment]
>No message found matching provided query {:id=>90343}

Does this still happen after a refresh? It sounds like it might be related to #521

**Comment by nenominal** [comment]
I have the same issue, I'm running 1.0.0-1ef7dbd67e-stable.
The issue appeared after update, not clean install, the servers_controller.rb it's the same as in [#521](https://github.com/postalhq/postal/issues/521)

**Comment by willpower232** [comment]
This particular problem is database related. Do you still get it with a refresh?

**Comment by nenominal** [comment]
@willpower232 : what do you mean by *a refresh*? A db server daemon restart..?

**Comment by willpower232** [comment]
Presumably you encountered this problem clicking through the UI so a refresh of the browser page might clear up what is happening

**Comment by nenominal** [comment]
Ah, I see :). I have tried Chrome/Firefox/incognito before searching for some similar error, first I thought that can be an issue with the browser session/cache as well.
