### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: unsupported protocol

### ISSUE THREAD

**Issue by cinco** [postalhq/postal#982]
Hi!

Can the Postal delivery messages to a destination server that listens only on port 587?

My server is delivering to hundreds of other destinations, but for a specific destination it receives this error:

> SSL_connect returned=1 errno=0 state=error: unsupported protocol
> Support Ref: UJOXUZAT

**Comment by willpower232** [comment]
Looking at lib/postal/smtp_sender.rb, I don't think this is possible. Do you know the recipient or their email system directly? They might have a server problem if they have the standard port 25 open without it being specifically setup for SMTP.

**Comment by cinco** [comment]
I cant connection with recipient server using TLS?

**Comment by cinco** [comment]
> Looking at lib/postal/smtp_sender.rb, I don't think this is possible. Do you know the recipient or their email system directly? They might have a server problem if they have the standard port 25 open without it being specifically setup for SMTP.

I cant connection with recipient server using TLS?

Because the recipient and their email system accepting  only connections with TLS.
How make Postal using TLS too?

**Comment by willpower232** [comment]
It looks like Postal connects over 25 and then handles securing the connection separately rather than connecting to the port https://github.com/postalhq/postal/blob/a66b94b228204fa9f389191825b4e0e7fdff754a/lib/postal/smtp_sender.rb#L27-L29

**Comment by acsfer** [comment]
I have the same error with `smtp-in.orange.fr`
Telnet connects fine:
```

telnet smtp-in.orange.fr 25
Trying 80.12.242.9...
Connected to smtp-in.orange.fr.
Escape character is '^]'.
220 mwinf5c38 ME ESMTP server ready

telnet smtp-in.orange.fr 587
Trying 80.12.242.9...
Connected to smtp-in.orange.fr.
Escape character is '^]'.
220 mwinf5d38 ME ESMTP server ready
```

**Comment by saschaarthur** [comment]
running into exact the same issue:

# openssl version
OpenSSL 1.1.1d  10 Sep 2019

# openssl s_client -connect smtp-in.orange.fr:25 -starttls smtp  | grep verify
140281472566400:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../ssl/statem/statem_lib.c:1929:

**Comment by acsfer** [comment]
@saschaarthur problem is OpenSSL version.
You must downgrade to OpenSSL 1.0.2 to support old protocol versions required by some servers.

```
# openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

Once done:
```
# openssl s_client -connect smtp-in.orange.fr:25 -starttls smtp  | grep verify
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = FR, L = Paris, O = Orange, OU = Orange, CN = smtp-in.orange.fr
verify return:1
250 OK
```

**Comment by saschaarthur** [comment]
@acsfer fully agree with you that downgrade would solve the issue about deliver possibility to orange-fr.
(btw the poodle issue, which this whole thing is about is from 2014. Seems the didnt upgrade their servers yet, which is a shame..)

Anyways i strongly do not recommend to downgrade openssl to this very old version, because you open your whole system for a lot of security issues (not only for postal).

More helpful would be an optional option in postal, which allows to deliver "unsafe" emails.

Adding the (-tls1) option in latest ssl would do the trick.

```
# openssl version
OpenSSL 1.1.1d  10 Sep 2019

# openssl s_client -connect smtp-in.orange.fr:25 -starttls smtp -tls1 | grep verify
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = FR, L = Paris, O = Orange, OU = Orange, CN = smtp-in.orange.fr
verify return:1
140183533495424:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2150:
```

As you can see theres another issue ("dh key too small") with orange.fr (someone should really get fired there..). A second optional for ignoring to weak DH keys should be added as well to postal.

The fully "unsafe" version for orange.fr would then be:
```
# openssl s_client -connect smtp-in.orange.fr:25 -starttls smtp -tls1 --cipher 'DEFAULT:!DH' | grep verify
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = FR, L = Paris, O = Orange, OU = Orange, CN = smtp-in.orange.fr
verify return:1
250 OK
```

Having two options bringing this features, would be awesome !

**Comment by acsfer** [comment]
Agree, those options would be the best...option.
Maybe @willpower232 can reopen this regarding that "enhancement"?

In our case, blocking thousands of recipients was not an option so we've installed and older OpenSSL version and bound it to Ruby with something like https://stackoverflow.com/questions/30741367/ruby-using-wrong-version-of-openssl#answer-31348116

**Comment by willpower232** [comment]
This sounds similar to #878

**Comment by saschaarthur** [comment]
Well it is close.. Both SSL-DH problems.

About the DH to small thing.. 
Its the 'default strictness' of newer open-SSL libs.

The DH key/curve (orange.fr) offers to our client (postal) is to small / deprecated / unsecure.

Other SMTP-Servers, which are offering secure DH-Keys/Curves are not affected.

**Comment by saschaarthur** [comment]
our fix for this issue: 

# downgrade ssl level to 1
RUN sed -i -e "s/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/" /etc/ssl/openssl.cnf

**Comment by saschaarthur** [comment]
The next thing youre fighting against (orange.fr): 

`
140523061965952:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../ssl/statem/statem_lib.c:1929:
`

fixable with

```
# downgrade tls minimum to 1.0
RUN sed -i -e "s/TLSv1.2/TLSv1.0/" /etc/ssl/openssl.cnf
```

I strongly do not recommend doing this on your system, but sadly we have a lot of customers with those emails and orange.fr is not reacting on anything.

**Comment by acsfer** [comment]
@saschaarthur may I ask if this still works for you today?

```
# openssl version
OpenSSL 1.1.1f  31 Mar 2020

# openssl s_client -connect smtp-in.orange.fr:25 -starttls smtp  | grep verify
140167060710720:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../ssl/statem/statem_lib.c:1941:
```

**Comment by olegbliaher** [comment]
@saschaarthur I've managed to solve it for my organization, without messing around with openssl on the server. Here's the commit: https://github.com/olegbliaher/postal/commit/25b2585c4d95575de26196d75049e4cb459df505

@willpower232 Is this something that could be implemented in Postal?

**Comment by willpower232** [comment]
@olegbliaher I don't hate the idea but its not my say as to whether it gets implemented, can you make a PR in this repo for it so it can be reviewed?
