### ISSUE TITLE
Not sending all emails

### ISSUE THREAD

**Issue by djmuttart** [postalhq/postal#983]
Hello, 

I'm trying to send 1800 emails every few days or sometimes a couple of times a day. Recently I've received messages that some people are not receiving emails any longer. When I check in postal outgoing messages, my emails stop sending around 900 or 1000. 

I have 8 workers set and have always. I've checked log files and database log files and cant' see any reason for this not work. Does anyone have any ideas? 

I'm not an expert with Postal Mail so anything you can provide in the way of log files to check, or things to run or settings to change, please advise.

Thanks

**Comment by navinp** [comment]
Hello,

Do you have an hour limit in place?

**Comment by djmuttart** [comment]
Hello. 

If I do, it's set by default somewhere. Where would I look to see if there is a limit set? 
Thanks.

**Comment by navinp** [comment]
Hello,

Check Settings > Advanced Settings > Send limit

**Comment by willpower232** [comment]
If it isn't send limit related, you could have a look at one of the messages that didn't send and see what it says on the right hand side where other messages say that they sent.
