### ISSUE TITLE
IP Pools, what's the DNS requirement?

### ISSUE THREAD

**Issue by navinp** [postalhq/postal#984]
Hello,

If I have Postal installed on domain.com and I want to add a new IP to the IP pool.

I went to domain.com/ip_pools and created an IP pool, after that opened an organization, and assigned it to that IP pool.

After that send Test message via .../message/new/ but these messages are not going out.

- Do I need to add a few records for this new IP address? Like a-records, txt records etc? Similar to the main Postal install? 

- Do I need to have Postal installed on this new IP (machine)?

If I do `ip a,` I get an output, **but** I don't see the IP there ...

**Comment by zeba121** [comment]
Hello @navinp,

Firstly, you need to Bind IPs on the server.
Second, Add A-records for the IPs.
Third, you need to create an IP pool and assigned your mail server.
Then you will be sent your emails properly.

**Comment by navinp** [comment]
Hello,

I assume I can just add the IP by comma separation in the config file? 

Will try. Thanks

**Comment by navinp** [comment]
Adding 2 IP addresses, separated by a comma didn't do it for me.

I tried this format:

>   enabled: true
  bind_address: 
    - 1.2.3.4
    - ip6 address here
    - 5.6.7.8
    - ip6 address here

**Comment by zeba121** [comment]
Can you share the output of ifconfig please?

**Comment by zeba121** [comment]
Hello @navinp 

If your VPS Server ethernet is ens3 or eth0.
then you can use this formate according to your ethernets type:-

auto eth0:1
iface eth0:1 inet static
name Ethernet alias LAN card
address 1.2.3.4

auto eth0:2
iface eth0:2 inet static
name Ethernet alias LAN card
address 4.5.6.7

auto ens3:1
iface ens3:1 inet static
name Ethernet alias LAN card
address 2.3.4.5

auto ens3:2
iface ens3:2 inet static
name Ethernet alias LAN card
address 3.4.5.6

**Comment by willpower232** [comment]
The `bind_address` config setting is for the click tracking so isn't related to IP Pools.

I believe that for IP Pools, you need the IP addresses available for your server to use and then you configure them in the UI only.

As for DNS, you should make sure there is some kind of reverse DNS record set up for each IP address otherwise you may find messages sent using them go to spam.

With many server providers, you will have to configure the additional IP addresses manually in your server so you should follow their instructions for adding additional IP addresses. Once they appear in `ip a` you should be able to use them in your IP Pools.

**Comment by navinp** [comment]
Hello @zeba121 thanks for your help

> Hello @navinp
> 
> If your VPS Server ethernet is **ens3 or eth0**.
> then you can use this formate according to your ethernets type:-
> 
> **If your ethernet is eth0 you can use this format:-**
> 
> auto eth0:1
> iface eth0:1 inet static
> name Ethernet alias LAN card
> address 1.2.3.4
> 
> auto eth0:2
> iface eth0:2 inet static
> name Ethernet alias LAN card
> address 4.5.6.7
> 
> **If your ethernet is ens3 you can use this format:-**
> 
> auto ens3:1
> iface ens3:1 inet static
> name Ethernet alias LAN card
> address 2.3.4.5
> 
> auto ens3:2
> iface ens3:2 inet static
> name Ethernet alias LAN card
> address 3.4.5.6

Hello,

I actually don't know how or where I should use this information...

My server is hosted with DigitalOcean. 

> root@domain:~# **ip a**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group defaul                                                                                        t qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP gr                                                                                        oup default qlen 1000
    link/ether da:45:74:cd:ff:f8 brd ff:ff:ff:ff:ff:ff
    inet 159.65.159.168/20 brd 159.65.159.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.47.0.9/16 brd 10.47.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2400:6180:100:d0::7f7:5001/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::d845:74ff:fecd:fff8/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP gr                                                                                        oup default qlen 1000
    link/ether 32:be:b7:7c:cb:0b brd ff:ff:ff:ff:ff:ff
    inet 10.139.40.235/16 brd 10.139.255.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::30be:b7ff:fe7c:cb0b/64 scope link
       valid_lft forever preferred_lft forever

**Comment by navinp** [comment]
With the reverse DNS I assume you mean PTR - records?

Also if I understand correctly, I do not have to touch the POSTAL.YML file.

If I check using online tools the reverse DNS, it is showing the domain and IP address

IP address < == > domain 

So that is setup correctly.

It's just whenever I add an org to an IP pool, messages are held as **Pending** and 

**Spam Status
NOT CHECKED**

> The `bind_address` config setting is for the click tracking so isn't related to IP Pools.
> 
> I believe that for IP Pools, you need the IP addresses available for your server to use and then you configure them in the UI only.
> 
> As for DNS, you should make sure there is some kind of reverse DNS record set up for each IP address otherwise you may find messages sent using them go to spam.
> 
> With many server providers, you will have to configure the additional IP addresses manually in your server so you should follow their instructions for adding additional IP addresses. Once they appear in `ip a` you should be able to use them in your IP Pools.

**Comment by navinp** [comment]
How do I do the "binding"?

> Hello @navinp,
> 
> Firstly, you need to Bind IPs on the server.
> Second, Add A-records for the IPs.
> Third, you need to create an IP pool and assigned your mail server.
> Then you will be sent your emails properly.

**Comment by zeba121** [comment]
> How do I do the "binding"?
> 
> > Hello @navinp,
> > Firstly, you need to Bind IPs on the server.
> > Second, Add A-records for the IPs.
> > Third, you need to create an IP pool and assigned your mail server.
> > Then you will be sent your emails properly.

If your server **ethernet** is **eth0** you can use this format:-

auto eth0:1
iface eth0:1 inet static
name Ethernet alias LAN card
address 1.2.3.4

auto eth0:2
iface eth0:2 inet static
name Ethernet alias LAN card
address 4.5.6.7

If your server **ethernet** is **ens3** you can use this format:-

auto ens3:1
iface ens3:1 inet static
name Ethernet alias LAN card
address 2.3.4.5

auto ens3:2
iface ens3:2 inet static
name Ethernet alias LAN card
address 3.4.5.6
