### ISSUE TITLE
Hide origin IP from outbound message headers?

### ISSUE THREAD

**Issue by juouy** [postalhq/postal#987]
Currently when postal is sending outgoing message it attaches following headers:
`
Received: from api (xxxx.xxx.com [IP_THAT_CALLED_API]) by Postal with HTTP; Tue, 04 Feb 2020 04:07:09 +0000`

This is often security risk for people running their servers behind services like cloudflare who want to prevent ip disclosure. IP disclosure often results in DDOS attacks.

Is it possible to disable this header from being sent?

**Comment by juouy** [comment]
I had to manually remove it from 2 files:

```
For SMTP Server:

lib/postal/smtp_server/client.rb

For HTTP:

app/models/outgoing_message_prototype.rb 
```

I hope there will be a config switch in future to hide the IP's from being disclosed.

I dont think that services like MailGun or similar are disclosing customers servers IP addresses likePostal does.

**Comment by willpower232** [comment]
I can understand your use case but this header is part of how email works and I am not sure how bad it would be to fully remove it. There might be an alternative but it would require more research.

**Comment by iammattmartin** [comment]
Probably similar to #86 for the same reasons.

**Comment by iammattmartin** [comment]
Also a dupe of #457 maybe.

**Comment by willpower232** [comment]
Ah yes I knew there was a distant bell ringing in my head. Since #457 is open and not commented upon officially, I'll close this for now.
