### ISSUE TITLE
IP reserve 

### ISSUE THREAD

**Issue by sahilsunesara** [postalhq/postal#989]
Hi

I have 10 IP... do i have to reserver 

mail.domainname.com   19.xx.xx.01
mail1.domainname.com   19.xx.xx.02
mail2.domainname.com   19.xx.xx.03

or i have to reserve with

mail.domainname.com   19.xx.xx.01
mail.domainname.com   19.xx.xx.02
mail.domainname.com   19.xx.xx.03

hope to see your reply soon

Thanks

**Comment by willpower232** [comment]
As long as Postal is listening on and can use all of those IP addresses, I don't think there is a problem doing it either way apart from cosmetic preference.

If you are making use of IP Pools to specifically send email for a certain account with a specific IP address then you may prefer to use a different domain name for each reverse DNS.

**Comment by sahilsunesara** [comment]
Please check the image... i have added IP into Postal IP Pool... could you please tell me is that the way is correct to update or it's wrong?

https://paste.pics/297c7640723c69f402195dd927703790
