### ISSUE TITLE
OpenSSL SMTP service connect failure. "dh key too small"

### ISSUE THREAD

**Issue by juouy** [postalhq/postal#990]
Hi,

I'm having trouble sending emails through smtp port, due to "dh key being too small" for modern openssl versions. Tested on newest debian.

Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

```
cat /etc/issue

Debian GNU/Linux 10 \n \l

OpenSSL> version
OpenSSL 1.1.1d  10 Sep 2019
OpenSSL> 
```

```
root@server: openssl s_client -connect mailserver.mydomain.com:25 -starttls smtp


CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = mailserver.mydomain.com
verify return:1
**140103841752192:error:141A318A:SSL routines:tls_process_ske_dhe:**dh key too small**:../ssl/statem/statem_clnt.c:2150:**
---

```

Seems like some major issue, it happens on newer openssl version. 
Does Postal use big enough DH keys?

The configuration we tested this on is very very default one. With clean version of Debian 10 + openssl. Should be very easy to reproduce.

**Comment by willpower232** [comment]
Have a look at #943 and #878 and reply again if they don't cover what you're seeing
