### ISSUE TITLE
Email Delivery issue

### ISSUE THREAD

**Issue by bpareek9694** [postalhq/postal#991]
Hi Community,

I install postal on my dedicate server.

I've tried to send a bulk mail on this server.

some email ids are sent, but some mail id's mail store in the queue and held messages.
after this, all messages are stored in the queue and held message, also message rate showing 0.00/minutes

After I can flush the queue and held messages.

the mail will be perfectly delivered. and the message rate will be increased.

Guys, Please Help.

Thanks

**Comment by willpower232** [comment]
Have you got a send limit in place? Have a look under Settings > Advanced Settings > Send limit

**Comment by bpareek9694** [comment]
@willpower232 Thanks For Replay

I'm not set any limit on sending mail.

My issue is that,
for example, when I send 100 mail on the postal installed server.

the 80% mail is successfully delivered but the 20% mail is store in held and queue messages.

After than when I send more mail without a clear queue and held a message.
all 100% mail is store in the queue and held message not a single mail is sent.
also, I can check the message rate is zero.
Please check below screenshot,
https://prnt.sc/qz9q5v

after that when I clear all queue and held message.

After that send more mail, all 100% mail is delivered successfully.
and during this message rate will be increased.

Please suggest me that how can I send a with your postal application, without any interruption.

**Comment by bpareek9694** [comment]
We're expecting for getting a reply soon.

**Comment by willpower232** [comment]
That is a very large amount of email messages, can you share the output of `postal status`?

**Comment by bpareek9694** [comment]
@willpower232 Thanks For Reply

quantity doesn't matter.
I'm sending 1k mail in the same server but the issue will be the same.

below are the postal status.

`root@ns101022:~# postal status
Procodile Version   1.0.22
Application Root    /opt/postal/app
Supervisor PID      5316
Started             2020-02-05 02:12:40 -0500

|| web
|| Quantity            1
|| Command             bundle exec puma -C config/puma.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => web.1            Running      05/02/2020   pid:5322     respawns:0      port:-        tag:-

|| worker
|| Quantity            30
|| Command             bundle exec ruby script/worker.rb
|| Respawning          5 every 3600 seconds
|| Restart mode        start-term
|| Log path            none specified
|| Address/Port        none
|| => worker.1         Running      05/02/2020   pid:15292    respawns:0      port:-        tag:-
|| => worker.2         Running      05/02/2020   pid:12578    respawns:0      port:-        tag:-
|| => worker.3         Running      05/02/2020   pid:12580    respawns:0      port:-        tag:-
|| => worker.4         Running      05/02/2020   pid:15294    respawns:0      port:-        tag:-
|| => worker.5         Running      05/02/2020   pid:12584    respawns:0      port:-        tag:-
|| => worker.6         Running      05/02/2020   pid:14927    respawns:0      port:-        tag:-
|| => worker.7         Running      05/02/2020   pid:12588    respawns:0      port:-        tag:-
|| => worker.8         Running      05/02/2020   pid:15654    respawns:0      port:-        tag:-
|| => worker.9         Running      05/02/2020   pid:15656    respawns:0      port:-        tag:-
|| => worker.10        Running      05/02/2020   pid:15300    respawns:0      port:-        tag:-
|| => worker.11        Running      05/02/2020   pid:12605    respawns:0      port:-        tag:-
|| => worker.12        Running      05/02/2020   pid:15303    respawns:0      port:-        tag:-
|| => worker.13        Running      05/02/2020   pid:14935    respawns:0      port:-        tag:-
|| => worker.14        Running      05/02/2020   pid:12614    respawns:0      port:-        tag:-
|| => worker.15        Running      05/02/2020   pid:15659    respawns:0      port:-        tag:-
|| => worker.16        Running      05/02/2020   pid:15309    respawns:0      port:-        tag:-
|| => worker.17        Running      05/02/2020   pid:12625    respawns:0      port:-        tag:-
|| => worker.18        Running      05/02/2020   pid:15315    respawns:0      port:-        tag:-
|| => worker.19        Running      05/02/2020   pid:12632    respawns:0      port:-        tag:-
|| => worker.20        Running      05/02/2020   pid:15662    respawns:0      port:-        tag:-
|| => worker.21        Running      05/02/2020   pid:15665    respawns:0      port:-        tag:-
|| => worker.22        Running      05/02/2020   pid:12645    respawns:0      port:-        tag:-
|| => worker.23        Running      05/02/2020   pid:12648    respawns:0      port:-        tag:-
|| => worker.24        Running      05/02/2020   pid:15319    respawns:0      port:-        tag:-
|| => worker.25        Running      05/02/2020   pid:12656    respawns:0      port:-        tag:-
|| => worker.26        Running      05/02/2020   pid:15668    respawns:0      port:-        tag:-
|| => worker.27        Running      05/02/2020   pid:15324    respawns:0      port:-        tag:-
|| => worker.28        Running      05/02/2020   pid:12667    respawns:0      port:-        tag:-
|| => worker.29        Running      05/02/2020   pid:12670    respawns:0      port:-        tag:-
|| => worker.30        Running      05/02/2020   pid:12673    respawns:0      port:-        tag:-

|| cron
|| Quantity            1
|| Command             bundle exec rake postal:cron
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => cron.1           Running      05/02/2020   pid:5432     respawns:0      port:-        tag:-

|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Running      05/02/2020   pid:5435     respawns:0      port:-        tag:-

|| requeuer
|| Quantity            1
|| Command             bundle exec rake postal:requeuer
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => requeuer.1       Running      05/02/2020   pid:15330    respawns:0      port:-        tag:-`

**Comment by bpareek9694** [comment]
@willpower232 We're expecting for getting a reply soon.

**Comment by willpower232** [comment]
The held messages imply that the receipients are having problems receiving your email so those will have to be addressed directly.

The queued messages may well be locked by an older Postal process if it got restarted somehow. You could have a go at https://github.com/postalhq/postal/issues/717#issuecomment-451656179 to see if that gets the messages out of the queue.

**Comment by bpareek9694** [comment]
@willpower232,

Thanks for providing me #717 (comment),
We're doing this before raised ticket.

But the issue are same


Please Help!!

**Comment by willpower232** [comment]
Have you been able to clear the whole queue yet? If you clear the locking fields as suggested, does that help or is there anything else in that table which needs changing too?
