### ISSUE TITLE
Cannot send the confirmation email using the data you provided.

### ISSUE THREAD

**Issue by digitalcooperatives** [postalhq/postal#994]
Here is a transcript of the error message:
Connection could not be established with host postal.example.com [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]
Log data:
++ Starting Swift_SmtpTransport
!! Connection could not be established with host postal.example.com [php_network_getaddresses: getaddrinfo failed: Name or service not known #0] (code: 0)

I also tried my server as server.utubeguru.net, utubeguru.net but failed

**Comment by willpower232** [comment]
Have you put the correct domain in the config file and restarted Postal to apply it?

**Comment by digitalcooperatives** [comment]
Yes added the correct domain and it’s active. I did not restarted postal. How can I do that can you send me the query to restart the postal?
I have shared the screenshot

Thank you.
Best regards.

CEO – Digital Co-operatives

**Comment by willpower232** [comment]
You would need to run `postal restart` from the terminal if you haven't done anything special like systemd.

**Comment by digitalcooperatives** [comment]
Hello. 
Thank you for your reply.
I am configuring it with mailwizz. I also tried on a mail client application but it did not work. Let me restart it and try it again.

Thank you.
Best regards.

CEO – Digital Co-operatives

**Comment by digitalcooperatives** [comment]
Hi
I restarted it but the issue is same I have attached the screenshots of mailwizz.
Can you help me remotely?
Through teamviewer or anydesk plz.
I am facing issues with that. 

Thank you.
Best regards.

CEO – Digital Co-operatives

**Comment by digitalcooperatives** [comment]
Hello. 
Thank you for your reply.
I am configuring it with mailwizz. I also tried on a mail client application but it did not work. Let me restart it and try it again.

Thank you.
Best regards.

CEO – Digital Co-operatives


Thank you.
Best regards.

CEO – Digital Co-operatives

**Comment by digitalcooperatives** [comment]
Hi
I also used mail client and it’s not sending email. It’s giving a warning  “ The server has rejected your msg because you have not authenticated yourself.”

Thank you.
Best regards.

CEO – Digital Co-operatives

**Comment by willpower232** [comment]
On the credentials page of the server you are trying to use within Postal you should see a link `Read more about sending outgoing e-mails` which explains what your username should be.
