### ISSUE TITLE
Using IPv6 Only

### ISSUE THREAD

**Issue by devallareddyb** [postalhq/postal#995]
Is there any possible to use only IPv6 for some domains like gmail ?

I tried to add only ipv6 but getting error like i need to attach ipv4 also.

**Comment by willpower232** [comment]
Unfortunately a significant portion of the internet still uses IPv4 so unless you're only sending emails to gmail, you will have some problems without IPv4.

If Postal sees AAAA records and has an IPv6 enabled connection, it will be able to make use of that but you can't guarantee that will always be the case AFAICT.
