### ISSUE TITLE
Fixnum is deprecated warning

### ISSUE THREAD

**Issue by willpower232** [postalhq/postal#996]
```
/opt/postal/app/lib/postal/message_db/message.rb:9: warning: constant ::Fixnum is deprecated
```

https://github.com/postalhq/postal/blob/a66b94b228204fa9f389191825b4e0e7fdff754a/lib/postal/message_db/message.rb#L9

Doesn't seem to prevent anything from working but probably worth resolving. Found with Ruby 2.6 so presumably a recent thing.

**Comment by dragoangel** [comment]
ruby 2.5.5-p157 also has this
