### ISSUE TITLE
Upgrading Postal

### ISSUE THREAD

**Issue by teemurainio** [postalhq/postal#998]
I have installed Postal from package as that is the default installation method in the documentation. However by looking at the latest stable and beta links it seems if I'm not incorrect the stable version is bit less than year old and beta is even older?

Would it be possible to upgrade the packages? 

Alternatively is there instructions how to convert existing package based installation to git?

**Comment by willpower232** [comment]
Packaging is handled by @adamcooke and atech so its down to them. There are more than a few useful PRs outstanding so it would be better to get those merged before a release.

Using git-based tends to be more complex as you could have made changes to the files which could conflict with changes from the repo so its easier for most to stick with packages.

Postal is mostly stable so you shouldn't have any major problems with the latest releases code, do make an issue or reply if you need more information or get stuck somewhere.
